### ISSUE TITLE
既存リンクの選択（New Playground）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#100]
#87 を受けてのIssueです。

［シーン］タブから関連するリンクを選択できるようにします。

**Comment by snext1220** [comment]
［リンク］選択ボックスを追加し、そのシーンからのリンクを選択できるようにしました（現時点でGitHubのみ反映）。ご確認ください。

**Comment by cocotori** [comment]
この機能の確認方法がよくわからなかったのですが、

https://www.web-deli.com/sorcerian/text/playground/

こちらのplay groundでは確認できないのでしょうか？

**Comment by snext1220** [comment]
はい、こちらは現時点ではGitHubのみの反映となりますm(_ _)m

**Comment by cocotori** [comment]
githubの方で確認しました！

この機能いいですね。同じノードから複数出ている場合に、
今どの矢印を選択しているかがわかりやすくなりました。

**Comment by toki-sor1** [comment]
ご報告が遅くなり申し訳ありません！
Win8.1／Chrome 74.0.3729.131(64 bit)にて動作確認。

「編集するリンクを選択」から**正常にリンクが選択できました。**
ミドル祭など、シーン数が多くなるシナリオの場合、フローチャートだけでリンク先を確認するのが大変になってきますので、こちらの機能は**とても便利だと思います。**
