### ISSUE TITLE
シーンへの色付け（New Playground）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#101]
#87 を受けてのIssueです。

フロチャ上、プロローグ／Endシーンに色付けします。
あまり細かく分けると重くなるので、選定は必要ですが、他に識別が必要なものがあればお願いします。

**Comment by toki-sor1** [comment]
フロチャの形がランダム生成なので、全てのSceneが同色だと始まりと終わりがやや見付けにくいかなと感じたので、私は **フロチャ上、プロローグ／Endシーンのみ色付け**が良いと思いました！
＃あまり色数が多いと逆に見辛くなってしまうかなと；

**Comment by snext1220** [comment]
こちら主にシステム的な制約の問題ですっかり対応遅くなってしまいましたが、漸く暫定的ながら実装できました。まだxmlインポートなどには対応できていませんが、プロローグ、end属性（happy／endそれぞれ）の3色を適用しています。カラーは暫定でイマイチかもしれないので、より良いものあればご指定いただけますと助かります～

#### ペンディング事項（メモ）

+ xmlインポート時のgroup処理
+ node0削除時の処理

**Comment by cocotori** [comment]
確認しました。スタートとエンドがわかりやすくなって、いいと思います。
バッドエンドの多いシナリオもあると思いますので、
グッドが見分けられるのも、いいですね。

**Comment by snext1220** [comment]
ありがとうございます！
まずは問題なさそうで良かったです！

実はグループでの色分けも一寸考えたのですが、却って見難くなるかな＆グループ間でシーンの重複がある場合もあるのかなと思い、現在はそこまではやっていませんでした（その辺、もしご要望あればまたご相談させてください＞皆さん）。

**Comment by toki-sor1** [comment]
ご検討＆実装お疲れ様でした＆ありがとうございました！
こちらもそれぞれ特定のSceneが色付けされているのを確認済みです。
とても見易くなって良いと思います～。

> グループでの色分け

個人的には、現在の色分けルールのみで事足りていると思います～。
＃グループ表示で見分けることが容易＆代用可能なので。

**Comment by snext1220** [comment]
ご確認有難うございます！
現在の色分けのみでOKとのことも了解です～
