### ISSUE TITLE
New Playgroundマニュアル

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#102]
β版リリースになったので、基本的なマニュアルを追加します。
比較的直観的なツールなので、せいぜい以下位のライトなものを考えています。

https://www.crumblyheadgames.co.uk/gamebook-authoring-tool-help/how-to-use-the-gamebook-authoring-tool/

**Comment by toki-sor1** [comment]
情報がぎっしりだと「ど、どこを読めば……」と腰が引けてしまうケースもあるので、マニュアル例のようなライトな内容だと見易くて良いと思います！

**Comment by snext1220** [comment]
まずは、第一弾を公開しました。
こちらをベースに、ミドル100などで質問が出たものから補足していければと～
ご確認くださいませm(_ _)m

https://sorcerian.hateblo.jp/entry/2019/05/03/211951

**Comment by toki-sor1** [comment]
第一弾公開お疲れ様です！　遅ればせながら拝見しました！
Playground（SText）は機能が充実してきたことで、解説の情報量が多くなり易いのが悩みだったので、第一弾のマニュアルでは、**ここさえ押さえておけばシナリオ作成が可能**というギリギリのラインまで情報量を削ぎ落し、文章を読み易くしているところが良いなと思いました！

一点だけ、このマニュアルを読んでもっと詳しい情報が知りたいと思った人向けに、**マニュアルの最後の辺りに「通常のマニュアル」などへのリンクがあると、次に何処を見ればいいのか迷わずにアクセスできて良いな**と思いました。
＃最初のところに開発者マニュアル目次もあるのですが、それよりも明確に「次へのステップ」を示す、みたいなイメージです。

補足についても承知しました～。
どうかご無理のない範囲で引き続きよろしくお願い致しますm(_ _)m

**Comment by snext1220** [comment]
> 「通常のマニュアル」などへのリンク

こちら検討いたしますね。
#78 で議論したきり放置状態になっていたのですが；、どの順序でマニュアルを見ていくかを、きちんとナビゲートできるページを作成していければと思っています。

＃そもそも、New Pgで入った人がいきなりSGMLリファレンスを見て理解できるかというのもあり、その辺の整理も課題です^^;

**Comment by cocotori** [comment]
マニュアル読みました。
いい感じだと思います！

ちょっと1ページの分量は多くなってしまいますけど、
情報が分散していないので
こうやって上から下まで読みながら試せば、
一通り作れるようになっているのがいいと思います！
