### ISSUE TITLE
シナリオ募集用のバナー

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#103]
メイン領域トップ（旧サイトでもバナーを掲載していた箇所）に、シナリオ募集バナーを掲載できないものか、と考えております。

というのも、現在、募集中のシナリオが外部からは判りにくく、たとえば現在はSText的にはドラゴンモードで盛り上がっている状態ですが、既に募集は打ち切っている状態で、「では、今って一般シナリオは投稿して良いの？」と、若干躊躇われる状態なのかなと。

そんな人たちのために、現在、「なにを」募集しているのかを明確にするのが目的です。

### バナー種別

+ 一般シナリオ募集用途（STextメインバナー ベース）
+ ミニミニ30募集用途（ミニ30バナー ベース）※一応、半永久的に募集中と考えています^^;
+ 今後、新規企画が立ち上がった時に、そのバナー

いずれのバナーも［Scenario］ページのカルーセル用バナーをベースに、「シナリオ募集中」の文字を重ねるようにし、画像作成の手間を最小限にできればとm(_ _)m （＝募集のために一から画像を作成する、ということはしない）

### 表示方法

+ 基本、複数バナーをランダム表示、［Post］ページにリンク。
+ 新規企画は、［Post］ページ側でもなにかしら専用枠を設けられればと。
+ 現在募集中のシナ種類は［Post］ページでもう少しまとめてもよいのかも？（ご意見募集）

相変わらず、 @toki-sor1 さんにお手間を取らせる案件で恐縮ですが；、まずはご意見など頂戴できれば幸いですm(_ _)m ※もちろん、こういう見せ方の方が良い、など、バナー以外の対応もありうるのかなと。

**Comment by toki-sor1** [comment]
確かにドラゴンモードで大々的にシナリオを募集していたこともあり、では通常シナリオやミニミニ30祭りシナリオは募集していないのか、とやや分かりにくいところがありましたね。
早速既存のバナーのデザインを元にシナリオ募集のバナーを作ってみました（O/Dアップ済み）
https://onedrive.live.com/?id=4837C202555BE782%217367&cid=4837C202555BE782

![カルーセル用シナ募集バナー](https://user-images.githubusercontent.com/42646342/54284382-2dcfda00-45e3-11e9-9ad5-91a0ca36b771.png)
※両方とも同じサイズです

**Comment by snext1220** [comment]
おぉ、お早い！ありがとうございます～
早速、サイトの方にも反映させていただきました。

ただ、現在、［Post］ページにリンクしているだけなので、そもそもミニミニ30って、などわかりにくいところもあり、別途［Post］ページにテキストを追加したいと思います。少々お待ちくださいませm(_ _)m

**Comment by cocotori** [comment]
バナー作成ありがとうございます！
ドット絵キャラがすごく可愛いです、

こういうイラストがあると注目度がぜんぜん違うと思うので、
とてもいいと思います。
