### ISSUE TITLE
New Playground本番リリース

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#104]
New サイトの方もおかげさまで特に問題なく稼働していますので、移行を見送っていたNew Playgroundについても、本番環境に移行しました。
引き続きGitHub側も利用できるようにして参りますが、今後はweb-deli.com側をメインでご利用ください。

伴い、ゲーム画面もNew Playground対応しています（見た目は変わりません）。動作テストの際には合わせてご覧戴けますと幸いです。

**Comment by cocotori** [comment]
これも難しいようなら今後の課題で全然構わないのですけど、

ノードの情報（サマリー）を更新した際、
左側のマップが更新されてどこに行ったかわからなくなってしまいますね。
マップ構成が変わってしまうため仕方ないのだとは思いますが、
かなり使いづらさを感じてしまいました。

やるなら、そのノードに焦点を当てたまま、
周りが更新される、感じでしょうかね。

**Comment by cocotori** [comment]
（いろいろとNew Play Groundをテストしています）

これって、実績の取得はどのように入力したらよろしいでしょうか？

すでにあるシナリオを取り込んで、ちょっと編集して保存すると、
一応今までの実績取得は反映されているようなのですけど、
新しく入力する時はどうやればいいのかわからなくて。

**Comment by snext1220** [comment]
やはり触って戴くと、諸々問題出てきますね～本当にありがとうございます！

> 左側のマップが更新されてどこに行ったかわからなくなってしまいますね。

こちら、同感です。なんらかの対応を取りたいと思います。

若干濁り気味になっているのは、意外とフロチャで利用しているライブラリの癖が強く、「ノードに焦点を当てたまま、周りが更新」という形が難しそうで；（私の理解不足もあるかもしれません）
＃じつは別Issueのノード色替えも更新を前提にすると結構悩ましく、頭を抱えてたり；

やるとしたら、マップを再生成し、該当するノードに再フォーカスするという形になるか、そもそもマップの更新はリロードボタンで明示的に行うか、などの形になるかもしれません。
また、そもそもノードリストのようなものが別に必要なのかも；

とりあえず総合的に対応を検討しますので、少々お待ちくださいませm(_ _)m

> 実績の取得はどのように入力したらよろしいでしょうか？

こちら、スミマセン、バグで項目が抜けています；
別途、項目追加しますので、少々お待ちください～

### 補足

とりあえずミドル祭（仮）に向けて、致命的と思われるバグ対応＋複数Edgeの識別は優先して修正してまいりたいと思います。勿論、他件も順次検討してまいりますので、ご意見引き続きどうぞよろしくお願いいたします～

**Comment by snext1220** [comment]
sceneでの実績設定について、先ほど修正し、GitHub／本番環境双方に反映済みです。
お手数ですが、ご確認くださいませm(_ _)m

**Comment by toki-sor1** [comment]
Win 8.1 Chrome 73.0.3683.103(64bit)にて動作確認。
正常に動作しています（リンク指定時に矢印が荒ぶっていたのが解消されていました）。

今までSGML又はGBATで作成していたので、まだ直感的な操作に慣れないところはありますね。
でも、 **いったん既存の自シナリオをNew Playgroundにインポートして各項目を見比べてみる** と、scenario.xmlで設定したものがNew Playgroundにはどのように反映されているのか等、仕組みが分かり易くなりました。

ただ、New Playgroundでは **scenario.xmlをダウンロード（出力）しないとシナリオの中身（生のファイル？）が確認できない** のがやや気になります。
旧Playgroundやエディタでのシナリオ作成に慣れていると、 **シナリオ作成中にフローチャートしか確認できないところに少しじれったいような印象** も受けました；

旧Playground廃止を考えると、New Playgroundでは **フローチャートとシナリオの中身の表示を切り替えられたらいいな** と思いました。
＃ただし、シナリオの中身は表示できても直接編集はできず、編集する時はあくまでも右側の編集画面のみ、とか？

また、フローチャート上でリンクを削除しようとした時、誤ってsceneごと消してしまうことがありました（**文字とは違って、一瞬にして1つのsceneがまるごと消えてしまう** のがこわいですね；）。

明らかに私が操作に不慣れなのが原因であり（大汗）、こまめなシナリオ保存で防げる事故ではありますが、可能であれば **New Playgroundにアンドゥ機能があったら安心かな** と思いました。
＃GBATもアンドゥ機能が弱いところが気になっていたので；

あと、事故防止対策として、 **選択しているリンクやsceneがもう少し判別し易くなると** 嬉しいです。
＃選択しているリンクの矢印をもう少し太くする、選択しているsceneは色が変わるなど。

**Comment by cocotori** [comment]
実績、追加されているのを確認しました。
ありがとうございます！

ただ、「シナリオを実行」を押すと
以下のようなエラーが出てしまいました。
（環境の更新中でしょうか？）

発生時期は2019/4/6 9:30頃です。

![クリップボード](https://user-images.githubusercontent.com/42885160/55662744-687b0a00-5851-11e9-8212-4c2bed6c4f7e.png)

**Comment by snext1220** [comment]
@toki-sor1 さん、 @cocotori さん＞
ご確認有難うございます！

ご指摘の内容は、今回のMay Updateでは吸収難しそうなので（一部は仕様の議論も必要そうなので^^;）、改めてNew Playground改善のIssueを立ち上げますね。細かな回答もそちらにまとめますので、暫しお待ちくださいませ～

ということで、以下、一部のお返事になります～

> 旧Playground廃止を考えると、

とと、スミマセン、誤解があったようなのですが、とりあえず現時点では廃止検討対象はGBAT2STextのみで（これも当面は継続予定）、旧Pgについては継続予定です。
＃ご指摘の通り、フロチャベースは（ある程度操作感が向上したとしても）生のソースコード編集に慣れている人にとっては、やはりまどろっこしいと思うので^^;
その前提で、もしご意見に変化があるようであれば、是非にお願いいたします～

>「シナリオを実行」を押すと以下のようなエラーが出てしまいました。

スミマセン…！
#108 に由来するバグです
id値に応じてテキストを取得するようになっていたのですが、Playgroundにはscenario.xmlがないので、エラーとなっておりました；先ほどダミーのデータを追加したので、エラーが解消しているかと思います。お手数ですが、ご確認くださいませm(_ _)m

＃怪我の功名で、New Playgroundの専用フォルダーも用意できたので、ダミーの画像を表示するなども今後対応できるかなと思っています^^;

**Comment by snext1220** [comment]
こちら、Issueでの改善ご要望については、 #110 にて新Issueを立ち上げさせていただきました。
ご要望への回答方々、今後の改善方針をまとめておりますので、ご確認くださいませ～（新リクエストもこちらから）

伴い、こちらはCloseしてまいりますね。
