### ISSUE TITLE
SText Data Book（Utility）の新設

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#106]
以下ＴＬで「SText Data Book」（図鑑）の話題が出ました。
https://twitter.com/ishikawanonoich/status/1110878023257997312

以前からモンスター／アイテム図鑑のような話題もありましたので、ここで作成していこうかなと。如何なものでしょうか。

現状想定している前提は以下です。

+ 環境は道場と同じく、STextのゲーム環境で
    + トップにシナリオ目次があって、その配下にシナリオごとのインデックスがある構造
    + 1000単位にシーンを共有（シナ4であれば4000～4999）、先頭にインデックスページを、1項目/ページ、など最低限のルールの範囲では、作者さんそれぞれの裁量で
    + 攻撃力比較などの要素を設ける場合はフォーマットを要相談
    + 編集が悩ましいですが、該当するscene要素だけを送って戴いて、マージという形かなと。
+ モンスター図鑑を想定していますが、シナリオによってはアイテムや登場人物、舞台等の解説があってもＯＫ
+ 多くのデータが揃うに越したことはありませんが、すべてのシナリオでなくともよい
+ 同じく、参加シナリオもすべてのモンスター／アイテムを紹介する必要はない

結構緩い図鑑を想定しているので、徐々にデータを追加していければ程度で、いくらかの賛同が得られたところで、まずはプロトタイプを作成してイメージ共有できればと思っています。

まずは大枠での賛否お知らせいただけますと幸いです。

**Comment by snext1220** [comment]
早速のご賛同有難うございます！

はい、以前から実績系と絡めて、などアイデアは出ながら、データを揃えられるか、といったところで形にならなかったものですが^^;、今回のようなゆるゆるとした形であれば、現実味もあるかな～と…！

TLの方でも、ちゃなさんのご賛同がありましたし、他の皆さまのご意見も待ちつつ、まずは、プロトタイプを作成してみたいと思います（ちょっと時間空きそうですが^^;）。
＃とりあえずひとつのscenario.xmlにまとめるべきかなど、細かなところが悩ましい...（編集の効率性という意味で）

イラスト／スクショ＞はい～こちらは積極的に！逆に、図鑑でイラを書き起こされるような場合には（あればｗ）、既存シナにもフィードバックしていければ良いですね…！

**Comment by RYU-DS** [comment]
余計な事に気付いた感がありますが…「検索」機能を付けないと煩雑すぎて見てもらえない可能性が…しかも「全シナ検索」と「個別シナ検索」を…まぁこれは忘れておくとして。

チラッと話しましたが、自動化がいいかと思います。
シナリオデータのenemiesを自動で引っ張ってきて表示するだけという。

・シナ中同様の敵表示
・その敵の説明文（enemiesの最後）をさらに下にも表示

ここまでを自動でやり、さらに詳しい説明を入れたければ下段を修正、隠したり条件を指定したり、イラストを付けたければできるように、とできればいいかと。
itemsに関しても同様にできるのではないかと思います。
キャラクターその他に関しては手動で入れて、数が多い場合のページ区分けなんかもとりあえずは自動で1000シーン単位で分けてしまい（敵がいないシーンのページもできてしまう事も）、これも修正できるようにすればいいと思います（そのスレであれば、クラーケンまでを1ページなど）。

システム側の負担だけを強いているようで申し訳無いのですが、一度作ってしまえば後は放置でいいのでなんとか…言いだしっぺとしては、シナリオを書く方々に極力負担をかけたくないというのがありまして…また、これの非充実シナリオに対するユーザーの不満なども発生させたくないというのもあります。
どうでしょうか？

**Comment by snext1220** [comment]
ええと、申し訳ありませんが、自動化については現時点ではなしとさせてください。

細かな処では諸々ありますが、大まかには以下の理由からです（1. が特にですが）。

### 1. 複数のscenario.xmlをリアルタイムでまとめるのは、パフォーマンス的に困難

対応するならば、現在のブラウザー処理だけでなく、サーバー処理の実装が不可欠ですが、現在のSTextではほぼサーバー処理を利用していないため、影響は大（たぶん、見た目の生成もデータの不揃いを考えると、例外的な処理が大量に発生すると思われます）。

余談ですが、今回のユーザーランキングもシナリオデータを一か所にまとめるために、stext.xmlを改定するなど、主にデータメンテ的な意味で影響大でした（主に、運用的な意味で）。

### 2. シナリオによって、敵／アイテム情報の内容にばらつきがある

シナリオによっては「鋭い痛み」「生か死か」のような単体では意味のないものも多く、アイテムに至ってはダミーのものなどもあるため、そのままの自動化は悩ましく。また、シナリオのしくみ的にenemy要素を使わずに登場している敵も多くいます（むしろそうした敵の方が物語的には重要）。

紹介文もプレイ画面での表示を想定しているため、簡素なものが多く、そのまま列挙しても、プレイヤーがあえて見たいと思うほどの内容にはならないかと（ほとんどのものが相応以上の加筆が必要と思われ、それが、先にも網羅性は意識しない方が良いと触れた理由でした）。

### 3. 互換性にも影響が出る

もし追加データの枠を設ける場合には、scenario.xmlが主候補となりますが（更に、バラバラのファイルに分けるのは、1. の理由からサーバーサイドにしても避けたい）、その場合、既存の構造にも影響が出ます。

---

以上から、図鑑については（やるとしたら）、基本、独立したコンテンツとしての立ち上げを前提とさせていただけますとm(_ _)m

なお、検索機能についても、少なくともSTextのゲーム画面環境では、実装は難しいと思われます（機能はできますが、これまた影響が大きいわりに、図鑑専用になるため避けたい）。SText環境であれば、目次（インデックス）から辿るという形式になると思われますし、それ以上の機能となると、別環境を模索した方が良いかもしれません。

**Comment by RYU-DS** [comment]
なるほど、自動だと常に図鑑側から全シナを見る事になるから負荷が大きいんですか。
シナ制作者が手を付けずとも自動で最低保証を…と思ったのですが、無理がありますね。
であれば最初の提案通りのユル目の「何がどれくらい載ってるかどうかは制作者の気分？次第」的なモノでいいかと思います。

またちょっと適当な思い付きなんですが、いっそWikipediaのようにプレイヤーが自由に編集できるというのも面白いかもしれません。
「このシナリオにこんなモンスターがいた、強かった（弱かった）」といったような…
さすがに収拾がつかないとは思いますが、さらに絞って図鑑のモンスターに感想を書き込む所を作ってもいいかも？
掲示板と重複しますが、（総合であってもシナ別であっても）掲示板に「さあ何か書け！」だと、よほど声を大にして言いたい事が無いとなかなか書けないのに対し、気軽に書ける（発信できる）のはいいのではないかと思います。

**Comment by snext1220** [comment]
あと、お手数ですが（＆TL重複恐縮ですが）こんな感じで図鑑に掲載したいなどのテキストがあれば、こちらのIssueでお送りいただくことはできますでしょうか。プロトタイプ作成時に参考＆利用させていただければとm(_ _)m

> さすがに収拾がつかないとは思いますが、さらに絞って図鑑のモンスターに感想を書き込む所を作ってもいいかも？

本件は、#94 でコメント機能として議論しておりますので、もし宜しければ、こちらでご意見戴けますとm(_ _)m 現状は反対意見が多く、あと1週間ほどでwontfix予定ですが^^;、ご意見ある場合は一旦closeせずに議論保留にできればと。

なお、以下で軽く触れていますが、質問箱という形で、軽い意見／感想は受け付けられればとも思っています（来るかどうかは判りませんが^^;）。入力を独自に受け付けるようになると、スパム対策など諸々セキュリティ対策も面倒にもなるので、現時点ではこのくらいかなと。
https://github.com/snext1220/snext-management/issues/15

> ソーサリアン Textに関する感想、意見、質問その他は、管理人リオ氏への目安箱、もとい、質問箱で受け付けておるんじゃよ？匿名での投稿も可能とのこと、是非お気軽に投じてほしいぞよ（あ、ゴミ投げ入れないで…）https://peing.net/ja/yy7512 #falcom #ゲームブック

**Comment by RYU-DS** [comment]
あと、お手数ですが（＆TL重複恐縮ですが）こんな感じで図鑑に掲載したいなどのテキストがあれば、こちらのIssueでお送りいただくことはできますでしょうか。プロトタイプ作成時に参考＆利用させていただければとm(_ _)m

要はテンプレートを作る、という事でしょうか？
既にお話している通り、基本は
・シナ中のenemies表示まま
・同説明抜き出し（クリックしなければ見れない文を表示する意味はあると思います）
でいいと思っていますが、現在のenemies表示が最下段にしかできない仕様では無理ですかね？
しかしenemies表示を使わないとなると強さがわからないとなるので、紹介的な意味合いは残ってもデータ的な意味合いは薄れてしまいます。
使う場合は1ページに1キャラに限られ、上にそれなりの説明や絵が必要になり、制作側のハードルが上がると思います（そのスレ内のやつはこれにする予定です）。
上に数キャラ簡単な説明を並べ、下にもそのキャラのenemies表示を並べる…はちょっと雑過ぎるイメージでダメかと。

とりあえずそのスレ内に作るつもりのやつは…

①グリーンスライムLv1
②…知能が無いためか緊張感無く街の近くに現れるスライム…のどかさが増すだけだが一応倒しておくべきか。趣味がスライムいじめとは言われない程度に。
③想定パラメータ…STR6/INT6/DEX7/KRM5/HP75/MP75/FREE1=0/FREE2=1
④m111:グリーンスライムLv1:earth:physics:2L+2R+10-STR-FREE1-10FREE2

①名前。
②これは短いですが半ページ～１ページ以上のものも多いです。
③今の自キャラをこの数値にして実際戦ってみる事ができるようにします（このためのenemies表示）。
④実際のenemies表示です。

これをユーティリティ図鑑の標準にするわけにはいかないので、②をenemies表示内の説明（もしくはそれに追加説明）にし、④をテキスト表示化して１ページ内に並べられるようにするのがいいでしょうか。④の負担が重いと思うので、それで他の方の賛同が得られればいいんですが…

**Comment by snext1220** [comment]
想定テキストありがとうございます。
現時点でのプロトタイプを作成してみました。

以下からもアクセスできますので、ページ構成のイメージ合わせとしてご利用ください。
https://snext1220.github.io/stext/index.html?id=material

また、scenario.xmlはこちらにもUpしておきます。
適宜、Playgroundでの修正＆確認にご利用くださいませ。
[scenario.zip](https://github.com/snext1220/stext/files/3026138/scenario.zip)

> ②をenemies表示内の説明（もしくはそれに追加説明）にし、④をテキスト表示化して１ページ内に並べられるようにするのがいいでしょうか。

とりあえず、1、2までが標準で、あとは自由になるのかもしれませんね（1項/シーンを除いては、ほとんどフリーフォーマットですが^^;）。

4は、本来のscenario.xmlからコピペすればよいので（頻繁に更新はしないと思うので、大丈夫かと）、ギリ標準化は可能かと。テキスト化する方が面倒なので、やるならenemy要素で賄うのが吉かと思います^^;

**Comment by Salvadors-cabin** [comment]
お疲れ様です。
ちょっと忙しく回答遅くなりましたが、「図鑑」には賛成です。

>「何がどれくらい載ってるかどうかは制作者の気分？次第」的なモノ

そうですね。このくらいの緩さがよいと思います。

**Comment by cocotori** [comment]
図鑑などのデータベースがあれば面白そうなのは間違いないのですが、
そのための製作の労力を考えるとどうかな・・・
という、ちょっと消極的な意見です。
すみません・・・

やるのであれば、シナリオ製作者は全く手を掛けずに、
取りまとめる人を立ててその人がまとめていくいう形が
現実的ではないかと思います。
（それがわたしになった場合は、
　もちろんしっかり頑張りたいと思います。）

気になったのは、SText形式にしようとする理由は何かありますか？
個人的には図鑑というと、
Webページをスクロールしながら眺められるようなものをイメージしていました。
プロトタイプのように、
ボタンをクリックしながら探していくのは結構大変ではないか？
という印象があります。

**Comment by snext1220** [comment]
@Salvadors-cabin さん、 @cocotori さん＞
ご意見有難うございます！

> ちょっと消極的な意見です。すみません・・・

いえ、全然です。
そうしたご意見もあるだろうなと思っての、参加自由、というレベルでしたので^^;

> やるのであれば、シナリオ製作者は全く手を掛けずに、
> 取りまとめる人を立ててその人がまとめていくいう形

こちらについては自動でただまとめる作業であれば、ご指摘の通りなのですが（そして、それであれば無理してでもシステムで自動化した方が良いのですが^^;）、以下コメントの2.で挙げた理由から、現状のシナリオ情報を機械的にまとめても、プレイヤーがあえて見たいと思うような情報にはならないのかなと（＝大小はあれ、加筆／整理が必要と思われました）。
https://github.com/snext1220/stext/issues/106#issuecomment-478196962
＃最初からある程度図鑑を想定されていたドラスレだけが、恐らく唯一の例外かと^^;

> 気になったのは、SText形式にしようとする理由は何かありますか？

敵と実際に戦闘できるように、というリクエストがあったためでした。
あとは、インデックスページさえ整備できていれば、縦長のページよりも1項目/ページに分かれていた方が見やすい、ならば、ブログよりも～という理由も（こちらは好みもありそうですが^^;）

もちろん、現時点ではあくまでプロトなので、ブログ展開も全然ありだとは思います～

**Comment by RYU-DS** [comment]
やはり必要性が薄いと考えられる方の負担が争点となりますねー。
なのでやはり自動もしくはそれに近いレベルの簡単なものを標準として、手を掛けたい人は掛ける、がいいでしょう。
図鑑っぽく無さは私も感じましたが、つらつらとページをめくっていく従来の図鑑感覚に対して、インデックスが並んでいるのは（その名の通り）目次を見ている感じでしょうか。
私も個人的には従来方式が好きですが、これは情報過多で必要なものだけ見たい今の時代には合っているかと。スクロールしていかないと次が見れず、それで検索も無いとなるとそれこそ見てもらえないと思います。
あとは標準の落とし所ですかねー。
あ、FREEが1しか無かったですが、そのスレは2まで必要ですし、シナによっては3も要るのでは？

**Comment by snext1220** [comment]
FREE欄＞ こちらはスミマセン、単なる漏れです。
項目は自由に追加できますので、もちろん、FREE3を追加戴くのは自由ですm(_ _)m

**Comment by snext1220** [comment]
とりあえず、こちらはそろそろ方針を決めていければと思います。

### 管理者をたてて包括的にまとめるか、できる範囲で、か

現時点では、以下との認識です。「?」付の方は判断しかねたので、とりあえず片方に入れていますが、違うよ、という場合はご指摘ください。

+ 包括的：RYUさん、cocoさん?
+ できる範囲で：ときのじさん?、サルバさん、リオ

ただし、「包括的」は、先の通り、今回はシステム自動化はNGとさせていただきたく、どなたかベースを作成／メンテ頂ける方が立候補頂けることが前提になるかと思います。

### プロトタイプ版について

現時点では、インデックス型を想定しておりますが、他案がある場合は、お手数ですが、以下のscenario.xmlを直接修正戴くか、別案（scenario.xmlでもブログでも具体的な形にて）をお願いできますと幸いです。
https://github.com/snext1220/stext/issues/106#issuecomment-478304999
＃たぶん、「あれをこれを」と言っているよりも、具体的なレイアウトでお話させて戴いた方が誤解もないかと思うので、ご協力お願いいたしますm(_ _)m


以上、2点について、04/12を一定の〆とさせていただいて、方針決定できればと思いますが、如何でしょうか。
＃もちろん、無理をするものではないので、単なる多数決ではなく、あまりに足並みが合わないように見える場合は、廃案もありだとは思っています。

**Comment by toki-sor1** [comment]
皆さんのご意見を拝見し、自分なりに意見をまとめますね。

### 図鑑はSText？　それとも他の方法？

私は主に管理の面で **「GitHubのwikiを利用する」** のが良いと思いました。
SText版プロトタイプも拝見しましたが、項目を1ページずつ分けて展開できるのと、デザインの観点から良いと感じたのですが、やはり **管理の面から手間が掛かってしまう** と感じたからです。

とりあえず、こちらに **wiki版サンプル** を作成してみました（図鑑の仕様が決まり次第削除します）。

＃サンプルなので特に加筆はしていませんが、作者様毎にシナリオ内には書き切れなかった設定を加筆するのも面白いと思います（ネタバレ要素は、ページ下部にまとめるのも良いかと）。
https://github.com/snext1220/stext/wiki/Scenario-5%E3%80%8C%E5%B0%91%E5%A5%B3%E3%81%AF%E8%8B%B1%E9%9B%84%E3%82%92%E8%AA%9E%E3%82%8A%E3%81%A6%E3%80%8D%EF%BC%88%E4%BD%9C%E3%83%BB%E3%81%A8%E3%81%8D%E3%81%AE%E3%81%98%EF%BC%89

<img src="https://user-images.githubusercontent.com/42646342/55482439-808b3780-565f-11e9-821e-5ece3db4aa2f.png" width="320">

#### GitHubのwiki展開のメリット
- 新たにレンタルサービスなど「登録しなくても良い」

- 共同管理し易く「いつでも編集し易い環境」を実現（＝編集バッティングが発生しにくい）

- SText関連のコンテンツとして「一箇所に集約されているため」管理しやすい

- 現在のSTextサイトやSTextのシステムに「影響が出ない」

#### GitHubのwiki展開のデメリット
- 見た目が「図鑑っぽくない」

- 文字色など自由に変えられないなど「編集にやや難がある」

- 「（恐らく）シナリオ1本につき1ページ」という割り当てになりそう（キャラやアイテムなど項目毎に区切るだけ）

***

### 誰が管理・更新する？

ここも難しい問題ですよね。
チーム内でも既に様々な作業の分担が決まっており、手がいっぱいのところがあるので、 **一人に作業が集中するのは避けたい** ところです。
ただ、ゲスト様のシナリオに関する図鑑は、 **wikiの編集権限があるスタッフが、それぞれ分担して反映する** 感じになるのかなと思います。
 
また、図鑑の内容は「作者自身が書いた方が語弊もなく、自由に書ける」ことから、

- 基本的には「シナリオの作者が自分のシナリオの図鑑を担当する」
- ゲスト様の図鑑は、「内容をIssueにてまとめてご投稿いただき、シナリオ毎の担当スタッフが反映する」

というのが良いかなと思いました。
ただ、図鑑は一度ページを作ってしまえば、そう頻繁に編集するものではないとは思うのですが、ページを作成するまでには相応に負担が掛かるため、  **「図鑑制作の参加は自由」** が良いでしょうか。

***

### 検索機能について

ご意見を拝見して、私も最初は「検索機能は必要」と思って、ブログ展開を推そうと思っていました。
しかし、STextシナリオにおいて **本当に検索機能は必要なのか** 少し疑問を持ちました。

確かに情報量の多いシナリオともなると、検索機能があった方が見やすく、親切だと思います。
それに、調べたいものを索引から探す（＝検索）というのもまさに図鑑的ですもんね。

ただ、シナリオプレイ中には、ゲーム内で各種情報が提示されているので、個人的には **STextシナリオの規模であれば、** シナリオ単位で各項目毎に情報がまとめられてさえいれば、 **検索機能は必須という訳ではないのでは** と感じました。
検索機能が使えれば、それはそれで便利ではあるんですけどね～。

**Comment by snext1220** [comment]
お忙しいところ、ご意見ありがとうございます！軽くレスまとめますね。

#### 図鑑はSText？　それとも他の方法？

GitHubのWikiは実は自分の中の選択肢からは抜けてましたが^^;、編集性などから現実味もあり、賛成です！（サイドバーなども利用すれば、ある程度目次も付けられますし）
stext-managementリポジトリの方であれば、ゲストの方にも権限を付与して、直接編集もありなのでは、と思いました！

#### 誰が管理・更新する？

> 一人に作業が集中するのは避けたい ～～ページを作成するまでには相応に負担が掛かるため、 「図鑑制作の参加は自由」 が良いでしょうか。

私も、主に上記の点かこちらでも賛成でございますm(_ _)m

#### 検索機能について

こちらも賛成でございます。
見た目は若干微妙ですが、GitHubであれば、標準でリポジトリ内部検索があるので、こちらで最低限の用途は満たすかとも。










取り急ぎ

**Comment by snext1220** [comment]
本件、ご意見戴きました皆さま、ありがとうございました。

とりあえず当初予定しておりました〆日になりましたので……

議論については、現時点であまり収束せず、このまま全体として進めるのは微妙に思われたので＆本筋の新企画も本格始動しそうなので、本件は一旦保留にできればと思います。
＃June Updateと合わせて、一旦はwontfixに。それまでに何かあれば引き続きお願いいたします。
＃ @toki-sor1 さん＞折角プロト案をご提示いただいたのに申し訳ありません。。wikiの方は今後の議論でも利用できるかと思いますので、宜しければそのまま残していただけますとm(_ _)m

ただ、以前から話題には挙がっていた件で、できれば形にしたくもあり^^;

+ 各人で「こんなの作ってみたよ」は大歓迎です！（Utilityなどからリンク作成させていただきます）
+ 本IssueもいつでもReopenできますので、議論は歓迎です。

一旦の区切りとはさせていただきますが、引き続きよろしくお願いいたしますm(_ _)m
