### ISSUE TITLE
sitemap.xmlの追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#107]
SEO対策です。
参考： https://seolaboratory.jp/88749/

新サイトでページを分離したことで随分と検索エンジン的には有利になったのですが、それでも、ゲーム画面はほぼ検索エンジンに掛からないため、sitemap.xmlでの改善を期待できればと。先ほどサイトマップを自動生成するコードを作成し、Googleにも登録したので、数日後に検索エンジンにも反映されてくるのではないかと思います。

**Comment by cocotori** [comment]
レクイエムや金竜を試しましたが、無事登録されていました！

検索に引っかかるようになるのはいいですね。

**Comment by snext1220** [comment]
ご確認戴き、ありがとうございます～

はい、その他のページもようやく検索エンジンでヒットするようになり、心なしかPVも全体にばらけてきたような気がします！

**Comment by toki-sor1** [comment]
自シナリオ3作で確認しました。
「常闇」「少女英雄」はタイトルを入力して一発で検索結果に出てきました。
![image](https://user-images.githubusercontent.com/42646342/57136801-e8f94000-6de8-11e9-926c-0d2015268dfd.png)
＃こちらの結果は、「余計なお世話じゃ～いｗ」ってなりましたｗｗ

ただ、やはり「魂」はタイトルが一般的によく使われているor類似しているものがあるからなのか（あとは宣伝不足？）、タイトルと一緒に「観光」「少女」を入れてようやく2番目に結果が表示されていました。

**Comment by snext1220** [comment]
Googleヒントは余計なお世話多いですよねｗ

とりあえず魂、少女は「魂 ソーサリアン」「少女 ソーサリアン」ですと、上位orトップに出てきますね～

Google Search Consoleで該当シナの状況を拝見するに、それなりに検索ヒットはしている（全体平均程度）ので、ご安心ください！

＃ちなみに、原因は不明ですが、検索ヒット数（notアクセス数）だけを見ると、王杖、吸血、イン、ゼロ創造、常闇が上位に来ているようです。
