### ISSUE TITLE
ゲーム画面へのテキストデータ出力

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#108]
#99 でも話題になりましたが、現在、STextは検索エンジン的に弱い状態になっています。

これを改めるために、scenario.xmlのsceneの内容を不可視のテキストとして、ゲーム画面内に吐き出すように改めます。

ブラウザーからソースを見てしまえばネタバレにはなりますが、そこまで見るユーザーであればscenario.xmlまで見ると思われるため、一般的な用途としては問題ないと判断しています。気になるのは大きなシナリオでは起動が重くなる点ですが、現時点では、それを上回って、SEO対策としての有効性がはるかに大きいかと（ただし、お手元で速度が気になる場合はお知らせいただけますと幸いです）。

＃なお、不可視のテキストというと怪しげに聞こえますが、Google的にも正しい手法で埋め込んでいるので、いわゆるSEO的なペナルティが付く隠しテキストではありません。

#### 追記

scenario、utilityページも同様に、stext.xmlからのテキストを埋め込むように改めました。

**Comment by cocotori** [comment]
シナリオの文章にしかない「ラブラディーネ」で検索したら
ソーサリアンText出てきました。

いいですね！いずれ、ソーサリアン周りのワードの検索で
いっぱい引っかかってくれたらいいなと思います。

![スクリーンショット 2019-05-01 10 09 52](https://user-images.githubusercontent.com/42885160/57002313-6c543f00-6bf9-11e9-8854-34f409457934.png)

**Comment by snext1220** [comment]
おぉ、ちゃんと出ていますね…！
ご確認有難うございます！

ちなみに、拙作はすごく二次創作なので、王様の杖やらトラベラーズインやらグーランやら、原作側がヒットしてしまい、中々トップに出てきませんｗ 原作由来のネタも痛し痒し?です^^;

**Comment by toki-sor1** [comment]
こちらも自シナリオで確認してみましたが、リオさんが仰る通り二次創作の色が濃いシナリオ（常闇）では、検索結果になかなか出てきませんね～。
原作の方がガンガン出てきます……ｗ

しかし、「魂」は登場キャラのリュフーが珍しい名前なのでパッと出るかと思いきや、宣伝不足の影響もあるのかなかなか出てきませんでした；

「少女英雄」は、Nextシナリオのリメイクであったり、ミニミニでも扱っていた影響か、STextではなく「新時代の～」と「Nextサイト」関連で検索結果に出てくる方が多かったですね。

**Comment by snext1220** [comment]
原作の方が＞ SEOだけ見てしまうと、独自シナの方が当たりは良いんですよね^^;
原作ネタだからこそ、というメリットもあるので、ホント痛し痒しなんですが＞＜；

宣伝不足＞SEO対策をしてから日も浅いので、その辺も影響してそうですね^^;
ただ、なによりのSEOはブログなどからのリンクなので、どんどん宣伝してやってくださいませ～
