### ISSUE TITLE
王さまbot（新規サイトへの対応）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#109]
備忘録代わりに、こちらでもまとめております。

新規サイトでページが分かれ、Twitterカードにも対応したことに伴い、お手数ですが、お手すきの折にも、王さまbotの既存ツイ更新をお願いできますと幸いです＞ @cocotori さん

具体的には、以下の対応が必要と思われます。

+ 旧：新URLが1：Nのため、URLの変更
+ Twitterカードと画像付きツイが競合?する場合は、画像の指定を一部外す必要があるかもしれません（Twitterカード至上でもないので、添付画像の方が訴求性ある場合はそちらを活かす？）
+ サイト移行によって古くなった画像などの差し替え or/and 内容的に古くなったツイの削除？

**Comment by cocotori** [comment]
了解です！対応しておきます。
（ちょっと忙しくなってきてしまったので遅れるかもしれません。
　すみません・・・！）

**Comment by snext1220** [comment]
いえいえ、お忙しいところ恐縮です＆どうぞよろしくお願いします！

**Comment by snext1220** [comment]
こちら最近流れているツイの範囲で、確認しておりました。
で、古くなった機能（たとえばPlaygroundの超初期の画面、以前のステータス画面など）も結構流れておりますが、この辺消した方が良いかも、などと。完全メンテは難しいと思うので、どこまでというのはあると思いますが、如何でしょうか。

＃古い機能を懐かしむ、という割り切りも一定はあると思いますがｗ

**Comment by cocotori** [comment]
了解しました。

古いのを見直したいと思います。

**Comment by cocotori** [comment]
ざっと見直してきました。
ただ、完全にではないのでこちらはおいおい、ですね。

**Comment by snext1220** [comment]
ありがとうございます～
はい、量も多いので、気付いたものから＆次の更新時になど、ボチボチですね。
お手数をおかけしますが、引き続きどうぞよろしくお願いします！

**Comment by toki-sor1** [comment]
私の方でも確認してみました。
既にご対応済みかもしれませんが、5月3日23:00～に確認したところ、下記ツイートがリンク切れ・情報がやや古い印象でした。

- bot 7ページ目
  - #falcom さんや、Wii U版 ソーサリアン Next（http://bit.ly/YcJZ6I ）は、まだかのぅ？もうそろそろだと思うのじゃが… #snext pic.twitter.com/BntzaP2Md7
  - 「ソーサリアンNextのペンタウァの勇者たち」（http://bit.ly/1QzbNjS ）では、後日、Next企画をご紹介頂いたぞよ。Nextラジオをはじめ、さまざまな腹案をお持ちのご様子。水面下で諸々企画されているそうじゃ。ありがたいことじゃのぅ… #falcom

- bot8 ページ目
  - 余も驚きを表現する顔文字とやらを作ってみるとするかの…。そうじゃの、「（ ' sss ' ）」というのはどうじゃ？ Sは勿論ソーサリアンのSなのじゃが…むっ？ 兵士Aよ、残念な王を見るような目をしているのは何故じゃ？ #snext
  - 「続・ソーサリアンNextのペンタウァの勇者たち」（http://bit.ly/1TAjvgB）では、後日開かれた「王さまを囲む会」、もとい、「プチNext有志オフ会」の様子をレポート戴いておるのじゃよ？シナリオ／BGMの人気投票もあったようじゃよ？ #falcom

- bot 9ページ目
  - 漫画版「みんな集まれ！ファルコム学園3巻（http://bit.ly/1CjVpJj）」絶賛発売中ぞよ！な、なんと3巻では幾人ものソーサリアンの心を折ったという伝説のアレが…！スリットちゃんも大活躍じゃ！ #falcom

**Comment by snext1220** [comment]
ご確認ありがとうございます！

ラジオ、有志オフなどは、私も悩んでいました。そうした意味では、ドラスレラボ系のリンク切れも複数あるのですが、以前そんなネタもあった、程度で残しておいても良いかな、などと微妙にユラユラと^^;（リンクだけを消して、ツイは残すという選択肢もありますが）

同じくWiiUについても古くなっているのですが、ウソネタなので（＝STextとか現在の実機能を伝えるツイでないので）、これはこれでありなのかとか、表現を変えていくのか、など。

顔文字、はこれなんでしたっけ？（あまり新旧関係ないかもと思ったのですが、実は元ネタ理解してない？ｗ）

と、古いツイの整理については方針微妙に揺らいでいるので、引き続きご意見頂けますと幸いです～
＃ 本件、一旦July Updateに移動いたしますね。

**Comment by toki-sor1** [comment]
> ラジオ、有志オフなどは、私も悩んでいました。そうした意味では、ドラスレラボ系のリンク切れも複数あるのですが、以前そんなネタもあった、程度で残しておいても良いかな、などと微妙にユラユラと^^;（リンクだけを消して、ツイは残すという選択肢もありますが）

そうですね、リンクと文章の修正でそのまま継続というのも有りだと思います～。

> 同じくWiiUについても古くなっているのですが、ウソネタなので（＝STextとか現在の実機能を伝えるツイでないので）、これはこれでありなのかとか、表現を変えていくのか、など。

機種が古い物というところとネタツイートというところでやや悩みますが、こちらも上記と同じ対応で大丈夫そうかなと思います。
（そのままだと、どうしてもツイート自体の古さを感じさせてしまい、情報が更新されていないのではという印象を与えてしまうため、若干の修正は必要かなと）

> 顔文字、はこれなんでしたっけ？（あまり新旧関係ないかもと思ったのですが、実は元ネタ理解してない？ｗ）

確か、結構前の朝ドラで使われていた顔文字が元ネタだったかな、とおぼろげにｗ

**Comment by snext1220** [comment]
ご確認有難うございます！

とりあえず内容的に変更があるものは個別に対応だと思いますが、リンク切れについてはリンクを「（現在はリンク切れ）」でしょうかね～特に、紹介戴いたブログ系は内容をメンテするのも難しそうなので、最低限リンク切れだけを避ける程度かなと^^;

> 確か、結構前の朝ドラで使われていた顔文字が元ネタだったかな、とおぼろげにｗ

やはり元ネタありでしたかｗ（地味にそういうのがチラホラと^^;）

**Comment by cocotori** [comment]
リンク切れ情報ありがとうございます！
（大変遅くなり申し訳ありません）

リンク切れは基本的にリンク切れ表記を追記する、
文言を多少変更する、で対応したいと思います。
判断に困るものがあったらまた相談させてください。

**Comment by snext1220** [comment]
ご対応ありがとうございます！
私の方では、問題ないかと思います。
既存のものも含めますと非常に分量があって見直すだけでも大変かと思われますが、
徐々に気付いたものから修正していければと。引き続きどうぞよろしくお願いしますm(_ _)m

**Comment by toki-sor1** [comment]
返信が遅くなり申し訳ありません……！
ご対応お疲れ様です！

> リンク切れは基本的にリンク切れ表記を追記する、
文言を多少変更する、で対応したいと思います。
判断に困るものがあったらまた相談させてください。

はい、私も問題ないと思います！
お忙しい中、お手数をお掛けしてしまい恐縮ですが、引き続きよろしくお願い致しますm(_ _)m

**Comment by cocotori** [comment]
一通り対応しました。

・Wii U
　ゲームボーイ版などと同様に、過去ネタに変更しました。

・「ペンタウァの勇者たち」
　リンクのみ削除。

・顔文字
　一応このまま残してあります。

・ファルコム学園
　ファルコムショップを覗いてみましたが、もう3巻が置いてありませんね。
　古いからなのか・・・　ツイート自体を削除しましたが、
　他の対応の方がよければ連絡ださい。

・ドラスレラボ
　リンクのみ削除。

消してしまったものも、bot.xlsxには念の為残してあります！

**Comment by toki-sor1** [comment]
ご対応ありがとうございます！　お疲れ様です～！

> 顔文字

かなり前の朝ドラが元ネタなので、こちらはツイートそのものを削除いただいても良いかなと思います（ときのじ発案ツイート）

> ファルコム学園

参照URLのご確認ありがとうございます！（お手数をお掛けしました……！）
こちらも私発案のツイートとなりますが、削除で問題ないと思います。
現在、新シリーズがスタートしていますので（https://www.falcom.co.jp/book-data/bk-0149-00 ）、また新たなツイートとして追加させていただいた際には、よろしくお願い致します。

上記以外のツイート（ご対応）については、特に意見はありませんです～。

**Comment by snext1220** [comment]
ありがとうございます！
私の方も上記ご方針／対応にて異論ございませんです～

**Comment by cocotori** [comment]
顔文字のツイートも消しておきました！
