### ISSUE TITLE
テキストカラーの追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#11]
以前からあったテキストカラーにWhiteを追加します。

選択反転するまで判読できないテキストの用途で利用します。

`4. みんな、%white%ソーサリアン%/%！`

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 69.0.3497.81（64 bit）、iPhone 7／Safariにて確認。
正常に動作しました。
iPhoneでは文字を選択して反転しただけでは文字が読めませんが、該当の文字をコピーし、別の場所にペーストすることで、文字の内容を確認できました。

**Comment by snext1220** [comment]
ご確認ありがとうございます。確認したところ、iPadでも同様でした（恐らくSafariでは共通なのかなと）。Androidはじめ、他のブラウザーでは反転のみでいけるので、利用時には注意を促す、程度でママにしていければと。
