### ISSUE TITLE
New Playgroundの改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#110]
#104 を受けて、新規にIssueを立ち上げました（前Issueからの転載あり）。
議論しつつ、ご要望確定したものから徐々に実装進めていければと。
なお、既にNew Playground関係でいくつかIssueが立ち上がっていますが、既にあるものは含めていません。

### マップの再描画（一次対応済）

> ノードの情報（サマリー）を更新した際、左側のマップが更新されてどこに行ったかわからなくなってしまいますね。マップ構成が変わってしまうため仕方ないのだとは思いますが、かなり使いづらさを感じてしまいました。～～やるなら、そのノードに焦点を当てたまま、周りが更新される、感じでしょうかね。

やるとしたら、マップを再生成し、該当するノードに再フォーカスするという形になるか、そもそもマップの更新はリロードボタンで明示的に行うか、などの形になるかもしれません（自動でマップが再編成されてしまうくらいなら、それもあり？）。

また、GBATのように、そもそもノード（パラグラフ）リストのようなものが、チャートとは別にあっても良いのかもしれません（ご要望あればお願いします）

### ~~マニュアル／ヘルプへの反映（対応なし）~~

> 今までSGML又はGBATで作成していたので、まだ直感的な操作に慣れないところはありますね。でも、 いったん既存の自シナリオをNew Playgroundにインポートして各項目を見比べてみる と、scenario.xmlで設定したものがNew Playgroundにはどのように反映されているのか等、仕組みが分かり易くなりました。

ご評価ありがとうございます～
はい、ツールとして旧Pgよりも機能は高くなっているので、若干の慣れは必要かもしれません^^; 

現在、マニュアル作成も予定しておりますが（正直、超導入者向けなので、既にscenario.xmlを知っている方にはあまり意味がない内容になるかと^^;）、ある程度ご利用いただいて、「この辺が最初理解しづらかった」などあれば、是非ご指摘くださいませ～
マニュアル、またはダイナミックヘルプに取り込んでいければと…！

### ~~ソースコードの確認（廃案）~~

> ただ、New Playgroundでは scenario.xmlをダウンロード（出力）しないとシナリオの中身（生のファイル？）が確認できない のがやや気になります。旧Playgroundやエディタでのシナリオ作成に慣れていると、 シナリオ作成中にフローチャートしか確認できないところに少しじれったいような印象 も受けました；
> 旧Playground廃止を考えると、New Playgroundでは フローチャートとシナリオの中身の表示を切り替えられたらいいな と思いました。

#104 の方でお返事した件ですが、旧Pgは残る前提ですと、如何でしょうか？
ソースでの編集に慣れた方は旧Pg or/and エディター、ライト層は新Pg という感じかなと。

＃将来的に新旧Pg一本化を考えるとすると、ソースの表示／編集もできるようにならないと、要件を満たしにくいのかなと思われ、若干悩んでいます^^;（ただ、新Pgはscenario.xmlとは別形式なため、表示の度に変換が必要になるという；）

### ~~パラグラフ削除時の処理（済）~~

> 明らかに私が操作に不慣れなのが原因であり（大汗）、こまめなシナリオ保存で防げる事故ではありますが、可能であれば New Playgroundにアンドゥ機能があったら安心かな と思いました。

ここは仰る通り、削除は怖いですよね^^; 慣れてきても、ついうっかりはあると思いますので、対処を検討したいと思います。

ただ、Undo機能は処理履歴を記録しなければならないので、影響は大きそうです。
また、エディターが既にUndo機能を持っているので（ctrl＋zで可）、そちらとのバッティングも出てきそうで；（エディター的には置換はじめ、GBATよりかなり色々いけるはずなので、ぜひご活用ください…！）

よって、削除時には確認ダイアログを出していくという形で如何でしょうか。削除そのものはそれほどないと思うので、それで事故防止にはなるのかなと…！

### ~~フローチャートの表示スタイル（済）~~

> あと、事故防止対策として、 選択しているリンクやsceneがもう少し判別し易くなると 嬉しいです。＃選択しているリンクの矢印をもう少し太くする、選択しているsceneは色が変わるなど。

こちら検討してみます。
一旦、こちらでスタイル変更してみますので、もしカラーなどご要望あればお願いします～

**Comment by toki-sor1** [comment]
お返事ありがとうございます！

### マップの再描画

> また、GBATのように、そもそもノード（パラグラフ）リストのようなものが、チャートとは別にあっても良いのかもしれません（ご要望あればお願いします）

**ノード（パラグラフ）リストのようなものがあると嬉しいです！**
New Playground（以下新Pg）のフローチャートでは、ノードとEdgeの重なりで視認しにくいところ出てくるケースも多いので、ノードを純粋に上から順に並べたものがあると、シナリオの構成が確認し易くなって助かります。

### ソースコードの確認

> #104 の方でお返事した件ですが、旧Pgは残る前提ですと、如何でしょうか？
ソースでの編集に慣れた方は旧Pg or/and エディター、ライト層は新Pg という感じかなと。

わぁぁ……！　勘違い大変失礼致しました……！！
廃止の方針はGBAT2STextのみで、旧Pgまで廃止という話ではありませんでしたね……；；
（GBAT2Text廃止の流れで、つい旧Pgも廃止と思い込んでました；）

はい、新旧Pg共に継続であれば、新Pgで生のコードとフロチャを切り替えられる機能はなくても大丈夫ですね！
**前回の私の提案は廃案でお願いします……！**

### パラグラフ削除時の処理

> また、エディターが既にUndo機能を持っているので（ctrl＋zで可）、そちらとのバッティングも出てきそうで；（エディター的には置換はじめ、GBATよりかなり色々いけるはずなので、ぜひご活用ください…！）

> よって、削除時には確認ダイアログを出していくという形で如何でしょうか。削除そのものはそれほどないと思うので、それで事故防止にはなるのかなと…！

エディター側のショートカットによるUndo/Redo機能について、考えが至りませんでした；
こちらはヘルプから確認できるものにもかかわらず、先の件と併せて確認不足申し訳ありません……；；

フローチャート側のUndo機能実装は問題が多いことや、エディター側でショートカットが充実していることを考えると、フローチャート側では **「削除時に確認ダイアログを出していく」という対策でワンクッション挟むことで問題解決できそう**ですね！

### フローチャートの表示スタイル

> こちら検討してみます。
一旦、こちらでスタイル変更してみますので、もしカラーなどご要望あればお願いします～

ご検討ありがとうございます！
もし選択中のノードとEdgeのカラーが変更できましたら、現在の寒色とは逆に「暖色（#ff9900や#ff99ccなど）」が判別し易くて良いかなと思いました！

**Comment by snext1220** [comment]
とりあえずNew Pgの改善の対応できるものから対応してみました。詳細?は上の関連Issueを参照下さい。あとは、
+ Sceneリスト
+ プロローグなどのカラーリング
かなと思いますが、カラーリングが地味に難物で別の策を講じる必要があるかもしれません；
＃その他、なにか忘れているものがあればお知らせください。

**Comment by snext1220** [comment]
本Issueの内容も、 #137 で凡そ役割を終えたように思えます。
カラーリングは #101 に移動していますので、問題なければCloseにできればと。

**Comment by cocotori** [comment]
問題ありません。
改めて見て、膨大な更新内容・・・よくぞここまで・・・
ほんとお疲れさまです！

**Comment by snext1220** [comment]
ありがとうございます！
そう仰って戴けると、作者冥利に尽きます＞＜

またプレグラ祭で使い込んで戴くと色々出てくるのかな～と思いますが、引き続きよろしくお願いいたします～

**Comment by toki-sor1** [comment]
改善お疲れ様でした…！
また、こちらから色々と無理難題を言ってしまったにもかかわらず、じっくりと丁寧にお話を聞いていただき、こうして膨大な量のリクエストをに応えていただき、本当にありがとうございました！
こちら、問題ありません！

**Comment by snext1220** [comment]
こちらこそ膨大な課題への議論にお付き合い戴き、ありがとうございました！
皆さんのリクエストが改善の糧でもあるので、本当に助かりました。
そして、まだまだ改善の余地はあるだろう前提ですが、現時点では良い環境ができたと思います～
引き続きどうぞよろしくお願いいたします！
