### ISSUE TITLE
Scene／リンク削除時の確認ダイアログ（New Pg）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#113]
#110 を受けてのIssueです。

Node（Scene）／Edge（リンク）削除時に確認ダイアログを表示するようにしました（現時点ではGitHubにのみ反映）。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 73.0.3683.103（64 ビット）にて動作確認。
正常にダイアログが表示されていました！　GitHub版への実装ありがとうございます～！
**ワンクッションあるだけで事故が防止し易くなるので、いいと思います！**

**Comment by cocotori** [comment]
確認しました。
いいと思います！
