### ISSUE TITLE
選択時のカラーリング（New Pg）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#114]
#110 を受けてのIssueです。

Node（Scene）／Edge（リンク）選択時のハイライトカラーを変更するようにしました（現時点ではGitHubにのみ反映）。

**Comment by toki-sor1** [comment]
早速のご対応ありがとうございます！
Win 8.1／Chrome 73.0.3683.103（64 ビット）にて動作確認。
Node（Scene）とEdge（リンク）がきちんと色分けされていて、**とても見易くなりました！**
良いと思います！

ただ、**この仕様が後々システムに負の影響を及ぼしたりする**ようでしたら、**もっと影響が少ない仕様**もしくは**色変更は無し**が良いのかなと思いました。

**Comment by snext1220** [comment]
ご確認有難うございます！

負の影響＞あ、こちらは言葉足らずで申し訳ありません；また、ご配慮恐縮です；；
一律「選択したもの」のカラーリングは問題ございませんです。

プロローグ／エンディングなど、**シナリオデータの内容に応じてカラーリングを切り替える**のが、現在のNew Pgでは難しくなっているため、なやんでおりました。こちらはもう少し別案を思案致しますので（今はノーアイデアなのですが^^;）、その折はご相談させてくださいませ～

**Comment by toki-sor1** [comment]
> 負の影響＞あ、こちらは言葉足らずで申し訳ありません；また、ご配慮恐縮です；；
一律「選択したもの」のカラーリングは問題ございませんです。

おおう、勘違いすみません；；
こちらの仕様については大丈夫なのですね、安心しました！

> プロローグ／エンディングなど、シナリオデータの内容に応じてカラーリングを切り替えるのが、現在のNew Pgでは難しくなっているため、なやんでおりました。

おぉん……今度はこちらが……。バランスが難しいですね……；；

> こちらはもう少し別案を思案致しますので（今はノーアイデアなのですが^^;）、その折はご相談させてくださいませ～

そうなると、**プロローグが一番上に、エンディングが下に**という感じで、始まりの位置がある程度制御できたら見易くなるかなぁと思いました。

ただ、これ似た意見を以前も出した覚えがあり、フローチャートの形状がランダムなのは仕方がないという感じだったので、**実装が難しい又は不可能な場合は、スルーでお願いします～。**

**Comment by snext1220** [comment]
> フローチャートの形状がランダムなのは仕方がない

はい～特に絞り込みをした時の変化に対応しきれないと思われ、でも、緩くであれば行けるか、などとまだ悩み中です；；
＃フロチャ機能の元となるライブラリを私もまだ十分に理解できていないもので^^;、スミマセン。。

ただ、現状では未対応の「Sceneリスト」があるので、こちらでプロローグ／エンディングを目立つように見せてやるというのはありかなと思ったのですが、如何でしょうか（フロチャと違って、こちらは比較的自由が利きそう）。

**Comment by cocotori** [comment]
確認しました。色がついて見やすくなったと思います！

**Comment by toki-sor1** [comment]
お返事が遅くなり申し訳ないです……！

> ただ、現状では未対応の「Sceneリスト」があるので、こちらでプロローグ／エンディングを目立つように見せてやるというのはありかなと思ったのですが、如何でしょうか（フロチャと違って、こちらは比較的自由が利きそう）。

「Sceneリスト」で対応可能なのですね！
こちら、比較的自由が利きそうとのお話ですので、**Sceneリストで対応が良い**と思いました！

**Comment by snext1220** [comment]
Sceneリスト＞承知いたしました！

こちらは機能、というよりもUIのどこへ組み込むべきかで悩み中ですが（ご要望あれば是非！）、粛々と対応してまいります～

**Comment by toki-sor1** [comment]
うーん、縦幅も横幅も結構ギリギリな印象ですよねぇ。
それに、エディター画面のタブでSceneリストと切り替え、というのもクリックの手間が増えてしまいそうなので、Sceneリストは常に見えている方が良さそうな感じもします；

となると、全体的に横幅を狭めて3カラム（？）が良いのかなぁと。
（リストを横へ横へと展開すると、パッと見た時に右と左のどちらがScene0なのか分かり難いと思うので）

**Comment by snext1220** [comment]
ギリギリ＞そうなんですよね...仰る通り、3カラムも考えたのですが、右ペインが狭めにくいので、チャートエリアを主に狭めると、結構見た目にも厳しいという^^;

あとは、以下のような案を考えています。

+ 「Sceneリストを常時利用する？」というのもありまして、ある程度限定的な用途であると考えると、以下のようなスライド式パネル（ https://oncebot.github.io/pushbar.js/ ）などで良いのかも。
+ 常時表示を優先する場合は、（横リストにはなりますが）チャートエリアの下部分に表示
+ もっと軽くドロップダウンリストとして、［テンプレートを選択］の隣に表示

引き続きご意見戴ければ幸いでございます～

**Comment by snext1220** [comment]
Sceneリストについては話題も別になってきましたので、Issue #120 として新設し、こちらはCloseしてまいりますね。
