### ISSUE TITLE
${if} 分岐での「|」利用

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#115]
以下のIssueを受けての対応です。
https://github.com/snext1220/snext-management/issues/16

${if}内での「|」がルビ構文と競合して正しく動作していませんでしたが、これを修正しています。

本修正は、シーン内のすべての${...}式に影響が及びます。注意は払っていますが、動作テストに際しては、他の${...}式にも目を配って戴けると助かります。

**Comment by cocotori** [comment]
うっかりしていましたね。
テストが抜けており失礼しました。

・ドールズ（構文未使用）
・吸血姫（構文未使用）
・ネコ（構文未使用）
・協力者
・金竜
・レクイエム
・裏切り者

で確認しましたが、今までの${}構文は大丈夫そうです。

**Comment by snext1220** [comment]
各シナリオのご確認ありがとうございます！

フリーテキストを加工する${...}系の構文は、新機能以外にも思わぬ影響が出るので、ホント要注意ですね...私の方でも改めて仕様チェックを強めていきたいと思います；

**Comment by toki-sor1** [comment]
確認対象シナリオは、${}構文使用の「魂」と「常闇」です。
Win8.1／Chrome 74.0.3729.131(64 bit)にて動作確認。
正常に動作していました。
