### ISSUE TITLE
マップ再描画時の選択状態維持（New Pg）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#116]
#110 からの派生です。

> ノードの情報（サマリー）を更新した際、左側のマップが更新されてどこに行ったかわからなくなってしまいますね。マップ構成が変わってしまうため仕方ないのだとは思いますが、かなり使いづらさを感じてしまいました。

上記ご指摘を受けて、まずは比較的簡単に対処できる「選択状態の維持」を対応しています。今後、Sceneリストの作成も検討してまいりますが、そちらは時間もかかりそうなので、まずは応急処置的に。

**Comment by cocotori** [comment]
確認しました。マップ自体は動いてしまいますけど、
選択が維持されること、選択時のカラーが見やすくなったことで
だいぶわかりやすくなったと思います！

**Comment by snext1220** [comment]
ありがとうございます！
こちら、まずは改善したとのことよかったです～
＃引き続きマップの維持等可能かどうか、検討してまいります。

**Comment by toki-sor1** [comment]
Win8.1／Chrome 74.0.3729.131(64 bit)にて動作確認。
**選択状態が維持されているのを確認しました。**
ココさんも仰っていましたが、サマリー更新時にマップが動いても、**選択状態の維持と選択時のカラー変更との相乗効果で、どのSceneを編集中かが分かり易くなったと思います。**
