### ISSUE TITLE
コントロールパネルの改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#118]
#117 からの派生で、本Issueはコントロールパネルの改善案についてです。

### 再編案（構造）

現在はパネルそのものの表示／非表示を切り替えできるので、これを維持して、パネルは一か所にまとめ、Systemとそれ以外も分離しないという方針を採っています。

+ Status
+ Result
+ Bonus
+ System
    + Backup
    + Restore
    + Sound（On/Off）
    + Help
    + Exit（旧Pentwa）

#### 懸案

+ Statusは右クリックで起動できるので、そこまで重要でないか（モバイル環境では右クリックできないので重要）
+ 同じくBonusはゲーム中はさほど見ない？
+ 実は、Backup／Restoreの方は頻繁に利用するかも
+ 上記の優先順位を入れ替える場合、二段目階層に逃がすものの一階層ラベルが悩ましい（Other？）

#### 今後の進行

1. メニューの階層構造を確定
2. ボタンデザイン案（その時が来たら、ときのじさんご相談させていただけますと）
3. 新コントロールパネルの実装

**Comment by cocotori** [comment]
確かに今までのボタンは数が多いかもしれませんね。
システム周りの、バックアップ、サウンド、ヘルプなどは
ひとまとめにする案に賛成です。

**Comment by toki-sor1** [comment]
> 確かに今までのボタンは数が多いかもしれませんね。
システム周りの、バックアップ、サウンド、ヘルプなどは
ひとまとめにする案に賛成です。

私も**ココさんのご意見に賛成**です～。

### 懸案
> 同じくBonusはゲーム中はさほど見ない？

確かにBonusは（私は）あまり……というか、ほぼ見ない感じですね。
**内容的にResultと一緒にまとめられそう**な感じもします。

＃その場合は、「Result」の下にTrophy （現Result）→ Bonusと続くイメージで。

> 実は、Backup／Restoreの方は頻繁に利用するかも

Backup／Restoreがより利用しやすくなり、高難易度（＝ゲームオーバーになりやすい）シナリオを実装しやすくなったので、今後も利用頻度は高いかなと思います。
**こちらは一階層が良さそうかな**と思いました。

＃そういえば、**私はスマホ環境だとBackup／Restoreの利用方法がわからず利用していない**のですが、皆さんはスマホやタブレットでBackup／Restoreを利用していらっしゃいますか？

### 今後の進行
> ボタンデザイン案（その時が来たら、ときのじさんご相談させていただけますと）

**承知しました！**

**Comment by snext1220** [comment]
ご意見ありがとうございます。
まずはご意見に基づいて、構成を再編してみました。★は新設です。

+ Status（モバイルファーストで考えると、ここは維持）
+ Info
    + ★Items（ステータスから分離して所持アイテムの表示）
    + ★Flags（ステータスから分離して所持フラグの表示）
    + Result
    + Bonus（有効化ボーナスはここで表示）
+ System
    + Backup
    + Restore
    + Sound（On/Off）
    + Help
    + Exit（旧Pentwa）

### 補足

+ ステータスダイアログを整理するという意味では、メニューを減らすのではなく、アイテム／フラグなど、用途に応じてダイアログそのものを分けてはどうかと考えました（メニュー項目は増えますが、階層化したことで、優先度合いは明確になったのではないかと）。
+ ボーナスについては、既にダイアログがあるので、そちらにまとめさせていただきました（https://github.com/snext1220/stext/issues/119#issuecomment-491570184 も参照）
+ Backup／Restoreは1階層というご意見も戴いていたのですが、まとめ方が難しいため＆現在も疑似的な二段メニューなので、Systemママと致しました

### お返事

> そういえば、私はスマホ環境だとBackup／Restoreの利用方法がわからず利用していないのですが、皆さんはスマホやタブレットでBackup／Restoreを利用していらっしゃいますか？

これ、ほぼ使えていないですね...ファイルをクラウドに保存するなどして利用できはするのですが、現時点ではＰＣ専用機能とお考えいただいた方が良いかと思います。
モバイル対応を本格的に進める場合、こうした機能の整理も要検討かと（おそらくブラウザストレージ＆ファイル保存のハイブリッド）

**Comment by toki-sor1** [comment]
再編お疲れ様です～！

- メニューを減らさず、用途に応じてダイアログそのものを分けるのに賛成です！
- BONUSを現在のBONUSダイアログにまとめるのも良いと思います！　有効利用！
- Backup／Restoreは、考えてみればそこまで頻繁に使うものではなかったですね。Systemままで良いと思います！

### 意見

https://github.com/snext1220/stext/issues/118#issuecomment-492695579 でSound（On/Off）をSystemにまとめるという意見に賛成していたのですが、**ちょっと方針転換させてください；**

STextでは様々なBGMを使用している影響で、**BGMの音量もまちまちなところがあります。**
すると、急に音が大きくなってプレイヤーさんがビックリするというケースもあるのではないかと思うので、**サウンドはさっとOn/Offができるように1階層の方が良さそうかな**と思いました。

＃以前、BGM音量が大きいという意味合いのツイートをお見掛けしたことがあります。
スマホでは本体のボタンでさっとボリュームを調整できるのですが、**PCからだと操作が少し多くなるので、そうなるとすぐにOn/Offできる位置にボタンがあった方が親切かなぁと。**
（音量の大きさの理由については、以前Azさんからご説明いただいたので、そちらは承知しております）
***
> スマホ環境でのBackup／Restoreの利用方法

お返事ありがとうございます～。
クラウドなどを活用すればスマホからでも利用はできるものの、現在はPC専用という感じなのですね。了解です！

> モバイル対応を本格的に進める場合、こうした機能の整理も要検討かと（おそらくブラウザストレージ＆ファイル保存のハイブリッド）

そうですね～。Backup／Restoreはシナリオ執筆の自由度やプレイヤーさんの遊び易さにも影響してくるものなので、今後の方針によっては機能の整理も必要そうですね。
技術的な面からの意見が出せず申し訳ありませんが（大汗）、その際はよろしくお願い致します；；

**Comment by snext1220** [comment]
> 再編お疲れ様です～！

再編案へのご賛同ありがとうございます！
細分化させると、ステータスダイアログは多少自由度が上がりますね～
引き続き以下の点について議論を進めさせていただけますとm(_ _)m

+ ステータスに残す項目（現在は上からFreeまでが残るイメージです）
    + まだ項目が多いのでスッキリさせたいですが、あまり細分化させると使いにくいと思われ、悩ましい
+ 魔法／星は分離させても大丈夫か

> #118 (comment) でSound（On/Off）をSystemにまとめるという意見に賛成していたのですが、ちょっと方針転換させてください；

確かに、頻繁に利用するものではないのですが、すぐにOffにする需要はありそうですね^^;
「音量が～」というご指摘はたぶん、最初期の頃ですね～ボリューム機能というお話もあったのですが、主にUI的な問題で避けていたような記憶がｗ
現在もその事情は変わっていないのですが、他のものを大改訂するならば、合わせてやっておくべきかもしれませんね～

なお、コンパネの構造についても、最新版がわかりにくくなりそうだったので、リポジトリの方にマスターとして分離しました。今後、ご意見などありましたら、是非、こちらを適宜更新しつつ、議論させてくださいませ。
https://github.com/snext1220/snext-management/blob/master/control.md


> スマホ環境でのBackup／Restoreの利用方法

と、こちら、私の誤認識が一部混じっておりました。
正確にはスマホ環境ではなく、Safari（Macも含む）環境ですね...
よって、Android環境では問題なく動作します。
Safariでは、ダウンロード系の問題があるので、Pg含めて、現時点では要検討という状態です。Backupだけの問題ではないので、改めて検討してみたいと思います。

＃上のAudio系もそうですが、Monthly Updateを止めると言いながら、この辺は結局継続になってしまいそうですね^^;

**Comment by snext1220** [comment]
Issue整理中です。
他との重複があるもの、ある程度役割を終えたものをCloseしております。
当方判断で行っておりますが、もしCloseに問題あればReopenにしますので、なんなりとお申し付けください。

こちらは #127 Issueに議論の中心が移っているため、Closeします。
