### ISSUE TITLE
ステータスダイアログの改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#119]
#117 からの派生で、本Issueはステータスダイアログの改善案についてです。

### 改善ポイント

+ yuncoさんのレイアウト案に沿って、項目の並べ替えを行う予定です。
    + FREEだけが悩ましいのですが、横ぶち抜きにするかも。
+ ［+］［-］は赤で色揃え（他のカラーが赤系が多いため）
+ 入力ボックスの背景は白、フォーカス時のみの青適用

### 懸案

ステータス画面内部のボタンサイズについては、タブレット＋多少の?スマホ派を考慮して、維持したい派でおります。こちらは皆様のご意見をうかがえますと。

**Comment by yuco-mizuri** [comment]
FREE悩ましいですね！
私も悩ましいなと思いながらつくってました（汗

ボタンですが、タブレット、スマホだと丸くなりますね。
これはこういう仕様ですか？
![IMG_6390](https://user-images.githubusercontent.com/49935073/57223489-353ebd00-7041-11e9-8ee8-b82d64205a15.PNG)

PC版だと四角いので、長方形のボタンを正方形にするだけで少しすっきりするかな？と思ったんですがスマホ、タブレットのボタンを真円にするとおかしいですかね…

私の環境がアレだったらすみません↓ 
[PC] Mac Chrome使用
[タブレット] iPad pro Chrome使用
[スマホ] iPhone Chrome使用

**Comment by snext1220** [comment]
> FREE～～私も悩ましいなと思いながらつくってました（汗

あとから追加した要素でかなり無理やり入れている（更に、最初はFree2まででしたが、途中で3にしたり）＆項目名も後付けだったりするので、どうしても無理が出てしまいますね...

> ボタンですが、タブレット、スマホだと丸くなりますね。
> これはこういう仕様ですか？

いえ、ブラウザーの標準スタイルだと思います。
border-radiusで四角になるかな～と試してみたのですが、なぜか直らず、そのままに^^;

> PC版だと四角いので、長方形のボタンを正方形にするだけで少しすっきりするかな？と思ったんですがスマホ、タブレットのボタンを真円にするとおかしいですかね…

真円は問題なさそうなのですが、ボタンがそのまま小さくなるので（縦幅は広くし辛いので）、その辺がネックですかね...
＃ タッチパネルへの対応を全く度外視すれば良いのですが、個人的には思い切りづらく...

**Comment by toki-sor1** [comment]
現在、スマホやタブレット端末から読み物を楽しむという方も増えてきたことを考えると、**STextも** （PC環境に比べたら多少の不便はあるかもと思いつつも） **スマホやタブレットにも対応していけたらいいですよね。**

> FREEだけが悩ましいのですが、横ぶち抜きにするかも。

そうですね、2分割された中央に配置するのは厳しそうなので、**MAGICと同じく区切って横ぶち抜き**というのが、現状のデザインでは精一杯のような気もします……。

すみません、若干横道に逸れてしまいますが、**BONUSの影が薄いような気がします。**
2ページ目はそう頻繁に確認するものではないので、**1ページ目のJOBの下辺りにBONUSの表示があると、存在感が出るかもしれません。**

＃ただ、BONUSも一回確認すれば、あとはそんなに確認するものでもないかなって感じもしますし、画面がゴチャ付いてしまう可能性もあるので、リクエストとしては**優先度「低」です。**

あとは、**CLASS**に年齢も含めてAGEの表記を消すと、JOBが入れられるスペースが確保できるような気がします。
顔グラ（イラスト）が表示されるので、**そこまでAGEを強調する必要もないかな**と思ったので。

しかし、それが果たして実現可能なのかも、更には工数すらも分かっていないので（大汗）、こちらもやはりリクエストとしては**優先度「低」です。**

**Comment by snext1220** [comment]
> スマホやタブレットにも対応していけたらいいですよね。

ちなみに、過去四半期の統計を確認したところ、モバイル41％、タブレット8％で、半数近くがモバイルという結果でした。やはり無視はしにくそうですね。。

> BONUSの影が薄いような気がします。
BONUSについて、ご指摘の通り、CLASS AGEなどをまとめると、一行空くので、入るかと思います～
ただ、これまた仰るようにBONUSがそれほど何度も見る情報ではない and 上に集まっている基本情報とは別種なため、若干悩んでおります^^;

そこで亜案として、以下のようなものを。如何でしょうか。

+ BONUSダイアログで現在適用されているボーナスをアクティブ表示する
+ シナリオ開始時に適用されたボーナスをトースト通知する
+ STATUSダイアログからBONUS欄を削除する

> あとは、CLASSに年齢も含めてAGEの表記を消すと、JOBが入れられる～～

こちらはそれ単体では問題ないと思います。
ただ、そもそもSText 2.0（モバイル対応）を進めるかによって、どのタイミングで実施するかは要ご相談ですね…！

**Comment by yuco-mizuri** [comment]
ボタンサイズについては、「誤タップを防ぐ>画面をスッキリさせる」という優先順位で正しいと思うので、リオさんの感覚的に小さくしたくない、ということであれば現状でよいと思います。
参考) https://www.dotproof.jp/2013/08/06/minimum-tap-size/

あとはよくある生年月日の入力フォームのようにくるくるくる〜っと数値が選べる…とか…
（技術的なことは全く考えずに言っております！^^;）

これ以上大きくできないという状況で、より改善しようとする場合、ボタンとボタンの間を開けるといいかもしれませんね。

早急な問題でないのなら、もう少しスマホのゲームUIなど研究したいかなと思うのですがいかがでしょう？
実際ここまで細かい数値をいじるゲームというのがあんまり存在しないかもしれませんが…
なにか情報あれば共有お願いします…

----------------------------------------
【BONUS】
確かにBONUSが今ついてるのがどうかよくわからずにプレイしてました。
（というかついてるものだと思ってた？）
なんらかの形で今適用されているBONUSを表示するのは良いと思います。

ちょっとBONUSをすべて把握してないので
「常に確認できるようにする」「話の冒頭のみトースト表示する」どちらが適切か、
BONUSの種類によって変わったりするのか、要検討です。

**Comment by snext1220** [comment]
> 早急な問題でないのなら、もう少しスマホのゲームUIなど研究したいかなと思うのですがいかがでしょう？

はい、ステータスダイアログはゲームそのものの自動化で、当初よりは重要度が落ちていると思いますし、そもそもSText 2.0を検討する場合は相当（というか膨大な）時間がかかるので^^;、「もう少し研究」賛成です！

仰るように、ここまで入力欄の多いゲームがないと思うので、あるいは業務アプリの世界かもしれませんが（ただ、そういう資料ってゲームの世界よりも更に見かけませんよね...；）

> あとはよくある生年月日の入力フォームのようにくるくるくる〜っと数値が選べる…とか…（技術的なことは全く考えずに言っております！^^;）

技術的には可能ですｗ
ただ、入力項目が多いため、ポップアップ、くるくる～の操作が却って煩雑かと、現時点では採用していませんでした。
＃あとは、ライブラリ導入が前提になるので、デザインをカスタマイズする際にはネックになるかも？

> これ以上大きくできないという状況で、より改善しようとする場合、ボタンとボタンの間を開けるといいかもしれませんね。

はい。ただし、その場合は項目数も多く、そのままダイアログ領域が広くなるので、ステータスダイアログを複数タブ（現在も2ページ）でより細かく分割する必要がありそうです。
＃ #118 でも触れていますが、そもそもコンパネを階層化するならば、アイテム／フラグ（場合によってはメモ、魔法も？）など、ある程度用途に応じて別ダイアログに分けても良いのかも？

> ちょっとBONUSをすべて把握してないので「常に確認できるようにする」「話の冒頭のみトースト表示する」どちらが適切か、BONUSの種類によって変わったりするのか、要検討です。

常に確認させるのは五月蠅そうなので、最初にトースト表示で、あとは自動化をある程度進める、といったところなのかなと（現在はすべて手作業なので、真面目に適用している人は少なそうｗ）。

以下はコードからの抜粋なので若干見難いのですが、ボーナスの一覧です（ご参考）。

```
'gi01' : { name: '金の卵', desc: '月の欠片を5個所有した状態で冒険を開始' },
'gi02' : { name: 'ガラティーン', desc: '火星の欠片を5個所有した状態で冒険を開始' },
'gi03' : { name: '五元素のマント', desc: '水星の欠片を5個所有した状態で冒険を開始' },
'gi04' : { name: 'アマゾンの剣', desc: '木星の欠片を5個所有した状態で冒険を開始' },
'gi05' : { name: '幸福のコイン', desc: '金星の欠片を5個所有した状態で冒険を開始' },
'gi06' : { name: 'ムラサメブレード', desc: '土星の欠片を5個所有した状態で冒険を開始' },
'gi07' : { name: 'G・スレイヤー', desc: '太陽の欠片を5個所有した状態で冒険を開始' },
'gi08' : { name: '水晶の剣', desc: '左サイコロが5以上の時、そのシーンでHPを1回復' },
'gi09' : { name: '王様の杖', desc: '左サイコロが5以上の時、そのシーンでMPを1回復' },
'gi10' : { name: 'ブルーリボン', desc: '戦闘ダメージを1減算' },
'gi11' : { name: '王家のダイヤモンド', desc: '罠ダメージを1減算' },
'gi12' : { name: '不老長寿の水', desc: '冒険中に一度だけHPを半分回復できる' },
'gi13' : { name: 'タリスマン', desc: '冒険中に一度だけMPを半分回復できる' },
'gi14' : { name: '鏡の盾', desc: 'HPダメージを1減算' },
'gi15' : { name: '銀の竪琴', desc: 'MPダメージを1減算' },
'gi16' : { name: 'パンドラの箱', desc: '右サイコロが4以上の時、戦闘回避が可能' },
'gi17' : { name: '魔法の絨毯', desc: '右サイコロが5以上の時、罠回避' },
'gi18' : { name: '中和剤', desc: '毒耐性' },
'gi19' : { name: '聖水', desc: '呪い耐性' },
'gi20' : { name: 'チルドの実', desc: '凍結耐性' },
'gi21' : { name: '銀のハーモニカ', desc: '石化耐性' },
'gi22' : { name: '真実の鏡', desc: '忘却耐性' },
'gi23' : { name: 'D・スレイヤー', desc: 'すべての星を1個所有した状態で冒険を開始' },
'bgi01' : { name: '塩酸', desc: 'シーン毎にダイス合計が5未満でHPを1減算、5以上でMPを1回復' },
'bgi02' : { name: '紅玉', desc: 'シーン毎にダイス合計が5未満でMPを1減算、5以上でHPを1回復' },
'bgi03' : { name: '血まみれの斧', desc: '冒険開始時に呪い。解除で3回まで星消費せず魔法発動可' },
'bgi04' : { name: 'トリカブト', desc: '冒険開始時に毒。但し、解除までシーン毎にMPを1回復' },
'bgi05' : { name: 'ギャルのパンティー', desc: '冒険開始時に忘却。解除までSTR/INT0でない方を10' },
```

**Comment by toki-sor1** [comment]
皆さん、ご提案やご回答ありがとうございます。
内容的に複雑化し易い話題なので、適度に省略しながら返信しますね。

### モバイルからのアクセス数増加

おお、モバイルからのアクセス数がかなり増えてますね！
STextページ切り離し後にモバイルからのアクセスが増えたとのお話ですし、プレイヤーさんの間でも**「ちょっと不便なところはあるけど、スマホからでも遊べる」という認識が広がってきている**　のかもしれませんね。

今後ますますモバイルも便利で高性能になってゆくと思いますし、**将来を見越してモバイル対応は必須かな**と思えてきました。

### BONUSの扱いについて

改めて、ご提案ありがとうございました！
個人的には、 **「シナリオ開始時に適用されたボーナスをトースト通知する」** が良いかなと思いました。

「BONUSの種類によって自動適用」も有りかなと思ったのですが、**適用するものとしないものが混同することで、逆に混乱を招いてしまいそうな気がします。**

もしステータスダイアログの複数タブ対応が可能になったら、 **「トースト化」＋「優先度の低いタブに移す」** のが良いかもしれませんね。
（ステータスからBONUS自体を消してしまうのは、BONUSの存在感と価値が極限まで薄くなってしまいそうな気がするので、できればステータスの何処かには入れていただけたらなぁと；）

### AGE表記について

> こちらはそれ単体では問題ないと思います。
ただ、そもそもSText 2.0（モバイル対応）を進めるかによって、どのタイミングで実施するかは要ご相談ですね…！

単体ではまとめることも可能なのですね、承知しました！
現在ではまだ方針が定まっていないので、この話題はまた後日ですね。

### スマホのゲームUIの研究

そうですね。現代ではソシャゲはもちろんのこと、コンシューマーゲームがスマホゲームとして移植されているケースもありますもんね。
**こういったモバイル環境に最適化されたUIを観察し、研究することは、STextページ改装において大いに意味のあること**だと思います！

**Comment by snext1220** [comment]
あ、誤解があったようなので、補足です～
BONUSをステータスから削った場合にも、ボーナス表記がなくなるわけではなく、BONUSダイアログに表示を移動しようという案でした。

先との重複になりますが、STATUSダイアログは既に情報過多で、恐らくこのままの構成で整理を図っても限界があるのかなと^^; であれば、（ボーナス表記だけでなく）ダイアログ自体を用途ごとに細分化しては、と（＝コンパネも1階層目がきちんと整理できていれば、2階層目はそれなりには増やせるのではないか）。

+ ステータス系
    + ステータス（基本情報～HP系、STR系、FREEまで）
    + 魔法（7星、魔法発動）
    + メモ（これは一寸悩ましい）
+ 情報系
    + アイテム一覧
    + フラグ一覧
    + ボーナス（現在アクティブなものを強調表示）
    + 実績

**Comment by toki-sor1** [comment]
> あ、誤解があったようなので、補足です～
BONUSをステータスから削った場合にも、ボーナス表記がなくなるわけではなく、BONUSダイアログに表示を移動しようという案でした。

あわわ、勘違い失礼しました……！　補足ありがとうございます！！
BONUS表記は消える訳ではないのですね、安心しました！

> STATUSダイアログは既に情報過多で、恐らくこのままの構成で整理を図っても限界があるのかなと^^; であれば、（ボーナス表記だけでなく）ダイアログ自体を用途ごとに細分化しては、と（＝コンパネも1階層目がきちんと整理できていれば、2階層目はそれなりには増やせるのではないか）。

確かに今の情報過多な状態で整理しようとしても、配置にも制限が掛かっていて、再構成が難しいですもんね；
サイトのメニューまとめに通じるところがありますが、**ダイアログを用途ごとに細分化、いいと思います！**

**Comment by snext1220** [comment]
https://github.com/snext1220/stext/issues/127#issuecomment-539513305 を受けて、ステータスダイアログの分割、サイドバー化を開始しています。GitHub Pagesでのみ、以下の機能が動作していますので、ご確認ください。

+ Basic
+ Items & Flags
+ Player Rank

@toki-sor1 さん＞お手数ですが、デザインについては完全に仮状態なので、カラー／背景などご検討頂いても宜しいでしょうか（背景なしでただの黒背景でも良いかとは思っています）。

引き続きMagic、Statusなどのサイドバー化も進め、それらがFixした後、新コンパネ（メニューバー）をリリースの予定です。

＃サイドバー化がこれだけ進むと、先般のBonus、Resultsもデザイン統一しつつ、サイドバーにまとめた方が良いかもしれませんね。

**Comment by snext1220** [comment]
上記に続いて、以下のサイドバーを対応しました。

+ Status
+ Magic
+ Result
+ Bonus

これで一応対応すべきものがすべてサイドバー化されたはず。
古いコントロールパネルの機能も動作しているため、一部の機能が競合して、変な動作をする場合がありますが、デザインなど確定したところで、旧コンパネは破棄していければと。

＃ 実は、内部的にはかなりの改修だったので、ここから大規模なコードの整理（削除）が始まります。動作テストまでにそこまで済ませたいところではありますが、結構気を遣うところなので、どうなるか^^;

@toki-sor1 さん＞お忙しいところ恐縮ですが、全体のデザインについてお手すきの折にもご検討頂けますと幸いですm(_ _)m

**Comment by toki-sor1** [comment]
お返事が遅くなってしまい申し訳ありません…！（本当にこればっかりで；；）
デザインについて、全体＆各項目毎に意見を書いていきますね。

> 全体のカラー／背景

黒背景でややシンプルかな、という印象も受けますね。
ただ、項目によっては横幅ギリギリまで文字が表示されているので、視認性を重視するなら、そのままの方が見易くて良いのかなと感じました。
現状での皆さんのご意見も参考にできれば、と思っています。

カラーについては、黒背景なので基本的に旧版の配色が良さそうかなと思います。

> 各サイドバーに［Status］［Results］のようなロゴが必要でしょうか？

- ロゴがあると、ぱっと見の印象も豪華になりますよね。
- 黒背景＋背景画像なしの組み合わせであれば、ロゴを画像にするというのも有効かもしれません。
- 文字色を変えるだけであれば、旧版のキャラ名に使用している、やや黄色っぽい白色にしてみるのは如何でしょう？

> Status
- キャラ名や顔グラなどの情報（Basic）と一緒に表示されないのが、やや違和感がありました。
  - 縦幅の問題もありますが、個人的には「名前～JOB」までセットで表示しても良さそうな感じです。
- キャラ名は新版も前と同じ配色（赤紫＋黄色っぽい白）だと良いなと思いました～
  - そうするとMemosはとなりますが、こちら、実は「Items & Flags」とセットの方が使いやすいのではと（項目名が未知ですが；）。
  - フラグはプレイヤーからすると、そこまで気にするものではないかなーと思うので、旧版と同じ表示方法かつ、「items ＆ Memos」にして、そこにFlagsを含めてしまうのも有り…？

> Magic、Result、Bonus

- 問題ないと思います！

> Sound(On／Off)

- 実際に新版を触っていて、ここにすぐアクセスできないのが、ちょっと気になりました。
  - 個人的には、旧版のようにぽちっと切り替えられる感じだと、使いやすいなと思いました。

**Comment by snext1220** [comment]
@toki-sor1 さん、ご意見ありがとうございます！

> 黒背景でややシンプルかな、という印象も受けますね。ただ、項目によっては横幅ギリギリまで文字が表示されているので、視認性を重視するなら、そのままの方が見易くて良いのかなと感じました。

は、現時点ではデザインは未対応（最小限）でしたが^^;、意外とすっきりと良いのかもしれません。今回はTemporaryということで、「機能のみのリニュ＋本格的なデザイン検討は今後」とは思っておりますが、どう進めていきましょうかね...
＃ お手数ですが、プレグラ／幕末が落ち着いたところで、ときのじさんの方でデザイン案を検討いただき、皆さんのご意見を募るという感じで大丈夫でしょうか（汗

> カラーについては、黒背景なので基本的に旧版の配色が良さそうかなと思います。
> ロゴがあると、ぱっと見の印象も豪華になりますよね。

はい～若干殺風景な気はしますので、飾りなどは各シート統一でロゴ化できるとよいのかな、とは。ただ、シンプルイズベストというご意見もありそうなので、皆様のご意見に従います！

> 縦幅の問題もありますが、個人的には「名前～JOB」までセットで表示しても良さそうな感じです。

ここは悩んだのですが、STATUSに統合すると、モバイル環境では肝心のステ情報がスクロール要になってしまいそうですね...（情報的にもほとんど利用しない名前、CLASSなどを上に配置せざるを得ないですし、却って煩わしいかも？）
で、BASICとしてわけるとすると、MEMOSとセットが分類的にも分量的にも収まりが良い、という流れでした^^;

ということで?、こちらスミマセン、確定でないにせよ、現状で一旦据え置かせていただき、慣れを見させていただいてもよろしいでしょうか（もちろん、将来再度ご意見戴いての修正は可能でございます！）

> Sound(On／Off)
> 実際に新版を触っていて、ここにすぐアクセスできないのが、ちょっと気になりました。

こちらも以前伺っていて若干悩んだのですが、「デバッグ時を除いては頻繁にオンオフするものではないかな」「STATUS、MAGICと比べると優先順位が落ちるため同列に並べるのに違和感あり？」ということで、二段目に落としておりました^^;

悩ましいですが、もう少しほかの皆様のご意見もうかがう、という感じでよろしいでしょうか？（汗
＃ もし一段目にあげるとしたら、右端にスピーカーアイコンなどを設け、他のメニュー項目とは区別した方がよいかもですね～

**Comment by snext1220** [comment]
本Issue、機能面は一旦落ち着いてきましたので＆デザイン面はまだ時間もかかるかと思うので、一旦Closeさせていただき、デザイン検討中心に新Issue #152 で進めていければと。引き続きどうよろしくお願いします…！
