### ISSUE TITLE
シーン内での簡易な条件分岐

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#12]
謙信、ドラスレなど拝読していての案です（以前、Excelベースでも出ていた内容の亜案です）。

以下のような、特定のフラグ／アイテムを所有している場合にだけ表示されるブロックを表現できるようにしても良いのかなと。

```
${if i10}
i10を所有している場合にだけ表示されるテキスト
${/if}
```

現状でもシーンを分ければ良いだけなので、あまり複雑な実装まで手掛ける気はなく、フラグ／アイテムがある場合（複合条件はなし、not条件もなし）、程度かなと。

気軽に、あるフラグ／アイテムがある場合にテキストを追加したい場合の用途、を想定しています。
優先順位的には低だとは思いますが、完全に新機能なのと、実装する際には後から変更は影響が大きくなる恐れがあるため、互換性問題あり、としています。

**Comment by toki-sor1** [comment]
実装に賛成です。
2つのシーンの違いが、たったの数行しかないのであれば、それでシーンを分けて消費するのが
勿体ないように思えたからです。

**Comment by snext1220** [comment]
とりあえずアイテム／フラグ条件（複合条件は認めず）で分岐を可能にしました（マニュアル反映済み）。あまり複雑な分岐はそぐわないかとは思いますが、もしも今後ニーズが出てきたら、条件の追加は検討します！

**Comment by RYU-DS** [comment]
うーんこれまた、コレがあればNPCによる文章差に対応できて複数作らなくてもよくなりますねー。
まぁ自分は結局、どうせ別シーンで作り直すなら、と話の流れに合わせて文章全体を調整したのですが、結果的に良くはなったから別にいいかなと思っていますが…
こういうので手数が減らせれば、制作期間も短縮できるかと。
