### ISSUE TITLE
Sceneリストの新設

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#120]
#110 、#114 を受けて、新規Issueに分けています。
以下はSceneリストの実装方法について、既出の案を再掲しておきます。

+ 3カラム式にして、左端にSceneリストを加える
    + 懸案：右ペインが狭めにくいので、チャートエリアを主に狭めると、結構見た目にも厳しいかも？
+ 「Sceneリストを常時利用する？」というのもありまして、ある程度限定的な用途であると考えると、以下のようなスライド式パネル（ https://oncebot.github.io/pushbar.js/ ）などで良いのかも。
+ 常時表示を優先する場合は、（横リストにはなりますが）チャートエリアの下部分に表示
+ もっと軽くドロップダウンリスト（https://designwithpc.com/Plugins/ddSlick#_=_ ）として、［テンプレートを選択］の隣に表示

実装方法については、お手数ですが、引き続きご意見戴きながら検討進めていきたいと思います。

**Comment by snext1220** [comment]
New Pg上部の右上に選択ボックスとして追加しました（GitHubの未反映）。
もう少し目立つUIにしても良いかなとは思ったのですが、まずは機能実装を優先した方が良いかなということで。見た目のご要望あれば、引き続きご意見戴けますと幸いです。

**Comment by toki-sor1** [comment]
https://snext1220.github.io/stext/playground/

実装お疲れ様です～！
PCから拝見・動作確認致しましたが、下記の点が良いと思いました！

- リストから編集したいシーンを選ぶと、選択したフロチャが前面に出てくる
- シンプルゆえに操作も容易で、とても見易い
- リストが収納されているので、
  - 幅も取らず、デザインを邪魔しない
  - 操作の邪魔にならない

最初は、リストがずらっと表示されているのをイメージしていましたが、フロチャがその役割を果たしているようにも感じるので、選択ボックス式も良いなと思いました。

また、個人的には、このリストはアイコン化するよりも、このままの選択ボックスの方が、分かり易くて良いかなと感じました。

***
それとはまた別件なのですが、シーンタブを開くと下記のように一部表示が見切れていました～。
（Win 8.1 Chrome 77.0.3865.75にて動作確認）

![image](https://user-images.githubusercontent.com/42646342/65042098-1ce99200-d993-11e9-80fb-b4a4230b6f4d.png)

**Comment by snext1220** [comment]
ご確認有難うございます！まずは、大きく問題なかったようでホッと^^;

> 最初は、リストがずらっと表示されているのを～～

はい、私もそんなイメージでしたｗ
ただ、デザインへの影響が大きいことから現在のような形に。
結果としては「このままの方が」とのことでよかったです～
Scene数が増えてきた時に課題が出てきそうですが、また使いながらご意見頂戴できますと幸いですm(_ _)m

＃ 現在はプロローグとエンディングとに★マークを付けて区別つくようにしています。 色分けが難しかったので、このような感じになっていますが、如何でしょうか（汗

> 一部表示が見切れていました～。

こちらもご報告有難うございます！
STR～KRMの追加での溢れでした^^; 現在諸々動かしているもので、機能的な改修を終えたところで見た目はまとめて修正させて戴きますね。少々お待ちくださいませ～

**Comment by cocotori** [comment]
いいと思います。
前も触れましたが、
グラフィカルなフロー図があったとしても
こういう列挙的なリストは必要に思うので、
便利な機能だと思います。

**Comment by snext1220** [comment]
ありがとうございます！
まずは問題なさそうで良かったです！

実はグループによる階層化も考えたのですが、各シーン1グループの対応関係ができている必要があるので、今回は見送りました（その辺、もしご要望あればまたご相談させてください＞皆さん）。

**Comment by toki-sor1** [comment]
お返事が遅くなってしまい、申し訳ありません…！

> Scene数が増えてきた時に課題が出てきそうですが、また使いながらご意見頂戴できますと幸いですm(_ _)m

はい～、何か気になるところが出てきましたら、お知らせ致しますね！

> ＃ 現在はプロローグとエンディングとに★マークを付けて区別つくようにしています。 色分けが難しかったので、このような感じになっていますが、如何でしょうか（汗

フローチャートの方で色が変わっているので、こちらは★マークが付いていれば十分見易い＆内容が把握できると思います～。

> STR～KRMの追加での溢れでした^^; 現在諸々動かしているもので、機能的な改修を終えたところで見た目はまとめて修正させて戴きますね。

修正ありがとうございました＆お疲れ様でした！
PCからの確認ですが、正常に表示されていました！

**Comment by snext1220** [comment]
ご確認ありがとうございます！
フロチャとのセットで問題なしとのことよかったです！
＃ ★については、場合によっては、フロチャ同様、プロローグ／Happy／Endで区別することも可能なので、必要に応じてお申し付けください…！
