### ISSUE TITLE
ゲーム画面のスクロール改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#121]
#117 からの派生で、本Issueはゲーム画面の改善です。

> 文を読み、ダイスを振り、ステータスを割り振り…の動作で、文章量によっては何度も上下スクロールをする必要があります。文を読みながらスムーズに動的要素に触れられるようにしたいと感じました。例えば、下にスクロールでコントロールパネルがついてくる…文章部分をスクロールバーボックスにする…など （シナリオやシナリオ内の要素管理の煩雑さが不明なため要検討）

現時点では、前掲のIssueでも触れたように以下の方針でおります。

**ページでの操作途中で、ヘッダー（コンパネ）に頻繁に触れることはないと思われるので、対象は以下に絞る。**

+ モンスター情報
+ 簡易ステータス
+ ダイスの配置

以上の情報を「下からのスライドパネル」として実装するか。

もっとシンプルに「本文のボックス化」とすれば、修正規模は局所化できますが、現状のダイスとモンスター一覧が若干離れているのが使いづらいか。とすると、やはりスライドパネルとして再編するのがベターと判断しています。

まずは、上記方針についての皆さまのご意見を戴ければ幸いですm(_ _)m

**Comment by cocotori** [comment]
スライドパネルがいいか本文ボックス化がいいかは
ちょっと判断つきませんが、

戦闘で使う、モンスター情報・簡易ステータス・ダイスを
ひとまとめにするのはいい案だと思います！

**Comment by toki-sor1** [comment]
うーん、私も本文ボックス化と下からのスライドパネルのどちらが良いのかは判断が難しいのですが、ココさんと同じく**モンスター情報・簡易ステータス・ダイスをひとまとめにするのは良いと思います。**

> 【ゲームブック本文】
文を読み、ダイスを振り、ステータスを割り振り…の動作で、文章量によっては何度も上下スクロールをする必要があります。
文を読みながらスムーズに動的要素に触れられるようにしたいと感じました。
例えば、下にスクロールでコントロールパネルがついてくる…
文章部分をスクロールバーボックスにする…など （シナリオやシナリオ内の要素管理の煩雑さが不明なため要検討）

ああっと、すみません！
https://github.com/snext1220/stext/issues/117#issuecomment-488267123 で見落としていたところがありました……！（大汗）
上記の @yuco-mizuri さんのご意見について、もしかしたらと思い、念のため一点補足でございます～。

（スマホ環境だと無効な操作となるので、やはり何処かで対応しないといけないとは思うのですが） **PC環境ではゲーム画面上のどこでも右クリックすると、詳細ステータスが表示されます～。**

**ソーサリアンText プレイヤー向けマニュアル**
https://sorcerian.hateblo.jp/entries/2017/12/20

**Comment by snext1220** [comment]
ご意見有難うございます。

ひとまとめ＞こちらはほぼ同意を戴けた感じですね。
実装方法については、恐らく https://github.com/snext1220/stext/issues/122#issuecomment-490314531 の「レスポンシブ対応」「非ソーサリアン層訴求のデザイン見直し」を対応するかによって変動しそうです。グラグラしてしまって恐縮ですが；、この辺、今一度ご意見頂戴できますとm(_ _)m

＃この決定によっては、 #123 のSText 2.0が前提になるため、進め方も結構変わってきそう^^;

> ゲーム画面上のどこでも右クリックすると、詳細ステータスが表示されます～。

ご指摘ありがとうございます！
こちら #118 のコンパネ改善案で議論中なので、コンパネ表示内容の優先順位共々、ご意見戴けますとm(_ _)m

**Comment by yuco-mizuri** [comment]
#119 で判明したモバイルとタブレットでほぼ50%というのを考えるとレスポンシブは必須というのが私の意見であります…

レスポンシブで、テキストボックスは各デバイスに最適化できるのか？というところが疑問なので
レスポンシブにするならスライドパネルがよいかなと思います。
あと長いテキストボックスとその外の情報がストレスなく閲覧できた経験というのがあんまりない気がします…。だいたいなんか変な挙動な気が…


>（スマホ環境だと無効な操作となるので、やはり何処かで対応しないといけないとは思うのですが） PC環境ではゲーム画面上のどこでも右クリックすると、詳細ステータスが表示されます～。

あ、そうなんですね！ありがとうございます。
操作性を見るにあたり、わざとマニュアル読まずにプレイしてたのですが
「マニュアルを読まないと理解できない」という点をなるべく排除するのも今回のサイトリニューアルでやりたいことでした。（すみません、私の中で勝手に思っていて、明文化してませんでした）

完全になくすというのは無理だし不親切ですが、目標をそこに置いておけばそれぞれのリニューアルの方向がはっきりするかと思うのですがいかがでしょう？

-----
なんでマニュアルがなくても遊べるようにするべきか

一見さんをなくすためです！
多様な作家さんがたくさんの作品を発表していてすごく充実したサイトなのに
遊び方がわからないと**コア**な「ソーサリアン好き」と「ゲームブック好き」しか遊んでくれないからです。
最近のありとあらゆるゲームがほぼそうですがマニュアルはほぼ存在せず、チュートリアルで大体理解できるようになっています。

そして「基本的なことを遊べるようになったら」自分で細かい部分を調べたり、
少しずつ使える機能を増やして慣らしたりします。
最初のハードルを下げることが大事だと思っています。

**Comment by snext1220** [comment]
> 「マニュアルを読まないと理解できない」という点をなるべく排除するのも今回のサイトリニューアルでやりたいことでした。（すみません、私の中で勝手に思っていて、明文化してませんでした）

いえいえ、STextチームとしても、まさにこの認識（目標）でした。
理由も強く同意でございます。

（ここは言い訳→）と言いながら、度重なる高機能化で、特に戦闘周りがマニュアル抜きではわかりにくくなってきている状態で、結局マニュアル改訂で逃げている、という状況でした；この辺は、デザイン刷新の上で、チュートシナ（not マニュ）も新設したいなと思っています。
＃本来であれば、Scena1「新・王杖」がその役割を担うべきなのですが、実装が古くなっているので、たぶん、新設した方が早い＆建設的^^;

> レスポンシブで、テキストボックスは各デバイスに最適化できるのか？というところが疑問なので、レスポンシブにするならスライドパネルがよいかなと思います。

最適化、についてはメディアクエリを使えば限りなく制御できると思うのですが、スタイル開発については門外漢なので^^;、できるだけシンプルにしておきたいと考えると、基本は％指定＋α程度かなと^^;
＃ その他でもメディアクエリは極力避けて、（レスポンシブ対応する場合は）Flexレイアウトの範囲で検討していきたいと思っています^^;

> レスポンシブは必須というのが私の意見であります…

ですね...半年くらい前のおぼろげな記憶ではモバイル割合はずっと少なかったはずなのですが、恐らく今年2月に行ったサイトリニューアル＆SEO対策で急激に高まったのではないかと推測しています。

レスポンシブ対応（要は大規模対応）は、私自身も時間をかけてでもやらざるを得ないかな、との意見に傾きかけていますが、スミマセン、規模的に私も独断できないので、スタッフ面々の意見を待たせてください^^;

**Comment by toki-sor1** [comment]
返信が遅くなり申し訳ありません……！
共通した話題が多いので、 @snext1220 さんと @yuco-mizuri さんへの返信を同時に行っていきますね。
***
> 操作性を見るにあたり、わざとマニュアル読まずにプレイしてたのですが
「マニュアルを読まないと理解できない」という点をなるべく排除するのも今回のサイトリニューアルでやりたいことでした。（すみません、私の中で勝手に思っていて、明文化してませんでした）

いえいえ、こちらこそ早とちり失礼しました！
確かにゲームだと特に「遊ぼうと思って手を出したはいいものの、システムが複雑過ぎて挫折してしまう」とか「UIが分かり難くてストレスを感じてしまう」ということはよくある話ですもんね；

> 完全になくすというのは無理だし不親切ですが、目標をそこに置いておけばそれぞれのリニューアルの方向がはっきりするかと思うのですがいかがでしょう？

はいー、**分かり易いのはどの層にとっても大事なこと**だと思います！
それに、コアな層だけでなく、ゲームをライトに楽しみたい層や、ソーサリアンは知らないけどSTextに興味あるよ層にも親しんでいただけるようなものを目指していきたいですね！

> と言いながら、度重なる高機能化で、特に戦闘周りがマニュアル抜きではわかりにくくなってきている状態で、結局マニュアル改訂で逃げている、という状況でした；この辺は、デザイン刷新の上で、チュートシナ（not マニュ）も新設したいなと思っています。

そういえば、今までシナリオを作る側のチュートリアルはありましたが、**シナリオをプレイするためのチュートリアル**ってありませんでしたね；（盲点でした；）

戦闘周りは確かに複雑でマニュアル抜きだとわかりにくいところはあると思いますが、それでも、**シナリオプレイの基本操作を覚えるチュートリアルシナリオ**があるとないとでは、とっつき易さが違ってくるかなと思います。
***
ちょっと自分の中でUI（デザイン）とシステム（戦闘ルール等）が混ざってきてしまったので一旦整理しますが（汗）、

- UI（デザイン）については、マニュアルなしでも「これはこういう機能だな」と理解でき、基本的な操作を覚えられるような、わかりやすいものを目指す（戦闘ルール等の把握とはまた別の問題）

- システムについては、マニュアルはそのままに、シナリオプレイの基本操作を覚えるチュートリアルシナリオを実装する（UIのみではどうしても理解しづらい戦闘ルール等をフォローする）

という感じが良いのかなぁと思いました。
＃場合によっては、**UIの変更に合わせてシステムも変更する必要が出てくるのかも**しれませんね。
***
> レスポンシブ対応（要は大規模対応）は、私自身も時間をかけてでもやらざるを得ないかな、との意見に傾きかけていますが、スミマセン、規模的に私も独断できないので、スタッフ面々の意見を待たせてください^^;

私個人の意見になりますが、STextリリースから時間が経ち、スマホやタブレット等のモバイル環境からでも（やや不便はあるものの）遊べることが周知されてきたように思います。

今後ますますスマホやタブレットの性能が良くなり、できることが増えてゆくと思いますし、**プレイヤーさんのコア層・ライト層は問わず、手軽にどこでも遊べるゲーム**というのは需要があると思うんですよね。

そう考えると、モバイルからのアクセスは今以上に増えそうですし、プレイヤーさんは快適に遊べる環境を望まれると思いますので、可能であれば**STextのレスポンシブ対応も進めていけたらいいなぁ**と思いました。

**Comment by snext1220** [comment]
> そういえば、今までシナリオを作る側のチュートリアルはありましたが、シナリオをプレイするためのチュートリアルってありませんでしたね；

あは、新・王杖は、一応当時は、チュートの位置づけで作成していたのでした^^;
戦闘シスが当時から大きく変わってしまったので、現在ではアレなんですがｗ
STextは日常的にシステム更新が継続しているので（しかも結構根本で）、新チュートを作成する場合も、どこまで作り込むかは悩みの種ですね；

> 可能であればSTextのレスポンシブ対応も進めていけたらいいなぁと思いました。

はい、是非とも！
こちらは、最初、根本的にSText 2.0を開発する案を出していたのですが、見積もっていくと、大改訂どころの騒ぎではないので；、1.xをベースにしてコンパネ／ダイアログ周りにどれだけ手を入れるかで悩み中です。

新サイトのデザインにアプリを載せてみて、そこから調整＆検討という形になると思うので、かなり長丁場になるかと思いますが、気長にお付き合い頂けますとm(_ _)m

**Comment by toki-sor1** [comment]
> あは、新・王杖は、一応当時は、チュートの位置づけで作成していたのでした^^;
戦闘シスが当時から大きく変わってしまったので、現在ではアレなんですがｗ

ああ～～～！！　STextの記念すべき第1作目ですもんね！！！
うっかり発言、大変失礼しました……！！（大汗）

> STextは日常的にシステム更新が継続しているので（しかも結構根本で）、新チュートを作成する場合も、どこまで作り込むかは悩みの種ですね；

そこが難しいところですよねぇ……；
道場も今や情報が古く、ソーサリアン達の交流を楽しんでいってね……！！！的な感じになってしまいましたからね～。

チュートリアルが今後そうなる可能性がないとは言い切れませんし、**サイト＆ゲーム画面改装の目処が付いた頃に構成を考えるのが無難なのかな**という気はしています；
***
> こちらは、最初、根本的にSText 2.0を開発する案を出していたのですが、見積もっていくと、大改訂どころの騒ぎではないので；、1.xをベースにしてコンパネ／ダイアログ周りにどれだけ手を入れるかで悩み中です。

SText 2.0 #123 を拝見しました。
技術的な部分やそれに掛かる労力については、こちらの知識不足で具体的にイメージするのがなかなか難しいのですが（す、すみません；）、ドワーーーッ！と並んだスケジュールやリストから、とんでもない状況になっていることは伝わってきます……；

> 新サイトのデザインにアプリを載せてみて、そこから調整＆検討という形になると思うので、かなり長丁場になるかと思いますが、気長にお付き合い頂けますとm(_ _)m

はい～、こちらこそ引き続きよろしくお願いします！
しぬでないぞ……

**Comment by snext1220** [comment]
> ああ～～～！！　STextの記念すべき第1作目ですもんね！！！
> うっかり発言、大変失礼しました……！！（大汗）

あ、いえいえ、私もチュートとは明文化していませんでしたので^^;
SText自体が、基本どこからでも始められるゲームなので、当時、明示的にチュートと謳っていなかったので、中途半端感はあ（ry

> そこが難しいところですよねぇ……；
> 道場も今や情報が古く、ソーサリアン達の交流を楽しんでいってね……！！！的な感じ
> になってしまいましたからね～。

そうなんですよね；；
自動化がある程度落ち着いてきた＆道場のようにキャプチャは利用しないはずなので、もう少しは影響防げると思うのですが、それでも、ですよね...

タイミングについては、仰るように、改定目途に、とのこと賛成です！
＃そもそも「王杖」は、タイトル自体がソー層にはチュートと識別できるのですが、新チュートで「王杖」に相当するタイトル（シナ）があるかは悩ましく。その辺からじっくり選別していければと（強募ｗ）。

> 技術的な部分やそれに掛かる労力については、こちらの知識不足で具体的にイメージするのがなかなか難しいのですが（す、すみません；）、ドワーーーッ！と並んだスケジュールやリストから、とんでもない状況になっていることは伝わってきます……；

ご覧戴いてありがとうございます！
現在の1.xは既に改定が困難な状態になっているので、一から作るとなると、この2年近くの作業を一からになりますからねぇ...（勿論、再利用できるコードは部分的にあると思いますが、ほぼゼロスタートになりますし、仕様そのものも現状を引き継ぐとはいえ、議論なしでは決まらないと思いますし；）

こちらにどっぷり浸かってしまうと、シナリオには到底手が回らなくなってしまうので、現時点では1.xの改訂を阻害している部分を改築しながら、なんとか…と現時点では；
2.0は、シナリオの外部投稿がゆっくりとでもされるようになってきたところで、集中して、というのが現実的になりそうです^^;

**Comment by toki-sor1** [comment]
> SText自体が、基本どこからでも始められるゲームなので、当時、明示的にチュートと謳っていなかったので、中途半端感はあ（ry

いえ～、30周年の時、新・王杖の掴み＆インパクトはバッチリでしたし、まさに第1作目、そしてチュートリアルシナリオに相応しい内容だと、多くの皆さんが証明していますよ！ｗ

> タイミングについては、仰るように、改定目途に、とのこと賛成です！
＃そもそも「王杖」は、タイトル自体がソー層にはチュートと識別できるのですが、新チュートで「王杖」に相当するタイトル（シナ）があるかは悩ましく。その辺からじっくり選別していければと（強募ｗ）。

ご賛同ありがとうございます！
確かにソー層は「王杖」＝チュートリアルシナリオという認識がありますから、知名度という面でも「新・王杖」が第1作目だったのはまさに適役という印象ですね！

チュートリアルというと **MD版「灰色のダンジョン」、forever版「ある魔術師の失敗」** もそうかな～とは思うのですが、原点にして頂点の「王杖」が強すぎて……ｗ
しかし、まずはそうですね、じっくり選別していきましょ～。

> 現在の1.xは既に改定が困難な状態になっているので、一から作るとなると、この2年近くの作業を一からになりますからねぇ...

ﾋｯ　2年近くの作業を一から……と考えると、とてもとても気が遠くなるお話ですね……；；
今まで積み上げてきたものを一度崩すというのは、精神的にもしんどいですが……それだけの対価を払うからには、ゼロスタートになってでもやる価値がある、というものできるよう、しっかりと方針を決めていきたいですね……！
引き続きご協力させていただけましたら幸いです～。

> 2.0は、シナリオの外部投稿がゆっくりとでもされるようになってきたところで、集中して、というのが現実的になりそうです^^;

ご予定について了解です！
企画の方もどのように進行してゆくのか未知なところが多いですが、臨機応変に動いていきたいですね……！
***
> なお、本日、本番環境のゲーム画面を暫定的に修正しました。

暫定修正お疲れ様です！　iPhone 7／Safariから動作確認を行いました！

- 今までは横画面推奨だったり、縦画面だと手動でゲーム画面を調整する必要がありましたが、それが自動で行われるようになって、とても読み易くなりました！　いいと思います！

- シナリオを読む際にゲーム画面がカタカタしているのが気になっていたので、流れ星が無効化されてシナリオの可読性が向上したと思います！　スッキリ！

- ヘッダー部分がなくなり、見た目がかなりシンプルになりましたが、読むことに集中できるところが良いと思います！　こちらもスッキリ！

### 気になった点

今回は暫定的な修正とのお話でしたので、既に修正対象になっているとは思いますが、以下が気になりました（ボタンの大きさについては除外します）。

- 各メニューのダイアログの大きさ（現時点では伸縮の処理がされていない？）

**Comment by snext1220** [comment]
早速「なんちゃってモバイル対応」ご確認有難うございます！
なんちゃってながら、それなりにスッキリ！感を感じて戴いたようで良かったですｗ

お返事前後しますが、一点のみでございます～

> 各メニューのダイアログの大きさ（現時点では伸縮の処理がされていない？）

あっと、言葉足らずでスミマセン、今回はゲーム画面本文のみの対応ということでご容赦を（汗
というのも、ダイアログは固定レイアウトのため、そのまま伸縮してしまうと、ただ見た目が小さくなるだけで、たぶん操作が困難になってしまうもので；（実は一寸嘘が混じっていますが、大雑把には^^;）

こちらは、まずはダイアログの内容を整理してから、ですかねｗ
＃そろそろゲーム画面の側もどこから手を付けていくか整理していきたいと思います～

**Comment by toki-sor1** [comment]
モバイル対応の告知お疲れ様でした＆ありがとうございました～！

> あっと、言葉足らずでスミマセン、今回はゲーム画面本文のみの対応ということでご容赦を（汗
というのも、ダイアログは固定レイアウトのため、そのまま伸縮してしまうと、ただ見た目が小さくなるだけで、たぶん操作が困難になってしまうもので；（実は一寸嘘が混じっていますが、大雑把には^^;）

ご説明ありがとうございます～！
しかし、こちらこそ言葉足らずで申し訳ありません……！（大汗）
「ダイアログは画像を使っていたりと調整が難しそうだから、今回はゲーム画面の文章のみのご対応（＝後日対応予定）なのかな」と納得した上での書き込みでしたが、すみません、言葉を端折り過ぎていましたね；；

ただ、ふわふわっとした認識だったこともあり、ただ伸縮するだけでは表示には適さない理由を分かり易くご説明いただいて助かりました！　ありがとうございます！！

> こちらは、まずはダイアログの内容を整理してから、ですかねｗ
＃そろそろゲーム画面の側もどこから手を付けていくか整理していきたいと思います～

はい～、仰る通り、まずはダイアログの内容を整理してからですね……！
整理の件も了解です！　引き続きよろしくお願い致します！

**Comment by snext1220** [comment]
> 「ダイアログは画像を使っていたりと調整が難しそうだから、今回はゲーム画面の文章のみのご対応（＝後日対応予定）なのかな」と納得した上での書き込み～～

おぉ、こちらこそ失礼しました^^;
また、改めてのご確認ありがとうございました！

この後、ダイアログは増えていくと思うのですが、項目の整理と、もうひとつは、伸縮に対応しやすい背景が課題になっていきそうです（現在の枠ですと、伸縮するにしても厳密に縦横比を維持しなければならないので、その辺がネック）。
その辺、たとえばフラグ一覧など比較的優先度の低いものを試験的に実装していければと…！
また、お知恵をお借りできますと幸いです～

> 整理の件も了解です！　引き続きよろしくお願い致します！

はい～こちらは改めて #117 の方でまとめてまいりますね。

> 原点にして頂点の「王杖」が強すぎて……ｗ

そうなんですよね...
あえていえば、人気度／知名度からも「天の神々たち」もありか、と思うのですが（原作プレイでは、私はいつもここからｗ）、チュートというイメージにマッチするかというと（ry

> それだけの対価を払うからには、ゼロスタートになってでもやる価値がある

まさに仰る通りかと…！
新技術での置き換えだけであれば力づくでできてしまうのですが、それは目的ではないですものね^^; そこまで時間をかけるならば、仕様をきちんと煮詰めて価値あるものにしていきたいところです！

引き続きよろしくお願いいたします！

**Comment by snext1220** [comment]
Issue整理の一環で、こちらはBattle Sheetの実装＋ #118 で解決すると思われるため、 問題なければwontfixでcloseしていければと。もし対応漏れなどあればお知らせください。
