### ISSUE TITLE
プレイヤー、開発者への導線改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#122]
#117 からの派生で、本Issueは導線の改善案についてです。
コメントも抜粋移動しています。

---

> メニューを色分け／区分けするレベルに限定すれば、比較的小規模に収まるかも。
> あるいは、［Post］メニューのみページ右上に移動？（アイコン作成要）

このあたりを中心に構成考えてみますので、上がったらまたご意見ください！
ラフの段階ではメニューを上にして全体をまとめようと思ったのですが
縦メニューを生かしたままにするなら
https://www.willtec.jp/
こんな感じで固定されてるとよいなと思いました。
（横メニューでももちろん固定がいいです）

---

あっと、スミマセン、こちらは先の投稿時点で導線改善とは別ものと考え、固定メニューまでは考えていませんでした^^;（［Post］リンクをアイコン化して、ページ右肩などに移動する程度を想定）
＃ゲーム画面の方は別で、こちらは操作性の面から固定メニュー化 or フローティング化が必須と思われ、 #121 にて検討中です…！

というのも、現時点でのSTextサイトが（古いNextサイトからの流用であるため）古めかしいテーブルレイアウトになっていまして。固定メニューを実装する場合は、サイト構造（マークアップ）から根本的に書き直す必要があるためです；

マークアップについても勿論必要に応じて組み直していければと思うのですが、その場合も、固定メニュー化そのものを目的にするにしては作業量が大きいので^^;、微妙に悩ましいところではあります。

#### Topリンク

総じてサイト本体はそこまで縦に長いページもないため、メニューへのアクセス効率を改善、という意味では、Scenarioページ（＆必要に応じて他ページでも）でシナリオ単位に［Topに戻る］リンクを設ける程度でも十分かも。

#### フローティングメニュー

［Scenario］ページのプレイヤーレベルのように、ページ左肩にフローティングメニュー化（もしくは上／左からのスライドパネル）にすることも可能。
＃ マークアップの修正は必要になるものの、本体と別もの扱いにできるので、修正量は多少限定的に。

![無題](https://user-images.githubusercontent.com/27911337/57290499-7c3bb980-70f8-11e9-87d4-82ab8052b54f.png)

ただし、上と同じ理由（縦に長いページもない）から、効果は限定的かもしれません（固定メニュー化の目的によっては、別の解決策もあるかも？）

### まとめ？

当初、あまり拡張性を考えて作成したページでないため、つまらないところでネックになってしまい、スミマセン；；もちろん、現状維持が前提ではないので、これはやるべき！となった時には、マークアップからの見直しも考えていければと思いますので、引き続きご意見頂戴できますと幸いです。

**Comment by snext1220** [comment]
あまり自信がなかったので、固定メニュー化のテンプレを作成してみました（中身は入ってませんが）。とりあえず全ページ書き換えが前提にはなりますが^^;、対応可能です～

[index.zip](https://github.com/snext1220/stext/files/3155081/index.zip)

**Comment by yuco-mizuri** [comment]
見本まで作っていただきありがとうございます！
まさにこういう感じにしたかったのですが、そもそも

【大項目】UIの最適化
［中項目］導線の最適化

という関係だと思っていたところがあるので、私の提案が大改造になってしまってました^^;

★固定メニュー化
固定メニュー化の目的は、レスポンシブ対応するのであれば必要かな、という意識でした。
といってもスマホサイトはむしろフローティングメニュー（ハンバーガーメニュー）でもいいのかなと思います。
（フローティングの方が工数が少ないという意識がなかっただけです汗）
この場合は組むのに簡単な方で全然問題ないかと！


> * レスポンシブ対応

普段レスポンシブ対応のサイトを作るときは、PC版だけを作ってあとはコーダーさんにお願いしてるのですが、
「既にあるPC版サイトをあとからレスポンシブ対応にすることが可能なのか？」
というのが疑問でして…
可能であれば、レスポンシブ対応を前提としたデザインでPC版を一旦リニューアルし、実際のレスポンシブはあとから対応する。というのもできるのですがどうなんでしょう？


> * 非ソーサリアン層訴求のデザイン見直し
> （名前からソーサリアンの冠を外すのは時期尚早ですが、デザインとしての切り離しは別ものとして考えても？）。

まさにそのとおりです。
UIレベルでデザインを改築するなら、非ソーサリアン層への訴求も一緒に行った方がいいという前提で動いてました。
このあたりの改築は数回にわけても素材制作のときのじさんの負担が増えるだけでは…という想定です。

私がリオさんにできないことはない、くらいの意識でモノを言ってるところがあるので^^;
ハチャメチャなこと言ってたらすみません！

**Comment by toki-sor1** [comment]
専門的な知識が必要な話題なので、私の意見に「それは技術的に（もしくは工数的に）無理だよー」というものが含まれていたり、勘違いが含まれていましたら、スルーまたはご指摘いただけましたら助かります～。

### 固定メニュー化

サンプル作成ありがとうございます＆お疲れ様でした！
スクロールしてもメニューが動いてくれるので、**別ページに飛びたい時など、煩わしさがなくて便利**だと思いました。

スマホ版になると、このメニューがどうなるのかがまだ把握できていないのですが、ページのメインが圧迫されないよう、**スマホ版だと普段はメニューが収納されているといいな**と思いました。

### レスポンシブ対応

まだそれぞれの用語を検索して補完しながらのふわふわ発言で申し訳ないのですが、**PC版とスマホ版で共通した見た目のサイトだと、閲覧者側にも優しいかな**と思いました。
＃PC版とスマホ版でデザインが極端に異なっていると、見た目の面でも、操作の面でもちょっと戸惑うので。

### 非ソーサリアン層訴求のデザイン見直し

> UIレベルでデザインを改築するなら、非ソーサリアン層への訴求も一緒に行った方がいいという前提で動いてました。
このあたりの改築は数回にわけても素材制作のときのじさんの負担が増えるだけでは…という想定です。

ひーん！　お心遣いありがとうございます……！！
はい、今回は専門的な知識に基づいて素材を作成してゆく流れになるので、リテイクも多くなってしまうと思います；

そのため、yuncoさんが仰るように**UIレベルでデザインを改築するなら、非ソーサリアン層への訴求も一緒に行い**、集中的に作業を行った方が、改装の際の足並みも揃えられるかなと。

お手数をお掛けしてしまい恐縮ですが、**素材作成の際はレスポンシブ対応に適切な素材のサイズ、解像度、ファイル形式などの必要事項も一緒に教えていただけましたら助かります；**

**Comment by snext1220** [comment]
お返事前後しまして恐縮ですが、すごくざっくりとレスポンシブ対応サイトの骨格を作成しています。
ポイントは以下です。

+ レスポンシブにしてしまうならば、上メニューの方が簡単なので、そのように変更
+ 画面幅に応じて、メニューは折り畳み
+ 上メニューは固定

以下のリンクを解凍し、menu.htmlを起動してご確認ください。
[stext_renewal.zip](https://github.com/snext1220/stext/files/3194908/stext_renewal.zip)

**Comment by toki-sor1** [comment]
早速のサンプル作成お疲れ様です＆ありがとうございます！

画面幅に応じて、メニューは折り畳み、いいですね。
個人的な好みではありますが、**スマホだと主に縦持ち（？）であること**や、**右利き・左利きで使い勝手が変わらない**ということから、**stext_renewal版（上メニュー）の方がいいなぁ**と感じました。

> ファイル形式は特別な理由がない限り、pngで統一で行きましょうかね。

了解しました！　では**png形式**で！

> 素材サイズについては、今後の進め方でご相談させてくださいませ。
あるいはシステム側で決め打ちにしてしまうよりも、（大枠のレイアウトは決めた上で）細かなサイズはデザイン主導で決めて戴いた方がスムーズかも？
＃基本は大きく問題がない限り、PC版／モバイル版で同一のものを伸縮（%指定）できればと思っています（この辺も正直よく判っていないので^^;、進めていく中でご相談させてください；）

なるほど、大きく分けて2通りの決め方ができそうですね。

今まで素材制作も趣味創作の範囲で行っていたため、WEBデザインのこととなると専門知識が必要なことから、**今回の場合はどのような手順で素材の制作を進めれば良いのか等、分からないことだらけ**だったりします（大汗）。
ご面倒をお掛けしてばかりで申し訳ありませんが、ご指導ご鞭撻のほどよろしくお願い致しますm(_ _)m

**Comment by snext1220** [comment]
> 画面幅に応じて、メニューは折り畳み、いいですね。

ご確認ありがとうございます！
近年は、シングルカラムレイアウトが流行りですし、現在のゲーム画面もシングルカラムなので、統一も取りやすいかと思います。

> 今回の場合はどのような手順で素材の制作を進めれば良いのか等、分からないことだらけだったりします（大汗）。

あは、安心してください！実は私も全然わかっていませんｗ
ただ、とりあえずの感覚としては、レスポンシブ対応でも素材作成の流れが大きく変わることはない、と思っておりまして（解像度、サイズも過度に意識しなくてよいはずです）。
あえて言うならば、細かく書き込むのはあとにして、ラフ画像の段階でどんどんプロトタイプに配置＆全体確定時にまとめて仕上げ、という流れになるのかなと（＝段階的な仕上げは危険そうなので、そこだけ避ける）。

私も（Webアプリは専門ですが）Webデザインは門外漢なので、ご一緒に悩ませてください^^;

### 今後の流れ（想定）

一応、大まかな今後の流れを以下に叩き台代わりに（★～★はとりまとめ）。
根本的に見直すとなると、おそらくアプリ側は相当に時間がかかりそう＆レスポンシブ対応のノウハウも蓄積する必要がありそうなので、まずはサイトリニューアルが先になるかと。以下は、その前提です。

+ サイトの骨組み作成（方針確定次第、先のサンプルを作り込み、構造を決定します）★リオ★
+ 全体デザインの作成（骨組みをベースに、ラフスケッチ＆素材の必要箇所を判定願います）★ときのじさん★
+ ラフ素材の埋め込み（色調がわかる最低限。お手間次第でどこまでかは要相談）★ときのじさん★
+ プロトタイプサイトの完成（ここで画像サイズなど詳細も確定）
    + サイト内コーディング★リオ★
    + 素材の仕上げ★ときのじさん★
+ 動作テスト＆リリース

「全体デザインの作成」「ラフ素材」では、yuncoさんのお力を是非お借りできればと…！m(_ _)m

**Comment by snext1220** [comment]
@yuco-mizuri さん；
お返事前後した上、すっかり反応遅くなり申し訳ありません！

> まさにこういう感じにしたかったのですが、そもそも～～
> という関係だと思っていたところがあるので、私の提案が大改造になってしまってました^^;

いえいえ、仰る通り、これがあるべき姿かとは^^;
私もまさに同じ認識でしたが、大項目の影響があまりに大きいと考え（ #117 の「影響大」がそれでしたが）、一旦外しておりました。
ただ、今回、改めて根本的なところから最適化を図るということで皆さんの同意も得られましたので、その前提で進めていきたいと思います。改めて、全体レイアウト、導線面で諸々アドバイスのほどお願いいたします…！

> 私がリオさんにできないことはない、くらいの意識で～～

そういわれて、なんでもやってみせます！と言いきるスキルが欲しいｗ
ただ、プログラミングに比べると、イマイチCSS の方は自信がないというスキル状況なので、その辺が悩ましいところでして；（＝理屈は勿論判るのですが、トラブった時の原因特定が結構苦戦しそう）その辺が改定のネックになるかもしれませんが、勉強していきたいと思います^^;

あとは、SText固有の事情で、結構自転車操業なので、

+ ゲストな皆さんには「SText生きてるよ（続いてるよ）！」アピールしつつ、継続的に進化している感を出していきたい（＝少しずつでも成果物を出していきたい）
+ シナリオ企画を並行して進めているので、そちらとの兼ね合い

などで、現状の動きと両立できるかが課題、といったところです^^;
＃改築で数回に分けて、としていたのも、総工数が増えても、短期的な負荷を分散できれば、という意図がありました。

> （フローティングの方が工数が少ないという意識がなかっただけです汗）この場合は組むのに簡単な方で全然問題ないかと！

了解です！
現状のレガシーなレイアウトの場合は、フローティング（というか単なるポップアップなメニューですが）の方が影響を最小限に抑えられるとは思いますが、レスポンシブルなページにするのであれば、仰る通り、シングルレイアウトの方が断然楽ですね～先の新サンプルもその前提で組み替えてみました！

> 「既にあるPC版サイトをあとからレスポンシブ対応にすることが可能なのか？」というのが疑問でして…

モバイル版のイメージが関係者で強く共有できていれば可能だと思うのですが、今回のような互いにリモートでしか対話できない環境ですと、一寸危険かもしれませんね。。^^;

むしろモバイルを強く意識したページを作成しておいて、あとはＰＣで冗長と思われる点をどこまで最適化するか、といった順序かもしれません。

**Comment by snext1220** [comment]
こちらこそ早速のお返事ありがとうございます！

> そして早速サンプルサイトまで…ありがとうございます。仕事早すぎて全然追いついてません^^;

あ、6月が結構厳しくなる見込みで、やれる時にやっとこうという感じなので^^;
ゆるゆるお付き合いしてやってください。

> サイトツリーはリオさんとときのじさんの方が構造わかってるので～～

取り急ぎサイトツリーですが、pptなどで作成しようかなと思ったのですが、小規模でもありますし、図の作成に時間をかけるよりもまずはメンテしやすい方がよかろうと、テキスト（markdown）で作成してみました。
https://github.com/snext1220/snext-management/blob/master/sitemap.md
もし例示のサイトのように図示で、あるいは、ここをもう少し明確に、などあればお申し付けください。

※こちら誰もがメンテできるように、リポジトリへのアクセス権限を にも付与しました。前回同様の許諾メールが送信されているかと思いますので、承認いただけますと幸いです。

なお、まずは現状をまとめただけなので、もちろん、ここから諸々動かしていく可能性はあるとの認識です。

> スマホ版は%指定するんですよね？^^;

はい、今のところは、そのように^^;
仰る通り、伸縮や解像度の問題などであまりに荒れるのであれば、その時に対策していければ良いかなと…！

> 構成案はUIに関連するので現状のサイトを見ながら私がつくりますね。

恐縮です！よろしくお願いしますm(_ _)m

> ファーストビューでは「どういったサイトか一目でわかるキャッチとビジュアル」程度にとどめ、細かな説明はaboutなどに収めたいなと思ってます。

文章、仰るようにコンパクト化要ですね^^;
＃ちなみに、現状のサンプルサイトがAboutの内容なので、トップは今のところ、Scenario側（https://www.web-deli.com/sorcerian/text/）になる予定です。

Scenarioページの側は、シナリオ作者さんの紹介文をそのまま掲載しているので、文章量を微妙に制御しにくいのも悩みの種です（一応の文字数は指定しているのですが、人によって結構マチマチという^^;）。

**Comment by toki-sor1** [comment]
各種対応＆お返事ありがとうございます！
（以下、 @snext1220 さんと @yuco-mizuri さんへのお返事を一緒にまとめています）

> まず、構成案とサイトツリーをつくります。
下記サイトが参考になるかと思います。
http://d.hatena.ne.jp/ef7038/touch/searchdiary?word=%2A%5B%A5%EF%A1%BC%A5%AF%A5%D5%A5%ED%A1%BC%5D

とても分かり易い詳細なご解説ありがとうございました！
今までサイトデザインというと素材などの見た目のことばかりに目がいってしまってたのですが、まず初めに構成案とサイトツリーを作成すると良いのですね！
構成案とサイトツリーについても勉強になりました！
***
>サイトツリーはリオさんとときのじさんの方が構造わかってるので、作っていただいて、私が手を加える方がよいのでしょうか？
私が作るでも大丈夫なのでご指示くださいませ。

> pptなどで作成しようかなと思ったのですが、小規模でもありますし、図の作成に時間をかけるよりもまずはメンテしやすい方がよかろうと、テキスト（markdown）で作成してみました。
https://github.com/snext1220/snext-management/blob/master/sitemap.md

早速のご提案＆サイトツリーの作成ありがとうございます！
サイトツリーを拝見しましたが、

- **SText紹介とユーティリティが類似した内容もあり、ページが違ってもぱっと見て区別しづらい**という印象を受けました。

現段階では上記のことが気になりました。
***
> 構成案はUIに関連するので現状のサイトを見ながら私がつくりますね。
過不足あれば都度ご指摘いただく感じで！

うおおおおありがとうございます……！！
お手数をお掛けしてしまい恐縮ですが、よろしくお願い致します……！m(_ _)m
***
> あと、作っていただいたテストスマホ版を見て思ったのですが、文章がかなり多いですね。

> PC版だとスカスカになる可能性があるので、あるいはスマホ版では冒頭一段落を表示、PC版でのみ以降の段落を表示という方法もあり？（いずれにせよ文章は要検討ですが）

現状、**PCブラウザからサンプルを見ても文章が多め**なので、**スマホから見ると文章が折り返されている影響もあり**更に気になりますね；

文章量の調整などは必須かなとは思うのですが、一例として、レスポンシブ対応のYs9公式サイトのこちら（https://www.falcom.co.jp/ys9/world/ ）のように**文章量が多い箇所は、■をクリックするとページの一部分だけ切り替わる**というのも有効なのかなと思いました。
＃STextサイトでは、シリーズ紹介のカルーセル（？）部分のようなイメージでしょうか。

> Scenarioページの側は、シナリオ作者さんの紹介文をそのまま掲載しているので、文章量を微妙に制御しにくいのも悩みの種です（一応の文字数は指定しているのですが、人によって結構マチマチという^^;）。

うーん、**シナリオ紹介文と分類等のシナリオデータが一緒**というところも文章量が増えている感じがしますね。
こちら、**シナリオ紹介文とシナリオデータを切り離し、シナリオ紹介内にシナリオデータへのリンク（ボタン？）を置く**というのは如何でしょう？

**Comment by snext1220** [comment]
> サイトツリーを拝見しましたが、～～～～

まさに、ですね^^;
こちら、現在のsitemap.mdを更新頂いても構いませんし、大きく変化あるようでしたら、別ファイルとしてUp戴くでも構いませんので、是非どんどんいじってやってくださいませ（履歴は残るので、基本は元ファイル更新で大丈夫かと思います）～

> ＃STextサイトでは、シリーズ紹介のカルーセル（？）部分のようなイメージでしょうか。
> こちら、シナリオ紹介文とシナリオデータを切り離し、シナリオ紹介内にシナリオデータへのリンク（ボタン？）を置くというのは如何でしょう？

情報量を維持しながらですと、そうした展開式?になりそうですね！

この辺、見せ方の問題なので、見せるべき情報の整理を経てからにはなると思いますが、個人的には、モバイル版では、「現在のプロローグ文章はカット、シナリオデータだけを残す」のもありかと思いました。
＃現在の文章の半数以上はプロローグからの切り取りなので、紹介文としては著者の一言コメントのみでも十分？（gamebook.xyzなど見ると、トップページの情報は相当に絞っているようでした）

**Comment by yuco-mizuri** [comment]
長らく放置してすみません…
それと小説内のスマホ対応お疲れ様でした！
変えられる部分から変えていくのはいいと思います！

シングルカラム、メニュー固定などもろもろ了解しました。
上記を踏まえて「プレイヤー、開発者への導線」を改めて考えますね。

サイトツリーは樹形図のようになっている方が、階層がわかりやすいのですが
>SText紹介とユーティリティが類似した内容もあり、ページが違ってもぱっと見て区別しづらいという印象を受けました。

まさに、という感じです。
TOPページのシナリオ紹介の仕方ももっと改善できるとは考えていたのでそのあたりもここの課題を解決するべくサイトツリーのリニューアル、構成案の作成を進めていきますね。

そして…私も仕事が立て込んでまいりまして…（お盆のスケジュールまで押さえられてしまい…(T_T)）
書き込みがあった場合は全て読んでいますので、何もコメントがなければ問題なしとして構成案に盛り込んで制作を進めていると思っていただければ…
しばらく無言になるかもしれませんが、疑問点などあればまたご意見伺います！

**Comment by snext1220** [comment]
お忙しいところお返事ありがとうございます！
もちろん、基本的にやれる時に進めていこうが基本姿勢なので^^;、気長にお付き合いください～

> 書き込みがあった場合は全て読んでいますので、～～

ありがとうございます！では、そのつもりで。
現状は［Renewal］タグで、根本的な議論を
https://github.com/snext1220/stext/labels/Renewal
［Temporary］タグで、Renewalに先行した対応（暫定修正含む）を行っています。
https://github.com/snext1220/stext/labels/Temporary

Temporaryについては簡易なRenewalですが、それでも後々に無駄にならないようにしていければとは思っていますので、お気づきの点があればご指摘お願いいたしますm(_ _)m

> 解決するべくサイトツリーのリニューアル、構成案の作成を進めていきますね。

ありがとうございます！
こちらもどうぞよろしくお願いいたします。
不明な点は何なりとお聞きくださいませ。

**Comment by snext1220** [comment]
Issue整理中です。
他との重複があるもの、ある程度役割を終えたものをCloseしております。
当方判断で行っておりますが、もしCloseに問題あればReopenにしますので、なんなりとお申し付けください。

こちらは #117 Issueに議論の中心が移っているため、Closeします。
