### ISSUE TITLE
${tweet}指定時にツイートボタンが表示されない

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#124]
https://twitter.com/ishikawanonoich/status/1129101710381633536

上のご指摘を受けてのIssueです。
サイトリニューアル時の設定漏れで、個別ツイートが反映されない状態になっていました。
本番ゲーム画面を修正済です。

**Comment by RYU-DS** [comment]
確認しました。修正ありがとうございます。
https://twitter.com/ishikawanonoich/status/1129256602903535616

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 74.0.3729.157(64bit)にて動作確認。
「ソーサリアン性格診断占い」の各ページでTweetボタンを押して確認し、**各結果のツイートが正常に表示されているのを確認しました。**

**Comment by cocotori** [comment]
確認しました。
問題なくツイートできました。

**Comment by cocotori** [comment]
ただ、ツイートのサイトへのアドレスが古いサイトになってるみたいですね。
リダイレクトのおかげで、問題なく繋がりますが。

**Comment by snext1220** [comment]
ご指摘ありがとうございます！
先程修正しまして、GitHub／本番サイト共に反映させていただきました～
お手すきの折にもご確認戴けますと幸いですm(_ _)m
