### ISSUE TITLE
バックアップ機能のSafari対応

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#125]
以下コメントで戴いた件です。
https://github.com/snext1220/stext/issues/118#issuecomment-492695579

これまでSafariの制限でダウンロード機能が利用できませんでしたが、サーバー側にシカケをしまして、本番環境にて対応しております。当方、iPadのみで確認していますが、可能な方はiPhoneなどでもご確認を戴けますと幸いです。

＃ただし、サーバー環境の都合上、GitHubからは動作**しません**ので、ご注意ください（Safariのみ）。

**Comment by toki-sor1** [comment]
iPhone 7 Safariから動作確認。
iCloud Driveにバックアップファイルを保存し、「ブラウザ」を選んでRestoreすることで**正常に再開することができました！**

わあああ早速のご対応ありがとうございます！！
BackupとRestoreの手順を簡単に解説する必要はあるかと思いますが、これでモバイル環境（iPhoneなどのiOS系）で更に遊び易くなりましたね！

**Comment by snext1220** [comment]
早速のご確認ありがとうございました！
ここまでは基本Chromeベースで開発を進めてきたのですが、モバイル対応となると、Chrome／Safariを中心に確認を進めていかないと、ですね。

＃今回のバックアップ機能は、Safariが唯一の鬼っ子で、結局、サーバー側にシカケを施してようやく対応となりました；ブラウザ互換はホント悩ましいです；；

マニュアルについては、諸々の機能が落ち着いたところで再整備していければと～
ただ、バックアップについては、、、どうしてきましょうかね^^;

現状、以下ページの「セーブデータのバックアップ／リストア」でまとめておりますが、iPhone周りの保存方法までまとめるとなると、環境依存にもなりそうなので、中々悩ましそうで；
https://sorcerian.hateblo.jp/entry/20171220
もし「この辺がわかりにくかった」などあれば、ぜひご指摘くださいませm(_ _)m

**Comment by toki-sor1** [comment]
> ここまでは基本Chromeベースで開発を進めてきたのですが、モバイル対応となると、Chrome／Safariを中心に確認を進めていかないと、ですね。

ううっ、モバイルに対応してゆくためには避けて通れませんもんね……。
時代の波についてゆかねば……！

> ＃今回のバックアップ機能は、Safariが唯一の鬼っ子で、結局、サーバー側にシカケを施してようやく対応となりました；ブラウザ互換はホント悩ましいです；；

ご対応、本当にお疲れ様です……；；
サイト表示だけでなく、ブラウザの中身のことも考えて機能を実装しなければいけないのは辛いですね……；；

> マニュアルについては、諸々の機能が落ち着いたところで再整備していければと～
ただ、バックアップについては、、、どうしてきましょうかね^^;

現状、シンプルで読み易くまとまっていますから、iPhone周りの保存方法もまとめるのはどうしようか、確かにちょっと悩ましいですね；

ただ、せっかくの機能も使い方が分からなくては有効活用できないのでは、とも思うんですよね；
**マニュアルのページはシンプルさを保ちつつ（そのままに）、リンクで詳細説明のページに飛べる仕様**というのもいいかもしれません。

**Comment by Salvadors-cabin** [comment]
旧型iPad(iOS9+Safari)では、セーブはO/Dにできたものの、リストアはできないようでした。

![AugTest1-20190731](https://user-images.githubusercontent.com/42834363/62182292-0bbbd600-b391-11e9-9516-24260592aedb.png)

たぶん旧ブラウザに対応していないのだと思います。
そろそろiOS9+Safariのテストは意味がないかも、と思っています。

**Comment by snext1220** [comment]
ご確認ありがとうございます。
OneDriveへのアクセスの問題?のように見えますが、例えばローカルにセーブデータを保存して、そちらからリストア、などはできませんでしょうか。

> そろそろiOS9+Safariのテストは意味がないかも、と思っています。

確かに、iOSがかなり古くなっていますよね...
悩ましいところなのですが、（主に私の環境の問題で）Safariでの検証がかなり手薄だもので、できればもう少し継続戴けるとm(_ _)m
※IEを除くと、Safariが鬼っ子であることが意外と多いので。

**Comment by toki-sor1** [comment]
iPhone 7（iOS 12.4）／Safariにて動作確認。
バックアップ・リストアともに正常に行うことができました。
こちらはOneDriveではなく、**iCloud Driveにバックアップファイルを保存してリストアしています**が、アクセスも問題ないですね。

試しにDropboxにバックアップしてみましたが、今度はリストア時にDropboxが選択できず（選択候補として表示されない）、こちらは無理そうでした。

**Comment by snext1220** [comment]
ご確認有難うございます！

選択候補に表示されない＞ については制約の条件が不明ではあるのですが、とりあえずアプリ（JavaScript）原因ではなさそう＆代替はききそうなので、今回はママとさせていただきますね。

**Comment by Salvadors-cabin** [comment]
私の環境ではバックアップ時にOneDriveだけしか候補に出てこないですね。バックアップはできるのですが、リストア時にエラーになってしまう（前の書き込みの状況）という・・。
設定の問題なのかブラウザが対応していないのか不明ですが、今のところやれることが無さそうです。

**Comment by cocotori** [comment]
iPad6 (iOS 12.3) にて問題なく動作することを確認しました。
iPod Touch (iOS9.3)ではバックアップできないようです。
（ファイルエクスプローラー等が選択肢に出ない。）

何かしらアプリを入れればできるのかもしれませんが、
古めのOSですので、ひとまずできるところまでで
いいのではないかと思います。

**Comment by snext1220** [comment]
ご確認ありがとうございました！

> 設定の問題なのかブラウザが対応していないのか不明

ファイル選択ボックスなので、ブラウザーそのものというよりも、OSの対応、もしくは設定の問題のようには思われますが、 @cocotori さんも仰っているように、古いOSなので「できるところまで」程度で十分そうですね（今後もそのレベルでのご確認で良いかと考えております）。こちらは他にご意見なければ、クローズにしていければと。
