### ISSUE TITLE
ボーナスダイアログの改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#126]
https://github.com/snext1220/stext/issues/117#issuecomment-497334334 を受けてのIssueです。

ボーナスダイアログを以下のように改善しました（GitHubのみ反映）。

+ 非ダイアログ化（ゲーム画面との切り替えに）
+ レスポンシブ対応（画面幅に応じて列数も変化するように）
+ ボーナスアイテム情報はトースト表示
+ 伴い、その他のダイアログにも対応できるように、サブ画面表示ロジックの共通化

現時点では背景は取り払ったり、［戻る］はテキストの矢印のみと手抜きですが、まずはダイアログ改定のお試しということでお許しください。

**Comment by toki-sor1** [comment]
Win 8.1 Chrome 74.0.3729.169(64bit)／iPhone 7 Safariにて動作確認。
**パソコン環境、モバイル環境ともに正常に動作していました。**

- モバイル環境でも手動で幅を調節する等のストレスなく表示されるのが良いですね！
- ボーナスアイテム情報のトースト表示も見易くて良かったです！

後日、背景等の各種素材のお話になると思いますが、詳細が決まり次第対応の予定です。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

詳細が決まり次第＞はい、とりあえず https://github.com/snext1220/stext/issues/117#issuecomment-497334334 の方針でご賛同戴き次第、順次詳細を詰めていければと思っております。諸々ご相談ばかりで恐縮ですが、まずはご意見のほどよろしくお願いしますm(_ _)m

**Comment by snext1220** [comment]
https://github.com/snext1220/stext/issues/117#issuecomment-502332000 のお返事です（個別スレに移動いたしました）。

ダイアログの背景＆ボタン、早速ありがとうございます！
こちらGitHub環境に反映させていただきました～

+ 背景はメイン画面のものとも対照関係にあり、良いかと思いました！
+ Backボタンは私の環境だと若干薄いので、もう少しはっきりしていると良いかもしれませんです
    + どうも私の環境がコントラスト弱いようで（画面設定でも治らず；）、その問題もあるかも？
+ 暫定でもあるので、枠線はCSSでザックリ付けましたが、如何でしょうか。

### ご相談

こちらがある程度Fixしましたら、他の細かなダイアログも順に作成していければと…！

+ 改めてダイアログ間のリンク関係は整理致したく、その際に必要となるボタンについてもご相談させて戴ければ幸いですm(_ _)m
+ ダイアログ背景、Backボタンは基本、今回作成戴いたもので統一していければと思っておりますが、如何でしょうか。

**Comment by toki-sor1** [comment]
お返事＆反映、そしてご意見ありがとうございました！

> 背景はメイン画面のものとも対照関係にあり、良いかと思いました！

本番ではデザインをもっと洗練させたいなと思っているのですが、色合い等ひとまず方向性は良いようで安心しましたｗ

> Backボタンは私の環境だと若干薄いので、もう少しはっきりしていると良いかもしれませんです
どうも私の環境がコントラスト弱いようで（画面設定でも治らず；）、その問題もあるかも？

Backボタンはどこまで目立たせようか迷って、他のものより若干控えめにしていたので、色は特に薄かったかもしれません；（モニタによる色の違いも本当に悩ましいですよね～；）
という訳で、他のボタンと一緒にBackももうちょっと目立つように調整してみました～（O/D内の素材も差替え済みです）。
![濃度調節版](https://user-images.githubusercontent.com/42646342/59784706-11d48680-92fe-11e9-806e-7506d2ff5d33.png)
https://onedrive.live.com/?id=4837C202555BE782%216763&cid=4837C202555BE782

> 暫定でもあるので、枠線はCSSでザックリ付けましたが、如何でしょうか。

はい！　ボタン同士の境が明確になり、文字だけの時よりもタッチ（クリック）を意識し易くなっているのが良いと思います～。

> 改めてダイアログ間のリンク関係は整理致したく、その際に必要となるボタンについてもご相談させて戴ければ幸いですm(_ _)m

承知しました！

> ダイアログ背景、Backボタンは基本、今回作成戴いたもので統一していければと思っておりますが、如何でしょうか。

はい～、良いと思います！

**Comment by snext1220** [comment]
早速のご対応ありがとうございました！

> 背景壁紙も前回のwp.png（左：濃度20%） に加えて、新たにwp2.png（右：濃度30%） も追加しました。

ありがとうございます～
こちらは以前のものでも致命的ではなかったのですが、若干薄めに感じたので、wp2.pngをwp.pngにリネームして差し替えさせて戴きました！

> Backボタンはどこまで目立たせようか迷って、他のものより若干控えめにしていたので、色は特に薄かったかもしれません；（モニタによる色の違いも本当に悩ましいですよね～；）

モニタは、、、逆に環境によって目立ちすぎたりするので悩ましいですよね；
こちらも新規のもので差し替えさせて戴きました！ありがとうございます～
＃個人的には、Backが一番使うので、他ボタンと同様 or より強調くらいでも？とは思いましたが、自信なしです^^;皆様のご意見も伺いながらおいおい（必要に応じて）調整させてくださいませ～

> はい！　ボタン同士の境が明確になり、文字だけの時よりもタッチ（クリック）を意識し易くなっているのが良いと思います～。

ありがとうございます！まずは暫定ですが、今後様子を見ながら＆ボタンが揃ってきたところで、調整ご相談させて戴けますと…！

こちらダイアログ系の素材については、
https://github.com/snext1220/stext/tree/master/stext/common/renewal
でまとめておりますので、もし差し替えられる場合は、こちらに適宜Up戴けますと幸いですm(_ _)m

> ダイアログ背景、Backボタンは基本、今回作成戴いたもので統一していければと思っておりますが、如何でしょうか。

ご了解有難うございます！
では、ゆるゆるにはなりますが、他ダイアログも展開進めてまいりますね！

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 76.0.3809.87(64bit)、iPhone 7／Safariにて表示確認。
正常に表示されているのを確認しました。

> wp2.pngをwp.pngにリネームして差し替えさせて戴きました！

大分お返事が遅くなってしまい申し訳ありません……！
その節はご対応ありがとうございました！

> ＃個人的には、Backが一番使うので、他ボタンと同様 or より強調くらいでも？とは思いましたが、自信なしです^^;皆様のご意見も伺いながらおいおい（必要に応じて）調整させてくださいませ～

ご意見ありがとうございます！
前回は各ボタンのサイズに合わせてBackボタンも作成し、色味も調整しましたが、現在のBackボタンもやや小さく目立っていない感じがしますね；
必要に応じて調整、了解でございます～。

> まずは暫定ですが、今後様子を見ながら＆ボタンが揃ってきたところで、調整ご相談させて戴けますと…！

こちらについても了解です！

> こちらダイアログ系の素材については、
https://github.com/snext1220/stext/tree/master/stext/common/renewal
でまとめておりますので、もし差し替えられる場合は、こちらに適宜Up戴けますと幸いですm(_ _)m

ご案内ありがとうございました！
差し替えの際はこちらを利用させていただきますね。

こちらも色々と滞っていて申し訳ありませんが、引き続きよろしくお願い致します……！

**Comment by cocotori** [comment]
Backボタンがとてもかっこよく、雰囲気出ていると思います。

現状ですと、SECRET状態のボーナスアイテムも、
押すと詳細が見れてしまいます。
こちらは意図通りでしょうか？

**Comment by snext1220** [comment]
とと、失礼しました；
初歩的なミスで空欄ボーナスが除外できていませんでした。
先程修正しまして、GitHubには反映済みです。
お手数ですが、ご確認くださいませm(_ _)m

**Comment by cocotori** [comment]
OKです！修正されていることを確認しました。
