### ISSUE TITLE
コントロールパネルの固定メニュー化（暫定版）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#127]
https://github.com/snext1220/stext/issues/117#issuecomment-497334334 を受けてのIssueです。

コントロールパネルを以下のように改善しました（GitHubのみ反映）。

+ ページ上部への固定メニュー化
+ レスポンシブ対応（画面幅に応じて見た目も変化するように）
+ Status／Bonusのみ動作（他はなにも動きませんし、Statusも中身は空の状態です）

### 懸案その他

+ あくまで暫定なので、旧来のコンパネはそのまま動作していますし、今後、内部的にはSText本体との統合を図っていく必要があります（＝いずれにせよ、すぐさまにはリリースはできない）。
+ Soundは第一段が微妙な感じだったので、一旦、System内に置いています。
+ 今回の機能はそのままサイトでの固定メニューにも援用していこうと思っています。
+ こちらが了承されたら、他のダイアログ改善も徐々に展開していければと。
+ モバイル環境だとハンバーガーメニューを開いてからなので、目的のメニューまで行きつくのが若干長い気はしますね。。構造要検討です。
    + やはりステータスダイアログの中で切り替え表示とする必要があるかも

### TODO

+ ダイアログの非表示（シーン移動時の処理）
+ ダイアログ非表示の共通ロジック化
+ シナリオ初期化前のヘッダー画像（画面幅いっぱい）

**Comment by snext1220** [comment]
https://github.com/snext1220/stext/issues/117#issuecomment-502332000 のお返事です（個別スレに移動いたしました）。

メインアイコンですが、早速ありがとうございます！
こちらGitHub環境に反映させていただきました～
＃シンプルで、現在のデザインにもマッチしていると思います！！あくまで暫定とはいえ、テキスト中心で控えめな存在感という意味でGoodだと思いました。

**Comment by toki-sor1** [comment]
お返事＆反映ありがとうございます！
（個別スレ移動した方がいいのか悩んでいたので、移動ありがたいです！）

現在挙がっているデザインの方向性から、シンプル且つ控えめが良いかなと思って作成していたので、マッチしているとのお言葉にとてもホッとしました！
仮デザインではありますので、今後の話し合いからデザインをもっと洗練させていけたらいいなぁと思っています。

**Comment by snext1220** [comment]
> 個別スレ移動した方がいいのか悩んでいたので、移動ありがたいです！

あは、ご遠慮なく、スレ移動はどんどんしてやってくださいｗ
基本は方針面だけを #117 で、個々の話題は別Issueで、という感じでやってますが、私も使い分けはいい加減になっていますので^^;

> 現在挙がっているデザインの方向性から、シンプル且つ控えめが良いかなと思って作成していたので、マッチしているとのお言葉にとてもホッとしました！

どちらかというと、私のスキル＆工数的な事情でしたが、合わせて戴いて助かりましたm(_ _)m
実際作成してみると、シンプルもこれはこれで、という気がしてきますが、全然決定ではありませんので、本格改定では根本的なテイストから是非弄って戴ければと…！

> 仮デザインではありますので、今後の話し合いからデザインをもっと洗練させていけたらいいなぁと思っています。

はい、暫定版は本格版のプロトタイプの場とも割り切っていますので、思いつきをどんどん反映させていければと。もし @toki-sor1 さんの方で頻繁に更新などされるようであれば、フォルダー／ファイル名などのルールなど決めて、どんどん差し替えできるようにしていければと思っています～

今後の話し合い、については、切り分け若干むずかしいかもですが、場合によっては「素材テイスト」で、Issueを別に立ち上げた方が良いかもしれませんね。もし宜しければ、お願いします～

**Comment by snext1220** [comment]
他との重複もありますが、時間も経過したので、最新?のコンパネ構成案をまとめています。
ステータスダイアログの分離による更新、Player Rankの移動が、主な変化です。

+ Status（モバイルファーストで考えると、ここは維持）
+ Magic（魔法と星） 
+ Info
    + Basic（キャラ基本情報。メモもここへ）
    + Items＆Flags（ステータスから分離表示）
    + Result
    + Bonus（有効化ボーナスはここで表示）
    + Player Rank（現在の［Scenario］ページのものを移動？）
+ System
    + Backup
    + Restore
    + Sound（On/Off）
    + Help
    + Exit（旧Pentwa）

#### 懸案

ご意見頂戴できますと幸いです。

+ Player Rankはここに置くべきか、サイト（Utility）などに移動するか
+ ステータスダイアログの分離度合いはこれでよいか

**Comment by toki-sor1** [comment]
> Player Rankはここに置くべきか、サイト（Utility）などに移動するか

まとめて確認出来た方が便利なので、「Info」が良さそうです。

> ステータスダイアログの分離度合いはこれでよいか

良いと思います！

> Status系のダイアログは、Battle Sheet同様、サイドバーとして再編の予定です。良い？

サイト、SText共にサイドバーを活用しているので、サイドバーとして再編が良いと思います！

> Magicは利用頻度も低くなっていますが、メインな操作メニューなので一段にしています。良い？

確かに、魔法の手動発動（手動での欠片増減）の機会は少なくなったと思います。
しかし、私のシナリオや「slayer」など、特定のシナリオでは、手動による操作を必要とする機会が多いので、一段目だとありがたいです。

**Comment by snext1220** [comment]
ステータスダイアログの改善に伴い、コンパネ（ヘッダーメニュー）もSText本体に組み込み、かつ、すべてのメニューが動作するように修正いたしました。

ステータスダイアログの機能がFixした後になるかと思いますが、こちらの動作確認もよろしくお願いいたします。

＃本改定に伴い、おそらくPg Editorが一部動作しなくなる可能性があります（Pg Editorは本番サイトでしか動作しないので未確認）。今後、修正していく予定ですが、これらの改定がFixした後になるかと思います。ご了承くださいませ。

**Comment by toki-sor1** [comment]
なかなかお返事できず、ご迷惑をお掛けしました；；
申し訳ありません；；

#### Win 8.1／Chrome 78.0.3904.87(64bit)で動作確認

- 手動でHPやMPを最大値以上増やした状態でHPまたはMPがシーン移動で減ると、最大値に戻ってしまいました。

#### iPhone7／Safariで動作確認

- 手動でHPやMPを最大値以上増やした状態でHPまたはMPがシーン移動で減ると、最大値に戻ってしまいました。
- Backupが正常に機能せず、バックアップファイルを保存できませんでした。
***

> 場合によっては画面幅のバナー（背景？）を置いてはと思ったのですが、如何なものでしょうか

確かにぽっかりと隙間がありますね（GitHub版にて確認）。
ただ、コンパネが表示された後は隠れてしまうものと考えると、現在使用中の壁紙でもフォローできる範囲として割り切っても良いような気もします。

> タブの切り替えがイヤという方がいるとなんですが、如何なものでしょうか。

同じタブでの表示よりも、現在の別タブ表示の方が便利だと感じています。

**Comment by snext1220** [comment]
こちらも断片ですが...

> 手動でHPやMPを最大値以上増やした状態でHPまたはMPがシーン移動で減ると、最大値に戻ってしまいました。

こちらは現時点では仕様になってしまいます...
hp／mp属性による変更は上限を超えた場合は、上限で止めるという仕様になっていたもので...
その仕様を廃止しても良いか、ですね...
＃ 上限越えを想定していないシナリオで、上限を超えたhp/mpができてしまいますが；

**Comment by cocotori** [comment]
文章を下に読み進めてもアクセスしやすい＆
邪魔にもならない
という点でとてもスッキリしたメニューになったかと思います。

各項目表記ですが、英単語はおしゃれではあるんですけど、
アイコンに比べ、ややどこに何があるか判断するまでに時間がかかりました。
ただ、今までの慣れのせいもあると思うので、もう少し使って様子を見ます。

PCから操作した場合、Info等のプルダウンタイプのものは
マウスオーバーだけでプルダウンメニューが出てきますね。
少ボタン操作で手軽ではあるのですけど、
わたしがすぐボタンを押してしまうタイプのせいで、
Infoにマウスオーバー → プルダウンメニューが出る直前にマウス左クリック
→ プルダウンメニューが一瞬で消えてしまう

という誤操作を多発してしまいました。
慣れの問題なので構わないのですが。

もしもですが、マウスオーバー後、
一瞬だけ（0.5秒くらい？）左クリックを禁止する、
なんてことができたらそういうこともなくなるのかなと思いました。

とは言えそんなに必要としてはいないので、
話半分に聞いて貰えれば。

**Comment by toki-sor1** [comment]
いえいえ、ご返信いただきありがとうございます！

> こちらは現時点では仕様になってしまいます...
hp／mp属性による変更は上限を超えた場合は、上限で止めるという仕様になっていたもので...
その仕様を廃止しても良いか、ですね...
＃ 上限越えを想定していないシナリオで、上限を超えたhp/mpができてしまいますが；

ああ～、なるほど…！
確かにHPとMPは、回復した際に上限を超えないようになっていましたね…！
認識不足申し訳ありません；；

幕末ソーで成長システムが採用されること（HPとMPは含まれてはいませんでしたが）＋「そのドラ」で上限値超え前提のシナリオであることから、大丈夫かなと「双王」のキングドラゴン戦でHPとMPと各ステータスを上限越えさせるルールを採用してしまっていました；

修正する場合、シーン移動の際の被ダメージは演出としての役割もあるので、HPとMP上限値超えを廃止＋ダメージ式の数値再設定が最良でしょうか。

**Comment by snext1220** [comment]
ご確認ありがとうございました！

@toki-sor1  さん

>　ただ、コンパネが表示された後は隠れてしまうものと考えると、現在使用中の壁紙でもフォローできる範囲として割り切っても良いような気もします。

了解です！
では、まずは様子見といたしましょうか。
本番環境に移行すると、また気になるなどのご意見もあるかもしれませんが、その際はまたお声がけください and/or ご相談させてください～

>>　タブの切り替えがイヤという方がいるとなんですが、如何なものでしょうか。
>　同じタブでの表示よりも、現在の別タブ表示の方が便利だと感じています。

これは意外でしたｗ
同一画面で見られないのはデメリットとばかり思っていたもので、完全にシステム都合の修正だと覚悟していたのですが。思わぬご意見でよかったです～
＃ ちなみに、同一画面だと込み入って見にくいという感じでしょうか。

> 修正する場合、シーン移動の際の被ダメージは演出としての役割もあるので、HPとMP上限値超えを廃止＋ダメージ式の数値再設定が最良でしょうか。

仰る通り、既存シナの用途に合わなくなってきたので、ご意見に賛成です～
ただ、こちらCompati案件なので、一応、タグを付けて皆様のご意見を待ちますね。

なお、ダメージ式の再設定、についてはシナリオ側のご対応、ということで大丈夫でしょうか？（システムでなにかすべきことがあればお知らせください～）

@cocotori  さん

> 文章を下に読み進めてもアクセスしやすい＆～～

ご評価ありがたいかぎりです！
当初はシーン単位でスクロールしない範囲の文字量、を想定していたのですが、中々そうもいかない＆モバイル対応も本格化してきたところで、結果、良いタイミングになったのかなと！

> ただ、今までの慣れのせいもあると思うので、もう少し使って様子を見ます。

は、この点、サイト開発していると、ありがちな問題なので、私も悩んでいました^^;（スリムに見える英語と、判読性の日本語と）
とりあえずはステータス画面も英語中心であることから、現時点では英語としていますが、初見で判りにくいのも良くないので、慣れ具合見ながら引き続きご意見いただけますと幸いです（ほかの皆様もぜひお願いします）。
＃ 日本語にする場合は画像にするなどして、少しスタイル整える必要はありそう？

> わたしがすぐボタンを押してしまうタイプのせいで、～～

こちらについては、一時的にクリック禁止、はライブラリに手を入れなければならないので悩ましいので、いったん、クリックでメニュー展開に改めてみました。マウスオーバーよりわずかに手間はありますが、誤操作はなくなるかと。
皆様のご意見いただきつつ、Fixしてまいります。

**Comment by toki-sor1** [comment]
ご多忙の中、お返事ありがとうございます！

> 本番環境に移行すると、また気になるなどのご意見もあるかもしれませんが、その際はまたお声がけください and/or ご相談させてください～

それでは、こちらは様子見で！
本番移行後についても承知しました～。

> ＃ ちなみに、同一画面だと込み入って見にくいという感じでしょうか。

す、すみません、別タブが便利と思っているのは変わらずなのですが、ちょっと勘違いしていたところがありました；
以前のEditorをイメージしての発言ではなく、何故かEditor画面がそのままゲーム画面になるようなイメージを思い浮かべてました；（本当に何故なのか；；）

確かに、見易さの面では同タブ内の方が上かなと思います。
ただ、別々のタブの方がシナリオ編集時のふとした操作ミスも防げると思いますし、ゲーム画面を消したい時はタブを消せば良く、動作も安定するかなと思っているので、別タブ良いと思います～。

> 仰る通り、既存シナの用途に合わなくなってきたので、ご意見に賛成です～
ただ、こちらCompati案件なので、一応、タグを付けて皆様のご意見を待ちますね。

承知しました～！

> なお、ダメージ式の再設定、についてはシナリオ側のご対応、ということで大丈夫でしょうか？（システムでなにかすべきことがあればお知らせください～）

お気遣いいただきありがとうございます！
こちら、シナリオ側で対応しますので、システムの方ではご対応なしで大丈夫です～。
システムを変えるか否かは皆さんのご意見待ちとなりますが、現在ではシナリオの戦闘ルールがシステムにマッチしていないので、シナリオ側を近々修正して再アップしますね。

> Backup

あわわ勘違い申し訳ありません…！
本番環境のみの機能ですね、承知しました！

**Comment by snext1220** [comment]
> 何故かEditor画面がそのままゲーム画面になるようなイメージを思い浮かべてました；
そんなイメージの方がイマドキですよね^^;
今回は、本番環境、Pg環境の統一を図って、こんな感じになりましたが、将来的には、Flow／Editorの統合も図りたいと思っているので（いつになるか；）、その際には実行画面も検討できればと…！
まずは、別タブで問題ないとの事もありがとうございます～

> こちら、シナリオ側で対応しますので、システムの方ではご対応なしで大丈夫です～

了解です＆よろしくお願いします！
参考までに、シナリオ修正の際、修正箇所教えて戴ければ幸いです～
＃ 現在は対応なしの予定ですが、一応の将来用に現状把握しておければと…！

> 本番環境のみの機能ですね、承知しました！

恐縮です；あとはアップロードが本番Onlyですね～

### 報告

あとhp/mp属性については、Issueのテーマからは若干外れかけていたのと長くなってきたので、 #149 に移動済みです。ご意見引き続きよろしくお願いします～
