### ISSUE TITLE
STextサイトの固定メニュー化（暫定版）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#128]
https://github.com/snext1220/stext/issues/117#issuecomment-497334334 を受けてのIssueです。

本番サイトのメニューを以下のように改善しました。

+ ページ上部への固定メニュー化
+ レスポンシブ対応（画面幅に応じてハンバーガーメニューに）
+ シナリオページではシナリオ情報をモバイル非表示に
+ ギャラリーページも画面幅に応じて並びを調整

### 残課題

+ ロゴ画像（キャッチフレーズをどこに残すか）
+ 背景（現在は黒一色だが、流石に殺風景？）

**Comment by cocotori** [comment]
新サイト対応お疲れ様です！

（PCから）
Edgeは大丈夫だったのですが、Chromeだと
Galleryの画像がおかしなサイズになっていました。
強制的に原寸になっているような・・・？

ご報告までに。

**Comment by snext1220** [comment]
ご確認有難うございます！いろいろ弄っていますもので、思わぬページ、環境で問題が出ている可能性もあり、ご確認とても助かります～

Chrome＞こちらですが、旧スタイルがキャッシュに残っている現象のように見えます。お手数ですが、ブラウザーキャッシュを破棄した上で再度ご確認戴いても宜しいでしょうか？m(_ _)m

**Comment by cocotori** [comment]
キャッシュを消して、正常に表示されることを確認しました！
お騒がせしました。

キャッシュ、結構厄介ですね・・・
サイト構成が大きく変わったときには
以前のを無視するようなことができたらいいですね。

**Comment by snext1220** [comment]
ご確認有難うございます！

キャッシュ＞はい、一番良いのは、タイムスタンプなど付与してファイル名そのものを変更することなのですが、こちらはファイル管理の自動化が前提となりますので（手作業だと地味に半端ない^^;）、今後の課題とさせてくださいませm(_ _)m

**Comment by snext1220** [comment]
https://github.com/snext1220/stext/issues/117#issuecomment-502332000 のお返事です（個別スレに移動いたしました）。

サイト側のメインアイコンは、色付きの方にて反映させて戴きました！
早速ありがとうございます！

ゲーム画面とサイトとで明確に区別もついて良いかなと思っておりますが、 @toki-sor1 さんのイメージと異なるようであればお知らせくださいませm(_ _)m

**Comment by toki-sor1** [comment]
お返事＆メインアイコン反映ありがとうございました！
確認しましたが、ゲーム画面とサイトとで使い分けるアイデア、とてもいいと思います！
今後もしサイズなど調整の必要が出てきましたら、気兼ねなくご相談くださいませ～。

**Comment by snext1220** [comment]
> ゲーム画面とサイトとで使い分けるアイデア、とてもいいと思います！

ご賛同ありがとうございます！
ゲーム画面のコントロールバーは、全ダイアログが揃ってからのリリースになるので、暫くはGitHubのみのリリースになりますが、活用させて戴きますね…！

> 今後もしサイズなど調整の必要が出てきましたら、気兼ねなくご相談くださいませ～。

お気遣いありがとうございます！早速で恐縮なのですが（汗

> 背景（現在は黒一色だが、流石に殺風景？）

については如何致しましょうか。シンプルという意味では絶対なしではないと思うのですが、一寸寂しいかなと思いましてf(^^;

**Comment by toki-sor1** [comment]
> ゲーム画面のコントロールバーは、全ダイアログが揃ってからのリリースになるので、暫くはGitHubのみのリリースになりますが、活用させて戴きますね…！

はい～、承知しました！

> 背景（現在は黒一色だが、流石に殺風景？）については如何致しましょうか。シンプルという意味では絶対なしではないと思うのですが、一寸寂しいかなと思いましてf(^^;

BONUSダイアログにはめ込んでいたので、右下がやや寂しいかなという感覚はあったのですが、確かに他のダイアログとなると何もないところが寂し気でしたね；

今度の**wp3.png**は星を散りばめてみましたが、画像の大きさの感覚がちょっと掴めてなくて、壁紙に適していない大きさになっていましたらすみません；；
また、星を散りばめるのにあたって、透過素材ではなくなってしまったため、黒背景限定になります；
https://onedrive.live.com/?id=4837C202555BE782%216763&cid=4837C202555BE782
![wp3](https://user-images.githubusercontent.com/42646342/59922739-69910000-946c-11e9-8c4b-63ad7ce6476f.png)

**Comment by snext1220** [comment]
> BONUSダイアログにはめ込んでいたので、右下がやや寂しいかなという感覚はあったのですが、確かに他のダイアログとなると何もないところが寂し気でしたね；

あ、こちらはスミマセン、STextサイトの背景の方でした…
＃早速ご対応戴いたのに、言葉足らずで申し訳ありません。。

たぶん、右上の紋章を外して、星を若干薄めにしていただくといけるのかなと思ったのですが、お願いしても宜しいでしょうか（汗

ちなみに、ダイアログについては、右上固定配置（repeatなし）となるため、まずは、先日のwp2.pngでいければと思っています～
＃サイズが変化する環境では、現状のデザインで万遍に敷き詰めるということが難しいため；逆に、敷き詰めるには紋章を外さないと難しいかもです～

**Comment by snext1220** [comment]
細かな修正をしています。

シナリオページで...

+ PC環境では作者名を表示（シナリオ詳細に追加していた作者名を削除）
+ モバイル環境では現状維持

**Comment by toki-sor1** [comment]
遅くなってしまい申し訳ありません……！
Win 8.1／Chrome 76.0.3809.87(64bit)、iPhone 7／Safariにて表示確認。
それぞれの環境の設定に合わせた表示になっていました。

**Comment by cocotori** [comment]
Win 10/Firefox、iPad/Safariで確認しました。
全体的に、モバイルは情報を少なくしすっきりに、
PCは情報量を多めに、というコンセプトの統一感が
感じられていいと思います！
