### ISSUE TITLE
戦闘用ダイアログの追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#129]
https://github.com/snext1220/stext/issues/117#issuecomment-497334334 を受けてのIssueです。

新規にBattleシートを設けました（GitHubのみ反映）。

+ Battleメニューからオープン
+ そのシーンの敵情報に加え、ダイス／簡易ステータスなどをまとめて表示
+ 現時点では自動計算、ダイスなどは動作しません。

### 懸案

+ ダイアログを増やしたことで諸々不具合も出ていますが、暫定なので、現在は新規のシートのイメージとしてのみご覧ください（すべてのダイアログが揃ったところで調整します）。
+ 背景、戻るの画像は要相談です。
+ 本文を表示したままBattleダイアログを表示するか、他ダイアログのように切り替えにするかは迷い中（乞うご意見）

**Comment by snext1220** [comment]
スクロールしてもページが元に戻らないよう、横からのスライドシートとして再実装しました。
現状のページとの互換性を保つために、まだダイスは動作しません。

こちら、UIとして賛同得られるようであれば、機能も本格移行し、デザインの本格リニューアルに先立ってリリースできればと思っておりますので、ご確認戴けますと幸いですm(_ _)m

＃ その場合、新メニューバーのリリースはまだ先になるため（ステータスダイアログまで移行してからなので、本格リニューアルのタイミングになるかも）、現状のコントロールパネルにボタンを一つ追加する必要がありますが、 @toki-sor1 さん、その際は時期含めてご相談させて戴けますとm(_ _)m

**Comment by toki-sor1** [comment]
返信が遅くなってしまい申し訳ありません…！
こちら、ご対応お疲れ様です！

新UIはスタイリッシュな感じでいいですね！
現在のUIでは、複数の敵を設定すると、ゲーム画面がかなり縦に伸びてしまうので、そういう意味でもスライドシートにまとまった新UIは、スッキリとしていて見易いです！

ただ、iPhone7などモバイル環境の場合、以下の点が気になりました。

- 縦持ちだとスライドシートの横が見切れる（戦利品辺りが見えない）
- 横持ちだとダメージのポップアップが見切れる（上部しか見えない）

> 現状のコントロールパネルにボタンを一つ追加する必要がありますが、 @toki-sor1 さん、その際は時期含めてご相談させて戴けますとm(_ _)m

了解しました！
ボタンのデザイン案やサイズがお決まりになりましたら、教えていただけますと助かります～。

**Comment by snext1220** [comment]
ご指摘ありがとうございます！
モバイルでの現象については、（iPhone環境は手元にないのですが）Android環境で別途確認しまして、縦置き前提で改善していければと思います。少々お待ちくださいませ～

> ボタンのデザイン案やサイズがお決まりになりましたら、教えていただけますと助かります～。

ご快諾ありがとうございます！
ボタンサイズは現状のコンパネに並べる予定なので、他のボタンと同じサイズにてお願いできますでしょうか。デザインについては、Battleなので剣と杖が斜めに交叉しているようなデザインがイメージしやすいかなと思いますが、如何なものでしょうか？

**Comment by toki-sor1** [comment]
> モバイルでの現象については、（iPhone環境は手元にないのですが）Android環境で別途確認しまして、縦置き前提で改善していければと思います。少々お待ちくださいませ～

ご検討ありがとうございます～！　よろしくお願い致します！

> Battleアイコン

![ctrl_battle](https://user-images.githubusercontent.com/42646342/64195822-57482f00-cebd-11e9-8385-62f4b73b7c76.png)
作ってみました！
FIGHTERの剣とWIZARDの杖が属性ボタンと被りそうだったので、（武器を使ってるキャラの）性別反転してみましたｗ　こんな感じで如何でしょう？（https://github.com/snext1220/stext/tree/master/stext/common ）
＃今回こちらにアップしていますが、大丈夫だったでしょうか？

**Comment by snext1220** [comment]
御礼遅くなってしまいましたが、アイコン有難うございました！
バッチリでございます～
組み込みは、戦闘シート完成の後になってしまいますが、暫しお待ちくださいませm(_ _)m

**Comment by snext1220** [comment]
アイコン反映はまだですが、とりあえず以下の対応を行いました。

+ モバイル対応（あふれ改善されましたでしょうか）
+ サイドボタンからのオープン／クローズ
+ 動作の安定化に伴い、メイン画面の敵一覧、ダイス、簡易ステータスを削除

お手数ですが、引き続きご確認のほどをお願いいたします。

**Comment by toki-sor1** [comment]
ご対応ありがとうございます！
モバイル環境で戦闘画面の表示溢れてが改善されていることを確認しました！
また、ダイスの挙動、ダメージ増減、ダメージ半減等の処理、各種トースト、チェックボックス、閉じるボタンも問題ありませんでした！

ただ、メイン画面の敵一覧がなくなったことで、スッキリしたのはとても良いのですが、何か「ここは戦闘あるよ！」と強調する表示などがないと、そのまま戦闘をスルーされてしまうかもしれません。
（右端タップでバトルシートを開けますが、シートを開く必要の有無に関わらず表示されている＆やや目立たないので、文字リンクによる誘導やバナーやアイコンなど必要？）

また、戦闘がないシーンで戦闘画面を開いた時の「ここには、モンスターの気配はないようだ。」という表示が、シーンを跨いでボスと戦っているシーンでは違和感がありました。
元のナレーションのように雰囲気のあるものを考えるのは難しいですが、「この場面ではバトルシートを開く必要はないようだ」などに変更すると違和感が薄れるかもしれません。

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！
こちらで確認しておりましたバグを修正したほか、とりあえずは以下の修正を追加しています。

+ 敵情報がある場合は、開閉ボタンを赤く変化させる
+ ホバー時に開閉ボタンにアイコン表示（PCのみ）

完全解決ではありませんが、い、如何なものでしょうか？？

> 何か「ここは戦闘あるよ！」と強調する表示などがないと、そのまま戦闘をスルーされてしまうかもしれません。

ここが悩ましいですね^^;
最初はenemiesがある場合にだけボタンを表示しようかとも思ったのですが、簡易ステータスやダイスは戦闘に関わらず必要なので、上のような対応となりました^^;
＃ 小さめなのも、常時表示なので～という感じでして；

いずれにせよ、現在のシナリオですと、「下の敵リストから～」のような文言があるので、今回のリリースに合わせてシナリオ側も変更の必要がありそうですね。。。（皆さんにはお手間をおかけしてしまいますが…）

> また、戦闘がないシーンで戦闘画面を開いた時の「ここには、モンスターの気配はないようだ。」という表示が、シーンを跨いでボスと戦っているシーンでは違和感がありました。

こちらは失念しておりました；
文言については、スミマセン、もちっと考えてみたいと思います。。
＃上の通り、バトルシートそのものは敵の有無に関わらず必要ですし；単に、文言なし、というのもありですかね...一寸画面は寂しいですが^^;

**Comment by snext1220** [comment]
@Salvadors-cabin さん＞

お忙しいところ大変お手数ですが、以下の件についてゲスト作者の皆さまにご連絡をお願いしても宜しいでしょうか。非互換というほどではないので、機能そのものに問題がなければ本番リリースはしてしまおうと思っておりますが、見直しては戴いた方が良さそうです。

> いずれにせよ、現在のシナリオですと、「下の敵リストから～」のような文言もあるので、今回のリリースに合わせてシナリオ側も変更の必要がありそうですね。。。（皆さんにはお手間をおかけしてしまいますが…）

**Comment by toki-sor1** [comment]
お疲れ様です！　早速のご対応もありがとうございました！

> 敵情報がある場合は、開閉ボタンを赤く変化させる

かなり見易く、更にバッチリ主張していて良いと思います！

> ホバー時に開閉ボタンにアイコン表示（PCのみ）

- アイコン（画像）を表示というアイデアは、とても良いと思います！
- ただ、アイコンのデザインと開閉ボタンがちぐはぐな印象なので、ちょっとデザインを考え直す必要がありそうですね；（杖と剣の白いシルエットのみ？）

> 最初はenemiesがある場合にだけボタンを表示しようかとも思ったのですが、簡易ステータスやダイスは戦闘に関わらず必要なので、上のような対応となりました^^;

なるほど、簡易ステータスとダイスの問題もありましたか…確かにこれは悩ましいですね…；

#### 良いと思った点
- 開閉ボタンが赤く変化することで「主張」という面では、これで解決しているかなと思います。
- 戦闘関係の情報や機能をバトルシートに収納したことで、一つの画面に表示する情報が絞られ、ストーリーの没入感が増したように思います。

#### 気になった点
- この状態だと簡易ステータスの「そのままの画面で確認できる」という利点がなくなってしまったため、ちょっと不便な感じもしました（＝1アクション必要になってしまった）。
- 開閉ボタンが「Battle sheet」だと非戦闘時にダイスを振る時など違和感があるため、「Battle & Dice」みたいに分ける必要がありそう…？（響きとしてはBattle sheetが良いのですが）

> 今回のリリースに合わせてシナリオ側も変更の必要がありそうですね。。。（皆さんにはお手間をおかけしてしまいますが…）

いえいえ、システムアップデートには修正が付き物ですから、こればかりは仕方がないですよ～。
テキスト修正は、そこまで急を要するものではないと思いますので、正式アップデートの際には、各人無理なく修正を進めていただく感じになりますかね。

> 文言については、スミマセン、もちっと考えてみたいと思います。。
＃上の通り、バトルシートそのものは敵の有無に関わらず必要ですし；単に文言なし、というのもありですかね...一寸画面は寂しいかもですが^^;

お手数をお掛けしてしまいますが、よろしくお願い致します～…！
＃はいー、文言無なし、というのもありだと思いますね～。ただ、仰るとおり画面はちょっと寂しい感じはしますね…；

**Comment by snext1220** [comment]
ご確認＆ご指摘ありがとうございました！
地味に、UI的にはリリース以来の大変更なので、やはり諸々問題が出てきますね^^;

> ただ、アイコンのデザインと開閉ボタンがちぐはぐな印象なので、ちょっとデザインを考え直す必要がありそうですね；（杖と剣の白いシルエットのみ？）

コンパネと同列感を出そうと思ったのですが、うまく表現できておりませんでした^^;
むしろ通常の黒／赤ラベルだけに戻した方がスッキリでしょうか？（汗

> この状態だと簡易ステータスの「そのままの画面で確認できる」という利点がなくなってしまったため、ちょっと不便な感じもしました（＝1アクション必要になってしまった）。

ここは若干悩みましたが、以下の理由からママで如何でしょうか。

+ これまでも余程短いページを除いては、ページ下部までスクロールの必要があった
    + 今回はボタンはスクロールについてくるので、スクロールがクリックに代わっただけで手間はほぼ同等になるかと。
+ ステ確認の大部分は戦闘とセットになるかと思うので、近接していた方が使いやすいのでは？

> 開閉ボタンが「Battle sheet」だと非戦闘時にダイスを振る時など違和感があるため、「Battle & Dice」みたいに分ける必要がありそう…？（響きとしてはBattle sheetが良いのですが）

こちらも悩ましいですが、ママ押しですかね…^^;
ラベルは極力シンプルの方が良いかと思いますし、ここにあると判っていればそこまで悩まないかな＆厳密を追求すると、StatusなどもStatus＆Equipment＆...的になってしまうのでｗ

> はいー、文言無なし、というのもありだと思いますね～。ただ、仰るとおり画面はちょっと寂しい感じはしますね…；

了解です！一旦は文言なしで行きたいと思います～
＃もちろん文言を入れるのは比較的簡単なので、あとでご希望が出てきたら、改めて対応させて戴きますね。

**Comment by toki-sor1** [comment]
> コンパネと同列感を出そうと思ったのですが、うまく表現できておりませんでした^^;
むしろ通常の黒／赤ラベルだけに戻した方がスッキリでしょうか？（汗

先ほど、GitHubの方に修正したアイコンと差し替えてみました。
文字がダブっていたのも気になったので、文字を消しつつ地の色を活かした白のみの透過アイコンにしてみましたが、如何でしょう？（※画像は戦闘時の状態に非戦闘時の状態をはめ込んでます）
![バトルシートサンプル](https://user-images.githubusercontent.com/42646342/64484596-9ecd1300-d24f-11e9-85d4-a8bca0bc6b2e.png)

> 簡易ステータスについて
Battle sheetの表記について

こちら、リオさんのご意見（意図）を拝見してなるほど納得です！
了解しました、是非このままでお願いします！

> 文言について

こちらも了解です～！

**Comment by snext1220** [comment]
ちょうどcaptive見てて、おぉ変わってる！と感激してたところでしたｗ
おかげさまで新しいタブにもマッチしており、良い感じになったと思います～本当に有難うございます！

文言についてもご了解戴き、ありがとうございます～

**Comment by toki-sor1** [comment]
ナイスなタイミングだったようでｗ
今までのボタンとは違った感じなので、どうかなぁとソワソワしていましたが、ご感想をいただけて安心しましたｗ
Battleボタンは今のところ手直しはありませんので、そのまま使っていただけましたら幸いです～。

**Comment by snext1220** [comment]
滑り込みになってしまいましたが、戦闘シートの追加に伴い、プレイヤーマニュアルも更新しています。
https://sorcerian.hateblo.jp/entry/20171220

マニュアル全体としては、キャプチャが新旧入り混じっているのですが、致命的に変化しているものは差し替えているつもりですので、ご容赦をm(_ _)m

**Comment by Salvadors-cabin** [comment]
確認遅くなり申し訳ありませんが、１件報告です。
iOS9+Safariの環境で、縦向き表示させると画像のような表示になります。
（画像はiPadのスクリーンショットです。加工はしていません）
他の環境ではこの現象は出ていないでしょうか。
![image](https://user-images.githubusercontent.com/42834363/64536320-da510580-d353-11e9-942e-92862362a4a5.png)

**Comment by snext1220** [comment]
Android、iPad（iOS12）環境＋開発者ツールでは、特に再現確認できず、でした...
＃開発者ツールでデバイスサイズを変更しての確認もしてみたのですが、、、Safariのバージョン、ですかね...？

ちなみに（本題ではありませんが）、右のBattle Sheetタブが横書きになっているのは、Safariのバージョンの問題のようです。

**Comment by Salvadors-cabin** [comment]
早速のご確認ありがとうございます。
こちらでも時間をおいてやってみたら問題が解消されていました。
旧バージョンでは不安定な感じです。
お騒がせしました。

あと、ゲストさんへも後日連絡しておきます。少しお待ち願います。

**Comment by snext1220** [comment]
ご確認有難うございます！
とすると、キャッシュの問題かもしれませんね～（途中のCSSが残っていたようにも見えます）
なんにせよ、改善して良かったです！

連絡＞ありがとうございます～お手数ですが、どうぞよろしくお願いいたします！

**Comment by cocotori** [comment]
新戦闘UI、確認してみました。

PCブラウザではかなりいい感じです。
必要なときに必要な情報が表示されて、
だいぶスッキリしたかと思います。

ただ、タブレットやスマートフォンでは
戦闘タブが完全に本文を覆い隠してしまうので、
わかりにくさを感じてしまいました。

すぐダイアログを閉じて確認すればいいだけなんですけどね・・・
なんだか隔絶されてしまった感じを受けるのですよね。
例えば本文の一部をダイアログに表示させられるようにするとか？
（作者が自由にキャプションをつけられる？）
何かしらの工夫があるといいかもしれません。

ですが、個人の感覚の問題もあるので、
このままでも大丈夫です。

**Comment by snext1220** [comment]
ご確認有難うございます！

隔絶＞こちら、確かに悩ましいところですね...とりあえず以下の施策を打ってみました。

+ バトルシートを半透明化
+ モバイル環境でのシートを98％に（横が若干見える）

後者は閉塞感を薄める意味、前者は辛うじて背後のテキストが判読できるレベルなので気休めではありますが^^; （これも別Issueのルールテキストを追加すると、あまり意味はなくなるかも；）
引き続きご意見戴けますと幸いです。

**Comment by cocotori** [comment]
対応ありがとうございます！

半透明になったことで、上にかぶさってる事が
よくわかるようになったと思います。

正直、この薄さだと下の文字が読めるかというと
読みにくいかと思いますが、これでいいと思います。
今回の修正で、自分が気になっていたのが何だったか、
より鮮明になりました。

画面がバトルシートに変わってしまうことにより、
居場所を見失ってしまう感じを受けていました。
それが、今回の修正で、ああ上に乗ってるだけなんだなというのが
わかるようになって、よくなったと思います。

あと少し気になるのが、
バトルシートの文字の開始位置が上すぎる気もします。
バトルシートを開くタブが少しオフセットした位置にありますので、
そのくらいの高さから始めるのはどうでしょうか。


もう一点、戦闘UIとは別の問題なのですが、
本番環境の一番下に表示される、
Presented By SORCERIAN Next team.
のリンクが古くてリンクエラーになってしまうようです。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

違和感のご説明ありがとうございます。
新UIということで、今後も実際に使っていきながら、諸々出てきそうな気もしますが、適宜調整してまいりましょう。どうぞよろしくお願いいたします。

> バトルシートの文字の開始位置が上すぎる気もします。

こちらについては、10pxほどの上マージンを加えて、GitHubのみ反映済みです。
もう少し下に、ということではあったのですが、現在ルールテキストの話があるので、現時点では下の余裕をもっておきたく。その辺が確定したところで、必要に応じて改めて調整できればと…！

> Presented By SORCERIAN Next team.のリンク

こちらはスミマセン...修正済みでございます。

以上問題ありませんでしたら、本番環境にも反映していければと。
何度も恐縮ですが、最終確認よろしくお願いします～

**Comment by cocotori** [comment]
いい感じだと思います。ありがとうございます！

**Comment by snext1220** [comment]
ココさん、ご確認有難うございます！

では、一旦はこれにて本番反映し、本IssueもCloseとしてまいりますね。
ただ、上の通り、新UIということで、暫くは試行錯誤だとは思いますし、お気づきの点はなんなりとお知らせいただけますと幸いです～

＃勿論、ときのじさんの方もなにかあればなんなりと、です～
