### ISSUE TITLE
表組みのスタイル付け

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#13]
表組みについて、現在、STextでは明確なスタイルが定義されていないため、表は枠線が出ない、など若干使いづらい面がありました。

これらを利用できるように、スタイルを追加できればと。

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 69.0.3497.81（64 bit）、iPhone 7／Safariにて確認。
表の崩れや文字のズレもなく、正常に表示されていました。
