### ISSUE TITLE
実績ダイアログの改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#130]
https://github.com/snext1220/stext/issues/117#issuecomment-497334334 を受けてのIssueです。

実績ダイアログをボーナスダイアログ同様、非ダイアログしました（ゲーム画面との切り替えに）。ただ、大きくなったことで若干見た目がスカスカになってしまったかもしれません。

本格的にはリニューアル時とは思っていますが、もし手軽に対応できそうな改善案があればお願いします。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 75.0.3770.142(64bit)、iPhone 7／Safariにて表示確認。
- 以前より見易くなったと思います。
- スマホから見ると画面が詰まっているので丁度良い感じがします。
- PCから見ると、仰る通りスカスカに見えてしまいますね；

改善案ですが、私からはこの二点でしょうか。
- stextページのシナリオタイトルに使っている壁紙のように、右端に図を入れて下方に繰り返すタイプの壁紙にする。
- トロフィー毎に区切りの線を入れる。

**Comment by Salvadors-cabin** [comment]
ちょっと気になるところがありましたのでご報告です。
実績を積んでいくと同じ実績が２回表示される現象が見受けられました。
Win10(64Bit)+Edge・GitHUB環境で確認しています。

画像を添付します。
![AugTest2-20190731](https://user-images.githubusercontent.com/42834363/62181996-12961900-b390-11e9-806f-77e522540f29.png)
![AugTest3-20190731](https://user-images.githubusercontent.com/42834363/62181997-15910980-b390-11e9-886b-9948ed9d5d02.png)

**Comment by snext1220** [comment]
ご確認ありがとうございます！

@toki-sor1 さん：

> PCから見ると、仰る通りスカスカに見えてしまいますね；
> トロフィー毎に区切りの線を入れる。

やはり一寸右が寂しいですよね...とりあえず私の方ですぐに対応できる区切り線のみ対応してみました。如何でしょうか？
＃ 背景はときのじさんのお力をお借りしなければなりませんが；、どうしましょうかね。暫定なのでまずはママとし、あとはレスポンシブ対応で1／2段組み切り替えなどを検討？

@Salvadors-cabin さん：

> 実績を積んでいくと同じ実績が２回表示される現象が見受けられました。

失礼しました；
実績表示時の初期化処理に関するバグでした。。
先程修正し、GitHub Pagesには反映済みです～

**Comment by Salvadors-cabin** [comment]
早速の対応、お疲れ様ですー。
問題が解消されていることを確認しました。

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！
初歩的なバグにてお手数をおかけしました＞＜;

**Comment by cocotori** [comment]
![スクリーンショット 2019-08-05 21 54 32](https://user-images.githubusercontent.com/42885160/62466198-b1c17300-b7cb-11e9-899d-554e004e7e7b.png)

ものによっては結構長めのテキストの実績もあるので、
個人的にはこのままでもいいような気もします。
黒背景、スッキリしててスタイリッシュですしね。

区切り線はあると、よりわかりやすくなったと思います！

**Comment by toki-sor1** [comment]
> やはり一寸右が寂しいですよね...とりあえず私の方ですぐに対応できる区切り線のみ対応してみました。如何でしょうか？

ご対応お疲れ様でした！
区切り線が入って、実績同士の境が明確になって見やすくなったと思います！

> ＃ 背景はときのじさんのお力をお借りしなければなりませんが；、どうしましょうかね。

背景壁紙の改変であればこちらで対応可能ですが、時期的に素材の考案・加工は厳しめですね；
デザイン変更の場合は、ドラモード後の対応になってしまうと思います；

ただ、視認性という意味では、ココさんも仰っているように、黒が多めの方がスッキリしていて見易いというのも確かなんですよね（実績のテキストが長めのものだと特に）。
背景壁紙のデザインはもっと洗練させたいとは思っていますが、区切り線が入ったことでスカスカ感は緩和されてきた印象なので、ちょっと様子を見ても良いかもしれません。

> 暫定なのでまずはママとし、あとはレスポンシブ対応で1／2段組み切り替えなどを検討？

実績はズラ～～っと並んでいるのを見るのが視覚的にも楽しいかなと思っているので、個人的にはこのままの並びの方が好みですね。

**Comment by snext1220** [comment]
ご確認有難うございました！
＃区切り線については効果あったようで良かったです。

背景については、若干意見もわかれておりますし、今回は暫定ということでもありますので、ママでまいりましょうか（ @yuco-mizuri さんからも本番移行に関する構成案も出てきておりますので、デザインもそちらに注力していければという趣旨でございます）。

> 実績はズラ～～っと並んでいるのを見るのが視覚的にも楽しいかなと思っているので、個人的にはこのままの並びの方が好みですね。

なるほど。そういう考え方も^^;
あまりに長い縦スクロールはどうかという視点ばかりだったので、一寸目鱗でしたｗ
