### ISSUE TITLE
実績ラベルの空白を復活

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#131]
実績リストに表示される「実績タイトル」から空白が除去されていましたが、scenario.xmlでの指定ママで表示されるように改めました。

**Comment by toki-sor1** [comment]
iPhone 7／Safariにて表示確認。
「終焉」の実績で空白が表示されているのを確認しました。

**Comment by cocotori** [comment]
こちらも確認しました！
Win 10/Firefoxです。
