### ISSUE TITLE
シーン移動時のステータス自動計算強化

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#132]
https://github.com/snext1220/snext-management/issues/18 を受けてのIssueです。

シーン移動に伴うステータス自動計算に関する改善です。

+ scene要素にstr～krm属性を追加（指定可能な値は増減値のみ）
+ シーン移動時のステータス変化に対してトースト表示
    + ★複数のステータスを変化させている場合、複数トースト表示は五月蠅いかも
    + ★既にシナリオ内で「MPが10減った」などの文言がある場合は重複（既存シナへの影響）
+ hp～mp、str～krm属性で「`@10`」のような固定値指定
    + freeN属性では実装済み
    + ★統一感は出るが、必要性は？（hp～mpは0以下でゲームオーバーなので、0リセットのような用途は考えにくそう。完全回復は現在も指定可）

★は懸案事項なので、ご意見戴きつつ、改定内容は引き続き検討していければと思います。

**Comment by toki-sor1** [comment]
ご検討いただきありがとうございます！
懸念事項のことも含めて意見を書かせていただきますね。

#### scene要素にstr～krm属性を追加（指定可能な値は増減値のみ）
- ありがとうございます！
- 値の指定については、下記の **「hp～mp、str～krm属性で「@10」のような固定値指定」** にて意見を書いています。

#### シーン移動時のステータス変化に対してトースト表示
> ★複数のステータスを変化させている場合、複数トースト表示は五月蠅いかも
> ★既にシナリオ内で「MPが10減った」などの文言がある場合は重複（既存シナへの影響）
- 複数トースト表示は、スマホなどの画面が小さいものだと特に五月蠅そうな感じもしますね。
- 「MPが10減った」などの文言と重複するのは、トースト見逃し時に再確認できるのが利点かとは思いますが、同じ情報が別々の手段で表示されるのは、やはり五月蠅いかもしれませんね。
  - 既存シナの修正も必要になってきそうで、そこもまた気掛かりですね。
- 上記意見から、**トースト表示はなし＋今まで通り文言を入れる**で十分かも、と思いました。

#### hp～mp、str～krm属性で「@10」のような固定値指定
> freeN属性では実装済み
> ★統一感は出るが、必要性は？（hp～mpは0以下でゲームオーバーなので、0リセットのような用途は考えにくそう。完全回復は現在も指定可）
- freeNの数値をリセットできれば使い回しが出来そう、と考えていたのですが、**固定値で「＠0」と指定すれば実現可能**でしたね；　こちら失念しており、大変失礼いたしました；；
- freeNで指定できればと思っていたので、hp～mp属性で固定値指定は特に必要はなさそうですね；
- str～krm属性ですが、増減のみだとキャラクターによっては減算で下限を下回る可能性があるので、**固定値指定（@0）** と、あと０から元に戻す際の上限超過防止策として**full指定** ができれば良さそうかなと思いました。

**Comment by snext1220** [comment]
ご意見有難うございます！

> 複数トースト表示は、スマホなどの画面が小さいものだと特に五月蠅そうな感じもしますね。

そうなんですよね…そもそもそんな複雑な自動更新をすべきか、というのはありますが^^;
また、複数ステの変更は１トーストにまとめる方法もありそうではありますが…既存シナの修正もあることからニーズ次第ですかね；
＃表記が統一されていた方がプレイヤー的に嬉しいというのはありそうです。

> str～krm属性ですが、増減のみだとキャラクターによっては減算で下限を下回る可能性があるので、固定値指定（@0） と、あと０から元に戻す際の上限超過防止策としてfull指定 ができれば良さそうかなと思いました。

了解です～こちらも他の皆さまのニーズを戴きながら、確定していければと…！
ホントはhp、freeN、str系すべて同じ仕様で統一できるのが美しいのですが、使いどころが微妙に異なるのが悩ましいですね^^;

**Comment by snext1220** [comment]
本件、以下の内容でGitHub Pagesを更新しました。ご確認をお願いいたします。
https://sorcerian.hateblo.jp/entry/2018/11/01/211745#str

ただ、現時点でfull指定は初期値に戻るなので、連作でSTR～KRMを成長させていく場合には一寸使いづらいかもしれませんね。。（この事情はHP、MPも同様）

STR～KRMの上限値は現在は変更できないのですが、せめて自動計算だけででも上限を変更できるようにすべきか、やや悩ましいところです（繰り返しですが、HP、MPも同様）。

**Comment by toki-sor1** [comment]
ご報告が遅くなり、大変申し訳ありません……！
更新お疲れ様です！　リクエストのご対応ありがとうございました！
（マニュアル加筆もお疲れ様です！）

Win 8.1／Chrome 76.0.3809.132(64bit)にて正常に動作しました！
私個人は、現状の機能も十分に素晴らしいと思っています～。

> ただ、現時点でfull指定は初期値に戻るなので、連作でSTR～KRMを成長させていく場合には一寸使いづらいかもしれませんね。。（この事情はHP、MPも同様）

連作では基本的にfull指定は使わない、などの対応が必要かもしれませんね（成長させればさせるだけ上がり、原作のように下限を下回るのも許容する等）。

> STR～KRMの上限値は現在は変更できないのですが、せめて自動計算だけででも上限を変更できるようにすべきか、やや悩ましいところです（繰り返しですが、HP、MPも同様）。

うーん、成長させても上限値が変わらないだけに、表示が不自然に見えますもんね；
シナリオ執筆者側が任意で選べる機能として、自動計算だけでも上限値を変更出来ると、現在値と上限値の表示が自然に見えたり、シナリオを手直しするかどうか選べたりで、良さそうな気がします。

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！
まずは、現時点での実装が問題ないとの事良かったです～

> 連作では基本的にfull指定は使わない、などの対応が必要かもしれませんね（成長させればさせるだけ上がり、原作のように下限を下回るのも許容する等）。

はい、この辺は上限値というよりも初期値と割り切れば、それで問題ないと思います！下限も現在は特にガードしていないので負数含めて大丈夫です～

> 自動計算だけでも上限値を変更出来ると、現在値と上限値の表示が自然に見えたり、シナリオを手直しするかどうか選べたりで、良さそうな気がします。

こちらもご意見ありがとうございます～
自動計算オンリーの操作が初めてなので、一寸慎重に、皆さまのご意見待ちつつ、進めてまいりますね。

**Comment by toki-sor1** [comment]
> はい、この辺は上限値というよりも初期値と割り切れば、それで問題ないと思います！下限も現在は特にガードしていないので負数含めて大丈夫です～

おお、問題なしで安心しました！　負数の件も了解です～！

> 自動計算オンリーの操作が初めてなので、一寸慎重に、皆さまのご意見待ちつつ、進めてまいりますね。

確かに始めてとなると既存の機能にどう影響するのかが未知だったりしますもんね；
ぜひ慎重に進めていただけたらと思います～。よろしくお願い致します！

**Comment by snext1220** [comment]
ご賛同ありがとうございます！
はい、こちらも幕末の成長ルールがどうなるかを見据えながら、仕様確定していければと…！
こちらこそ、引き続きよろしくお願いいたします～

**Comment by cocotori** [comment]
自動更新を行っていく方向に舵を取っているので、
このアップデートはとてもいいと思います。

トースト表示するかどうかは悩ましいですが、
デメリットもよくわかりますので、
現状の本文にて説明する、がいいと思います。

終末の双王にて動作確認しました。

hp,mp全回復とかが回復ポイントとして使えて便利そうです。

**Comment by snext1220** [comment]
ありがとうございます！

表示系の自動化は統一優先か個別の表現優先かで、ホント悩ましいですね。
切り替えもできますが、シナリオの指定はより面倒になりますし。
この辺は実際のシナリオに触れながらの感覚になっていくかと思いますし、引き続きお気づきの点は何なりと、です！
