### ISSUE TITLE
テキストインポート機能の実装

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#133]
https://github.com/snext1220/snext-management/issues/18#issuecomment-514617912
を受けてのIssueとなります。

そこまで利用頻度が高い機能ではない＆他でも代替できるため、優先順位は低いですが、リクエストの程度に応じて検討していければと思っています。

#### グローバルインポート

scene要素配下に${import **@save**}のような埋め込み構文で、あらかじめシステム側で用意しておいたテキストを埋め込める（ここではsave.txt）。セーブポイントや戦闘の説明など、シナリオ内部でよく利用する文言を統一するのが目的

#### ローカルインポート

+ init－texts要素で再利用可能なテキストを準備
+ 同じく ${import **hoge**}で、scene要素から引用可能（`@`の有無でグローバル／ローカル識別）

### 開発メモ

+ ${import}の優先順位最大

**Comment by toki-sor1** [comment]
ご検討いただきありがとうございます！

> グローバルインポート

- セーブポイントを導入し易くする意味でも、シナリオをより遊び易くする意味でも、良い機能だと思います。
- 今後、連作シナリオで共通したテキスト（ルールなど）が必要になってくる場面もあるかもしれないので、そういう時にも役立ちそうですね。

> ローカルインポート
- 同じシーンに同じバッドエンド行きの選択肢を複数入れると、URL（scene id）でネタバレしてしまうので、それぞれ別のシーンに同じテキストを入れて対応していることもあります。
  - その時に、「同じテキストのうちの1つを修正して、もう1つの方を修正し忘れる」とか「同じテキストで文字数ばかりが増えてしまう」というのが悩ましく。
  - そう考えると、ローカルインポートができると楽そうだなと思いました。

**Comment by snext1220** [comment]
こちらもご意見ありがとうございます！

なるほど、連作シナでのルール指定ではインポート機能は有効そうですね！
実は、グローバルインポートが実装上の問題が発覚してしまったもので、少々検討が必要そうですが（ローカル～は問題なし）、できるものから実現していければと思います。

ちなみに、インポートテキストに対して、呼び出し元から値を引き渡せるなどの機能は必要でしょうか。以下イメージです。

```
// 呼び出し側
${import hoge}
  ほげほげ
${/import}

---
// インポートテキスト

こんにちは、${embed}さん！

---
// 結果

こんにちは、ほげほげさん！

```

ここでは単一の値しか埋め込めませんが、複数の値であれば、以下のようになるのかも。
```
${import hoge name:リオ title:ソーサリアン}
  ほげほげ
${/import}
```

あまり複雑な実装になるのも避けたいですが^^;、どのレベルで再利用していきたいのかの感触があれば、是非にお願いします～

**Comment by toki-sor1** [comment]
具体的な使用例やご提案ありがとうございます～！

> 実は、グローバルインポートが実装上の問題が発覚してしまったもので、少々検討が必要そうですが（ローカル～は問題なし）、できるものから実現していければと思います。

おおっと、グローバルインポートは問題発覚ですか……！　検討の件、了解でございます！
一方のローカルインポートの方は問題ないようで安心しましたｗ
お忙しいところ恐縮ですが、引き続きよろしくお願い致します～……！

> インポートテキストに対して、呼び出し元から値を引き渡せるなどの機能は必要でしょうか。

複雑なテキストになると上記イメージのように呼び出せれば、間違いもなく便利かなと思います。
ただ、上記イメージの使い方は改行に対応させ辛く、単純にコピペだけでも間に合ってしまうことから（おそらく改行なしの短文での利用が主だと想定）、個人的にはそこまで利用頻度は高くならない感じもしました；

このインポート機能は**文章量が多いのテキストを呼び出す方が利用頻度が高そうな印象**ですね。

**Comment by snext1220** [comment]
> ただ、上記イメージの使い方は改行に対応させ辛く、～～

あ、こちら若干誤解があったようなので、補足でございます。

```
${import hoge name:リオ title:ソーサリアン}
  ★ほげほげ★
${/import}
```

複数の場合、name／titleなどは改行なしが前提ですが、本体部分（★～★）については改行＆タグ付きのテキストを許容する予定です。
＃ 一か所だけであれば、改行付きテキストの埋め込みが可能（2個目以降は改行禁止）


作り込んでいくとキリはないですし、あまり複雑にしても却って使いにくくなるという話もありますが^^;、部分的に異なるテキストの埋め込みがそれなりにある場合には、そこまでサポートしておいた方が良いのかも、という提案でございました。

> このインポート機能は文章量が多いのテキストを呼び出す方が利用頻度が高そうな印象ですね。

だと思います！テキストの推敲を考えても、細切れなテキストの場合はコピペで埋め込んだ方が確認しやすそうですね～

**Comment by toki-sor1** [comment]
お返事が遅くなり、申し訳ありません…！

> あ、こちら若干誤解があったようなので、補足でございます。

あわわ、勘違い失礼致しました…！；；
一か所だけであれば、改行付きテキストにも対応可能なのですね！　す、素晴らしい…！
私の場合、戦闘時にルールの説明文もセットであることが殆どなので、特に中編～長編だと威力を発揮しそうな印象です！

> 作り込んでいくとキリはないですし、あまり複雑にしても却って使いにくくなるという話もありますが～

そうですね、確かに作り込んでいくとアレもコレもとなってしまい、開発者側も開発が大変＆利用者側も機能が把握し切れないなど問題が出てくると思います～。

こちらの機能についても、皆さんのご意見を伺って利用頻度が高くなさそうでしたら、こちらは廃案または他の機能を優先してやってくださいませ～。

**Comment by snext1220** [comment]
ご意見有難うございます！
こちら皆さまのご意見戴きながら、引き続き方向性決めていきますね。

皆さま＞ご意見お願いします。

+ 呼び出し元からの値埋め込みの機能必要／不要
+ 必要の場合
    + 短い単語程度で十分（複数）
    + 複数行テキストが欲しい

**Comment by snext1220** [comment]
とりあえずごくシンプルなローカルインポートのみを実装してみました。
上で挙げているようなより高度な機能については、ご要望を伺いながら追加実装していければと思いますので、引き続きご意見戴けますと幸いです。

https://sorcerian.hateblo.jp/entry/2018/11/01/211745 （共通テキストの埋め込み）

**Comment by cocotori** [comment]
否定的な意見になってしまって申し訳ありませんが、
わたしはこの機能にはどちらかというと反対、かなと思っています・・・

・ruleがシーンのテキストを呼び出すのに対し、
　こちらはimportタグのテキストを呼び出すもので、
　コンセプトに違いがある。

・機能が増えすぎている感じがあり、執筆ルールの把握が大変そう。
　文字を読み出す機能で、例えばキャラクター名等は
　タグを使うしか方法がないのであってもいいが、
　任意テキストはコピペでも対応できる。

等の理由からです。
確かにときさんが仰られるように、
urlネタバレを防ぐための同文章別シーンには
役立ちそうではあるのですが。

逆に、urlを表示させなくするとかはできないですかね。
ブラウザ側の問題いなってくると難しいかな・・・

**Comment by snext1220** [comment]
ご意見ありがとうございます！

> わたしはこの機能にはどちらかというと反対、かなと思っています・・・

す、スミマセン、こちらは現状既に組み込んでもしまったので、とりあえず維持の方向でご相談させて戴ければ助かりますが、「コンセプトに違いがある」について、もう少しだけお教え戴いても宜しいでしょうか。基本、いずれも「シーン内に別シーンのテキストを埋め込む」という機能だととらえていたのですが（埋め込み先が本文かサイドバーかという違いだけ）、わかりにくいでしょうか？（汗
※どこまで、というのはありますが、まずは仕様面でわかりにくい点を少しでも改善できればと。

> 機能が増えすぎている感じがあり、執筆ルールの把握が大変そう。

これは、本件だけでなく、今後本体の機能追加をどうしていくか、ですね...既に機能もおなか一杯という話は出ていたので、保留となっている自動化機能なども一旦ご相談かもしれません。

あとは、今回の件とはやや別観点になってしまうのですが。
現在は、ある程度スレが進んだところで、どんどんEnhancementをConfirmed扱いで改定進めているのですが、改めて皆さん同意のもとでConfirmedに進める、という流れを採った方が良いでしょうか。今回機能テストの段階で、修正要件ではなく機能そのものの要否が話題になったので、少々気になった次第でした^^;

同意そのものにいちいちReminderを出してまわるのはいかにもウザそうなので、同意→改定の流れはあまりそぐわないのですが、機能テスト段階でのRejectも辛いので、どうしようかなと悩ましく...；
＃否定意見はとてもとても歓迎なので、あくまで進め方の問題、ということでご了承くださいませ；

> 逆に、urlを表示させなくするとかはできないですかね。

こちらはスミマセン、現時点では難しいですね...
そもそもリンク機能をそのまま移動ボタンとして利用しているのを変更すれば、なのですが、そもそもMarkdownの一部としてリンクを書いているところからの変更になってしまうので^^;

＃まったく先の話ではありますが、SText 2.0でシナリオ形式を変更して、リンク指定を本文から切り出せば可能、というレベルです。。

**Comment by cocotori** [comment]
こちらこそ後出しのイチャモンのようになってしまってすみません・・・！
すでに組み込んで運用してもらっているものですので、
現状維持ということで問題ありません。


コンセプト違いについて、うまく説明できるか自信がないのですが・・・

まず、外部から参照して文字なり何なりを持ってくる、
という概念が初心者にはわかりにくいと思っています。

しばらく経ってくると、ここに書いた内容はシーン内で参照できる、
ということがわかってくると思います。
ヘッダ部分の、敵とか、アイテムとか、今回のテキストインポートとか。

それと比べると、ruleは別のシーンに書かれた内容を参照できるという、
少し毛色が違う仕様のように思え、混乱するのはないか、
と心配しました。
（なのでどちらかというと、テキストインポートより
　ruleの仕様の方が難しい？）


Enhancementについては従来どおり、
案が出た時点でどんどん改定していってもらって大丈夫だと思います。
みんなの意見が固まるまで待ってしまうと、それだけで
遅れが出てしまうと思いますので。

今までも、従来と互換性がなくなるような変更の場合には
合意が得られてから進めてもらっていますし、
その感じの進め方で全く問題ないかと思います。

今回はわたしが完全に後出しでしたね・・・

**Comment by toki-sor1** [comment]
ここまでの流れを拝見して、個人的には以下のように考えています。

### テキストのインポート機能
- 既に実装していただいている機能ですので、現状はルール＆本文テキストのインポート機能は、様子見しつつ改めて時期を見て改定か否かを議論するのが良いかなと思っています（こちらの機能は、私自身の要望をご検討いただいたものなので、賛成派です～）。

- URL隠しができれば必要性が薄れると思いましたが、現時点ではURL隠しは難しいとのお話でしたので、現状維持かなと（実は私もこれをチラッと考えたのですが、従来のゲームブックではシーンの数字を隠したりするのは不可能なので、書きませんでした）。

- ただ、ココさんの仰る通り、ルール＆本文テキストのインポート機能は、似たような機能であるものの、毛色の違いから作者が混乱してしまう可能性もあります。
  - インポート機能に限らず、特殊な機能に関しては、文字だけだと分かり辛いところがあるのは否めないので、図などを使った具体的な解説が必要かもしれません。

### 改定の進め方
- 本来であれば、全員の意見が揃ったところで改定というのが望ましいのかなとは思うのですが、ココさんの仰る通り、デメリットとして「意見が一致しなかった場合に議論が長引く（＝改定が遅れる）」というのもありますので、なかなか難しいとは思います。

- 意見を述べるタイミングがそれぞれに異なることもありますし、新機能もテスト段階を過ぎた頃に良し悪しが見えてくるものもあると思います。

- 既に実装されている新機能に関しては、後に改めて「要議論の箇所をまとめ、改善が必要な場合は議論する」「リオさんに使い勝手が気になるところをピックアップしていただく（そのことに関して議論の参加者が答える）」という感じになるのかなと。

- まとめると、改定の進め方は、現状のままが良いかなと思っています。

**Comment by snext1220** [comment]
ご意見有難うございます！
お二方のご意見引用しながら以下お返事してまいりますね。

> こちらこそ後出しのイチャモンのようになってしまってすみません・・・！

いえいえ、とんでもないです！
共同創作／開発していると、どうしてもYesに傾きがちなので、cocoさんの別角度からのご意見にはいつも助けられています（本当に！）。今後とも忌憚なきご意見よろしくお願いしますm(_ _)m

> まず、外部から参照して文字なり何なりを持ってくる、～～～
> それと比べると、ruleは別のシーンに書かれた内容を参照できるという、～～

確かに外部参照はリレーショナルデータベース的な考え方なので、非開発層にはハードルが～というのはありそうですね；
ただ、そこまでは仕方ないとして、今回のインポート＆ルールは自己参照（＝シーンがシーンを参照する）点でわかりにくいのかなと解釈しました（正しい？）。
そうした意味では、同じ参照系でも、元々の実装であったtext要素としてシーンとは別定義する方が、従来と考え方は一致している（わかりやすい）ということだったのかもしれません（?）
https://github.com/snext1220/stext/issues/136#issuecomment-531830278

> 様子見しつつ改めて時期を見て改定か否かを議論するのが良いかなと思っています（こちらの機能は、私自身の要望をご検討いただいたものなので、賛成派です～）。

ありがとうございます！
議論についても了解です。ある程度までは慣れなどの問題もあると思いますし、折角実装もしてしまったので、実際に皆さんのシナにも取り込んで戴き、是非「こんな形であればもっと使いたい！」など発展的に議論していければと…！

> 図などを使った具体的な解説が必要かもしれません。

ですね～
ドキュメントもおなか一杯的なご意見もあり、どうシンプルに、かつ充実させていくか、中々に難しいところですが、#76 のTrial強化などとも連携しながら、ぜひご相談させて戴ければと…！

> Enhancementについては従来どおり、
> まとめると、改定の進め方は、現状のままが良いかなと思っています。

は、こちらもお二方から大枠ご了承戴きましたので、現状ママで引き続きよろしくお願いいたします！なかなか定期的に確認、というのも難しいとは思いますが、是非お気づきのものからご意見戴ければ幸いですm(_ _)m
