### ISSUE TITLE
ランダムな移動と新構文の併用

### ISSUE THREAD

**Issue by toki-sor1** [snext1220/stext#134]
現在執筆中の「終末」のシーン移動でちょっと困ったことがありました。

【意図】Scene AのフラグとScene Bのフラグのどちらかを既に得ている場合に選択肢ボタンを表示させる（尚且つランダム移動させたい）
`
[王子を召喚する（一撃必殺）](400401,400401,400402,400401,400401 "oFREEI4+&amp;!f400401|!f400402")
`
上記のような意図でリンク先を指定していたのですが、**ランダム移動のように複数の移動先を指定した場合は、選択肢ボタンが画像扱いになってしまう**ようでした（添付画像参照）。
![image](https://user-images.githubusercontent.com/42646342/62824672-9516a800-bbdc-11e9-80c8-c91b25b3529c.png)

**しかし、指定のシーンを1つまで減らすと画像にはならず、選択肢ボタンが表示されました。**
どうもランダム移動との組み合わせが良くないようですね；

こちら、ランダム移動をなしにして内容に変更を加えれば対処可能です。
急ぎの案件ではないのですが、お手隙の際にご確認いただけましたら助かります。

**Comment by snext1220** [comment]
まず現状ですが、
こちらランダム移動、任意移動ボタンなどでは、条件分岐を想定していなかったもので、未対応でした^^;

で、とりあえずランダム移動のみ対応し、先ほどGitHub Pagesにのみ反映してみましたが、如何でしょうか。地味に条件分岐の根幹を弄っているもので、もし可能であれば、Oct Updateによる機能テストを経てからのリリースにした方が無難、かもしれません（過去も問題の多かった箇所なので；）。

エピに影響が出てしまうので、お手数ですが、ご検討くださいませm(_ _)m

**Comment by toki-sor1** [comment]
お忙しいところ、早速のご確認とご対応ありがとうございました！
最新版のstext-masterをDL後、動作確認を行いました。
#### 動作確認環境：Win 8.1／Chrome 76.0.3809.100(64bit）
![image](https://user-images.githubusercontent.com/42646342/62844901-82e15a80-bcff-11e9-96c9-58315b3fc6ce.png)
結果、選択肢ボタンも正常に表示され、ランダム移動によりScene 400201と400202に移動できることも確認しました！
ただ、過去に問題の多かった箇所ということもあり、機能テストをしっかりと行ってからのリリースの方が良さそうですね。

今回は**該当の箇所の仕様を変更し、ランダム移動＋新構文の組み合わせは使用しない**ということで対応したいと思います～（Scene数がなかなか多くなってきたので、Scene数削減はある意味助かったといいますかｗ）。

**Comment by snext1220** [comment]
お忙しいところ、ご確認ありがとうございます！

> 機能テストをしっかりと行ってから～～

こちらもご了承ありがとうございます！
こちらはできれば早いリリースの方が良いと思うので、（本当は次はNov Updateのつもりだったのですが^^;）Oct Updateを設け、こちらで皆さまにもご確認をお願いできればとm(_ _)m
＃ 間に合えば、戦闘シートの刷新なども加えていく予定です～

> 今回は該当の箇所の仕様を変更し、ランダム移動＋新構文の組み合わせは使用しないということで対応したいと思います～

シナ変更ということで恐縮です；Scene数削減にはお役に立ったようで？？^^;

#### 余談

と、ふと思ったのですが、実は${if}構文でのランダム選択などってニーズがありますかね。以下のようなイメージ（優先順位は低いとは思いますが^^;）

```
${if rand}
表示1
---
表示2
---
表示3
${/if}

```

**Comment by toki-sor1** [comment]
お返事が遅くなってしまい、申し訳ありません…！

> こちらはできれば早いリリースの方が良いと思うので、（本当は次はNov Updateのつもりだったのですが^^;）Oct Updateを設け、こちらで皆さまにもご確認をお願いできればとm(_ _)m
＃ 間に合えば、戦闘シートの刷新なども加えていく予定です～

> シナ変更ということで恐縮です；Scene数削減にはお役に立ったようで？？^^;

先日はご対応ありがとうございました！
仲間の召喚タイミングによって選択肢が複雑化していたので、Scene削減できたのは大きかったですね…ｗ（その代わり、予定にないルートを思い付いて執筆していたのでプラマイゼロのような気もしますがｗ）

リリースのタイミング、戦闘シートの刷新についても了解です！
よろしくお願い致します！

> と、ふと思ったのですが、実は${if}構文でのランダム選択などってニーズがありますかね。以下のようなイメージ（優先順位は低いとは思いますが^^;）

選択肢をランダムに表示する、というイメージでしょうか？
確かに使用するシーンはそう頻繁にはなさそうなので、優先順位は低めかなとは思います。
ただ、現在の選択肢ボタンの設定だと、選択肢の名前までは変えられないので、選択肢の違いを明確に表すのであれば、こちらの機能は有効かなと思いました。

いずれにしても、現時点では絶対に必要！という機能ではなさそうかなと思います～。

**Comment by snext1220** [comment]
> （その代わり、予定にないルートを思い付いて執筆していたのでプラマイゼロのような気もしますがｗ）

きっと後編でも、中編ドラ1ルートに追加が出るはず…！（こっそり期待ｗ）

> 選択肢をランダムに表示する、というイメージでしょうか？

いえ、Scene内でテキストの一部をランダムに切り替え表示するイメージです。
今回のリクエスト拝見して、なんとなくですが、ランダムリンク先は内容が大部分共通しているのでは、と思われましたので、実はシーン内分岐の方の用途があるのかなと^^;
勝手な予想なので、丸外しであればスミマセン；；
＃いずれにせよ、優先順位は低めだとは思われますが…^^;

**Comment by toki-sor1** [comment]
> きっと後編でも、中編ドラ1ルートに追加が出るはず…！（こっそり期待ｗ）

へへへ、ダークドラゴン戦はあと3ルート＋隠し1ルートはあるので、こちらはそのままかな～とは思うのですが、後編で先ほど新たな変則的なルートを思い付いたのは、ここだけのお話です…ｗ

> いえ、Scene内でテキストの一部をランダムに切り替え表示するイメージです。

おお、ご説明ありがとうございます！　イメージが掴めました！
なるほど、今まではフラグによって表示する文章を制御するのみでしたし、ランダム表示できるのは短文のみでしたが、こちらの場合は文章をまるっと切り替える感じなのですね。

ただ、今回の双王でランダム性を取り入れようとしたルートでは、トロフィーをそれぞれに設定しているので、やはりScene自体を分ける必要がありますね；（すみません；；）

しかし、たとえば1つのシナリオ内で同じSceneを往復することが多い構成の場合は、町の人の会話内容が変わるなど、Sceneを増やさずに手軽にバリエーションを豊富にすることもできそうですね。

**Comment by cocotori** [comment]
条件分岐とランダム移動の組み合わせ、確認しました。
無事動いています。

ランダム周りは動作確認も大変そうですね・・・！
作る方も頭がこんがらがってきそうなので、
慎重に使いたいです。

**Comment by snext1220** [comment]
ランダムはじめ機能が増えてきましたので、組み合わせ次第でホント、さまざまなことができてしまいますものね...（やり方次第では結構トリッキーなことも）

システム的にはいろんな機能に触って戴きたいと思う一方、実際のシナリオではシンプルな実装が推奨です^^;（主に保守性の観点から）
