### ISSUE TITLE
エンディング時（happy/end）のリンク処理の変更

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#135]
以下コメントを受けてのIssueです。
https://github.com/snext1220/stext/issues/79#issuecomment-526422979

エンディング時のリンク表示を以下のように改めます。

+ happyで［ペンタウァに戻る］を表示
+ badは現状維持
+ nextsは特に対処しない

以下は、皆さんのご意見を戴きながら対応していければと（現状は未対応）

> ※ただ、nextsについては、リンクではなく、たとえば「※クリアデータは、そのまま次のシナリオに引き継がれます。」のような文言をリンクの下に表示させるのもありかもとふと思いました

**Comment by toki-sor1** [comment]
DMからの意見の移動等ありがとうございました！

> 賛成です！確かにhappyで［最初から～］はあまり意味がないんですよね（当初はマルチエンディングに挑戦するため、という趣旨はありましたが）^^;

> happyで［ペンタウァに戻る］を表示

そうですね、私もhappyの場合はマルチエンディングに挑戦するという認識でおりましたが、表現としても［ペンタウァに戻る］の方が自然だと思います。

> badは現状維持
nextsは特に対処しない

はい、こちらも賛成です～。
nextsについては、今までになかった機能であることを考えると、「※クリアデータは、そのまま次のシナリオに引き継がれます。」と表示させるのも分かり易くなって良いと思います。

**Comment by snext1220** [comment]
ご確認有難うございます！

nexts属性のテキストについてもありがとうございます！
こちらは比較的軽微で、それなりにすぐ対応できそうなのでｗ、幕末の連作ルールなど詰めていく中で確定してまいりましょうかね（次、が結構変則的なので、この辺どのようにナビゲートしていくかが悩ましそう^^;）

**Comment by toki-sor1** [comment]
> こちらは比較的軽微で、それなりにすぐ対応できそうなのでｗ、幕末の連作ルールなど詰めていく中で確定してまいりましょうかね

おお、了解です！
引き続きよろしくお願い致します！

> （次、が結構変則的なので、この辺どのようにナビゲートしていくかが悩ましそう^^;）

「STRを鍛えたい場合は「シナリオ○○」へ」など、次のシナリオを選ぶ指針としてシナリオ名を表示するのも良いかな～と思いました。
＃ただ、シナリオ数が増えれば増えるほど表示するシナリオ名が増えるので、画面が若干うるさくなるなど、表示の仕方が課題ではありますが…；

**Comment by snext1220** [comment]
> ただ、シナリオ数が増えれば増えるほど表示するシナリオ名が増えるので、画面が若干うるさくなるなど、表示の仕方が課題ではありますが…；

そうなんですよね…ストーリー的には、キャラ成長的には、と指針は色々あるんですが、初見の人には、結局どこに行けばいいの、となってしまいそうですし。説明文で、エンディングの余韻?が損なわれるのも若干気にしてみたり^^;

個人的には「ストーリー的な次」のみを示し、他の指針はシリーズ紹介などで軽く、くらいでも、と思ったりも。尤も、サイト本体の方も文字数削減で（ry
＃ただ、これも一覧性の強いシナ紹介と、ワンポイント?で見せるシリーズ紹介や募集は切り分けても良いのかなとは（勿論、極力短くするのは前提で、モバイル環境でスクロールなし程度にはしていきたいですよね...）。

**Comment by cocotori** [comment]
happyとbad、確認しました。

いいですね、
言われてみればなんですけど、
クリアしたのにまた最初から？という違和感があったので
それが払拭されたと思います。
