### ISSUE TITLE
シナ共通ルールの記述

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#136]
幕末発端のIssueです。

+ init－rule要素を追加し、配下のテキストをバトルシートに表示
+ 周回ルール、戦闘のシナ共通ルールなどを明記できるようにします。

文字数に制限はありませんが、サイドパネルという性質上、ごくシンプルなルールの記載に留めることを想定しています。

**Comment by snext1220** [comment]
とりあえずは、ごくシンプルに単一のルールのみを埋め込めるように実装しました（今後ご要望次第で複数対応できるようには準備しています）。GitHub Pagesにのみ反映していますので、ご確認戴けますと幸いです。

マニュアルは以下で、 #133 とも機能を共有しています。
https://sorcerian.hateblo.jp/entry/2018/11/01/211745#text

**Comment by toki-sor1** [comment]
実装お疲れ様です！

Win8.1 Chrome 76.0.3809.132／iPhone7 Safariにて動作確認。
両環境ともにバトルシートに内容が反映されていることを確認しました。
既に把握済み（または今回は実装優先）とは思うのですが、両環境でシートの方では「％red％～％/％」とそのまま表示されていました～。

> この辺が悩ましいところですね。正直、双王でのルール説明－αくらいがギリで、それ以上はあまり適さないのかな、とは^^;

そうですね、あまりにも文字数が多いとバトルシートへの表記は適さないと思います。
システム的なガードは、そこから発生する不具合が出てこないとも限らないので、やはり作者に委ねる感じが良さそうかなとｗ

> 私もチラッと考えながら、当初外しておりました。

> 一応、rule要素にid値を付与するなどして、切り替えることは可能なのですが、執筆を考えると、rule要素に切り離すとメンテしにくいのかなと；

予想されてましたかｗ
なるほど、確かに既存シナへの影響も気になるところですし、複数の異なるルールの管理、シナリオごとのルール表記場所のばらつきなど、問題も多いですね；
シンプルな共通ルールに徹するのが良さそうです（さっそく双王でも共通ルールで利用させていただいてます！　ありがとうございます！）。

**Comment by snext1220** [comment]
ご確認有難うございます！取り急ぎで恐縮ですが、一点のみでございます～

> 両環境でシートの方では「％red％～％/%」

こちらは現時点では仕様ということで、暫しお待ちくださいませ（汗
（以下マニュアルより）

>Battle Sheetに埋め込むべきテキストには、SText固有の埋め込み式は利用できません。

**Comment by toki-sor1** [comment]
お忙しいところ、お返事ありがとうございます！

> Battle Sheetに埋め込むべきテキストには、SText固有の埋め込み式は利用できません。

ああ～、埋め込み式は「if」のことだと思っていたのですが、文字色の指定も該当していたのですね；
勘違い失礼致しました；；
もしご対応が難しい場合は、importは使わず今まで通り本文のみの表示に戻すことで対処可能です～。

> 2. scene要素にrule属性を設ける（指定時のみBattle Sheetに埋め込み）

ご検討ありがとうございます！
複数ルール対応で差し替えですか～、なるほど！
今後のことを考えると、「2」の方が様々なシナリオに対応できそうですね。

ただ、複数ルールを大量に設定すると、前コメでもあったような問題も出てくるので、そこがまた悩ましいですね；

> 前コメでは複数ルールなしとお返事してしまいましたが、早々に必要な感じに？？ｗ

importは使わず今まで通り本文のみの表示に戻すことで対処可能なので、いつでも大丈夫です～！（ご対応が難しい場合は、廃案としてくださいませ～）
＃「双王」で使用する場合は「t0は空」「t1は共通ルール」と2つのみになりそうです。

**Comment by snext1220** [comment]
早速のご確認有難うございます～

> 埋め込み式は「if」のことだと思っていたのですが、文字色の指定も該当していたのですね；
> 勘違い失礼致しました；；

いえいえ、確かに書き方が曖昧でした...失礼しました；
一応、マニュアル上は「SGML式」という言葉を使っているので、そちらに差し替えておきますね。
＃ここに限らず、STextの用語って、結構用語が無秩序になってて、悩ましかったりします；（Pgなども）色々ツール、機能も増えてきたので、用語統一しないとですね；；

> 複数ルール対応で差し替えですか～、なるほど！～～～～
> ただ、複数ルールを大量に設定すると、前コメでもあったような問題も出てくるので、そこがまた悩ましいですね；

そうなんですよね...ただ、今回、早々に要件として出てきたので恐らく必要そう＆対応そのものはそれほど難しくないので、複数対応で進めていければと～少々お待ちください！

なお、一寸お話は違うのですが、ルールテキストの記述を現在はtext要素にさせていますが、実は既存のscene要素に記述できた方が良い？と考え始めています（その方がNewPg上、他のsceneと同じように編集できる＆普通のsceneと近い位置で記述できるので良いのかも）。反面、埋め込み用のテキストであることが少しだけ判別しにくくなりますが…

基本、決めの問題ではあるのですが、どちらでも良い含め、もしご要望あればお願いします～

**Comment by toki-sor1** [comment]
> 一応、マニュアル上は「SGML式」という言葉を使っているので、そちらに差し替えておきますね。

ううっ、ありがとうございます～…！（お手数をお掛けします；；）

> ＃ここに限らず、STextの用語って、結構用語が無秩序になってて、悩ましかったりします；（Pgなども）色々ツール、機能も増えてきたので、用語統一しないとですね；；

私自身もこうして書き込む時に用語がごっちゃになってしまいがちですね；
「これからシナリオ作ろう！」という執筆者様にとっても、用語が統一されていた方が安心かなと思います～。
（初めて触れるものって、慣れた人にとっては当たり前となった部分でも、初見だと知らない用語の連続で、機能も覚えなくてはいけなくて、そこでつまずくと挫けてしまうこともあると思うので）

> そうなんですよね...ただ、今回、早々に要件として出てきたので恐らく必要そう＆対応そのものはそれほど難しくないので、複数対応で進めていければと～少々お待ちください！

承知しました！
お忙しいところ大変恐れ入りますが、よろしくお願い致します！

> なお、一寸お話は違うのですが、ルールテキストの記述を現在はtext要素にさせていますが、（以下略）

確かに、今回text要素としてルールを書き込んでいましたが、これが複数となると、シナリオの基本情報が見辛くなってしまうのでは…と気になりました。

仰る通り、scene要素にルールを書き込める場合、埋め込み用のテキストであることが少しだけ判別しにくくなるとは思います。
しかし、これは作者側が分かり易いところにルール用のsceneを配置すれば大丈夫そうかな、と思っています（私の場合は「双王」で攻略情報ページは、シナリオの最下部に配置しています）。

**Comment by snext1220** [comment]
お返事前後しますが、取り急ぎ。
詳しくはマニュアルの方も参照くださいませ～

+ text要素を廃止（scene要素でテキストをかけるように）
+ scene要素にrule属性を追加（指定idのシーンをBattle Sheetに反映）
+ id="99999"のシーンを共通ルールに
+ Battle SheetでもSGML式を利用可能に

**Comment by toki-sor1** [comment]
> これ、ありますよね^^;
●○と■■って同じもの？とか考えだすと、そちらに労力を吸い取られてしまうという；（以下略）

ありますね～；；
表記が違っていると「あれ、これって同じもの？　それとも違うもの？」→「うーん、念のために他のも調べてみよう…」となったりするのあるあるです…（そして無情にも時間だけが過ぎる…）。

> ということで、ここまでの議論を改修しGitHubに反映いたしました！
詳しくはマニュアルの方も反映しておりますので参照くださいませ～

実装お疲れ様です＆ありがとうございます！！（は、はやい…！！ｗ）
Win8.1 Chrome 77.0.3865.75／iPhone7 Safariにて動作確認し、正常に動作＆表示されているのを確認しました！

早速「双王」でも「rule 90000に今までの戦闘ルールを表記」、「rule 99999の共通ルールを空白」というように設定し、ルールを切り替えられることを確認しました～！
文字色や太字といった装飾もばっちり反映されていました！　とってもイイ感じです！！

**Comment by snext1220** [comment]
> そして無情にも時間だけが過ぎる…

仲間～ですねｗ
同じ人は結構多そうなので、改めてプレグラ、幕末に先立って、この辺、あまり行き届かなかったところでの統一／整理も図っていきたいですね！

そして、早速、共通ルールのご確認もありがとうございました（はやい！ｗ）
また、実際のシナリオで活用して戴けて、本当にありがたいです～
基本機能が整ったところで、あとは使っていく中で追加リクエストも出てくるのかなと思いますので、是非お気軽にお声がけください！

**Comment by cocotori** [comment]
確認しました。問題なく動作しています。

普段シナリオを表現するのに使っているシーンを、
戦闘ルールを記述するためのテキストとして使っているわけですね。

慣れるまで少し手間取りそうですが、
役立ちそうな機能です。

**Comment by snext1220** [comment]
ありがとうございます！
仰る通り、Sceneの使い方を拡張した機能なので、一寸戸惑うかもしれませんが、ぜひ使ってやってください～

元々幕末由来で用意した機能だったのですが、この機能でキャラ引き継ぎやレベルアップのルールを各シナ共通で記述していければと。お手数ですが、引き続きご検討よろしくお願いします…！
