### ISSUE TITLE
Playground Flowにおける入力支援改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#137]
New Pgでの入力支援の一環で、［シーン］［リンク］タブに関する、以下の施策を検討中です。
現在暫定的に実装していますので、まずはGitHub Pagesからご確認＆ご意見戴けますと幸いです。

### アイテム／フラグ／敵／実績設定（対応済）

［シーン］タブから［アイテム］［フラグ］［敵］［実績］欄にフォーカスすると、サイドバーが開いて、設定済みの情報を選択できるようになります。

### 種族／年齢／性別設定（対応済）

［基本］タブから［種族］［年齢］［性別］欄にフォーカスすると、サイドバーが開いて、規定の情報を選択できるようになります。

### ［基本］タブのBGM、及び［シーン］タブのBGM／SE（対応済）

ボタンクリックでファイル選択ボックスからファイルを選択可能に。拡張子を取り除いたものをテキストボックスに反映

### HP／MPなどのオートコンプリート（対応済）

「@...」「full」「m...n」などのテンプレートを自動補完ボックスから選択可能に。あくまでテンプレートなのでフォーマットを提示することが目的で、修正は必要

### 移動ボタンの条件式（対応済）

条件式入力の組み立てを支援するサイドパネルを用意します。［条件式］欄からのクリックでオープンします。

### scene要素のソート（対応済）

シーン挿入時にid昇順にソートの並び順をソート

### アイテム、フラグ、敵、実績のソート（対応済）

シナリオ読み込み時にid昇順にそれぞれの項目をソート

### スタイルシートの調整（対応済）

［シーン］タブの溢れを改善

### 作成したシナリオの投稿（対応済）

PgFlowで作成したシナリオを画面上から直接にアップロードする機能（環境の問題でGitHub Pagesは不可。本番環境のみ動作）。まずは、ダイアログのイメージのみご確認戴けますと幸いです。

### 投稿時のメール送信（対応済）

Flowからの投稿では、サーバーにデータを保存した後、投稿者あてにAckメールが送信されます（以下内容）。

---

ソーサリアン Textにシナリオを投稿戴き、ありがとうございました。

現在、スタッフ側で掲載処理を進めておりますので、
掲載までしばらくお待ちください。
＃紹介文、難易度などについては、スタッフ判断で調整／リライト
　させて戴く場合もありますので、ご了承ください。

なお、掲載まで別のシナリオを投稿することはできません。
修正がある場合は、同じシナリオに限り、再度投稿が可能です。

今後とも、ソーサリアン Textをどうぞよろしくお願いいたします。

ソーサリアンTextスタッフ一同

---

このメールはFrom／Bccにサルバさんアドレスを設定させて戴く予定です。
お手数ですが、このメールをトリガーに、Uploadデータの移動＆stext.xmlの編集、掲載後、投稿者へのお返事をお願いできますでしょうか。
＃ データの保存先フォルダーは、別途お知らせいたします。

@Salvadors-cabin さん＞ お手数ですが、メールへのアドレスの掲載問題ないか、ご確認戴けますと幸いです（難しい場合はFromはリオのものと致します）。

### Editor⇔Flow間のデータ交換（対応済）

ボタン一つで互いに作業環境を切り替え可能に。
本対応に伴い、単発にて大変×2お手数ですが、アイコン画像をお願いできますでしょうか（汗）＞ @toki-sor1 さん
  + Flow上のアイコン
     + Editorで編集（［F→E］？）：pg_f2e.png
  + Editor上のアイコン
     + Flowで編集（［E→F］？）：pg_e2f.png

**ご相談：Editor側にチャート表示機能を残していますが、実はFlow2Editorがあれば不要？**

### フロチャの描画アルゴリズム改善（対応済）

よりフローが明確になるよう、階層式の描画ルールを取り入れてみました。

### フロチャの座標削除（対応済）

取り急ぎですが、ご要望を受けて、データ保存時に.xml、,jsonファイルからx、y座標を除去してみました。使い勝手など、引き続きご要望戴けますと幸いです。

### マニュアルへの反映（対応済）

以上の修正に伴う解説の修正、用語統一をサイト／Flowマニュアルにも反映済みです。
サイトではPostページは全体を細かく修正していますので、ご確認戴けますと幸いです。

#### フロチャの位置固定

フロチャの位置を固定するなどのご提案を戴いていましたが、シーンの絞り込みを行うと逆に疎らに見難くなってしまうおそれがあり、悩ましく思っています。シーン数が多くなってきた時に、表示シーンの絞り込みを行いながら作業することで賄えないか、この辺ご意見頂戴できますと幸いです。

#### 左上のロゴ＆投稿ボタン（ @toki-sor1 さん ）

+ Playgroundの正式名称が決まりましたら、お手数ですが、タイトル部分もPlayground Flowで修正お願いできますと幸いですm(_ _)m
+ 投稿ボタンを現在はただのボタンとしていますが、他同様、ボタンイメージをお願いしても宜しいでしょうか（ポストや封筒など？）

**Comment by toki-sor1** [comment]
> Playgroundの正式名称が決まりましたら、お手数ですが、タイトル部分もPlayground Flowで修正お願いできますと幸いですm(_ _)m

DM拝見しました！　反映ありがとうございました！

> 投稿ボタンを現在はただのボタンとしていますが、他同様、ボタンイメージをお願いしても宜しいでしょうか（ポストや封筒など？）

他のアイコンと同じサイズで作成致しましたが、如何でしょうか？
（アイコンのファイル名をお聞きするのを失念していたため、仮にpg_post.pngと付けてO/Dにアップしています；　ご使用の際にファイル名の変更が必要な場合は、お手数をお掛けして申し訳ありませんが、変更よろしくお願い致します；）
![pg_post](https://user-images.githubusercontent.com/42646342/65391995-cae9a780-ddaa-11e9-9da8-c7c497155bf7.png)
https://onedrive.live.com/?id=4837C202555BE782%216765&cid=4837C202555BE782

***
> フロチャの位置固定

ちょっと話が逸れてしまっていたら、申し訳ありません；
人によってフロチャに求めるものは違うのかもですが、個人的にフロチャは「シナリオ全体の流れを見るもの」という印象です。
そうなると「表示シーンの絞り込みでフロチャの部分部分を確認しながらの作業」というのは、やや感覚が異なるのかな、という感じがします。

位置が固定できた方が見易いとは思うのですが、もし「scene同士が重ならない仕様（リンクの重なりは有り）」が可能であれば、Scene数が多くなってきても、位置固定されなくても、だいぶ見易くなるのでは、と思いました。

ただ、それがそもそも可能かどうか、難易度的に見てどうなのか等、その辺りがまったく分からない状態で意見を書いています；
実装が厳しい・実現できない・リスクを伴うなど問題がありましたら、スルーしてくださいませ；（この場合、無理なく現状維持で進めていただければと～）

**Comment by Salvadors-cabin** [comment]
>このメールはFrom／Bccにサルバさんアドレスを設定させて戴く予定です。

問題ありません。

>フロチャの位置を固定するなどのご提案を戴いていましたが、シーンの絞り込みを行うと逆に疎らに見難くなってしまうおそれがあり、悩ましく思っています。シーン数が多くなってきた時に、表示シーンの絞り込みを行いながら作業することで賄えないか、この辺ご意見頂戴できますと幸いです。

シーンが多くなってきたら表示を絞り込んで作業するのは必須と思います。
ただ、絞り込んだとしても今のままだとフローの整理作業から開始となります。
多少見難くても前回出力時のままインポートできれば整理作業も少なくて済むような気がします。
むしろXY座標をxmlに記録しない方がいいかもしれません。
XY座標がないxmlをインポートすると、それなりに並べてくれるので整理もしやすかったです。（「新・囚われた～」ではそうやっていました）

**Comment by toki-sor1** [comment]
**Flow上のアイコン、Editor上のアイコン**
![image](https://user-images.githubusercontent.com/42646342/65623682-4e053a80-e003-11e9-81ec-4783c1baed3f.png)

DMで先にお知らせ済みですが、アイコンを作成致しました。
2つともGitHubにアップ済みです（旧、と付いていない方をアップしています。急なアイコン差替え、どうもすみません；；）。

**Comment by snext1220** [comment]
@toki-sor1 さん、 @Salvadors-cabin さん ：
フロチャの表示についてご意見戴きありがとうございました。

> そうなると「表示シーンの絞り込みでフロチャの部分部分を確認しながらの作業」というのは、やや感覚が異なるのかな、という感じがします。

上記、まさにPgの使い方によって求めるものは変化しそうですね^^;
Editorベースで作成したストーリーの全体を最終確認する用途であれば、まさにときのじさん仰る通りですし、Flowベースで編集しようとすれば絞り込みは必須というサルバさんのご意見なのかと。

ということで、それぞれの用途を満たすように何とか調整していければと思っておりますが…以下、個々へのお返事です。

> もし「scene同士が重ならない仕様（リンクの重なりは有り）」が可能であれば、Scene数が多くなってきても、位置固定されなくても、だいぶ見易くなるのでは、と思いました。

こちらですが、これまで利用していた描画アルゴリズムを入れ替えて、調整してみました。重なりを完全には除去できないものの、ほとんどのシナリオで相応の見た目になったように思えるのですが、如何なものでしょうか（Slayerなど例外あり^^;）。

> むしろXY座標をxmlに記録しない方がいいかもしれません。

編集（絞りこみ）時の見易さについては、まずは簡単に対応できそうな、こちらのご意見にて対応してみました。 .json、.xmlファイルへの保存時にx、y属性を除去しています。

上記、それぞれGitHub／本番環境に反映しておりますので、他と合わせてご確認戴けますと幸いです～ご意見戴きながら、引き続き設定調整していければと…！

**Comment by cocotori** [comment]
こちらの改善案、追っていなくてすみません！

今ようやく触り始めましたが劇的に進化していますね！
アイテム欄で候補が出てくるのはとても使いやすいと思います。

ただ、アイテム欄やフラグ欄、サマリー欄などを
ダブルクリックすると、なぜかマニュアルのページが開いてしまいました。
（以前からそうだったかは覚えていないです。）

フロー図の並びも、以前に比べるとだいぶわかりやすくなった気がします。
ただ、文字の重なりはいぜん気になりますね。

全体の拡大縮小はわりと簡単に行えるので、
もう少しシーンブロックの間隔を広げるとか、
文字サイズを小さくするとかはできないでしょうか？
（任意に選択できるとなお良い？）

**Comment by snext1220** [comment]
@cocotori さん、ご確認有難うございます！

> ダブルクリックすると、なぜかマニュアルのページが開いてしまいました。

こちらはダイナミックヘルプの機能で、以前からでした^^;
サイドパネルを開くには、テキストボックスのシングルクリックでお願いできますとm(_ _)m

> ただ、文字の重なりはいぜん気になりますね。

そうですね...リンク文字列は長いものが多いので、フロチャに埋め込むとどうしてもそこは重なってしまいますね；
実は、シーンブロックは間隔を広げると、拡大した時に疎らになって見難かったので、既定から狭めていました。ご指摘受けて、文字サイズを14→8ptに、シーン間隔も80→100と調整してみました（文字サイズは変化が判るように大きく変えましたが10pt程度が適当かも）。GitHubからのみ確認できますので、ご覧ください～

**Comment by toki-sor1** [comment]
@snext1220 さん＞
> Editorベースで作成したストーリーの全体を最終確認する用途であれば、まさにときのじさん仰る通りですし、Flowベースで編集しようとすれば絞り込みは必須というサルバさんのご意見なのかと。

おおお、分かり易くまとめていただき、ありがとうございます！
私とサルバさんの意見は逆だな～と思っていたのですが、リオさんにまとめていただいて「なるほど！」としっくりきました。確かにこれは逆な訳ですねｗ

> こちらですが、これまで利用していた描画アルゴリズムを入れ替えて、調整してみました。

異なる意見だったのですが、その両方を満たす調整を…！　本当にお疲れ様です＆ありがとうございます！！
早速PCにてGitHubと本番環境でテストしてきましたが、良かった点と気になった点（不具合？）は、以下のとおりです。

### 良かった点
- シナリオによって差異はありますが、Sceneの重なりが軽減され、フローチャトとしてとても見易くなりました！
  - 特に短編シナリオでは、効果抜群でしたね！

### 気になった点
- シナリオ（リンクの設定）によって、Sceneを左右に移動できても、上下に移動できないことがある（操作がやや窮屈な印象）。
  - 特に「Trial」では、フローチャートが真一文字に表示されるのですが、Sceneを上下に移動できず、逆に見辛い感じになっていました；

### 不具合？
- 表示するSceneの絞り込みを行うと、その範囲内でフローチャートに表示されないSceneがある（shadowテスト時／Scene0～20まで、など）

***
> ご指摘受けて、文字サイズを14→8ptに、シーン間隔も80→100と調整してみました（文字サイズは変化が判るように大きく変えましたが10pt程度が適当かも）。

す、すみません、何度もブラウザを再読み込みしたり、キャッシュを削除したりしているのですが、本番環境とGitHubで違いが無いように見えました；
私の目が節穴eyeなのか、もしくは反映に時間が掛かっているということなのでしょうか…時間をおいてからまた試してみますね。

**Comment by snext1220** [comment]
早速のご確認有難うございます！

> 異なる意見だったのですが、その両方を満たす調整を…！

頑張ってみました^^;
まだまだ課題は多いようですが、それでも少しずつ改善はしているようで、ホッとｗ
完全な最適解もないとは思うのですが、なんとか落としどころを見つけていければと思いますので、引き続きよろしくお願いいたします～

＃ 意見が割れるところは、設定変更できる仕組みも作っていければと思いますが、そちらはも少し意見が収束してきたところで^^;

> 「Trial」では、フローチャートが真一文字に表示

互いのリンクが激しく絡み合っているシナで起こる現象のようですね；
元に戻しても今度はコスモ世界になってしまったのでｗ、階層式を維持しながら、少しだけ並びのルールを維持してみました。
横にしか動かせないという制限は変わらないのですが、Trial／Slayerなどでは改善したかなと；（逆に、若干見難くなったシナもある気がしますが、バランス的にはギリか；）

> その範囲内でフローチャートに表示されないSceneがある

失礼しました！
こちらは恐らくリリース時からの不具合ですね...先ほど修正いたしました～

> GitHubを開いたら、新設定が反映されていました！

こちらでも諸々弄っていたので、あるいは途中の状態がUpされてたかもしれません；ご確認有難うございました（汗
同時に反映しようとすると相性が～が、まさにですね；試験的に以下の対策を打ってみました。

+ リンク文字のサイズを12に変更
+ 完全に非表示にすることはライブラリの制約で難しい＆概観する際に不便かなと思われたので、まずは標準の透明度を0.3に
+ 選択時に赤字ボールドで表示されるように

ん～場所によっては多少改善された気もしますが、リンクが重複している箇所の見難さは改善しにくい（選択中のシーンも同じなので）ですね...あとは、潔くフロチャ上のリンク文字列を完全に非表示にしてしまうという選択肢はありますが；；

**※当面の調整はGitHub Pagesのみ反映しております。ある程度まとまったところで本番環境には反映してまいりますので、当面は調整前後の比較という意味で両方の環境を比べて戴けますと^^;**

**Comment by cocotori** [comment]
・リンク矢印のハイライトについて

赤字ハイライトでだいぶ見やすくなったかと思います。
ただ、せっかくのハイライトが下に行ってしまうことがありますね。

ハイライトしたときだけ、文字が最前面に来るようにはできないでしょうか？
難しそうなら大丈夫です。


・ノードの移動制限について

ノードを自由配置しないことによって、フロー図がだいぶ見やすくなったと思います。
特に、エンディングが下で、時系列的になっていくのがよいですね。

ただ、ユーザーは横にしか動かせなくなってしまったことで、
文字の重なった部分を広げて確認したいときに煩わしさがあるなと思いました。
特に横にノードが並んでしまったとき。

考えたのですが、ユーザーがノードを動かせるのは
あくまで文字の確認目的に留めるという意味で、
自由に動かせるようにしてはどうでしょうか？

自由なフロー図を作れてしまいますが、それは一時的なものだよ、
という意味を込めてどこかに「ノード再整理ボタン」を配置して。

新しいノードを追加したら、強制的に再整理してしまうのも
今のままでいいと思います。

現状の配置アルゴリズム上、そういう事ができないようであれば
大丈夫です。


------


ここからは今後の話になるかと思います。
今回のバージョンアップで、劇的にシナリオが作りやすくなったと思います。
当初の目的である、

・プログラム的な知識を必要とせず、GUI中心のツールのみでシナリオ作成を完結できること。
　それにより、企画参加の敷居を下げる。

という方向性ともあっていると思います。
ちなみに目的は、この理解で大丈夫でしょうか・・・？
認識にズレがあってはいけませんので・・・

ただ、ドラゴンスレイヤーのような長編を作るには
どうしてもリンク線がぐちゃぐちゃになってしまって、
いまだ課題があるように思います。

感覚的な話ですが、現在の仕組みでは100シーンくらいが限界かなと思っています。

それ以上の規模のシナリオを作るには、
階層化が必要ではないかと思います。

現在はscenario.xmlにすべてのシーンを記述していますが、
scenario1.xml,scenario2.xml,...
のようにして、シーン数をなにかの区分けごとに分けるのはどうでしょうか。

例えば英雄を語りてでは、「ポーラスと会うまで」「グリメルムに会うまで」「グリメルム戦」
というふうに分けるとか。

大きな区分けの間をリンク線がたくさん出るということはあまりなく、
区分けの中で完結することが多いと思うのでスッキリするのではないでしょうか。
もちろん、自由度を高めるためにも別のファイルの任意のノードに移動できるようにはして。

アイデアレベルですが、ご一考くだされば。

![無題25](https://user-images.githubusercontent.com/42885160/65811777-af422f00-e1f8-11e9-962e-0333b0a3979a.png)

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！
諸々のご意見、いちいちごもっともと思いながら拝見しております。

> ・リンク矢印のハイライトについて
> ハイライトしたときだけ、文字が最前面に来るようにはできないでしょうか？

そうなんですよね…すごく同感です；
こちらは現時点ではライブラリの制約で前面移動ができずにおります。。
ご意見は本当に仰る通りだと思うので、継続調査とさせてくださいませ。

> ・ノードの移動制限について
> 自由に動かせるようにしてはどうでしょうか？

こちらもまさに仰る通りだと思うのですが、階層式チャートが「レベル」という概念を持つため、階層式を維持したままだと現状厳しそうです。。（レベルを跨いだ移動が階層の中ではできない）
従来のランダムチャートに戻せばもちろんいけるのですが、前のものがあまりに見難かったので、果たして、切り替え機能含めて設ける意味があるのか、という疑問があり、そのままになっていました^^; 

専らライブラリ（もしくは私の理解）の制約で、現時点では否定的な回答になってしまい、スミマセン；ただ、ご意見は強く同意なので、引き続き検討していければと…！

> あくまで文字の確認目的に留めるという意味で、～

ちなみに、上記の意味では、シーン文字列は［シーン］タブのシーン選択ボックスから確認する、という使い方では難しいでしょうか。一望するには、そちらの方が見やすい＆選択する際には結局こちらを使う機会が多いのかな、とも^^;

> ちなみに目的は、この理解で大丈夫でしょうか・・・？

おまとめ戴き、ありがとうございます！
まさに仰る通りです！！

> ただ、ドラゴンスレイヤーのような長編を作るには～～
> 感覚的な話ですが、現在の仕組みでは100シーンくらいが限界かなと思っています。

まさに、これも仰る通りだと思います。
本件については、実はこちらでも新機能を検討しておりまして。
私の方では、 **グループ** という概念を新設することを考えていました。

`<group start="0" end="100" title="洞窟の入り口" />`

たとえばこれで0～100Sceneをひとつのグループとして束ねるイメージです（Flow上ではスプレッドで編集できるようにする予定）。グループはフィルター時に利用できるようにします。
＃ Flow、そもそも大きなシナでは「絞り込みながら作業していく」が基本思想だったので、その絞り込みをより簡単化していくイメージです。

というのも...

> 大きな区分けの間をリンク線がたくさん出るということはあまりなく、
> 区分けの中で完結することが多いと思うのでスッキリするのではないでしょうか。

実は、大きなシナでもそうした構造のものは比較的フローもスッキリしていたりしてまして^^;（hero、scepterなど）
一方、slayerは勿論なのですが、trial、goldなど比較的小粒のものでも、全体にわたって相互リンクしているシナはフローも崩れてしまい、そうしたシナは分割も難しいのでは、と思った次第です。
＃ 加えて、分割すると0がない場合の処理をはじめ、結構影響が大きかったり^^;

如何なものでしょうか。
それでは意図が違う！などあれば、引き続きご意見戴けますと幸いでございますm(_ _)m

**Comment by cocotori** [comment]
>追記：以前のときのじさんのご意見を受けて、疑似的にリンク矢印のラベルを通常非表示＋ホバー選択時のみ表示するようにしてみました。ざくっとみたい時には以前のように見えていた方が良いのかも、とも思いましたが、ご意見戴けますと幸いです

ああ、いいですね！きちんと文字が見えるようになったと思います。
全体表示がいいか、文字が全部見えるほうがいいか、
これは好みでしょうね・・・
選択ができるといいのでしょうが。
わたしはこの新しい、ホバー選択時表示がいいなと思いました。

「編集するリンクの選択」も使いやすくていいと思います。
グラフィカルなマップもいいですが、
こういう、リスト化されて順番に並んでくれるものもあると
とても便利だと思うんですよね。
右上の、「編集するシーンを選択」と合わせて、役に立っています。


・グループ
いいと思います！
分割と絞り込み、それぞれにメリット・デメリットあると思いますが、
一度にアクセスする情報を減らせるという点で
役に立つと思います。

**Comment by snext1220** [comment]
早速のご確認有難うございます～
大筋改善したとのこと、良かったです！

> 全体表示がいいか、文字が全部見えるほうがいいか、
> これは好みでしょうね・・・

ですよね^^;
意見が割れる＆使い勝手に大きく影響する箇所では、将来的に設定変更できる仕組みも作っていければと思いますが、まずは暫くホバー選択表示で様子を見ていきますね！
＃引き続きご意見お願いします！＞皆さん

>「編集するリンクの選択」も使いやすくていいと思います。
> 右上の、「編集するシーンを選択」と合わせて、役に立っています。

良かったです！
下のグループができたら、シーン選択の方も階層表示できたら良いなぁなどと考えています。

> ・グループ
> 一度にアクセスする情報を減らせるという点で役に立つと思います。

ありがとうございます！
こちらは本格実装はDec Update以降になるかと思いますが、進めていきたいと思います～
#139 としてIssueを立て、僅かではありますが現時点での懸案事項もまとめておりますので、またご意見など戴ければ幸いですm(_ _)m

余談：
なんの柵もなければ、複数ファイル分割は魅力的ですね～
ヘッダーファイル（アイテム／フラグ等の設定情報）＆シナリオ複数で細分化できれば、エディターでの編集もぐんと楽になるのかなと。それこそSText 2.0の課題ですが^^;

**Comment by toki-sor1** [comment]
お返事が遅くなり、申し訳ありません…！

> ＃ 意見が割れるところは、設定変更できる仕組みも作っていければと思いますが、そちらはも少し意見が収束してきたところで^^;

了解です！　引き続きよろしくお願い致します！

> 横にしか動かせないという制限は変わらないのですが、Trial／Slayerなどでは見た目は若干改善したかなと；（逆に、若干見難くなったシナもある気がしますが、バランス的にはギリか；）

ご対応ありがとうございました！　表示が改善されているのを確認しました！
シーン同士の繋げ方によってフローチャートの見え方もだいぶ左右されますもんね；
現状のバランスが丁度良いと思います～。

> その範囲内でフローチャートに表示されないSceneがある

修正ありがとうございました！　正常に表示されています！

> フローチャートの改善（返信内容を一部割愛させていただきつつ）

ご対応ありがとうございました！
ココさんのご意見を得て、表示が更に洗練されて見易くなりましたね！
リンク文字の非表示、ホバー選択表示等、とっても良いと思います！

> グループ化機能

こちら、良いですね！
長いシナリオになればなるほど、グループ表示は有効に作用すると思います～。

ただ、このグループ化機能は、PgFlowでシナリオの流れを確認する上ではとても有効なものの、編集という点においては、やはり複数ファイル分割は魅力的ですね～。
（長編や文字数が多いシナリオの場合、検索機能も活用しているものの、scenario.xmlの上下スクロールが地味に作業に響いてくるので；）
デメリットとしては、複数ファイルにまたがる修正が出た際に、修正がやや面倒というところでしょうか。

**Comment by snext1220** [comment]
こちらも問題なしとの事、ありがとうございます！

ファイル分割については、IDEがきちんと機能していれば大いに有効なので、SText 2.0で是非実現したいですね...；たぶん1年がかりの作り直しになると思うので、シナリオなどが止まってしまうことを考えると、どこで取り組むのかだけが悩みの種です^^;
