### ISSUE TITLE
SText用語の統一／整理

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#138]
ソーサリアン Textに関わる用語が、次第と入り乱れてきたので、こちら整理&統一していければと思います。これはこの名前の方が、これも不明瞭、などあれば、ご指摘願います。
＃正確にはenhancementではないのですが、マニュアル／サイトへの反映もあるため、そのように分類しています。

以下、曖昧と思われる用語です。

+ SGML：scenario.xmlのフォーマット＆データそのものを指す用語。定着しているかは微妙なのですが、わかりにくいという意見がなければそのままで。
+ SGML式：scene要素で利用できるmarkdownの拡張構文。良い表現あれば？
+ Playground Flow：New Playgroundと呼ばれていたもの。いつまでもNew～はおかしいので。
+ Playground Text：旧Playground。Flowと区別する意味で。ただ、STextのTextとも重なるので、Playground Editor等の方が判りやすい？
+ メイクリアン：開発環境を指していましたが、Playgroundが一般的になってあまり使う機会もなくなりそう？

折角なので、他にも何か曖昧になっている用語があればお願いします！

**Comment by toki-sor1** [comment]
Issue立てありがとうございます～。

> SGML

STextを説明する上で必要な用語なので、そのままで良いと思います。
プログラム等の「言語」に馴染みのない私にとっては、「そういうものである」という認識なのですが、逆に、知識がある方にとっては、とてもシックリくる用語なのではないでしょうか。

> SGML式（式埋め込み）

「SGML」自体が独自の用語なので、「SGML式」と書かれているのを見て、ぱっと内容が理解し易いかというと、そうでもないかなと思います。

ただ、説明時には大体SGML式ではなく、個別に「条件分岐」「テキストのカラーリング」と表記しているので、総称である「SGML式」は必要だと思います（総称があると、機能の説明をまとめ易い）。

> Playground Flow

悩んだのですが、変更するならプレグラ100祭の宣伝時の方が、名称の切り替え時期としても丁度良いのでは、と思っています（こちらの担当では、バナーとwiki要修正）。

> Playground Text

フローチャート重視のプレグラが「Flow」であれば、テキストエディター重視のプレグラは「Editor」の方が解り易いような気がします。

> メイクリアン

確かに現在ではプレグラが一般的になっている印象なので、メイクリアンはひっそりとしている感じもしますね；

***
> 折角なので、他にも何か曖昧になっている用語があればお願いします！

こちら、私が勝手に呼んでしまっているものなのですが（汗）、正式名称はありますか？

- 戦闘時のダメージ、ドロップアイテムを表すボタンの名称（私：戦闘式ボタン）
- ステータスダイアログのMAGIC（私：魔法一覧）

また、以下もやや表記ブレがあるので、STextではどちらの方が適しているのか、使い分ける際によく迷ったりします；
（どちらでも良いのかなとは思っているのですが、告知などでも表記することがあるので）

- シーン数 or パラグラフ数

**Comment by snext1220** [comment]
諸々のご見解＆ご賛同ありがとうございます！
Pg Editorについても、ご意見ご尤もだと思いますので、そちらで進めていければと！
SGML式だけが若干悩ましいですが、使っていけば慣れていくのかな、という感じもするので、まずはママでいきましょうか（マニュアルには、もう少し広い意味での「SGML拡張」というキーワードがありますが、やや曖昧かも^^;）

＃勿論決定ではありませんので、それぞれ別案ある方いらっしゃいましたらお願いします～＞皆さま

> メイクリアンはひっそりとしている感じもしますね；

元々Next0401ネタからの掘り返しでしたが、一般的な用語からすると、Playgroundがイメージしやすいこともあり、無理することはなさそうですね^^;
将来的に、Playground Flow／Editorが統合?される時に、また命名の問題が出てきそうですが、その時の候補のひとつになるのかも、しれません？（シンプルにPlayground Unitedなどになりそうな気もしますが^^;）

> 戦闘時のダメージ、ドロップアイテムを表すボタンの名称（私：戦闘式ボタン）

私のシナでは［ダメージ式］ボタンとしていました。
ドロップ～の方はあまりマイシナ上では登場せず、マニュアルでは、辛うじてドロップアイテムボタンとしていますね^^;

ただ、より大きな括りとして、Battle Sheetという用語ができたので、今後は「Battle Sheetからダメージ／ドロップアイテムを反映させよ」のような表記になるのかな、とも^^;
＃細かな命名は恐らく統一させづらいので、わかりにくくない範囲で、より大きな枠組みでの表現（ここではBattle Sheet）に留めるのが吉かなと感じました～

> ステータスダイアログのMAGIC（私：魔法一覧）

こちらは、魔法条件の移動ボタンで自動減算されることから、こちらでは、シナリオ内で言及する機会がなくなってしまっておりました^^;
ただ、使うとしたら、「ステータスダイアログから魔法を行使せよ」のような感じで。上の「大きな枠組み」前提の表現になっていくのかな～と？

＃てか、そもそも「ダイアログ」でなくなってしまったので、統一感を持たせるならば、「Status Sheet」なのか、という話も^^;（あまり拘ってもですが；）
更に細かい点だと、Battle Sheetなのかバトルシートなのか、という話もありそうですね^^;

> シーン数 or パラグラフ数

こちらはSTextとしてはシーン数かなと思っています～
ただ、ゲームブック層にはパラグラフ数の方が通りが良いこともあり、広く告知する際にはあえて「パラグラフ」と明記しておりました。
統一できた方が良いのですが、SGML的にはパラグラフにするのも混乱しそうなので、「マニュアルなどの内部文書ではシーン、告知にはパラ」の使い分けになっていくのかなと（結局、ダブルスタンダードに^^;）

**Comment by cocotori** [comment]
使用頻度の低い固有名詞は可能な限り
見えなくしたい、というのがわたしの思いです。

・SGML
・SGML式

表現としては問題ありませんが、これはほとんど見えなくしないですね・・・
おそらく、playground flowを使っているうちは
ソースコードを一切意識しなくて済むはずですので、
可能な限り隠蔽したいです。

タグ等の説明には、テキスト内の独自構文、
などの表現ではいかがでしょうか。


・Playground Flow：New Playgroundと呼ばれていたもの。いつまでもNew～はおかしいので。
・Playground Text：旧Playground。Flowと区別する意味で。ただ、STextのTextとも重なるので、Playground Editor等の方が判りやすい？

Playground Flow、Playground Editor、
略称PgFlow、PgEditor、いいと思います。


・メイクリアン：開発環境を指していましたが、Playgroundが一般的になってあまり使う機会もなくなりそう？

そうですね、こちらもマニュアル類から
徐々に消していければと思っています。

**Comment by snext1220** [comment]
> 使用頻度の低い固有名詞は可能な限り見えなくしたい、というのがわたしの思いです。

賛成です！
できるだけ初見の方にハードル低く、という大方針とも合致していると思います。
SGML（式）についても、不要な処では言い換えを、でよいと思います。

タグとしての説明をしている「開発リファレンス」では残すとして、他のドキュメントでは可能な範囲で利用しない、という方針ですよね（認識これでOK？）。仰る通り、Flowベースの説明ではそもそもSGMLをほぼ意識する必要はないかと思いますし、ときのじさんが仰っていた「総称があると、機能の説明をまとめ易い」とも矛盾しないかと…！

> ・SGML式

ここだけがFlowを使っていても出てきますが、仰る通り、「独自の埋め込み構文」で十分に通じそうですね（曖昧になりそうな文脈があれば要相談）。

**Comment by toki-sor1** [comment]
### SGML、SGML式
> タグ等の説明には、テキスト内の独自構文、などの表現ではいかがでしょうか。

> SGML（式）についても、不要な処では言い換えを、でよいと思います。

賛成です！
なくしてしまうと困るものの、あると用語に馴染みが薄い or ご新規さんが戸惑ってしまうものなので、お二人がご提案されている形で表記するのがベストだと思います～。

### メイクリアン
メイクリアンも0401の思い出の一つなので、消すのはちょっと寂しい気持ちもありますが、現状では仰る通り「Playground」の方がイメージし易いのは確かですね。
情報の整理ということで、メイクリアンという表記は、思い出としてマニュアル以外の場所に残す以外は、消す方向が良さそうな感じがします。

> 将来的に、Playground Flow／Editorが統合?される時に、また命名の問題が出てきそうですが、その時の候補のひとつになるのかも、しれません？（シンプルにPlayground Unitedなどになりそうな気もしますが^^;）

候補としては有りかなと思いますが、やはりPlaygrandが広まりつつあるので、Playground Unitedのように「Playground ○○」となりそうな…？
＃単純に、（当然ではあるのですが）メイクリアンとソーサリアンで響きや見た目が似通っていること、更に、ぱっと見て何だか分かり辛いということもありますが；

***
こちらから質問しておきながら、お返事が遅くなり、申し訳ありません…；
とても丁寧にご回答いただき、本当にありがとうございました！

> ［ダメージ式］ボタン、ドロップアイテムボタン

こちら、可能なものから表記を改めていきたいなと思っています～（まずは双王からですね）。

> ＃細かな命名は恐らく統一させづらいので、わかりにくくない範囲で、より大きな枠組みでの表現（ここではBattle Sheet）に留めるのが吉かなと感じました～

そうですね～、Battle Sheetという用語ができたことで、表記がぶれにくく、戦闘関連の表記について認識を一致させやすくなったと思います。
戦闘のルールによっては、［ダメージ式］ボタンのように個々に表記した方が良いケースもありますが、そういった特別な事情がなければ、Battle Sheetと括って表記すると良さそうですね。

> ステータスダイアログのMAGIC（私：魔法一覧）
> ステータスダイアログから魔法を行使せよ

なるほど、確かに現在では自動減算が主流（？）で、MAGICについて言及する機会がなくなっていましたね；
そうなると、魔法一覧にない魔法を使用する際の指示としてMAGICを表記する際には、そのまま「魔法一覧」として表記し、そのケース以外では、ご提案いただいた例文を参考にして表記したいと思います～。

> Status SheetとBattle Sheet

確かに現在ではステータス「ダイアログ」ではなくなっていますね…；（横がはみ出て違和感があるので、いずれゲーム画面に収まるようにできたらいいですよね…）
Battle Sheetに合わせるのであれば、「Status Sheet」が有力候補かなと…！

また、Battle Sheetは、このままの表記がいいですよね。
英語表記だとなんか格好良いですし！ｗ

>こちらはSTextとしてはシーン数かなと思っています～

> 「マニュアルなどの内部文書ではシーン、告知にはパラ」の使い分けになっていくのかなと（結局、ダブルスタンダードに^^;）

今まで認識がごっちゃだったので、自分が表記する際にはブレていたのですが、ご回答を拝見して、場面に応じて使い分けている、ということをはっきりと認識することができました！
使い分けの基準もなるほど納得です！　今後、使い分けていこうと思います～。

**Comment by snext1220** [comment]
> メイクリアンとソーサリアンで響きや見た目が似通っていること、更に、ぱっと見て何だか分かり辛いということもありますが；

確かに、これは大きいですね；
メイクリアンはあくまで0401ネタでの命名と割り切った方が良さそうです^^;

その他命名についても、ご了承有難うございます！
おそらく完全に適用できない文脈もありそうですが、一応の基準として進めてまいりましょう～マニュアル／サイト等についても、この後、諸々修正が入るタイミングで徐々に反映していければと思っています。

> 確かに現在ではステータス「ダイアログ」ではなくなっていますね…；（横がはみ出て違和感があるので、いずれゲーム画面に収まるようにできたらいいですよね…）

本当に。
いわゆるTemporary（暫定）案件としては唯一残ってしまったのですが、中心ダイアログなので、2周年前後で是非とも整理していきたいです。
＃ そろそろ幕末にも軸足を移していかねばなので、2周年終えてからになるか、ふと思いつきで一気にやってしまうかは、まだよくわかりませんｗ

こちらデザイン面でもご相談させていただくことになりそうですが、お手数ながら、引き続きどうぞよろしくお願いいたします！
