### ISSUE TITLE
シーンのグループ化機能（PgFlow）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#139]
#137 を受けてのIssue です。

シナリオを意味ある単位で分割できるよう、 **グループ** 機能を新設します。

```
<group start="0" end="100" title="洞窟の入り口" />
```

たとえばこれで0～100Sceneをひとつのグループとして束ねるイメージです（Flow上ではスプレッドで編集できるようにする予定）。
グループはフィルター時に利用できるようにします（複数グループも選択可）。

＃Flow、そもそも大きなシナでは「目的の単位で絞り込みながら作業していく」が基本思想だったので、その絞り込みをより簡単化していくイメージです。

**追記：こちら対応が完了しておりますので、Nov Updateに繰り上げています。従来の［フィルター］ボタンから確認できるのでご確認ください（GitHubのみ）。
伴い、従来のシーン番号による絞り込み機能は除去しています。基本なんでもできる、よりも、グループ定義と絞り込みはセットとした方が、慣れてくればすっきり使いやすいだろう、という趣旨ですが、ご意見戴けますと幸いです（細かく表示を変えたい場合にはあった方が良いかもしれませんが、適切なグループ化がされていれば、あとは慣れの問題かと割り切っています）**

#### テスト時の注意

既存の.jsonファイルをインポートすると、失敗します。
.xmlからインポートしてください（最新のデータが.jsonの場合はご相談ください）。

#### 開発メモ（備忘録）

+ ~スプレッドシート~
+ ~xml出力~
+ ~xmlインポート~
+ ~サイドメニューの作成~
+ ~フィルター機能の実装~
+ ~group要素のマニュアル~
+ ~NewFlowマニュアル~

**Comment by cocotori** [comment]
確認しました。問題なさそうです。

フィルターのメニューなのですが、
グループ名だけなくシーン数まで表示されたらわかりやすいかと思いましたが、
ごちゃごちゃするので好みの問題かもしれませんね。
スペースの関係上難しいかも・・・

**Comment by cocotori** [comment]
あっ　後、フィルター解除のボタンはあったほうがいいかもしれません。
今はall sceneのグループで代用していますが。

**Comment by snext1220** [comment]
早速のご確認有難うございます！

シーン数＞ここ悩ましいですよね。私もごちゃごちゃが気になって外していました^^; とりあえず改行付きで入れれば比較的スッキリかなとUpdateしてみましたが、如何でしょう？？

フィルター解除＞実は無選択で再表示すると解除だったのですが、激しくわかりにくかったので、解除ボタンを入れてみました。他のサイドバーとの共通化の関係で他のボタンとの共通になっていますが、ご容赦を...；

いずれもGitHub Pagesのみ反映済みです～

**Comment by toki-sor1** [comment]
Win 8.1 Chrome 77.0.3865.90(64bit)から動作確認。
正常に動作するのを確認しました。

シーン数が多くなってくると、シーン数だけ見てもどのシーンなのか分かり辛く、指定もし辛いですもんね。
現在のように、自分でグループ化した範囲でシーンを確認出来て、尚且つシーン数も表示されるのは、とても親切で分かり易いと思います！
フィルター解除ボタンも分かり易くて良いと思います！
