### ISSUE TITLE
隠しフラグの削除機能

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#14]
ネコで、アイテムをフラグ代わりに利用されていたことを受けてのIssueです。

従来、フラグの削除機能は「進行が戻ることはない」という理由から設けてきませんでしたが、リクエストがあれば、**隠しフラグ限定**で削除を可能にできればと思います。

`<scene flags="-f01,-f02">`

ネコについてはシーンを分ければ対応は可能なので、Scene30企画限定の問題（＆優先順位は低め）とは思いますが、コンパクトに表せるのは悪いことではないので。

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 69.0.3497.81（64 bit）、iPhone 7／Safariにて確認。
正常に動作しました。
iPhoneでは文字を選択して反転しただけでは文字が読めませんが、該当の文字をコピーし、別の場所にペーストすることで、文字の内容を確認できました。

**Comment by cocotori** [comment]
実装ありがとうございます。
#8 でもコメントしましたが、欲しかった機能なのでありがたいです。
隠しフラグ限定で特に問題ないと思います。

**Comment by RYU-DS** [comment]
これで無理やりアイテムをGet/Lostしなくて済みますｗ
そのスレ第二部の平たい石はこのためだけに出て、そして無くなりましたｗ
その影響でモス撃破後の森の主との会話が大幅に変更になったりして大変だったので、とても助かります。
