### ISSUE TITLE
Playground Editorの強化

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#140]
Playground Flowに置き去りにされていたEditor側の強化＆改善を図ります。

#### Editorロゴ（お願い事項）

@toki-sor1 さん＞
Editorの正式名称も決まったところで、Flow同様のロゴをお願いしても宜しいでしょうか。
もちろん、急ぎではございませんので、ご検討頂けますと幸いですm(_ _)m
＃ 現在はFlowのロゴで代用しております。

#### ~新コンパネ／サイドバー対応（済）~

#119、 #127 に伴い、現状の編集／結果をまとめた構造が難しくなったため、Flowと同じく結果画面を別タブに分離します。以下ページにて新Editorをリリース済みです。
https://www.web-deli.com/sorcerian/text/playground_new.aspx

#### GBAT2STEXTをボタン化（機能のみ済）

従来のGBAT2STextを他同様アイコン化しました。

@toki-sor1 さん＞
お手数をおかけしまして恐縮ですが、アイコン画像のご相談をさせてください（GBATアイコンを加工してアイコン化？）現在はFlowのインポートボタンで代用しています。

#### ~SGML式の埋め込み機能（済）~

現在もありますが、Flow相当の埋め込み式に対応

@toki-sor1 さん＞
毎度お手数ですが、アイコン画像のご相談をさせてください（［${＋}］のような？）
現在は画像なしでメニューのみ配置しています。

#### ~テンプレートの自動ロード（済）~

Editorの構造修繕に伴い、空のエディターだけを初期表示するのはちと殺風景かなと思ったので、空のテンプレートを初期表示するようにしました。

#### マニュアルの改善（途中）

+ チュートリアル／GBATなど、画面も大きく変化しているので現状に即した反映を行います。
+ 投稿方法なども
+ 基本はNew Editorリリース後に対応予定です。

#### ~基本ライブラリの共通化（済）~

これまでゲーム画面とEditorとはライブラリが独立していましたが、ライブラリの共通化を図り、スムーズなリリースを可能にします（動作テスト時は全体的な挙動のご確認を戴ければ幸いです）。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 78.0.3904.87(64bit)にて動作確認。
gbatファイル変換→xmlファイルの読み込み、Pg Flowへの切り替えも正常に行えました。

ロゴ化へのお返事がなかなかできず、遅れてしまい申し訳ありません…！

> Editorロゴ

承知しました。
ただ、文字数が多くなるため、従来のサイズに文字を収めるのが厳しそうな場合は、少しだけ横幅を広げるかもしれません。

> GBAT2STEXTをボタン化

承知しました。
GBATアイコンっぽく見えるようなデザインを入れたいと思います。

アイコンの作成が完了し次第、DMでお知らせしつつ、直接差し替えさせていただきますね。

**Comment by snext1220** [comment]
いえいえ、 @toki-sor1 さんも諸々で手一杯だと思いますので、デザイン／ロゴ系は機能とは切り離してご無理ない範囲で進めてやってくださいませ（汗

> アイコンの作成が完了し次第、DMでお知らせしつつ、直接差し替えさせていただきますね。

ありがとうございます！！
現在はFlowのもので仮置きしているもので、お手数ですが、ファイル名はそれぞれ以下でお願いします～ ＃あとで呼び出し側の方を変更いたします～

+ ロゴ：pge_logo.png
+ GBAT：pg_gbat.png

**Comment by toki-sor1** [comment]
お忙しいところ、お返事＆お気遣いいただきありがとうございます！
まずは一つ一つ進めていこうと思います！

大変お待たせしてしまい申し訳ありません！
アイコンが作成できましたので、ご指定のファイル名で本番環境にアップ致しました！
（意外とGBATの真ん丸コウモリくんのフォルムが難敵でしたｗ）
![image](https://user-images.githubusercontent.com/42646342/68085589-d4742e00-fe85-11e9-90fa-4b43a7b4e05c.png)

**Comment by snext1220** [comment]
ありがとうございます！！
思わぬ難敵、も恐縮です＞＜;
こちら出先だと本番環境に触れないため反映少々遅くなりますが、お待ちいただけますとm(_　_)m

**Comment by toki-sor1** [comment]
いえいえ、元々あるものを手本にしてドットを打つのは、色々と発見もあるので、良い勉強になりましたｗ
反映タイミングも了解です。どうかご無理のないペースでよろしくお願いします～。

**Comment by snext1220** [comment]
久々自宅で更新致しました！
マニュアルも致命的な部分を更新し、なんちゃって最新に更新済みです～
細かな点は気付いたところから修正していければと思いますので、もしお気づきの点があれば［Bug］Issueなどを挙げてやってくださいませ。

ドットを打つのは、色々と発見＞そう仰って戴けると（感謝
