### ISSUE TITLE
ボーナスアイテム適用の改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#141]
現在、ボーナスアイテムをシナリオ開始時に適用していますが、正直、あまり意識していない人も多く、特にバッドアイテムは適用が面倒なことから、厳密に適用していない場合が多いように思われます。

これらについて自動化を進めると共に、自動化の難しいルールを改訂していければと思っています。現時点で使われていないとすればあまり優先順位の高い案件ではありませんが、まずは問題提起までに。

### 改定内容

+ ステータスへの自動反映
+ シナリオ開始時の適用ボーナス
+ 関連するサイドパネルへのボーナス内容の表示（戦闘関連はBattle Sheetなど）
+ ボーナスパネルへの適用ボーナスの表示（済）

### ボーナスの分類

現時点では、以下のように問題点と改善案（途中）を整理しています。dec update時点では議論だけになるかもしれませんが、ご意見頂戴できますと幸いです。

#### シナリオ開始時に適用するもの

bad系の適用が難しいので、もう少し単純なルールに修正要です（特にbgi04）。

```
    // 'gi01' : { name: '金の卵', desc: '月の欠片を5個所有した状態で冒険を開始' },
    // 'gi02' : { name: 'ガラティーン', desc: '火星の欠片を5個所有した状態で冒険を開始' },
    // 'gi03' : { name: '五元素のマント', desc: '水星の欠片を5個所有した状態で冒険を開始' },
    // 'gi04' : { name: 'アマゾンの剣', desc: '木星の欠片を5個所有した状態で冒険を開始' },
    // 'gi05' : { name: '幸福のコイン', desc: '金星の欠片を5個所有した状態で冒険を開始' },
    // 'gi06' : { name: 'ムラサメブレード', desc: '土星の欠片を5個所有した状態で冒険を開始' },
    // 'gi07' : { name: 'G・スレイヤー', desc: '太陽の欠片を5個所有した状態で冒険を開始' },
    // 'gi10' : { name: 'ブルーリボン', desc: '戦闘ダメージを1減算' },
　=> 冒険開始時にSTRを+1
    // 'gi11' : { name: '王家のダイヤモンド', desc: '罠ダメージを1減算' },
　=> 冒険開始時にINTを+1
    // 'gi12' : { name: '不老長寿の水', desc: '冒険中に一度だけHPを半分回復できる' },
    // 'gi13' : { name: 'タリスマン', desc: '冒険中に一度だけMPを半分回復できる' },
    // 'gi23' : { name: 'D・スレイヤー', desc: 'すべての星を1個所有した状態で冒険を開始' },
    // 'bgi03' : { name: '血まみれの斧', desc: '冒険開始時に呪い。解除で3回まで星消費せず魔法発動可' },
　=> 冒険開始時に呪い。解除で3回まで星消費せず攻撃魔法を利用できる
    // 'bgi04' : { name: 'トリカブト', desc: '冒険開始時に毒。但し、解除までシーン毎にMPを1回復' },
　=> 冒険開始時に毒。ただし、解除まで魔法ダメージを半減できる
    // 'bgi05' : { name: 'ギャルのパンティー', desc: '冒険開始時に忘却。解除までSTR/INT0でない方を10' },
　=> 冒険開始時に忘却。ただし、解除時に0になっていたステータスを+1できる
```

#### シーン単位に適用するもの

サイコロが～は自動化であまり意味がなくなるので、「20％確率で回復」などにできればと。

```
    // 'gi08' : { name: '水晶の剣', desc: '左サイコロが5以上の時、そのシーンでHPを1回復' },
　=> 30％の確率でシーンごとにHPを1回復
    // 'gi09' : { name: '王様の杖', desc: '左サイコロが5以上の時、そのシーンでMPを1回復' },
　=> 30％の確率でシーンごとにMPを1回復
    // 'bgi01' : { name: '塩酸', desc: 'シーン毎にダイス合計が5未満でHPを1減算、5以上でMPを1回復' },
　=> シーンごとに30％の確率でHP1ダメージ、40％の確率でMPを1回復
    // 'bgi02' : { name: '紅玉', desc: 'シーン毎にダイス合計が5未満でMPを1減算、5以上でHPを1回復' },
　=> シーンごとに30％の確率でMP1ダメージ、40％の確率でHPを1回復
```

#### 戦闘に影響するもの

戦闘／罠の区別が現在できないので修正要です。

```
    // 'gi14' : { name: '鏡の盾', desc: 'HPダメージを1減算' },
    // 'gi15' : { name: '銀の竪琴', desc: 'MPダメージを1減算' },
    // 'gi16' : { name: 'パンドラの箱', desc: '右サイコロが4以上の時、戦闘回避が可能' },
    // 'gi17' : { name: '魔法の絨毯', desc: '右サイコロが5以上の時、罠回避' },
```

#### ~状態異常を防ぐ（済）~

改定は必要ですが、ほぼ問題なし。

```
    // 'gi18' : { name: '中和剤', desc: '毒耐性' },
    // 'gi19' : { name: '聖水', desc: '呪い耐性' },
    // 'gi20' : { name: 'チルドの実', desc: '凍結耐性' },
    // 'gi21' : { name: '銀のハーモニカ', desc: '石化耐性' },
    // 'gi22' : { name: '真実の鏡', desc: '忘却耐性' },
```

**Comment by snext1220** [comment]
最終的に、以下の内容でボーナス情報を再編し、システムに組み込みました。
ご確認いただけますと幸いです。

```
'happy' : {
'gi01' : { name: '金の卵', desc: '月の欠片を5個所有した状態で冒険を開始する' },
'gi02' : { name: 'ガラティーン', desc: '火星の欠片を5個所有した状態で冒険を開始する' },
'gi03' : { name: '五元素のマント', desc: '水星の欠片を5個所有した状態で冒険を開始する' },
'gi04' : { name: 'アマゾンの剣', desc: '木星の欠片を5個所有した状態で冒険を開始する' },
'gi05' : { name: '幸福のコイン', desc: '金星の欠片を5個所有した状態で冒険を開始する' },
'gi06' : { name: 'ムラサメブレード', desc: '土星の欠片を5個所有した状態で冒険を開始する' },
'gi07' : { name: 'G・スレイヤー', desc: '太陽の欠片を5個所有した状態で冒険を開始する' },
'gi08' : { name: '水晶の剣', desc: '30％の確率でシーンごとにHPを1回復する', type: 'status' },
'gi09' : { name: '王様の杖', desc: '30％の確率でシーンごとにMPを1回復する', type: 'status' },
'gi10' : { name: 'ブルーリボン', desc: '冒険開始時にSTRを1加算する' },
'gi11' : { name: '王家のダイヤモンド', desc: '冒険開始時にINTを1加算する' },
'gi12' : { name: '不老長寿の水', desc: '冒険中に一度だけHPを半分回復しても良い', type: 'status' },
'gi13' : { name: 'タリスマン', desc: '冒険中に一度だけMPを半分回復しても良い', type: 'status' },
'gi14' : { name: '鏡の盾', desc: '戦闘時のHPダメージが1減算される', type: 'battle' },
'gi15' : { name: '銀の竪琴', desc: '戦闘時のMPダメージが1減算される', type: 'battle' },
'gi16' : { name: 'パンドラの箱', desc: '右サイコロが4以上の時、戦闘を回避しても良い（ただし、アイテムは入手できない）', type: 'battle' },
'gi17' : { name: '魔法の絨毯', desc: '右サイコロが6の時、戦闘を回避できる（アイテムも入手可）', type: 'battle' },
'gi18' : { name: '中和剤', desc: '毒耐性', type: 'status' },
'gi19' : { name: '聖水', desc: '呪い耐性', type: 'status' },
'gi20' : { name: 'チルドの実', desc: '凍結耐性', type: 'status' },
'gi21' : { name: '銀のハーモニカ', desc: '石化耐性', type: 'status' },
'gi22' : { name: '真実の鏡', desc: '忘却耐性', type: 'status' },
'gi23' : { name: 'D・スレイヤー', desc: 'すべての星を1個所有した状態で冒険を開始する' },
},
'bad' : {
'bgi01' : { name: '塩酸', desc: 'シーンごとに30％の確率でHP1ダメージ、40％の確率でMPを1回復する', type: 'status' },
'bgi02' : { name: '紅玉', desc: 'シーンごとに30％の確率でMP1ダメージ、40％の確率でHPを1回復する', type: 'status' },
'bgi03' : { name: '血まみれの斧', desc: '冒険開始時に呪い。ただし、解除後に3回まで星消費せず攻撃魔法を利用できる', type: 'magic' },
'bgi04' : { name: 'トリカブト', desc: '冒険開始時に毒。ただし、解除まで魔法ダメージを半減できる', type: 'battle' },
'bgi05' : { name: 'ギャルのパンティー', desc: '冒険開始時に忘却。ただし、解除時に0になっていたステータスを+1できる', type: 'status' },
}
```

**Comment by toki-sor1** [comment]
各アイテムの効果の修正お疲れ様です！
確かに、私もテストプレイ時には効果を反映させていないことも多いので（汗）、自動的に反映されるのは便利ですし、ありがたいです～。
それに、システムをより良い方向に活かすように改善されているところが良いなと思いました！
（それぞれタイプ分けされているのも、分かり易いです！）

内容も確認しましたが、説明や効果がよりシンプルに分かり易くなりましたね。
システムが変わってきたことであまり意味がなくなってきたアイテムも、現在のシステムに合った効果になっているのもGOODです！

Win 8.1／Chrome 78.0.3904.87(64bit)で動作確認。
どうも「塩酸（シーンごとに30％の確率でHP1ダメージ、40％の確率でMPを1回復する）」が選ばれると、ゲーム画面の各項目が縦一列にずらずらと表示されてしまうなど、表示が乱れてしまうようです。

**Comment by cocotori** [comment]
自動更新、ありがたいです。

どのボーナスアイテムが選ばれるかが自動になったことも含め、
より、ゲームらしさが出たのではないかと思います。

**Comment by snext1220** [comment]
@toki-sor1 さん、 @cocotori さん＞
ご評価ありがとうございます！
以前からの懸案を今回のサイドバー化と合わせて対応してしまいましたが、ご評価ありがたいかぎりです。
＃ 最初は自動化など考えていなかったので、結構複雑なルールもあったのですが、結果としてすっきりした感じですｗ

>　どうも「塩酸（シーンごとに30％の確率でHP1ダメージ、40％の確率でMPを1回復する）」が選ばれると、ゲーム画面の各項目が縦一列にずらずらと表示されてしまうなど、表示が乱れてしまうようです。

こちらスミマセン、Win10+Chromeは同じバージョンで確認したのですが、再現しませんで...大変恐縮ですが、キャッシュを破棄するなどして今一度ご確認いただいてもよろしいでしょうか。また、もし改善しない場合は、念のため、該当キャプチャをいただいてもよろしいでしょうか。お手数をおかけします。。。

**Comment by toki-sor1** [comment]
お忙しいところ、お返事ありがとうございます！

> Win10+Chromeは同じバージョンで確認したのですが、再現しませんで...

おろろ、そうでしたか；
こちらは、改めてキャッシュをクリアしてからGitHubの方にアクセスして試してみました。
該当のBONUSが選ばれるまで再読み込みを繰り返してた影響もあるのかもしれませんが、こちらでは同じ症状が出ますね；（シナリオは『双王』です）
![image](https://user-images.githubusercontent.com/42646342/68117584-1b732980-ff41-11e9-89d8-fc09201a5bc1.png)
![image](https://user-images.githubusercontent.com/42646342/68117872-e1eeee00-ff41-11e9-8084-bd8d1df1ec19.png)

**Comment by snext1220** [comment]
おぉ、そういうことですね…！
スミマセン、現象を読み違えておりました。
そして、コンソールまで含めたキャプチャで原因を速やかに特定できました。
ありがとうございます！GitHub反映済みです。

お手数ですが、ご確認いただけますと幸いですm(__)m

**Comment by toki-sor1** [comment]
ご対応ありがとうございます！
確かにランダム発生の不具合は、気付きにくいですよね；

先ほど、Win 8.1／Chrome 78.0.3904.87(64bit)にて、上記と同じ条件（連続読み込み）で確認しました。
今度は「王家のダイヤモンド」が表示された時に、同じ不具合が出てきてしまいました；
（iPad Proの方で「紅玉」が出た時は、不具合が解消されていました）

お手数をお掛けしてしまい恐縮ですが、よろしくお願い致します；
![image](https://user-images.githubusercontent.com/42646342/68295540-fa900d00-00d5-11ea-8d50-b3eba9fb67ab.png)
![image](https://user-images.githubusercontent.com/42646342/68295460-d2081300-00d5-11ea-9055-5179e0f46af3.png)

**Comment by snext1220** [comment]
こちらこそ何度も失礼いたしました！
サンプリングでは見ていたつもりだったのですが、何度も問題が出ており申し訳ありません...
先ほど修正しましてGitHubにも反映済みでございます～
改めてご確認戴ければ幸いですm(_ _)m

**Comment by toki-sor1** [comment]
いえいえ、本当にお疲れ様です＆ご対応ありがとうございました！
Win 8.1／Chrome 78.0.3904.87(64bit)にて動作確認
「王家のダイヤモンド」や「紅玉」など、今まで問題となっていたBONUSで不具合が出ないことを確認しました！

**Comment by snext1220** [comment]
ホント、細かくご確認戴いてありがとうございます＆感謝感謝です！
おかげさまで現状確認できている問題は一応クリアのようなので（実は他も色々あって、裏でセコセコ直してました^^;）、一旦Closeとしてまいりますね。
