### ISSUE TITLE
旧コンパネの廃止

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#142]
#127 の対応に伴い、旧コード整理＆廃止の必要性が出てきています。
見た目的にはたんなる廃止なのですが、地味に慎重を要するところなのでIssueとして挙げておきます。動作確認時には、既存シナリオの動作確認と合わせながら、考えうる一通りの機能をお手元で試して戴けると幸いです。

**Comment by Salvadors-cabin** [comment]
このIssueの影響かどうかはわかりませんが、GitHUBの環境で以下のボタンが効かなくなってます。

・BattleSheetの「ダメージ」ボタン
　※トースト表示も出てきません。
・Status、Magicシートの「+」「-」ボタン

Win10+Edgeで確認しました。
なお、本番環境では問題無いようです。

**Comment by snext1220** [comment]
@Salvadors-cabin さん、ご確認有難うございます！
本Issue＋αの影響で一部の機能が無効化していたようです；
大変失礼いたしました。。

先ほど修正しましてGitHub Pagesに反映させて戴きました～

**Comment by Salvadors-cabin** [comment]
早速の対応、お疲れ様でございますー。
問題が解消していることを確認しました！

**Comment by Salvadors-cabin** [comment]
Win10+Edgeでは問題無いのですが、前々から問題の多かった古いiPad(iOS9+Safari)ではリニューアルされた本番サイトとGitHUBはほとんど動かなくなっているようです。
そろそろ限界のようです。

**Comment by toki-sor1** [comment]
ご対応お疲れ様です～。
Win 8.1／Chrome 78.0.3904.87(64bit)、iPhone7／Safariにて動作確認。
- #127 の不具合あり
- 以下のように入力したところが、参照画像のような状態になってしまい、正常に表示されませんでした（現在はルビを消して対応）。
```
『${sex?彼:彼女}』が＜${竜王の如き混沌|キングドラゴン}＞
```
![image](https://user-images.githubusercontent.com/42646342/68046469-4c741400-fd1f-11e9-91af-f5a0be52a505.png)
- それ以外では、大丈夫そうでした。

**Comment by snext1220** [comment]
@Salvadors-cabin さん＞
ご確認有難うございます！
FlowあたりからJavaScript的に新仕様を使っているので、その影響がありそうです。
ちなみに、どの辺で問題が出ていますでしょうか？

@toki-sor1 さん＞
ご確認有難うございます！
現象見る限り、ルビについては恐らく前からの問題のように思えます＞＜
修正進めます…！

**Comment by cocotori** [comment]
ざっとしか見れていませんが、
大きな不具合はなさそうでした。
操作していく中で、何かあったらご連絡します。

**Comment by Salvadors-cabin** [comment]
>ちなみに、どの辺で問題が出ていますでしょうか？

以下の画像です。(上：Webサイトの上部バーScenario選択後、下：GitHUBのScenarioメニュー選択後)
両方ともこれ以上進みません。
![stextWebsite](https://user-images.githubusercontent.com/42834363/68068374-6a7d5b00-fd97-11e9-910c-9cc7b4bef9f5.gif)
![GitHUB](https://user-images.githubusercontent.com/42834363/68068378-76691d00-fd97-11e9-9fb8-3c93621975f6.gif)

**Comment by snext1220** [comment]
皆さま、ご確認ありがとうございました！
本Issueに限らず、今回のdec updateは影響範囲も広いため、中々すべてをご覧になれないかと思いますが、ぜひ、ご自分のシナリオデバッグと合わせて、気になったところに触れてみていただけると幸いです～

@toki-sor1 さん＞
ルビについては、確認したところ、ほかのSGML式との関係で慎重に対応した方が良さそうなので、もう少しお時間いただくことになりそうです。恐縮ですが、 #148　として別Issueに改めさせていただきました。お待ちくださいませ～

@Salvadors-cabin さん＞
ご説明ありがとうございます！
ああ、これはもう全然ですね...（もう少しは部分的に動くかと思っていたのですが^^;）
ご指摘の通り、iOS9+Safari　によるテストは終了にてお願いいたします...

＃ 大変恐縮ですが、どなたかタブレット系でご確認いただけそうな方がいらっしゃいましたら、ご協力をお願いいたします＞皆さま
