### ISSUE TITLE
魔法行使ボタンの改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#143]
#141 の派生Issueです（準備のための機能を実装しています）。

magicシートの［Shoot］ボタンを押すことで、魔法の効果に応じてステータスを自動演算し、結果をトースト表示するように改めました。すべてが自動演算ではありませんが、以降の指示が明確になったことで、プレイしやすくなったのではないかと思っています。

**Comment by toki-sor1** [comment]
今までは手動でしたが、自動で発動できるのは便利で良いですね！
ダメージ半減も指示を表示してフォローしているのでばっちりですね！

Win 8.1／Chrome 78.0.3904.87(64bit)、iPhone7／Safariにて動作確認。
- 「呪い」状態でも魔法が利用できてしまいました。

**Comment by cocotori** [comment]
今までだとせっかくのShootボタンがあっても
手動操作が発生していて、片手落ち感を感じてしまっていたので、
とてもいい改善だと思います。

手動操作の部分も、トーストが役にたってると思います。
トースト、普段は場所を取らず
必要なタイミングで情報を提供できるので
なかなか便利ですね・・・他にも色々と役に立ってくれそうです。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

@toki-sor1 さん＞

> 「呪い」状態でも魔法が利用できてしまいました。

こちらは以前からの問題というか仕様というか、微妙な状態になっていました（汗
基本は状態異常は「毒」のみ自動化しており、あとは見た目を変更していた、というだけなのですが、特に呪いは魔法を自動化したことで、中途半端な感じになったのかもしれません。

ということで、こちらは呪い時にはShootボタンでエラートーストを出して魔法を実行できないよう、あらためています（GitHub Only）。

ただ、関連して一つ問題がありまして、この問題はシーン移動時の魔法発動にもあります。
現時点では、シナリオ製作者判断ということでなにもしていませんが、実は、こちらも呪い時にはボタンが出ないように改めるべきでしょうか。
＃ Compati 案件なので、タグをつけて皆様のご意見をお待ち致しますね。

@cocotori さん＞

> なかなか便利ですね・・・他にも色々と役に立ってくれそうです。

はい、トーストはじめ、サイドバー、メニューなど、サイト／ゲーム画面双方で共通してライブラリを導入したことで、これまであふれかえっていた情報が随分と整理され、UI的にもすっきりしたのかなと。「こんな情報も見せたい」などあれば、引き続きご意見宜しくお願いします！

**Comment by snext1220** [comment]
魔法移動ボタンについては、Issueのテーマからは若干外れかけていたのと長くなってきたので、 #150 に移動済みです。ご意見引き続きよろしくお願いします～
