### ISSUE TITLE
state属性の追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#144]
#143 の派生Issueです。

［Shoot］ボタンの自動化に伴い、状態異常の操作が必要になったため、併せてscene要素にstate属性を付与できるようにしました。詳細はリファレンスを参照してください。

＃ これでほとんどのステータスがscene要素で操作できるようになったはずです。

**Comment by toki-sor1** [comment]
ダメージ式ボタンを使用しなくても良いので、より自然な演出ができるようになって良いですね～。

Win 8.1／Chrome 78.0.3904.87(64bit)にて動作確認。
正常に動作しました。
