### ISSUE TITLE
hp／mp属性の仕様変更

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#145]
#143 からの派生Issueです。

［Shoot］ボタンの自動化に伴い、HP/MP半減の操作が必要になったため、hp/mp属性にも設定値halfを追加しました（あまり用途はないかもしれませんが、邪魔になるものではないと思うので）。詳細はリファレンスを参照してください。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 78.0.3904.87(64bit)にて動作確認。
正常に動作しました！
