### ISSUE TITLE
自動化に伴うSEの追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#146]
ここ最近で随分と自動化が進みましたが、ボタンクリック＋トースト表示のため、演出としては若干弱いものとなっています。場合によっては、以下の箇所にSEを追加してはどうかと考えていますが、如何でしょうか。
＃かえって五月蠅いというご意見もあるかと思い、まずはdec updateでは提案のみと致します。

+ 魔法のShoot時
+ Battle Sheetでの被ダメージ時
+ Battle Sheetでのアイテム入手時
+ シーン移動時のダメージ等にはSEは適用**しない**（重複を避けるため）
    + ■代案■ se属性＞状態異常＞hp/mpダメージ の順でSEを適用という方法もあり？

ここにもほしい（いらない）、など、まずはご意見戴けますと幸いです。

■強募■ 良いSE音源があれば、お教えくださいm(_ _)m

**Comment by toki-sor1** [comment]
私もシナリオでよくSEを追加することがありますが、BGMとのバランスに悩みはするものの、場面の雰囲気が強く感じられるようになるのが良いですね～。

今回はシステム関連のSE追加のお話ですが、確かに頻繁にSEが鳴ると、やや騒がしくなってしまうので、もし実装する場合は、加減が必要だと思います。

> 魔法のShoot時、Battle Sheetでのアイテム入手時

戦闘ではダイス音が入りますので、被ダメージの時に鳴るとSE同士がけんかしてしまうような気がします。
もし実装するとなった場合は、個人的には、上記2箇所が頻度的にも良さそうかなと思っています。

***
SE音源だと、下記のサイト様をよく利用させていただいております～。

- On-Jin ～音人～ 様（https://on-jin.com/ ）
- 効果音ラボ 様（https://soundeffect-lab.info/ ）

**Comment by snext1220** [comment]
お返事断片で恐縮ですが…

> 戦闘ではダイス音が入りますので、被ダメージの時に鳴るとSE同士がけんか

こちらですが、SE再生は［ダメージ式］ボタンを押したところで、になるので、そのご懸念は大丈夫かと思います～ アイテム入手と揃える意味では、ダメージ時のSEまではあった方が？と思ったもので、念のため^^;

**Comment by cocotori** [comment]
どこまで演出をリッチにしていくかは難しい問題ですね・・・

個人的にはユーザーさんのアクションに対してリアクションとして
SEがあるといいと思うので、
被ダメージ、Shoot時などにSEがあるといいと思います。

ただ、ほぼ間違いなく、
それを煩わしく思うタイプの方もいるはずなので、
SEのON/OFF（BGMとは別に）機能は必須かと思います。

**Comment by toki-sor1** [comment]
> SE再生は［ダメージ式］ボタンを押したところで、になるので、そのご懸念は大丈夫かと思います～ 

言葉足らずで申し訳ありません…！
SEが鳴るタイミングは、同時ではなくそれぞれ異なるのは理解していました～。
ただ、ダメージ式ボタンは、ダイスを振ってからすぐに押すものなので、余韻的な意味でSE同士がちょっと喧嘩してしまうかなと思ったのでした；

そうですね、タイミング的には問題なさそうですし、アイテム入手時にあってダメージ式ボタンを押した時にないのもやや不自然なので、統一した方が良いかもしれません。

> それを煩わしく思うタイプの方もいるはずなので、
SEのON/OFF（BGMとは別に）機能は必須かと思います。

私もココさんのご意見に賛成です～。
こちら、個別にON/OFFできるとベストかなと思いますが、難しそうなので、SE全てのON/OFFを切り替えられたら良いですね。

**Comment by snext1220** [comment]
SEについてのご意見ありがとうございます。
追加そのものについては、おおよそご賛同いただいた感じですね。
優先順位は低めだと思いますが、順次進めてまいります。

> SE音源だと、下記のサイト様をよく利用させていただいております～。

ご紹介ありがとうございます！
こちら参考に、音源選定していければと思います。

正直、この辺は皆さま拘りもありそうなので、ご要望をぜひ頂ければ反映してまいります。ぜひご協力いただけますと。

現時点で、追加予定の音源は以下です（魔法がより細かい方が良いかも？）。

+ ダメージ時
+ アイテム入手時
+ 魔法発動時（攻撃）
+ 魔法発動時（回復）

＃ ダメージ式についてのご説明ありがとうございました！こちら、まずは当てはめてみて、五月蠅いようであれば調整していきますね＞ときのじさん

> SEのON/OFF（BGMとは別に）機能は必須かと思います。

こちら実装の際にはオンオフは入れていきますね（現在はダイスはオフにできないので、これも対応予定）。ただ、できればBGMのオンオフと連動させていければと思うのですが、いかがでしょうか（地味に音声周りは複雑なので、できればあまりわけたくない、といいますか...^^;）。


なお、こちら議論だけのIssueだったので、議論は継続しつつ、対応はJan Update以降に持ち越してまいります～

**Comment by toki-sor1** [comment]
早速のお返事ありがとうございます。

> こちら参考に、音源選定していければと思います。

> 正直、この辺は皆さま拘りもありそうなので、ご要望をぜひ頂ければ反映してまいります。ぜひご協力いただけますと。

上記で挙げていないサイト様もありますが、いくつか候補を書き込みますね。
（ソーサリアンっぽいSEは難しいので、一般的なゲームでいうとこんな感じかな～と）

- ダメージ時
  - https://on-jin.com/ の「効果音ジャンル＞戦闘系音＞手足・殴る、蹴る10」
  - 『戦闘01』無料・フリー効果音素材/魔王魂 https://maoudamashii.jokersounds.com/archives/se_maoudamashii_battle01.html
  - https://soundeffect-lab.info/sound/battle/ の「戦闘＞戦闘[1]＞格闘（ゲーム・アニメ風）＞小パンチ」

- アイテム入手時
  - https://on-jin.com/ の「効果音ジャンル＞戦闘系音＞手足・殴る、蹴る10」
  - https://pocket-se.info/ の「宝箱を開ける音」(https://pocket-se.info/archives/1318/ )

- 魔法発動時（攻撃）
  - https://soundeffect-lab.info/sound/battle/ の「戦闘＞戦闘[1]＞ファンタジー＞詠唱2」

- 魔法発動時（回復）
  - https://on-jin.com/ の「効果音ジャンル＞その他音＞魔法的音08」
  - https://soundeffect-lab.info/sound/battle/ の「戦闘＞戦闘[1]＞ファンタジー＞詠唱2」

> こちら、まずは当てはめてみて、五月蠅いようであれば調整していきますね＞ときのじさん

はい～、よろしくお願い致します！（おそらく、音量調整は必要かと思います～；）

> ただ、できればBGMのオンオフと連動させていければと思うのですが、いかがでしょうか

なるほど、複雑なご事情が！
承知しました！　是非BGMのON/OFFとセットのご対応をお願い致します～。
ただ、「BGMは聴きたいけど、SEは切りたい」というプレイヤーさんもいらっしゃるかなと思っています。
音量調節と、必要とあればSEを鳴らすシーンをもう少し絞るのも手でしょうか。

**Comment by snext1220** [comment]
SE候補ありがとうございます！
こちら拝聴しつつ、選定進めてまいりますね～（他の皆様もご希望あれば是非に）

BGM、元々オマケ機能だったので、他以上に適当実装だったのですが、途中から大幅に拡張して、手を付けるのが怖い状態に^^;
とりあえずSEは切り離して新実装にする予定ですが、BGMと足並み揃えるまではできるだけシンプルさを保たせてくださいませ～

別個なのでSE独立での音量絞り込みはできるかと思います。鳴らすシーンも実装してみて五月蠅いようであれば調整してまいりましょう！

**Comment by toki-sor1** [comment]
先ほど「双王」の修正を行ってテストプレイを行っていましたが、早速SEが付いていましたね～！
ご対応、そしてSEの吟味と調整お疲れ様でした！

> BGM、元々オマケ機能だったので、他以上に適当実装だったのですが、途中から大幅に拡張して、手を付けるのが怖い状態に^^;

> とりあえずSEは切り離して新実装にする予定ですが、BGMと足並み揃えるまではできるだけシンプルさを保たせてくださいませ～

いやぁ、まさに制作秘話ですね…ｗ
どうか慎重に開発を進めていただければと思います～！
引き続きよろしくお願い致します！

> 別個なのでSE独立での音量絞り込みはできるかと思います。鳴らすシーンも実装してみて五月蠅いようであれば調整してまいりましょう！

音量絞り込みもできそうなのですね、承知しました～。
現在採用されているSEですが、個人的には五月蠅い感じもなく、丁度良い印象でした！

ただ、自分で挙げておいて何ですが、アイテム入手時のSEが、やや分かりにくい感じですかね…？
ちょっと他に合いそうなものも挙げてみます～。

- アイテム入手時（追加候補）
  - https://on-jin.com/ の「効果音ジャンル＞生活系音＞トランク・開ける」
  - https://on-jin.com/ の「効果音ジャンル＞生活系音＞星・キラーン05」

**Comment by snext1220** [comment]
> 早速SEが付いていましたね～！

確認早いｗ
はい、実は対応不完全だったのですが、こっそりUpしていました^^;
先ほどSEのオンオフ対応、アイテムGet時SEの修正なども行い、GitHub／本番双方に反映いたしました～
＃改めて音声のご提案有難うございました！

現時点で、以下の種類のSEが設定されています。

+ 魔法詠唱時（共通） ※魔法種類ごとにバリエーション持たせるかは要検討
+ アイテム入手時
+ ダメージ時
+ 状態異常時
+ ダメージ／状態異常を防いだ時

音声そのものの変更は勿論、種類を増やすなども可能なので、実際にご確認戴いてご意見いただければ幸いです。

> どうか慎重に開発を進めていただければと思います～！

ありがとうございます！
この辺はゆるゆるになるかと思いますが、新実装に伴って、ボリューム機能などもいずれは、と思っております～

**Comment by toki-sor1** [comment]
> はい、実は対応不完全だったのですが、こっそりUpしていました^^;
先ほどSEのオンオフ対応、アイテムGet時SEの修正なども行い、GitHub／本番双方に反映いたしました～

こちらこそ各種ご対応やSEの実装等お疲れ様でした＆ありがとうございました～！
SEが入ると一気にゲーム感が増しますね！
デジタルならではの新しいゲームブックとして、また一歩進化したように感じました！

現在実装済みのSEですが、私はSEの選択＆音量ともに丁度良いと感じました。
今のところは、現在実装されているSEで十分かな～と思っています。

**Comment by cocotori** [comment]
SE、確認しました。
プレイヤーのアクションに対して
リアクションがあるのはとてもいいことだと思います。

わたしはややSEが大きかなと思いました。
ただこれは好みなので
突き詰めると
BGM、SEともにボリューム調整ができるようにしなければ
ならない、ということになってしまいますからね・・・

それは大変だと思うので一旦置いておいてもらって大丈夫です。

**Comment by snext1220** [comment]
> わたしはややSEが大きかなと思いました。
> ただこれは好みなので～～

ご指摘ありがとうございます。
丁度良いというご意見もあったので、こちらは若干だけ小さく設定してみました（GitHub Only）。
ボリューム調整もいずれは、と思っておりますので、新機能群がある程度落ち着くまでお待ちいただけますと…！
