### ISSUE TITLE
ルビの不具合（SGML式）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#148]
https://github.com/snext1220/stext/issues/142#issuecomment-548896632
を受けてのIssueです。対応少々お待ちください。

---

 以下のように入力したところが、参照画像のような状態になってしまい、正常に表示されませんでした（現在はルビを消して対応）。
```
『${sex?彼:彼女}』が＜${竜王の如き混沌|キングドラゴン}＞
```

---

**Comment by snext1220** [comment]
修正し、GitHub Pagesのみ反映済みです！

**Comment by toki-sor1** [comment]
お疲れ様です！
こちらの不具合が改善されているのを確認しました！
ご対応ありがとうございました！
