### ISSUE TITLE
HP／MP属性の上限ガード解除

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#149]
https://github.com/snext1220/stext/issues/127#issuecomment-549139437
由来のIssueです。

> hp／mp属性による変更は上限を超えた場合は、上限で止めるという仕様になっていたもので...
> その仕様を廃止しても良いか、ですね...

copati案件なので、半数以上の賛同でもって対応の予定です。
ご意見よろしくお願いします！

現状、 @toki-sor1 さんの賛同を戴いているという認識です。

**Comment by toki-sor1** [comment]
> 現状、 @toki-sor1 さんの賛同を戴いているという認識です。

はい～、賛成派です！
今回、「双王」の方は「ダメージ式の修正＋ダメージを受けない選択肢を選べば大丈夫かな」と判断し、戦闘ルールからHP/MP上限値超えを廃止していますが、今後のことを考えると、安定して上限値を超えていても遊べる方が良いかな～と。

**Comment by Salvadors-cabin** [comment]
上限オーバーは問題ないと思います。
が、今のStatus画面での表示は"aa/bb"となっているので、bbを超えてaaが表示されると、バグっぽく見えるかもしれません。
「MAX値無し」という仕様にするなら"/bb"の表示は無しにした方がよい気がします。

**Comment by cocotori** [comment]
上限撤廃自体は賛成です。
何らかの加護を受けて、一時的に上限を超えられるなど、
シナリオに深みを表現できると思います。

ただ、まだイメージがしきれていないのですが、
新しい仕様では「現在値に関わらず上限までの全回復」
という行動はできないということでしょうか？

シナリオの途中で、全回復して
決まったステータスでシナリオに挑戦してもらいたい、
という要望があるかなと思ったので。

実現するのであれば、
上限を見ながら手動で回復してもらう旨の
メッセージをシーン中に入れるとかでしょうか。

**Comment by snext1220** [comment]
皆さま、ご意見ありがとうございます。
上限オーバーはおおよそ賛成を戴いたのですが、引き続き課題もありますね。。

以下、回答してまいります。

> 何らかの加護を受けて、一時的に上限を超えられるなど、シナリオに深みを表現できると思います。

はい、既にドラスレなどでも上限越えが前提になっていますし、今後、レベルアップルールが標準で実装されてくると、これまでの上限は単なる「初期値」として以上の意味は持たなくなってくるのかなと；

> 新しい仕様では「現在値に関わらず上限までの全回復」という行動はできないということでしょうか？

こちらは可能です。
ただ、上限というよりも初期値への回復、という形になります。

> が、今のStatus画面での表示は"aa/bb"となっているので、bbを超えてaaが表示されると、バグっぽく見えるかもしれません。

仰る通り、ここが悩ましい。。。
一番良いのは、上限（bb）も可変にできることなのですが（そうすれば、full指定もより直観的にはなるかと）、ステータスシートがまた込み入ってしまうので、悩ましい。。
＃機能的には全く実装の問題ないので、純粋にUIの問題です。

この辺、こんなレイアウトであれば、などあれば、是非アイデアよろしくお願いします＞皆さま

**Comment by toki-sor1** [comment]
> 一番良いのは、上限（bb）も可変にできることなのですが（そうすれば、上のfull指定もより直観的にはなるかと）、ステータスシートのレイアウトがまた込み入ってしまうので、悩ましい。。
＃機能的には全く実装の問題ないので、純粋にUIの問題です。

また込み入ってしまうのは避けたいですよねぇ；
いっそのこと、HPとMPの「＋」と「－」を取って、上限（bb）も可変にするのは如何でしょう？
現在では、戦闘だと自動計算がありますし、シーン移動に伴うダメージも自動で増減できるので、HPとMPに関しては、メインを自動計算に委ねても良いような気がします。

**Comment by Salvadors-cabin** [comment]
シナリオ側でどのようなイベントを想定しているかは色々あると思います。
どう使うかはちょっと置いておき、システム面から頭の中を整理してみました。

(1) "MAX"(上限)という意味からして、HP,MPがMAX値を超えるというのはシステムが自らMAX値の意味を無くしているような気がします。
(2) HP,MPがMAX値を超えたとき自動的にMAX値も増えるのなら、システム的に意味が保たれていそう。
(3) (2)のようにするなら表示も問題無いと思います。（「+」「-」は今のままで、HP,MPを上限値以上に設定したらMAX値も一緒に上がるようにする）

**Comment by snext1220** [comment]
皆さま、ご意見ありがとうございました。
頂いたご意見に基づいて、整理してまいりますね。

#### 上限も可変

こちらはご指摘の通り、意味が不明瞭になるだけなので、**可変で進める**方向でまいりたいと思います。

#### xxxx_max属性を追加（scene要素）

伴い、自動化の道を用意していきます。

+ hp_max・mp_max・str_max～krm_maxが対象です。
+ 設定可能な値は、+10、-10、-10..-1（範囲指定）

＃ 範囲指定は不要でしょうか。

#### 可変の方法

こちらは悩ましいですよね。。

現在値／上限値が自動連動する方式＞UIにはほぼ影響が出ないことから、すごく魅力的なのですが、上限を減らす場合に対応できない点に悩ましさを感じています；あとは暗黙的な更新がなにか新たな矛盾を引き起こさないかと、漠然とした不安も（こちらは根拠ありません^^;）

［+］［-］（Spinner）を削除＞ご指摘のように、役割がだんだん薄れてきていますね～システム的には楽で、シートそのものもスッキリするので、これまた魅力的なのですが。旧シナで十分に対応できていないものもあることを考えますと、微妙に機能ダウンしてよいかと悩んでいました；

でもって、亜案なのですが、

+ 常時は［+］［-］を非表示
+ テキストボックスにフォーカスしたところで、その前後の［+］［-］ボタンだけを表示

などは如何でしょうか。見た目の感じが若干心配ですが、とりあえず要件は満たしそうです。お手数ながら、引き続きのご意見をお待ちしています。

**Comment by toki-sor1** [comment]
まとめお疲れ様です！
意見についてご検討いただき、ありがとうございます！

> 上限も可変

こちらは問題ありません！

> xxxx_max属性を追加（scene要素）

良いと思います！
範囲指定ですが、ランダム要素があるところがゲームらしくて良いかなと思います。

> 可変の方法

なるほど、どちらか片方の方法だと一長一短なのですね；
そうなると、リオさんがご提案くださった亜案が良いと思います～。

仰るとおり見た目がどうなるかが心配ですが、こちらも気になるようであれば調整という感じになりそうですね。

**Comment by cocotori** [comment]
・xxxx_max属性を追加（scene要素）

+10,-10と言っているのは例でしょうか？
そうでなければ、自由な値を増減できてもいいように思います。

範囲指定はあってもいいと思います。


・可変の方法

亜案もよさそうなのですが、モバイル端末等だと
タップ数が増えてしまって操作がやや煩わしくなるかなと思いました。

ただ、自動計算のおかげで+-ボタン自体が、
通常押すものでなくなってきていることを考えると
隠してしまうのもありかもしれません。

そのままにする方法でも、隠してしまう方法でも、どちらでも大丈夫です。

**Comment by snext1220** [comment]
@toki-sor1 さん、 @cocotori さん＞
ご意見有難うございました！

> xxxx_max属性を追加（scene要素）

+10、-10はもちろん例なので、自由に設定可能です！
こちらは凡そのご賛同を得られたように思えるので＆他に影響しないので、次回Updateに向けて実装を進めていこうと思います。

また、合わせて以下の修正を行う予定です。

+ ステータスシートで各上限値を変更可能に（まずはテキストボックスのみ）
+ hp/mp属性などによる上限オーバー時の上限丸めは **維持**

> 可変の方法

こちらは意見が割れており、悩ましいですね...
ただ、議論も出尽くした感があるので、（少し後になるかもしれませんが）亜案で部分的に実装してみて、まずは使い勝手を見てみる感じでしょうか；；

**Comment by toki-sor1** [comment]
動作確認環境：Win 8.1/Chrome 80.0.3987.122(64bit)

自作シナリオを改変して動作確認を行いました。
xxx_max属性を指定し、上限値が加算/減算されるのを確認いたしました。
また、上記の状態で上限オーバーによる上限丸めがされることも確認済みです。

> 可変の方法

> ただ、議論も出尽くした感があるので、（少し後になるかもしれませんが）亜案で部分的に実装してみて、まずは使い勝手を見てみる感じでしょうか；；

そうですね、まずは亜案で操作性などを確かめるのが良いかもしれませんね。
こちら承知いたしました。

**Comment by cocotori** [comment]
max属性の変更を確認しました。

現状、上限オーバーの丸めが発生するのはHP,MPのみで
STR～KRMには丸めが発生しないようでしたが
それでよろしいですか？

**Comment by snext1220** [comment]
はい、現時点では仕様です。
というのも、主に「そのドラ」でSTR～KRMの上限操作が行われているため、恐らくcompati案件になってしまうかと。

ただ、ルール不ぞろいは、恐らくあとで混乱になるかと思うので、「そのドラ」の了承を得た上で、統一した方が良いかもしれませんね。
＃お忙しい処大変恐縮ですが、アンケ機能共々、ryuさんにご連絡（確認）戴いても宜しいでしょうか＞ @Salvadors-cabin さん

もちろん、他の方も「変更困る」などあれば何なりとお願いします！

**Comment by snext1220** [comment]
現時点で、まずは最小限の修正となる、ステータスシート上のXXXX_MAX欄をすべてテキストボックスに修正してみました。不揃いではありますが、上限値を頻繁に動かすことはない＆ほとんどが自動計算に委ねることを考えれば、これでも事足りるかと考えた次第です（GitHubのみ反映）。

と、ここまで修正したところで、一寸混乱してきました；

hp／mpは冒険中常に増減するものなので、全回復などの用途で上限（hp_max、mp_max）が必要なのですが、実はstr～krmについては上限（xxx_max）の意味がなかったりしますか。
というのも、（たとえば）strとstr_maxとが異なる状況が考えにくいのかと思いまして。
＃あえていえば罠などで暫定的にstrを増減させて、すぐにstr_maxに戻すようなケースくらい？

となると、str～krmを変更する時は、常にstr_max～krm_maxも合わせて設定しなければならず、却って面倒なのかなと。とすると、そもそもstr～krmだけにしてしまい、str_max～krm_maxは廃止（表示もしない）のがスッキリなのかなと思った次第です。
＃成長する場合はstr～krmを操作すればいいだけで、xxx_maxが表示されているから変な問題が出てくるのでは？

今更ながらに「str_max～krm_maxの用途って？」と思ってしまったもので、投稿しておきます。

**Comment by Salvadors-cabin** [comment]
>str_max～krm_max属性を廃止（まだ使ってる人いないですよね？）
>ステータスシートでのstr_max～krm_maxを非表示
>一応、セーブデータとしてのstr_max～krm_maxは残す（使わないけど）

私としては特に問題ありません。

**Comment by toki-sor1** [comment]
> str_max～krm_max属性を廃止（まだ使ってる人いないですよね？）
ステータスシートでのstr_max～krm_maxを非表示
一応、セーブデータとしてのstr_max～krm_maxは残す（使わないけど）

こちらも上記仕様で問題ありません。
そうですね、STRなどの上限値は、ステータスシートでは非表示で良いと思います。
もし上限値のデータが必要であれば、シナリオ側からメモの指示を出すなどして、手動で記録しておけば良さそうです。

**Comment by cocotori** [comment]
わたしも問題ありません！

**Comment by snext1220** [comment]
特に問題なさそうなので、修正の方向で作業を進めます。

一寸だけ気になったのは、

> もし上限値のデータが必要であれば、シナリオ側からメモの指示を出すなどして、～

でしたが、もし想定されているようなシーンがあれば、念のためお教えくださいませm(_ _)m

**Comment by cocotori** [comment]
HP/MPのみ現在値/上限値があり、
そのほかのステータスは現在値のみになることを確認しました。

playground上のシーンタブで、
ステータス変更量を入力しようとしたときに
入力候補が出るのもとてもいいと思います。

ただ、今回の件でSTR等は上限値という概念がなくなりましたので、
fullが候補として現れないほうがいいと思いました。
（現状で選んでしまうとSTRが0になってしまう？ような
　現象になってしまいました。）

**Comment by toki-sor1** [comment]
> HP/MPのみ現在値/上限値があり、
そのほかのステータスは現在値のみになることを確認しました。

Win8.1／Chrome 83.0.4103.97(64bit)にて上記の表示であることを確認しました。

> ただ、今回の件でSTR等は上限値という概念がなくなりましたので、
fullが候補として現れないほうがいいと思いました。
（現状で選んでしまうとSTRが0になってしまう？ような
　現象になってしまいました。）

こちらもGitHub版のPg Flowで試したところ、同じ状態になりました。

<img src="https://user-images.githubusercontent.com/42646342/83938372-8e61bd00-a80e-11ea-9f05-13c1a2d95ffe.png" width="500">
<img src="https://user-images.githubusercontent.com/42646342/83938333-4773c780-a80e-11ea-8a6e-e3dce8949524.png" width="500">

>> もし上限値のデータが必要であれば、シナリオ側からメモの指示を出すなどして、～

>でしたが、もし想定されているようなシーンがあれば、念のためお教えくださいませm(_ _)m

お返事が遅くなり、申し訳ありません；
例えばなのですが、STRを強化して上限値が高くなった後に、キャラクターのステータスを初期値に戻して強化し直したい時でしょうか。
（上限値というよりも、初期値と書いた方が良かったですね；　すみません；；）

**Comment by snext1220** [comment]
> ただ、今回の件でSTR等は上限値という概念がなくなりましたので、fullが候補として現れないほうがいいと思いました。

ご指摘ありがとうございます。こちらPgFlowからも削除いたしました。
ちなみに、STRが空白（0？）になるのはステータスシート側に別のバグがありましたので、修正しています。現時点ではfullで初期値に戻るようになっています。ご確認くださいませ。

> 例えばなのですが、STRを強化して上限値が高くなった後に、キャラクターのステータスを初期値に戻して強化し直したい時でしょうか。

ということで、こちらもfull指定で賄えるかと思います。ただ、名前がよくないので、実際に利用される際には今一度改定するなどして、名前はinitなどにした方がよいかもしれませんね^^;
＃ 現在もマニュアル上はfullは非推奨としています。

**Comment by cocotori** [comment]
STR等からfullがなくなっていることを確認しました。
作るときに間違いがなくなっていいと思います！

**Comment by toki-sor1** [comment]
返信が大変遅くなり、申し訳ありません；
ご対応いただきありがとうございます＆修正お疲れ様でした！

Win 8.1／Chrome 83.0.4103.116(64bit)にて動作確認。
正常に動作していました。
fullで初期値に戻ることも確認しました。

> ということで、こちらもfull指定で賄えるかと思います。ただ、名前がよくないので、実際に利用される際には今一度改定するなどして、名前はinitなどにした方がよいかもしれませんね^^; そうしたニーズがある場合はお声がけください。
＃ 現在もマニュアル上はfullは非推奨としています。

初期値に戻す場合は、こちらの方法で大丈夫そうですね。
ただ、確かにこの場合に使うのがfullというと、感覚的に違和感がありますね；
利用したいなと思った時には、すみませんが是非ご相談させてくださいませ。（非推奨も承知しました～！）

**Comment by snext1220** [comment]
> 利用したいなと思った時には、すみませんが是非ご相談させてくださいませ。

はい～マニュアル上もFull（非推奨）で残していますので、ご利用の際はなんなりと、です！
