### ISSUE TITLE
「呪い」状態時の魔法移動ボタンの挙動

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#150]
https://github.com/snext1220/stext/issues/143#issuecomment-549266144
派生のIssueです。

**「呪い」時に魔法移動ボタンも表示しない**

是迄と挙動が変化するcompati案件ですので、まずはご意見をお待ちしております。

**Comment by toki-sor1** [comment]
Issue立てありがとうございます～。
元のIssueからご返信を引用しつつ、お返事を書いてゆきますね。

> こちらは以前からの問題というか仕様というか、微妙な状態になっていました（汗

なるほど、そうだったのですか…！
今まで「呪い時に魔法は使えない」という認識から呪い時にボタンを押したことがなかったので、この前、試しに押してみて気付きました；

> ということで、こちらは呪い時にはShootボタンでエラートーストを出して魔法を実行できないよう、あらためています（GitHub Only）。

Win 8.1／Chrome 78.0.3904.87(64bit)、iPhone7／Safariにて動作確認。
両環境共に正常に動作していました！
トーストも色が違って目立ちますし、テキストも良いと思いました！

> ただ、関連して一つ問題がありまして、この問題はシーン移動時の魔法発動にもあります。
現時点では、シナリオ製作者判断ということでなにもしていませんが、実は、こちらも呪い時にはボタンが出ないように改めるべきでしょうか。

ああ～、確かにこれは悩ましいですね…。
呪いなのに、魔法に関するボタンが表示されるというのは、不自然ではありますし…；
呪い時でもボタンが表示されていれば、つい押してしまうということもありそうですし、個人的には、**可能であれば**「呪い」時に魔法移動ボタンも表示しないとした方が良いかなと思いました。

ただ、既存シナリオへの影響が大きい場合は、現状の「シナリオ製作者判断」を維持し、今後も「シナリオに呪いを採用する場合は、魔法移動ボタンの扱いに注意する」という感じでも良いと思います。

**Comment by snext1220** [comment]
ご確認ありがとうございます～

トーストのメッセージ＞問題ないとのことよかったです！ただ、今回自動化に伴い、他の箇所でも増えており、雰囲気的にはイマイチかな～と思うものもあるので^^;、テストプレイなどしながらお気づきの点があればなんなりと…！

魔法移動ボタン＞非表示一票ですね～了解です！
私も自動化するならば、それが明快だと思います！（非表示賛成派）

ただ、これ表示されないとなると、ズルしても回避できない詰みの原因となるので、ホント悩ましいです^^; （しかも、ボーナスで呪い状態になると、シナ責任でなく詰むことも；）

まあ、完全詰みもソーサリアンらしくて良いという話もありますしｗ、記憶の範囲ではそこまでクリティカルな箇所では使われていなかったような気はするのですが。STextでは、こうした詰みの仕様はこれまでなかったので、一応、も少し皆さまのご意見をお待ちしていきます～

**Comment by toki-sor1** [comment]
> トーストのメッセージ

確かにトーストは使いやすいこともあり、使用する場面が多くなってきた感じはしますね。
トーストは、ゲームでよくあるインフォメーションみたいな認識なので、統一性を持たせる意味では、このままも有りかなと個人的には思っています～。

> 魔法移動ボタン

ご賛同ありがとうございます～！
ただ、リオさんが懸念されている「呪いによるボタン非表示が原因の詰み」と「BONUSで呪い状態になるとシナ責任でなくても詰む可能性あり」は、確かに悩ましい問題ですね～…；

完全詰みもそれはそれで、という感じはしますが、STextの特徴の一つに「無敵モードでも遊べる（ズル許容）」もありますので、ここでずばっと非表示にしてしまうのは、ちょっと躊躇ってしまいますね…；

そこで無敵モードありの方針で新たな案を考えてみました。
呪い状態の場合、魔法を使用する選択肢ボタンは押せるものの、該当するボタンの色を呪いと同じ青色にする、というのはどうでしょう？（見辛いのは仕様）

実現可能かどうかは分かりませんが（汗）、これなら無敵モードも維持できますし、「呪い状態だと本来はこのボタンは押せないもの」と視覚的に訴えることもできるかな、と。

**Comment by Salvadors-cabin** [comment]
原作もそうなのでよいと思います。
「詰み」を不具合と誤解されることを防止するなら、「呪い」状態時に魔法が使えないことをルールとしてマニュアルなどに載せておけばよいと思います。

**Comment by cocotori** [comment]
・呪い時に魔法を使えない

確認しました。
わかりやすく、いいと思います。


・選択肢としての魔法

こちらも呪い時には自動で見えなくしてしまう、に賛成です。
ズルをできなくする、にも効果がありますし、
勝手に魔法が使えなくなるので
プレイヤーがルールを細かく把握する必要がなく、
プレイヤーライクだと思います。

無敵モードとしては、
STATUSで状態異常を正常にこっそり直してしまうことで
対応してもらうのはどうでしょう。

ちなみに現状は一度状態異常にしてしまうと、
手動では正常に戻せないようなのですけど
これは仕様通りですか？

**Comment by snext1220** [comment]
皆さま、ご意見有難うございました。
ご意見総合して、概ね呪い時はボタン非表示がスッキリというご意見が強そうだったので、そのように更新してまいりたいと思います（Feb予定）。

> STextの特徴の一つに「無敵モードでも遊べる（ズル許容）」もありますので、ここでずばっと非表示にしてしまうのは、ちょっと躊躇ってしまいますね…；

はい、この点、cocoさんからもご意見ありましたように、呪いを手動で解除することで一応無敵モードを維持できるので、許容と判断しました。
ただ、完全詰みとなるようなシナは、本文中でなにかしら触れておいた方が親切かもしれませんね。

> 呪い状態の場合、魔法を使用する選択肢ボタンは押せるものの、該当するボタンの色を呪いと同じ青色にする、というのはどうでしょう？（見辛いのは仕様）

こちらまさに、ステータスシートの旧仕様がそんな感じでした^^;
時間が経って半Bugのような形になってしまったので、スミマセン、こちらは今回は見送りでm(_ _)m

> 「呪い」状態時に魔法が使えないことをルールとしてマニュアルなどに載せておけばよいと思います。

こちらは、プレイヤーマニュアルの方でまとめておりますので（バトルシートの項ではありますが）、一旦はママと致しました。


> ちなみに現状は一度状態異常にしてしまうと、手動では正常に戻せないようなのですけどこれは仕様通りですか？

こちらはスミマセン、Bugですね...#157 にて改めさせていただきました。
