### ISSUE TITLE
プレイヤーマニュアルの見直し

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#151]
https://github.com/snext1220/stext/milestone/14
の対応によって、見た目に大きく変化が出ているため、プレイヤーマニュアルの見直しを実施します。

**Comment by toki-sor1** [comment]
改めて、マニュアルの更新お疲れ様でした！
DMの返信と重複しますが、現在のマニュアルの内容は、分かり易くてばっちりでした！

**Comment by cocotori** [comment]
マニュアル確認しました。
最新の情報になっていますね。
わかりやすくていいと思います。

誤字の件ですが、
攻撃の属性のアイコンごとの説明で
状態異常の忘却だけ、文章が抜けているようでした。

**Comment by snext1220** [comment]
大きな問題なく良かったです！

> 状態異常の忘却だけ、文章が抜けているようでした。

ご指摘ありがとうございました。こちらも修正済みでございます。

あとは、ルール的に曖昧なものなどご指摘戴いたところから修正していければと思いますので、お気軽にお声がけくださいませ。
