### ISSUE TITLE
各種サイドバーのデザイン（ステータスダイアログ等）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#152]
https://github.com/snext1220/stext/issues/119#issuecomment-549307869
からの継続Issueです。

機能面は一旦落ち着いてきましたので一旦Closeさせていただき、デザイン検討中心に新Issueで進めていければと。以下、前Issueからの引用です。

---

> 黒背景でややシンプルかな、という印象も受けますね。ただ、項目によっては横幅ギリギリまで文字が表示されているので、視認性を重視するなら、そのままの方が見易くて良いのかなと感じました。

は、現時点ではデザインは未対応（最小限）でしたが^^;、意外とすっきりと良いのかもしれません。今回はTemporaryということで、「機能のみのリニュ＋本格的なデザイン検討は今後」とは思っておりますが、どう進めていきましょうかね...
＃ お手数ですが、プレグラ／幕末が落ち着いたところで、ときのじさんの方でデザイン案を検討いただき、皆さんのご意見を募るという感じにできればと思っておりますが、いかがでしょうか（汗

> カラーについては、黒背景なので基本的に旧版の配色が良さそうかなと思います。
> ロゴがあると、ぱっと見の印象も豪華になりますよね。

はい～若干殺風景な気はしますので、飾りなどは各シート統一でロゴ化できるとよいのかな、とは。ただ、シンプルイズベストというご意見もありそうなので、皆様のご意見に従います！

> 縦幅の問題もありますが、個人的には「名前～JOB」までセットで表示しても良さそうな感じです。

ここは悩んだのですが、STATUSに統合すると、モバイル環境では肝心のステ情報がスクロール要になってしまいそうですね...（情報的にもほとんど利用しない名前、CLASSなどを上に配置せざるを得ないですし、却って煩わしいかも？）
で、BASICとしてわけるとすると、MEMOSとセットが分類的にも分量的にも収まりが良い、という流れでした^^;

ということで?、こちらスミマセン、確定でないにせよ、現状で一旦据え置かせていただき、慣れを見させていただいてもよろしいでしょうか（もちろん、将来再度ご意見戴いての修正は可能でございます！）

> Sound(On／Off)
> 実際に新版を触っていて、ここにすぐアクセスできないのが、ちょっと気になりました。

こちらも以前伺っていて若干悩んだのですが、「デバッグ時を除いては頻繁にオンオフするものではないかな」「STATUS、MAGICと比べると優先順位が落ちるため同列に並べるのに違和感あり？」ということで、二段目に落としておりました^^;

悩ましいですが、もう少しほかの皆様のご意見もうかがう、という感じでよろしいでしょうか？（汗
＃ もし一段目にあげるとしたら、右端にスピーカーアイコンなどを設け、他のメニュー項目とは区別した方がよいかもですね～

#### 追記

各サイドバーのスタイルを修正しました。
前のものを参考にしておりますが、一部却ってうるさくなりそうなものもあったので、シンプルめにwhiteママとしたり、若干簡単化しています。ここはこの色の方が、などあれば、ご指摘お願いします。

---

**Comment by snext1220** [comment]
#### 思いつき

Basic については悩んでいるのですが、シナリオ初回開始時に最初に開いて見せる、などもありでしょうか？

**Comment by toki-sor1** [comment]
お返事が遅くなり、申し訳ありません…！
ご返信＆新Issue立てもありがとうございました！

> ＃ お手数ですが、プレグラ／幕末が落ち着いたところで、ときのじさんの方でデザイン案を検討いただき、皆さんのご意見を募るという感じにできればと思っておりますが、いかがでしょうか（汗

了解しました～。
おそらく緩やかな進行ペースになってしまうと思うのですが、進めていければと思っています。

> STATUSについて

いえー、ご検討いただきありがとうございました！
なるほど、名前～JOBを含めると、モバイル環境だと見たい情報がスクロールしなければ見られなくなる可能性も高まりますね；
そう考えると、現状の配置は確かに収まりが良いですね。

ただ、やはり「プレイヤーキャラが自動生成」であることから、ゲーム開始時に自分がどんなキャラであるのかぱっと判りにくいというのは、ゲームという性質上、（感覚的なものかもしれませんが）気になってしまいます；

上記の理由から、リオさんが新たに挙げてくださった「（Basic については悩んでいるのですが、）シナリオ初回開始時に最初に開いて見せる、などもありでしょうか？」というアイデアはありだと思いますし、個人的には賛成です～。

> Sound(On／Off)について

> 悩ましいですが、もう少しほかの皆様のご意見もうかがう、という感じでよろしいでしょうか？（汗

こちらもご検討いただき、ありがとうございました！
はい、皆さんのご意見も伺いつつ決めていけたらと思っています～。

> ＃ もし一段目にあげるとしたら、右端にスピーカーアイコンなどを設け、他のメニュー項目とは区別した方がよいかもですね～

スピーカーアイコン化＆他のメニューと区別もいいですね！
個人的には、こちらのご意見に賛成です～。

**Comment by cocotori** [comment]
・名前～JOB

これ、悩ましいですよね・・・
前のスタイルとも変わっているので、
確かに違和感はあります。

ただ、STATUSに統合するとスクロールが
煩わしいというのもよくわかります。

場所は今のまま、Infoがいいかなと思います。
ただ、Basicというのはイメージしにくいかなと思いました。
Chara InfoとかChara Basicとか、そのまま、Name＆Jobとか。
いかがでしょうか。
枠の長さから難しさはあるかと思いますが。

あとはItem ＆ Flagは個人的には比較的確認頻度が高いので、
Infoよりはもっと外に出ているとありがたいなと思いました。
一段目を増やしたくないのであれば、
むしろMagicを二段目にしてMagic、Item ＆ Flagを並列に並べるとか？


・Sound(On／Off)について

個人的には現状でそこまで不便を感じないので大丈夫です。
アイコンはあるといいかもですね。

**Comment by cocotori** [comment]
シナリオ開始時のBasic表示は、わたしも賛成です。
現在はキャラを新規作成しました、とだけ出ますが、
どんなキャラかな、という興味はあると思うので
表示してもらうと面白いなと思います。

**Comment by snext1220** [comment]
皆さま、ご意見有難うございます！

#### デザイン進行

> おそらく緩やかな進行ペースになってしまうと思うのですが、進めていければと思っています。

色々と恐縮です；
では、こちらのIssueは一旦そのままと致しますので、ときのじさんのデザイン進行に使ってやっていただけますと幸いです。
＃他の機能面は、其々別Issueに分離し、本IssueはFeb Update以降に。

#### シナリオ開始時のキャラ情報表示

こちらはお二人の賛同を戴きましたので、Feb Updateとして対応してまいりますね。
#155 として新規のIssueを立てています。

#### メニュー構造について

ご確認有難うございます。
こちらはやはり皆さまのご意見がわかれますね。。
一部は慣れもあると思いますし、意見の整合を図った方が良さそうなので、 #156 として分離いたしました。

別IssueのものはFeb Updateとしておりますので、引き続きご意見頂戴できますと幸いです。

**Comment by toki-sor1** [comment]
> では、こちらのIssueは一旦そのままと致しますので、#117 ともども、ときのじさんのデザイン進行用に使ってやっていただけますと幸いです（不要になった場合は適宜Closeもしてやってください）。
＃他の機能面は、其々別Issueに分離し、本IssueはFeb Update以降に。

こちらこそ、ペース調整でお手数をお掛けしてばかりで、申し訳ありません；
お気遣いいただき、また、Issueの件もありがとうございます！

**Comment by toki-sor1** [comment]
大変お待たせしてしまい、申し訳ありません…！
各メニューのタイトル画像を作成しました。

- 「Chara」は、収まりの関係から「Character」にしています。
- 「Magic&STARS」は、使っているフォントの関係で「Stars」にしています。
https://onedrive.live.com/?id=4837C202555BE782%219428&cid=4837C202555BE782
![タイトルサンプル](https://user-images.githubusercontent.com/42646342/73553896-1402e400-448e-11ea-8a70-8edf80141fd2.png)

**Comment by cocotori** [comment]
かっこいい・・・！
むちゃくちゃおしゃれです。

が・・・おしゃれゆえかやや文字の内容を把握しづらいような
印象を受けました。慣れかもしれませんが。
おそらくアイコンで判断することが中心になってくると思うので、
アイコンをもう少し目立たせるとか？
もう少しだけ文字とアイコンを離すとか・・・

個人の感覚によるところかと思うので、
他の方の意見も出たところで検討してもらえればと思います。

**Comment by snext1220** [comment]
@toki-sor1 さん＞

アイコン画像ありがとうございました！
Next0401サイトのメニュー的でおしゃれですね～
早速、GitHub Pagesに反映させて戴きました！

＃ ただし、Charaはキャラ名／顔画像がタイトル代わりのようになっていたので、タイトル画像は割愛とさせていただきました（Rankと同様）。如何でしょうか？

なお、ファイルは
https://github.com/snext1220/stext/tree/master/stext/common/side
にまとめております（短くリネームしております）。もし差し替え発生する場合は、こちらからUpしてやってくださいませm(_ _)m

@cocotori さん＞

> が・・・おしゃれゆえかやや文字の内容を把握しづらいような印象を受けました。慣れかもしれませんが。

オシャレになると、どうしても可読性の問題が出てきますよね^^;
ただ、個人的には、最初にメニューから開いているので、プレイヤーも内容を把握している前提でオシャレに倒してしまってよいのかなと（＝そこまで文字を読むものでもないかな）

あと、オシャレになった分、背景黒の寂しさが際立ったように思え。なにかしら簡易な背景があっても良いかななどと。これも好み次第かもしれませんし、画面が込み入ってしまうのも良くないのですが、皆さんのご意見伺えれば幸いです。

**Comment by toki-sor1** [comment]
ココさん、リオさん、ありがたいご感想と貴重なご意見ありがとうございました～！
今までの素材よりももっと良いものを作りたいと思っていたので、お褒めいただけて嬉しいです！
（仰る通り、Next0401サイトのメニューを意識して、同じフォントを使用していました～）

> ＃ ただし、Charaはキャラ名／顔画像がタイトル代わりのようになっていたので、タイトル画像は割愛とさせていただきました（Rankと同様）。如何でしょうか？

遅ればせながら、タイトル画像の反映ありがとうございました！
そうですね、**Characterページのタイトル画像は、無しで良い思います！**
＃それに伴い、StatusとCharacterのアイコンを入れ替えました。

> が・・・おしゃれゆえかやや文字の内容を把握しづらいような
印象を受けました。慣れかもしれませんが。

> オシャレになると、どうしても可読性の問題が出てきますよね^^;

はい～、使用したフォントは格好良いものの、読み易さの点では難ありなんですよね；
メニュー選択時のフォントは読み易いので、そこで内容は伝わるかなと思ったのですが、やっぱりページの方でも内容が分かり易い方が良いですよね。
という訳で、皆さんのご意見を参考に素材を改良し、差し替えさせていただきました！

- アイコンが目立つように、アイコンの光度を調整
- アイコンとフォントの間隔を調整
- フォントを小さくし、ページ内容も追加
- 画像の透過範囲を調整

> あと、オシャレになった分、背景黒の寂しさが際立ったように思え。なにかしら簡易な背景があっても良いかななどと感じました。

まさに、タイトル画像と背景がアンバランスになってしまい、背景の寂しさが際立っていましたね；
私もそこが気になったので、右上寄せタイプで繰り返さないタイプの壁紙を作成しました！
こちらは新規素材になりますので、O/Dにアップしました。
お手数をお掛けしてしまい恐縮ですが、壁紙の反映をよろしくお願いいたします…！
https://onedrive.live.com/?id=4837C202555BE782%219428&cid=4837C202555BE782

![タイトル壁紙サンプル](https://user-images.githubusercontent.com/42646342/74104442-f3c2db80-4b97-11ea-81cb-aaa7f9e202ea.png)

**Comment by snext1220** [comment]
@toki-sor1 さん、タイトル画像＆壁紙のUpありがとうございました！
GitHub Pagesには反映済みです～

お蔭様で、各段に見栄えが改善されましたね～
ただ、私の環境ゆえかもしれませんが、壁紙が薄めで微妙に見えにくいように思えました（ホント、環境所以に思えるので、他の皆さまが気にならなければご放念ください；）

＃ もし背景濃くするようでしたら、今度はタイトル画像との重なりが気になるかもしれないので、上部分は短くする必要がある、かもしれません？（すると、縦横比でアンバランスに？？）

**Comment by toki-sor1** [comment]
早速の素材反映＆ご意見・ご感想ありがとうございます！

壁紙の濃度ですが、初回ということでかなり薄めにしていたので、ご意見いただけて調整しやすくなりました！
今回は、**濃度を10%上げて、左上の模様を黒色で削ったもの**と差し替えてみました～。
また、ファイル名を間違えていたタイトル画像も、微調整した画像とあわせて差し替え済みです。

＃ただ、ページ内容（実績、魔法など）の漢字がサイズの関係で潰れてしまい、何か他の用語を当てられないものかと悩んでいます；
![image](https://user-images.githubusercontent.com/42646342/74212929-2117a280-4cda-11ea-92ca-4d3e5f46da85.png)

**Comment by snext1220** [comment]
早速のご修正ありがとうございます！
濃度、削除範囲共に、当方環境では程よく見えており、良いと思います～

潰れ、については悩ましいですね...
魔法は呪文、カナ表記マジックックなど、実績はカナ表記リザルトなどで置き換えもできますが、他と表記がずれてしまうのも良くないですし；個人的には、英語表記と合わせて十分に判読できるのでママでも、などとは^^;

**Comment by toki-sor1** [comment]
こちらこそ、ご確認ありがとうございます！
修正内容は問題なかったようで安心しました～！

フォント潰れについてもご意見ありがとうございます！
デザイン的にもあまり大きなフォントにし辛いこともあり、本当に悩ましい限りですが、そうですね、表記がずれてしまうと違和感がありますもんね；
それに、仰る通り英語表記と合わせれば判読可能な範囲かなと思いますので、**今のところはこのままでいこうと思います**（調整が必要になれば調整する感じで）。

**Comment by cocotori** [comment]
サイドバーレイアウト、確認しました。
とてもおしゃれでかつわかりやすく、ステキなデザインになったと思います。

黒い画面によく映えますね！
