### ISSUE TITLE
Flagシートで隠しフラグが表示される

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#153]
Ｄで @toki-sor1 さんより報告戴いていた問題ですが、こちらに移動いたしました。

> 動作確認で、どうやら隠しフラグが隠れていないようです～

失礼しました；
サイドシート移行時にダウングレードしてしまっていたようです。。
GitHub／本番環境共に修正させて戴きました。
ご確認くださいませm(_ _)m

**Comment by toki-sor1** [comment]
修正お疲れ様です！
GitHub／本番環境ともに隠しフラグが隠れているのを確認いました！
早急にご対応いただきありがとうございました！
