### ISSUE TITLE
実績の合計数が実際の設定を超過している

### ISSUE THREAD

**Issue by toki-sor1** [snext1220/stext#154]
私の環境のみの問題かもしれませんが、Player Rankやサイトに表示される実績の合計数で **「ラミディアの魔法使い」だけ、実際の合計値を超過して「8／3」と表示されてしまいます。**

![image](https://user-images.githubusercontent.com/42646342/68545081-e0736900-040c-11ea-8cb4-c0976c9f9edc.png)

![image](https://user-images.githubusercontent.com/42646342/68545092-f41ecf80-040c-11ea-9cb4-3add7fc0b185.png)

全シナリオのバックアップ（https://1drv.ms/u/s!AoLnW1UCwjdIzE-U9_w2X5jZHpUh?e=uGIrvs ）を取ったところ、下のようになっていました。
```
"ramidia":["r09","r01","r02","r05","r04","r03","r06","r07"]
```
これが原因だと思うのですが、何故そうなってしまったのかがどうにも分かりません；
もしこちらの環境のみの問題であれば、どのようにすれば正常な合計数を表示させることができるのでしょうか？

＃ゲーム進行には支障のない問題なので、後に回していただいて大丈夫です！
お手数をおかけしてしまい申し訳ありませんが、お手隙の際によろしくお願い致します。

**Comment by snext1220** [comment]
ご連絡ありがとうございます！

こちら現時点ではよく判らないのですが、以前のテストシナリオが同じくramidiaだったので、その時のデータが残っている、、、、のかもしれません（確信はなし；）
当面の応急処置としては、お手数ですが、該当箇所を以下のようにしていただいた上で、リストアして戴くと正しくなるかと。

```
"ramidia":["r01","r02","r03"]
```

手元でもramidia見てみますが、原因不明となるかもしれず、スミマセン...＞＜

**Comment by toki-sor1** [comment]
なるほど、以前のテストシナリオの名残（？）かもなのですね！
早速、教えていただいた方法をサイトとGitHub両方で試してみたところ、今度は3／3と正常に表示されるようになりました！
お忙しいところ、ご回答ありがとうございました！！

> 手元でもramidia見てみますが、原因不明となるかもしれず、スミマセン...＞＜

いえいえ、こちらこそお手数をおかけしてしまい申し訳ありません…！
一応問題は解決しましたので、もしまた同じような表示になりましたら、その時はまたご連絡致しますね。
