### ISSUE TITLE
シナリオ初期開始時のキャラ情報表示

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#155]
#152 由来のIssueです。

サイドバー設置でキャラ情報が見えにくくなったことから、
**シナリオ初回開始時に最初にBasicシートを開いて見せる**
ように改定いたしました（GitHubのみ反映済）。

**Comment by toki-sor1** [comment]
iPad  Pro、Safariから動作確認。
正常に表示されました。
今まで自分のキャラがどんなキャラなのか、ぱっと分かりにくかったので、今回の仕様変更はとても良いと思います。

**Comment by cocotori** [comment]
確認しました。
キャラのグラフィックも表示されるので、いいですね。
感情移入が進みます。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで確認いたしました。
問題ありません！
