### ISSUE TITLE
トップメニューの構造

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#156]
#152 由来のIssueです。

引き続きトップメニューの構造について議論してまいります。

#### Soundメニュー

**第一階層に格上げし、右端にアイコンとして表示する。**

こちらは、凡そのご賛同が得られたように思えるので、対応していきたいと思います。

@toki-sor1 さん＞ お手数ですが、スピーカーON/OFFのアイコン（2種類）を制作戴いても宜しいでしょうか。サイズは30x30くらいでしょうか（ただ、必須ではなく、メニュー欄に収まれば、あとは他とのバランス次第かなと思っております）。

#### Item＆Flagsの位置

> あとはItem ＆ Flagは個人的には比較的確認頻度が高い

ご要望有難うございます。以下の理由から、個人的にはママにできればという意見ですが、引き続き皆さまのご意見を戴けますと幸いです。

+ カテゴリー的にもInfoの範囲なのでまとめたい
+ できれば一段目を増やしたくない（本来の目的がこれだったので）
+ これまでもステータスシートを開いてからの切り替えだったので、階層としては以前と同様

> むしろMagicを二段目にしてMagic、Item ＆ Flagを並列に並べるとか？

こちらはスミマセン、よく理解できていないのですが、Item＆Flagをそのままに、Magicを二段目に落とすというご意図でしょうか？
＃Magicについては、 @toki-sor1 さん（でしたっけ？）から一段目が望ましいというご要望がありましたので、現在の状態になっておりました（一段目に操作系を残しておきたいという意味もあり）。

この辺、結構それぞれで優先するものが異なりそうなので^^;、ご要望伺いながら2人以上の賛成で移動していければと思っています。

#### Basicメニューの名前

> Chara InfoとかChara Basicとか、そのまま、Name＆Jobとか。

Infoという表記が上位メニューとも重なるので、単に「Chara」または「Character」では如何でしょうか。

**Comment by cocotori** [comment]
・Item & Flagのイメージ

イメージとしては、

-Status

-Item
--Magic(STARS)
--Item & Flag

-Info

というようにmagicとitem&flagの階層を
揃えるという意味での発言でした。
その場合1階層目を何にするか悩ましいですが、
魔法も、星という所持品から発動することになるので、
広義のitemと思い1階層目をitemにしてあります。

あくまでイメージですので、こうしろ、というものではないです。


・Basic
Chara、いいですね。
わかりやすく簡潔だと思います。

**Comment by toki-sor1** [comment]
> スピーカーON/OFFのアイコン（2種類）

![sound_on](https://user-images.githubusercontent.com/42646342/71767610-51d52100-2f51-11ea-87d9-e99bdbb53b3b.png)　![sound_off](https://user-images.githubusercontent.com/42646342/71767611-54d01180-2f51-11ea-8aed-28b88e5c499c.png)

大変お待たせしました；
こちら、作成致しました。O/Dにアップ済みです。
サイズや色合いなどは、バランスを見て、必要とあれば微調整致します。
https://onedrive.live.com/?id=4837C202555BE782%216765&cid=4837C202555BE782

> Magicについては、 @toki-sor1 さん（でしたっけ？）から一段目が望ましいというご要望がありましたので、現在の状態になっておりました（一段目に操作系を残しておきたいという意味もあり）。

私も記憶があやふやなので改めての意見になりますが（汗）、Magic（STARS）はシナリオによっては使用頻度が高いものなので、一階層目の方がアクセスし易く、ストレスなく操作できるかなという感じはします。

> 魔法も、星という所持品から発動することになるので、広義のitemと思い1階層目をitemにしてあります。

なるほど～。原作でも装備品を選択して、その装備品に掛けられた星の力に応じて魔法を発動させているので、MagicとStarsをItemに含めるのも原作再現的な意味で良い感じがしますね！

ただ、良いと思う一方で、気になるところもあります。
Magicはシナリオによっては手動操作が多くなりますが、Item & Flagはどのシナリオでも自動で処理されるものなので、操作の優先度から見ると、一階層目のMagicをItem & Flagと同じ二階層目に移す利点が、ちょっと少ない感じもしました。

> Basicメニューの名前

「Chara」または「Character」表記、いいですね！

**Comment by Salvadors-cabin** [comment]
>Item＆Flagsの位置

いろいろ考えてみましたがどれも一長一短あり、私の意見としては現状維持とさせていただきます。

>Basicメニューの名前

「Character」への変更に賛成です。

よろしくお願いしますー

**Comment by snext1220** [comment]
皆さま、ご意見ありがとうございます！
ご意見まとめまして、以下のように一旦結論してまいりたいと思います～（対応はMarch）

#### Item＆Flag

一旦据え置き。
cocoさんよりご意見ありましたが、ときのじさん、サルバさんママとのことで、現時点では（個人的にも、ときのじさんの「一階層目の方がアクセスし易く～」に賛成で）。
勿論、この辺実際に利用していく中で「やはり気になる」というのもあると思いますので、様子見ながら、またお気づきの点はご意見お聞かせください。

#### Basicの名称

Charaで修正してまいります。

#### Soundについて

@toki-sor1 さん＞アイコンありがとうございます！こちらにて実装していきますので、少々お待ちを～（背景色との関係で「×」のカラーなど調整お願いさせて戴く、かもしれませんが、その際は宜しくお願いいたします～）

**Comment by snext1220** [comment]
以下件対応し、GitHub Pagesのみ反映済みです！
改めてアイコンの作成有難うございました＞ @toki-sor1 さん

+ Basicの名称変更
+ Soundの階層変更＆アイコン化

**Comment by toki-sor1** [comment]
お返事が遅くなり、申し訳ありません！
ご対応ありがとうございました！

> Basicの名称変更

すみません、前回どっちつかずな意見を書いてしまったのですが（汗）、表記変更後のバランスを見た印象だと「Character」表記の方が収まりが良いかな（＋見慣れている）と感じました；
（タイトル画像作成中にも、見た目の問題でCharacter表記にしていました；）

> Soundの階層変更＆アイコン化

Soundアイコンですが、前Verは目がちかちかしたのと、×色が要調整のようでしたので、文字色と同じ白に変更してみました。
https://onedrive.live.com/?id=4837C202555BE782%219428&cid=4837C202555BE782
![image](https://user-images.githubusercontent.com/42646342/73552835-4a3f6400-448c-11ea-9ae3-6fc096ef8ecb.png)

**Comment by cocotori** [comment]
・Basic

Character、OKです！問題ないと思います。


・Soundの階層変更＆アイコン化

すぐに切り替えられるようになって、使いやすくなったと思います。
色も、白一色のほうがスッキリしててよいのではないかと思います。
話題のフラットデザイン。オサレ。

**Comment by snext1220** [comment]
@toki-sor1  さん

> 「Character」表記の方が収まりが良いかな（＋見慣れている）と感じました；

了解です！
最初は文字数短い方が良いという判断だったのですが、より長いものもありますので、非省略の方が良さそうですね～

> Soundアイコンですが、前Verは目がちかちかしたのと、×色が要調整のようでしたので、文字色と同じ白に変更してみました。

こちらもありがとうございました。最新版で差し替え済みです！
＃ 位置については、実は下にずらすとバーそのものが若干下部にはみ出てしまう?ので、現状の位置になっていました；調整試みますので、、とりあえずスミマセン。。

@cocotori さん

> 色も、白一色のほうがスッキリしててよいのではないかと思います。
> 話題のフラットデザイン。オサレ。

同感です！
