### ISSUE TITLE
ステータスシートから状態異常を正常に戻せない

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#157]
https://github.com/snext1220/stext/issues/150#issuecomment-562915369 でご指摘戴いた件の修正です。

> ちなみに現状は一度状態異常にしてしまうと、手動では正常に戻せないようなのですけどこれは仕様通りですか？

こちらサイドシート化に伴うバグでしたので、修正し、反映いたしました（GitHub Only）。
ご指摘ありがとうございます。

**Comment by cocotori** [comment]
確認しました。状態異常から、正常に無事戻りました。

**Comment by toki-sor1** [comment]
Win8.1／Chrome 79.0.3945.88(64bit)にて動作確認。
こちらも正常に戻すことができました。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで確認いたしました。
問題ありません！
