### ISSUE TITLE
playground flowで、リンクが全て消えることがある

### ISSUE THREAD

**Issue by cocotori** [snext1220/stext#158]
playground flowを使用しているときの不具合報告です。

何かの作業のきっかけで、
今まで作っていた矢印（リンク）が全て消えてしまうことがあります。

何がきっかけかよくわからず、
同じ事を繰り返しても再発しないこともあり、
現象の特定ができていません。

おそらく、ノードの追加・削除、リンクの追加・削除、
リンクやノードの名前変更あたりがきっかけになっているのではないかと
推測しますが。

保存にも似たような不具合があるようで、
フロー図上はリンクがあるようにみえても、
保存したあとのファイル（xml）にはリンクが残っておらず、
再びflowで読み込むとリンクが全て消えてしまっています。

発生頻度はそれほど高くないのですが、
長いシナリオを作っていると結構な回数遭遇し、困っています・・・

時間があるときに確認してもらえれば助かります。

ブラウザはgoogle chromeで確認しています。

**Comment by toki-sor1** [comment]
私も「暗き沼」執筆の際に、同じような症状が1回だけ出たことがありました。
シナリオ執筆中は余裕がなく、シナリオ公開後に報告する予定であったにもかかわらず、失念しておりました……ご迷惑をお掛けしてしまい、大変申し訳ありません；

Win8.1／Chrome 79.0.3945.88(64bit)にて動作確認。
当時のことを思い出して試していたところ、下記の手順で再現できました。

1. リンク（矢印）を選択後、「Delete Selected」で削除
2. どれかの適当にSceneを選択後、そのSceneをバッドエンドに指定する
3. リンク全て吹っ飛び（リンクが消えた状態で、Sceneが横並びになる）

![不具合](https://user-images.githubusercontent.com/42646342/71718781-a5674200-2e5f-11ea-9b5f-30e3784c34ab.PNG)
![不具合２](https://user-images.githubusercontent.com/42646342/71718782-a5674200-2e5f-11ea-906e-5712d2439e31.PNG)

**Comment by cocotori** [comment]
リンクが消えてしまう問題ですが、再発したのでコンソールのエラー情報を載せておきますね。

![クリップボード](https://user-images.githubusercontent.com/42885160/72219236-2a043f80-3587-11ea-8c28-4e986c696290.png)

再現性もあるようなので、そのときのファイルも添付します。

[scenario (3).zip](https://github.com/snext1220/stext/files/4050668/scenario.3.zip)

1 scenarioンクが消えてしまう問題ですが、再発したのでコンソールのエラー情報を載せておきますね。

![クリップボード](https://user-images.githubusercontent.com/42885160/72219236-2a043f80-3587-11ea-8c28-4e986c696290.png)

再現性もあるようなので、そのときのファイルも添付します。

[scenario (3).zip](https://github.com/snext1220/stext/files/4050668/scenario.3.zip)

1 scenario (3).xmlをplayground flowで読み込む
2 id16→id27のリンクを削除する（矢印名：蜂の巣を揺さぶる）。

すると、リンクが選べないおかしな状態になる
（矢印をクリックすると、マップも一緒に動いてしまう）。
この状態で、

3 シナリオを保存でxmlを保存すると、全リンクが消えてしまっています。


問題解決に役立てばよいのですが。
よろしくお願いします！

**Comment by snext1220** [comment]
お時間戴いておりましたが、本件確認しまして、GitHub Pagesにも反映済みです。
改めてバグのご報告ありがとうございました。
お手数をおかけしまして恐縮ですが、ご確認戴けますと幸いです～

**Comment by toki-sor1** [comment]
Win8.1 Chrome 79.0.3945.130(64bit)にて動作確認。
```
1. リンク（矢印）を選択後、「Delete Selected」で削除
2. どれか適当にSceneを選択後、そのSceneをバッドエンドに指定する
3. リンク全て吹っ飛び（リンクが消えた状態で、Sceneが横並びになる）
**※追記：ハッピーエンド指定でもリンクが消えました**
```
```
1 scenario (3).xmlをplayground flowで読み込む
2 id16→id27のリンクを削除する（矢印名：蜂の巣を揺さぶる）。

 すると、リンクが選べないおかしな状態になる
（矢印をクリックすると、マップも一緒に動いてしまう）。
この状態で、

3 シナリオを保存でxmlを保存すると、全リンクが消えてしまっています。
```
上記2パターンをテストし、報告されていた不具合が再現されないことを確認しました。
修正お疲れ様でした！

**Comment by cocotori** [comment]
直っていました！
ありがとうございます。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで問題ないことを確認しました！
