### ISSUE TITLE
BattleSheetの機能拡張

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#160]
#159 でリクエストいただいた件の議論用Issueです。

---

一件応募させていただきます。

・リクエスト概要
　「BattleSheetの機能拡張」です。

・用途
　戦闘システムの自由度を拡張することを目的としています

・仕様
　下の画像の①～⑥の機能を変更にしてほしいという要望です。

![BattleSheet2](https://user-images.githubusercontent.com/42834363/73122363-698b4c80-3fc7-11ea-8872-d60fa619e2f4.png)

①表示内容をカスタマイズ可能に。
②Free欄の数値を表示。ボタン押下時に更新、再表示。
③攻撃アイコンをクリックしたときに計算式実行。（例：敵のHP(Free欄)を減算）
④表示スペース縮小の為に計算式表示はやめ、「盾」のようなアイコンに変更。（計算機能は今のまま）
⑤戦闘ルールの文章表示。
⑥イラスト表示。

データの方は、enemyカテゴリに追加してはどうかと思います。
以下のような例です。
<enemy id="m01" name="こうもり" element="" attack="" func="" drop="" ①bar="名前／属性　　HP" ②value="free1" ③damage="free1" func1="L+R+FREE3" ⑤rule="特別ルールhogehoge" ⑥image="hoge.png">

※互換性維持のため、①～⑥を設定しない場合は従来表示。
※①⑤⑥は複数の敵が同時に出現する場合は最初の敵のを有効。

これはもともと「ラミディア」の戦闘システム自動化を考えていたときに思いついたアイデアですが、自由度が広がれば他のシナリオでも利用できると思います。

・UIイメージ
　「ラミディア」を例にすると以下のようなイメージになると考えています。

![BattleSheet3](https://user-images.githubusercontent.com/42834363/73122368-7314b480-3fc7-11ea-89d3-8078ef311e74.png)

※複数敵が登場するとFree欄が敵の数だけ必要になります。ラミディアでは問題無いですが、将来的にはFree欄の拡張も必要になるかもしれません。

検討いただけたら幸いです。

_Originally posted by @Salvadors-cabin in https://github.com/snext1220/stext/issues/159#issuecomment-578409274_

**Comment by snext1220** [comment]
リクエストありがとうございます！
こちらは #95 で戴いていた内容の発展的な内容ですね。
以下、現時点での意見をまとめます～

#### ①表示内容をカスタマイズ可能に。

こちらは「名前／属性」のみカスタマイズ、というご意図でしょうか？
＃ それとも攻撃、ダメージ、戦利品、すべて？

できれば合わせておいた方がプレイヤーも把握し易いかなと思ったのですが、どんな状況で使われるご予定でしょうか？

実装する場合は、enemies要素にelement-name属性、attack-name属性などを設けて、シナリオ一括で名前を差し替えるような形になりそうです。

#### ②Free欄の数値を表示。ボタン押下時に更新、再表示。

ページ内でのみ有効な情報でしょうか。
であれば、enemy要素にhp属性（敵HP）、enemy-attack属性（敵攻撃用の計算式）で自動計算、という感じで対応できそうです。
＃ enemy-attackの方は良い命名が思いつかない...

＃ Freeは個数が制限なくなりそうなので、避けておきたく^^;

#### ③攻撃アイコンをクリックしたときに計算式実行。（例：敵のHP(Free欄)を減算）

こちらは②次第で要検討ですね～
現在の［攻撃］欄が敵の攻撃属性を意味するので、一寸直観的ではないかも。

#### ④表示スペース縮小の為に計算式表示はやめ、「盾」のようなアイコンに変更。（計算機能は今のまま）

計算式から戦術を決めていた人もいるように思えるのですが、如何なものでしょうか？
＃ どちらにせよ、上のenemy-attack属性（計算式）を表示する余白がすでにないのですが^^;（以前も出ましたが、そもそも2行化が必要になるかも）

#### ⑤戦闘ルールの文章表示。

#136 の機能で代用できるかなと思われ、こちら是非利用してやってください～

#### ⑥イラスト表示。

複数の場合は、先頭のものを優先するイメージですかね～
ただ、魔物を複数sceneで利用している場合、一律表示されてしまうと五月蠅い、かも。となると、これまでのscene画像で賄って戴いた方が自由度もありそうですが、如何なものでしょうか。

まずは、ざざっとまとめておりますが、引き続きよろしくお願いいたします！

**Comment by Salvadors-cabin** [comment]
お返事ありがとうございますー

>①表示内容をカスタマイズ可能に。
>こちらは「名前／属性」のみカスタマイズ、というご意図でしょうか？

あいまいな指定で申し訳ありません。
これは「名前／属性」の右に「HP」などの行を増やしたいという意図でした。
「名前／属性」をカスタマイズ可能にすれば、その行を伸ばして「HP」などの追加ができるかな、と考えたのです。

>＃ それとも攻撃、ダメージ、戦利品、すべて？

こちらの変更は特に希望はしていないです。

>できれば表記は合わせておいた方がプレイヤーも把握し易いかなと思ったのですが、どんな状況で使われるご予定でしょうか？

HPなどの敵モンスターのパラメータを表現する目的です。

>②Free欄の数値を表示。ボタン押下時に更新、再表示。
>ページ内でのみ有効な情報（＝セーブデータに保存の必要がない情報）でしょうか。

そうです。セーブデータには保存しなくてよいと思います。

>であれば、enemy要素にhp属性（敵HP）、enemy-attack属性（敵攻撃用の計算式）で自動計算、という感じで対応できそうです。
>＃ enemy-attackの方は良い命名が思いつかない...
>＃ Freeは個数が制限なくなりそうなので、避けておきたく^^;

その方が実装しやすいのであれば、やりやすい方でお願いいたします。
命名はenemy-attackかenemy-damageでしょうかね・・・

>③攻撃アイコンをクリックしたときに計算式実行。（例：敵のHP(Free欄)を減算）
>こちらは②次第で要検討ですね～
>現在の［攻撃］欄が敵の攻撃属性を意味するので、一寸直観的ではないかも。

確かに敵への「ダメージ」なのか敵の「攻撃」なのかは直感的ではないですね・・・
特別ルールのシナリオで使用する予定なので、そのあたりはルール表示で説明したいと考えています。

>④表示スペース縮小の為に計算式表示はやめ、「盾」のようなアイコンに変更。（計算機能は今のまま）
>計算式から戦術を決めていた人もいるように思えるのですが、如何なものでしょうか？

私としては戦闘に至るまでのストーリー展開で戦闘の有利・不利を決めたいので、式を隠したいケースはあります。（有利や不利の極端な式が表示されているとネタバレor理不尽な気持ちになる）
戦術についてはシナリオごとの特性になると思いますので、式を表示するかアイコン表示にするか、選べられるようにしたいという要望です。

>＃ どちらにせよ、上のenemy-attack属性（計算式）を表示する余白がすでにないのですが^^;（以前も出ましたが、そもそも2行化が必要になるかも）

私としては計算式表示は不要でアイコン表示で表示を詰めて１行におさめたいという希望です。

>⑤戦闘ルールの文章表示。
>#136 の機能で代用できるかなと思われ、こちら是非利用してやってください～

すでに存在したのですね！
試用させていただきました。
この機能で問題無いと思います。ひとつ要望を申し上げると「閉じる」ボタンの上に説明文を配置したいのですが・・・

>⑥イラスト表示。
>複数魔物/sceneの場合は、先頭のものを優先するイメージですかね～
>ただ、魔物そのものを複数sceneで利用している場合、一律表示されてしまうと五月蠅い、かも。
>となると、これまでのscene画像で賄って戴いた方が自由度もありそうですが、如何なものでしょうか。

そうですね。sceneごとの画像でよいと思います。
⑤#136の文章表示は特別なscene(99999など)を利用する仕組みになっていると思いますが、99999などのsceneで画像を設定した場合にBattleSheetに文章と共に表示される予定はないでしょうか。（今は表示してない、ですよね）
これなら敵モンスターに関わらずsceneごとに表示する・しないのコントロールも可能になると思います。

よろしくお願いしますー

**Comment by snext1220** [comment]
ご回答ありがとうございます！

#### ①表示内容をカスタマイズ可能に。

> これは「名前／属性」の右に「HP」などの行を増やしたいという意図でした。

了解です！
であれば、enemy要素にhp属性がある場合にHP列を追加のみで大丈夫そうですね～

#### ②Free欄の数値を表示。ボタン押下時に更新、再表示。

> その方が実装しやすいのであれば、やりやすい方でお願いいたします。

了解です！
セーブデータはできるだけ増やしたくないので、hp実装の場合には
**ページ内のテキストボックスに値を表示＋自動計算結果の反映**
で進めていきたいと思います。

#### ③攻撃アイコンをクリックしたときに計算式実行。（例：敵のHP(Free欄)を減算）
#### ④表示スペース縮小の為に計算式表示はやめ、「盾」のようなアイコンに変更。（計算機能は今のまま）

> 戦術についてはシナリオごとの特性になると思いますので、式を表示するかアイコン表示にするか、選べられるようにしたいという要望です。

こちらはcompati案件になるので、皆さまのご意見待ちとさせてくださいm(_ _)m
hpを表示の制御位であれば、なんとかワンソースで制御できるのですが、
+ HP表示の有無
+ 式 or アイコン表示
+ 上記に伴い、1 or 2行表示
は入ってくると、コードもパターン別に管理しなければならないので、後々のメンテを考えると、できれば避けたく；
＃ 以前の #95 も議論が止まってしまったのはここだったので、汎用的な統一レイアウトをまとめられるかがポイントになってきそうです。

#### ⑤戦闘ルールの文章表示。

> この機能で問題無いと思います。ひとつ要望を申し上げると「閉じる」ボタンの上に説明文を配置したいのですが・・・

こちら現状は、特別ルールはそれなりに長くなるケースがあること、複数ページで表示する場合、大して見ないケースも多くなることから、［閉じる］ボタンはスクロールなしで押せる場所に配置しておりました。

#### ⑥イラスト表示。

> ⑤#136の文章表示は特別なscene(99999など)を利用する仕組みになっていると思いますが、99999などのsceneで画像を設定した場合にBattleSheetに文章と共に表示される予定はないでしょうか。（今は表示してない、ですよね）

サイドバーの性質上、あまり大きなコンテンツを詰め込みたくない、という思想で、現在は画像は対応予定なしでございます；画像は基本、メイン領域に配置いただくと助かりますが、如何なものでしょうか。

---

とりあえず現状、

+ ③が最大の課題（ご要望＋アイデア募集）
+ ⑤、⑥は他の皆さまのご意見も伺いつつ、多数の場合に対応
+ ①、②は内容的にはクリア（対応は③次第）

といったところでしょうか。
戦闘周りはリリース当初からの課題で、私も汎用的な戦闘シートを、とは思っているのですが、システムへの影響も大きく、しかも後からの建て増しも難しい処なので、引き続きご意見交換しつつ、詰めさせてくださいm(_ _)m

**Comment by Salvadors-cabin** [comment]
検討ありがとうございます。
互換性を維持しながら、というのがなかなか難しそうですね。

>0227追記

そうですね。
私としては①～④がぜひ実装して欲しい機能で、⑤⑥は可能であれば欲しい機能だったので、要件はほぼ満たされていると思います。
この案が現実的と思います。

>②Free欄の数値を表示。ボタン押下時に更新、再表示。
>ページ内でのみ有効な情報（＝セーブデータに保存の必要がない情報）でしょうか。

申し訳ないです。前の書き込みで「セーブデータには保存しなくてよい」と書いたのですが、よく調べたところ場面によっては敵HPを次のシーンに引き継ぎたいケースもありました。（例えば「ラミディア」のディオールは２シーンまたぎで戦闘が続く）
HP欄にFree欄の内容をセットする（HP欄が減ったときFree欄も同時に減る）オプションも用意していただけないでしょうか。

**Comment by snext1220** [comment]
> 私としては①～④がぜひ実装して欲しい機能で、⑤⑥は可能であれば欲しい機能だったので、要件はほぼ満たされていると思います。この案が現実的と思います。

ご了承ありがとうございます。
コア機能のため、実装そのものは他の皆さまのご意見を待ってからとなりますが、まずは、この方向ベースで議論していければと思います。

> 申し訳ないです。前の書き込みで「セーブデータには保存しなくてよい」と書いたのですが、よく調べたところ場面によっては敵HPを次のシーンに引き継ぎたいケースもありました。（例えば「ラミディア」のディオールは２シーンまたぎで戦闘が続く）
> HP欄にFree欄の内容をセットする（HP欄が減ったときFree欄も同時に減る）オプションも用意していただけないでしょうか。

ラミディアのディオール戦を確認してみました（enemies属性がm4、m5のscene）。
こちらに限れば、ディオールをhpがゼロになったところでscene移動しているので、hpの保存は不要に思われるのですが、如何でしょうか。

幾つかの理由から、できればhpとfreeN欄の連携は避けたいと思っていまして（絶対やらないという意味ではなく、やるなら汎用性を持たせたいという意図です）、要件を伺いながら、最適解を導き出せればと。引き続きよろしくお願いいたします。

**Comment by cocotori** [comment]
①表示内容をカスタマイズ可能に。
②Free欄の数値を表示。ボタン押下時に更新、再表示。

賛成です。敵にHPが設定され、より戦略的になると思います。


③攻撃アイコンをクリックしたときに計算式実行。（例：敵のHP(Free欄)を減算）
HP列をボタン＆クリック可能に（HPを自動計算＆値反映）

賛成です！
func_oppで構いませんが、
func_atkとかはどうでしょうか。


④表示スペース縮小の為に計算式表示はやめ、「盾」のようなアイコンに変更。（計算機能は今のまま）

計算式は可能ならば残しておきたい派ですね・・・


⑤戦闘ルールの文章表示。
⑥イラスト表示。

現状の機能でまかなえるのではないかと考えています。

**Comment by Salvadors-cabin** [comment]
>ラミディアのディオール戦を確認してみました（enemies属性がm4、m5のscene）。
>こちらに限れば、ディオールをhpがゼロになったところでscene移動しているので、hpの保存は不要に思われるのですが、如何でしょうか。

敵HPのシーン間引継ぎが必要なのはシーン1303です。

![1303](https://user-images.githubusercontent.com/42834363/76100367-e02c5880-600f-11ea-9f74-36a70b00abaa.png)

ここでやりたい事は、敵の攻撃でプレイヤーのMPが削られ、MPが0になったらHPを減らすという戦闘です。
この目的の為にattack属性がmagicのm5とphysicsのm4を用意し、m5でMPを削られた後にm4を登場させる事で「プレイヤーのMPが0になったらHPを減らす」を実現しています。
シーン1303はm5の登場シーンで、ここで敵のHPが0になる前にプレイヤーのMPが0になった場合は、(敵の残りHPを記録し次へ)という操作が必要になります。これが敵HPのシーン間引継ぎです。

ちょっと話がそれますが、目的が以上の事なので敵HPを引き継がなくても以下の別案のどちらかを実装していただければ実現できそうです。
別案1:attack属性に「MPが0以上のときはMPを減らし、MPが0のときはHPを減らす」という特別な属性を実装していただく。
別案2:計算式に「MPが0以上のときはMPを減らし、MPが0のときはHPを減らす」という表現ができる式を実装していただく。

ややこしい話ですみません。
よろしくお願いしますー

**Comment by toki-sor1** [comment]
### ①表示内容をカスタマイズ可能に。

良いと思います！

### ②Free欄の数値を表示。ボタン押下時に更新、再表示。

今までは「計算式のダメージに耐えられれば敵を倒したことにする」という表現が主だったので、敵ステータスに直接HPが設定できるのは、よりゲーム的で分かり易いですね。
良いと思います！

### ③攻撃アイコンをクリックしたときに計算式実行。（例：敵のHP(Free欄)を減算）

> HP列をボタン＆クリック可能に（HPを自動計算＆値反映）

（hp属性設定時のみ）HP列追加＋ボタン追加によって、敵の攻撃なのか自分の攻撃なのか分かり易くなって良いと思います！

> func_atkとかはどうでしょうか。

atkの方が見慣れている（意味が分かり易い）ので、こちらを推します！

### ④表示スペース縮小の為に計算式表示はやめ、「盾」のようなアイコンに変更。（計算機能は今のまま）

計算式は「こいつは強いから優先的に斃そう！」みたいに判断することがありますし、ネタバレ防止を取るか、遊びやすさを取るか悩ましいですね。

計算式非表示の代わりに、**計算式は設定するけど、Secretと表示して計算式を見えなくする**というのは、難しいでしょうか？

### ⑤戦闘ルールの文章表示。
### ⑥イラスト表示。

バトルシートの戦闘ルール表示機能と本文にイラストを表示させることで、こちらはまかなえると思いました。
***
### 敵HPのシーン間引継ぎ

素人考えで実装の可否や工数のことは分からないのですが（汗）、

 - ディオールのデータを2つ用意する（ディオールAとディオールB）
 - 1回戦目のディオールAのHPを、2回戦目のディオールBに引継ぐ新たなhp属性を実装する
    - ディオールBのHPにディオールAのid属性＋scene数を指定し、残りHPを引継ぐ

という上記の指定は、可能なのでしょうか？

**Comment by snext1220** [comment]
本件、ご意見有難うございます！
凡そご賛同得られたと思うので、実装の方向で動いてまいりますね。
実装前に最終仕様はまとめてまいりますが、以下、現時点でのペンディングです。何度もお手数ですが、ご意見戴けますと幸いです。

#### 敵HPのシーン間引継ぎ

> 別案1:attack属性に「MPが0以上のときはMPを減らし、MPが0のときはHPを減らす」という特別な属性を実装していただく。

システム的には上記が影響最小化できそうです。
ただ、
**STextの基本ルール（HP、MPいずれかがゼロでゲームオーバー）から逸脱する独自ルールを標準システムに組み込むべきか**
という点で悩んでいます。
＃経緯を知らない開発者にとっては仕様を把握しにくくなるもとになるため（「あれ、HP（MP）ゼロでもいいんだっけ？」的な）。

これ単体ですとそれほどではないのですが、大概一例作ってしまうと、後々雪崩れてカオスになるのはよくあるので、もし例外を作るならば慎重にしていきたく...；

> ディオールBのHPにディオールAのid属性＋scene数を指定し、残りHPを引継ぐ

こちらはスミマセン、残りhpをセーブデータに保存という形になるので、以前のコメと同じ問題が出てきてしまいます；（＝不可能ではないが、ここだけの独自実装になるので避けたい）折角のご提案にも関わらず申し訳ありません。。。

#### 計算式表示について

少なくとも「標準は計算式表示」で据え置きの方が良さそうですね～
ご提案のfunc属性をsecret表記は大丈夫だと思います（1レイアウト内での条件分岐の範囲に収まりそうです）。おそらくfunc属性が「@～」で始まる時に非表示、のようなルールになるのかなと…！

#### 属性名（敵攻撃の計算式）

そうなんですよね。
enemy_atk（enemy_attack）の方が単語としては馴染みやすいんですよね...
ただ、atkですと「敵**による**攻撃か、敵**への**攻撃」なのかが不明瞭のため、あとで混乱のもとになるかと避けておりました^^;
で、苦肉のoppだったわけですが、如何なものでしょうか（汗

### まとめ？

+ hp／func_opp属性は**名前が同意され次第**、実装を進めていければと思います。
+ attack属性の拡張については、恐縮ですが、今少し議論できればとm(_ _)m

**Comment by snext1220** [comment]
試験的にenemy要素にhp、func_opp属性を追加しました（GitHub Pagesでのみ）。
属性指定時にBattleSheetにHP表示がされるようになっています。

**Comment by Salvadors-cabin** [comment]
>STextの基本ルール（HP、MPいずれかがゼロでゲームオーバー）から逸脱する独自ルールを標準システムに組み込むべきか

「オプション機能」という扱いがよいのではないかと思います。

**Comment by toki-sor1** [comment]
> STextの基本ルール（HP、MPいずれかがゼロでゲームオーバー）から逸脱する独自ルールを標準システムに組み込むべきか

ご懸念されているとおり、プレイヤーのルール把握で混乱を招きかねないので、**標準システムに組み込まない方が良い**と思います。

ただ、シナリオの表現を拡げる意味では、**オプション機能で組み込むというのも有りかな**と思いました。

> ディオールBのHPにディオールAのid属性＋scene数を指定し、残りHPを引継ぐ

ご返信ありがとうございました。お返事が大変遅くなり、申し訳ありません…！

いえいえ、独自実装は、工数の問題でも避けたいものですものね。
承知しました。こちらの案は、**取りやめということで**よろしくお願いいたします。

> 試験的にenemy要素にhp、func_opp属性を追加しました（GitHub Pagesでのみ）。

Win8.1／Chrome 81.0.4044.122(64bit)にて動作確認。
敵HPが表示されているのを確認しました。

ダメージは、どちらも固定で2と表示されて0以下にはなりません。
また、プレイヤーがダメージを受けた際の情報は、再読み込み後も維持されていましたが、敵HP情報は保存されていないようでした。

こちらは試験導入ということで、現状での仕様でしょうか。

**Comment by cocotori** [comment]
・HP,MPの独自計算ルール
そうですね、標準システムとしては
組み込まないほうがいいと思います。

オプションとした場合にどう実装するか悩みどころですが・・・
こういった例外的な機能は、
オプションとしてまとめておいて、
タグ等で指定しない場合は無効になるという感じで。

シナリオ作者さんはその機能を理解していなくても、
未設定であれば無効になるので、
ひとまず影響はでない、といった仕組みにできると
いい感じでしょうか。

・func_opp属性
経緯もわかりましたので、
この名前で問題ありません！

**Comment by snext1220** [comment]
ご意見ありがとうございます！

> オプション機能

こちらは悩ましいところです。
というのも、STextの機能はほとんどがオプション（＝使っても使わなくても良い）なので。
＃ scene要素を除くすべての要素、属性が未設定でもシステムは動作します。
ドキュメント上、これだけをあえてオプションと明記＆区別するのも却って混乱を招くような気がします。

また、今回気にしたのが **シナ固有の仕様で、システムルールに矛盾するものをシステムに反映させるか** でして；（これまでは、こうした機能にはシスは関与しないが基本思想でした）
改めて「他シナでも利用するか」を確認させていただいた方がよいかと思っております。

以前の繰り返しになってしまいますが、例外的なルールは、ドキュメント（仕様）を分かりにくくしますし、システムを複雑にしてしまう（＝バグの原因ともなる）＆改定負荷が高まるため、System側としては避けた方がよいという意見です。。（単体であればよいのですが、大概重なっていくのが問題化と）

と、否定的な意見が続いてしまいましたが（スミマセン）、一般的なニーズがある場合には自由度を高めるのは良いことだとは思っていまして。本件、導入する場合は、システムとして仕様を決めてしまった方がよいかなと。たとえば、以下の通りです。

+ ゲームオーバー条件は「HPのみ0」「HP/MP双方0」「それ以外」から選択可能にする
+ ゲームオーバー条件を満たしたときにトースト表示する（毒のケースも入ってくると思います）


ただ、無敵モードへの対応、セーブデータへの反映を考えると、地味に中規模以上の改定となるため、お手数ですが、汎用性についてご意見頂けますと幸いですm(_ _)m

＃余談：PgFlowが高機能になってきたため、システムとPgの同期（二重開発）が想定以上に工数の増加に繋がっているという事情も、正直無視できなくなってきています；伴い、気軽でスピーディな対応が段々難しくなってきていますが、まだまだ進化はさせていきたいと思っていますので、引き続きおつきあいくださいませ。

その他、バグ?報告については改めて確認いたしますので、少々お待ちください；；

**Comment by Salvadors-cabin** [comment]
>ただ、無敵モードへの対応、セーブデータへの反映を考えると、効果の割には大きな改定となるため、お手数ですが、汎用性（＝自シナで利用するか）について今一度ご意見頂けますと幸いですm(_ _)m

私が言い出しっぺなのでアレですが次作は「ラミディア」ルールで考えています。（要するにHP＝0でゲームオーバー）

「オプション」については言葉の選択が悪くすみませんでした。大きな仕様変更（ルール変更）を意図した訳ではなく「隠し機能」ぐらいのイメージで考えていました。
ただ、他Issue(#175, #176 など)でSTextの一般化、自由度アップの方向性が上がっていましたが、その方向であれば、HP=0でゲームオーバーというのもルールとしてあってもよいのではないかと思います。

**Comment by toki-sor1** [comment]
今までのシナリオでもありましたが、基本的に特殊ルールの扱いは、

- シナリオ内でシナリオ固有の特殊ルールであると提示する
- 汎用性があまりない特殊ルールは、（手間ではあるが）既存のシステムで再現する
  - 例）MPが0になったらHPを減らす場合
  - MPへの攻撃とHPへの攻撃の2種類を用意
  - MPが0かどうかは、プレイヤーに判断してもらい、攻撃を切り替えてもらう

というのが**プレイヤー／クリエイターの混乱を招かない現実的な落としどころ**かなと思いました。
***
>  ゲームオーバー条件は「HPのみ0」「HP/MP双方0」「それ以外」から選択可能にする
>  ゲームオーバー条件を満たしたときにトースト表示する（毒のケースも入ってくると思います）

ゲームオーバーについては、下記の対応が良いかなと思いました。

  - ゲームオーバー条件は、シナリオ内で提示＋プレイヤーに判断をゆだねる
  - **ルール関係なく**HPやMPが0になった場合にトースト表示
     - 「HPが0になってしまった！」だけでも良いですし、更に追加で「ゲームオーバー条件となっている場合は、君はここで力尽きたことになる。」等のメッセージも入れてもいいかも？
***
@snext1220 さん＞
> バグ?報告についてありがとうございます。以下回答いたします。

お返事が遅くなってしまい恐縮ですが、ご回答ありがとうございました！
固定ダメージについては設定がそのようなっているから＆HP0以下にならないのは仕様によるものだったのですね、承知しました！

**Comment by snext1220** [comment]
> 今までのシナリオでもありましたが、基本的に特殊ルールの扱いは、～～

私も基本、その方針、に賛成です。
仕様のシンプルさという意味で隠し機能は避けたく、システム改定の負荷を抑えるという意味でも汎用性のある（ありそうな）機能からの対応とさせていただけますとm(_ _)m

重ねてですが、一般化、自由度Upの方向性に舵は切っているので、STextとしてニーズが高いのであれば、ゲームオーバー条件の自由度を上げることそのものは反対ではありませんです。今回は他の皆様からも「使いたい」ニーズが出なかった＆地味に影響が大きい、などからrejectとさせていただけますとm(_ _)m

> ルール関係なくHPやMPが0になった場合にトースト表示

そして、これが地味に影響が大きいという理由の一つだったりします；というのも、HP/MPゼロでゲームオーバーであれば話が早いのですが、いわゆる「無敵モード」の存在があり、ゲームオーバー条件を無視してゲームを続けられなければならないという。これゆえに、トースト表示済みかをセーブデータに持たせなければならず、互換性に影響が出てしまうのです...（実は忘却系の問題もこの辺が絡んでいます）

もちろん、できなくはないのですが、影響の割に大して効果がないのかな～という意見だったりします^^;（自動計算時に現在のHPなども出るのでプレイヤー的には気づかないという状況はあまりないかなと、勝手に） 如何でしょうか？（汗

**Comment by cocotori** [comment]
ちょっとどういう方向性に持っていけば
わからなくなってきてしまいましたが、

わたしの方では、

・ゲームオーバー条件は「HPのみ0」「HP/MP双方0」「それ以外」から選択可能にする
・ゲームオーバー条件を満たしたときにトースト表示する（毒のケースも入ってくると思います）

が必要になってくるシナリオは今の所考えていないです。
あってもいいかと思いますが、修正の影響が大きいようでしたら
見送りでも構いません。

**Comment by snext1220** [comment]
皆さま、ご意見ありがとうございます。
現時点では修正ニーズが限定的である点、修正規模等からattack属性の設定値追加、ゲームオーバー条件は見送ってまいります。ご提案戴いたのに申し訳ありません；

ただ、セーブデータを動かしにくい問題については、今後も課題なので、継続して検討進めてまいります（新しいブラウザーでは比較的楽に実装出来はするのですが；）。attack＆ゲームオーバーについても今後ニーズの変化によっては引き続き議論できればと思いますので、必要に応じてお声がけください。
