### ISSUE TITLE
シナリオ紹介ページに投票フォーム設置

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#161]
#159 でリクエストいただいた件の議論用Issueです。
議論の中で、対応の可否を決めていければと思います。是非ご意見をお願いいたします。

---

STextはシナリオへの反応が、プレイヤー側・作者側ともに分かり辛く、ゲームが遊べるサイトにもかかわらず、関係者以外の気配がないのも課題かなと思いました。

> リクエスト概要

「シナリオ紹介ページに投票フォーム設置」

> 用途

- 紹介ツイートする、RTするといった反応はハードルが高い。シナリオへの反応・応援のハードルを下げる目的
- プレイヤーさんに対し、「他のプレイヤーさんの存在」を明確にする
- 投票項目に「ストーリー」「キャラクター」など設定することで、シナリオ内でどの要素が好まれているのか分析する

> UIイメージ

- Twitterのような投票フォームをシナリオ紹介ページ下に設置（画像参照）

![image](https://user-images.githubusercontent.com/42646342/73365062-ffd4b080-42ee-11ea-8b06-243b70b6f51e.png)

_Originally posted by @toki-sor1 in https://github.com/snext1220/stext/issues/159#issuecomment-579785491_

**Comment by snext1220** [comment]
リクエスト有難うございます！

こちらは以前から度々話題に上がっていたユーザーフィードバックについてですね。
＃ リクエストについては、SText本体だけでなく、Pg、サイト幅広くで大丈夫なので、ご安心ください～

類似の機能としては、以前コメント投稿機能などいくつか案が出て、一度廃案になっておりましたので、まずは要否を議論していければと。以下は、現時点での懸念事項です。

#### 対応規模

Twitterのアンケート機能（＆埋め込み）ですと、期限が短いので、今回の要件には足りないかも（使ったことがないので、認識間違いあればご指摘ください～）。フリーのアンケートウィジェットがあればよいのですが、今のところ「これ！」というものがなく、もしよさげなものがあれば是非お願いします。
＃ ただし、こちらはシナ追加都度の個別対応になると思います。

もし自作する場合には、データの管理方法からの検討になるので、stext.xmlまで巻き飲んだ微妙に大きめな対応になりそうです（一度作ってしまえば、色々は場は広がると思うのですが；）。

#### 利用程度＆内容

以前のコメント投稿の時も話に出ましたが、ひたすら利用程度が懸念でしょうか。
初期の誘い水は要検討です。

その性質上、ネガティブなフィードバックは出にくいかと思いますが、特定のシナに投票が偏るなど気にされる方はいる、でしょうか？（個人的には、この辺は割り切りとは）

#### まとめ？

ユーザーフィードバックは魅力的なので、私もそれ単体ではすごく賛成なのですが、開発規模を押さえられるならば or/and 他の優先順位の高い機能と合わせての対応であれば、といったところでしょうか。
＃ スモールスタートという意味では、まずは適当なウィジェットがあるのが前提、といった感じ？

あとは、亜案としては、個別シナのアンケートではなく、

+ SText全体に関するアンケート（選択式でもコメントでも）を設けて回答結果も公開していく（＝一般的なアンケートフォームであれば、それなり既存サービスがありそう）
+ Twitterアンケートで王さまbotからミニアンケートを取っていく＆サイトに埋め込み

などもあり、でしょうか。

一寸否定的な見解になってしまい恐縮ですが、頻々と類似リクエストがでるということは、 根強くご要望があるということかと思いますので、原案に限らず、良い形で昇華させていければ良いですね。

**Comment by toki-sor1** [comment]
リクエストについてご回答ありがとうございます！
ご寛大なお言葉をいただき、ホッとしました…！

> 対応規模

はい、形こそはTwitterのアンケート機能をイメージしていましたが、回答期限のないものが良いですね。
探してみたところ、「Googleフォーム」が埋め込みにも対応しているようでした。

- Googleフォーム（https://www.google.com/intl/ja_jp/forms/about/ ）
- 自作サンプル（https://forms.gle/PkYSAyR5z3QWnP4t9 ）
- 解説サイト様1（https://prebell.so-net.ne.jp/tips/pre_19060401.html ）
  - 埋め込む方法（https://prebell.so-net.ne.jp/tips/pre_19060401.html#sub_03-2 ）
- 解説サイト様2（https://hep.eiz.jp/how-to-use-google-form/ ）
  - カスタマイズについて（https://hep.eiz.jp/how-to-use-google-form/#sec4 ）

> 利用程度＆内容

利用程度は、なかなか予測し辛いところがありますね。
ただ、上記フォームはサイト内に組み込めるようなので、目立ちやすいところに設置できるという利点があると思います。

誘い水として、王さまbotからの告知は必須かなと思います。

確かに、投票の偏りはあり得ることですね。
匿名投票ではあるものの、「気にされる方もいらっしゃる」という前提で設置や内容を検討してゆく必要はありそうです（私は回答があればもちろん嬉しいのですが、偏りは気にしない派です）。

> まとめ？
> SText全体に関するアンケート（選択式でもコメントでも）を設けて回答結果も公開していく（＝一般的なアンケートフォームであれば、それなり既存サービスがありそう）

なるほど、シナリオのこと以外にも気になるところがありますから、シナリオだけにこだわることもなさそうですね。
SText全体に関するアンケート＆回答結果の公開も良いと思います。

> Twitterアンケートで王さまbotからミニアンケートを取っていく＆サイトに埋め込み

実はクイズのような感じで、王さまbotからアンケートを取ろうかなと考えていたこともありました。
ただ、自分がそこまで手が回るかどうか不安だったので、保留としていました；

しかし、SText全体に関するアンケートなど、お題があれば試験的にやってみるのもありかもしれませんね。

いえいえ、ご検討いただき、本当にありがたいです！
それに、何でも導入すればよいというものでもないですし、工数のことや今後の運営方法など、色んなことも関わってくるので、慎重な見方やご意見はとても大事だと思っています。
お忙しいところ恐縮ですが、引き続きよろしくお願いいたします。

**Comment by snext1220** [comment]
早速のお返事＆アドバイスありがとうございます！

Googleフォーム＞はい～私もこの辺検討してみたのですが、実は、以下の点が気になっておりました（説明不足で申し訳ありません；；）。

+ 結果が別ページ表示（アンケート回答済みでないと確認できない）
+ 回答制限をかける場合はGoogleアカ前提
+ シナリオ追加時にアンケート作成は都度手動

暫定版をStaffページ末尾に追加しています～（半日程度で削除します）
https://www.web-deli.com/sorcerian/text/staff.aspx
こちら、もちっと調査してみますね。

**Comment by snext1220** [comment]
改めてリクエスト有難うございました！
昨晩お返事後回しになっていた箇所＋αにてコメント致しますね。

> 上記フォームはサイト内に組み込めるようなので、目立ちやすいところに設置できるという利点があると思います。

はい、シナリオごとの場合は、ご提案戴いたようにサイドメニューになるかと思いますが、プレイ開始前に反応から内容を確認できるのは魅力的だと思います！

あとは、Googleフォームとした場合、先コメントのような制限はあるので、この辺、どこまで許容範囲になるか、ですね。現時点で、運用面では、（どうせシナリオ公開時に手動で反映しなければならないのであれば）アンケートの有無はシナリオ作者さん各位にお任せもありかなと思っています。

各位でアンケートを作成し、scenario.xmlにアンケートid（埋め込みURL末尾の長い英字）を指定した場合にはアンケートが反映されるイメージです。その場合は質問項目も自由に設定できますので、シナリオに応じて適切な設問を設置できそうです（もちろん、コメント欄も）。
＃ 見た目の問題もあるので、最低限のルールは決めておいた方が良さそうですが。

> 誘い水として、王さまbotからの告知は必須かなと思います。

はい～あとは、最初の登録／コメは結構勇気も要りそうなので、互いのシナリオ交換で投票＆（ある場合は）コメを登録するのもあり、かも？

> 実はクイズのような感じで、王さまbotからアンケートを取ろうかなと考えていたこともありました。ただ、自分がそこまで手が回るかどうか不安だったので、保留としていました；

継続的に、となると、中々しんどいですものね；お察しします。
ただ、単発でも、もし宜しければやってやってください～
＃ まだクイズのような～のイメージは沸いてませんが^^;

それで始まる何かもある＆モノによっては私の方で肩代わりできるものもあるかと思いますのでｗ3年目になってきて、基盤は整ってきたので、議論なくても思いつきでやってみるは全然ありかと個人的には。

とったアンケートはTwitter埋め込みで履歴的に残していけば、時間と共に数も増えてきそうですし、サイトの賑やかしにもなるかと…！

**Comment by toki-sor1** [comment]
こちらこそ、早速のお返事＆フォームのテスト反映ありがとうございました！

> - 結果が別ページ表示（アンケート回答済みでないと確認できない）

こちら、私もやや気になりました；
理想は、回答結果が投票前から確認できるものが良いのですが、フォーム埋め込み式となると候補が限られるんですよね；
Googleフォーム採用の場合、**ここは割り切りも必要かもしれません。**

> - 回答制限をかける場合はGoogleアカ前提

はい、1回の投票につき1項目のみ選択可能、というのはできるのですが、投票回数を制限する場合は、Googleアカが必須なんですよね；
それだと流石にハードルが上がってしまうので、Googleフォーム採用の場合は、**投票数は回答者様のご判断にお任せ**になりそうですね。

> - シナリオ追加時にアンケート作成は都度手動

> アンケートの有無はシナリオ作者さん各位にお任せもありかなと思っています。

こちら、関連する内容をまとめて返信致しますね。
なるほど、仮にアンケートを設置したとして、手動反映であれば作者さんごとにアンケートを設置するか否かを選べますものね。
**各位にお任せもありだと思います！**
***
> 各位でアンケートを作成し、stext.xmlにアンケートid（埋め込みURL末尾の長い英字）を指定した場合にはアンケートが反映されるイメージです。～

**こちらのイメージともぴったりです！**
質問項目を自由に設定できるのも楽しいですね～。
回答者側としても、今回はどんな質問があるのかとお楽しみが増えそうですｗ

> ＃ 見た目の問題もあるので、最低限のルールは決めておいた方が良さそうですが。

はい、**最低限のル－ル決めは必須**だと思います。
***
> 最初期は、互いのシナリオ交換で投票＆（ある場合は）コメを登録するのもあり、かも？

**ありだと思います！**（寧ろその方が良いかなと！）
シナリオを作る作者であると同時に、シナリオで遊んでいるプレイヤーでもありますもんね～。

> 継続的に、となると、中々しんどいですものね；お察しします。
ただ、単発でも、もし宜しければやってやってください～
＃ まだクイズのような～のイメージは沸いてませんが^^;

ひぃん、ありがとうございます…！
アンケートの内容はまだですが、まずはTwitterで告知から始めてみました！
早速の引用RTありがとうございました！
＃ クイズは「基本シナリオ『消えた王様の杖』でオークに盗まれてしまったのは、この内のどーれかのぅ？」みたいなノリをイメージしていましたｗ

> それで始まる何かもある＆モノによっては私の方で肩代わりできるものもあるかと思いますのでｗ3年目になってきて、基盤は整ってきたので、議論なくても思いつきでやってみる（やってしまった）は全然ありかと個人的には。

お気遣いいただき、ありがとうございます～！
そうですね、今までも「思いつきでやってみる（やってしまったｗ）」というのはありましたし、始めてみなければ分からないこともありますもんね～。
現在は告知のみですが、賑やかしの意味でもアンケートやクイズなど挑戦してみたいと思います～。

**Comment by snext1220** [comment]
諸々のお返事ありがとうございました。
割り切りありとの件も了解＆賛成です！
アンケートの有無もシナリオごとに決められれば、作者さん毎の判断にも委ねられるので、しくみ導入のハードルは下がりそうですね。

ということで、他の皆さまの賛否を確認した後、 **積極的反対がなければ** 導入の方向で考えていければと思います～

現時点での課題もまとめます。

---

#### 設置場所

+ メイン領域は邪魔なので、サイドバー前提とは。
+ ただ、現在の［冒険に出発する］シートはいっぱいなので、メイン領域から（アンケートのあるシナリオのみ）［詳細を表示］の隣に［アンケート］ボタンを表示して、別のサイドバーを開くような形になるのかなと思っています。
    + その場合、スミマセン、［アンケート］ボタンは（場所節約のため）縦横h25xw30？程度のアイコンをご相談させて戴けますとm(_ _)m
+ スマホでの問題はpx設定によるものと思われるので、本格実装の際には%設定にして改善できればと思っています～

####  最低限のル－ル決め

以下のような感じですかね～

+ アンケのタイトルは省略できないので、タイトル「シナリオ名 アンケート」、リード文「プレイされた方、アンケートに是非ご協力ください！」で統一（リード文は適当なので、ご希望あればなんなりと）
+ 設問は複数設置可能だが、スクロールを避けるため、基本は1～2個（最大でも3個に留める）

#### 設置時期

サイトデザインのリニューアルに合わせた方が二度手間は防げそうですが、ときのじさんのご都合いかがでしょうか（そもそもScenarioページに手を入れない場合は、本件先行しても大丈夫です！）

---


> 現在は告知のみですが、賑やかしの意味でもアンケートやクイズなど挑戦してみたいと思います～。

アンケートもありがとうございました！
早速、回答もあり、ワクワクしながら拝見しています～
こちらもサイトに埋め込み反映させていきたいですが、となると、［About］ページ（＝トップページ？）も整理していかないと、ですね。この辺もサイトデザインの動きと足並み併せていければと思っています～

**Comment by toki-sor1** [comment]
> 他の皆さまの賛否を確認した後、 積極的反対がなければ 導入の方向で考えていければと思います～

はい、私は異存ありません！
***
#### 設置場所
> メイン領域は邪魔なので、サイドバー前提になるかと考えています。

はい、良いと思います！

> ［アンケート］ボタンは（場所節約のため）縦横h25xw30？程度のアイコンをご相談させて戴けますとm(_ _)m

作ってみました！（色が違うのみ・黒と青の2種類）
アンケートを英語表記にすると、あまり馴染みのない表現になってしまったので、分かり易く「アンケート」と表記しました。
https://onedrive.live.com/?id=4837C202555BE782%219428&cid=4837C202555BE782
![questionnaire_black](https://user-images.githubusercontent.com/42646342/74604056-7d752a80-50fd-11ea-8d09-c412e0c02e77.png)　![questionnaire_blue](https://user-images.githubusercontent.com/42646342/74604057-8239de80-50fd-11ea-84d7-f5946b94eb33.png)

> できれば一か所でまとめて見られるのが良いのはそうなので、別アイデアあれば是非に！

- 個人的には、**サイドバー設置＋アンケートボタン案が良いかなと思いました。**
- もし一か所にまとめるのであれば、**サイト内にアンケート専用の新たなページを作り、シナリオ詳細ページとリンクさせて、そこから専用ページに飛べるようにする**というのは如何でしょう？

#### 最低限のル－ル決め

こちら、2つのご意見ともに異存ありません！

#### 設置時期
> サイトデザインのリニューアルに合わせた方が二度手間は防げそうですが、ときのじさんのご都合いかがでしょうか（そもそもScenarioページに手を入れない場合は、本件先行しても大丈夫です！）

こちら、大幅に遅れていて申し訳ありません…！
#117 を改めて確認しているのですが、おそらく素材も多くなりそうなので、**いつ頃に全ての素材が揃うかがちょっと分からない状況**です；

そのため、お手数をお掛けしてしまい申し訳ありませんが、**本件先行**が良いかもしれません；
***
> アンケートもありがとうございました！
早速、回答もあり、ワクワクしながら拝見しています～
こちらこそ、アンケートのRT等にご協力いただき、ありがとうございました！
初めての試みでドキドキしましたが、皆様にご回答いただいたり、ファボやRTでも反応いただけたりと、良いスタートを切れたかなと感じました！

> こちらもサイトに埋め込み反映させていきたいですが、となると、［About］ページ（＝トップページ？）も整理していかないと、ですね。この辺もサイトデザインの動きと足並み併せていければと思っています～

上記の意見と重なりますが、アンケートのみで一つのページが作れる内容になりそうなので、［About］を［Utility］と同じく2階層（？）にして「Questionnaire」という新たなページを作るのも良いかも、と思いました。

＃「みんなのソーサリアン Text」は、その他2項目と毛色が違う印象なので、［About］＞［SORCERIAN Text］・［Special］・［Questionnaire］と分けてしまうとか？
もしくは、［Gallery］を［Special］に変更して、［Special］＞［Gallery］・［Questionnaire］に？

**Comment by snext1220** [comment]
早速のアイコンありがとうございます！
とりあえず暫定でアンケートページを設けてみました。

> もし一か所にまとめるのであれば、サイト内にアンケート専用の新たなページを作り、シナリオ詳細ページとリンクさせて、そこから専用ページに飛べるようにするというのは如何でしょう？

まずは暫定で、サイドバーから［アンケート］ボタンを追加しています（アイコンはメイン領域の方で利用いたしますので、現在は未使用でございます。暫定ということでご容赦を...）。上のご意見に近い形にしたつもりですが、イメージ合っていますでしょうか？？

stext.xml（ https://github.com/snext1220/stext/wiki/GitHub%EF%BC%8FFTP%E3%81%AE%E9%81%8B%E7%94%A8 ）にquest属性を指定することで表示されるようになります。現在拙作の3作でアンケートを有効にしていますので、宜しければご自分のシナでもお試しください。

**Comment by Salvadors-cabin** [comment]
遅くなりましたが正式リリース後のゲストさんへの連絡、了解です。
よろしくお願いします。

**Comment by cocotori** [comment]
アンケート機能の追加、ありがとうございます。
ユーザーさんの声を受け取る一つの貴重なきっかけになると思います。

ルール、レイアウトも、今のもので問題ありません！

わたしも、徐々に利用させてもらおうと思います。

**Comment by toki-sor1** [comment]
＞ @snext1220 さん
改めて、アンケート実装ありがとうございました！
アイコンの問題や、回答結果がすぐに見られないなどの問題もありましたが、DMで迅速にご対応いただいたことで、どちらも解決することができてとても助かりました！

アンケートのル－ルもまとめていただき、こちらもありがとうございました～！
おかげさまでスムーズにアンケートを設置することができました！

サイトの見た目などの問題が出てきた時のルール追加も承知しました！
正式リリース後のwikiまとめなど、お忙しいところ大変恐縮ですが、よろしくお願いいたします…！

＞ **皆さん**
今までなかなか良い落としどころが見付からず、流れていた意見でしたが、この度、リオさんのご協力を得て、ようやく念願叶いました！
そして、温かなお言葉もいただけて、安心すると同時にとても嬉しく思いました！
皆さん、ありがとうございました！
これから様々なアンケートが見られる日が楽しみです！

＞ @Salvadors-cabin さん
お任せしてしまって申し訳ありませんが、正式リリース後のお知らせをよろしくお願いいたします！

**Comment by snext1220** [comment]
@toki-sor1 さん＞
こちらこそありがとうございました！
長年?の懸案が一応の解決を見て、ほっとしています～プレイヤーさんの声をひとつでも広い、作者さんには執筆の士気向上に繋がればよいですね…！

@Salvadors-cabin さん＞
お忙しいところ恐縮ですが、正式リリースのご通知をよろしくお願いいたしますm(_ _)m
（基本ルールは簡単ながら以下にまとめております）

皆さん＞
アンケートルールについては、wikiにまとめております。
あまり複雑にする気もないのですが（基本作者さん個々にご自由に、というスタンス^^;）、不足の点があれば何なりとご指摘ください。
https://github.com/snext1220/stext/wiki/GitHub%EF%BC%8FFTP%E3%81%AE%E9%81%8B%E7%94%A8#quest%E5%B1%9E%E6%80%A7%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E3%82%A2%E3%83%B3%E3%82%B1%E3%83%BC%E3%83%88%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0
