### ISSUE TITLE
Playground 終了時の警告

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#162]
#159 でリクエストいただいた件の作業用Issueです。

---

playgroundを使っていて感じたことなのですが、
未保存でページを離れることに対する警告が出せたらいいなと思いました。

こまめな保存に気をつければいい話なのですが、
ついうっかり保存する前にブラウザを落としちゃった、
という事態もどうしても発生すると思うので。

ブラウザに自動で一時保存できれば一番いいのかもしれませんが、
そこまでできなくても警告が出るだけでもいいかと思います。

_Originally posted by @cocotori in https://github.com/snext1220/stext/issues/159#issuecomment-580991647_

**Comment by snext1220** [comment]
リクエストありがとうございます！

仰る通り、誤操作に対するワンクッションはあった方が良さそうですね。
こちら互換性の問題もありませんし、比較的小規模に対応できるかと思いますので、PgEditor／Flow双方に改定進めていきたいと思います。

今のところ、未保存警告の方向でおりますが、対応はコード見ながら検討とさせてくださいませ。

**Comment by toki-sor1** [comment]
Win8.1 Chrome 79.0.3945.130(64bit)から動作確認。
警告文が正常に表示されました。
誤操作によるデータ消失を防ぐ良いアイデアだと思います！

**Comment by cocotori** [comment]
確認しました。
ついうっかりがなくなり、使いやすくなったと思います。

**Comment by Salvadors-cabin** [comment]
お疲れ様ですー
Win10+Edgeで確認しました。
問題ありません。
