### ISSUE TITLE
経過シーンがカウントアップされない

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#163]
Statusシートの経過シーン数がカウントアップされない。
サイドシート更新に伴うバグでしたので修正し、GitHub Pagesに反映済みです。

**Comment by toki-sor1** [comment]
Win8.1 Chrome 79.0.3945.130(64bit)から動作確認。
閲覧履歴などを消去してテストしましたが、GitHub版も経過シーンがカウントアップされず、0のままでした。

![image](https://user-images.githubusercontent.com/42646342/73610419-5822ef80-461a-11ea-96ba-5cbb73622184.png)
![image](https://user-images.githubusercontent.com/42646342/73610436-86083400-461a-11ea-8596-41b4a428988b.png)

**Comment by snext1220** [comment]
早速のご確認有難うございました。
そして、失礼しました！＞＜;

手元のデータがGitHubにPushできていなかったようで；
先ほどPushし直しました～（お手数をおかけして申し訳ありません；）

**Comment by toki-sor1** [comment]
いえいえ、ご確認とご対応ありがとうございました！お疲れ様です！
iPhoneから動作確認。今度は正常にカウントアップされていました！

**Comment by snext1220** [comment]
夜遅くまでありがとうございます！
まずは問題なしとの事、了解でございます～

＃ 大きな改定行うと、思わぬところでダウングレードが発生してしまうのが悩ましいですね...

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで確認しました。
問題ありません。

**Comment by cocotori** [comment]
経過シーンがカウントされることを確認しました。

ただ、ステータス異常の忘却と石化は、
必要シーン経過してもステータスが正常に戻ったり死亡したりしませんでした。

前に伺った気もしますが、
このあたりの仕様ってどうなっていましたっけ？

経過シーンの発生するステータス異常は、
経過シーンをカウントするのみでその後のアクションはしない、
という仕様であればこれでOKです。

**Comment by snext1220** [comment]
> ただ、ステータス異常の忘却と石化は、
> 必要シーン経過してもステータスが正常に戻ったり死亡したりしませんでした。

現時点ではカウントのみで以降のアクションは自己責任という仕様です。

というのも、STextでは「死亡」という状態を持っていないためでして。
所謂無敵モードを許容するのが目的です。

ただ、自動化がここまで進んでいるので、

+ 石化：死亡通知（あくまでトースト表示のみ）
+ 忘却：自動回復

はありかもしれませんね。こちらお手数ですが、ご意見いただければ幸いです。

**Comment by toki-sor1** [comment]
> 石化：死亡通知（あくまでトースト表示のみ）
忘却：自動回復

状態異常の処理は、うっかり忘れやすいですね。
トースト表示や自動回復などでフォローしていただけると、うっかりミスが防止できて良いかなと思いました。

**Comment by Salvadors-cabin** [comment]
>石化：死亡通知（あくまでトースト表示のみ）
>忘却：自動回復

これをもし実装するなら「毒」のHP:0でも死亡通知が欲しいなと思いました。

**Comment by cocotori** [comment]
そうですね、シーン経過が関係するステータス異常

毒、石化はトーストによる死亡通知
忘却は自動回復

してくれるとありがたいと思います。

**Comment by snext1220** [comment]
ご賛同ありがとうございます。
こちらも実装の方向で進めていきたいと思います。
以下、現時点で想定している仕様です。

+ 忘却：自動回復。経過シーンもゼロクリア
+ 石化：死亡通知（トースト表示のみでstateのクリア、経過シーンのクリアは**行わない**）
+ 毒：#160 とも絡むため、改めさせていただきます。

いわゆる無敵モードに対応させるため、忘却／石化の扱いに差が出るが若干気になりますが、如何なものでしょうか。

**Comment by cocotori** [comment]
忘却：20ターンで自動回復、経過シーンのゼロクリアを確認しました。

しかし、ゼロクリアするのがその次のターンのような動きをしますが、
それであっていますでしょうか？

例えばなんですけど、自動回復したそのシーンに、
敵の攻撃などで再度忘却になってしまうと、ゼロクリアできずに
20,21...と永遠にカウントアップしてしまう事象が起きてしまいました。
こうなると、たとえ40シーン目でも自動回復することはありませんでした。

確率的にはとても低いとはおもうのですが、
おかしな状態に落ち込んでしまってもとに戻らない現象なので、
できれば対応したいなと考えています。


石化：30シーンで死亡通知が出ることも確認しました！

**Comment by toki-sor1** [comment]
Win8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
石化、忘却ともにカウントされていました。
無敵モード対応も良いと思います。

> 忘却：20ターンで自動回復、経過シーンのゼロクリアを確認しました。
しかし、ゼロクリアするのがその次のターンのような動きをしますが、
それであっていますでしょうか？

私の環境でも同じ条件で同じ挙動をしていました。
（永遠とカウントアップする、40シーン目でも自動回復しないのも確認）

忘却の場合、**20シーン目になった時点でカウントが0に戻り、自動回復する仕様**であれば大丈夫そうなのですが、それは難しいでしょうか？

**Comment by snext1220** [comment]
ご指摘ありがとうございます。
こちらちっとトリッキーな動きではあるのですが、20sceneで解除＆カウント0で対応いたしました。如何でしょうか。

お手数ですが、ご確認戴けますと幸いです。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
忘却時、20scene目で解除＆カウント0になることを確認しました。

今度は永遠とカウントアップすることもなくなりましたし、トーストで20scene目だということが分かるので現在の仕様が良いと思います！

【余談】
（無敵モード前提ですが）石化死亡後に忘却になり、20scene経過した場合、石化カウントも0になっていました。
無敵モードであればカウントが0になっても特に問題はなく、こういうケースは無敵モード以外では有り得ないのですが、念のために。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

余談＞はい、仰るように、基本的に無敵モードの場合はカウントは気にしていないはずなので、ママでいければと～（状態異常は重複しないので、石化解除の時点でゼロクリアになってしまうのですよね...）

**Comment by cocotori** [comment]
chromeで確認しました。
20シーン目で0になり忘却が解除されました！
