### ISSUE TITLE
Playground Flowで、作ったはずのリンクが消える？

### ISSUE THREAD

**Issue by cocotori** [snext1220/stext#164]
こちらの現象、おや？と思ったので挙げさせてください。
ただ、わたしの勘違いの可能性もありますので
もう少し様子を見させてください。

--

flowにてノードとリンクを作り、xml保存をします。
次回、xmlよりロードをしたとき、
作ったはずのリンクが数個消えているような気がしました。

おそらく最後の方に追加したリンクですので、
単にわたしの保存し忘れなのかもしれません。
また発生するようならご連絡します。

ふと思ったのですが、
わたしは同じノードに複数のリンクを作るとき、
手動で並び順を設定しないことが多いです。
（ツールが勝手に割り振るのに任せている。
　修正したいときだけ、振り直す。）
それは使い方としてあっているでしょうか？

それによって番号がかぶっておかしくなる等の問題があるようでしたら
作り方を見直したいと思います。

**Comment by snext1220** [comment]
現時点では、複数リンクがある場合は、並び順を指定するのが前提となっております。
よって、並び順の指定がない場合、仰る通り、一部のリンクが消えるのではないかと思われます。
現時点では、恐縮ですが **並び順明示で** 作成戴けますとm(_ _)m

ただ、確かに勝手の割り振りは許容できた方が良さそうですね。。
こちら別途にはなるかと思いますが、まずは検討とさせてくださいませ～

**Comment by cocotori** [comment]
そういう仕様だったのですね。理解しました。
改めて並び順を指定せずに保存したところ、現象が再現しました。
なので、やはり仕様と合わない使い方をしていたのだと思います。
お騒がせしました。


仕様変更ありがとうございます！
使ってみたところ、
仮の順番を勝手に決めてくれるので
わたしとしてはとてもありがたいです。

**Comment by snext1220** [comment]
仕様と合わない＞いえいえ、リンク周りはかなり複雑なことをしているので、中々判りにくいかもしれません（元々、順番もランダムリンクや任意リンクなど、特殊リンクを束ねるのが目的だったり^^;）。仕様的にも改善の余地ありという認識なので、ご意見大変助かります！今後ともなんなりとご意見お寄せ下さいませ～

＃ とりあえず仕様変更で使いやすくなったとの事、良かったです！


＃ ただ、特殊リンクを使っていくと、恐らくもっと簡単に設置したいと言われるかなぁと覚悟しています^^;

**Comment by toki-sor1** [comment]
ココさん、リオさん、仕様についての検証や変更等、本当にお疲れ様です！
***
動作確認環境：Win 8.1/Chrome 80.0.3987.122(64bit)

こちらも1つのノードに対して複数のリンクの表示順序を指定せず（空白のまま）、scenario.xmlを保存し、それを読み込んでみました。
表示順序に数字（順番）が自動的に割り振られ、リンクが消えることはありませんでした。

修正したい表示順序は、後から手動でも修正可能ですし、仮の数字が自動的に割り振られるのは楽で良いですね。

**Comment by Salvadors-cabin** [comment]
お疲れ様ですー。
Win10+Edgeで問題ないことを確認しましたのでご連絡します。
