### ISSUE TITLE
Playground Flow、3つ以上の条件組み合わせが効かない

### ISSUE THREAD

**Issue by cocotori** [snext1220/stext#165]
シーン移動の際の条件なのですが、

どうも3つ以上だと認識してくれないようです。

例：フラグ3種のアンド

f01&f02&f03など。
f01&f02&-f03もだめです。

古い表記の、
f01,f02,f03ならいけました。

一度確認をお願いできれば・・・と思います。

**Comment by snext1220** [comment]
ご指摘ありがとうございます！

> どうも3つ以上だと認識してくれないようです。

こちら、もしや条件式をサイドバーからのシートから編集すると反映されないという問題、でしょうか（直接メイン領域のテキストボックスに入力だと問題なし？）。とりあえず、その問題という前提でGitHub Pagesのみ修正してみました。

お手数をおかけして恐縮ですが、もし問題改善しないようであればお申し付けくださいm(_ _)m

**Comment by cocotori** [comment]
いろいろ試してみましたが
問題が改善されず・・・Flowの問題というよりは
システム側の問題のようにも思います。

認識されないという表現がわかりにくくてすみません。
サイドバーでもテキストボックス直接入力でも
コードとしては入るのでxmlには保存されるのですが、
それを実行すると、意図通りの動作をしないという意味です。
（フラグ条件に合致する場合でもボタンが出現しない）

かんたんな検証シナリオを作ってみたので確認をお願いできませんか？

[scenario_test.zip](https://github.com/snext1220/stext/files/4246865/scenario_test.zip)

**Comment by snext1220** [comment]
改めてバグ報告有難うございました。
こちら新規構文のバグだったようで、先ほどGitHub Pagesに修正Upしております。
何度も恐縮ですが、ご確認戴けますと幸いですm(_ _)m

なお、検証シナの否定構文ですが、恐らくお間違いのようだったので修正し、検証しています。
```
!f01&amp;f02&amp;f03
⇒
!(f01&amp;f02&amp;f03)
```

**Comment by cocotori** [comment]
修正されたことを確認しました。
全ては確認できていませんが、
フラグを4つにしたりして追加で確認も行い、大丈夫そうです。

修正ありがとうございます！

こちらも機能アップのときに確認したはずなのですが、
ザルでしたね・・・すみませんでした。

**Comment by snext1220** [comment]
ご確認ありがとうございました！

ザル＞いえいえ、こちらでも気づきませんで；
当初導入時には3条件でのテストケースが残っているので、恐らく${if}競合などのBugFixで発生した問題のように思われます（恐らく半年前位に混入したバグ？）。
条件式はコアにも関わらず、パターンが無限で検証が難しいところなので、こちらでもデグレードテストの方法など考えてみたいと思います。

＃ 本当はどこかで分岐の旧構文は削除していきたいのですが、もう少し維持ですね。。

今回はcocoさんにはお手数をおかけしてしまいましたが、反面、シナリオの中でFlow含めて各種機能をご利用いただいて、問題が出ればIssue立ち上げという流れを作って戴いたのが本当に有難く。バグがないに越したことはないのですが、今後ともどうぞよろしくお願いします。

**Comment by toki-sor1** [comment]
ココさん、リオさん、こちらもご検証や修正等お疲れ様です！

今まで不具合とは気付かずに、エラーが出る組み合わせ＝設定できない組み合わせだと思い込んでおりました；
思い込み、本当にダメですね…申し訳ありません；
ご報告やご検証、そして修正も本当にありがとうございました…！
***
動作確認環境：Win 8.1/Chrome 80.0.3987.122(64bit)

ココさん、検証シナリオの作成お疲れ様でした＆ありがとうございました！
4つの条件を指定した組み合わせでボタンが表示されるか検証する際に、下記の条件も加えさせていただきました。
```
[f01&amp;f02&amp;!(f04&amp;f05)](4 "f01&amp;f02&amp;!(f04&amp;f05)")
```
こちらも条件が揃った際に、ボタンが表示されるのを確認しました。

**Comment by snext1220** [comment]
ご検証ありがとうございます！

> エラーが出る組み合わせ＝設定できない組み合わせ

条件式の新規構文はそれなりになんでもできるようになったので（仕様上は^^;）、どこまでが仕様なのかが判定しにくいですよね；とりあえず「&」「|」「!」「(...)」の組み合わせで表現できることは、それなりにいけるはずなので、こんなんダメなの、などありましたら、お気軽にお問い合わせくださいませ～

**Comment by Salvadors-cabin** [comment]
そういえば私も過去に条件がうまく動かなかったので試行錯誤しているうちに動くようになったのでそのまま報告しなかったような・・。
もしかしたらこの条件文にハマっていたかもしれないという事を今思い出しました・・。

ともかく、Win10+Edgeで問題ないことを確認しました！

**Comment by snext1220** [comment]
検証有難うございます。

> もしかしたらこの条件文にハマっていたかもしれないという事を今思い出しました・・。

新規構文では皆さま苦労されているようで恐縮です；なんでもできるように見える分、なにができるのかできないのかが判りにくくなっているのかもしれません。

マニュアルでも主に利用すると思われるものはまとめておりますが、他にも「このパターンはよく利用する！」というものがあれば追加しますので、お知らせくださいませ＞皆さま

https://sorcerian.hateblo.jp/entry/2018/11/01/211745
（9）複合条件式

逆に、「こんな条件式を書いたが動かない」というものがあればお教え戴ければ幸いです。

**Comment by snext1220** [comment]
マニュアル充実＆安定性向上を目的に、本IssueについてはMay Updateまで残したいと思います。
上記コメントの以下件につきまして、なにかございましたら是非にお知らせください。

> 他にも「このパターンはよく利用する！」というものがあれば追加しますので、お知らせくださいませ
> 逆に、「こんな条件式を書いたが動かない」というものがあればお教え戴ければ幸いです。

**Comment by snext1220** [comment]
本件、不具合あればとのことで3か月保留しておりましたが、特に追加のBug報告ありませんでしたので、一旦Closeとしたいと思います。
