### ISSUE TITLE
【Playground Flow】xxxx_max属性の追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#166]
#149 に伴い、PgFlowにもxxxx_max属性の欄を追加しました。

※伴い、オートコンプリートによるテキストボックスの不具合（＝セーブデータに反映されない）を修正しています。

**Comment by toki-sor1** [comment]
動作確認環境：Win 8.1/Chrome 80.0.3987.122(64bit)

PgFlowもxxx_max属性が反映されるのを確認しました。

しかし、xxx_max属性入力後にシナリオをブラウザに保存し、マイストレージからシナリオの読み込みを行ったところ、xxx_max属性の値だけは消えていました。
（テキストボックス、アイテム、ステータスの値は、消えませんでした）

**Comment by snext1220** [comment]
大変申し訳ありません！
完全ポカで書き戻しが漏れていました；先ほど修正＆GitHub反映済みでございますm(_ _)m

**Comment by toki-sor1** [comment]
お忙しいところ、早速の修正＆反映お疲れ様です！
履歴を削除してから上記の手順で確認しました。
今度はxxx_max属性もアイテムと同様に値が保持されていました！
ありがとうございました！！

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで機能的には問題ないことを確認しましたー。
表示画面でちょっと気になるところがありました。
![166](https://user-images.githubusercontent.com/42834363/75878192-8fc0c980-5e5c-11ea-8782-f1850fdf7f4a.png)

HP_MAXの並びの２行目がシートからはみ出してしまい、読めなくなっています。
もしかするとブラウザやフォントサイズの問題かもしれませんが、一応報告しておきます。

**Comment by snext1220** [comment]
見た目の件、ご指摘ありがとうございます！
仰る通り、フォントサイズの関係でKRMの箇所が2行になってしまったのが問題のようです。
とりあえず以下の対策を採りましたが、如何でしょうか。

+ 縦幅を若干拡張
+ テキストボックスの横幅を一律小さめに（改行発生を防ぐため）
+ ラベルの背景を白に（はみ出た場合も最低限判読できるように）

**Comment by Salvadors-cabin** [comment]
対応ありがとうございます。問題は解消されたと思います。
![166](https://user-images.githubusercontent.com/42834363/76095174-2fba5680-6007-11ea-8770-a0361b7d7ccc.png)
