### ISSUE TITLE
Playground Flow使い勝手の所感と課題提起

### ISSUE THREAD

**Issue by cocotori** [snext1220/stext#167]
Playground Flowを使っていて、
使い勝手の課題とか問題点を感じましたので、
書き出してみます。
　
課題としてあげさせていただきましたが、
今現在でも使うことはできますし、
すぐに対応しろというものではないです。
実現が難しいものもあるでしょうし、長期的なテーマとさせてもらえれば。
　
　
1) 入力文字がいつ保存されるのかがわかりにくい

例えばサマリーに文字を入力し、すぐに別のノードをクリックすると、
サマリーに入力した文字は消えてしまいます。

一方、本文の方は同じ操作をしても消えずに残ります。

このあたりに、ややわかりにくさがあるので共通化できたらありがたいです。

方向性とはどんな感じでしょうね・・・
・何か入力したら、一文字でも自動で保存する
・変更中はそれとわかる表示をする。ノード名に（*）をつけるとか。
　
　
2) 双方向の矢印が見にくい。選択しにくい。

シナリオ構成次第でしょうが、
ゲームブックで一つ前のノードに戻ることは結構多いように思います。
もう少し改善できたらなと思っています。

対策案を考えてみましたが、

・2ノード間をつなぐリンク線を、最大で2本までにする
・重なってしまうのは仕方ないが、例えばABノード間のリンク線をクリックしたとき、
　AよりならA→Bが、BよりならB→Aが選択できる、などの仕様にする

などでしょうか。
　
　
3) 新しいノードと今までのノードの接続操作性があまり良くない

新しいノードを作ると一番上に配置されてしまうので、
今まで作っていたノード（おそらく一番下）とリンクを生成するときに、
ドラッグしながらマップを拡大したり縮小したりする操作が発生して
わりと大変でした。

例えば新しいノードを今編集してるノードのそばに生成するとか、
リンクを生成したい2ノードがあったときに、
順番にクリックするとリンクが生成されるとか。
　
　
4) 本文を記述している際の、サジェスチョンを邪魔に感じることがある

これはわたしだけかもしれません。
本文を書いていると、自動候補機能が働くのですが、
それでつい古い文章を繰り返し入力してしまうことがあります。
例えば、改行を2回入れたいときに、エンターを2回連続で入力すると
改行せずに候補文字が入ってしまいます。

操作ミスなので気をつければいいだけの話なのですが、
本文のように日本語の文を入れることが多いところでは
そもそも候補機能自体いらないのではないかと思っています。

ただ、候補機能をよく使われている方もいるかも知れませんし、
まずはそんなこともあったよ、という問題提起をさせてもらえればと思います。
　
　
5) 本文の領域が狭い

現状では一度に見ることのできる行数は15行となっているようです。
サイズとの兼ね合いもあると思いますが、もう少し広く取ることはできないでしょうか。

せめて倍の30行程度が一度に表示されるとありがたいと思っています。
　
　
　
6) おまけ

お知り合いの方に、yEd Graph Editorというツールを教えてもらいました。
Flowのように、フロー図を作成ツールで、
とても使い勝手がよかったのでご紹介をさせてもらいます。

https://www.yworks.com/products/yed

試しに、このツールで「導きソーサリアン」の前編部分を
フロー図にしてみました。
とても見やすくないでしょうか。
もちろん今から乗り換えようとかそういう話では無いのですが、
フロー図の作り方等、参考になるところも多いような気がします。

![image](https://user-images.githubusercontent.com/42885160/75621050-2a0ddc80-5bd3-11ea-97af-d6ce82792142.png)

**Comment by snext1220** [comment]
ご指摘ありがとうございます！
繰り返しにはなりますが、ツール使い込んで戴いての諸々のリクエスト大変ありがたく。利用しているライブラリの制約で直接的な対応が難しいものもありますが、別案も出しながら改善していければと思いますので、引き続きお気づきの点はご指摘お願いいたします。

ということで、以下取り急ぎではありますが、リクエストの件、回答してまいります。
対応済みの箇所は、GitHub Pagesにのみ反映済みです（併せて［Testing］扱いにしていますので、ご確認戴けますと幸いです）。

> 1) 入力文字がいつ保存されるのかがわかりにくい

こちらまさにご指摘の通りで；、基本は一文字単位での保存を意図していたはずなのですが、一部統一が取れていませんでした。改めて統一したつもりですが、如何なものでしょうか。

> 2) 双方向の矢印が見にくい。選択しにくい。

修正してみました。
同方向リンクで重なるのは避けられないケースもありますが、その場合は従来の［シーン］タブからリンクを選択いただければ賄えるのかなと。如何でしょうか。

> 3) 新しいノードと今までのノードの接続操作性があまり良くない

現在の表示位置に応じて、追加ノードの表示位置を表示してみました。
如何なものでしょうか。

> 4) 本文を記述している際の、サジェスチョンを邪魔に感じることがある

こちらOS標準の入力候補でしょうか（であれば、PgFlowとしての無効化は難しい）。PgFlowについては入力候補機能は有効化していないはずですが、環境に依るのかと、一応明示的に無効化してみました。現象改善していなければお知らせください。

> 5) 本文の領域が狭い

こちらはボタンでエディター領域の伸縮を可能にしてみました。

**Comment by toki-sor1** [comment]
暗き沼～の公開直後にまとめられず、申し訳ありません；
当時のPlayground Flowとは異なるところもありますので、現在のPlayground Flowについてまとめますね（主にエディターと併用した時）。
***
### 【意見】id（Scene番号）の値が離れすぎている時の表示
例えば、長編シナリオで「id=100」のパターン違いを作成する時です。
私は番号の振り直しミスがこわいので、「id=100」にパターン01を作成する時に連番にはせず、「id=10001」と設定することがあります。

そういう法則でidを設定していると、**場合によっては画面にノードが表示されなかったり、リンクが繋がっていないように見えてしまうことがあります**（画像は双王の例）。
※ただし、「編集するシーンを選択」からは、ノードが表示されていないものも確認可能
<img width="200" src="https://user-images.githubusercontent.com/42646342/75991757-48a90600-5f3a-11ea-8280-cbe9db8a6e34.png">

こういった番号の振り方は、おそらく特殊だとは思うのですが、できればノードもリンクも表示されると嬉しいです。
***
### 【意見】リンクの矢印が見辛い
矢印が曲線になっていますが、**個人的には直線の時よりも見辛いように感じました。**
シナリオの構成によるところも大きいとは思うのですが、**矢印が曲線になることで、ノード同士の繋がりを目で追う時間が増えた**のかもしれません（誤差の範囲かもしれませんが…；）。

ただ、**双方向の矢印**については、**曲線の方が矢印が離れているので見易いです。**

一長一短で悩ましいですが、**双方向の場合は、直線2本を間隔を開けて表示する**と見易そうだと思いました。
***
### 【改善】ノードの表示位置
ノードが何処かにいってしまった、ということがなくなって、良いと思いました。

### 【改善】入力候補機能OFF
Win 8.1/Chromeで確認しました。OFFになっています。

### 【改善】エディター領域伸縮
Win 8.1/Chromeで確認しました。
文章入力途中に、基本データなどを入力することは、あまりないと思うので、現在の展開方法も良いと思います。
***
### 【感想】yEd Graph Editor
私は試しにオンライン版を触ってみましたが、PowerPointみたいにノードをズレなく並べられたり、ノードの形やリンクの矢印を設定できるのが良いですね。

直線の矢印を途中で折り曲げることもできるので、矢印同士が重なりにくくなるところも良いなと感じました。

**Comment by snext1220** [comment]
ご確認＆リクエストありがとうございます！
ご要望、課題について中心にお返事してまいりますね。

> 【意見】リンクの矢印が見辛い

こちらは使用しているライブラリの関係で、双方向矢印を直線で離すというのが難しそうでして（私の理解不足の可能性はありますが、現時点の認識で。以下同）；極力直線に近づけてみたのですが、如何なものでしょうか；；

＃ 直線のままで矢印を重ねた場合も、リンク元のノードを選択してから矢印を選択することで選択しやすくはなるのですが…これは聊か裏技的ですね^^;

> 例えば、長編シナリオで「id=100」のパターン違いを作成する時です。

こちらについては調査しますが、恐らくライブラリ側で複雑なノード連結を割愛して表示しているのが原因と思われます。
グループ機能も、関連する番号はまとまった番号帯にあることが前提に作成していますので、極力、近接した番号を振って戴くのがお勧めでしょうか。

例. メインの番号は100、200、300...にように振っていき、100配下の枝番?は110、120...でまとめるなど。

> 【感想】yEd Graph Editor

ホント、良いツールだと思います。重ねてですが、ライセンス料金が2桁下ならば導入しても、という感じです^^;

現在利用しているのが、フロチャ作成というよりもネットワーク図表示のためのツールなので、その辺で限界が出ているようにも感じます（現在のものもかなり高機能で、機能も順次追加されているので、フロチャを意識した機能も将来実装されるかも）。

ちなみに、無償で利用できるフロチャツールとしては、以下のようなものもあるようでした。
https://alyssax.com/x/flowy/

ただ、単体で完成度の高いツールは、組み込みの自由度がどこまであるかなどありますし、PgFlow自体もほぼ一から作り直しになってしまうので、現在のものもまだまだブラッシュアップの余地はあると思うので、慎重に検討していければと思っています（反面、費用＋機能で優位性があれば、現状で無理を重ねるよりも、というのもありますし、一から作り直すのは覚悟だけなので^^;、またよさげなツールがあれば是非お教えください）。

**Comment by cocotori** [comment]
素早い対応ありがとうございます！
個人的にはどの改善も、大満足です。

自動候補はOS側の機能だったのですね。
今回の変更で、でなくなることを確認しました。
個人的にはこちらのほうがありがたいです。

**Comment by toki-sor1** [comment]
＞ @snext1220 さん
お疲れ様です！
ご返信と早速の意見反映もありがとうございます～！

> 極力直線に近づけてみたのですが、如何なものでしょうか；；（GitHubのみ反映）

おお！　直線に近くなったことで、とても見易くなりました！
双方向の時も見易さも維持されているので、本当にありがたいです！

双方向矢印の直線で離すのは、ライブラリの制約などで現状難しいのですね。こちら、承知しました～！

> ＃ 直線のままで矢印を重ねた場合も、リンク元のノードを選択してから矢印を選択することで～

なるほど、その手が！
現状の表示方法とこちらの方法を併用すれば、矢印が複雑なフローチャートでも見失わずに済みますね。
***
> こちらについては調査しますが、恐らくライブラリ側で複雑なノード連結を割愛して表示しているのが原因と思われます。

確かに「100」と「1001」では実際にとても間が空いていますし、それがもっと複雑になれば、割愛して表示しているのも頷けます…；

> 例. メインの番号は100、200、300...のように振っていき、100配下の枝番?は110、120...でまとめるなど。

ご助言もありがとうございます！
主に長編シナで複雑な番号を振ってしまいがちなので、今後の長編シナでは、こちらを参考に番号を振ってみようと思います！
***
> ホント、良いツールですよね…！本気で、ライセンス料金が2桁下ならば導入しても、という感じです^^;

いやぁ、まさに桁違いでしたねぇ…；
良いツールなので名残惜しいですが、お値段を見てしまったらもう諦めるしか…ｗ

> 現在利用しているのが、フロチャ作成というよりもネットワーク図表示のためのツールなので、その辺で限界が出ているようにも感じます～

なるほど、現在使用しているツールは、その機能を応用してフロチャを作成できるようにしているのですね～。
機能も順次追加されているとのお話ですので、今後の機能追加にも期待が高まりますね！

> ちなみに、無償で利用できるフロチャツールとしては、以下のようなものもあるようでした。

ご紹介ありがとうございます！
こちらも触ってみたのですが、機能がよく分からず、あまり複雑な操作はできませんでした；

ただ、ノードもさっと追加できて、ノード同士を近づけることで、リンクを繋げられるのが、直感的で良いですね。
画面が見易いところも良い感じでした！

> ただ、単体で完成度の高いツールは、組み込みの自由度がどこまであるかなどありますし、～

おぉん、組み込みの自由も大事ですもんね～。
流石にここまで育ててきたPgFlowを一から作り直しというのは、色々な面から考えても、何か止むに止まれぬ事情がない限りは避けたいですし（大汗）、慎重に検討しつつブラッシュアップを頑張る方向でいきたいですね～！

> またよさげなツールがあれば是非お教えください

はい～、他のツールから学ぶこともありますし、何かありましたらお知らせいたしますね～。

**Comment by snext1220** [comment]
@cocotori さん＞

> 個人的にはどの改善も、大満足です。

地味に交々弄っていたので、そう仰って戴けると開発者冥利に尽きます！
引き続きお気づきの点は、なんなりとお寄せくださいませ～

@toki-sor1 さん＞

早速のご確認、また、見やすくなった、とのご評価、ありがとうございます！

> 双方向矢印の直線で離すのは、ライブラリの制約などで現状難しいのですね。

ドキュメント、サンプルなど見る限りは、ですね～ただ、この辺、私も制約を読み切れていないので、引き続き調査＆調整してまいりますね^^; ある日直っていたら、やっぱり機能あったのか、ではなく、ライブラリがバージョンアップしたのだと思ってやってくださいｗ

> 現状の表示方法とこちらの方法を併用すれば、矢印が複雑なフローチャートでも見失わずに済みますね。

はい～今回戴いた数値採番の件もそうですが、PgFlowの暗黙的なテクニックは諸々ありそうなので、この辺もいずれがドキュメントにまとめていければと…！
＃ もし「自分はこんな技も」などあれば、是非にお知らせください～

双王の問題は、スミマセン、もう少しお時間ください。ただ、他のフロチャに影響が出る可能性もあり、ママとなってしまったらお許しを...

> なるほど、現在使用しているツールは、その機能を応用してフロチャを作成できるようにしているのですね～。

> こちらも触ってみたのですが、機能がよく分からず、あまり複雑な操作はできませんでした；

早速ご確認ありがとうございました！デモがかなり特定用途に作り込まれているようで、そのままでは汎用的な操作は難しそうですね；一応、こんなんもあるよ、という程度で...^^;

> 流石にここまで育ててきたPgFlowを一から作り直しというのは、色々な面から考えても、何か止むに止まれぬ事情がない限りは避けたいですし（大汗）、慎重に検討しつつブラッシュアップを頑張る方向でいきたいですね～！

仰る通り、作り直しは細かな操作性をゼロに戻してしまう可能性があるので、安易には、ですよね^^; 今回のようなIssueはホント価値が高いので、是非今後ともお気づきの点はお気軽にお願いします～

### まとめ？

とりあえず双王の対応もあるので＆PgFlowへのその他のご意見の受け口として、May UpdateまでIssueは継続いたしますね。引き続きどうぞよろしくお願いいたします＞皆さま
