### ISSUE TITLE
nexts属性で自シナを指定

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#168]
scene要素のnexts属性に関する改善です。
旧仕様では、指定できるのは他シナリオに限定されていましたが、現在のシナリオ（自分自身）も指定できるように改めています。

**Comment by toki-sor1** [comment]
動作確認環境：Win 8.1/Chrome 80.0.3987.122(64bit)

他シナリオも現在のシナリオも各種データを引き継ぐことができました。
シナリオ１→シナリオ２→シナリオ１というような引き継ぎも可能でした。

**Comment by Salvadors-cabin** [comment]
いまさらで申し訳ありませんが、nexts属性の使い方を教えていただけると助かります。
リファレンスにあるようにend属性のあるscene要素にnexts属性を追加してテストしてみましたが、結果がどのようになれば成功なのかが分かりません。
・end属性はhappyでもbadでもよいのでしょうか。
・記述例は「nexts="ramidia"」であってますかね。
・そのsceneに到達した後にbackupし、nextsで指定した別シナでrestoreしてみましたが、ロードに失敗しました。このテスト方法でよいかどうかがわかりません。GitHubからソースをダウンロードし、ローカル環境でテストしました。

よろしくお願いしますー

**Comment by snext1220** [comment]
ご確認お疲れ様です。

>・end属性はhappyでもbadでもよいのでしょうか。
>・記述例は「nexts="ramidia"」であってますかね。

はい、問題ありません！

> ・そのsceneに到達した後にbackupし、nextsで指定した別シナでrestoreしてみましたが、ロードに失敗しました。

自動展開されますので、backup/restoreはご不要です～
詳しく（でもありませんが^^;）は以下を参照下さいませ。

+ https://sorcerian.hateblo.jp/entries/2017/12/20  セーブデータの引き継ぎ
+ https://sorcerian.hateblo.jp/entry/2018/11/01/211745#nexts

**Comment by Salvadors-cabin** [comment]
ご教授ありがとうございます。
Win10+Edgeで試してみたところ、他シナへの引継ぎはできました。
しかしながら、自シナをnextsに設定し、ENDシーンで自シナをプルダウンメニューから選択しても「続きから」「最初から」の画面が出ず、キャラクターが新規作成されてしまいました。
シナリオを直さないとテストできないため、ローカル環境でテストしてますが、、

**Comment by toki-sor1** [comment]
Win8.1/Chrome 80.0.3987.132(64bit)で改めて動作確認（ローカル環境）。
こちらは現在のシナリオのエンディング後、プルダウンメニューから同じシナリオを選択した時に「続きから」「最初から」の画面が出ていました～。

ただ、今回の確認時に最初「**nexts**＝"test"」を間違えて「**snext**="test"」と間違えてテストしていたらしく、「あれ？　おかしいな？？」と慌ててました；
（この場合、キャラクターが新規作成になりました）

**Comment by Salvadors-cabin** [comment]
>しかしながら、自シナをnextsに設定し、ENDシーンで自シナをプルダウンメニューから選択しても「続きから」「最初から」の画面が出ず、キャラクターが新規作成されてしまいました。

先ほどテストをやり直してみたところ、今度はうまくいきました。（たぶんどこかでスペルミスをしていたのだと思います。）
お騒がせしてすみませんでした・・・

**Comment by snext1220** [comment]
@toki-sor1 さん、引っ掛かりどころのご紹介ありがとうございました！
@Salvadors-cabin さんの方も解決されたようで何よりです～
