### ISSUE TITLE
ランダムリンクでキャッシュ機能を実装

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#169]
ランダムリンクでキャッシュ機能を有効にします。

```
[ランダムリンク](1,2,3;7)
```

セミコロン以下で有効期限を指定（上の例では7日間キャッシュを維持）。
もちろん、「;7」を省略した場合にはキャッシュは無効です。

キャッシュ機能は比較的汎用的に実装しているので、今後、他の場所でも利用できるようにしています。

**Comment by toki-sor1** [comment]
動作確認環境：Win 8.1/Chrome 80.0.3987.122(64bit)

キャッシュ機能の影響かは分からないのですが、ランダムリンクで毎回同じSceneが表示されるようになりました（;○を消すと毎回ランダムになりました）。

ただ、私がしっかりと意図を理解できておらず大変申し訳ないのですが（汗）、ブラウザのキャッシュ削除後も同じSceneが表示されるのは、正常な動作と考えてもよいのでしょうか？

**Comment by snext1220** [comment]
> キャッシュ機能の影響かは分からないのですが、ランダムリンクで毎回同じ 
> Sceneが表示されるようになりました（;○を消すと毎回ランダムになりました）。

ご確認ありがとうございます！
はい、リンク先を保存しておくための機能なので、ご確認戴いた動作で問題ないと思います（仰る通り、;○を消すとキャッシュを利用しなくなるのでランダムに戻ります）。

> ブラウザのキャッシュ削除後も同じSceneが表示されるのは、正常な動作と考え てもよいのでしょうか？

はい～問題ありません！
本機能はCookiesという機能を利用していますので、ブラウザーキャッシュを消しても無効化されません。もし削除する場合は［閲覧履歴のデータを削除］する際に、cookieも削除対象に加えて戴く必要があります。

ただ、Cookie全体が消えてしまうので、開発者ツールから「stext_cache_～」というcookieだけを消した方が安全かもしれません。

![無題](https://user-images.githubusercontent.com/27911337/75790673-dfe15280-5dae-11ea-810b-382d7a0a140c.png)

**Comment by toki-sor1** [comment]
とても丁寧にご説明いただき、機能について理解することができました！
お忙しいところ、ご説明ありがとうございました！

> はい、リンク先を保存しておくための機能なので、ご確認戴いた動作で問題ないと思います（仰る通り、;○を消すとキャッシュを利用しなくなるのでランダムに戻ります）。

> 本機能はCookiesという機能を利用していますので、ブラウザーキャッシュを消しても無効化されません。

おお、この動作で問題はないのですね！　安心しました！
ブラウザーキャッシュを削除しても、同じ結果が出ているのでちょっと心配だったのですが、Cookieが関係していたと分かって、それは同じ結果が出続ける訳だ～、となるほど納得です！

仰るとおり、Cookie全体が消えてしまうと困ってしまうので、こちらは削除の対象外にしていました。
しかし、個別にCookie消すという方法なら、他のCookieに影響もなくて安全ですね。
ご助言ありがとうございました！

**Comment by Salvadors-cabin** [comment]
お疲れ様です！
Win10+Edgeで機能することを確認しました。

**Comment by cocotori** [comment]
win10+chromeで正常に動作しました。

ただ、キャッシュの記述（;数字）をすると
flowでの矢印が消えてしまいました。
逆に、リンクの記述が今までなかった本文に現れました。
記述が変更されたことで、
リンクとして認識されなくなった・・・？ようです。

**Comment by toki-sor1** [comment]
Win8.1/Chrome 80.0.3987.132(64bit)にて動作確認。
私も自シナリオのプロローグにランダムリンクを追加してPgFlowで読み込んでみましたが、ココさんのご報告と同じ症状が出ていますね；
<img width="200" src="https://user-images.githubusercontent.com/42646342/76143538-8bdeb280-60bb-11ea-8552-e60571fa1631.png">
<img width="200" src="https://user-images.githubusercontent.com/42646342/76143587-fdb6fc00-60bb-11ea-899b-13ad6ca4ad83.png">　<img width="200" src="https://user-images.githubusercontent.com/42646342/76143596-19ba9d80-60bc-11ea-8ac1-93a361b11d11.png">

**Comment by snext1220** [comment]
@cocotori さん、 @toki-sor1 さん、ご指摘ありがとうございました！
PgFlow対応については別Issueを立てましたので、そちらで対応進めるとして、こちらはCloseとしてまいりますね。
