### ISSUE TITLE
【PgFlow】ランダムリンク（キャッシュ対応）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#172]
以下ご指摘に基づいた対応です。
https://github.com/snext1220/stext/issues/169#issuecomment-596021110

本件対応いたしまして、GitHubのみ反映しております。
ご確認戴けますと幸いです。

**Comment by toki-sor1** [comment]
Win8.1／Chrome 81.0.4044.122(64bit)

Pg Flow　GitHub版で動作確認。
scenario.xmlをテキストエディタで編集して、ランダムリンク＋キャッシュ期限を指定。
そのscenario.xmlをPg Flowで読み込んだところ、以下のような状態になりました。

- 例えばランダムリンクで(1,2;2)と指定した場合、**scene 1へのリンクのみキャッシュ期限が表示された**（scene 2へのリンクには、キャッシュ期限が表示されない）
- その状態でゲームをプレイしてランダムリンクを踏むと、**何故かscene 101に飛ばされてしまう**

<img src="https://user-images.githubusercontent.com/42646342/80311450-a2cb9680-881a-11ea-96d0-b640019d4958.png" width="200"> <img src="https://user-images.githubusercontent.com/42646342/80311465-baa31a80-881a-11ea-8d90-aca14f1dfb9c.png" width="300">

**Comment by snext1220** [comment]
ご確認ありがとうございます。
こちら順次確認してまいりますね。
PgFlowにつきまして、今回新たに #191 を新設しましたので、こちらにて統合してまいります。
一旦こちらはCloseしてまいりますが、対応は続けますのでご了承くださいませm(_ _)m

**Comment by snext1220** [comment]
Closeしますと言いながら申し訳ありません。一部ちょっと回答＆確認させていただけますでしょうか。

> 例えばランダムリンクで(1,2;2)と指定した場合、scene 1へのリンクのみキャッシュ期限が表示された（scene 2へのリンクには、キャッシュ期限が表示されない）

こちらは仕様になりますm(_ _)m
条件式やキャッシュルールは最初のひとつにのみ反映されます（複数入力時も、xmlに戻した時には片方一つだけが優先して反映されます）。

> その状態でゲームをプレイしてランダムリンクを踏むと、何故かscene 101に飛ばされてしまう

前のキャッシュが残っていませんでしょうか。
キャッシュのキーが、stext_cache_random_playground0のような形になっているため、同じシナリオ、同じシーンでリンク先を変更してもキャッシュの問題で反映されない可能性があります。お手数ですが、キャッシュを消してご確認いただけますと。

一応現時点ではママでいけそうかなと思っていますが、お手数ですが、問題あれば今一度ご指摘お願いいたします～

**Comment by toki-sor1** [comment]
お返事が遅くなり、お手数もお掛けしてしまい申し訳ありません…！
とても丁寧にご解説いただき、キャッシュの扱いや仕様について理解しました。

Win8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
以下のサイトで紹介されている方法で個別にキャッシュを消去した後、ランダムリンクの移動先を変更後にもランダムリンクが適用されていることを確認しました。

[\[Chrome\] 特定のサイトのキャッシュデータを削除する方法 \| Search Light（CakePHP PHP jQuery JavaScript CSS Linux MySQLMac）](https://www.searchlight8.com/chrome-cache-delate/)
