### ISSUE TITLE
SGML式の拡張（ステータス情報の表示）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#173]
現在はキャラ情報として表示できるのは${title}、${name}ですが、
${hp}、${mp}、${str～krm}、${free1～3}を許容することを考えています。

メイン領域にこれらの情報を表示できるようにすることで、以下のような用途が考えられます。如何なものでしょうか。

+ 現在のステータスに応じてプレイヤーがなんらかの判断をしたい場合にも、ステータスシートを開かなくても良い
+ free1～3になんらかのポイント（たとえばGold）を保存していた場合、最終的に「最終獲得額：●○ Gold」のように、シナリオとしての結果表示にも利用できる

既存仕様への影響はないので、積極的反対がなければ実装の方向で進められればと思うのですが、如何でしょうか。
=> 特に反対意見が内容だったので、こちら先行して実装させていただきました。

**Comment by toki-sor1** [comment]
Win8.1／Chrome 81.0.4044.122(64bit)にて動作確認。

${hp}、${mp}、${str～krm}、${free1～3}の数値が表示されていることを確認しました。
仰る通り、数値をテキスト側で表示できた方が確認の手間も省けて便利なので、**実装後の方がより良い**と感じました。

**Comment by cocotori** [comment]
${hp}、${mp}、${str～krm}、${free1～3}
一通り確認しました。
正常に表示されています。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで表示されることを確認しました。問題ありません。
