### ISSUE TITLE
アイテムの任意利用を可能に

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#174]
#### 概要

items－item要素にuse属性を追加する。

#### 挙動

+ use属性の付いたアイテムは［Items＆Flags］シートから［使う］ボタンでアイテムを利用できるように
+ ［使う］ボタンを押されたアイテムはシートから消える

#### 背景

+ これまでアイテムを使うにはsceneを跨ぐしかなかった
+ そのため、回復薬のように、「任意のsceneで使いたいアイテム」を実装するのが困難であった
    + 使用する可能性のあるすべてのsceneで「使う」ボタンと対応するsceneを設ければできるが、あまり現実的でない上、手間
+ 本機能でそうした任意仕様のアイテムの実装を容易に

#### 備考

+ アイテムを使ってしまったことによる「詰み」はシナリオ作者の責任
+ いずれはアイテムの個数を管理するなどもできればと考えますが影響大なので、ここでは除外しています。
    + 現時点ではitem idをわけて同名のアイテムを用意すれば同様の表現は可能

**Comment by cocotori** [comment]
戦闘や進行に有利なアイテムを
その場で判断して使う、といった
遊び方も可能になるわけですね。
賛成です！

**Comment by Salvadors-cabin** [comment]
ぜひ実装して欲しい機能です。
アイテム使用時にパラメータの変化（例えばHPが全回復とか）が自動でできるとありがたいです。

**Comment by toki-sor1** [comment]
> items－item要素にuse属性を追加する。

私もシナリオで消費タイプのアイテム等を幾つか出していることもあり、**実装には賛成です。**

サルバさんのご提案にある「アイテム使用時にパラメータの変化」も自動でできると、便利なことに加えて、アイテムを使用した感覚をより感じられると思います。

**Comment by snext1220** [comment]
ご賛同ありがとうございます。
item要素、セーブデータ、パラメーター反映と多岐に亘るため、かなり大規模な修正になりそうですが、気長にお待ちください（段階的な実装になるかもしれません）。

以下、現時点で想定している仕様です。

+ item要素にtarget属性（反映すべきパラメーター）、value属性（設定値）
    + 冒頭備考のように、個数は考慮しない
+ 対象パラメーター：HP、MP、STR～KRM、FREE1～3、None（パラメーターに反映しない）
+ パラメーターの設定値：scene要素の対応する属性に準ずる
+ 任意使用が可能かはtargetの有無によって決定
    + アイテム使用による矛盾の解消はシナリオの責任にて

**Comment by cocotori** [comment]
USEボタンにて、アイテムの効果が反映されることを確認しました。

ただ、Item&Flagシートには残り続けてしまうような現象になりました。
こちらは今、RYUさんから質問を受けている話と
関連しているのではないかと思っています。

**Comment by toki-sor1** [comment]
> USEボタンにて、アイテムの効果が反映されることを確認しました。

Win8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
こちらもアイテムの効果が反映されることを確認しました。

しかし、#192 でも報告しておりましたが（https://github.com/snext1220/stext/issues/192#issuecomment-640051762 ）、私の環境でもココさんと同じくItem&Flagシートに使用したアイテムが残り続けていました。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でも同様の結果でした。アイテムは消えなかったです。

**Comment by snext1220** [comment]
本件、大変失礼いたしました。
Mobile Safari対応の関係で見た目と背後のデータの関係が崩れておりました（実は見た目は選択ボックスなのですが、実体はリストというかなりトリッキーなことをしています...）。Safari対応前にデータのリフレッシュをしていたと思い込んでいたので、確認漏れとなり、失礼いたしました。

先ほど修正し、GitHub Pagesに反映させましたので、ご確認戴けますと幸いです。

**Comment by toki-sor1** [comment]
https://github.com/snext1220/stext/issues/192#issuecomment-641384159 と同様の返信失礼します…！

Win 8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
キャッシュ削除後にテストプレイを行い、正常に動作することを確認しました。

- Items&Flagsシート確認後もアイテムが表示されるように改善された
- 使用したアイテムが消えるように改善された
  - アイテムの効果も発動していた（前回と同じく正常）

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でアイテムが使用後に消えることを確認しました。効果も確認しましたー

**Comment by cocotori** [comment]
Chromeで確認しました。
無事、使用したアイテムが消えました！
