### ISSUE TITLE
ステータスのラベル表記をカスタマイズ可能に

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#175]
■概要
HP、MP、STR～KRMのラベルを変更可能にしても、という提案です。
現在はFREE1～3が独自ラベルを指定できるようになっていますが、これをより一般化するIssueです（これに伴い、FREE1～3の表記も少しレイアウト修正予定です=>テキストボックスの上側に移動）。

■用途
たとえば旧来のゲームブックらしく、DEXを技術点、KRMを運点など、シナリオによって変更したい用途があるのかなと。

■仕様
現在のlabel要素を拡張し、hp、mp、strなどの属性を追加します。

■備考
ソーサリアン Textはソーサリアン色の強いゲームブックですが、将来的には、より一般的なゲームブックプラットフォームにできればという話が以前からありました。本件は、その一歩と考えています。
※自由度はUIの統一性は損なうものなので、その辺補うマニュアルの改訂も必要になりそうです。

**Comment by toki-sor1** [comment]
> HP、MP、STR～KRMのラベルを変更可能にしても、という提案です。

汎用性が高くなって良いと思います。
ラベルを使い分けることでソーサリアン色強めのゲームブック系or一般的なゲームブック系にするかを選べるので、**実装に関しては特に問題はないのではないでしょうか。**

**Comment by cocotori** [comment]
よいと思います。

ツクールでもそこは自由にカスタマイズできるようになっていて、
手軽にオリジナリティを出せるので
作者さんに結構重宝されている印象です。

**Comment by Salvadors-cabin** [comment]
よいと思います！

**Comment by snext1220** [comment]
ご賛同ありがとうございます。
こちらは仕様含めて同意を得られたと思うので、実装に向けて進めていきたいと思います。

**Comment by cocotori** [comment]
無事動作することを確認しました。
オリジナリティが出せるようになって、いいと思います！

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで問題無く動作することを確認しましたー

**Comment by toki-sor1** [comment]
Win8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
正常に動作していました。表現の幅が拡がる内容で良いですね！
