### ISSUE TITLE
PCの顔画像をシナリオ単位に設定可能に

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#176]
タイトルの通りです。
シナリオフォルダーにfighter_male.pngのように決められた名前で画像を用意することで、顔画像の差し替えを可能にします。

#175 と同じく、よりシナリオ側での自由度を許容するのが目的ですが、ニーズあります、かね？

**Comment by toki-sor1** [comment]
実は以前から、PCの顔画像を差し替える機能やパック（顔画像セット？）みたいなものもあったら楽しいかなと考えていました。
これはプレイヤー側として考えていましたが、自分のPCでSTextを遊べる環境を作らなければならない等の敷居の高さもあり、ボツにしていました。

シナリオ制作者側がシナリオのイメージに合わせて顔画像を差し替える、というのも**ありだと思います。**

RYUさんから以前「そのドラ」主人公のイメージをお聞きして、こんな感じかなと画像を改変したこともありましたので（あとで剣のところの着色をミスっていることに気付きました…お恥ずかしい…）。
![male_young_fighter](https://user-images.githubusercontent.com/42646342/80313550-73bb2200-8826-11ea-95f3-9a15d1d3096e.png)　→　![ヒューマン男中ドラスレ版](https://user-images.githubusercontent.com/42646342/80313553-7584e580-8826-11ea-9f09-9d05bc1f367c.png)

**Comment by cocotori** [comment]
シナリオ側で主人公像を固定化したいときなどに
便利そうですね！
こちらの機能は賛成です。

しかしここまで来ると、
プレイヤーの方でもキャラメイクしたいという要望も出てくるかな・・・
と感じています。ときさんが言われるような顔画像セットを
こちらで用意して、選んでもらう、というような。
全部のシナリオに適応するのは難しいでしょうし、
何かの企画のときにやってみてもいいかもしれないですね。
（幕末とか？）

**Comment by Salvadors-cabin** [comment]
キャラクター画像の自由度を上げるのは賛成です。


>プレイヤーの方でもキャラメイクしたいという要望も出てくるかな・・・

私もキャラクターメイキング機能は欲しいと思っており、リクエストしようと考えていました。
ただ、キャラクター画像についてはキャラメイクで選択したAGE/CLASSの結果で変わるのが自然かな、と思っています。
後ほど #159 に（画像の選択は無しの）キャラメイクのリクエストを出しますので、ご意見あれはお願いしたいです。

**Comment by snext1220** [comment]
ご賛同いただいてありがとうございます。
ただ、仕様についてはもう少し合意が必要そうです。
現時点で、以下のように考えておりますが、如何なものでしょうか（一部相反するご要望もあったため、独断でまとめています）。

+ イメージはCLASS／AGEの設定に準じて自動設定（自分での設定はできない）
+ シナ単位に標準、独自イメージいずれを利用するかを設定（一部だけを独自は不可）
    + もちろん、利用可能な種族／性別等が限定されている場合は、対応する画像のみあればよい

あくまでこちらはキャラメイクとは切り離したシナ開発者のための機能というイメージです。
＃キャラメイクについては、#190 にてIssue立てさせていただきましたm(_ _)m

**Comment by toki-sor1** [comment]
> そのドラ主人公、まさにそんなイメージですね…！ｗ

へへへ、嬉しいお言葉ありがとうございます！ｗ
イメージ化はいつも緊張しますが、そう仰っていただけると安心します！

> - イメージはCLASS／AGEの設定に準じて自動設定（自分での設定はできない）

実際のAGEはOLDだけど、見た目はYOUNG…というのも浪漫がありますが、見た目の違いによる混乱やイメージの設定ミスも予想されますね。
**自動設定**が安心そうです。

> シナ単位に標準、独自イメージいずれを利用するかを設定（一部だけを独自は不可）

「利用可能な種族／性別等が限定されている場合は、対応する画像のみあればよい」とのことですので、**この仕様でも問題なし**だと思います。

> 追加案：システムとして幾つかのイメージセットを用意し、シナリオ側ではセットを指定するだけでよい、という方法もありかとは。この場合は、ときのじさんにお願いせざるを得ないので、ご負担の面からも要ご相談ではあります。

ううっ…！　そうなんです、そこが悩ましいのですよね…。
現在のイメージは、MVに寄せた絵柄であり、本来の絵柄とは違うので、今度は違う絵柄で…というのが理想なのですが、自信を持ってお引き受けするのが難しい状態ですね…。
言い出しっぺであるにもかかわらず申し訳ありません；；

**Comment by snext1220** [comment]
ご意見ありがとうございます！
こちらは仕様の方は特に問題なしとのことで、［confirmed］扱いで進めていきたいと思います。ただ、影響も大きいので、他の改定が落ち着いたところでやや優先順位を落として、にはなってしまいますが（Augustからは一旦外しています）、暫しお待ちくださいませm(_ _)m

> 現在のイメージは、MVに寄せた絵柄であり、本来の絵柄とは違うので、今度は違う絵柄で…というのが理想なのですが、自信を持ってお引き受けするのが難しい状態ですね…。

ですよね^^;
勿論了解ですので、もし @toki-sor1 さんの気が向くようなことがあれば、声かけてやってください。システム側はウェルカムですｗ

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で顔画像が変えられることを確認しましたー

**Comment by cocotori** [comment]
Firefoxで確認しました。
これはテンションあがりますね！
自作勢にとって、ありがたい機能だと思います。

![クリップボード](https://user-images.githubusercontent.com/42885160/86506475-8e9fa900-be0a-11ea-9f3b-d807a7012663.jpg)

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.116(64bit)にて動作確認。
正常に動作していることを確認しました。
これはやっぱり胸熱ですね！　とっても良いと思います！！（親指ｸﾞｯ

> 場合によっては、（フルセットでなく）今回のドラスレ画像や、ときのじさんのシナで作成されたものをUtil XXという形でダウンロードできるようにしておくのもあり、かも（勝手意見^^;）

なるほど、描き下ろしではなく、今までのシナリオで作成したもの等を使うというのもありですね！
ちょっとどんなイラストが使えそうか考えてみます～。

**Comment by snext1220** [comment]
皆さま、テンション上げて戴いたようでなによりです！
是非ご活用ください！！

> ちょっとどんなイラストが使えそうか考えてみます～。

ぜひぜひよろしくお願いいたします～
その際はUtilにUpさせていただきますので、ぜひお声がけください！

**Comment by toki-sor1** [comment]
第二弾顔グラとしてアップできそうなものが作れましたので、ご報告も兼ねてこちらのIssueを一旦Openさせていただきました。

原作キャラ（著作権的な意味で皆さんのオリジナルキャラ以外）＋ソーNext関連でアップしたイラストから丁度良さそうなものを加工して顔グラを作成しております。
＃ドラスレ中年FIGHTERさんは悩みましたが、原作キャラ枠に入れております（塗りつぶしミスも修正済みです）

https://onedrive.live.com/?id=4837C202555BE782%2110257&cid=4837C202555BE782
![image](https://user-images.githubusercontent.com/42646342/88683676-070a3900-d12f-11ea-85ab-e87d362212f4.png)

今後も完成したら追加する、という感じの不定期更新になると思います。
もし問題がないようでしたら、お手隙の際にUtilへのアップロードをお願いいたします。

**Comment by snext1220** [comment]
お忙しい処、ありがとうございます！
早速、stext.xmlを修正しまして、Util 4としてUpさせていただきました～
https://www.web-deli.com/sorcerian/text/util.aspx
＃ 優先順位の低いものを後ろに下げています。

テキストは暫定でもあるので、もしご要望あればstext.xmlを修正してやってくださいませ。
また、画像はstext/common/faceフォルダーにまとめておりますので、追加／差替などはこちらにお願いできれば幸いです～

> ドラスレ中年FIGHTERさんは悩みましたが、原作キャラ枠に入れております（塗りつぶしミスも修正済みです）

良いと思います！
というか、個人的には枠をあまり気にせず、過去の画像など、可能な範囲でどんどん追加していっても良いのかなと思いました（加工のお手間があるので、もちろんご無理されない範囲で、とは）

その意味では、ミニソーの画像で結構使えそうなものがありそうで、たとえば七惑星神やアド・ルー、ダルクファクト、アンナ、エステルなどなど、全然ありなのかなと…！（切り取りが難しいものもありそうなので、あくまでざっと見た感覚です^^;）

> 著作権的な意味で皆さんのオリジナルキャラ以外

なお、私のシナ関連のキャラについてはご利用いただくこと全く問題ございませんです～

**Comment by toki-sor1** [comment]
お忙しいところ、早速の反映ありがとうございました！
Util 4も確認しました！　テキストもばっちりです！！（優先順位の件も了解です！）

リオさんのシナリオ関連のキャライラスト使用について、ご快諾ありがとうございました！
今回、原作プレイキャラ中心に探り探りイラストを加工しておりましたが、**枠を気にせず他NPCや敵キャラも大丈夫そうということで、今後はそちらも視野に入れて顔グラを作成・更新していきたい**と思います～。

＃イラストはほとんどの場合がpsdファイルも取ってあるのですが、仰る通り背景の切り取りが難しい場合もあるので、不自然にならないものを選んでの加工になりそうです；

該当フォルダについても了解です！　今後利用させていただきますね！

**Comment by snext1220** [comment]
こちらこそ早速の追加ありがとうございます！
＃ 懐かしのオリジナルキャラ、グロスまで…！感謝感謝でございます＞＜

こちらでもstext.xmlを編集して、緩くグループごとに並べ替えてみました（非ソー＞ソーNPC＞ソーPC＞その他）。また、画像にtitle属性を入れて画像名もツールヒント的に表示するようにしております～ いずれも暫定なので、並べ方含めて、ご自由に修正してやって戴ければ幸いでございますm(_ _)m

あとは、ある程度追加が一段落したところで、TLでも告知していければと思っておりますので、お声がけくださいませ～（sunshineの公開から少し経った辺りで？）

**Comment by toki-sor1** [comment]
大変お待たせして申し訳ありません…！
ある程度の数の顔グラを追加できましたのでご報告いたします…！
![image](https://user-images.githubusercontent.com/42646342/92298878-65290800-ef88-11ea-940c-69362843384f.png)

絵自体のサイズや加工にバラツキが出ておりますが、描画範囲やレイヤー統合の関係で調整が難しいため、このままとさせていただきましたら助かります；

> ＃ 懐かしのオリジナルキャラ、グロスまで…！感謝感謝でございます＞＜

こちらこそご快諾いただき、とても助かりました！　ありがとうございます！
グロスさんは、企画の早い段階で描いたキャラなので、特に思い出深く印象に残っています～。
**もし皆さんのシナリオのキャラ＆私が描かせていただきましたイラストの中に、顔グラ加工OKなイラストがありましたら、お声をかけていただけると助かります～。**

> こちらでもstext.xmlを編集して、緩くグループごとに並べ替えてみました

こちらもありがとうございます！！
どのように並べようかと悩んでいたもので、リオさんに並べていただけて本当に助かりました！　画像名のヒントもナイスアイデアです！！
デフォルト顔グラも込みで番号を振っているため、こちらで少し手を入れさせていただきつつ、今回の顔グラも追加させていただきました（GitHub、サイトに反映済み）。

もし問題がないようでしたら、告知OKでございます！

**Comment by snext1220** [comment]
画像追加、stext.xmlへの反映お疲れ様です＆ありがとうございます！（画像名の修正も助かりました～）
おかげさまでラインナップも増え、使ってみたくなる感も高まりましたね～

ではIssueとしてはCloseし、別途告知してまいりますね！
