### ISSUE TITLE
すべてのシーンで共通シーンをインポートする

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#177]
■概要

+ id=99998のシーンをすべてのシーン末尾に無条件にインポートする
+ scene要素のexclude属性をtrueとした場合には自動インポートを停止

■用途

［HPがゼロになったら...］［FREE3がゼロになったら...］のような特定条件でのボタンを一律全てのシーンで表示する。

■備考

現在でも${import} を利用すればできるが、シーン数が多くなってきた時に手間である

**Comment by cocotori** [comment]
よいと思います。
気づかず99998のシーンを作ってしまって
（あまりないと思いますが・・・）
意図せずインポートしてしまわないよう、
何かしら警告が出るといいですね。

ただ、警告を出すのも大変なので
マニュアル記載だけでもいい気もします。

**Comment by toki-sor1** [comment]
> id=99998のシーンをすべてのシーン末尾に無条件にインポートする

私はそこまで必要な要素かどうか、ちょっと判断が難しいです。

戦闘が多いシナリオ、特定条件でゲームオーバーになるシナリオであれば、このインポートの実装は有効だと思います。
しかし、ゲームオーバーがないシナリオや読み物系のシナリオでは、**逆にexclude属性をtrueにする方が手間かも、と思いました。**

**Scene0など何処かのSceneで1回trueに設定すれば、以降のSceneではインポートされないという仕様**であれば大丈夫そうなのですが（そもそも、ご意図や仕様を勘違いしていたらすみません；）。

**Comment by snext1220** [comment]
言葉足らずですみません；
以下ご懸念の点、補足いたします。

> 逆にexclude属性をtrueにする方が手間かも、と思いました。

言葉足らずですみません；こちらは、99998のシーンがなければそもそもインポートされないので問題ありません。99998が存在する場合で、なおかつ、インポートしたくないシーンがある場合にexclude属性を指定いただく必要があります。

> 意図せずインポートしてしまわないよう、何かしら警告が出るといいですね。
> ただ、警告を出すのも大変なのでマニュアル記載だけでもいい気もします。

そうですね。こちらは誤ってインポートされればそもそも99998のシーンが表示されるので、ドキュメント記載だけとできるとありがたいです^^;

**Comment by toki-sor1** [comment]
> こちらは、99998のシーンがなければそもそもインポートされないので問題ありません。99998が存在する場合で、なおかつ、インポートしたくないシーンがある場合にexclude属性を指定いただく必要があります。

あわわ、すみません！　こちらこそ勘違い失礼しました…！
インポートしたくない場合は、99998のシーンさえ気を付ければ個別設定は必要ないのですね、安心しました！
ご解説ありがとうございました！

> 一応上記方針でシステム／ドキュメントともに対応し、GitHub Pagesに反映しております。問題あれば、お知らせ戴けますと幸いです。

Win8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
正常に動作しました。
ドキュメントも分かり易く書かれていて良いと思います！

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で動作することを確認しましたー
