### ISSUE TITLE
［Contact］ページの新設

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#178]
おかげさまで、開発者－プレイヤーさんを繋ぐさまざまな窓口が整備されつつあります。

+ Twitter（王さま垢）
+ GitHub（開発者フィードバック）
+ 質問箱（プレイヤーフィードバック）
+ マニュアル（ブログ）
+ アンケート（先日新設したもの）
+ その他なにかありましたっけ？

これら窓口を整備して、フィードバック先を判りやすくするのが目的です。
イメージ的には、以下のようなページを想定しています（デザインが、というわけではないのですが、まとめ方として）
https://www.typescriptlang.org/community/index.html
＃ そこまで分量があるわけではないので、現在懸案のTopページ（https://github.com/snext1220/stext/issues/117#issuecomment-515735736 ）を作成し、その末尾にまとめる方がスッキリかもしれません。

新設に際してはアイコンなど、 @toki-sor1 さんにもご相談させて戴きたく、まずはIssueとして挙げておきますm(_ _)m

**Comment by toki-sor1** [comment]
大変お待たせしてしまい、申し訳ありません…！
また、参考となるサイトも教えていただき、ありがとうございました！

- Twitter（王さま垢）・・・2種類（お好みで決めてやってください）
- GitHub（開発者フィードバック）・・・1種類
- 質問箱（プレイヤーフィードバック）・・・1種類
- マニュアル（ブログ）・・・1種類
- アンケート（先日新設したもの）・・・1種類

教えていただいたサイトのアイコンを参考に、上記アイコンを作成いたしました。
色の濃度や明度は、以前作成したアンケートアイコンに合わせていますが、薄いorもっと良い色があるという場合など、要修正箇所がありましたら修正いたします。
O/Dにアップ済みです。
https://onedrive.live.com/?id=4837C202555BE782%219428&cid=4837C202555BE782

![コンタクトアイコンサンプル](https://user-images.githubusercontent.com/42646342/80856661-b6498800-8c86-11ea-981e-9eaa1d7f8ce1.png)

> その他なにかありましたっけ？

今のところ思いつくものはありませんが、もし「これもあったらいいかも」というアイコンがありましたら、ご相談くださいませ～。

**Comment by snext1220** [comment]
お忙しいところご対応ありがとうございます！
こちらにて、まずは実装進めていこうと思うのですが、方針どうしましょうかね～

1. topページを新設してその中で統合する（影響大）
2. contactページを新設する（影響中小）
3. staffページをcontactページに改め、統合する（影響小）

個人的には、スタッフも含めた紹介＆連絡先と考えると、3. でよいかなとは思っているのですが（そもそもtopはまだサイト全体のデザインと合わせた議論が必要？）、如何なものでしょうか？？

**Comment by toki-sor1** [comment]
こちらこそお返事ありがとうございました！

> topページを新設してその中で統合する（影響大）

https://github.com/snext1220/stext/issues/117#issuecomment-625251629 でtopページのデザイン案を投稿しました。
アクセスし易い方が良いと思いますし、topページ仮デザインは全体的に画面が黒いので、こちらにアイコンを含んでも良さそうな気はします。
（しかし、アイコンの絵の部分は縮小すると崩れそうなので、余白を削る・色替えは簡単ですが、絵自体を小さくするのは難しそうですが…；）

こちらは影響大とのことですので、慎重に決めたいところですね。

> contactページを新設する（影響中小）

専用ページがあった方が見易いかなと思いつつ、ページが多くなってきているので、ちょっと悩ましいですね。
他ページに含める方が良いかもしれません。

> staffページをcontactページに改め、統合する（影響小）

確認不足、申し訳ありません…；；
staffページのデザイン案も https://github.com/snext1220/stext/issues/117#issuecomment-625251629 に投稿していたのですが、こちらの確認不足でcontactページを含まないデザインになっています；

staffページは一度見るとそこまで頻繁には見ないページだと思いますので、contactページに改めるのも良いかもしれませんね。

ただ、アクセスし易いかと言われればそうでもないので、そこが悩ましいところでしょうか；

影響の面から考えると**3. staffページをcontactページに改め、統合する（影響小）**が良いかなと思いました（アクセスし辛いのが少々気になりますが；）。

**Comment by snext1220** [comment]
お忙しいところ、早速のお返事ありがとうございます！

### contactページについて

>影響の面から考えると、3. staffページをcontactページに改め、統合する（影響小）が良いかなと思いました（アクセスし辛いのが少々気になりますが；）。

アクセスについては以下のような案もありかなと。

![無題](https://user-images.githubusercontent.com/27911337/81377928-6284e600-9141-11ea-884e-e778235330bd.png)

右サイドバーとして、作成いただいたアイコンを並べて見せる感じです（レイアウト上、説明はくわえられないので、Manual、Twitterなどの文字をアイコンに追加する必要があるかもしれません）。

サイト改修の際に、ワンカラム型のレイアウトにしたことから、サイトそのものがこじんまりとしてしまったな～と（幅広のディスプレイで見ると、中央に手狭な感じ）。
右サイドバーを追加することで、その辺も解消できるかなと考えています。
＃モバイル環境でワンカラムに戻せるようにしなくてはなりませんが。

### メイン領域の幅について

こじんまりという意味では、そもそもメイン領域の幅が現在550pxと、一般的なサイトと比べても狭いので、**650～800px程度まで広げても良い**かもしれません（以下は800pxの例）。ただ、その場合は既存のバナーをリサイズする必要はあるのですが…；

![無題2](https://user-images.githubusercontent.com/27911337/81377950-6ca6e480-9141-11ea-9dc1-2108ec098475.png)

### Topページについて

影響の面から＞については、ページを一つ追加するので、作業工数が大きめという意味でしたが、Topページを進めるのであれば、これらと統合するのもありかもしれません。

ただ、Topページを設置した場合に「～/text/」へのアクセスで、こちらを表示することになると思うのですが、Scenarioページにアクセスできた方が手早いので、悩ましいという…；

＃以前も（Topページではないですが）AboutページをTop代わりにしていたところ、RYUさんからシナページをTopにした方が使いやすいという指摘があり、変更した経緯があります。

さりとて、「～/text/」に紐づけずにTopページだけ設けるのも中途半端ですしね...

### 進め方について

> #117 (comment) でtopページのデザイン案を投稿しました。

別Issueでのデザインもありがとうございました！
こちら、外枠を外したメイン領域のデザインを戴いたのですが、 @toki-sor1 さん的には 外枠のデザインはママというご方針でしょうか。以前、yuncoさんとのお話でも、テイスト一新を目的としたリニューアルになるのかな、と思っていたもので、少々気になった次第でした（以下、過去引用）。

> 初訪問時、ソーサリアンつながりで知ったことを加味したとしても、現状のデザインは「ソーサリアン」層のみに作られているように見えます。ときのじさんの悩みとリンクしますが「約30年前のゲーム」のロゴやデザインをそのまま踏襲しているため「思い出で遊びたい」層には非常に刺さりますが、それ以外の層は置いてけぼり感は否めません。ネクストサイトとのカブり感というのも意図的ではないのなら、剣と魔法のファンタジー感は残しつつ、現代風にリデザインしたらどうでしょう。（詳細後述）

おそらく外枠のデザインをそのままにメイン領域だけを改めても、全体イメージはあまり変わらないように思えますし^^;、まずは外枠を優先してリデザインしていった方がよいのではないかなと、と、と。

一方、メイン領域はどうしてもプログラム的な要素がありますので、構造はできるだけ全ページ再利用可能な形＆テキスト中心にしていった方がよいのかなと感じました。
＃極端には、タイトル部分の背景を新デザインに合わせる、必要であればテキスト領域に透かし的な背景を入れる程度でも良いのかなと思います（もちろん、Scenario／（設ける場合）Topなど中心となるページは、個別のレイアウトになっていくのかなと思いますが；）

手を入れるとなると、大きな修正になりそうでしたので、基本的な方針面の確認になってしまい、スミマセン...；あとは、大きな変更になった場合、どこでリリースかけるかも要ご相談ですね（2周年とぶつかると、かなりつらいことになりそうなので；）

長文になってしまいましたが、引き続きどうぞよろしくお願いいたします！

**Comment by snext1220** [comment]
Ｄにてご質問の件、若干長文になってしまったので、こちらに移させていただきますね。

> こちらのissueにある「外枠」についてですが、外枠＝メイン領域外（背景）という認識で合っていますでしょうか？

外枠＝メイン領域外＞言葉足らずですみません。はい、そのご認識で問題ございません！大雑把に白背景部分がメイン領域とお考えいただければ大丈夫かと…！

> また、外枠にもし手を加えるとしたら、どんなことが可能なのでしょうか？

こちらも大雑把にはなってしまいますが、背景、メニュー（ヘッダー）、フッターはじめ、上でも話題に出ましたがサイドメニューのような追加要素も加えることは可能です（ただし、メニュー部分はライブラリの関係でできることが限定される可能性はあり；）。

基本やれるかやれないかという意味ではなんでもできてしまうのですが^^;、あとは、どこまで後々の更新を妨げないか、サイト共通で再利用できる割合が多いか、などのポイントから「現実的にできるか」のご相談になるかと思います～

メイン領域も必要最小限で、と言ってしまいましたが、同じ理由からサイト全体（または大部分で）共通化できるレイアウトであれば一括して手を入れるのはアリとは思っております！（ただし、もともとがテキスト中心のサイトなので、読みやすさという意味でも、今後の更改の枷にしないという意味でも、ある程度シンプルさを保っておいた方が無難とは^^;）

ざざっと書いてまいりましたが、回答になっておりますでしょうか？？
ご不明な点はなんなりとお聞きくださいませm(_ _)m

**Comment by toki-sor1** [comment]
こちらこそ細やかなご返信＆ご回答ありがとうございました！
お手数をお掛けしてばかりですみません；
DMでいただいたご意見についても含めてお返事してゆきますね～。

### contactページについて
リオさんのご提案を参考に、Battle Sheetと同じようにしてみたら良いかもと思い、下のサンプルを作成しました。
<img src="https://user-images.githubusercontent.com/42646342/81473713-4bc2ba00-923b-11ea-916f-ba25eae40195.png" width="300">
> 【DM引用】Contactのタブを右端に置くならば、そろそろPlayer Rankingはサイトからは外しても良いかもしれませんね（隠れてしまうので悩ましくはありますが^^;）

はい～、Player Rankingはテイストが不揃いのものの一つなので、**サイトから外すのも良いと思います。**
ただ、Player Ranking自体は、何処かに残して欲しいなと思っていたりも…。
***
### メイン領域の幅について
私もメイン領域がこじんまりしていると感じたので、**650～800px程度まで広げること自体は良いなと思っています。**

しかし、すみません、バナーリサイズにより絵やフォントの配置修正、テクスチャーの継ぎ接ぎ等の必要がありますので、**できればバナーリサイズは後に回していただけるとありがたいです；**（申し訳ありません…；）
***
### Topページについて
> Topを設置した場合には、「～/text/」へのアクセスでも、こちらを表示することになると思うのですが、Scenarioページにアクセスできた方が手早いのではないかと…；

まさに仰る通りで；
シナリオ公開→すぐ遊べるScenarioページにアクセスという方が、プレイヤー側としても便利でストレスもなくて良いですもんね～。
**topページは新設しない**に意見を変えます～。

> 【DM引用】当初30thロゴは一年経過したところで除去のようなお話もありましたが、どうしましょうか（30周年の時に作成したという意味では正しいのですが、リニュ画面で前面に出すかは要ご相談）

そうですね、今回のサンプルだと30周年を記念してリニューアルしたような感じになっていますね；
**リニュ用に新しいロゴ作成の方針で考えてみました。**
<img src="https://user-images.githubusercontent.com/42646342/81474347-c7266a80-923f-11ea-8781-6548921e9ec6.png" width="300">　<img src="https://user-images.githubusercontent.com/42646342/81474360-defdee80-923f-11ea-909b-2f747da5eabd.png" width="100">

新規ロゴについては、シンプルで古すぎないを目標に、まずは剣を…と決めて、そこからロゴっぽくまとめようと円形の線を足してみたものの、**ありがちなシルエット**なような気がしてなりません；

あとは星（魔法）を入れたり、蔦っぽいものも入れたらどうだろうと考えていましたが、**技術的な問題もあり、どうしたものかと頭を抱えている状態です；**
***
### 進め方について
お忙しいところ、外枠についてご説明いただきありがとうございました！

> こちら、外枠を外したメイン領域のデザインを戴いたのですが、～

す、すみません、こちらの勘違いでtopページはメイン領域なし、その他ページはメイン領域ありというようにデザインしておりました…；

ご説明いただき、外枠でできることや再利用できること優先等、詳しいことが分かりました。
認識を改め、まず外枠のデザインを考えてみました。

- 背景は、ヘッダーと同系色＋黒のグラデで旧デザインとの差別化
- A long～＋新規ロゴ＋テクスチャ追加で変化を
  - こちらはページ背景色黒に、上記の要素を足した壁紙（左右に繰り返し・ページ下固定？）を重ねるイメージです
- サイドバーの[Contact]は、ヘッダー色＋その反対の色で目立つように

> 一方、メイン領域はどうしてもプログラム的な要素がありますので、構造はできるだけ全ページ再利用可能な形＆テキスト中心にしていった方が～

そうですね、こちらは一部の素材に手を入れる等、**新デザインに合わせて少し手を入れる程度**でも印象が違ってくると思います。
**メイン領域は、まずタイトル部分の背景を新デザインに合わせる方向でいきますか～。**
***
### その他
> 【DM引用】アイコンのテイストが不ぞろいなので統一させたい、というお話も以前に伺っておりましたが、その辺では何か修正ございますでしょうか。

DMでお先にお知らせしておりましたが、アイコン系リニュは数が多くて手が回らない可能性があるので、こちらは**優先度：低**です；

クリアダイアログもテイスト不揃いで気になっていたので、今回のリデザイン作業の延長で作り直してみました（GitHub上げ直し、申し訳ありませんでした；）。
![dialog_bonus_back](https://user-images.githubusercontent.com/42646342/81475543-e923eb00-9247-11ea-9959-7446e107663e.png)

ひえぇ…こちらこそ長文になってしまいました…（大汗）
読み辛い文章で大変恐縮ですが、引き続きよろしくお願いいたします…！

**Comment by snext1220** [comment]
こちらこそ早速のご対応ありがとうございました～

#### contactページについて

ご提案ありがとうございます。
contactページについては、まずは優先事項と思われたので、全体デザインに先立って、本番サイトにも反映させていただきました。ゲーム画面との統一感もあり、アクセスもしやすくでよい感じになったのではないかと…！

#### Player Rank

> ただ、Player Ranking自体は、何処かに残して欲しいなと思っていたりも…。

こちら先の改定でゲーム画面に統合しておりますが、サイト本体に、というリクエストでしょうか？Scenarioページであれば、ご指定いただければ残すのは可能なので、お手数ですが、全体デザインの中でご検討戴ければ助かります～（他ページでもできますが、コードの対応は必要になりそう）

#### メイン領域の幅について

こちらも優先事項と思われましたので、700pxに広げました。
Scenarioページだけであればもう少し広げても良かったのですが、他ページもあるので、このくらいで（他のニュースサイトのメイン領域幅と同等くらいのはず）。

伴い、テキストサイズもそのままだと行あたりの文字数が多すぎるので、大きく修正しています（ゲーム画面と同じなので、統一感は出たのかなと^^;）。

>しかし、すみません、バナーリサイズにより絵やフォントの配置修正、テクスチャーの継ぎ接ぎ等の必要がありますので、できればバナーリサイズは後に回していただけるとありがたいです；（申し訳ありません…；）

承知いたしました！広げた感じ、そこまで違和感は出ていないので、大丈夫だと思います～（見る人が見ると気になるかもしれませんが、優先順位は低いかと^^;）

ちなみに、ゲーム画面はテキストの横幅を抑えるために、例外的に600pxとしています（マージン等の関係で、結果的にはサイト本体とテキスト領域の幅は同等のはず）。
＃これ以上にもできますが、初期（再起動）画面のズレがごまかせなくりそう；

#### Topページについて

> topページは新設しないに意見を変えます～。

了解です＆ありがとうございます！
＃ ときのじさんも仰っていたように、サイトとしての収まりはTopがあった方が良いので悩ましくはあるのですが^^; 引き続き検討してまいりましょう～

#### 進め方について

新規ロゴ、デザイン案ともどもありがとうございます！
こちらは、スタッフの皆さまはもちろん、yuncoさんのご意見も戴きながら、ブラッシュアップしてまいりましょう～
＃ロゴについて良い改善案を考えてみたのですが、現時点で良い代案が思い至らず^^;

現時点では、一点のみ背景についてです。
お陰様でイメージ的には良くなったのですが、横幅のあるディスプレイ＆スクロールの発生する画面ですと、繰り返しが発生してしまうかも？（それを避けるならば右＆下側は黒、背景画像は左上に付ける配置にできるのが望ましそうです～）

> DMでお先にお知らせしておりましたが、アイコン系リニュは数が多くて手が回らない可能性があるので、こちらは優先度：低です；

了解です！
サイト改定は本格的にやると大工数になるので、コアの個所から段階的に入替してまいりましょう。ご相談いただければ、関連するコードの入替などもタイミング合わせて対応してまいりますので、お申し付けください。

ではでは、こちらも長文になってしまいましたが、引き続きよろしくお願いいたします！

**Comment by toki-sor1** [comment]
お返事ありがとうございます！

> ゲーム画面との統一感もあり、アクセスもしやすくでよい感じになったのではないかと…！

GitHubのにゃんこが若干もっちりしていますが（笑）、試行錯誤しながらドットを打っていたので、お褒めいただいて嬉しいです～！

> 追記：あ、既存の機能、見た目で賄えるものは、このぺーじのこんな見た目で、と仰って頂ければ、こちらでも作成できますので、お気軽にお申し付けください（モックページの作成も大変かと思われたので念のため^^;）。カラーなど指定ある場合もカラー番号戴ければ大丈夫です～

承知しました！
その際は、よろしくお願いいたします～！

逆に、**この部分のカラー番号（フォント）は○○だよ**等のご指定がありましたら、仰ってくださいませ～。
素材作成時にスクショから色を拾っているのですが、拾う箇所によって若干色味が異なっていることも多く、フォントも目視でそれっぽいものを選んでいますので、カラー番号（フォント）もご指定いただけると確実です～。
***
https://github.com/snext1220/stext/issues/117 の内容をこちらのIssueに分散させてしまったので（申し訳ありません；）、**Linkページについて以降の返信は、「サイト構造＆見直しなど」に移させていただきますね。**

**Comment by snext1220** [comment]
本Issueについては特にご意見なさそうなので、これにてCloseとしてまいりますね。
サイトリニューアルの残課題については、引き続き #117 で宜しくお願いいたしますm(_ _)m
