### ISSUE TITLE
【Playground Flow】グリッド表でのid値検証

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#179]
https://github.com/snext1220/snext-management/issues/18#issuecomment-612367219 を受けてのIsueです。

> ・敵のIDはm+数字で書かないと機能しないのですが、数字だけで書いても入力、シーン指定できてしまうので、あとで混乱しました。

アイテム、フラグ、敵、実績のid値を入力値にチェックし、適切なプレフィックスがついていないものに対してエラーを表示するようにしています。GitHubのみ反映済みです。

すべてのチェックは（主にメンテナンス的な意味で）難しいかもしれませんが、「この辺は間違えやすい」などあれば、本Issueにてぜひお教えください。

**Comment by cocotori** [comment]
警告が出るのはわかりやすくていいですね。

ただ警告が出る状態でもタブを移動できるので、

例えばフラグのタブで間違ってn01と入力して、
敵のタブに移動して、入力しようとすると
「idは「f～」形式で入力してください」と表示されて
少し混乱するので、
「フラグのidは「f～」形式で入力してください」等に
してくれると更に親切かと思いました。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 81.0.4044.129(64bit)にて動作確認。
警告が表示されることで、自分が何を間違えたのかすぐに分かるところが良いと思います。

> 「フラグのidは「f～」形式で入力してください」等に
してくれると更に親切かと思いました。

確かに現在ではタブを移動しても他のタブの警告が表示されるので、ちょっと混乱しちゃいますね。
ココさんのご意見に賛成です！

**Comment by snext1220** [comment]
ご確認ありがとうございます。
メッセージ表示については現在共通になっているため、ばらす改定をかけたいと思います。
お待ちください。

**Comment by cocotori** [comment]
確認しました。
よりわかりやすくなったと思います！

**Comment by toki-sor1** [comment]
Win8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
正常に表示されていました。分かり易くなって良いと思います！

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で問題ないことを確認しましたー
