### ISSUE TITLE
［戻る］ボタンの廃止

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#18]
**著しく互換性を損なう可能性がある修正になります（特にドラスレは影響甚大）。まずは問題として提示していますが、システム内部の影響要調査のため、言うことが二転三転したらスミマセン**

stars、free1／2の導入によって、［戻る］での移動によって何度も該当ステが加減算されるなど、問題が出始めています。今後、自動化を進めていくと、更に問題が顕著になっていくと思われます。

もともと［戻る］は潜在的な問題も多かった機能なので、この辺で廃止できればと。

### 代案

ないわけではないですが、正直避けたいものばかりでは。

+ ［戻る］時にはstars属性などによる更新を無効化することは可能かも？（ただし、実装が複雑化する上、2個以上戻った時には同じことなので悩ましい。加算済みのシーンを記録するのは影響が大きすぎるのでお許しを）
+ シナリオ単位に［戻る］の有効／無効を選ばせる（こちらも、ルールの混在という意味でも、システムが複雑化するという意味でも、あまり気が進みません；）

#### createScene: function(scene_num, cond)

createScene: function(scene_num, info)
+ prev：前sceneのid値
+ reverse：戻るによる移動か
+ cond：移動時の条件式

reverse時、prevロールバック、currentシーンの処理は行わない

#### updateXxxxx

+ Util.updateItems(scene.attr('items'));
+ Util.updateFlags(scene.attr('flags'));
+ Util.updateStars(scene.attr('stars'));
+ Util.updateFrees(scene.attr('free1'), scene.attr('free2'));
+ Util.updateResults(scene.attr('result')); …ロールバック不要

var cond = (item.indexOf('-') === 0);
if (reverse) { cond = !cond; }
if (cond) { ... }

+ 星はもとにもどせない！
+ updateStarsByMagicは元に戻せない（何で移動したかが不明）

**Comment by cocotori** [comment]
戻るボタンを認めるとかなり管理が大変というのはわかりますので、
禁止に一票です。

ドラスレのようにすでに使っているシナリオを
どうするのか悩ましいところですが。
バージョン管理で、古いのは戻るボタン有効で、
これから作る新しいものは使用禁止とかできますかね？
（古いもの、というかドラスレだけ例外的に開放する感じ、とか）
複雑になりそうだな・・・

**Comment by snext1220** [comment]
バージョン管理＞仰る通り、コードが複雑になるので、悩ましいですね…；
Ver.1、2という形で完全にわけてしまうのはありですが、

+ すべてのファイルを二重化しなければならない
+ Ver.1は現在の機能で凍結となり、Ver.2の新機能は利用できない

などこれまた悩ましく。
戦闘システム（自動化？）など大きな仕様変更では、どこかでバージョンを分ける時は出てくるかなと思っていますが、いわゆるメジャーバージョンアップまでは避けておきたいですね；；

ちなみに、［戻る］禁止はシステム側にとってはありがたいのですが、実際に遊んでいる時に一寸戻りたいということって、あまりないですかね？この辺が頻繁に発生しているようだと、操作性が激しく低下するはずなので、悩ましいなと＞皆さん

**Comment by RYU-DS** [comment]
そのスレの事は気にしていただかなくても大丈夫です。
元々「戻る」機能は無くなる前提でやっていて、それまでの「持たせ」のつもりで組み込んでます。
「ポップアップチュートリアル」や「真（偽？）戻る」といった本当の解決が図られれば問題ないのですが、その前にとなると苦しいですが。

ただ、プレイ側として見た戻る機能の廃止は、「プレイヤーが激減する可能性がある」という事はお伝えしておいた方がいいかもしれません。
難易度と自由度が大幅に上昇/低下するので、コレを頼みにしていた人はまずやめると思います。
さらにゲームブックとしての体を失う要素でもあるため、非難を受けやすい（叩きやすい）というのもそれを後押しするでしょう。
しかし、自動化を進める事もeゲームブックとしての立場を固めるためには必要な事ではあるので、それによって得るユーザーが減少分を上回ると期待してやるしかないとは思いますが…

**Comment by snext1220** [comment]
> プレイ側として見た戻る機能の廃止は、「プレイヤーが激減する可能性がある」

仰る通り、この件が一番の懸案です。

他Issueの通り、ロールバック機能も検討しておりますが、対応工数が大きいのは勿論、「できない新機能」も増えてくるので、悩ましいところですね...既に［戻る］の問題は潜在的に幾つかありますので、個人的には
**制約が増えるのは許容しつつ、ロールバック機能を実装する（＝［戻る］機能を残す）**
に傾きつつあります。 ※かなり首はしまった気もします^^;

ポップアップ系の機能については、スミマセン、STextの全体方針としてモバイルでの制御が困難という理由から、廃止の方向で動いており、今後も対応はないかと思います。ヘルプについては、別シナとして立ち上げ、シナリオ内リンクから別タブ（ウィンドウ）という形でのご対応をお願いできますとm(_ _)m（ポップアップかタブか、という違いで、同じデザインの中で表示されるので、比較的ご要望に沿いやすいのではないかと）

真戻るについては、 #24 で議論中なので、お手数ですが、そちらで具体的な用途例などと合わせて、ご意見頂戴できれば。ヘルプは上記の理由から消極的なのですが、用途によっては、他の方からも「欲しい！」が出てくるかなと。

**Comment by RYU-DS** [comment]
ヘルプウィンドウはマップやフロチャを出したり、できればステータスウィンドウも出したい（既に簡易で対応されていますが）、と使い道はいろいろあると思います。
自分のこだわりはプレイヤーがどうやってその状態を作るか（現プレイ画面から離れずに）なんですが…これもブラウザ側の設定とからむので難しいでしょうか。
であれば、どこから再開しても必ず表示される位置に「このヘルプウィンドウを出してプレイしてください」というリンクを貼れるようにしたいのですが、可能ですかね？

**Comment by snext1220** [comment]
本件は皆さんの意見が割れており、正直悩んでいます。
ただ、議論も長引いてきたので［Expired soon］とし、一旦、［Confirmed］か［wontfix］からの判断をしたいと思っています。

現時点で、システム側としては
+ ［戻る］によってプレイヤー側の操作性が低下するというご意見は納得
+ ロールバックによるシナリオ開発側の制約はあるが、致命的ではない
との判断から、
**制約が増えるのは許容しつつ、ロールバック機能を実装する（＝［戻る］機能を残す）**
方向で検討できればと考えています（但し、具体的な実装で問題が出る可能性があるため、調査結果によっては実装不可となるかも）。

お手数ですが、引き続きご意見頂戴できれば幸いです（単にフェイスマークで［+1］でも構いません）。ある程度賛同が得られれば［Confirmed］に、大きく意見が分かれる場合は［wontfix］としてまいります。

**Comment by RYU-DS** [comment]
私はやはり「戻る」機能を残す事に賛成します。
ゲームブックらしく、ある程度はプレイヤーに遊び方の幅を残すべき、というのが私のstext＝eゲームブックに対して求めるスタンスだからです。
これは各自動化に関しても、あくまで利便性としての半自動化にとどめて、やはり「プレイヤーが手動で簡単にそれを元に戻せる」程度のものであるべきとも思っています。

ただし、幅＝自由には責任がつきまとうのも当然の事として「戻る」を行う事による不具合は一切関知しない、という姿勢もハッキリ明示するべきとも。
なので制作側がその負担を背負う必要は無いという考えです。
※ゲームの継続に致命的な事態を避けるために、シ－ン毎に「ここで戻ると危険（赤字）～戻って大丈夫（青字）」のような警告を出す、くらいはしてもいいかもしれませんが。

また現状そのスレのチュートリアルはフラグで管理しているため、関係無いものは読めなくなっており、結果的に現状が大変都合よくなっているのでそれも理由の１つであるという事は、一応言及しておきたいと思います。

**Comment by snext1220** [comment]
スミマセン、2点確認です。

+ ロールバック機能の実装は反対、というご意見？
+ ［戻る］機能を残すとのことなので、現状から特に動かさない（自動化機能の程度は今後別途相談だとは思いますが）というご意見で？

### 補足

基本、半自動化については賛成です。
テクニック集のドキュメントでも触れていますが、まさに仰る理由から、完全自動化はSTextにそぐわないと思っています。ただ、既に`<scene>`要素の各種属性で半自動化が進んでおり、プレイヤーが元に戻すのは難しくなっています（特に魔法行使の減算をプレイヤーに戻させるのは酷かと。items／flagsのように、そもそもプレイヤーが元に戻せない要素もありますし）。しかも、stars、free1、free2などの属性は気付かずに戻る／進むを繰り返すと、トンデモな数値になってしまうという；

これまではプレイヤーの自己責任と言っても許容できる範囲でしたが、そろそろバグと言われてもおかしくない領域に入ってきているようには感じます（自分の首をどんどん絞めてる^^;）。
＃ シナ開発者の方にはそれなりに仕組みを把握して戴きたい、というスタンスですが、プレイヤーに同等の意識を求めるのはあまり、ですかね...

**Comment by RYU-DS** [comment]
すいません、ロールバックと現在の「戻る」の違いをよくわかっていませんでしたｗ
上記で大体理解しましたので、ロールバックと現在の「戻る」のどちらでもよいと思います。
またあくまで希望であって、戻る系機能の消失は自分のシナリオ制作においてはそれほど重大な影響は無いので、どうしても反対というほどではありません（戦闘式の固定化などに比べればはるかに）。

＞これまではプレイヤーの自己責任と言っても許容できる範囲でしたが
プレイヤーの利便性の拡大（としての戻るの公的許容を含む）により、自己責任もまた拡大するというのは公正かつ理にかなっているので、すべて自己責任でOKと考えます。
というか現状でも複数fや一方通行シーンによって「戻ると継続不能」がそこら中にあるので…
…ん？あれ？そのスレだけですかね？

**Comment by snext1220** [comment]
上記コメ（https://github.com/snext1220/stext/issues/18#issuecomment-427624691 ）の方針で［戻る］機能を実装しました。GitHub Pagesにも反映済みです。

なお、本機能の実装に当たって、単純に［戻る］だけでなく、各シーンでの自動更新（scene要素の各属性）の実装も見直し、変更しています。テストに当たっては、それら共々確認をお願いします。

**Comment by snext1220** [comment]
@toki-sor1 さんよりＤにてご質問戴いておりましたが、共有のため、こちらに移動しております。

> 【ご質問】テストは途中なのですが、欠片などを手動で増減させてから次のシーンに進み、前のシーンに戻ると、手動で欠片を増減させる前の数値になっていました。これも仕様なのでしょうか？

はい、仕様です。現時点では、シーンを移動するタイミングで、その時点でのセーブデータを複製しているので、シーンの中での変更は反映されません。

もちろん、ダイアログ保存時の情報も履歴として複製していくことはできるのですが、保存のたびに履歴が一つ増える＆将来的に戦闘半自動を実装した場合には、ボタンクリックの都度、履歴が一つ増えるので、現状位が適当かな、と。如何でしょう？^^;

**Comment by toki-sor1** [comment]
質問の移動とご回答、ありがとうございました。

> テストは途中なのですが、欠片などを手動で増減させてから次のシーンに進み、前のシーンに戻ると、手動で欠片を増減させる前の数値になっていました。これも仕様なのでしょうか？

こちら仕様とのことで、承知しました。
将来的なことを考えると、現状位が丁度良さそうですね。

現在はまだ半自動化の途中で、シナリオ自体も手動操作を必要とする場面があるため、
今回はテストをしていて心配だったのですが、これから半自動化が進み、操作にも
慣れてゆけば、気にならなくなると思います。

**Comment by snext1220** [comment]
ご確認ありがとうございます！［戻る］に伴うロールバック機能はまだまだ手探り状態なので、お気づきの点はなんなりとお願いしますm(_ _)m

手動操作＞はい、戦闘半自動化を進めれば、最終的?にはFreeXを更新する時、アイテム／フラグ／メモなどを確認する時など、かなり限定的になるのかなという思惑も。ただ、過渡期的な現状では、まだまだ「その動き直観的でない」はあるかと思いますので、ご意見戴きながら調整していきたいと思います～

### 注意

ゲーム復元時に履歴が記録されていないエラーを発見しましたので、先ほど修正しました。
