### ISSUE TITLE
【Playground Flow】漢数字の一が表示されない

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#180]
https://github.com/snext1220/snext-management/issues/18#issuecomment-612367219 を受けてのIsueです。

> ・漢数字の「一」が見えません。Playground Editorでは普通に見えます。

こちらフォントスタイルの調整をし、暫定的に改善しておりますので、ご確認ください（GitHubのみ反映）。日本語入力時に前に制御文字が表示されてしまう問題は依然として残っておりますが（やや反則なのですが）、まずはクリティカルな問題（＝文字が正しく表示されない）から改善を図っています。

**Comment by cocotori** [comment]
確認しました。
気になってはいたので、修正ありがたいです。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeの環境で問題ないことを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 81.0.4044.129(64bit)にて動作確認。
きちんと「一」が表示されるようになりました。
シナリオでよく漢数字を使うので、修正していただけて助かりました。
