### ISSUE TITLE
【Playground Flow】データ飛び、文字化け等の不具合報告

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#181]
https://github.com/snext1220/snext-management/issues/18#issuecomment-612367219 を受けてのIsueです。

> ・フラグの有無による条件分岐を指定しようとすると、表示がおかしくなります。ここのところは結局XMLエディターで作りました。
> ・途中何度かデータが飛ぶことがありました。テストモードを実行して飛び先が見えなかったのでFlowに戻って作業しようとしたら、47とか90パラグラフ以降が消えているという現象が起きました。ただ、再現性はよくわかりません。もしかしたら私が古いデータを読み込んでしまっただけかもしれません。
...
>先日起きた現象です。確か、Playground Flow上でリンクのタブにある条件式のボックスを選択すると左からフラグ等のタグが出てきますが、そこでf01などを選択すると、下のボックスに文字化けしたような文字列が出て、確定させても機能しない文字列が条件式のボックスに転写されるという現象だったと思います。
>ただ、今確認したところ、再現できませんでした。もともとインポートした私のデータがおかしかったのかもしれません。

こちらは現時点で再現条件が確認できないため、様子見しています（GBATの相性の可能性もありそうです）。同様の問題が発生した場合には、お手数ですが、発生した時の

+ シナリオデータ（.json、.xmlなど）
+ 発生条件（前後で行った手順とscene番号など）

をお知らせいただければ幸いです。本Issueは、問題連絡用に暫くOpenしておきます。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 81.0.4044.129(64bit)にて動作確認。
こちらも以前GBATで作ったシナリオ「魂（2018年10月作成）」をPlaygrand Editorで読み込んで試しました。
しかし、FlowとEditorを行ったり来たりしながら条件式の辺りをいじってみたものの、問題の再現には至りませんでした…。

**Comment by snext1220** [comment]
検証ありがとうございます！
GBAT、PgEditor、PgFlow、テキストエディタ―と環境が多岐に及んでいるため、組み合わせを考えると、正直発生条件の確認が困難になっていますね；（特にGBATは既にほぼ見ていないため）今後問題起こったところでの再確認とし、今回はCloseしてまいります。
