### ISSUE TITLE
【Playground Flow】ダイアログからのリンク追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#182]
https://github.com/snext1220/snext-management/issues/18#issuecomment-612367219 を受けてのIsueです。

> ・リンクを張るときはフローチャート上で直接ドラッグするしかできないのでしょうか？テキストで跳び先のパラグラフを指定できると便利に思います。

本件、以下内容で対応しております（GitHubのみ反映）。

+ ［シーン］タブから［リンク追加］ボタンを押す
+  ダイアログで［キャプション］［リンク先］を入力
+ フロチャに反映

今後ご要望に応じて通常以外のリンクについても対応していきたいと思います。

**Comment by cocotori** [comment]
確認しました。
大変便利だと思います！
離れたノード同士をつなぐとき、結構たいへんだったので・・・

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで問題ないことを確認しました！

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 81.0.4044.129(64bit)にて動作確認。
正常に動作しました。
今までがマウスの使用を前提とした操作でもあったので、今回の改善により利用者の環境を選ばない仕様になって良いなと思いました～。
