### ISSUE TITLE
【Playground Flow】フロチャの拡大率維持＆領域拡大

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#183]
https://github.com/snext1220/snext-management/issues/18#issuecomment-612367219 を受けてのIsueです。

> ・左側のフローチャートが小さくて見づらいです。拡大しても右側のエディタをいじると都度縮小してしまいます。また、モニタの大きさに合わせてフィールドの広さや解像度を上げることはできないのでしょうか？

以下の対応を実施いたしました（GitHub）。

+ ブラウザのウィンドウサイズに応じてフロチャ領域を拡大
+ 更新前後での拡大率の維持

ウィンドウサイズの変更によってフロチャの拡大率も変化する問題はありますが、ウィンドウ自体を動かすことはさほど頻度も多くないと考え、現時点ではママとさせていただいております。如何でしょうか。

UI周辺は感覚的なものもありますため、皆さんのご意見いただきながら徐々に調整していければと思っています。

**Comment by cocotori** [comment]
この機能、欲しかったんですよ！
フローチャート領域が狭くて、作業のしにくさを感じていたので、
広くなってくれてとても嬉しいです。

ただ、ボタンや右のテキスト領域まで大きくなって
やや野暮ったい感じがしないでもないので、
そちらは今まで通りのサイズでもいいかもです。
大きくなることで困るわけではないので、
個別に制御するのが大変、とかであればこのままでも大丈夫です。


更新前後の拡大率の維持もいい感じです。
何か作業したときに今まで編集していた部分を
見失ってしまうのはやはりストレスになるかと思うので、
それがなくなったのは大変良いと思います。

ただ、更新後のノードやリンクの位置で気になることがあります。
おそらく、ノード名などを更新した後、
そのノードがフローチャート図の中央に来るように
制御しているのかなと思います。
通常はいいのですが、一定以上拡大率を上げた後に更新すると、
中央に来ずに、左上とか左下とかに移動してしまいます。
これはなんとかならないでしょうか？

**Comment by toki-sor1** [comment]
> ブラウザのウィンドウサイズに応じてフロチャ領域を拡大
更新前後での拡大率の維持

Win 8.1／Chrome 81.0.4044.129(64bit)にて動作確認。
どちらも動作することを確認しました。

パラグラフが多めのシナリオでは、拡大機能を利用する頻度が高いので、**更新前後も拡大率が維持されるのは良いですね。**

左側のフロチャ画面のことではないのですが、**右側のエディタ画面で敵タブの右端がスクロールしないと見られない**のは、敵情報を削除したい時に**ちょっと分かりにくい印象を受けました。**
***
> 通常はいいのですが、一定以上拡大率を上げた後に更新すると、
中央に来ずに、左上とか左下とかに移動してしまいます。

私の環境でも同じ挙動をすることを確認しました。
確かにこれはノードを見失ってしまう原因になるので気になりますね。

**Comment by snext1220** [comment]
まずは使いでよくなったようで良かったです。

> 通常はいいのですが、一定以上拡大率を上げた後に更新すると、中央に来ずに、左上とか左下とかに移動してしまいます。

こちら別途確認いたします！

> ただ、ボタンや右のテキスト領域まで大きくなって～

こちらは右のタブ領域はそのままになっているはずなのですが、スミマセン、私が認識できていないかもしれませんので、今一度お教えいただいてもよろしいでしょうか？＞＜

> 左側のフロチャ画面のことではないのですが、右側のエディタ画面で敵タブの右端がスクロールしないと見られないのは、敵情報を削除したい時にちょっと分かりにくい印象を受けました。

こちらは決めの問題にはなりますが、削除ボタンを左端に持ってくるかですかね～
現時点ではあまり利用しない（＆その方が一般的かな）との判断で、右端に配置しておりました。
お手数ですが、皆さんのご意見うかがい決めていければとm(_ _)m

**Comment by cocotori** [comment]
どうも、Chromeだと右側の領域まで大きくなってしまうみたいです。
念の為キャッシュの削除も行ってみましたが、変わりませんでした。

![クリップボード1](https://user-images.githubusercontent.com/42885160/81075300-1eb59500-8f25-11ea-9fb3-e6bd2cbae65b.png)


下はEdgeで確認した画像です。こちらは問題ありませんでした。

![クリップボード2](https://user-images.githubusercontent.com/42885160/81075324-28d79380-8f25-11ea-8a62-18a03e38373d.png)

原因がブラウザ依存ということなら、
避けることもできますので
優先度を下げてもらっても大丈夫です。

**Comment by snext1220** [comment]
ご連絡ありがとうございます！
ただ、私の方もChrome  80.0.3987.163（64bit）なのですが、Edge同様の表示になっており、再現しませんで...もう少し見てみますが、他の方でも同様の現象が起こるようでしたらお教え戴けますと幸いです。

**Comment by toki-sor1** [comment]
> - ブラウザのウィンドウサイズに応じてフロチャ領域を拡大
> - 更新前後での拡大率の維持

Win8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
両方とも正常に動作しました。

> どうも、Chromeだと右側の領域まで大きくなってしまうみたいです。

こちらの環境では、右側のエディタ領域は大きくならず、左側のフロチャ領域のみ大きくなりました。
意図した挙動ということで、こちらは問題ありませんでした。
***
> こちらは決めの問題にはなりますが、削除ボタンを左端に持ってくるかですかね～

以前はちょっと分りにくいと書いたのですが、左端に削除ボタンがあると、誤操作の原因にもなりそうですね；
意見が変わってしまい申し訳ありませんが、**削除ボタンは今までと同じ右端が良い**と思いました。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

右のエディタ領域、については原因不明ではあるのですが、 @toki-sor1 さん、私の環境で問題出ず＆致命的ではない、ということで、一旦はママとさせてくださいませ。

＃ @cocotori さんの方は現在も変わらず、でしょうか。もし改善されているようであれば、お手数ですが、ＤでもこちらのIssueでもお知らせいただければ幸いですm(_ _)m

削除ボタン＞こちらも承知いたしました。他の方のご意見もないようでしたので、右端ママで行きたいと思います～

**Comment by cocotori** [comment]
そうですね、あれから何度かキャッシュのクリア等しているのですが、
Chromeだけはなぜか右の領域が大きくなってしまいます。

ただ、そのままでも作業ができないわけはないこと、
Edgeやfirefoxではそういう現象が出ないことから、
closedにして頂いて問題ないです！

**Comment by snext1220** [comment]
ご連絡＆ご了承ありがとうございます。
当方でも複数PCのChromeで確認しているのですが再現せず、なんとも不思議です...
ご利用続けて、（改善した含めて）なにか変化がありましたら、またお教えくださいませm(_ _)m
