### ISSUE TITLE
【Playground Flow】フローチャートの初期情報を投入

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#185]
https://twitter.com/ChanaGame/status/1247141954715959297 を受けてのIssueです。

PgFlowでフロチャ機能を利用いただけないのはやはり悔しいのでｗ、
今後、フロチャそのものの機能を強化していくのはもちろんですが、特に初期の立ち上げで手軽にフロチャを作成できる環境も用意していければと思っています。

たとえば以下のような形式のテキストを投入すれば、現在のフロチャに統合するような機能を考えていますが、如何でしょうか。
※インデントなしのものがシーン情報、インデントありがシーンに付随するリンク情報です。

---

1,サマリー
　2,次へ
　3,次へ
2,サマリー
　10,戦う
　...

---

あくまで初期立ち上げの時の負荷を減らすのが目的ですが、「そんなんほしいんじゃないよ」的なご意見もありそうなので、まずは提案までに。

もしこれらの用途があるようであれば、アイテムや敵情報も同様にテキストファイルから投入できる機能があっても良いのかなと思っています。

**Comment by cocotori** [comment]
あくまで初期立ち上げ時の、ということではありますが、
新しい文法を覚えなくてはならないので
シナリオ作者さんにとっては
結構な負担になるような気もしますね・・・

テキスト中心ということであれば、
すでにplayground editorがありますので、
あちらを使いやすくする、などの方向性はいかがでしょうか？


これは個人的な感覚なのですが、
テキスト等のいわゆるCUIベースのインタフェースは
慣れた人が作業効率を重視するときに使うもの、という印象があります。

導入や、難しい文法を覚えたくない人に向けて
GUIがあると思っているので、
そのGUIが使いにくいのでCUIを使ってサポートするというのは、
なんというか本末転倒な気がしないでもないです。

いろいろ考えてくださってるのに
否定的な意見ばかりで申し訳ありません・・・


例えばなんですけど、
テンプレートをもう少し充実させていくなどの方向性はいかがでしょうか。
現在もいくつかありますが、ノード名がnullだったりして
最新の状態になっていないのでメンテしていくなどして。
（その際は協力もします！）

わたしもツクールでゲームを作る時、最初は作り方もわからなくて。
ツクールには中身を自由にいじれる
サンプルシナリオというのが用意されているんですけど、
それをいろいろ変更しながら自分のゲームにしていった覚えがあります。

**Comment by toki-sor1** [comment]
せっかくご提案いただいたのに申し訳ないのですが、個人的には、新たなフロチャ作成方法を増やすよりも、**Playground Flowの挙動を見直す方が良いかな**と思いました。

というのも、改めてGBATとPlayground Flowを比べてみると、
**Playground Flowでは新規Sceneを作る度にid等の入力画面が出てくるので、そこでワンテンポ遅れてしまっている印象を受けたからです。**

GBATでは、新規Sceneをidやサマリーを入力せずに続けて幾つも作れるので、Playground Flowで**Add Sceneのダイアログ（？）が出ないだけでも、フロチャ作成のテンポが良くなるのではないでしょうか。**
（画面右にエディター画面が出ているので、そちらに直で入力してもらうイメージです）

**Comment by snext1220** [comment]
> いろいろ考えてくださってるのに否定的な意見ばかりで申し訳ありません・・・

いえいえ、この辺は意見割れると思っていたので、忌憚なきご意見助かります。
仰る通り、テンプレートの充実はぜひできればと。
正直全く手が回っていないので；、「こんなテンプレあればいいな」or「このテンプレこうした方がよい」などあれば、どんどん更新＆コミット戴ければ幸いですm(_ _)m
＃ もちろん、私の方でもテンプレの充実はしていければと思っているのですが、まずはこんなのがあれば、というものを初期に用意したもので、追加の方は中々思いつかず；是非お知恵をお貸しいただければとm(_ _)m

> そのGUIが使いにくいのでCUIを使ってサポートするというのは、なんというか本末転倒な気がしないでもないです。

こちらについては補足いたしますと。今回の場合、初心者というよりも同種のツールを使いこんでいるちゃなさんからのご意見でしたので、大量データの投入であればCUIベースの方がマッチしているのかと思った次第でした^^;（個人的にはリンク情報はなしで、ノードだけにすれば、ほぼフォーマット規則もなくなるのでありなのかと、まだ引っ張ってみる^^;）

> すでにplayground editorがありますので、あちらを使いやすくする、などの方向性はいかがでしょうか？

はい、もちろん可能ですが、どの辺をなんとかしたい、などありますでしょうか？
＃ スミマセン、Editorの方は一寸ノーアイデアだもので、微妙に他力本願...；；

> Playground Flowでは新規Sceneを作る度にid等の入力画面が出てくるので、そこでワンテンポ遅れてしまっている印象を受けたからです。

はい、まさに仰る通りかと。
ただ、idがないとフロチャが生成できない仕様のため、最低限、idは最初に必要となりまして。
たとえば、「最大値+10」などの決まりがあれば、

+ ダイアログを表示させずにそのままノードを作成

とすることもできます。ただし、idはキーのため、あとで変更できないので、そう考えると、

+ ダイアログの既定値としてid値を自動セットする

というのもありですが…ダイアログが一旦挟まるのは変わらないうえ、結局修正しなければならないとなると、それはそれであまり省力化にならないかもしれませんね...うむむ。

**Comment by toki-sor1** [comment]
>> Playground Flowでは新規Sceneを作る度にid等の入力画面が出てくるので、そこでワンテンポ遅れてしまっている印象を受けたからです。

ご回答ありがとうございます！
なるほど、ライブラリ側の制約によって最初にid値を設定する必要があるのですね；
「最大値+10」というのも、人によっては気になってしまいそうですし、id値の自動セットもダイアログが挟まるとなると…

うーん、「ダイアログからid値を入力する」という今の形が一番手間が掛からない方法になる訳ですね；

そうなるとワンテンポの遅れを改善するのは難しそうですね…。
という訳で、私は下記のような方針が良いかなと思いました～。

- Pg Flowのid値設定ダイアログはそのままでOK
- id値しか設定されていないScene 0～50くらいまでのテンプレートの作成
  - シナリオ作成に慣れた人向けのテンプレートです
  - フロチャがカオスですが、「編集するシーンを選択」からシーンを探せば大丈夫そう
  - あとは自由にテキストをコピペしたり、リンクを繋げたりしてカスタマイズしてもらう
  - 短編用（Scene 0～30まで）、中編用（Scene 0～70まで）などもあると良さそう

**Comment by snext1220** [comment]
ライブラリ側の制約＞正確にはノードのidとシーンのidとを別物にしておけばよかったのですが、現時点で一致しているため、これを修正しようとすると根本的に手を入れないといけない状態です...申し訳ありません；

あとは別案としては、PgFlowの上部メニューに［簡易シーン追加］ボタンと［シーン番号増分］（テキストボックス）を設けて、無条件に「その時点での最大id ＋ 増分」でidを振っていくという方法はあるかと思います。これであれば比較的操作の手間はかからず、その人その人のニーズにも合わせやすい、かもしれません(?)

テンプレ＞こちらについては大歓迎です！以前に @cocotori さんからもご意見出ましたが、「こんなテンプレがあるといいな」というのは皆さんそれぞれにあると思うので、お気軽に /playground/template フォルダーに.json形式でUp戴ければ（既存のUpdateも可）、PgFlowにも登録してまいります～（#194 にも新規Issueを立てておりますのでご利用ください）

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.106(64bit)にて動作確認。
本番環境、GitHubの両環境でSceneが「その時点での最大id ＋ 増分」で追加されるのを確認しました。
ダイアログを挟まない分、お手軽かつテンポ良くSceneが追加できて大満足です！！
実装ありがとうございます～！！

【不具合？】
**［シーン番号増分］（テキストボックス）で「＋0」と設定してシーン追加ボタンを押したところ、フローチャートが全て吹っ飛んでしまいました（本番環境、GitHub）。**
そうなると、あとは「＋1」など他の数値を入力しても、フローチャートが追加されませんでした。

> もし問題ないようであれば、恐縮ですが、 @toki-sor1 さんにはアイコンのご相談をさせて戴けますと幸いですm(_ _)m

承知しました！
ご希望のサイズや「こういうイメージで！」というご指定がありましたら、よろしくお願いいたします～。
***
テンプレートIssueの立ち上げもありがとうございました！
今回のシーン追加機能が私のテンプレ案の代わりになりそうですが、**サンプル情報が登録されているテンプレがあった方が良さそうですよね。**
こちら、作成できましたら指定のフォルダにアップしたいと思います。

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！
まずは初期立ち上げのテンポという第一目的が改善してよかったです～
シーンが多くなった時の位置調整など細かな問題はありそうですが、そちらは徐々に；

不具合＞入力値チェックは全くしていなかったので、その関係ですね^^; あえて0もないかと無視してましたがｗ、全吹っ飛びも戴けないので+1で丸めるように改めました～

アイコン＞ご快諾ありがとうございます！サイズは他のメニューアイコンと同じでよいかと思うのですが、イメージの方ですよね...GBATにあるような［New Section］ボタン辺りで、イメージ沸きますでしょうか？？

テンプレ＞はい～現時点では、20sceneサンプルが一番近いかと思いますが、結構やっつけなので、「こんなのもあれば便利」などありましたら、是非ご提案くださいませ～

**Comment by toki-sor1** [comment]
お忙しいところ修正ありがとうございます＆お疲れ様です～！

> 全吹っ飛びも戴けないので+1で丸めるように改めました～

全吹っ飛ぶのはビックリですよねｗ
本番環境、GitHub版ともに「+0」と指定しても「+1」と同じようにシーンが生成されることを確認しました～！
（感覚的にちょっと気になりますが、慣れの問題なので大丈夫だと思います！）

> ［New Section］ボタン辺りで、イメージ沸きますでしょうか？？

詳細ありがとうございます！
GBATのアイコンを参考にアイコンを作成してみました～（ほぼまんまですがｗ）。
https://onedrive.live.com/?id=4837C202555BE782%219718&cid=4837C202555BE782
![image](https://user-images.githubusercontent.com/42646342/84905115-2f902380-b0eb-11ea-91cc-e4cfb53423ae.png)

> はい～現時点では、20sceneサンプルが一番近いかと思いますが、結構やっつけなので、「こんなのもあれば便利」などありましたら、是非ご提案くださいませ～

まだ調整途中ですが、こんな感じのテンプレを作成中です～。
<img src="https://user-images.githubusercontent.com/42646342/84905693-f2786100-b0eb-11ea-9187-344894858323.png" width="300">

**Comment by snext1220** [comment]
早速ありがとうございます！
文字も追加いただいたことでイメージもしやすくGoodだと思います～
まずはGitHub Pagesのみに反映させていただきました！（ちょっと更新スピードが上がっているので、本番へは落ち着いたところでまとめて^^;）
＃ 本日追加した他Issueの追加に伴い、コードをだいぶ弄っていますので、恐縮ですが、他の動作テストと共に軽く弄ってみて戴けますと幸いですm(_ _)m

> 本番環境、GitHub版ともに「+0」と指定しても「+1」と同じようにシーンが生成されることを確認しました～！（感覚的にちょっと気になりますが、慣れの問題なので大丈夫だと思います！）

はい～意図して「+0」にすることもないと思うので、まずはこれにて^^;
もし設定画面などを作成する場合は、そこで正の整数などのチェックを入れたいと思います。
＃ チェック系はやってくるとキリがなくなりますね～今回は負数、非数値まではやりましたが、他にも悪さをしようと思うと、色々できるはずなので；；

> まだ調整途中ですが、こんな感じのテンプレを作成中です～。

こちらもありがとうございます！楽しみにしております～

**Comment by cocotori** [comment]
Chromeで確認しました。
シーン追加ボタンで新しくシーンが追加されました。
ワンタッチでできるので、慣れてくるとスピーディーに操作できるかもしれませんね！

id加算用の値ですが、入力自体を0からマイナスを禁止することはできないのでしょうか？
それができれば丸めの処理がいらなくなると思いましたが。
難しそうであればこのままで問題ありません！

**Comment by snext1220** [comment]
> ワンタッチでできるので、慣れてくるとスピーディーに操作できるかもしれませんね！

是非活用ください～フロチャが大きくなってきたときの利用には適さないかと思いますが^^;、初期立ち上げ（とにかくたくさんシーンを作りたい）の状況では活躍してくれるのかなと。シーンタブからのシーン追加とセットで使い分けてやってください。

> id加算用の値ですが、入力自体を0からマイナスを禁止することはできないのでしょうか？

とりあえずスピンボタンでの増減では1未満にならないようにガードしてみました。
手入力する場合にはすり抜け出来てしまいますが、如何でしょうか。

基本、負数を敢えて入れる局面はほぼないと思いますし、あとは丸めガード程度で十分かなと^^;

勿論エラーチェックもできるのですが、とりあえずエラーチェックはまじめになっていくと、コード量が簡単に倍化するので、全体方針として、「**明らかな異常値については、致命的なエラーを避けるための対処はする程度に留める**（正常値と誤解されやすい値についてはできるだけフォローする）**」がバランス良いところかな、と思っておりますが、如何でしょうか。

＃ もちろん、「いや、負数も正常値として●○のような挙動を期待してしまうよ」というご意見もあるかとは^^;

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.116(64bit)にて動作確認。
正常に動作していました。
スピンボタンでの増減では1未満にならないことも確認しました。
丸め処理よりもこちらの方が、数値の設定と実際に作成されるシーンidに違いがなくて良いですね。

**Comment by snext1220** [comment]
本Issueは https://github.com/snext1220/stext/issues/202#issuecomment-653775899 の議論もありましたので、以下の懸案をSep Updateに引き継ぎたいと思います（ご意見によっては別Issueを立ち上げます）。

+ シーン追加ボタンの廃止是非
+ outlineの改良（#202）
+ 追加シーンのルール変更（最大値idのシーンに対して自動でリンクしていく、など）

お手数ですが、ご意見いただければ幸いです。

**Comment by toki-sor1** [comment]
> シーン追加ボタンの廃止是非

> #185 (comment) では、ご評価の声も戴いておりますので、ひと月待っての判断でしょうか（一応、折角実装したいので使って戴けるのであれば残してやりたいという欲も反面で^^;）

まだしっかりと機能を利用できていないので、現時点では判断が難しいですね；（すみません；）
ただ、シーン追加ボタンは、GBATユーザーと相性が良いかもしれない可能性や、実装してから十分な時間が経っていないことを考慮して、**ひと月待っての判断**が良いかなと思います。
***
> outlineの改良（#202）

> outlineについて、現時点では対応するのはメニューバーの選択ボックスですね...仰る通り見やすいとは言えないので、そもそもリンク時のid選択と同じ形式で、サイドバーとして表示するのもありでしょうか（常時表示されていなければ意味がないとする、意味ないかもですが^^;）。

やはり可能であれば、サイドバーよりも常時表示されていた方が確認し易いかなと思います；
しかし、**Pg Flowはoutlineが表示されていなくても十分なほど機能が充実している**ので、使用感をGBATに近付けるためにoutlineを常時表示する、というのも…う～ん…という気もしています；

前回の意見は、使用感をGBATと比較して感じたものなので、機能をGBATに寄せる方針でない場合は、**現在のままで良いと思います。**
（意見がふらふらしていて申し訳ありません；）
***
> 追加シーンのルール変更（最大値idのシーンに対して自動でリンクしていく、など）

> ここは現状ライブラリの制約で致し方ないですね...横並びの幅を狭めて少しでも見やすく、とは調整したのですが...；
あとは、そもそも最大値idのシーンに対して自動でリンクしていく、という方法もありますが、却って使い道を限定してしまいそうですね；

なるほど、並び方は制約が影響していたのですね。
（上記のとおり、前回がGBATと比較しているところがあったので、）Pg Flow単体として見た時は、リオさんの調整のおかげで追加したシーン同士が近く、きちんと並んでくれるので、追加したシーンを見失いにくくて
良いなと思っています！

自動シーンは、仰るとおり使い道を限定してしまったり、リンクを繋ぎ直す手間が増える可能性もありますね；
**シーン追加ボタンの機能としては、自動リンクはなしの方が良いかなと思っています～。**

**Comment by snext1220** [comment]
> シーン追加ボタンの廃止是非
> ただ、シーン追加ボタンは、GBATユーザーと相性が良いかもしれない可能性や、実装してから十分な時間が経っていないことを考慮して、ひと月待っての判断が良いかなと思います。

勿論了解です！
あまり追加したり削除したりも良くないので^^;、まずは皆さんのご意見待ちということで。「絶対欲しい（+∞）」「あってもいい（+1）」「なくてもいい（-1）」でご意見頂ければ助かります～＞皆さま
＃上記の合計得点の正負で決められればと（つまり、「絶対欲しい」が一件でもある場合は残します！）

> しかし、Pg Flowはoutlineが表示されていなくても十分なほど機能が充実しているので、使用感をGBATに近付けるためにoutlineを常時表示する、というのも…う～ん…という気もしています；

ご意見ありがとうございます！
GBATはフロチャ機能の見本ではありましたが、**機能を近づけること自体は目的ではない**ので、まずは様子見かもしれませんね。

＃ この数か月の改定で、GBATとPgFlowの方向性も結構違うのかなという感じになってきましたし^^; 勿論真似るべきものはGBATに限らず、どんどん真似ていきますんで、「こんな機能が」などあれば是非お教えください～

> Pg Flow単体として見た時は、リオさんの調整のおかげで追加したシーン同士が近く、きちんと並んでくれるので、追加したシーンを見失いにくくて良いなと思っています！
> 自動シーンは、仰るとおり使い道を限定してしまったり、リンクを繋ぎ直す手間が増える可能性もありますね；
> シーン追加ボタンの機能としては、自動リンクはなしの方が良いかなと思っています～。

ご評価ありがとうございます！
また、ご意見、私も賛成です。恐らく自動的にリンクまで追加するならば、シーンタブからのシーン追加機能の方が使いやすいと思いますし、そこは差別化しておいた方が良さそうですね～

**Comment by cocotori** [comment]
>シーン追加ボタンの廃止是非

確認ですが、こちらは左上の、+n番のシーン追加ボタンのことですよね？

シーンタブの中にシーン追加ボタンが作られたことで、
左上のボタンはなくても大丈夫ではないかなと思います。
　
　
>outlineの改良（#202）

こちらはわたしの方では今の所要望はないですね・・・
特になくても大丈夫かと思っています。
　
　
>追加シーンのルール変更（最大値idのシーンに対して自動でリンクしていく、など）

こちらは左上のシーン追加のボタンがなくなれば、
シーン追加の際には必ずどこかのシーンとリンクがつながるので
考慮しなくてもいい、という理解で大丈夫ですか？

そういう意味でも、左上のシーン追加ボタンはなくてもいいかな、と思います。

**Comment by snext1220** [comment]
ご確認ありがとうございます～

> 左上の、+n番のシーン追加ボタンのことですよね？

はい、仰る通りです！

> シーン追加の際には必ずどこかのシーンとリンクがつながるので考慮しなくてもいい、という理解で大丈夫ですか？

はい、あくまで「+n番のシーン追加ボタン」の機能についてなので、ご理解の通りです！

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で問題無いことを確認しました。

>シーン追加ボタンの廃止是非

「あってもいい」に一票です。

>outlineの改良（#202）

今のままでも問題無いと思っています。

>追加シーンのルール変更（最大値idのシーンに対して自動でリンクしていく、など）

これは、人によって製作手順が違うと思うので今のままでいいかなと思います。

**Comment by toki-sor1** [comment]
最初の意見を書いてから時間が経ちましたので、改めて意見を書きますね。

> シーン追加ボタンの廃止是非

**【あってもいい（+1）】**
「+n番のシーン追加ボタン」は、GBATの使用感に似ていることから、GBATユーザーと相性が良いかもしれないと思っているからです。

> outlineの改良（#202）

**現在のままで良いと思います。**

> 追加シーンのルール変更（最大値idのシーンに対して自動でリンクしていく、など）

- 「+n番のシーン追加ボタン」からの自動リンクは、**人によってはリンクを繋ぎ直す手間が発生してしまうため、現在の仕様が良いと思います。**
- 「シーンタブのシーン追加ボタン」からの自動リンクは、**「+n番のシーン追加ボタン」との使い分けという意味でも、現在の仕様が良いと思います。**

**Comment by snext1220** [comment]
皆さま、ご意見ありがとうございました！
ご意見で揃いましたので、以下結論まとめ、Closeといたしますね。

+ シーン追加ボタンの廃止是非

合計+1でしたので、今回は機能廃止せず（ママ）でまいりたいと思いますm(_ _)m
Playgroundの機能整理については、別Issueでも今一度ご意見募っていければと思いますので、引き続きご意見頂ければ幸いです。

+ outlineの改良（#202）
+ 追加シーンのルール変更（最大値idのシーンに対して自動でリンクしていく、など）

こちらも現状ママですね！私も問題ないと思います～
