### ISSUE TITLE
<enemy>要素のattack属性の設定値追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#186]
attack属性に、以下の設定値を追加できないかと思っています。

+ strN～krmN（Nは減らす値）

いわゆるステータス攻撃です。結構致命傷なので、状態異常と同じくfunc属性の値は回避条件になるのかなと。如何なものでしょうか。

実現する際には、お手数ですがアイコン画像も必要になるため、恐縮ですがご相談させてください＞ @toki-sor1 さん

**Comment by cocotori** [comment]
通常戦闘で自動計算でステータス攻撃ができるような感じでしょうか。
自分のシナリオでは今の所必要ではないので、
（特殊ルールとして、手動で増減できればよいかなという印象です）
他の方の意見待ちですね・・・

**Comment by toki-sor1** [comment]
> strN～krmN（Nは減らす値）

状態異常のステータス低下では表現し切れないところをカバーする、という意味でも**良いと思います。**
たとえば、サキュバスやトラップなんかでステータスドレインされるといった演出もできますし、シナリオの表現の幅も拡がるのではないでしょうか（回避条件の設定も必須ですね）。

> アイコン

大変お待たせしてしまい申し訳ありません；
ステータスダウンのアイコンと、念のためにステータスアップのアイコンも作ってみました。
O/Dにアップ済みです。
https://onedrive.live.com/?id=4837C202555BE782%219212&cid=4837C202555BE782

![ステータスアップダウンサンプル](https://user-images.githubusercontent.com/42646342/80821797-67630a80-8c14-11ea-99f1-90b7f3fe161e.png)

**Comment by Salvadors-cabin** [comment]
今のところは使う予定は無いですが、あってもよい機能と思います。

**Comment by snext1220** [comment]
ご意見ありがとうございます。
本件、積極的な反対もなく、互換性の問題もないため、実装の方向で動いてまいりますね。

@toki-sor1 さん＞
アイコンの作成ありがとうございます！
ただ、STR～KRMの区別がついた方がよいかな～と思うので、ST->STR、INT、DEX、KRMでお願いしてもよろしいでしょうか（攻撃ということで上昇はなくても良いかなと思っていますが、如何でしょうか？設定値もSTR+2、STR-2とするよりもSTR2とした方がスッキリなので）。

**Comment by toki-sor1** [comment]
@snext1220 さん＞

大変お待たせいたしました…！
上昇アイコンはなくても大丈夫とのことでしたので、下降アイコンのみ手直ししてGitHub環境＆本番環境のダミーと差し替えました。
![image](https://user-images.githubusercontent.com/42646342/83357321-a9fc3c00-a3a6-11ea-84f3-fae3ada4cab1.png)

**Comment by snext1220** [comment]
@toki-sor1 さん＞
お忙しいところありがとうございます！
お手数をおかけしてスミマセン。

そして、何度も恐縮なのですが、STR～KRMについてはぱっと見区別がしやすいよう、FREE1～3のようにカラーは変えた方がよいかなとも思ったのですが、如何なものでしょうか（同じデザインなので、並んでいるときに誤認しないかなと気になった次第です...）
感覚の問題かもしれないので、ご意見うかがえれば幸いです～

**Comment by toki-sor1** [comment]
@snext1220 さん＞
いえいえ、リオさんこそお忙しいところ更新お疲れ様です…！
こちらこそ各種素材の反映＆調整ありがとうございました！

確かに各ステータスの文字が小さ目&同じデザインなので、全て同色だと誤認し易そうですね；
こちら、色を変えてGitHub環境と本番環境のアイコンを差し替えました～。
![image](https://user-images.githubusercontent.com/42646342/83418880-39fdbc80-a45f-11ea-8035-82ff19259431.png)

**Comment by snext1220** [comment]
@toki-sor1 さん＞
ありがとうございます！
ぐんと区別がしやすくなったと思います！！

**Comment by cocotori** [comment]
STR～KRM、
食らったときに-1されることを確認しました。

確認している最中に少し混乱してしまったのですけど、
STR～KRMは状態異常扱いなのですね。

ダメージ式に10-STRとか書いて、一向に減らないな・・・？
と勘違いをしていました。
念の為、マニュアルに状態異常と同じ計算方法と、
明記しておいた方がいいかもしれません。


あと、今更な話になってしまうのですが・・・
ダメージ式の扱いが、物理・魔法と状態異常で反対になっていると感じました。
物理・魔法は、被害量　（小さい方がプレイヤーにお得）
状態異常は、回避率　（大きいほうがプレイヤーにお得）
であり、
ややわかりにくさを伴うかなと思いました。

今更な話なので、すぐに直そうとか言うことはないです！

**Comment by snext1220** [comment]
ご指摘ありがとうございます！
マニュアルについては別途対応してまいりますね（#191 にて別途管理）

ダメージ式については、悩ましいですね...^^;
回避率というか回避条件だもので「STR > 10」（STRの大きい方がプレイヤーにお得）、ダメージ式は一般的に「10 - STR」（STRの大きい方がプレイヤーにお得）で一致しているかな～と思っていたのですが、如何なものでしょうか。

こちらはもし変更するとなると、すべてのシナリオの多くの条件式に影響を伴う修正になるので、現実的にはSText 2.0（互換性なしの新シリーズ？）での対応になってしまうかと思うのですが（当面の対応はなし）、後々のご参考にご意見うかがえますと幸いです＞皆さま

**Comment by Salvadors-cabin** [comment]
>ダメージ式

機能的には問題ないので決めごとだと思います。
マニュアルに明記してあればよいのではないかと思います。

**Comment by cocotori** [comment]
わたしもちょっと気になっただけのことですので、
無理して変える必要はないと考えています！

**Comment by toki-sor1** [comment]
> ダメージ式

私も現在のままで大丈夫です～。

**Comment by snext1220** [comment]
ご意見ありがとうございました！
では、ママでまいります。

今後の仕様策定という意味で、表現の自然度どうかなとやや気にはなっておりますが^^;、もしなにかあればグループＤにてお願いいたします～
