### ISSUE TITLE
呪い状態が維持されない

### ISSUE THREAD

**Issue by toki-sor1** [snext1220/stext#188]
Win8.1／Chrome 81.0.4044.122(64bit)にて動作確認。

GitHub版で上記環境で動作確認を行っていたところ、**呪い状態が維持されない症状を確認しました。**
呪い状態が維持されないケースは、以下の通りです。

- 呪いを手動で設定し、確定後に再読み込み→続きから再開した時
- 呪いを手動で設定し、次のシーンへ進んだ時

もし既にIssueが立てられているor仕様でしたら申し訳ありません。

<img src="https://user-images.githubusercontent.com/42646342/80313141-1625d600-8824-11ea-919d-c16b9c852777.png" width="200"> <img src="https://user-images.githubusercontent.com/42646342/80313166-39e91c00-8824-11ea-8da0-d5868932d4c2.png" width="200">

**Comment by snext1220** [comment]
こちら確認しました。
ただ、申し訳ありません、ご指摘の手順で確認したところ、当方環境では確認ができませんでした。。（セーブデータにも反映されており、特に問題はなさそうに見えます）

お手数ですが、確定後のセーブデータ（chara－stateの値がcurseになっているか）を今一度ご確認いただいてもよろしいでしょうか。

![無題](https://user-images.githubusercontent.com/27911337/80974239-68d24400-8e5b-11ea-8ed3-ce840b2853ac.png)

私の勘違い、確認漏れであれば申し訳ありません。。

**Comment by toki-sor1** [comment]
ご検証ありがとうございます！
先ほど試したところ、上記2通りのテストで呪い状態が維持されていることを確認しました。

ただ、画面は呪い状態の壁紙が表示されているにもかかわらず、stateは空白のままになっています；
リオさんが挙げてくださった画像と各項目の並びが違うのも気になりますね…。

<img src="https://user-images.githubusercontent.com/42646342/81036147-f142fa00-8ed8-11ea-997f-c3bd16bd1d12.png" width="300">

**Comment by toki-sor1** [comment]
ああっ、すみません！！　stateのところがきちんとcurseになっていました！
セーブデータとシナリオが噛み合っておらず、見当違いなところを確認していました；；
お騒がせして大変ご迷惑をお掛けしてしまい、申し訳ありませんでした…！
![image](https://user-images.githubusercontent.com/42646342/81036416-fd7b8700-8ed9-11ea-95fe-7481c9ed2644.png)

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！
こちら、まずは問題なかったようで良かったです（見間違いドンマイですｗ）
以前ご覧になった時がどうだったのか、やや気になるところではありますが；、今回はまずはwontfixとさせていただきますね。また何か出てきたらお知らせください～

> 各項目の並びが違うのも気になりますね…。

項目同士の順番は決まっていないもので、環境によって異なる場合がありますので、ご安心ください～

**Comment by toki-sor1** [comment]
お忙しい中、本当にすみません；；　どんまいありがとです～！
今回は何度やっても前のような状況にならなかったのですが、万が一、同じ状況になりましたら、デベロッパーツールも確認してみます。
wontfixも承知しました！

> 項目同士の順番は決まっていないもので、環境によって異なる場合がありますので、ご安心ください～

おお、そうだったのですね！　安心しました！！
