### ISSUE TITLE
ボーナスアイテムの効果が一部おかしい

### ISSUE THREAD

**Issue by cocotori** [snext1220/stext#189]
ボーナスアイテムの「銀の竪琴」ですが、
説明文には「戦闘時のMPダメージが1減算される」とあります。

ただ、実際にはHPダメージが1減算されているような気がします。
不思議のソーサリアンで、
HP1固定のダメージがありましたのでたまたま気づきました。

なにぶんボーナスアイテムはランダムですので
チェックが大変ですが、他にも何かあるかもしれないので
確認してみます。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 81.0.4044.129(64bit)にて動作確認。
ココさん、検証お疲れ様です。
私も以下の環境で動作確認し、**「銀の竪琴」の効果がMPダメージ1減算ではないことを確認しました。**

HPダメージ1減算の「鏡の盾」は、正常にHPダメージが1減算されていました。

**Comment by snext1220** [comment]
ご指摘ありがとうございます。
仰る通り、バグかと思われますので、別途修正してまいりますm(_ _)m

**Comment by toki-sor1** [comment]
Win8.1／Chrome 81.0.4044.138(64bit)にて動作確認。
**現在は正常にMPダメージが1減算されていました。**

**Comment by cocotori** [comment]
確認しました。
無事修正されています！
ありがとうございます。
