### ISSUE TITLE
状態異常によるステの自動更新

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#19]
ステータス画面で状態異常を選択した時の処理を自動反映

+ 毒：シーン単位のHP-1
+ 石化／忘却：経過シーン数の記録
+ 呪い：低い方のテキストボックスを黒潰し？（不要？）

＃当初はステータス表示を変更しようと考えていましたが、矛盾が結構発生しそうなのでママとしました（将来的に自動計算時に加味すれば十分か）。

#18 の問題とも関連するため、あまり軽々しくは動かせませんが、操作性は格段に向上しそうです。

**Comment by RYU-DS** [comment]
いずれも状態異常全てに手を加えているそのスレでは「自動反映後に手動で変更」となるのであまり関係が無いのですが…

・呪い：低い方のテキストボックスを黒潰し？（不要？）
この呪いは忘却の間違いと前提して「STR/INTの低い方の数値を自動で0にする」でお願いします。
そのスレでは「STR/INTの低い方の数値を半分にする」なので、黒潰しだと手動で半分に戻せないので非常に困ります。

また呪いは「魔法のストーンフレッシュとリデュースライフ以外を灰文字にして使えなくする」でよいかとも思いますが、これも何か問題が出そうな気もしなくはないです。

**Comment by snext1220** [comment]
### 進捗メモ

+ [ ] 毒：シーン単位のHP-1
+ [ ] 石化／忘却：経過シーン数の記録
+ [x] 毒：HPのテキストボックスを背景赤色に
+ [x] 忘却：STR/IT低い方のテキストボックスを背景灰色に

※忘却のスタイルはとりあえず灰色で進めています（字は見えるので修正には困らないかと）。数字自体を0に変えてしまうと、手動操作もできる状態なため、以前の値が消えてしまうなど問題が大きく、現状はママにしています。

**Comment by toki-sor1** [comment]
**メイン背景の魔法陣壁紙**
- 背景が変わるのは、分かり易くて良いと思います。
- 状態異常になった際のサンプル壁紙を作成しました。
- O/Dに[A～Cの壁紙](https://onedrive.live.com/?id=4837C202555BE782%218774&cid=4837C202555BE782)アップ済みです。
<img src="https://user-images.githubusercontent.com/42646342/46873834-979c5a00-ce72-11e8-9c07-aab5943e547d.png"  width="320px">

**状態異常のカラーリング、表現**
- 現在の毒のような演出が、分かり易くて良いと思います。
- カラーリングは、原作でキャラの色が変わらない忘却以外、原作をイメージしてみました。
視認性の関係で、色味をやや濃い目にしているものもあります。
毒＝#ff0000、凍結＝#1e90ff、石化＝#696969、呪い＝#0000ff、忘却#800080又は#8b4513

**Comment by snext1220** [comment]
ご対応ありがとうございました！
戴いた内容にて、まずはGitHub Pages版のサンプルをUpdateしておりますので、
お手すきの折にもご確認戴けますとm(_ _)m
＃ 背景、もう少し薄めの方が良い、でしょうか…？（ディスプレイにもよりそう）

**Comment by toki-sor1** [comment]
ご確認＆サンプルのアップありがとうございました！
確かに、若干濃い目のように感じましたので、O/Dに[薄め版](https://onedrive.live.com/?id=4837C202555BE782%217572&cid=4837C202555BE782)もアップしました。
<img src="https://user-images.githubusercontent.com/42646342/46880823-a7249e80-ce84-11e8-961d-f4df37500e50.png" width="320">

**Comment by snext1220** [comment]
早速ありがとうございます！
画像置き換えさせていただきました。ただ、申し訳ありません、従来の背景（main_back.png）に比べ、ファイルサイズが3倍ほどになってしまっているため、お手数ですが、可能な範囲で画像サイズを落としていただいても宜しいでしょうか；；

また、合わせて忘却、呪い、凍結などの文字色が悪目立ちしてしまっていたので、文字色を変更しています（特に忘却は0無効化なので、見えにくいくらいがちょうどよいのかなと）。
あとは、凍結が薄青でぱっと見、あまり異常感がないのが気になりはしましたが（原作的にはこの色ですがｗ）、皆さま、どんな感じですかね～？他の状態異常の色合いも含めて、ご確認戴けますと幸いですm(_ _)m

**Comment by toki-sor1** [comment]
ご確認、ご意見ありがとうございます。

**メイン背景の魔法陣壁紙**
- すみません、ファイルサイズは盲点でした……（汗）。
軽量版をO/Dにアップしました。
https://onedrive.live.com/?id=4837C202555BE782%217572&cid=4837C202555BE782
<img src="https://user-images.githubusercontent.com/42646342/46901220-c35b2680-ceea-11e8-910e-cad350c2cec0.png"  width="320">

**状態異常のカラーリング、表現**
- 簡易ステータスにも色が反映されると勘違いしていましたので（汗）、
全体的にやや濃い目の色を指定していました。
- しかし、文字色を変更後は、欄の薄い色との差別化もあり、現在のカラーリングも
良いと思いました（文字色修正前は、呪いが一見ブルースクリーン風でしたが、
現在では、ブルスク風回避＆ソーサリアンっぽさが増したと思います）
- 「凍結」は、青系から離れると凍結っぽさが薄れますし、水色だと視認し辛い感じが
しますので、私は「青系＋少し濃い目の色」が良いと思っています。

**Comment by snext1220** [comment]
背景＞早速ありがとうございます！GitHubに反映いたしました～

簡易ステータス＞言葉足らずで申し訳ありません。。
ダイアログの方は、実際にダメージ反映する際などに目についた方が判りやすいという意味で、今回、スタイル付けしてみました。

カラーリングのご確認もありがとうございました。では、基本は現状ママで参りますね！
＃他の方も何かご意見あれば引き続きよろしくお願いします。

なお、簡易ステの方は参照用途だけなので＆下の方であまり目につかない＆今回背景を変更したなどの理由から、あまり強調する意味もなく。むしろボールド＆赤も外そうかなとも思っていたのですが、如何でしょうか。
＃逆に、現在の状態を明快に示すならば、状態異常ごとに色違い背景にするのも手かとは思いましたが…やりすぎでしょうか^^;

**Comment by toki-sor1** [comment]
> 簡易ステータス

いえいえ、こちらこそ確認を怠ってしまい、失礼しました。
簡易ステータスのボールド＆赤ですが、私はそのままでも良いような気がしました。
全て黒文字だと、目が滑ってしまうのでは、と思ったもので。

> 状態異常ごとに色違い背景

私も一瞬それを考えたのですが、状態異常になる頻度が高いシナリオでは、
かえって画面がうるさくなってしまうので、現状は様子見が良いのではと思いました。

> カラーリング
現状ままですね。承知しました。

**状態異常アイコン試作品**
以前、他のIssueで見掛けた覚えがあり、今回は状態異常関連の素材を作っていたので、
試しに各状態異常に対応したアイコン＆使用例サンプルも作ってみました（O/Dアップ済み）。
コンパネのBGM ON/OFFみたいに、クリック（タップ）すると色が変わるイメージです。
こちら、使えそうでしょうか？
https://onedrive.live.com/?id=4837C202555BE782%219157&cid=4837C202555BE782
<img src="https://user-images.githubusercontent.com/42646342/46902576-a7637f00-cf02-11e8-8f10-1e2eb024ebac.png" width="320">

**Comment by snext1220** [comment]
簡易ステ、色違い背景＞
了解です。では、まずは現状ママで！
他の方のご意見、または様子見でなにかあれば、またご相談させてくださいませ～

状態異常アイコン＞
おぉ、早速！早いです！ｗ
と、こちらは一寸悩んだのですが、「単一選択ボタンであることが見た目的に不明瞭になりそう」という懸念がありましたので、様子見でも宜しいでしょうか？（す、スミマセン）

＃ 複数選択（チェックボックス）ですと、まさにこのようなイメージなのですが、ラジオボタンですと、あまりこうした見た目を使わないように思えましたもので；（有効／無効のアイコンは統一するのが一般的？たま～に他のアプリでもあったりもするのですが、意外と違和感を感じてしまったりするもので^^;）

ただ、状態異常アイコンについては、まさに #39 でご相談させて戴いております件でして、そちらで
活用させて戴けますとm(_ _)m
＃ 余談にはなってしまいますが、こちらのIssueは結構規模も大きいので、反対がなければ、アイコン化、［ドロップ］ボタンなど、影響の少ないものから進めても良いのかな、とも。

**Comment by toki-sor1** [comment]
#39 確認致しました！
うわー！　お手数をお掛けしてしまい、申し訳ありませんでした……！（大汗）

状態異常アイコンは、 私も作成していて「クリック等が分かりにくいかも」とは
感じていましたので、リオさんのご意見を拝見して「やっぱり！」と納得しました。

アイコンは、#39 の仕様で新たに作成しましたので、最初にアップしたものは
ボツということでお願い致します。

**Comment by cocotori** [comment]
状態異常背景、いいですね。
見た目で緊急事態感が伝わってきてわかりやすいです。

背景色はこのまま一色がちょうどいいと思いますが、
簡易ステータスは状態異常ごとに色違いでもいいかも、と思いました。
このまま赤のままでも問題ないと思いますが！

**Comment by snext1220** [comment]
イメージに合っていたようでよかったです！
簡易ステータス表示についても、先ほどダイアログ側と同じカラーで適用してみました。
文字色なので、あまり目立たないかもしれませんが…^^;

**Comment by RYU-DS** [comment]
私もせっかくなので状態異常ごとに違う色に一票です。
色が難しいですが案としては…
・毒…赤（紫もアリ？）
・凍結…青（これは譲れないのでは？）
・石化…灰色（元々魔方陣が灰色なので反転して背景を灰・魔方陣を白？見にくくないよう灰の濃度を調節？）
・呪い…黒（これも背景黒・魔方陣白・文字白？さすがに見にくい？）
・忘却…紫（毒を赤にしてコレしか思いつかないです…）
あと多色の場合は血の斑点？は必要でもないと思うのでデータ削減できる？

**Comment by toki-sor1** [comment]
ご意見、ご感想ありがとうございます！

**簡易ステータスの文字色**
状態異常の文字色がそれぞれの色に対応したことで、より直感的に分かり易くなりました。

**魔法陣壁紙のカラーリング変更**
こちら、申し訳ありませんが、以下の点から現状は赤一種類で様子を見たいと考えています。

- 壁紙の背景色が変わると、場合によっては本文テキストの色を変える処理が必要になるため
- 状態異常になる頻度が高いシナリオでは、かえって画面がうるさくなる可能性があるため
- STextのメインである本文テキスト（シナリオ）の視認性を保つことを優先したいため
- 状態異常の種類は、簡易ステータスに表示されているため（文字色も状態異常毎に対応済み）

血の斑点につきましては、**明らかに異常で危険な状態である**と一目で分かり易くするための
演出なのですが、状態異常の壁紙から血を削除してもデータ容量は約5kbほどの差しか
ないので、そうであれば残しておきたいと思っています。
　※壁紙のデータ容量は、極端に重いものでなければ気にしなくても良いようです

どの状態異常でも同じ色というのは、ゲームとしては直感的ではないのかもしれませんが、
「状態異常であるということを視覚的に伝える」という意味では、赤一種類のみでも
条件を満たしていると考えます。

上記理由もあり、今回のアップデートでは、各状態異常のカラーリングに対応した壁紙に
ついて、様子を見させていただけましたら助かります；；
