### ISSUE TITLE
Characterシートの機能拡張

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#190]
#159 でリクエストいただいた件の議論用Issueです。

---

・リクエスト概要
　「Characterシートの機能拡張」

・用途
　戦士系、魔法系で有利不利（またはストーリー変化）のあるシナリオをユーザの選択でプレイできるようにするため、ゲーム開始時にプレイヤーに性別／クラス、AGEを選択できるようにする。
　また、キャラ名に好みの名前を付ける事で、より感情移入できるのではないかと思います。
　※キャラ名を入力した場合はニックネームは無しにする。

・仕様
　ゲーム開始時に表示されるCharactorシートで、キャラ名の入力、性別／クラス、AGEの選択を可能にする。
　※現在選択できるのは職業だけだが、これを拡張するイメージ。

ご検討いただけたら幸いです。

_Originally posted by @Salvadors-cabin in https://github.com/snext1220/stext/issues/159#issuecomment-622963337_

**Comment by snext1220** [comment]
リクエストありがとうございます。

以前と違って、プレイ開始時にCharacterシートを表示しているので、実装もしやすくなったように思えます。現時点で、以下のような実装を考えておりますが、如何なものでしょうか。

+ Characterシートの純粋拡張。つまり、名前、性別、クラス、AGEの編集を可能にするのみ
     + つまり、プレイ開始時だけでなく、いつでも変更できる
     + シナ途中で変更しても良い（システムとしては関与しないので、シナリオ／ルール次第でご自由に、とのスタンス）
+ ニックネームは性別を変更した時に再設定にできれば（カットだと見た目も寂しくなるため）

**Comment by Salvadors-cabin** [comment]
早速の実装ありがとうございます。
GitHUBテスト環境で確認させていただきました。
私としてはリクエスト通りでまったく問題ない仕様と思います。

>constraint属性

既存シナリオへの影響を考えると、キャラ制約した項目（種族、性別、年齢）だけは変更不可にする、という仕様の方がよいのかもしれません。
または、指定したシナリオのみこのキャラ変更を可能にする、というのでもよいと思います。

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！

> キャラ制約した項目（種族、性別、年齢）だけは変更不可にする、

はい、こちらは現在もconstraint要素の範囲でのみ選択できるようにしておりますので、大丈夫なはずです～（そうなってなかったらバグです（汗））

**Comment by Salvadors-cabin** [comment]
すでに対応済だったのですね！
既存のconstraint要素ありのシナリオで確認しましたが、想定通りの動きになっていました。
大変失礼しました。

**Comment by cocotori** [comment]
通常は自由に変更可能、
constraintでその属性は変更禁止になることを確認しました。

機能的には問題ないのですが、
途中でキャラ属性を変更できないのがデフォルトで、
シナリオ作者さんが何かしらの制約を与えたときに
自由に変更できる、の方が自然な気もしました。

ただ、従来のconstraintの互換性を活かすためにも
今のほうがやりやすいと思いますので、
現状の仕様で問題ありません。

**Comment by toki-sor1** [comment]
Win8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
constraint要素ありだと変更不可、constraint要素なしだと変更可能であることを確認しました。

感覚的には、いつでもキャラ属性が変更できるのがデフォだと不自然な気もします。
…が、今までのSTextでは、ゲーム冒頭の「キャラクターメイキング」にあたる部分がなかったので、私は**自由に変更できるのがデフォ**で良いかなと思っています。

### 問題点
ただ、今気付いたのですが、**CLASSとAGEに関しては、Scene 0でのみ変更可能**と、変更できるSceneを限定した方が良さそうです。
理由は、**どのSceneでもCLASSとAGEを自由に変更できてしまうと、シナリオによってはルールに矛盾が出る可能性がある**からです。

たとえばシナリオ「双王」の召喚石使用回数は、CLASSによって異なります。
そのため、シナリオの途中でCLASSを変えると使用回数に矛盾が出ます。

**Comment by snext1220** [comment]
一応、**自由に変更できるのがデフォ** でOKとのことでコメント戴いているので、蛇足かもしれませんが^^;、以下の対応は可能です～

1. Scene 0でのみ対応可能（他のSceneでは読み取り専用に）
2. scenario.xmlの設定で変更可否を変更可能
3. マニュアルでの補足

1 は比較的簡易ですがシナによっては問題になる、かも？
2 は可能ですがやや重め、といった感じです。

基本、BASICシートは従来機能のJOBも「シナリオ指定時のみ変更」のルールで、特にシステムとしてのガードはかけていなかったので、CLASS／AGEなども同様の扱いの方が自然かな～と（マニュアルではキャプチャの入替ととともに加筆できれば）。如何でしょうか？？

＃ 双王もその前提であれば、ママで良いように思えますが、場合によっては、シナリオ内のルール表記で明記？

**Comment by toki-sor1** [comment]
設定ガードについてご検討いただき＆解決策のご提示ありがとうございます！

> ＃ 双王もその前提であれば、ママで良いように思えますが、場合によっては、シナリオ内のルール表記で明記？

確かに今までも「シナリオ指定時のみ変更」のルールでしたね。

- JOB同様にCLASS／AGEなども同様の扱いの方が自然であること
- 「双王」もルール表記で明記していればカバーできる範囲であること
- CLASS／AGEなどの変更非推奨シナリオでそれらを変更したことによる詰みは自己責任

上記の理由から、**キャラ属性変更は基本自由であり、変更非推奨の場合はシナリオ内に明記するに留める**に意見（方針）を変えさせてくださいませ～。

**Comment by snext1220** [comment]
ご了解戴き、ありがとうございます！
お手数をおかけしますが、双王については必要に応じてシナリオ明記をお願いできますと幸いですm(_ _)m 
＃ 勿論「指示ある時に変更可」という意味では、個人的にはママでも大丈夫かなとは。

STextの場合、遊び方はプレイヤー任せ、無敵モードにも基本対応、ということで、どこまでをシステムでチェック＆自動化するか、匙加減は難しいところですね^^; 悩みつつも、あくまで「プレイヤーの行動を制限しない」を前提に改定進めていきたいと思っています…！

**Comment by cocotori** [comment]
システム的にはいつでも変更可能、
そうしたくないときはシナリオ側で説明する、ということですね。

わたしもその仕組で問題ないと思います。

**Comment by toki-sor1** [comment]
> お手数をおかけしますが、双王については必要に応じてシナリオ明記をお願いできますと幸いですm(_ _)m

はい～、承知しました！

>あくまで「プレイヤーの行動を制限しない」を前提に改定進めていきたいと思っています…！

改定方針に賛成です！
ゲームブックだからこその自由は、これからも大事にしたいですよね。

**Comment by snext1220** [comment]
ご意見ありがとうございました！
こちら仕様としてのご同意を得られましたので、これにてFix＆Close致します～
