### ISSUE TITLE
アイテム・フラグがシートに反映されない？

### ISSUE THREAD

**Issue by RYU-DS** [snext1220/stext#192]
ツイッターでも少し触れたのですが、そのスレで武器などを入手してもアイテム欄に反映されず、アイテム関係のシステム変更によるものかと思っていたのですが…
今調べた所、他のシナリオでも同様でした（少なくとも新王杖で「こいし」を入手しても反映されませんでした）。
で、色々試した結果わかったのは…

・アイテム欄に出ていないだけで内部的には得ている。
・F5で更新して続きから始め直すとアイテム欄に反映されて現れる。
・内部のGet/Lostはキチンと動作しており、Get前まで巻き戻して更新するとちゃんと消える（更新しないと表示されたまま）。
・フラグも全く同様。

といった感じです。
さすがに私の環境だけかもしれないと思うのですが…他の方どうでしょうか？
当方の環境はWindows10(64)/Chromeです。

**Comment by snext1220** [comment]
キャッシュが残っているなどはありませんでしょうか。
とりあえず王杖、トラインなどで一部確認してみましたが、アイテム／フラグ共にまずは正常に動作しているように思え、仰るような現象が確認できておりません。お手数をおかけしますが、今一度ご確認戴けますと幸いですm(_ _)m

＃ アイテム関係は諸々弄っているので、思わぬバグがあるのか、とドキドキしています^^;

**Comment by cocotori** [comment]
わたしの方でも確認したところ、
似たような現象が起きました。

1) Item1をシーン1で入手
2) Items&Flagsシートで確認
3) シーン2に移動。シーン2ではItem1を削減。
4) Items&Flagsシートで確認
　消えたはずのItem1が見える。（USEはできない）

この方法だとキャッシュを消したりしても何度も再発します。
一方、

1) Item1をシーン1で入手
2) シーン2に移動。シーン2ではItem1を削減。
3) Items&Flagsシートで確認

の手順で、Items&Flagsシートを見ないとそういうことは起きませんでした。
どうも、そのアイテムを所持した状態で一度でも
Items&Flagsシートを見ると、
なにか状態が残ってしまうような・・・そんな現象でした。

**Comment by snext1220** [comment]
ありがとうございます！
こちらでも同様の条件で、再現を確認いたしました。
おそらくシートのリフレッシュがうまくできていないように思えるので；、別途見直します。少々お待ち戴けますと幸いですm(_ _)m

**Comment by RYU-DS** [comment]
今キャッシュを消して試してみましたが同様でした（セーブデータはちゃんと消えていたのでキャッシュも消えているはずです）。
私だけ、なら特に問題は無いですが・・・（プレイヤーさえそうならなければ）

**Comment by toki-sor1** [comment]
Win8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
GitHub版テストシナリオ（Playground）にてテストプレイを行ったところ、以下のような状態でした。

- アイテムは入手できている（Items&Flagsシートを確認）

- target属性付きのアイテムはItems&Flagsシートから使用できている
  - アイテムをUSEボタンで使用するとMP回復などの効果は発動する
  - 使用したアイテムが消えずに残っている（ただし使用不可）
  - アイテム使用前まで戻ると、アイテムが使えるように戻っている

- Scene 2から6に移動時、アイテムi03「きのぼう」が消える設定になっているのにも関わらず残って表示されている
***
- 上記の動作確認を何度か行っていたところ、入手アイテムがItems&Flagsシートに反映されていないことを確認
  - しかし、アイテムが消える設定のScene 6までItems&Flagsシートを確認していない時は、アイテムi03「きのぼう」が設定通りに消えていた

- **キャッシュをクリアしても、Items&Flagsシートを確認してしまうと**入手アイテムが反映されなかった

<img src="https://user-images.githubusercontent.com/42646342/83943692-24124200-a839-11ea-98e6-9757b9f93df9.png" width="300">
<img src="https://user-images.githubusercontent.com/42646342/83943721-44da9780-a839-11ea-8497-40c7dcfddc8e.png" width="300">

**Comment by RYU-DS** [comment]
既にいくつかの報告である通り、アイテムなどを入手したシーンではシートに反映されておらず、それをシートで確認してしまうとそれ以降もシートに反映されない（内部的には持っている）ようですね。
入手したシーンではシートを開かず、次以降のシーンでシートを確認すれば反映されていますが、普通は入手したという文章のあるシーンで確認するので…
フラグでも同様ですし、アイテムを削除する場合も削除シーンで確認してしまうと残ってしまいます（これも内部的には消えてますが）。

**Comment by snext1220** [comment]
※ #174 と同じ内容のコメントになり、失礼いたします。

本件、大変失礼いたしました。
Mobile Safari対応の関係で見た目と背後のデータの関係が崩れておりました（実は見た目は選択ボックスなのですが、実体はリストというかなりトリッキーなことをしています...）。Safari対応前にデータのリフレッシュをしていたと思い込んでいたので、確認漏れとなり、失礼いたしました。

先ほど修正し、GitHub Pagesに反映させましたので、ご確認戴けますと幸いです。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
キャッシュ削除後にテストプレイを行い、正常に動作することを確認しました。

- Items&Flagsシート確認後もアイテムが表示されるように改善された
- 使用したアイテムが消えるように改善された
  - アイテムの効果も発動していた（前回と同じく正常）

修正お疲れ様でした！
選択ボックスだと思い込んでいたので、まさかのリストに驚きました！
ゲーム開発話で隠しテクニックの話題が出ることもあるので、今回がまさにその隠しテクニックだと分かってニヤニヤしちゃいましたｗ

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！
まさかのMobile対応が影響していたと思わず、対応遅れすみませんでした...確認していたはず、と思い込みが（ry

まさかのリスト＞IEを切ったあとは専らSafariが鬼っ子ですね～一人だけ思ったように動いてくれず、しかも、mac標準ブラウザなので切れないという；（ダウンロード回りもSafariのためだけに結構なコードを書いてます...）
この辺の隠しテクニックは苦労の結晶なので、楽しんで頂いて?なによりです！また、機会あれば愚痴交じりに呟いていると思うので、是非お楽しみくださいｗ

**Comment by cocotori** [comment]
Chromeで確認しました。
正常に、Items＆Flagsの欄から消えることを確認しました。
