### ISSUE TITLE
【PgFlow】リンク追加ボタンでの無名リンク作成

### ISSUE THREAD

**Issue by cocotori** [snext1220/stext#193]
細かい話で恐縮なのですが。

前回のアップデートで、リンク追加ボタンを
追加していただいたかと思います。

この時、キャプションに未記入のままリンクを作れてしまいます。
そしてそのままxml等に出力し、
再度flowにインポートすると、作ったリンクが消えてしまいました。
どうも、flowが無名のリンクをリンクとして認識してくれないようです。

もちろん最終的には無名のままにすることはないと思うのですが、
現状だと途中のデバッグ等で混乱することがあるかも、と思いました。

今までのリンク作成のように、無名の場合は
システム側がundefinedと仮の名前を自動でつけてくれれば、
そういうこともなくなるのかなと思いました。

いずれにしてもわたしの方では
要求度はそんなに高くないです。
余裕があるときにでも検討してもらえれば・・・！

**Comment by snext1220** [comment]
ご指摘ありがとうございます。
こちら、取り急ぎ既定値をセットするようにし、GitHubに反映しましたので報告です。

PgFlowは、基本入力値チェックは怠けており（アイテムidなどの件も同様でした）^^;、「これはチェックしてよ」的なご意見を戴きながら優先で対応している感じなので、こうした声を上げて戴けるのは大変助かりますm(_ _)m

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.97(64bit)にて動作確認。
キャプション未記入ままリンクを作成した時、自動的に既定値がセットされることを確認しました。
その状態で.xmlに出力してPg Flowにインポートしたもののリンクが正常に保持されていることも確認しました。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でリンクが維持されることを確認しましたー

**Comment by cocotori** [comment]
Chromeで確認しました。
次へというキャプションが勝手に入るのでいいですね。

ありがとうございました！
