### ISSUE TITLE
各種シートのON/OFFについて

### ISSUE THREAD

**Issue by RYU-DS** [snext1220/stext#195]
現在のシステムで自シナ（そのスレ）をプレイしてみて強く感じたのですが…
バトルシートを手動で呼び出すのはシナリオに集中しやすい半面、戦闘自体が意識の外に行きやすくバトルシートの呼び出しが特殊な位置なのも手伝って、戦闘をしないプレイを助長してしまっているように思えます。
そのスレのような戦闘メインのシナリオでは、戦闘をしない事はあくまで黙認（推奨もしなくはないですが…）であって、基本は戦闘をしてもらうスタンスなので、それを示す意味合いでも…

①戦闘が発生するシーンではバトルシートを自動で開く

ようにできませんでしょうか？
もちろん手動で閉じる事は可能で、それならば「自動シートオープンで戦闘が始まったが面倒なので自分の意志で閉じる」という流れになり、ずいぶん健康的？になると思います。
これまたもちろんですがシステムとして固定するのではなく、シナリオ側が設定できるようにして、そうすればシナリオ側でも「重要な戦闘時だけ開く」といった使い方もできます。

…とここまで書いておいてアレなんですが、現在の状態にも利点はあって、そのスレなんかでは延々とモンスター説明をしてから戦闘開始！という流れも多く、その場合はシーンテキストのどこまでを読んだらバトルシートを開いてほしいかを「Open the Battle Sheet!!」というようなテキストを挟むことである程度指定する、という使い方ができます。
そういう使い方を残す方法として…

②シートを開くキー（上記のような指定文章を入れて）をテキスト中に埋め込める

というのもよいかと思います。
贅沢をいえば①②両方とも可能にしてもらえると、いろんなタイプのシナリオやシーンに対応できて非常に良いかと。

またこれは他のシートも同様で、アイテムやフラグを入手/失うシーン、魔法使用/七星欠片変動シーン、ステータス変動シーン、それぞれで各シートが自動で開くのがより良いでしょう。

あとちょっとした思い付きなのですが、バトルシートを開いた状態用のBGMを指定できると、より一層RPGゲームのようになってよいので、ぜひ。

特に急ぎではないので、皆さんで検討・議論していただければと思います。

**Comment by snext1220** [comment]
リクエストありがとうございます。
こちらはAugust Updateとして、皆さんのご意見を待ちたいと思います。
暫しお待ち戴けますと幸いです。

皆さま＞どうぞよろしくお願いします。

**Comment by Salvadors-cabin** [comment]
「特定のシーンで自動でBattleSheetが表示される」をシナリオ側でコントロール可能にする、は賛成です。重要な戦闘シーンなどではテンポが良くなるのではないかと思います。
ルールなどを本文を読ませたい場合でも、#136 でBattleSheetに文章が書けるようにして頂いているので対応可能と思います。

**Comment by snext1220** [comment]
個人的には、本件全体的に消極的でしょうか。以下、その理由です。

+ 一定数以上、戦闘をスキップして進めている読者はいると考えておりまして、そうした層には却って邪魔になるのでは
    + 他シートの自動オープンも同様で、変化は文章で示すにとどめ、シートを確認するかはプレイヤーに委ねるべきではないか（STextの自動化方針としては**管理は効率化するが、操作は極力強制しない**のスタンスでおります）
+ 特にモバイル画面ではバトルシートが開くことでメイン領域が隠れてしまうので何が起こったかわかりにくい
    + 前シーンで説明文を入れても良いですが、であれば、現在のシーンで文章を入れてBattleSheetを入れても同じかと
    + ユーザー側で開く開かないを選択できるというのもないではないですが、そこまでするかは疑問
+ シートを開くキーについては、現状BattleSheetタブが常時表示になっているため、そちらで賄いたい

**Comment by toki-sor1** [comment]
> ①戦闘が発生するシーンではバトルシートを自動で開く

BattleSheetの自動展開は、RPGでモンスターとエンカントした時の「モンスターが現れた！」という場面を連想しますね。
よりコンピュータゲーム的な演出で、プレイヤーもドキッとして面白そうです。

ただ、**BattleSheet等の自動展開がゲームブックのメイン要素である「シナリオを読むという行為」を阻害する面もある**ため、悩ましくもあります。

上記理由から、私は**BattleSheetの自動展開は、今まで通りしない方針**がいいかなと思いました。

＃PCモニタだとBattleSheetタブがメイン画面と離れており、戦闘が意識の外に行きやすくなりますが、これはブラウザの幅を狭めれば解決するかなと
***
> ②シートを開くキー（上記のような指定文章を入れて）をテキスト中に埋め込める

シナリオを読む流れの中でサイドバーが開けるのは、テンポも良さそうな印象です。

ただ、Itemやflag等は加算・減算の自動処理が設定可能な項目であり、メニューバーも目立つ・操作し易いところにあるため、**テキストで展開されなくてもそこまで不便ではないかなと思っています。**

上記理由から、私は**シートを開くキーは、メニューバーで十分事足りているかな**と思いました。
***
> バトルシートを開いた状態用のBGMを指定

戦闘時にBGMが切り替わるのは、確かにRPGゲーム的ですね。メリハリがあります。
しかし、（個人的な感覚の話になるのですが、）STextはサウンドノベル寄りのゲームブックという認識なので、**私はシナリオ内で掛かっているBGMがそのまま戦闘でも流れている方が臨場感があって良いなぁ**と思っています。

**Comment by snext1220** [comment]
本件、今回は見送りのご意見が強めでもありましたので、今回はwontfixとさせていただきますね。
ご提案戴いたのに申し訳ありませんが、どうぞよろしくお願いいたします。
今後ともお気づきの点があれば、IssueでもTLでも宜しくお願いいたしますm(_ _)m
