### ISSUE TITLE
ゲーム画面メニュー画面の日本語化

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#196]
サイト側でのメニューのアイコン＆日本語化を行っておりますが、同様の処置をゲーム画面でも行えないかと思っております。まずは是非のご意見をうかがってからかと思いますので、ご意見うかがえれば幸いです。

@toki-sor1 さん＞実現の際は、恐縮ですがアイコンの作成をご相談させていただけますとm(_ _)m

#### アイコン化メニュー

+ Status（ステータス）
+ Magic（魔法）
+ Info（情報）
+ System（システム）

#### 日本語化のみ（二段目）

+ Character（キャラ情報）
+ Items＆Flags（アイテム／フラグ）
+ Result（実績）
+ Bonus（ボーナス）
+ Backup（バックアップ）
+ Restore（リストア）
+ Help（ヘルプ）
+ Exit（終了）

**Comment by toki-sor1** [comment]
ゲーム画面のメニューもアイコン化すると統一感が出そうですね。
アイコンのパターンをいくつか作成して、サンプルとして画像にはめこんでみました。

①光っているフォント違いのStatusアイコン（各ページのフォントと同じ）
②光っていないStatusアイコン
③光っているStatusアイコン（サイトと同じ仕様）
④光っている日本語化メニューアイコン
![ゲーム画面メニューサンプル](https://user-images.githubusercontent.com/42646342/84572336-3a3d7680-add4-11ea-828c-95e6518485df.png)

しかし、④の「光っている日本語化メニューアイコン」については、サイトのアイコンと同じように**フォントサイズが不揃いなところが気になりました。**
**こちらも一旦はそのままという訳にはいかないでしょうか？**

**Comment by snext1220** [comment]
早い！ｗ お忙しいところ、ありがとうございます～

個人的には、統一感という意味でも
> ③光っているStatusアイコン（サイトと同じ仕様）
が良いのかなと思いましたが、如何でしょうか。

> フォントサイズが不揃いなところが気になりました。
> こちらも一旦はそのままという訳にはいかないでしょうか？

上記書き方が悪くてスミマセン；
一段目メニューはアイコン化、二段目メニューについてはサイト同様日本語化のみ（アイコンなし）との意図でございました...お手数をおかけしてしまって申し訳ありません...

#117 共々、引き続きよろしくお願いいたします！

**Comment by toki-sor1** [comment]
ご意見ありがとうございます！
日本語化のみについて、盛大な勘違い失礼いたしました；；

③光っているStatusアイコン（サイトと同じ仕様）が統一感という意味でも良さそうということでしたので、**Status（ステータス）、Magic（魔法）、Info（情報）、System（システム）** のアイコンを作成し、O/Dにアップいたしました～。

ファイル名が長いので、もう少し分かり易くコンパクトにしても良いと思います～。

https://onedrive.live.com/?id=4837C202555BE782%216763&cid=4837C202555BE782

**Comment by snext1220** [comment]
早速ありがとうございました＆こちらGitHub Pagesに早速反映させていただきました！
＃ 日本語化のみ＞どんまいですｗ
画像については、ファイル名を若干短くしたうえで、/stext/common/menu フォルダーにUpしておりますので、修正される場合はこちらを置き換え戴けますと幸いですm(_ _)m

ところで、配置してみた処、Statusが他よりも大きいように見えたのですが、私の気のせいでしょうか；目の錯覚であれば良いのですが、念のためご報告です～

**Comment by toki-sor1** [comment]
こちらこそ早速の反映＆ファイル改名ありがとうございました！

> ところで、配置してみた処、Statusが他よりも大きいように見えたのですが、私の気のせいでしょうか；目の錯覚であれば良いのですが、念のためご報告です～

ひえええ申し訳ありません…！！
頭文字のみサイズを大きくしていたのを忘れたまま、各アイコンを作成しておりました；；
本日、アイコンを修正して差し替えました…！
![image](https://user-images.githubusercontent.com/42646342/84660646-1e60de80-af54-11ea-82c9-d4118813cdff.png)

**Comment by snext1220** [comment]
早速ありがとうございます！
そして、目の錯覚でなくてよかったですｗ
私の方も同期しまして確認いたしました～Goodだと思います！

**Comment by toki-sor1** [comment]
目の錯覚w  私もアイコン作成後にデスクトップに並ぶとアイコンの文字の大きさがバラバラだとは思ったのですが、まさかの設定ミスでした…w
的確なご意見、本当に助かりましたw

これで各項目がアイコンになりましたね。
ゲーム画面のSORCERIAN Textがテキストのままなので少し浮き気味ですが、他のアイコンと同じ仕様で画像を作成した方がいいでしょうか？

**Comment by snext1220** [comment]
ゲーム画面のSORCERIAN Text＞やはりここまでアイコン化すると、浮いてしまいますよね；私も配置した後悩んでいたのですが、統一感という意味では、現在のサイトロゴをそのままゲーム画面にも配置、というのもありでしょうか（その場合はこちらで対応いたします～）。区別するという意味では、ご提案の②もありかとは思いつつ、悩んでおります^^;

**Comment by toki-sor1** [comment]
ゲーム画面のSORCERIAN Textは、リオさんもお悩みだったのですね～；
そうですね、各項目のアイコンもサイトと同じデザインなので、統一感という意味でまずは**現在のサイトロゴをそのままゲーム画面にも配置**というのもありだと思います～。
（あとでサイズなどを調整したり、やっぱり②にするのも勿論OKです）

お手数をお掛けして申し訳ありませんが、サイトロゴの配置をよろしくお願いいたします。

**Comment by snext1220** [comment]
了解です～早速サイトロゴで配置してみました！
伴い、画像ファイルは/stext/common/menu配下に移動しておりますので、ご了承くださいm(_ _)m 

個人的には問題ないと思いますが、やはり区別した方が～などあるかと思いますので、ぜひご意見のほどをお願いいたしますm(_ _)m＞皆さん
＃ あとからの調整・変更問題ないとのことありがとうございます＞ @toki-sor1 さん

更に、本対応に伴い、GitHub Pagesの背景を#000に変更しています。
直接的には、旧来の白背景がロゴとミスマッチだったという理由ですが、これまでも本番環境との印象の違いで、本番移行時にスタイル調整が発生したことがあったので、これを解消する目的です。
＃ 背景画像を入れて完全に統一、も考えたのですが、一見区別できなくなるのも微妙かなと、背景は黒一色で^^;

**Comment by toki-sor1** [comment]
サイトロゴ配置ありがとうございました！
ただ、大変恐縮ながらスマホ環境でゲーム画面を見た時に**タイトルのでっぱりが文章に掛かっているところが気になってきました；**

それでゲームメニューに合わせた新タイトル画像を作成したのですが、差し替えても大丈夫でしょうか？；（ゲーム画面のタイトル画像のみ変更）

![gamebook_header_text4サンプル](https://user-images.githubusercontent.com/42646342/85292469-e4a15200-b4d6-11ea-8d39-f1124d638dc7.png)

> 更に、本対応に伴い、GitHub Pagesの背景を#000に変更しています。

本番環境とGitHub版の画面が統一されて良いですね！
壁紙ありorなしで環境の区別がし易いところも良い感じです！
こちらも素材作成の面で雰囲気が統一されて助かりました～！

**Comment by snext1220** [comment]
実は、スクロールで回避できればいいかなと目をつぶってたのですが、やはり気になられましたか…！^^; ご指摘の通り、読みやすさを損なうのは本末転倒ですし、新ロゴを拝見してすごく良い感じなので、Upをお願いできますでしょうか。

ただ、現在サイト側とファイルを共有しているため、/common/menu配下にgame_logo.pngのような別名でUp戴けますと幸いです～（従来のファイルはheader_logo.png）既にコード側はパスを変更しているので、Up戴ければGitHub Pages側には反映されるはずです～

**Comment by toki-sor1** [comment]
お忙しいところ、早急にご対応いただきありがとうございます…！！
はい～、メインの方では大丈夫だったのですが、やはりゲーム画面では気になってしまいました；

先ほどファイル名を「game_logo.png」に変更し、本番環境とGitHub環境の画像を差し替えました。
![image](https://user-images.githubusercontent.com/42646342/85297809-35687900-b4de-11ea-870c-6b9debc0cf89.png)

ようやく画像が変わったので確認してみたのですが、**ちょっと下側に寄っている**ように見えました。
**こちらで改善できるものであれば改善いたしますね。**

もし設定側で変更できるようでしたら、お手数をお掛けしてしまい申し訳ありませんが、お手隙の際に**タイトル画像が下にはみ出さない程度に上げていただけましたら助かります；**
（急ぎではありませんです～）

**Comment by snext1220** [comment]
あ、ちょうど今直したところでしたｗご確認ください！

**Comment by toki-sor1** [comment]
なんという擦れ違い！！ｗ
先に位置を修正してくださっていたのですね、お疲れ様でした＆失礼いたしました…！！
おかげでタイトルがしっかりと収まって、とても良い感じになりました～！

剣アイコンの件に続き、こちらも迅速にご対応いただき、本当にありがとうございました！

**Comment by snext1220** [comment]
こちらこそ重なるデザイン周りのご対応ありがとうございました！
テキスト中心のサイトながら、要所要所に素敵な画像を鏤められたことで、キリリと引き締まるサイトになってきたのではないかと…！今後ともどうぞよろしくお願いします～

**Comment by cocotori** [comment]
段々とおしゃれなサイトになっていくのが素敵です。
本当にお疲れさまです・・・！

後出しですみませんが、
せっかく日本語にするのであれば、
Backupはデータ保存、Restoreはデータ復元とかはどうでしょうか？
リストアはそこまで一般的ではないと感じたので。
とはいえそんなに難しい単語ではないと思うので、このままでも構いません。

ただ、Restoreがつづりが間違っており
Restorになっているようです。
ちょっと挙動がよくわからなくて、最初はRestoreで表示されているのですが、
ポインタを持っていって日本語にしてから見ると、
Restorに変化してしまいました。

**Comment by toki-sor1** [comment]
労いのお言葉やお褒めのお言葉ありがとうございます！
少しずつでも今時のデザインっぽくできたら良いなと思っていたので、お褒めいただけて嬉しいです！

> Backupはデータ保存、Restoreはデータ復元とかはどうでしょうか？

確かに、**日本語化するのであれば、こちらの表記の方が分かり易くて良いですね。**

> ちょっと挙動がよくわからなくて、最初はRestoreで表示されているのですが、
ポインタを持っていって日本語にしてから見ると、
Restorに変化してしまいました

Win 8.1／Chrome 83.0.4103.116(64bit)にて動作確認。
**私も同様の操作でRestoreがRestor（末尾のeが抜けてしまう）になることを確認しました。**

**Comment by snext1220** [comment]
ご確認ありがとうございます！

> ただ、Restoreがつづりが間違っており～

こちら失礼いたしました。誤植でしたので、修正済みです。

> Backupはデータ保存、Restoreはデータ復元とかはどうでしょうか？

はい、こちら私も日本語化の時に悩んだのですが、以下の理由から現状の表記としておりました。

**データ保存はセーブの意味にとれるため、バックアップの方が正確と思われる（さりとて、他に良い訳が中々見つからないという…）。バックアップをカナ表記とした場合、リストアの方が統一が取れる**

cocoさん仰るように、さほど難しい単語ではないかと思いますし、マニュアル、ユーティリティ側でもリストアという表記を主に利用していますので（一部は判りやすさを考慮して復旧などと併記）、統一性という意味でもママとさせていただけますと助かりますが、如何でしょうか。

**Comment by toki-sor1** [comment]
ご返信ありがとうございます＆修正お疲れ様です～！
なるほど、他の意味に取れる用語だと混乱の元になってしまいますし、用語の統一性についても考えないとですね。
では、BackupとRestoreについては、現状のままですね。承知しました！
