### ISSUE TITLE
サイドバー間の相互リンクボタン

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#197]
Status、Magic、Basic、Items＆Flagsなどの主要シート内で、相互リンク（ボタン）を設置する案です。いちいちサイドバーを閉じて、メニューから開きなおす手間を軽減します。
＃ 本格リニューアル前の仮デザインではあったものが一度破棄され、また復帰できないか、という案です。

#### 懸案など

+ PC環境では直接メニューバーから選択すれば、シートが切り替わるのでそこまで必須ではありません。主にモバイル環境向けです。
+ おそらく既存ボタンの下に配置することになるので、スクロールを極力発生させないため、配置は要検討。

**Comment by toki-sor1** [comment]
ギリギリ文字が読める＆縦幅と横幅を詰めたアイコンを２パターン作成してみました（サンプル画像のみ）。
ただ、どうしてもスクロールが発生してしまうのが悩ましいのですが…；

![ショートカットサンプル](https://user-images.githubusercontent.com/42646342/84571399-d44df080-adcd-11ea-97c3-797fa8b9f00c.png)
![ショートカットサンプル２](https://user-images.githubusercontent.com/42646342/84571847-0d3b9480-add1-11ea-8580-da75afc5e513.png)

**Comment by snext1220** [comment]
こちらも早速のご検討ありがとうございます！

> ただ、どうしてもスクロールが発生してしまうのが悩ましいのですが…；

そうなんですよね...特に大きなステータスシートは一定仕方もないと思うのですが^^;
デザイン的にも移動ボタンはバー上部の方が良いのですが（下だとボタンデザインの違いもあり、やはり建て増し感が強いですものね...）、本来のコンテンツを下に押しのけてまで、というと、悩ましいなぁと思考が止まっていました；

ただ、とりあえず相互リンクが必要なものを絞り込むのはありかなと。
具体的には、Result～Helpはゲーム中に頻繁にみるものでもないので、相互に移動できなくても（＝メニューバーからアクセスできれば）良いのかな、などと。

そして、残る4アイコンの配置については、以下のようにタイトル画像に回り込ませれば、縦幅を節約できるかなと。

![無題](https://user-images.githubusercontent.com/27911337/84582837-36d5d980-ae2c-11ea-9dcc-07cf77fdec43.png)

Item＆Flags、Magicなどのシートが悩ましいですが、こちらは縦幅が短いので、ときのじさんのご提案通り、横一列に並べる感じで（シートごとに不統一なのが気持ち悪くは。とすると、横一列で揃えるのもありかなとは思ってしまったりも^^;）

余談：Magic＆Stars、Items＆Flags、いずれもタイトルそのものを短くできると良いのですが...Magic＆StarsはMagicでよいとして、Items＆Flagsは難しいですね...

と、イマイチまとまらない意見をツラツラスミマセン...もう少し考えてみます^^;

**Comment by toki-sor1** [comment]
お忙しいところご意見ありがとうございます！
前回のサンプルでは、必要な項目を絞っても、スクロールが発生してしまう等の問題がありましたね；（しかもMagic＆Stars、Items＆Flagsは省略が難しかったりも；）

私も移動ボタンは上部にあった方が良いなと思っていたので、リオさんのご意見を参考に、アイコンは必要な4項目のみに絞り、絵で内容が伝わるようなアイコンを作成してみました。
なるべく各項目タイトルの絵と合わせてみましたが、如何でしょうか？
![ショートカットサンプル改２](https://user-images.githubusercontent.com/42646342/84587134-a0b7a880-ae57-11ea-9572-e2ecf668ec9d.png)

**Comment by toki-sor1** [comment]
絵メインのアイコン改め移動ボタンも少し手直ししてO/Dにアップいたしました。

https://onedrive.live.com/?id=4837C202555BE782%216763&cid=4837C202555BE782

灰色版は、例えばStatusページにいる時に、現在はStatusページにいることを示すためのものです。
こちらについては、思い付きで作成したものなので、未使用でもOKです。
※ファイル名が長めなので、もっと分かり易いものがあれば変更してやってくださいませ～
![image](https://user-images.githubusercontent.com/42646342/84595124-476c6b00-ae91-11ea-81b3-06f70a71c927.png)

**Comment by snext1220** [comment]
こちらも早速のご対応ありがとうございます。
まずは「GitHub Pagesのみ」「Statusシートのみ」反映させていただきました！（現状は横幅など節約のため、現在のシート**以外**のアイコンのみ配置しています）
画像については、/stext/common/side フォルダーに若干リネームの上でUpしておりますので、修正される場合はこちらを上書きいただければ幸いですm(_ _)m

以下、とりあえず配置しての懸案です。

+ 一応、ヘッダー画像とリンク画像とは同列に並んでいるのですが、ヘッダー画像の右側に空白があるため、改行されております。もし同列に並べる場合は、ヘッダー画像の切り取りが必要になりそうです（こちらで一部やってみたのですが、画像が荒れてしまったので、もし以下の件とも絡んで、必要であればご対応をお願いできますでしょうか...お手数をおかけします；）

+ Magic、Itemsの方はそもそもヘッダー画像（文字列）が長いため、現在の画像でも一行には入らなさそうです（以下スマホ配置でのイメージ）。となると、Statusまで含めて、次行にまとめた方が良いでしょうか？（それともStatusが項目も多いので、ひとつだけ例外に？）

![無題](https://user-images.githubusercontent.com/27911337/84596750-7c30f000-ae9a-11ea-99d7-5fd52d55f4d8.png)

+ おかげさまでイメージ沸きやすいアイコンに仕上げて戴いたのですが、リンクとなると、分かりやすさの意味で文字列があった方が無難かも、とも（好み、慣れ、感覚などありそうなので、ご意見うかがえますとm(_ _)m）もし文字列を入れる場合には、やはりヘッダー画像の下部に横並び配置ということになりそうです。
＃ モバイル環境ではもう少し画像自体を大きくしておきたいという思いもあったり、でも、なんとかスリム化もしたい、と矛盾した思いの中で悩んでおります...^^;

+ Charaシートはそもそものレイアウトが異なるので、何処にボタンを配置するかが悩ましく；（JOBの下、最上部など考えましたが、微妙ですよね...）そもそもStatus以外のシートからはStatusに戻れれば十分だったりしますでしょうか。

諸々まとまっていない意見で申し訳ありません；レイアウトの問題は、各人ご意見もありそうなので、お手数ですがご意見頂ければ幸いですm(_ _)m

**Comment by toki-sor1** [comment]
ご意見＆リネーム＆反映ありがとうございます！
しかし、なかなか悩ましい問題が山積み状態ですね；；

> ヘッダー画像の右側に空白があるため、改行されております。～

> おかげさまでイメージ沸きやすいアイコンに仕上げて戴いたのですが、リンクとなると、分かりやすさの意味で文字列があった方が無難かも、とも～

試行錯誤、本当にお疲れ様でございます…！
タイトル画像ですが、**文字列を入れるとなると、右側を削っても移動ボタンの配置は無理だろう**と判断し、削るのは一旦止めました；

> Charaシートはそもそものレイアウトが異なるので、何処にボタンを配置するかが悩ましく；

こちらも本当に悩ましい問題ですが、やはり**移動ボタンの位置がページ毎に異なるのは違和感があり、使いにくい印象が強いかな**と思います；

> そもそもStatus以外のシートからはStatusに戻れれば十分だったりしますでしょうか。

個人的には**Status、Magic＆Stars、Character、Items＆Flagsを自由に移動できた方が便利だと思います。**
***
移動ボタンという役割上、ページ上部にあった方が便利ですし、確定ボタンとの誤タップを防ぐという意味でも、私は**ページ上部に配置派**ですね。

Characterページとその他ページとのデザインの違いもあるので、ちょっと違和感はあるかもしれませんが、以下の案はどうでしょうか？

- 絵＋文字列の移動ボタンに変更
  - 各ボタンの色が違うのは、どの色が良いのかのテストです
- サイドバーの壁紙の絵柄を少し下げる
- タイトル画像以下を全て下げる
- 上部の空いたスペースに移動ボタンを配置する

![ショートカットサンプル改３](https://user-images.githubusercontent.com/42646342/84664516-9da4e100-af59-11ea-8207-9592357f64a8.png)

**Comment by snext1220** [comment]
こちらも早速の修正＆ご提案ありがとうございます。
上部に統一が操作的にも一番よさそうですね＆賛成です！

関連シートをそれぞれ暫定修正しましてGitHubにも反映済みです。
だいぶ良い感じになったのですが、、、スミマセン、スマホ環境ですと、やはり複数行になってしまいそうでして...詰めるとなると、文字のみ...にした方がよさそうでしょうか...（せっかく作成いただいたのに恐縮なのですが；）

![無題](https://user-images.githubusercontent.com/27911337/84672009-ff1d7d80-af62-11ea-9768-c7babf337c8d.png)

> 各ボタンの色が違うのは、どの色が良いのかのテストです

ありがとうございます～色的にはヘッダー画像と判別しやすいという意味で、個人的には白推しでしょうか。いっそ背景白潰し＆枠線にしてしまうのも、ボタンと分かりやすいという意味ではありかもしれません（好みの面も強そうなので、皆様のご意見も伺えれば）

**Comment by toki-sor1** [comment]
ご確認＆配置調整ありがとうございました！

いえいえ、ドット絵の件はお気になさらずに！
長めになったけど大丈夫かな～と思っていたら、全然大丈夫じゃなかったですね…（白目）
こちらこそ、スマホからの確認を怠ってしまい、申し訳ありません；；

ご意見を参考に移動ボタンを改良し、差し替えてみました（意図を取り違えていたらすみません；）。
こちらはiPhone 7からのスクショになりますが、こちらは一行に並んでいて大丈夫そうでした。
![IMG_3713](https://user-images.githubusercontent.com/42646342/84676132-13b04480-af68-11ea-9b79-dda60e8caac8.png)

**Comment by snext1220** [comment]
早速のご対応＆ご指摘ありがとうございます！
ぐんと目立つようにもなり、良い感じですね…！（文字数の多いItems～は若干判読性が悩ましいかもですが、まあ、慣れの問題かと^^;）
移動ボタンも右寄せで修正いたしました～（重複感、なるほど！）

半角スペースけしもありがとうございます～一寸間延びしているな、と思っていたところだったで、助かりました！！

**Comment by toki-sor1** [comment]
各ページ＆本番環境への反映ありがとうございました！お疲れ様です！！
（位置修正もありがとうございます！）
リオさんの的確なご意見もあり、スムーズに改良することができました！

ドット絵を入れていた名残で半角スペースを入れていたので、気になって消したのですが、間延びが解消されて良かったですｗ

先ほど文字にアンチエイリアスをかけて文字を滑らかにし、Items～は若干大き目にしてみました（GitHub、本番環境ともに差し替え済み）。
![image](https://user-images.githubusercontent.com/42646342/84772255-a529c000-b015-11ea-8dad-ab953282a1b2.png)

フォント自体が小さ目だと可読性があまり良くないのは気になっていたのですが、一か所に色んなフォントが混じっても違和感があるかなと、タイトル画像と合わせてました～。

**Comment by snext1220** [comment]
こちらこそ迅速なご対応ありがとうございました！
地味にアクセス性が改善するので、早めに実装出来てよかったです～

アンチエイリアスもありがとうございます～特にItemsは文字潰れ（荒れ）が気になっていたのですが、ぐんと見やすくなったと思います！！

**Comment by cocotori** [comment]
メニュー内の移動ボタン、とても便利だと思います！

あと、細かい話ですが、PCでCharacterにポインタを合わせたとき、
basicの表記になっていました。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

> basicの表記になっていました。

こちらですが、以前の表記が内部キーになっておりまして、これをもとにシートを呼び出していた関係で、表示されておりました。そもそも他のものもitem、magicなど、ユーザーに見せる情報ではないことから、別の場所に設定を映し、表示そのものがされないように改めました。ご確認ください～

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.116(64bit)にて動作確認。
正常に動作していました。便利になって良かったです！

> そもそも他のものもitem、magicなど、ユーザーに見せる情報ではないことから、別の場所に設定を映し、表示そのものがされないように改めました。ご確認ください～

GItHubは表示されないようになっていました。
現在はGItHubのみ設定が修正されている感じでしょうか？（本番環境では、basic等が表示される）

**Comment by snext1220** [comment]
説明漏れておりまして申し訳ありません；
はい、本日の更新はすべてGitHub Onlyです～本番環境反映はMilestone Close時にまとめて行いますので、修正確認はGitHub Pagesでお願いできますと…！
