### ISSUE TITLE
設定画面の新設

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#198]
すぐに、という話ではないのですが、SText／PgFlowも機能が揃ってきたところで、挙動カスタマイズのための設定画面を準備できればと考えています。コアに踏み込むと難しい＆どこまでをカスタマイズ可能にするかなどの問題もありますが、まずは「ここは切り替えられれば便利（人によって異なる）」などあれば、ご意見頂ければ幸いです。

以下例です。

+ Stext本体
    + 音声ボリューム
+ PgFlow
    + 簡易シーン追加時の増分値★済★
    + 作者名★済★
    + 初期テンプレート
    + Sceneのカラーリング（http://chanagame.hateblo.jp/entry/2020/07/25/190211 ）
    + ~~フロチャの表示形式~~
    + ~~HTML変換時の形式（シャッフル／縦書き）~~

**Comment by snext1220** [comment]
現在、試験的に設定画面のダイアログ作成を進めています（GitHub Only）。

+ 作者名
+ 初期テンプレート
+ フロチャの表示形式

現在は以上の内容が設定可能ですが、表示形式だけは機能が未完成なので、入力できるだけです（動作しません）。
これで基盤は最低限出来たので、今後は必要なものから追加していければと思います。

**Comment by toki-sor1** [comment]
ご対応お疲れ様です！
スピーカーアイコンと同じサイズ（30x30）でpg_config.pngというアイコンを作成してみました～。
stext/common/内にアップしておりますが、ファイル名や色合いなど大丈夫だったでしょうか？

![configサンプル](https://user-images.githubusercontent.com/42646342/90397802-59f26300-e0d3-11ea-95ec-cc4f07d532dd.png)

**Comment by snext1220** [comment]
おぉ、早速ありがとうございます！
実は、他のctrl_～.png系のボタンと同じイメージでいたのですが、役割も異なりますし、今回いただいた方が良いですね！！
GitHub Onlyですが、早速反映させていただきました～

**Comment by toki-sor1** [comment]
早速のご確認＆反映ありがとうございます！
私も最初は今回のようなデザインかctr_～.png系デザインかで迷ったのですが、枠＋歯車だとちょっとくどいかなと思ったので、枠なしで作っていましたｗ
役割が異なるということで、デザインも問題なさそうで安心しました！

**Comment by toki-sor1** [comment]
設定画面は、内容も見た目も問題ないです～。
今後の更新で、Stext本体の音声ボリュームが変更できるようになったらいいなと思ってます。

**Comment by snext1220** [comment]
動作問題ないようで良かったです。
ご確認ありがとうございます！
他の皆さまの確認も待って、Closeしてまいりますね。

音声ボリューム＞はい、SText本体の方もどこかで是非に（ひとつだけの設定画面も寂しいので、もう少し設定項目が溜まったら^^;）。

**Comment by snext1220** [comment]
本件、長引いてきておりますので、一旦Nov Updateに移動いたします～

**Comment by cocotori** [comment]
歯車イメージ、OKです！

内容についてですが、できるのかどうかわかりませんが、

BGM音量
SE音量
を個別に調整できるといいと思いました。

flowの設定画面については、
・シナリオデータ由来のもの
・エディタ制御由来のもの

にわけるといいのかなと思いました。

シナリオデータ由来のものは設定タブの方にもうけるのがいいと思います。
現在も基本タブに作者名がありますので、設定画面の方にはなくてもいいと感じました。

一方で、
簡易シーン追加時の増分値
初期テンプレート
Sceneのカラーリング（http://chanagame.hateblo.jp/entry/2020/07/25/190211 ）
（フロチャの表示形式→こちらは、自動onlyとなったことで廃止？）
HTML変換時の形式（シャッフル／縦書き）

等は、エディタ側の設定ですので、
設定画面にあるといいと思いました。

特に、カラーリングについては個別に設定したいという要望が
あるだろうなと思います。
　
　
あと、作ってもらった歯車ボタンなのですが、
ブラウザの横幅を狭くすると消えてしまいます。
右側に見切れてしまうのではなく、消えてしまいます。

横幅を広くすればいいだけなので大きな問題はありませんが、
編集シーンの選択等の他の項目は消えないので、
ちょっと気になりました。

**Comment by snext1220** [comment]
ご意見ありがとうございます！

> BGM音量 SE音量 を個別に調整できるといいと思いました。

現時点では双方同じコードで管理しているので分離が必要ですが、まずは可能です。
音量についてはリリース当初からの懸案になっているので、別途検討させてください。

> flowの設定画面については、
> ・シナリオデータ由来のもの
> ・エディタ制御由来のもの
> にわけるといいのかなと思いました。

あ、シナリオデータ由来～については、あくまで初期値とお考え下さい。
作者名については、基本いつも同じ値を入れているはずなので、既定で設定しておければという意図でした（表記は再度検討したいと思います）。

> 簡易シーン追加時の増分値
> 初期テンプレート
> Sceneのカラーリング（http://chanagame.hateblo.jp/entry/2020/07/25/190211 ）
> （フロチャの表示形式→こちらは、自動onlyとなったことで廃止？）
> HTML変換時の形式（シャッフル／縦書き）

はい、フロチャの表示形式は自動onlyなので廃止ですね～
＃ あとは、シャッフルも。
増分値は、現在のシーン追加ルールが落ち着いてから、ですね。

て、カラーリング、要望強いですか。正直、あまり真剣に考えてなかったので、今一度皆さんのご意見うかがいたく。基本は、現在のプロローグ、通常シーン、エンディング（グッド／バッド）の4種類を変更できる程度で？（種類を増やしたいとなると、規模は結構変わってきます；）

> あと、作ってもらった歯車ボタンなのですが、
> ブラウザの横幅を狭くすると消えてしまいます。

こちらは静かに二行目に折り返されています（横幅狭くすると、編集シーンなども消えていきます）。フロチャの後方に隠れているので、実質利用できなくなっている感じです。
ツールバーそのものを複数行化しようとも思ったのですが、現時点では微妙な分量なので＆仰る通り、横幅を広げればよいので、現時点ではママでも良いかなと放っています^^; 如何でしょうか

**Comment by cocotori** [comment]
>カラーリング

もちろんデフォルト固定でも問題ないのですが、
エディタのレイアウトや色を自分好みに変更できるというのは
結構、筆のノリにも影響するものだと感じていまして。

設定画面を作るのであれば、追加してもいいんじゃないかな、と個人的には思います。
自由に変えられるとなると対応が難しいと思いますので、
色分類数は増やさず、配色を自分で決められるイメージです。
　
　
>消える歯車ボタン

了解です！このままで大丈夫です。

**Comment by toki-sor1** [comment]
> BGM音量、SE音量の変更

前回BGM音量調整のみ意見を出していましたが、**SE音量も変更できるといいですね。**
ブラウザゲームでも見掛ける設定なので、需要はあると思っています。
BGM音量については、設定項目が溜まったらとのお話でしたね。了解です～。

> 高速モード（再描画の頻度を押さえ、高速化するモード）

大きなシナリオ制作によるパフォーマンスの低下は、GBATでも問題になっていましたね。
ツールの動作にもたつきが出るのは、どんなツールであっても気になるところなので、**高速モードがあると良いなと思います。**

> カラーリング

私は現在のカラー設定を変更できるようにするというよりも、**清書済みを表す1色を追加する**のと、**清書済みかどうかをチェックボックスで変更できる（チェックを入れると色が変わる）** という機能が良いかなと思っています。

ただ、全員がその機能を使うかどうかは分からないので、**Sceneを追加した時はチェックが入っていない状態（現在の水色）** が良いかなと思いました。

**Comment by snext1220** [comment]
お返事前後しますが、先行して清書モードについてです～
こちら［サマリー］欄末尾に（たとえば）「♪」などのマークを付けておく、という形では如何でしょうか（システムではなく、あくまでマイルールとして）

フロチャにカラーリングすることで完成度を視覚的に見られるという効果はありそうですが、制作管理用のフラグ的なものを設けていくと、用途に応じて、更に細分化されていきそうだな、と思いまして（汎用化していくと、結局はシーン単位にカラーを決定できるようにすべき、になりそうかなと^^;）。

勿論、そうしたニーズが強い場合には、本格的にカラーリングの見直しをできればと思っていますが、清書モードに限ると、上記の記号付けなどでニーズを満たしそうかなと思った次第です（この方法であれば、下書きシーンをシーン一覧からも一望できるので）。

**Comment by toki-sor1** [comment]
> こちら［サマリー］欄末尾に（たとえば）「♪」などのマークを付けておく、という形では如何でしょうか（システムではなく、あくまでマイルールとして）

お返事ありがとうございます！
こちらの方法だと、仰る通りシーン一覧から確認できるのが利点ですね。

ただ、こちらもまたリオさんも仰っていましたが、大きなシナリオになればなるほどフロチャの縮小率が高くなりますので、やはり**フロチャにカラーリングする方が完成度が一目で分かって良い**と感じました；

> （汎用化していくと、結局はシーン単位にカラーを決定できるようにすべき、になりそうかなと^^;）

うーん、個人的には今の配色で満足しているんですよね…。
あとは清書用に1色追加されたらいいかなぁと思っているのですが、そうですね、それはシーン単位にカラーを変えることに繋がるので、最終的に**シーン単位にカラーを決定できるようにすべき**に行きついてしまいますよね…；

せっかくご提案いただいたのに申し訳ありませんが、**エンディング2種類とプロローグはカラー固定で、それ以外のシーンのカラーを変更できる方が良い**と思いました；

**Comment by snext1220** [comment]
こちらは意見が割れている状況ですね^^;
以下の議論をdec updateに持ち越して確認していければと思いますので、ここまでの議論をもとに、お手数ですが、今一度ご意見頂ければ幸いです。
＃ 設定画面からカラーリングのお話になってしまいましたが、あまりに込み入るようであればIssue分離します^^;

#### プロローグ／エピローグ／基本シーンのカラー設定

+ 現在、賛成1、反対1の状況です。
+ システム的には対応は可能です。
+ 私個人的には、「筆のノリにも影響」「共通の方がマニュアル化した際にも説明し易い」いずれも結構納得で、賛成反対双方のご意見を引き続きうかがいたい、というレベルです。

#### シーン単位のカラー指定

+ @toki-sor1 さんからのご提案です。
+ システム的にはまだ検討の余地ありですが、大筋では中規模の影響で対応可能と見込んでいます（特に清書モードなど用途は定めず、カラーのカスタマイズを可能にする）。
+ 因みに、システム的には特定用途でのカラーリングは意外と影響が大きく、追加のたびにシステム対応が必要になるので、やるならば汎用的なカラーリング対応押しです。
     + ただ、フロチャを重くする原因でもあるので、マーキングで賄えるのであればそちらを優先したい、といったところでしょうか（100％でなくても90％は賄えるのかな、と押してみる^^;）

#### その他

+ BGMについては、仰る通り、他の設定項目が蓄積されてきたところでまとめ対応してまいりますね。他にカスタム要件の高い項目があれば、引き続きご意見をお願いします。
+ 高速モードもご賛同ありがとうございます。画面と実データの不整合をある程度許容するモードなので、まずは可能な範囲でチューニングを固めてから必要に応じて進めてまいりますね。
     + 現時点では遅延も落ち着いている?ように聞こえるので、まずは様子見状態です。

**Comment by snext1220** [comment]
上記件、とりあえずは「シーン単位のカラー指定」を対応し、本番環境にも反映しております。
ご確認いただけますでしょうか。

なお、選択できるカラーについては現時点で暫定ですが（プロローグと重なるなど問題もありですが、一旦は仮置きで）、自由に拡張できますので、追加のご希望は、サマリテキストが埋もれない範囲で「#xxxxxx」の形式で戴けますと幸いです。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 86.0.4240.183(64bit)にて動作確認。
各シーンのカラー指定ができることと、ファイル出力後の読み込みでも反映されていることを確認しました。

カラーについては、文字色が濃い目の灰色ということもあり「blue」は、サマリーの判別が難しいように思いました。
ただ、サマリーが判別困難であっても、フロチャ上でシーンの種類が分かれば良い、というケースもあると思いますので、そのままでも良さそうですね。

**Comment by snext1220** [comment]
> ただ、サマリーが判別困難であっても、フロチャ上でシーンの種類が分かれば良い、というケースもあると思いますので、そのままでも良さそうですね。

了解です！
他にご意見なければ、まずはママで行ければと思います～

＃ ちなみに、現在のカラーはHTMLの標準16色から既に使われていたもの＆黒を除いたもの、で選択しています。

**Comment by cocotori** [comment]
chromeで確認しました。

背景色としてはまずは試しで、これだけ種類があれば十分だと思います。
現状、枠線と背景色が全く同じ色になっているようですが、
（それか枠線が消されてしまっている？）
枠線は例えば黒固定でもいいのかなと思いました。
そうでないと、背景白は周りと同化してしまって実質使えないと思いました。

**Comment by snext1220** [comment]
> 現状、枠線と背景色が全く同じ色になっているようですが、（それか枠線が消されてしまっている？）

こちらスミマセン、カラーを指定した場合には、データの持ち方の関係で（主にxmlでも維持させる関係から）枠線／背景色を一致させざるをえない状態ですね...
＃ プログラム的に無理やり枠線を付けてやることもできますが、一寸ひと工夫必要になりそう

白については仰る通りなので、現時点では白を排除という形にできればと思いますが、如何なものでしょうか。

**Comment by cocotori** [comment]
白削除で当面問題ないと思います！
