### ISSUE TITLE
【PgFlow】特殊リンクの簡易作成

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#199]
［Add Link］ダイアログから以下の特殊リンクを生成可能にしました。GitHub Pages Onlyで対応済みなので、ご確認戴けますと幸いです。

+ ランダム
+ 自由移動
+ テキスト入力

大概の用途には足りるかと思いますが、ランダムリンクのキャッシュ期間は改めてEdgeタブから追加、Orderは固定値（こちらも後で変更は可）など制限はあります。まずはお試しください。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で確認しました。
Add Linkダイアログの「追加情報」の下のボックスに入力しようとすると以下のようにundefinedの表示が並ぶ画面が出ました。
![199](https://user-images.githubusercontent.com/42834363/85870251-c9508280-b807-11ea-944c-1324d46fd6a3.png)
想定された動きでしょうか。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

> Add Linkダイアログの「追加情報」の下のボックスに入力しようとすると以下のようにundefined～～

こちらは一応正しい動きです。
シーン選択のための一覧を表示していますが、summaryが未設定のためにundefinedが表示されています。summaryを設定すると、その値が表示されると思うのでご確認くださいませ～

なお、summaryを設定していない場合のために、一応、「id: summary」の形式で表示されるように、先ほど修正いたしました。現在は、summaryなしの場合は「100: null」のような形式に変化しているかと。

**Comment by Salvadors-cabin** [comment]
ご説明ありがとうございます。
summaryが設定されているシナリオでテストしたところ、表示されることを確認しました。

>なお、summaryを設定していない場合のために、一応、「id: summary」の形式で表示されるように、先ほど修正いたしました。現在は、summaryなしの場合は「100: null」のような形式に変化しているかと。

そうですね。これならsummaryが設定されていなくても違和感はないと思います。
Win10+Edge環境で問題ないことを確認しました。

ただ、関連した問題があるようなので  #200 を参照願いますー

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！

問題なさそうでよかったです。ご指摘いただいた［Add Link］タブはじめ、［リンク］タブのid欄（2か所）など、計4か所に展開させていただきました～（GitHub Pagesのみ）
ご指摘ありがとうございました！

**Comment by cocotori** [comment]
使っていて、いくつか気になる点がありました。

リンクの追加ボタン：
・自由移動選択時に、上の、id:n->m　のところを入力しないと、0へのリンクが生成される？

・自由移動選択時に、上の、id:n->m　のところに例えば3と入力し、
　追加情報のところにも3,4,5とか入力すると、3へのリンクが2本生成される。

・自由移動選択時に、追加情報を空っぽにして追加すると、フロー上では見えない、
　空っぽのリンクが生成されてしまう。

（ランダムでも共通の問題あり？）

自由移動選択時は追加情報を空っぽにしない、追加情報と上のidのところに同じリンク先を入れない
などの使い方を決めてしまえば問題ないとは思いますが、操作がやや直感的ではない気がします。

例えば、
通常のリンクのときは上の項目だけ入力できるようにし、
ランダムや自由移動のリンクのときはidの項目は入力できず、
追加項目が空欄だと追加ボタンが押せない、などの制御が
できると間違いがないかなと思いました。

実装が難しそうであれば、このままでも大丈夫です！

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.116(64bit)にて動作確認。
各種リンクが追加できることを確認しました。
また、私の環境でもココさんと同じ不具合（？）が再現できました。

> 自由移動選択時に、追加情報を空っぽにして追加すると、フロー上では見えない、
　空っぽのリンクが生成されてしまう。

ただ、こちらに関してですが、私の方ではフロチャ上にリンクの矢印自体は表示されていました。
しかし、シナリオをプレイすると、**何の文字列も入力せずにシーン移動可能だが、シーンidが空白のシーンに移動してしまう**という状況でした。

ココさんとほぼ同意見なのですが、可能であれば、**指定したリンクに必要な情報が入力されていない場合or不必要な情報が入力されている場合は、警告が出るなどしてリンクが追加できないようにできたら、リンク追加ミスが減らせそうかな**と思いました。

**Comment by snext1220** [comment]
ご指摘ありがとうございます！
以下の対応で検討していければと思います。

+ 空入力チェックを行う
+ 追加情報と上のidに同じリンク先がある場合はひとつにまとめる

https://github.com/snext1220/stext/issues/185#issuecomment-653772983 とも方針としては合致するかなと思っていますが、如何でしょうか。

**Comment by snext1220** [comment]
ご指摘ありがとうございます！
とりあえず以下の対応を行いました。

+ リンク先idの必須チェック（元々は0へのリンクとしていましたがエラー化）
+ 通常リンク以外の追加情報必須チェック
+ テキスト入力リンクでの正解文字列必須チェック
+ リンク先と追加情報のid重複時の束ね

https://github.com/snext1220/stext/issues/185#issuecomment-653772983 とも方針としては合致するかなと思っていますが、如何でしょうか。

**Comment by cocotori** [comment]
Chromeで確認しました。
追加修正、ばっちりでした！

**Comment by toki-sor1** [comment]
早速の修正お疲れ様です＆ありがとうございます！

Win 8.1／Chrome 83.0.4103.116にて動作確認。
修正された機能が正常に動作していることを確認しました！
うっかり表記ミスやリンクミスを減らせて良いと思います！

**Comment by snext1220** [comment]
お二人ともご指摘＆ご確認ありがとうございました！
まずは問題ないとのことよかったです～
PgFlowも益々機能が増えてきて、分かりにくい（操作を間違えやすい）機能も多くなってきているかと思いますので、ご指摘大変参考になります。重ねて有難うございます！
