### ISSUE TITLE
BONUSダイアログの表示崩れ

### ISSUE THREAD

**Issue by toki-sor1** [snext1220/stext#20]
Windows8.1／Chrome 69.0.3497.81（64 bit）にて確認。
※iPhone／Safariでは該当アイテムが入手できず未確認

BONUSダイアログで＜ギャルのパンティー＞をクリックすると、ダイアログの上下に白い空白が表示されてしまう。
![default](https://user-images.githubusercontent.com/42646342/45366835-c082c280-b61a-11e8-87ec-d055bc89d13d.png)

**Comment by snext1220** [comment]
説明文字列が長いための問題でした。
説明文を短くし、対処しています（本番環境Update済）。

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 69.0.3497.81（64 bit）にて確認。
正常に表示されていました。修正ありがとうございました。
