### ISSUE TITLE
【PgFlow】リンク追加ダイアログでのシーン選択

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#200]
リンク追加ダイアログのシーン選択欄で、リンク先のシーンidをサイドバー（一覧）から選択できるようにしました。これでid値入力が随分と簡単化したのではないかと。

**Comment by Salvadors-cabin** [comment]
Add Linkダイアログの「id:」の下のボックスに入力しようとしたときに表示されるシーン選択画面で、summaryが設定されていない場合はundefinedと表示されます。
#199 で対応していただいたように"id: summary"表示の方が統一感の面からもよいのではないかと思います。

**Comment by snext1220** [comment]
#199 共々ご指摘ありがとうございます！
現在GitHub Pages Onlyですが対応済みですので、ご確認くださいませ～

＃ 本番環境にはある程度まとまったところで、反映してまいりますのでお待ちくださいませm(_ _)m

**Comment by Salvadors-cabin** [comment]
早速の対応ありがとうございます。GitHUB／本番環境でsummaryが表示されることを確認しました！

**Comment by cocotori** [comment]
Chromeで確認しました。
正常に動作しています！

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.116(64bit)にて動作確認。
正常に動作していました。

**これはフロチャ上で確認するよりも見易くて、選択するだけでidが自動入力されるところが楽でいいですね！**
