### ISSUE TITLE
【PgFlow】［リンク］タブでのid値変更

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#201]
［リンク］タブでid値を変更できるように改めました。
依然として、フロチャからのリンク付け替えも可能ですが、タブからの変更が可能になったことで修正がより簡易になったのではないかと。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でリンクが変更できる事を確認しました。

**Comment by cocotori** [comment]
Chromeで確認しました。
正常に動作しています！
