### ISSUE TITLE
【PgFlow】［シーン］タブにシーン追加ボタン

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#202]
［シーン］タブに［シーン追加］ボタンを追加しました。
これによって、新規にシーンを作成すると共に、現在のシーンからのリンクを自動生成できます。
シーンを継ぎ足しながら、執筆を進めるような状況で利用戴ければと。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でシーンが追加できる事を確認しました。

**Comment by cocotori** [comment]
Chromeで確認しました。

便利ですねこれ！
わたしの作り方だとほとんど順繰りにシーンを追加しているので、
この機能が今後役立ちそうです。

**Comment by snext1220** [comment]
ご評価ありがとうございます！
私も、今後はこの機能がシーン／リンク追加のメインの操作になっていくのではないかと思っております^^;

＃実は、フロチャ上での編集機能や、メニューバーからのシーン追加が要らないくらい？などとも。
前者はすぐさまになくすことはないと思いますが、後者は皆さんのご意見如何ではカットしても良いかななどと思い始めたりもしています^^;（操作のシンプルさを維持するという意味で）

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.116(64bit)にて動作確認。
正常に動作していました。

シーン同士が繋がった状態で自動的にシーンとリンクが追加されるのは、とても便利な機能ですね！
単独でリンクさせる手間が省けるのは作業のし易さにも繋がりますし、**メインで活躍しそうな機能です！**

> ＃実は、フロチャ上での編集機能や、メニューバーからのシーン追加が要らないくらい？などとも。

メニューバーからのシーン追加は、GBATの操作と近いものがありますよね。
ただ、GBATとは違い、縦並びのリスト（outline）が目立つところに表示されていないのと、フロチャでは横並びの追加されてゆくため、ちょっと見辛さもありますね；

同じような機能がいっぱいあると混乱してしまうので、操作のシンプルさを維持するために、**こちらは様子を見つつカットも視野に入れる感じになりそう**…ですかね？

**Comment by snext1220** [comment]
> 単独でリンクさせる手間が省けるのは作業のし易さにも繋がりますし、メインで活躍しそうな機能です！

ご評価ありがとうございます！
これでPgFlowの作成方法がかなり変化するかな、と思っていたので、ぜひ活用してやってください～

> こちらは様子を見つつカットも視野に入れる感じになりそう…ですかね？

は、こちらは悩み中です...
https://github.com/snext1220/stext/issues/185#issuecomment-653762181 では、ご評価の声も戴いておりますので、ひと月待っての判断でしょうか（一応、折角実装したいので使って戴けるのであれば残してやりたいという欲も反面で^^;）

outlineについて、現時点では対応するのはメニューバーの選択ボックスですね...仰る通り見やすいとは言えないので、そもそもリンク時のid選択と同じ形式で、サイドバーとして表示するのもありでしょうか（常時表示されていなければ意味がないとする、意味ないかもですが^^;）。

> フロチャでは（リンクされてないシーンは）横並びに追加されてゆくため、ちょっと見辛さもありますね；

ここは現状ライブラリの制約で致し方ないですね...横並びの幅を狭めて少しでも見やすく、とは調整したのですが...；
あとは、そもそも最大値idのシーンに対して自動でリンクしていく、という方法もありますが、却って使い道を限定してしまいそうですね；

**Comment by snext1220** [comment]
上記は #185 にて継続議論としまして、本IssueはCloseとしてまいりますね。
