### ISSUE TITLE
【PgFlow】シーンidの変更機能

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#203]
従来、一度設定したシーンidは変更できませんでしたが、［シーン］タブの［変更］ボタンから修正できるようにしました。関連するリンクにも自動反映されます。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でテストしました。機能的には問題無かったのですが、「変更」ボタンを押した後のポップアップ画面のボタン名が「追加」になっているのが気になりました。
流れから、「OK」「変更」「決定」あたりが適切かと思います。

**Comment by snext1220** [comment]
ご指摘ありがとうございます！
まさに、ですね；（コピペまるばれで^^;）
GitHub Onlyですが、［変更］にて修正させていただきました～

**Comment by cocotori** [comment]
Chromeで確認しました。

個人的には使う頻度は高くないかもしれませんが、
後から変更できるのはありがたいと思います！

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.116(64bit)にて動作確認。
正常に動作していました。

私はあとからシーンを追加したり、削除したりすることが多く、テキストエディタでシーンidをせっせこ修正していたりするので、**この機能はありがたいです～！**

**Comment by snext1220** [comment]
> 私はあとからシーンを追加したり、削除したりすることが多く、テキストエディタでシーンidをせっせこ修正していたりするので、この機能はありがたいです～！

複数環境での編集は、ファイルも増えたりして、やはり面倒ですものね。
お役に立ちそうで良かったです！
内部的にも結構大きな変更だったので、ぜひ使ってやってください！
