### ISSUE TITLE
【PgFlow】シーンidのシャッフル機能

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#204]
ちゃなさんからのご要望を受けてのIssueです。
https://twitter.com/ChanaGame/status/1275981888205684736

PgFlowに試験的にシーン番号のシャッフル機能を実装してみました（GitHub Pages Only）。ソーサリアン Text本体では利用しないものですが、主にhtml形式での出力を想定した機能です。
https://snext1220.github.io/stext/playground/

+ 右上部の［Shuffle］ボタンを押すと、シャッフルされた結果がストレージに保存されます。
+ シャッフルされた結果は［テンプレートを選択］から「マイストレージ」を選択してロードしてください。

現在はid=0のシーンだけが固定化されていますが、将来的には指定のidはシャッフルされずに固定する機能も実装する予定です（正確には、既に機能そのものは実装していますが、固定フラグを立てるUIがないので動作しない^^;）。

※α版以前レベルの内容なので、シャッフル前のデータは必ず保存してください！！

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でシャッフルが機能しましたー

**Comment by cocotori** [comment]
シャッフル機能がChromeで動作することを確認しました。

ただ、これとは別件なのですが、「シナリオを保存」の中の.html（For Browser）の
機能がうまく働かないような気がします。
最初一回だけ保存ができたのですが、その後何度押してもファイルが生成されず・・・
xmlやjsonは問題ないのですが。
htmlの場合は何かこれらと使い方が違いますか？

**Comment by snext1220** [comment]
> 最初一回だけ保存ができたのですが、その後何度押してもファイルが生成されず・・・

本件、本番／GitHub双方で確認してみたのですが、再現せず...恐縮ですが、開発者ツールのConsoleになにか出力されていないかを確認いただいてもよろしいでしょうか。

＃ 仕様上、画像を参照している場合、画像が見つからない「GET http://localhost/stext/playground/set.png 404 (Not Found)」のようなエラーは画像の数だけ出力されると思うのですが、それは問題なしです。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.116(64bit)にて動作確認。
正常に動作していました。

ただ、#205 の報告と内容が被りますが、**「英雄」と「双王」は、idの付け方が特殊なためか、.htmlファイルとして出力できませんでした。**
（.xml形式と.json形式は、出力できました）
