### ISSUE TITLE
【PgFlow】HTML出力機能の改善（シャッフル／縦書き対応）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#205]
#204 の関連Issueです。

+ .html形式の出力にシャッフル機能を適用しました
    - 【要議論】シャッフルの有無を選択式にする？（現在は常にシャッフル）
+ .html形式の出力を縦書きレイアウトに修正しました
+ 出力時にシーンidはすべて漢数字に変換
+ 標準markdownの適用（SText拡張をどこまで適用するかは要検討）

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 83.0.4103.116(64bit)にて動作確認。
正常に動作していました。
ただ、**「英雄」と「双王」は、idの付け方が特殊なためか、.htmlファイルとして出力できませんでした。**

縦書きレイアウトやシーンidの漢数字変換、とてもいいですね！
電子書籍化を意識したシャッフル機能もよいと思います！

現在のSTextシナリオは、.htmlファイルとして出力後に文章の表示が崩れる等の問題はありますが、それは元々がこの出力機能を前提とした作り方をしていないので、こちらは変換非推奨として割り切る感じですね。

**最初からこの出力機能を使うことを前提にしてシナリオを作成するのであれば、大活躍間違いなしだと思います！**

> 【要議論】シャッフルの有無を選択式にする？（現在は常にシャッフル）

**選択式が良いですね。**
今まで通りのやり方でシャッフルしたいというケースも考えられますし、縦書き変換はゲームブック作成以外にも電子書籍化に際して活躍しそうな機能なので。

**Comment by snext1220** [comment]
英雄についてのみ確認してみました。
to：2114、2184で問題が出ているようでした。
こちらリンク切れしているように見えるのですが、如何でしょうか（そこでシャッフルに失敗していました）。
きちんと見切れておらず申し訳ありませんが、 @toki-sor1 さんの方でもご確認戴けますと幸いですm(_ _)m

> 現在のSTextシナリオは、.htmlファイルとして出力後に文章の表示が崩れる等の問題はありますが、

はい、縦書き向けの表記はシナリオ側である程度意識して戴く前提ですね～
もちろん、漢数字への変換など、システムでなければできない（あるいはその方が便利）なものは対応検討いたしますので、お申し付けください。

> 選択式が良いですね。

ご意見ありがとうございます！
おそらくHTML出力は真剣にKindle対応など考えていくと、色々出てきそうですね。
シャッフルについてはご指摘の通りと思いますので、PgFlow設定画面（#198）にて継続検討してまいりましょう～

**Comment by toki-sor1** [comment]
> to：2114、2184で問題が出ているようでした。

お忙しいところ、シナリオの不具合をチェックしていただき、本当にありがとうございました…！
Sceneとリンクは、恐らく削除し忘れていたものだと思います；；
**原因のSceneとリンクを削除したところ、.html形式で出力されることを確認しました！**
お手数をおかけしてしまい、申し訳ありません；；
先ほど、GitHubと本番環境に修正したscenario.xmlと編集したstext.xmlをアップしました。

「双王」ですが、すぐに原因が特定できなさそうなので、こちらは縦書き非推奨ということもあり、一旦保留とさせていただきますね；　申し訳ありません；；
***
> idの漢数字への変換など、システムでなければできない（あるいはその方が便利）なものは対応検討いたしますので、お申し付けください。

はい～、その際はよろしくお願いいたします！

> シャッフルについてはご指摘の通りと思いますので、PgFlow設定画面（#198）にて継続検討してまいりましょう～

承知しました！　引き続きよろしくお願いいたします！

**Comment by snext1220** [comment]
英雄解決とのことよかったです！
HTML出力はシャッフルの関係でより厳密にリンク関係など見ているため、どうしてもこうした問題が出てきますね^^; エラーをチェックしながら、問題のあるidは出力して...なども考えたのですが、PgFlowで作成している限り、リンク切れはないかな、と現時点ではママにしております。今後html出力を前提にしたシナなど作成していく中で、ご要望も伺えればと…！

「双王」についてはざっと見た限りでは、空のsceneがあるのが原因であるようでした。完全にはチェックしておりませんし、本Issueとしては（仰る通りhtml出力を想定していないシナなので）Closeしてしまいますが、ご参考までに～
