### ISSUE TITLE
セーブデータの更新対応（グローバル）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#206]
従来、セーブデータの仕様変更はプレイ中のセーブデータに影響を及ぼすため、気軽にできない仕様になっていました。しかし、ここにきて、セーブデータに影響が出る変更が出始めているため、セーブデータのフォーマットに変更があった場合には、既存データにもこれを反映させるしくみを設けたいと思います。

見た目には影響は出ない予定ですが、内部的には大きな変更のため、まずはグローバルセーブデータを対象に修正行い、その上でローカルセーブデータに着手できればと。

#### 0714追記：対応し、GitHub Pagesのみ反映済みです。グローバルセーブデータ（ストレージのsorcerian_textキー）がある環境、ない環境で動作に問題ないかを確認戴けますと幸いです。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でnextsキーを使ったグローバルセーブデータの引継ぎを確認しました。
結果、次シナのキャラクターのCLASSとAGEが表示されないので引き継がれていないのかもしれません。(下の画像）
Freeや状態は引き継がれていました。
![nexts](https://user-images.githubusercontent.com/42834363/89090290-04cd0680-d3dd-11ea-9c33-efe0b3351f00.png)

**Comment by snext1220** [comment]
こちら、言葉足らずで申し訳ありません。グローバルセーブデータのフォーマットを変更した時に即座に反映させる仕組みで、nexts属性とは別物でした。現時点では通常操作でグローバルセーブデータ（実績、ボーナス、BGMのオンオフなど。詳細は https://sorcerian.hateblo.jp/entry/2018/11/01/211745）の破損などが発生していないかをごかくにんいただければ幸いです。

で、今回ご指摘の点ですが、引継ぎ側のシナリオで引き継いだ種族、年齢を許可していない、ということはありませんでしょうか。その場合割り当てができないので、ご指摘のような現象が出るように思えます。

**Comment by Salvadors-cabin** [comment]
>こちら、言葉足らずで申し訳ありません。グローバルセーブデータのフォーマットを変更した時に即座に反映させる仕組みで、nexts属性とは別物でした。

なるほど。そういう事だったのですね！
あらためてボーナス、BGM、実績が引き継がれていることを確認し、問題なかったです。

>で、今回ご指摘の点ですが、引継ぎ側のシナリオで引き継いだ種族、年齢を許可していない、ということはありませんでしょうか。その場合割り当てができないので、ご指摘のような現象が出るように思えます。

失礼しました。まさにその通りでした。

**Comment by snext1220** [comment]
無事に解決したようでよかったです！
グローバル～の確認もありがとうございます…！

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 84.0.4147.105(64bit)にて動作確認。
グロ－バルセーブデータに破損がなく、実績、ボーナス、BGMのオンオフなど各種データが引き継がれていることを確認しました。
