### ISSUE TITLE
【PgFlow】シーン／リンク削除

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#207]
鏡読みさんからのご意見を戴いてのIssueです。
https://twitter.com/kazamyomi09_wd/status/1282170796861878272

［シーン］［リンク］タブから現在編集中のシーン／リンクを削除できるようにします（シーン削除では関連するリンクも削除）。August Updateまでの改定でほぼフロチャからの操作がほぼ不要になっていましたが、この改定で完全にタブシートからの統一された編集が可能になります。

**Comment by cocotori** [comment]
Chromeで確認しました。
ボタンで選択シーンが消えました。

機能的には問題ありませんが、だいぶボタンが増えて
雑多な印象になってきてしまったので、
どこかで整理がいるかもしれませんね・・・
今の所、改善案は思いつかないのですが。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

> どこかで整理がいるかもしれませんね・・・

そうですね^^;
#185 でも話題に上っていますが、不要な機能や重複した機能を削除していく必要はありそうです。
削除そのものは追加よりは簡単なので、あとはどこを？ですね～
今のところ、やや気になっているのが…

+ メニューバーの［Add Scene］は利用要件がなければ削除？
+ フロチャ本体の［Edit］バーはほぼ［シーン］［リンク］タブの各種ボタンで代替可能なので削除可能

そもそも雑多な印象が強いのがどの部分かにもよるので、実は（メニューバーではなく）各タブのボタン配置が～などもありそうですし、同じ機能でも複数の操作があった方が便利、というご意見もありそうなので^^;、引き続きご意見頂ければ幸いですm(_ _)m

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境においてボタンでシーンが消えることを確認しましたー

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 84.0.4147.105(64bit)にて動作確認。
各タブのボタンにてシーン／リンクが削除できることを確認しました。

しかし、ぱっと見て何処に削除ボタンがあるのか、少し探してしまいました；
（雑多な印象になってきた、という問題に繋がる部分かなと）

削除ボタンを追加ボタンの近くに置くのは、誤操作の原因にも繋がるので止めた方がいいですよね。
そうなると、**削除ボタンを赤文字にする（赤枠を付ける）など、もうちょっと目立ったボタン**にすると分かり易いかもしれません。

**Comment by snext1220** [comment]
ご指摘ありがとうございました！
こちらボタンのキャプションのみ赤にしてみましたが、如何でしょうか？

その他、PgFlowの機能削除（整理）については、現時点で方針が絞り込まれていない状況なので、以下Issueにて「削除要」の旨のみメモ書きしております～
https://github.com/snext1220/stext/issues/159#issuecomment-663861917
削除／整理リクエストなどは、一旦そちらでお願いいたします～（私も適宜書き溜めていきたいと思います） ある程度方向見えてきたところで、独立したIssueを立てて対応していければと思っていますので、どうぞよろしくお願いいたしますm(_ _)m

**Comment by toki-sor1** [comment]
> こちらボタンのキャプションのみ赤にしてみましたが、如何でしょうか？

早速のご対応ありがとうございます！
黒文字が多い中、削除ボタンの赤色がワンポイントとなって見易くなりました！

**Comment by snext1220** [comment]
ご確認ありがとうございます～では、こちらはこれでCloseしてまいりますね！
