### ISSUE TITLE
ポストモードの新設

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#208]
鏡読みさんのツイート由来のIssueです。
https://twitter.com/kazamyomi09_wd/status/1282226681659355136

開発時に周辺の方々に気軽にテストプレイをお願いできるよう、ポストモードを追加しました。ポスト時に一時的に生成されるフォルダーをロードし、プレイできるようにする機能です。
ただし、あくまでテキストの確認であり、独自BGM、イラストは反映されません。
※ポストモードのURLは投稿時の通知メールに記載されるよう、改めました。

@Salvadors-cabin さん＞本改定に伴い、恐縮ですが、**/postフォルダー配下は公開時に削除**（＝即座に消さないで）戴くようお願いできますと幸いです。

### 追記

現在、PgFlowから投稿されたデータは、/playground/postフォルダーに展開していますが、今後、/stextフォルダー配下に直接配置することを検討しています（これによってイラスト／独自BGMについてもリアルタイムに反映されるようになります）。ただ、投稿が多くなった時には（あるいはゴミ投稿が増えてくると）/stextフォルダー配下の掃除が面倒になる恐れはあります（今時点では全く問題ないと思いますがｗ）。

また、既存のシナリオを更新することも検討しております（PgFlow上での投稿時に更新パスワードを発行）。stext.xmlのデータベース化が必要ですし、これまでにも何度か出て、廃案になってきたものですが、投稿＆リアルタイム反映はやはり今後も課題になってくると思われ、こちらで再提案しておきます（いつどこまでやるかは要検討です）。

これらについては皆さまのご意見をうかがえますと幸いです。

#### 開発メモ

+ MySQL Tables  --- series, scenarios, utility, 
+ Form --- scenarios
+ save -> xmlwriter

**Comment by Salvadors-cabin** [comment]
投稿したものがすぐに公開環境で動作確認できるというのはとてもよい機能だと思います。

ただ、公開後の更新については悩ましいですね。「ちょっと修正して試してみたい」と思っていても即公開されてしまいます。
公開後は別名で投稿する事にして、公開に関しては管理者（我々）がコントロールする方がよいかもしれません。

**Comment by snext1220** [comment]
ご確認＆ご評価ありがとうございます！

公開後の更新＞この辺、本当に悩ましいですよね；
STextのメリットとしてサポートの手厚さはあると思うのですが、反面、「我々と対話しないと投稿できない」が意外とハードルになっているのかな、と懸念していまして。我々として事後に投稿内容の確認はしていくとして、投稿者さんからは我々の影がある程度見えなくなっていく方が良いのかなとも^^;

> 「ちょっと修正して試してみたい」と思っていても即公開されてしまいます。

画像／音楽まで完全版での確認したい、というニーズですかね～？
こちらは暫定Uploadモードなどを設けるのはありかと思っております。

いずれにせよ、メリット／デメリットありますし、システム的には超大改定なので^^;、引き続きご相談させて戴けますと幸いです～

なお、以下如何なものでしょうか。

> 現在、PgFlowから投稿されたデータは、/playground/postフォルダーに展開していますが、今後、/stextフォルダー配下に直接配置することを検討しています

こちらは変更内容は些細と言えば些細なのですが、サルバさんの作業に直接影響してくるので、念のため確認でございます。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 84.0.4147.105(64bit)にて動作確認。
無事にテストプレイ用のURLが送信され、遊べることも確認しました。
（こちらでテストデータの削除も可能なのですが、混乱を招かないために、サルバさんにはお手数おかけしますが、鏡読みさんのテストデータと一緒に私のテストデータの削除をお願いいたします；）

> STextの強みとしてサポートの手厚さはあると思うのですが、反面、「我々と対話しないと投稿できない」が意外とハードルになっているのかな、と懸念していまして。我々として事後に投稿内容の確認はしていくとして、投稿者さんからは我々の影がある程度までは見えなくなっていく方が良いのかなとも^^;

私も**この辺りの「やり取りの多さ」が投稿者様にとっては逆に負担になっている（もしくは、投稿し辛い理由になっている）のでは**、と考えておりました。
そのため、スタッフ以外の方とも気軽にテストプレイが行えるシステムは、とても良いと思います！

> 公開後は別名で投稿する事にして、公開に関しては管理者（我々）がコントロールする方がよいかもしれません。

私もサルバさんと同意見ですね。
シナリオ投稿後、即時にシナリオが反映されるのは魅力的です。
しかし、そうなった時に嫌がらせ目的などの迷惑行為が必ずしもないとは言い切れません。
**シナリオ初投稿時に関しては**最低限「スタッフが目を通し、認証する」という時間は必要だと考えます。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

> シナリオ初投稿時に関しては最低限「スタッフが目を通し、認証する」という時間は必要だと考えます。

ちなみに、更新時は如何でしょうか。

この辺、個人的にはAndroid/iOSパターンと呼んでましてｗ（アプリ登録時、Google Playは初期も無審査、問題あるアプリがあれば随時ロック。対してApple Storeは初期に審査、通過したものを公開）

どちらもそれなりに問題なく運用されていることから、個人的には**投稿がきちんと通知され、管理者によって目を通されている限り、事前認証に拘らなくても良いのかな**と思っていたりします^^;

それよりも、どうしても**「やり取りの多さ」が投稿者様にとっては逆に負担に**、が気になっていまして、特に、初期投稿時に実質スタッフの誰かに声をかけなければならないのは、かなりのハードルなのかなぁと。

また、更新時という意味でも、今回鏡読みさんが公開後誤字が～などとつぶやいている様子でしたし、そうしたものの修正を気軽にできる環境を極力作っていきたいな、と思っています。

粘ってしまって恐縮なのですが、**システム的には超級の大規模修正**なので、ゆるゆる進めるという意味でも、この辺、引き続きご意見頂戴しつつ、ご相談させて戴けますと幸いです。恐らく実現するとしたら、以下のような感じで段階を踏んで年がかりの修正になると踏んでいます。

+ stext.xmlのデータベース化（運用ルールそのものは変わらず）
+ データベース更新のためのしくみ構築
+ 更新時のみ自動反映を認める
+ 初期投稿時にも自動反映を認める

**Comment by Salvadors-cabin** [comment]
>なお、以下如何なものでしょうか。
>
>現在、PgFlowから投稿されたデータは、/playground/postフォルダーに展開していますが、今後、/stextフォルダー配下に直接配置することを検討しています

おっしゃるように現時点では全く問題無いです。

>（こちらでテストデータの削除も可能なのですが、混乱を招かないために、サルバさんにはお手数おかけしますが、鏡読みさんのテストデータと一緒に私のテストデータの削除をお願いいたします；）

了解です。さきほど/postフォルダのテストデータとともに削除しておきましたー。

>それよりも、どうしても 「やり取りの多さ」が投稿者様にとっては逆に負担に 、が気になっていまして、特に、初期投稿時に実質スタッフの誰かに声をかけなければならないのは、かなりのハードルなのかなぁと。

確かにそれも感じますね。
ただ、変更権限は今のところ我々にしかないためにセキュリティ的な問題は起きないのですが、各ユーザで変更できるようにするには一般的なWebサービスのようにアカウント作成してもらって、変更範囲を制限（自シナのみに）できるようにしないといけないかな、と思います。
そうでもしないと、どのシナリオでも変更できるようになってしまうのではないでしょうか。

**Comment by snext1220** [comment]
> おっしゃるように現時点では全く問題無いです。

ご了承ありがとうございます！では、この方針で修正作業を進めてまいりますね。

> 各ユーザで変更できるようにするには一般的なWebサービスのようにアカウント作成してもらって、変更範囲を制限（自シナのみに）できるようにしないといけないかな、と思います。

恐らく実装するとしたら、もっとシンプルにシナリオごとに、変更パスワードを設定し、それでもって変更を許諾する形になるかと思います。アカウント作成するよりは若干セキュリティ弱いですが、GitHubにマスターがあるので、最悪の場合も、いきなりデータが消失する危険は低いのかなと。

**Comment by snext1220** [comment]
PgFlowの投稿先を/stextフォルダー（通常シナリオをUpしている場所）に改めました。
これでテストプレイでも画像、音声などすべて反映されるようになります。
ご確認戴けますと幸いですm(_ _)m

**Comment by Salvadors-cabin** [comment]
GitHUBのPgFlowでPostボタンからダイアログに入力し、投稿ボタンを押すとエラー表示になりました。テキストだけなのでサイズが8MB以上という事はないです。
![208](https://user-images.githubusercontent.com/42834363/91997238-d6906d00-ed74-11ea-871a-b8c3d5f3005b.png)

Win10+Edge環境で確認しましたが、他の環境では問題ないでしょうか。

**Comment by snext1220** [comment]
すみません。GitHub Pagesではアップロードに対応できないため、本番環境のみの機能となります。本番環境でご確認戴けますと幸いですm(_ _)m

**Comment by Salvadors-cabin** [comment]
なるほどー、了解です！
/stextフォルダにアップされることを確認しました！

**Comment by cocotori** [comment]
現在、問題となっているのが、

1: 投稿時にスタッフとのやり取りが発生し、心理的、作業的な壁になっている。
2: 公開前にテストプレイを他の人にお願いする環境がない。
　（あるにはあるが、データを渡して、playgroundにupして・・・等、現実的でない）
3: さらに言えばBGM・画像を含めたテストプレイの場がない。
　（こちらもあるにはあるが、ローカルサーバーは現実的でない）
4: シナリオ公開後、更新に時間がかかる、手軽に行えない。

でよろしいでしょうか？

そして、やりたいと考えていることが、

・テストプレイ用の、仮の公開場所を用意。
・シナリオの即時更新。まずは更新時、最終的には、初投稿時から。
・シナリオ投稿に際して、スタッフの手を通さず、ユーザー自身でできる。

と言ったところでしょうか。


その上で、

postモードによりテストデータが即時アップ、かつ他の人とも共有できるようになったのはとてもいいと思います！
chromeで確認しましたが無事投稿できました（データは消しておきました）。
修正もすぐに反映されて素晴らしいと思います。

修正方法が少しわかりにくかったので、
初投稿時と同じようにpostから投稿してください、と
メールの文面などに記載されているといいなと思いました。

再投稿は何か気をつけることはありますか？
現状だと、同じメールアドレスならば同じシナリオフォルダが作られるのでしょうか？

これで、問題点の2,3は解決されたと思います。

問題1についてですが、

こちらが、何が問題になっているのかいまいち把握しておらず・・・すみません、現状の流れを教えてほしいのですが、

・ユーザーさんがpostにて投稿
・メールでサルバさんに連絡がいく。シナリオは仮の場所に自動アップロード。
・サルバさんからスタッフに投稿があった旨を連絡
・スタッフでテストプレイ
・問題がなければ、サルバさんが公開作業、その後ユーザーさんにメールで連絡。

という流れであっていますでしょうか？
これだけを考えた時、個人的にはそこまで
ユーザーさんにとって手間になる要素がイメージできませんでした。
それとも、もう少し細かいやりとりがあるのでしょうか？

もちろんユーザーさんがpostボタンを押してみようと思えるまでの壁はあるかと思いますが、
それは自動更新型にしても同じように思います。

今後投稿が増えたときに、スタッフの手間を軽減するという意味での
自動更新なら効果があるかと思いますが、
ユーザーさんにとっては自動更新でもスタッフ更新でもそれほど変わらないような・・・気がしています。

公開後の更新も、他の作品公開サイトを見ても数日間かかるのはそれほど珍しくないように思います。
小説サイトなどは早いですね・・・あれは即時更新でしょうか。


あえて、心理的抵抗感について思い当たるフシがあるとすれば、
stextは人の匂いがしすぎる、ことでしょうか。
スタッフの手厚い、ツールの使い方サポート、テストプレイ、問題点の指摘。
それこそがstextの強みでもありますが、
逆に、迷惑をかけてしまうなと負担に思ってしまう方もいるかもしれないなと思います。

postフォームによる投稿はそういう、人の匂いを感じさせなくするのに一役買っているので、
いいと思います。

例えばなんですけど、投稿フォームにスタッフによるテストプレイを望むかどうかのチェックボックスを設けるなどして、
微修正だからわざわざ見なくていいよ、
という意思表示ができるようにしておくといいのかも、と思いました。


まとまらなくて申し訳ありませんが、
わたしは、無理してユーザーさんによる更新方式に舵を取らなくてもいいのでは、と思います。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 85.0.4183.83(64bit)にてテスト投稿しました。
BGM、SE、intro.pngを添付して投稿し、正常に再生・表示されてシナリオも遊べることを確認しました。
テスト後に本番環境のテストフィル一式も削除済みです。

> 再投稿は何か気をつけることはありますか？
現状だと、同じメールアドレスならば同じシナリオフォルダが作られるのでしょうか？

私がうっかり間違えてscenario.xmlを読み込まない状態で投稿してしまい、scenario.xml読込＋シナリオ紹介のみ変更して再投稿したところ、同じフォルダ名のURLが送られてきました。
何らかの方法で初投稿シナと再投稿シナが同一シナリオなのかを判別しているのでしょうか。

> あえて、心理的抵抗感について思い当たるフシがあるとすれば、
stextは人の匂いがしすぎる、ことでしょうか。
スタッフの手厚い、ツールの使い方サポート、テストプレイ、問題点の指摘。
それこそがstextの強みでもありますが、
逆に、迷惑をかけてしまうなと負担に思ってしまう方もいるかもしれないなと思います。

私が投稿者様の負担について気掛かりだったのは、まさにこのことでした。
運営側の負担削減のことも含めての意見ですが、やはり一番は**投稿者様の投稿ハードルを低くし、心理的負担を軽減する**のが目的ですね。

> 投稿フォームにスタッフによるテストプレイを望むかどうかのチェックボックス

ご自分のペースでシナリオの投稿や手直しをしたい、というケースもあると思います。
スタッフによるテストプレイを望むかどうかを選択できると良さそうですよね。

**Comment by snext1220** [comment]
皆さま、ご検証ありがとうございます！

> 何らかの方法で初投稿シナと再投稿シナが同一シナリオなのかを判別しているのでしょうか。

基本的にはブラウザー単位で判定しております（初期投稿時にユニークキーを発行し、次回以降もそれで判別）。よって、ブラウザーを変えたり、ストレージをクリアしたりすることで、別キーを持たせることは可能です（どちらかというと、スパムで大量データを投入されるのを防ぐのが目的です）。

> 投稿者様の投稿ハードルを低くし、心理的負担を軽減するのが目的ですね。

私も同意見です（ @toki-sor1 さん、言及ありがとうございます！）

**Comment by snext1220** [comment]
本Issueについては議論が収束していないと思われるため、Nov Updateに継続いたします。

＃ システム対応は規模も大きい＆運用にも影響するため、次回Updateで全員の積極的な合意がない場合はwontfixかなとは思っております（個人的には推進派ですが、見切りでは辛そう^^;）。

**Comment by Salvadors-cabin** [comment]
>心理的抵抗感

そうですね。これは少なからずあるでしょうね。
私も投稿者さんとのやりとりの中で
「お手数おかけしすみません」→「いえいえなんでも言ってください」
のようなやりとりはよくあるので、こちらはそうは思っていなくても「敷居」はあるのではないかと思います。

**Comment by snext1220** [comment]
> 「お手数おかけしすみません」→「いえいえなんでも言ってください」
> のようなやりとりはよくあるので、こちらはそうは思っていなくても「敷居」はあるのではないかと思います。

まさにこれですよね...^^;

---

ただ、現時点で「全員の積極的な合意」には至っていないように思えますので、ただ、このままwontfixにするには忍びないので。議論をゼロクリアしないために、一旦、Updateからは外してIssueとしては残せればと思っております。
＃「やっぱり自動化したいよね！」という声が強く上がってきたところで、議論が再開できればと^^;

**Comment by snext1220** [comment]
@Salvadors-cabin さん＆皆さん：

度々失礼致します。
現時点では、スタッフの皆さんの意思が揃っていないので、大きな修正は避けた方が良いと思うのですが、最低限、以下の方策をとるのはありかと思いました。

**新規登録時に、シナリオごとにFTPユーザー権限を付与する**

新規登録時のフローはこれまで通りですが、これによって以降の更新は読者さんが自由に行えることになります（ユーザー権限は新規登録時にフォルダー名が決まったところで私の方で行い、サルバさんにお伝えいたします）。

勿論、GitHubとの同期は必要なので、更新時は声がけ必要にはなりますが、都度でなくとも、ある程度落ち着いたところで教えてくれればよい、という程度であれば、随分と違うのかなと。

如何なものでしょうか。

**Comment by Salvadors-cabin** [comment]
>新規登録時に、シナリオごとにFTPユーザー権限を付与する

ユーザーさんから要望があれば問題無いと思います。

>POST時にid／passwordの一致で直接更新を可能にする（メール送信もあり）

こちらの方がよいかもしれませんね。
先月のちゃなさんのシナリオ開発では、POSTをかなり活用してもらっていたと思います。
公開後も同様の操作で更新できるのは分かりやすいと思います。

**Comment by cocotori** [comment]
細かいバグ修正や確認で他の人の手をわずらわせるのが
心理的な壁として大きいと思うので、
ユーザーさんの方で直接更新できる方法があるのはありがたいと思います。

>POST時にid／passwordの一致で直接更新を可能にする

この方法が、個人的にはよいと感じました。

**Comment by snext1220** [comment]
@Salvadors-cabin さん、 @cocotori さん：

ご意見ありがとうございます。
こちら一定のご賛同を得られたと思われるので、「POST時にid／passwordの一致で直接更新を可能にする」の方向で修正を進めていければと思います。

別Issueでシナリオidの話題も出ていますし、3周年優先の関係から、実際のUpdateは来年以降になる見込みですが、お待ち戴けますと幸いです（適宜追加でのご意見は歓迎です）。

**Comment by Salvadors-cabin** [comment]
了解しました。
ドラモードの更新完了報告に合わせて連絡しておきますー

**Comment by toki-sor1** [comment]
返信が大変遅くなり、申し訳ありません…！

> 「POST時にid／passwordの一致で直接更新を可能にする」
が以下のような問題があったため、今回は見送っております。

問題が幾つか出ていることと、時期的に大きな修正は避けた方がよい、という理由から**上記案の見送りに賛成です。**

> 新規登録時（ご要望の人のみ）に、シナリオごとにFTPユーザー権限を付与する

今までは、ゲスト様がシナリオを修正・更新したくても気軽にできない環境でしたので、**こちらの案の実装はとても良いと思います。**
