### ISSUE TITLE
Nextサイトのバナー修正

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#21]
先日の議論でNexrtMVが廃案になったことで、
Nextサイトトップ（http://www.web-deli.com/sorcerian/next/default.aspx ）のバナーを
修正する必要があります。

大変お手数ですが、以下バナーのリサイズ版を作成戴くことは可能でしょうか。
http://www.web-deli.com/sorcerian/next/images2/stext00.png

bynameで、また、お忙しいところ恐縮ですが、ときのじさんご検討頂けますと幸いです（High扱いですが、対応はどこかで必須というだけで、急ぎというわけではございません）。

＃ 単純にリサイズのみにするか、デザインの変更も加えるかは、ときのじさんご判断にてお願いいたしますm(_ _)m

**Comment by toki-sor1** [comment]
２パターン作成してみました。
上と下のどちらか良さそうな方をお選びいただいた後、改めてO/Dにアップしようと思います。
よろしくお願い致します。
![text_nextmv _topbanner1](https://user-images.githubusercontent.com/42646342/45430077-829ba200-b6df-11e8-811e-a679360bd078.png)
![text_nextmv _topbanner2](https://user-images.githubusercontent.com/42646342/45430080-84656580-b6df-11e8-9032-094d5d16ca7a.png)

**Comment by snext1220** [comment]
STextページと若干差別化と言う意味で、上に一票です～

**Comment by toki-sor1** [comment]
それでは、上のバナーに決定ですね。
新規作成したバナーをO/Dにアップし、過去のバナーはボツ素材置き場に移動しました。
ファイル名も若干変更していますので、バナー差し替え時に変更していただければ助かります。
https://onedrive.live.com/?id=4837C202555BE782%217611&cid=4837C202555BE782

**Comment by snext1220** [comment]
迅速なご対応ありがとうございます！
早速Nextサイトにも反映させていただきました！
