### ISSUE TITLE
【PgFlow】エディターの選択状態

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#210]
以下ツイートに基づくIssueです。
https://twitter.com/ChanaGame/status/1286816466893856768

シーン選択時にテキスト選択を解除するよう、改めています。

**Comment by cocotori** [comment]
Chromeで確認しました。
OKです。

確かに全選択状態で役立つことは特にないように思うので、
よい改善だと思います！

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で修正されていることを確認しました

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 84.0.4147.105(64bit)にて動作確認。
全選択ではなくなっていることを確認しました。全文消去の危険が減って安心ですね！
