### ISSUE TITLE
【PgFlow】リンクリストの表示順

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#211]
https://github.com/snext1220/snext-management/issues/18#issuecomment-667667558 由来のIssueです。

> ・リンクのタブで表示順を弄っても、シーンのタブで編集するリンクを選択のプルダウンメニューに反映されないので、表示順が変更されたかどうかわからない。

ソートキーとして表示順を加えて表示するよう、改めております（GitHub Only）。
ご確認戴けますと幸いです。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でシーンタブのリンク表示順が変更されていることを確認しましたー

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 85.0.4183.83(64bit)にて動作確認。
リンク表示順を変更した後、シーンタブのリンク表示順も変更されていることを確認しました。

**Comment by cocotori** [comment]
chromeで確認しました。指示通りの順番になっていました。

実はこれ気になっていたので、修正されてよかったです！
（指摘せずにおり、すみません）
