### ISSUE TITLE
【PgFlow】［シーン］タブの情報更新について

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#212]
https://github.com/snext1220/snext-management/issues/18#issuecomment-667667558 由来のIssueです。

> ・リンクのタブで選択肢の内容を変えても、そのままシーンのタブに戻ったとき反映されない。一度シーンを変えると反映されるが、まどろっこしい。

リンクリスト選択時に最新の情報を取得するよう改めております（GitHub Only）。
ご確認戴けますと幸いです。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でシーンタブのリンク内容が変更されていることを確認しましたー

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 85.0.4183.83(64bit)にて動作確認。
リンクのタブでリンクの内容を変更した後にフロチャやシーンのタブのリンクリストが最新の情報に変更されることを確認しました。

**Comment by cocotori** [comment]
chromeで確認し、リンクタブの変更がシーンタブに即反映されていることが確認できました。

この機能自体はこれでいいのですが、
リンクを選んでいるときの、シーンタブって何を表すのが正解なんでしょうね。
ちょっと気になっています。

現状だと、最後に選んだシーンになっているようです。
それも正解ですが、例えば、
リンクを選んだらその直近のシーンにしてほしいという人もいるかな・・・と思いました。
わかりにくいので、画像で説明します。
画像の場合、最後に、シーン1,2,3のどれが選ばれていてほしいか、
結構人によるのではないかと思いました。

![z](https://user-images.githubusercontent.com/42885160/92297213-e035f280-ef77-11ea-835d-ce6e79a5d1d3.png)

そういう誤解を防ぐためにも、
リンクを選んだときはシーンタブは選べないようにし、
シーンを選んだときはリンクタブは選べないようにするのもありなのかなと思いました。

ふと思ったレベルですので、要望というほどのものではないです。

**Comment by snext1220** [comment]
@cocotori さん：

ご意見ありがとうございます。
こちら、私も、誤解を招かないという意味で、仰る通り**リンク選択時は［シーン］タブを無効化** も検討していたのですが、あえて無効化しても選びなおさなければならない手間が増えるだけなので。完全な正解でなくても完全な間違いでないのであれば、残しておけば使えるシーンもあるだろう、程度で現状ママとしておりました^^;

画像の場合、最後に、シーン1,2,3のどれが選ばれていてほしいか＞は、仰る通り、人にも依りそうですし、そもそも状況にも依りそうですよね...；
