### ISSUE TITLE
【PgFlow】シーン／リンクの追加ルールについて

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#213]
https://github.com/snext1220/snext-management/issues/18#issuecomment-667667558 由来のIssueです。
本件は、方針面を決めてから動いた方が良さそうなので、まずはご意見頂けると幸いです。

> ・リンクを追加した後でそのリンクを選ぶ選択肢のテキストを入れようとしてもリンク先の選択が出ない。一度別のシーンにカーソルを合わせて再度選択すると可能になる。

フロチャ上からのリンク追加ということですね。
こちらは仰る通りの現象になるかと思います。
［シーン］タブ側の選択肢をリフレッシュするようコード修正できますが、フロチャからの編集機能をそのまま使い続けるかで悩んでいます（ライブラリ標準の機能で、あまり使い出も良くないため）。

現時点では、［シーン］タブの［リンク追加］ボタンの利用を推奨しておりますが、如何なものでしょうか。こちらであれば、リンク＋シーン追加をまとめてできますので、より作業がスムーズになるのではないかと。

> ・シーン追加を選んで空白をクリックするとAdd Sceneのタブが出るが、そこでidを手動入力しなければならない。空いているidが自動で入力された方が手っ取り早いのでは。（ソーサリアンTEXTだと10番おきとかを推奨してるからそれも相性が悪いかも？）
> ・「シーンを追加」ボタンを押すと新たなシーンが作成されるが、その際にそのシーンのテキストに飛ぶか、現在選択中のパラグラフからリンクを自動で張るとかの機能があった方が使い勝手が良いかも。

上記2点は、スタッフ内でも話題に上ったのですが、シーン番号の付け方が人それぞれのため、勝手に紐づかない方が良いという意見が強かったものでした；上記の通り、［シーン］タブの［リンク追加］ボタンの利用で賄えないかと考えておりますが、如何なものでしょうか。

**Comment by olreia** [comment]
この度は大変お世話になりました。
＞現時点では、［シーン］タブの［リンク追加］ボタンの利用を推奨しておりますが、如何なものでしょうか。
＞上記2点は、スタッフ内でも話題に上ったのですが、シーン番号の付け方が人それぞれのため、勝手に紐づかない方が良いという意見が強かったものでした。
おっしゃる通りですねー。私の作風だと、シーン番号を空けずにどんどんチャートを書いていって、最後に一度だけシャッフルするのが最も効率が良いので、［シーン］タブの［リンク追加］ボタンを押した際に、自動で新しいシーン番号が生成されてくれるといいかなー、と思ったのです。欠番のシーン番号をいちいち調べて入力するのが面倒だったので……。しかし、自動生成はソーサリアンTEXTの作風とは合いませんね。とりあえず適当にシーン番号を入れていって、最後にパラグラフシャッフルで整理するのが一番良いかもしれません。

ただ、パラグラフシャッフルにはまた別の論点があります。スレ違いで恐縮ですが……
・現状だと、HTML出力の時にパラグラフシャッフルするようになっているかと思いますが、パラグラフジャンプその他のパラグラフ番号に関するギミックを伴う作品の場合、「シャッフルするか固定したままかをパラグラフごとに指定する機能」は必須になります。
・また、随時パラグラフシャッフルによりシーン番号を整頓できると、現在の総シーン数が都度明確になるので便利です。しかしこの機能もソーサリアンTEXTにはあまりなじまないかも。。
・後これは思考実験レベルのマニアックな話なのですが……パラグラフシャッフルした結果として、「40→41」とか「23→35or36」みたいな分岐ができないようなアルゴリズムを組むことって、可能なんでしょうか？？経験上、100パラだとほぼ確実にこういう「美しくないジャンプ」が生成します。後から手直しするんですけど。。
・これ以外にも、後から手直しすることが非常に多いので、パラグラフシャッフルはHTML出力のタイミング以外に随時可能な方が有り難いです。。
毎度のことながら自分本位な意見ばっかりで申し訳ありません。。

**Comment by snext1220** [comment]
@olreia さん：

こちらこそPgFlowをご利用いただき、本当にありがとうございました。
もう何度でも言ってしまうのですが、ご指摘の一つ一つがPgFlowの血肉となっていくのを強く実感しております！ちゃなさんの創作活動にも少しでもお役に立ったのであれば良いなと思っております。

さて、戴いた件のお返事です。
パラグラフシャッフルの改善については新Issue #219 を立てていますので、合わせて参照戴けますと幸いです。

>［シーン］タブの［リンク追加］ボタンを押した際に、自動で新しいシーン番号が生成されてくれるといいかなー、と思ったのです。

現在の機能ですと、PgFlow上部ツールバーの［シーンを追加］ボタンがお勧めでしょうか。こちらは指定の増分（＋XXXX）に従って自動採番してくれるもので。ただ、リンクは手動で付けることになるので、どちらが簡単？というのはあるかもしれません^^;（とりあえずGBATには近い操作感なのかなと思われます）

> とりあえず適当にシーン番号を入れていって、最後にパラグラフシャッフルで整理するのが一番良いかもしれません。

はい、シャッフル前提ですと、確かに最初の採番はあまり意味がないので、そちらで賄えるようであればその方が良いですね～この辺、ご利用いただきながら、引き続きご意見頂ければ幸いですm(_ _)m
