### ISSUE TITLE
【PgFlow】ブラウザー保存データのロード方法

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#214]
https://github.com/snext1220/snext-management/issues/18#issuecomment-667667558 由来のIssueです。

> ・一旦ブラウザに保存を選んでページを更新するとシナリオが消える？ブラウザに保存したはずのシナリオをリロードする方法がわからない。

ブラウザーに保存したシナリオは、［テンプレートを選択］から「マイストレージ」を選択することでロードできます。

本件、セーブ時に、その旨をダイアログ表示するように修正済みです（GitHub Only）。
ご確認戴けますと幸いです。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でダイアログ表示、保存したデータのロードを確認しましたー

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 85.0.4183.83(64bit)にて動作確認。
ブラウザに保存した後にダイアログが表示され、マイストレージについて説明が書かれていることも確認しました。

**Comment by cocotori** [comment]
chromeで確認しました。ダイアログ、無事出てています！
