### ISSUE TITLE
【PgFlow】シーン冒頭の空白が削除される

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#217]
https://github.com/snext1220/snext-management/issues/18#issuecomment-667667558 由来のIssueです。

> ・各シーンの最初の空白（段落下げ）が反映されない？データをリロードするたびに段落下げがなくなっている。

.xmlファイルをPgFlow形式（.json）に変換する際に前後の空白を除去していたことが原因でした。末尾の空白だけを除去するように改めました。GitHubのみ反映しております。

**Comment by toki-sor1** [comment]
動作確認環境：　Win 8.1／84.0.4147.105(64bit)

今度は.xmlファイルの一行目の段落が意図したとおり下がっていることを確認しました！
早速のご対応ありがとうございました＆お疲れ様でした！
（返信内容が https://github.com/snext1220/stext/issues/215#issuecomment-669192489 と重複するため、同文で失礼いたします～）

**Comment by cocotori** [comment]
chromeで確認しました。
文頭の空白は消されず、末尾のみ消されており、
仕様通りになっていました。

ちなみに、末尾の方も、
空白を消してしまう理由ってありますかね？
何か機能上、そのほうがやりやすいならばいいのですが、
特に意図がないなら、製作者さんの意図通りの記述が
できたほうがよいのではと思いました。

例えば、シーン移動のボタンをすごく下にずらしたいときなど。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

末尾～については、本文の末尾に意図しない空行が入っていた時（経験上、意外と意味のない空行が混じることは多い）、シーン移動ボタンが下にずれたりずれなかったりとばらつくのが目的でした。

仰る通り、製作者のご意図ママとするのがあるべき、というご意見も理解できるのですが…システム的には、「ボタンをすごく下にずらしたい」のような具体的な要件がないのであれば、現状維持の方が無難ではないかというスタンスではあります。

勿論、ご要望次第で「空白処理は一切しない」はできますので、今一度ご意見いただければ幸いです。

**Comment by toki-sor1** [comment]
> 仰る通り、製作者のご意図ママとするのがあるべき、というご意見も理解できるのですが…システム的には、「ボタンをすごく下にずらしたい」のような積極的なご要望がないのであれば、現状維持の方が無難ではないかというスタンスではあります。

**空白処理は一切しないの方が自然で分かりやすいかな**と思いました。

現状では、HTMLタグを使うことで意図的に2行以上の空行を作ることも可能なようですが、キーを押すだけで2行以上の空行を作れないので、その辺りの操作はちょっと直感的ではなく、分かりにくい印象です。
（私も最初それに気付かず、やたら回りくどいことをして空行を入れていました…お恥ずかしい…）

おそらく自分が気付いていないだけで、自作シナでも末尾の無駄な空行を自動的に処理していただいているとは思いますし、その機能がなければボタン位置がバラついて「感覚的に気持ちの悪い状態」になりやすくなるかもしれません。

しかし、タグを入れずにそのまま意図したとおりに空行を入れられる（表示できる）方が作者側としても楽かなと思いますし、「あれ？　どうして空白が消えちゃうの？」という混乱が起きないのも良いかなぁと。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で空白の処理が仕様通りである事を確認しました。

末尾の空白を消す処理についてですが、意図せず空白が残ってしまっても人手で消せばよいと思うので、処理しないに一票ですね。

**Comment by snext1220** [comment]
末尾の空白について、空白除去処理はなしとのご意見が大勢でしたので、処理を破棄いたしました（GitHub Only）。
ご確認戴けますと幸いです～

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 85.0.4183.83(64bit)にて動作確認。
末尾に空白を追加した場合、空白が残っていることを確認しました。

ただ、すみません。いくつか分からないことがあり、お聞きしたいことがあります；

1. 空白ではなく**2行以上の空行**については、今までと同じく反映されないのでしょうか？
2. 空白除去の処理破棄後に今までのscenario.xmlをPg Flowで読み込んだところ、一行目が空行になっていました。
scene id等の属性の続きから文章を書いていない場合（二行目から文章を書いた場合）は、一行目が空白になってしまうのでしょうか？

＃もしかして１の仕様は2の処理に影響しているのでしょうか…？

**Comment by snext1220** [comment]
ご質問の件、取り急ぎ。

1. については、各行にタブなどを加えて戴くと複数行の空白を認識してくれるかと思います（改行のみだと、たぶん束ねられてしまいます）。

2. については仰る通りかと思います。空白（空行）処理がなくなったため、そのまま改行が出力される形となります。

**Comment by toki-sor1** [comment]
お忙しいところ、早速のお返事ありがとうございます！
1と2の仕様＆解決方法について承知しました！
2行以上の改行はタグを使用し、文章の冒頭はテキストエディタ等での編集時もPg Flowの仕様に合わせて一行目から書き始めるようにしますね。

**Comment by snext1220** [comment]
ご確認ありがとうございます～

文章の冒頭＞PgFlowネイティブで進めている場合はほぼ問題にはならないかと思いますが、環境混在の場合はそのようにお願いいたします…！

＃ 今回、空白については一旦修正しておりますが、システム的にはそちこちで空白処理を行っております（属性はほとんどのものを処理しています）。機能外したことで問題に感じる面も出てくるかと思いますが、改めて復活させることは可能なので、必要に応じてお声がけください。
