### ISSUE TITLE
【PgFlow】［リンク追加］ボタンでの挙動

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#218]
https://github.com/snext1220/snext-management/issues/18#issuecomment-667667558 由来のIssueです。

> ・リンク追加を押して新しいシーン番号を指定しても、分岐が生成されない？

［リンク追加］は既存シーンへのリンクだけの追加なので、そのようになりますね。。シーン作成を伴うリンク追加は［シーン追加］でお願いできますと。

ただ、この辺は挙動として判り難いのかなと思いますので、以下いずれかの対応を考えています。

+ ［リンク追加］では存在しないシーンを指定した場合、エラーを表示する
+ ［リンク追加］で新規シーンの追加も可能にする

［リンク追加］は結構情報も多いダイアログになっているので、更に新規シーンのサマリなどまで入れさせるよりも、シンプルにエラーを出す方が良いかな（1. の方が良いかな）と思っておりますが、如何でしょうか（ある程度皆様のご意見を戴いたところで対応進めてまいります）。

※ときのじさんからは以下のご意見を戴いております。

>仕様のご解説ありがとうございます！
なるほど、「編集するシーン」の一覧に新しいシーンが追加されていなかった理由は、そういうことなのですね～。
（勘違いで見当違いのことを書いていないか不安だったので、安心しました…ｗ）
対応については、1. ［リンク追加］では存在しないシーンを指定した場合、エラーを表示するが良いなと思っています。
理由は、既存のシーン番号を指定しようとした時に、誤って新しいシーン番号を入れてしまう可能性があるかも、と思ったからです～（意図しない新規シーン追加＆リンクミス）。

**Comment by cocotori** [comment]
わたしは、存在しないシーンの場合は、エラーを出すのがいいかと思います。

**Comment by Salvadors-cabin** [comment]
私もエラー表示に一票です。

**Comment by snext1220** [comment]
ご意見ありがとうございます。
こちら、「［リンク追加］では存在しないシーンを指定した場合、エラーを表示する」のご意見が強かったので、GitHub Pages Onlyで修正反映しております。ご確認戴けますと幸いですm(_ _)m

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 85.0.4183.83(64bit)にて動作確認。
存在しないシーンid指定時にエラーが表示されることを確認しました。
