### ISSUE TITLE
【PgFlow】パラグラフシャッフルの改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#219]
https://github.com/snext1220/stext/issues/213#issuecomment-669890932 由来のIssueです。

> ただ、パラグラフシャッフルにはまた別の論点があります。スレ違いで恐縮ですが……> 毎度のことながら自分本位な意見ばっかりで申し訳ありません。。

いえいえ、STextチームだけでは中々出てこない、Kindle出版を経験されているちゃなさんならではのご意見は大変参考になっております。本当に、何度でも、心から有難うございます！

>・現状だと、HTML出力の時にパラグラフシャッフルするようになっているかと思いますが、パラグラフジャンプその他のパラグラフ番号に関するギミックを伴う作品の場合、「シャッフルするか固定したままかをパラグラフごとに指定する機能」は必須になります。

はい、現在はid=0のシーンだけがシャッフル固定されていますが、実は他のシーンもシャッフル除外（固定）できたりします^^;（正確には、既に機能そのものは実装していますが、固定フラグを立てるUIがないので使えてないだけ）。こちらは必須とのことで今後対応していければと思います。

> ・また、随時パラグラフシャッフルによりシーン番号を整頓できると、現在の総シーン数が都度明確になるので便利です。しかしこの機能もソーサリアンTEXTにはあまりなじまないかも。。

こちらも実は機能としては存在します^^; 暫定版なので一旦削除してしまったのですが、現在GitHub Pagesのみ復活させています（詳しくは #204 を参照ください）。あくまで暫定実装なので、操作感についてはご意見頂ければ本格復活＆調整してまいります～

> ・後これは思考実験レベルのマニアックな話なのですが……パラグラフシャッフルした結果として、「40→41」とか「23→35or36」みたいな分岐ができないようなアルゴリズムを組むことって、可能なんでしょうか？？経験上、100パラだとほぼ確実にこういう「美しくないジャンプ」が生成します。後から手直しするんですけど。。
・これ以外にも、後から手直しすることが非常に多いので、パラグラフシャッフルはHTML出力のタイミング以外に随時可能な方が有り難いです。。

アルゴリズム、については複雑にはなりますが、ルールさえ明確になれば可能だと思います。ただ、拝見するにパラグラフの調整はその時々で細かく判断されているように思えるので、以下の対策をとった方が汎用的なのかなと感じました。如何でしょうか。

+ .jsonファイルを任意のタイミングでシャッフル可能に（上記の対策）
+ 任意のidを入替できる機能（たとえば1と10を入れ替える。スワップ機能）

**Comment by snext1220** [comment]
まずはシャッフル機能での固定idを実装しました。
［シーン］タブからシャッフル除外を選択することで、idが固定されます。

その他は、ご意見お待ちした上で対応進めていければと思います。
引き続きよろしくお願いいたします。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 85.0.4183.83(64bit)にて動作確認。
「シャッフル除外」にチェックを入れたSceneのidが固定されていることを確認しました。
チェックを入れていないSceneのidはシャッフルされていました。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でチェックしたシーンがシャッフルから除外されている事を確認しましたー

**Comment by olreia** [comment]
ご検討ありがとうございます。
idスワップ機能は従来型の（1から順にパラグラフ番号をつける）ゲームブックを作るうえでは大変心強いです！現状は、スワップしやすい（分岐の少ない）パラグラフに目をつけて、文章とリンクを一つずつコピペして、と手動で行っており、手間と間違いのリスクが大きいので。。

**Comment by snext1220** [comment]
ご意見ありがとうございます。また、承知いたしました～
スタッフの皆さんからも反対意見ありませんでしたので、本件対応を進めていければと思います。

@toki-sor1 さん＞
毎度お手数をおかけして恐縮ですが、スワップ機能のメニューアイコンをお願いできますでしょうか（機能開発に時間がかかると思うので、急ぎではございません～）。

+ シャッフル／スワップはサブメニューで選択させる予定なので、アイコンは一点、通常のデザインで良いかと思います。
+ 2個のシーンを入れ替えるようなイメージ（以下の人をシーンを表すような四角で置き換えたようなイメージ？ https://pixta.jp/illustration/2524272 ）
     + イメージなので、この方が良いなどあれば、勿論良いようにしてやってくださいませ^^;

**Comment by snext1220** [comment]
以下件について対応完了しております（GitHub Pages Only）。

> .jsonファイルを任意のタイミングでシャッフル可能に（上記の対策）

現在は［Shuffle］ボタンからシャッフル可能です（今後、アイコンに差し替え予定）。
シャッフル結果はそのまま現在のフローチャートにも反映されます。

> 任意のidを入替できる機能（たとえば1と10を入れ替える。スワップ機能）

［シーン］タブからidを［変更］します。
これまでは変更ダイアログで既存のidを入力した場合はエラーとなっていましたが、今後はスワップされます。

**Comment by toki-sor1** [comment]
> 毎度お手数をおかけして恐縮ですが、スワップ機能のメニューアイコンをお願いできますでしょうか（機能開発に時間がかかると思うので、急ぎではございません～）。

お待たせしてしまい申し訳ありません…！
**pg_shuffle.png**というファイル名でGitHubのcommon内にアップ済みです。
問題がないようでしたら、反映よろしくお願いいたします。
![pg_shuffle](https://user-images.githubusercontent.com/42646342/93481766-e2b22800-f939-11ea-9013-ac52bf73e4f4.png)

**Comment by snext1220** [comment]
こちらこそお忙しい処、ありがとうございます！
機能も対応済みなので、アイコン共々、本番環境にリリースさせていただきました～
ご確認いただけますと幸いですm(_ _)m

**Comment by snext1220** [comment]
あ、こちら任意タイミングでのシャッフル機能／スワップ機能を有効にしたことで、HTML保存時の自動シャッフルは無効化する予定ですが、問題ありませんでしょうか。
＃ たぶん、保存前にidを調整しているはずなので、自動シャッフルは却って邪魔なはず

**Comment by toki-sor1** [comment]
アイコンの反映ありがとうございます！　イメージ通りで安心しました！
本番環境から確認し、アイコンの表示とシャッフル機能ともに問題なしでした！

> あ、こちら任意タイミングでのシャッフル機能／スワップ機能を有効にしたことで、HTML保存時の自動シャッフルは無効化する予定ですが、問題ありませんでしょうか。

私の方は、無効化の方向で問題ありませんですー。

**Comment by cocotori** [comment]
chromeで確認しました。

シャッフル機能、スワップ機能、シャッフル除外、問題なく動作しています。

html保存時の自動シャッフルは無効で問題ありません。

スワップは、新規のidを振る時とスワップする時とで挙動が同じなので、
新規のつもりで気づかずスワップしてしまうことがあるかなと思いました。
相手先idがある時は、個人的には警告が出るといいと思いましたが、
煩わしいと思われる方もいるかもしれません。

皆様の反応を伺いつつ、決定してもらえたらと思います。

**Comment by snext1220** [comment]
ご確認／ご意見ありがとうございます！

スワップの警告＞については、はい、わずらわしさが気になっておりました^^;
修正そのものはできますが、実際にシナリオ作成戴いた感触でご判断いただいた方が良いかもしれません（それで別段気にならないようであれば、できるだけ警告は少なくした方が良いというスタンスです）。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で、シャッフル、シャッフル除外、変更が動作することを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 85.0.4183.121(64bit)にて動作確認。
**シャッフル機能、スワップ機能、シャッフル除外、正常に動作しています。**

スワップ機能ですが、時々間違えてSceneを指定してしまうことがあるものの、リンク自体は修正の必要がないので、あまり気になりませんでした。

ただ、リンク名にScene idを入れるタイプのGBでは、トラブルになりそうな気も…。
（例えば、○○をする場合は…Scene100へ といった書き方）

**Comment by snext1220** [comment]
> ただ、リンク名にScene idを入れるタイプのGBでは、トラブルになりそうな気も…。

仰る通り、特にシャッフル機能については、この辺きちんと管理しないと辛そうですよね^^;（固定id機能はありますし、SText本体では利用しないはずなので、まずは母集団は少なそうですが、忘れたころに...）

SText的には、リンクキャプションにシーン番号を入れない、がまずはお勧めですかねぇ...（勿論、シーン本文もそうですし、保守性という意味では他にも気にすべき点は諸々あると思いますが^^;）

cocoさんより戴いていた警告については、現時点では大きく気になるという意見はなかったので、一旦様子見したいと思います。勿論、今後問題出てくる場合には、修正そのものは可能なので、お声がけください＞皆さま
