### ISSUE TITLE
URLにアンダースコアが含まれているとリンクされない

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#220]
https://github.com/snext1220/stext/issues/76#issuecomment-674465467 でご指摘いただいた件です。

---

> すみません、「おたよりをよみたい」の【参照】にまとめた各ページのURLについて報告です。どうも「アンダーバー」付きのURLは、GitHub、XAMPP環境だと下記のような警告が出てしまいました；

ご指摘ありがとうございます！
こちらは以前からの問題ですね...ドラモードでも画像ファイル名で問題が出ていましたが（wiki）、アンダースコアはmarkdownの予約文字のため、内部的に`<em>`のようなタグに変換された結果、生じております。。
ただ、画像ファイルと違って、リンクは回避できないため、なにかしら対応しないとですね…少々特殊な処理が必要になりそうなので、暫しお待ちくださいませ；

---

本件、GitHub Onlyで対応しておりますので、ご確認戴けますと幸いですm(_ _)m

**Comment by toki-sor1** [comment]
早速の実装ありがとうございます！！
Win 8.1／Chrome 84.0.4147.125(64bit)にて動作確認を行いました。
**「共通インポートの無効化」にチェックを入れたシーンでは、正常に共通インポートが無効化されていました！**
これは設定も楽ですし、便利ですね！

ただ、一点だけ気になったことがあります。
例えば、**Scene 0の「共通インポートの無効化」にチェックをした後、Scene 1のシーンタブを開くと、そのままチェックが入っている状態**になっていました。

その場合、Scene 1のシーンタブのチェックを外すと無効化を解除できます。
しかし、**その状態のままScene 0のシーンタブを開くと「Scene 0のシーンタブのチェックが外れた状態になりつつも、テストプレイでは無効化されている状態」** になっているのです；

これだと、**シーンタブを開いた時にどのSceneにチェックを入れて、どのSceneでチェックを入れてないのか編集中に混乱してしまうのでは**と思いました。

**Comment by cocotori** [comment]
アンダーバーのついたurlでも、無事表示されることを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 85.0.4183.83(64bit)にて動作確認。
アンダーバー付きURLでも正常に該当ページへ移動できることを確認しました。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でアンダーバー付きURLが表示されることを確認しましたー
