### ISSUE TITLE
パネルから追加したシーンが見付けづらい

### ISSUE THREAD

**Issue by toki-sor1** [snext1220/stext#221]
パネルからシーンを1つ追加した時、共通インポート用のScene 99998があるためか、どのシーンを選択した状態でもScene 99999、100000、100001と追加されてしまいました。

また、追加されたシーンは1つまでならフロチャ上の目立つところに表示されるのですが、追加されたシーンが2つ以上の場合は、2つ目のシーン以降がどこに表示されているのか見つけられませんでした。

上記の症状で、以下の点が気になりました。

- 本来追加したいidのシーンが追加できない
- 追加されたシーンがフロチャ上で行方不明になってしまう（でも実際には追加されている）
  - 既存のシーンとリンクさせると見えるようになります

**Comment by snext1220** [comment]
コンパネ（ツールバー）の「＋x」機能については、仰る通り、最大id＋1で採番しているので、現時点ではご指摘の挙動が正しいですね...

この辺はルール決めの問題で修正は可能です～
たとえば

+ 90000番台のシーンは予約番号と決め、「90000未満の最大id＋1」
+ 設定画面で基点となるシーンも指定できるようにする など

ただし、シナの中でも特殊シーンを別採番している場合にはやはりそちらがネックになりますし、設定画面を開くのも却って面倒と考えると、「本来追加したいid」を決めるのが困難なのかなという気は。個人的には、本機能はシナ最初の立ち上げで沢山のシーンをまとめて作成したいなどで利用するにとどめるのが無難ではないかと感じています（それ以外は［シーン］タブから）。

> フロチャで行方不明

こちらも上記同様で、［シーン］タブからの追加がお勧めでしょうか。
ハック的には、特殊シーンに対しては、シーン0に対して未使用フラグ付きで連結する、はできるかと思います^^;（未使用フラグなのでゲーム画面からは見えないが、PgFlow上は0から連結しているので行方不明にならない）。

あくまで例ですが、いずれもなにかしらルールを決められれば修正も可能なので、もしご要望あればお願いします～

**Comment by toki-sor1** [comment]
お返事ありがとうございます！

> コンパネ（ツールバー）の「＋x」機能については、仰る通り、最大id＋1で採番しているので、現時点ではご指摘の挙動が正しいですね...

こちらは仕様だったのですね、承知しました！

> 個人的には、本機能はシナ最初の立ち上げで沢山のシーンをまとめて作成したいなどで利用するにとどめるのが無難ではないかと感じています（それ以外は［シーン］タブから）。

修正案もありがとうございます～！
しかし、どちらの修正は可能であるものの、実装したとしても難ありという感じなのですね；

そうなると、リオさんが仰っているようにコンパネ（ツールバー）の「＋x」機能はシナ最初の立ち上げで沢山のシーンをまとめて作成する際に利用し、それ以外は［シーン］タブから追加を行うなど、**それぞれの用途で使い分けるのが良さそうですね。**

> ハック的には、特殊シーンに対しては、シーン0に対して未使用フラグ付きで連結する、はできるかと思います^^;（未使用フラグなのでゲーム画面からは見えないが、PgFlow上は0から連結しているので行方不明にならない）。

なるほど、そういう方法でリンクの行方不明を防ぐこともできるのですね。
しかし、リオさんが仰る通り［シーン］タブを使用すれば初めからリンクとセットであり、そもそもシーンが行方不明にならないので、修正よりもこちらを利用した方が良いですね。

お忙しいところ疑問にお答えいただき、どうもありがとうございました！
お騒がせしてお手数をかけてしまい、申し訳ありませんでした；
こちらの2つの問題は、**［シーン］タブから追加を行う**ということで解決しましたので、後ほどCloseしたいと思います…！

**Comment by snext1220** [comment]
ご確認ありがとうございました！
まずは、［シーン］タブからの追加で解決したとのことよかったです～

> しかし、どちらの修正は可能であるものの、実装したとしても難ありという感じなのですね；

一応、「90000番台のシーンは予約番号と決め、「90000未満の最大id＋1」」については、ルールを理解してscene idを振っていくのが問題なければアリではあるのかな～とは^^; 
 ［シーンを追加］ボタンは元々若干使いどころが悩ましいが残した、という機能でもあるので、是非、 皆さんのご要望も伺いながら、改良していければと思っています。

**Comment by cocotori** [comment]
シーンを追加ボタンの扱いはなかなか悩ましいですね・・・

個人的には、シーンタブのシーン追加ボタンがあれば
十分だと感じていますが、
弱点としてはいちいち開いてるidを調べて、
手動入力しないと行けないところだと思っています。
その弱点を補う意味で、自動採番の「シーンを追加」ボタンがあると解釈しています。

そういう中で、リオさんの、
・90000番台のシーンは予約番号と決め、「90000未満の最大id＋1」
という採番ルールがいいと思います。

これをゆくゆくはシーンタブのシーン追加ボタンの方にも適用できれば、
わざわざ手動でシーン番号を入力する必要もなくなるのでは、と感じています。

わたしはあまり馴染みがなかったのですが、
ゲームブックでは最後にシーン番号をシャッフルする
（番号からプレイヤーに展開を予想されないようにするため？）
のが一般的なんですね？

となると、自動管理さえできるのなら
シーン番号にもほとんど意味はなくなるのかなと思っています。

ただ、今ってシーン番号がフロー図に影響を与えていましたっけ？
（番号が若いほど上の方に来る、等）
それがなければ自動管理で問題ないと思いますが、
もし影響があるなら、それはそれで悩ましいですね・・・

**Comment by snext1220** [comment]
> 弱点としてはいちいち開いてるidを調べて、
> 手動入力しないと行けないところだと思っています。

そうですよね；
この辺もルールを決められれば、自動的な採番は問題ありません。
たとえば、［シーン］タブからのシーン追加であれば、「現在のシーン＋決めた増分」（存在すれば更に増分プラス）など。

ただ、その時々で増分を決めている場合には却って自動採番が使いにくい or/and シーン一覧から番号は見られるのでそこまでは不要、など、ご意見が諸々ありそうで、少々悩ましく。ルールご提案戴きつつ、賛否投票していく感じでしょうか。

ということで、

【募集】［シーン］タブからのシーン追加において、自動採番の要否 ＆ 要の場合は採番ルール

でございます。

> そういう中で、リオさんの、
> ・90000番台のシーンは予約番号と決め、「90000未満の最大id＋1」
> という採番ルールがいいと思います。

はい、ツールバーでのシーン追加では、私もこれにて賛成ですかね～
皆さまの賛成があるようであれば、実装していければと思います！
＃ ただ、［シーン］タブからは自動採番するにせよ、別ルールの方が無難かも？

> ゲームブックでは最後にシーン番号をシャッフルする（番号からプレイヤーに展開を予想されないようにするため？）のが一般的なんですね？

はい、あくまで書籍の場合の手順ではありますが（ページを間違えて繰ってしまった時に、次の展開を見られないようにするため）。SText（PgFlow）ではグループ機能が事実上使えなくなるので、非推奨です～

> ただ、今ってシーン番号がフロー図に影響を与えていましたっけ？

いえ、シーン0からのリンク距離なので、影響はありません。
ただ、ゲームブックというと、パラ番号を付与するという伝統があるため（近頃そうでないものもありますが^^;、番号そのものに意味を持たせている場合もあり）、STextとしては残しておりました。
＃ 内部的にも、グループ化キー、指定番号ジャンプなどもあり。

**Comment by cocotori** [comment]
>【募集】［シーン］タブからのシーン追加において、自動採番の要否 ＆ 要の場合は採番ルール

自動採番が可能ならおそらくわたしは自動採番しか使わなくなるので、
・要否　→　要
・ルール　→　上記の、90000未満の最大id＋1

で構いません！

手動で番号を振りたい方との共存を図るため、
自動 or 手動がチェックボックス等で切り替えられるとありがたいでしょうか。

**Comment by snext1220** [comment]
ご意見ありがとうございます！

> ・ルール　→　上記の、90000未満の最大id＋1

こちら、先ご提案した「現在のシーン＋増分値」では難しいでしょうか。
たとえば10、100、1000、10000というシーンがあって、現在のシーンが10の場合、次のidは

+ 90000未満の最大id＋増分値（+1）：10001
+ 現在のシーン＋増分値（+1）：11

となります。恐らく後者の方が汎用性が高いと思われるためです。
＃ cocoさんの用途は常に小さい順にしかシーンを作成しない場合を想定していると思われるため。後者のルールもcocoさんの用途はほぼ満たすかと。

> 自動 or 手動がチェックボックス等で切り替えられるとありがたいでしょうか。

こちらは、いずれにせよダイアログを一度噛ますので、手動で入れたい方は既定で採番されたidを修正戴く堅いになるかと思います～

**Comment by cocotori** [comment]
>現在のシーン＋増分値（+1）：11

こちらの方法で問題ありませんです！
開いてる番号を自動で採番してもらえるなら、
こちらとしては特に困ることはないと思います。

**Comment by toki-sor1** [comment]
> 【募集】［シーン］タブからのシーン追加において、自動採番の要否 ＆ 要の場合は採番ルール

**自動採番： 要**ですね。
採番ルールについては、**現在のシーン＋増分値（+1）：11**が良いですね。

Scene追加のテンポが気になってコンパネ（ツールバー）の「＋x」機能について意見を書いた経緯があるので、上記の仕様であれば、追加したSceneが行方不明になることもなく、Scene追加のテンポも改善されて良いなぁと思いました。
［シーン］タブからのシーン追加で自動採番が実装された後は、コンパネ（ツールバー）の「＋x」機能が役目を終えそうな感じがしますね。

**Comment by snext1220** [comment]
@cocotori さん、 @toki-sor1 さん：

ご意見ありがとうございます。
取り急ぎですが、自動採番ルールは意見も一致したようなので、［シーン追加］ダイアログで実装してみました。また、ツールバーの［シーン追加］についても一旦90000以上のシーンを除外して、最大値を求めるように改めています。本番環境にも反映しておりますので、お手数ですが、ご確認戴けますと幸いです。

> ［シーン］タブからのシーン追加で自動採番が実装された後は、コンパネ（ツールバー）の「＋x」機能が役目を終えそうな感じがしますね。

ですね...本当になにも考えずにシーンだけを大量に追加したい、というニーズはあまり考えにくい気もしますし^^; こちらはdec updateまで待ってご異論なければ削除していければと思います。
＃ 今ある機能なので、「消さなくても良いのではないか」という意見も含めてあれば、残します～

**Comment by toki-sor1** [comment]
実装お疲れ様です！

> 取り急ぎですが、自動採番ルールは意見も一致したようなので、［シーン追加］ダイアログで実装してみました。

こちら、正常に動作しております～。
シーン追加のテンポが非常に良くなり、選択しているid+1のシーンが追加されるのも良いですね！

> また、ツールバーの［シーン追加］についても一旦90000以上のシーンを除外して、最大値を求めるように改めています。本番環境にも反映しておりますので、お手数ですが、ご確認戴けますと幸いです。

こちらも正常に動作しており、最大値+1のシーンが追加されていました！

ただ、そうですね、前回もちらりと書きましたが、自動採番ルール適用後の［シーン追加］の方が便利なので、**コンパネ（ツールバー）の「＋x」機能の削除について異論なし**でございます～。

> 追記：削除の件は #223 に移動したので、自動採番の件が問題なければ、このままCloseしてまいります

承知しました！
課題追加でこちらをCloseしても良いものか迷っていたので、お任せしてしまい恐縮ですがよろしくお願いします。

**Comment by snext1220** [comment]
ご確認ありがとうございます！
こちら問題ないようで、まずはほっとしました^^;
因みに、いずれの機能でも増分値は設定ダイアログで変更できますので、ご利用ください～

機能削除についてもご意見ありがとうございます！
こちらは #223 に引き継がせていただくとして、では、こちらはCloseしてまいりますね。
