### ISSUE TITLE
文字フォント／アニメーションの付与

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#222]
機能がある程度固まってきたところで、見た目の改善を図っていければと考えています。

具体的には、以下のものを検討中です。
いずれも使い過ぎは可読性を損ないますが、ポイントを絞ることでテキストをより効果的に表現できるのでは。

### 文字アニメーションの付与

シーン単位に、以下のようなアニメーション付与を可能にする
http://textillate.js.org/

`<scene effect="rollin;50">`

【課題】シーン内の特定段落にのみ適用したいケースがある？（使い方は難しそうだけど）

### webフォントの利用

シナリオ単位に、指定の日本語フォントを適用する
https://ferret-plus.com/2066
利用可能なものはあらかじめ選定しておく予定。

【課題】実はシーン単位、または段落単位に適用したい？（自由度を増すとダウンロードサイズが激増するので、どの程度まで許容するかはニーズに応じて相談）

ジャストアイデアですが、まずは**ニーズの有無を確認**できればと思います。

**Comment by cocotori** [comment]
>文字アニメーションの付与

やるのであれば、段落ごとに有効無効を切り替えられる、に一票でしょうか。
シーンごとだとだいぶ用途が限られてしまうように思います。
　
　
>webフォントの利用

こちらも、あくまで可能ならばですが
文字ごとに切り替えられるようにしたい要求があるのではないかと思います。
その際のフォント数の上限は、シナリオごとに3個とか4個に
限定してしまうのはありだと思います。
　
　
個人的な要望としては、
文字アニメーションはそれほど必要性を感じないが、
フォントは切り替えられるとありがたい、という感じでしょうか。

**Comment by snext1220** [comment]
ご意見ありがとうございます。

文字アニメーション＞目は引きますが、使い方は難しそうですよね。
＃ 個人的には、シーンの途中でアニメーションを挟むと気付きにくいことから、むしろシーン単位にしたほうが変な使い方がないのかな、と思っておりました^^;（前シーンで「天井を見上げると、血染めの文字が見えた」->次シーン全体でオドロオドロしい文字が浮かび上がる、ような演出）

なお、こちらでも調査していますが、今のところ、webフォントがパフォーマンス的に影響著しそう、という感触でした（有料サービスを使うと部分ダウンロードなども可能ですが、1種類でも数mbなのでやはりサイズの問題がネックですね...）。引き続き調査を進めてまいります。

**Comment by toki-sor1** [comment]
> 文字アニメーションの付与

こちらはデジタルGBの強みを活かした演出ですね。
頻繁に使うものではなさそうですが、ここぞという場面で使うと物語の雰囲気がぐっと増しそうです。
**導入に賛成です。**

> webフォントの利用

フォントは紙媒体GBでは容易に変更できますが、デジタルでは変更が難しいですよね。
紙媒体だとフォントはデザイン的な意味合いも強いので色々使えたら良いんと思うのですが、デジタルだとデザイン性よりも可読性を重視しているような印象があります。
そのため、個人的には**デジタルGBにおいては、Webフォントにそこまで必要性は感じてなかったりします；**

また、パフォーマンスにも影響しそうなので、私は**Webフォントは利用しなくてもよい**かなと思っています。

**Comment by Salvadors-cabin** [comment]
>文字アニメーションの付与

正直なところ、使い道が思い当たりません。
オープニングタイトルぐらいかな、という感じです。

>webフォントの利用

こちらはあれば使えるかも、という感じです。
例えば特定アイテムや強調したいところに使えるかもしれません。
（となると、文字単位になってしまいますが）

**Comment by snext1220** [comment]
ご意見ありがとうございます。

戴いたご意見の感じ、

+ 文字アニメーション：賛成1、消極的2
+ 文字フォント：消極的3

といったところでしょうか。
＃消極的は、「反対ではないorあっても良いが、絶対欲しいというほどではない」とのレベルです。

元々まずは感触を、ということでもあったので、優先順位は限りなく落としながら、どこかで実装する（かも）くらいで進めてまいりますね。

+ アニメーションは直近で利用するようであれば、勿論、優先順位上げますのでお声がけください＞賛成票戴いている @toki-sor1 さん
+ webフォントはパフォーマンス面での評価が先なので、ゆるゆる調査を進めてまいります。

**Comment by snext1220** [comment]
アニメーション機能のみをGitHub Onlyで実装しました。ご確認戴けますと幸いです。
詳細仕様は、マニュアルより${effect}の項を参照ください。

＃ Webフォントについては先の議論で消極的であったことから＆パフォーマンス上の問題も現時点で対策見込めないことから、wontfixとしてまいりたいと思います。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeでアニメーション機能を確認しました。面白いですね。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
ありがとうございます！　がっつり活用させていただいてます！
おろろろ～んできてます！

ただ、指定する時に総当たりで試していてちょっと苦労したので、どんなアニメーションなのかが分かり易いアニメーション効果の一覧（文字だけの説明だけでも）があると良いかもです。

**Comment by snext1220** [comment]
@toki-sor1 さん：
ご確認＆早速のおろろーんありがとうございます！ｗ

一覧＞こちらライブラリの公式サイトにPlayground（https://textillate.js.org/ ）がありましたので、ヘルプからもこちらへのリンクを追加させて戴きました（文章よりも恐らく実際に動かした方が判りやすそうなので）。英語ページではありますが、如何でしょうか？

**Comment by toki-sor1** [comment]
おお、以前もご紹介いただいたサイトがありましたね！（すみません、失念しておりました；）
実際にアニメーションが見られるので、リンクから確認出来てとても良いと思います！

ひとつ気になったことなのですが、バナー＝悪質なサイト誘導みたいな先入観念があり、サイトTOPの赤いDownload on GitHubというバナーにちょっとドキッとしてしまいました；
『詳細な挙動は https://textillate.js.org/ ページ下部のIn Animation一覧から指定してご確認ください』のように、もう少し分かり易く書かれていると良いかもと思いました～。
が、こちらはお任せします！

**Comment by snext1220** [comment]
成程、黒背景に赤ということで余計妖しさ感満載なのかもしれませんねｗ
こちらご指摘の文言を若干変更して反映させて戴きました～

**Comment by toki-sor1** [comment]
お忙しいところ、ご対応いただきありがとうございました！
そうですｗ　妖しさ感が気になってしまい……ｗ
という訳で、変更後の文言ばっちりです～！
