### ISSUE TITLE
【PgFlow】機能削除について

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#223]
PgFlowの機能向上に伴い、いくつか不要と思われる機能も発生してきております。
以下機能についてご異論なければ、近日中に削除していければと思いますが、如何でしょうか。

#### フロチャ上のシーン／リンク編集機能

以下Issue由来です。
https://github.com/snext1220/stext/issues/216#issuecomment-698796988

>>逆に、Delete Selectedでシーンを消してもシーン一覧のリストに残っていたりします。
> こちらも恐らく今回の修正で改善されたかと思いますが、如何でしょうか。
> ただ、（別件ですが）［シーン］タブのシーン削除も追加されたので、フロチャからのシーン操作はもはや削除しても良いかもしれませんね。。（微妙にコードを共通化できずにいるので、テスト工数がシャレにならなくなってきている感じです；）

対象はシーン／リンクの追加／削除、リンクの付け替えなどに及びます。
すべてはタブ側の機能で賄えるので、現在は利用されている方がほとんどいないのかなと考えています。

#### ツールバーからの［シーン追加］機能

以下Issue由来です。
https://github.com/snext1220/stext/issues/221#issuecomment-703207679
こちらは以前にもうかがった件で、一度は消極的賛成で残してあったものですが、自動採番機能が付与されたことで、改めて伺う次第です。

>>［シーン］タブからのシーン追加で自動採番が実装された後は、コンパネ（ツールバー）の「＋x」機能が役目を終えそうな感じがしますね。
> ですね...本当になにも考えずにシーンだけを大量に追加したい、というニーズはあまり考えにくい気もしますし^^; こちらはdec updateまで待ってご異論なければ削除していければと思います。
> ＃ 今ある機能なので、「消さなくても良いのではないか」という意見も含めてあれば残すことを優先します～

#### ［シーン追加］［リンク追加］のボタン位置

削除ではありませんが、細かい修正なので、ここでまとめて。
［シーン］タブの［シーン追加］ボタンをタブ末尾の［現在のシーンを削除］ボタンと並べて移動しようかと考えています。如何でしょうか？

シーン操作系のボタンは一か所にまとめたい＆レイアウト次第では折り返しが発生するのが気になっていた、のが理由です。

**追記：本Issueで提案している機能ですが、本番環境含めて、一旦削除いたしました（すぐに戻せる状態にはなっています）。削除した状態の方がイメージ沸きやすいであろうというのが趣旨です。**

**Comment by toki-sor1** [comment]
> フロチャ上のシーン／リンク編集機能

私は削除しても問題ないです～。
同じ機能が別々の場所にあるのは、混乱の元でもありますので。

> ツールバーからの［シーン追加］機能

こちらも削除しても問題ないです。
自動採番機能によって、シーンも簡単に追加できるようになりましたし。

> ［シーン追加］［リンク追加］のボタン位置

最初はちょっと戸惑いましたが、慣れれば問題なさそうです。
［現在のシーンを削除］では、警告ダイアログのワンクッションもあるので、誤操作も防げるかなと。

**Comment by cocotori** [comment]
>フロチャ上のシーン／リンク編集機能
>ツールバーからの［シーン追加］機能
>シーン追加］［リンク追加］のボタン位置

どの項目も、変更後の仕様で問題ありません！

**Comment by snext1220** [comment]
本件、皆さまの同意を得られましたので、これにてCloseとしてまいります。
機能が増えてきたところで、今後もこのような形で機能削除を提案していければと思っております（背後のコードは当面残しておく予定。管理が難しいですが...）。皆さまからも「これは削除しても」というものがあれば、何なりとお声がけください。

一方、細かなボタンなどのレイアウト変更は、作業の関係上、予告なく行う可能性がありますが、ご了承ください（もちろん、反対意見などある場合は、頂ければ元に戻すなどしてまいります）。
