### ISSUE TITLE
【PgFlow】EPUB対応

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#224]
Kindle等電子書籍対応のため、PgFlowからでんでんコンバーター（https://conv.denshochan.com/ ）形式のテキストをエクスポートできるようにします。まだβ版ですが、GitHub Onlyでリリースしておりますので、お試しください。

以下は、縦書き出力用のスタイルシートです。
[style.zip](https://github.com/snext1220/stext/files/5323359/style.zip)

以下は、PgFlow経由で生成した電子書籍をでんでんでEPUB変換した結果です。

![無題](https://user-images.githubusercontent.com/27911337/95018005-b1ef2400-0697-11eb-9f88-5fe5a29b9f2c.png)

**Comment by Salvadors-cabin** [comment]
Win10+Edgeでβ版を使用してみました。
EPUB形式で出力され、ツールで文章表示できました。
![epubReader](https://user-images.githubusercontent.com/42834363/98121374-8e1b3a00-1ef2-11eb-9048-4469e4e98274.png)
ただ、シーンの条件分岐ができませんね。

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！

> ただ、シーンの条件分岐ができませんね。

はい、EPUB/HTML形式はあくまで静的なドキュメントを生成する手段（＝リンカブルなテキストを作成するだけ）なので、ソーサリアン Textの動的な機能のほとんどは使えなくなってしまいます。KindleなどがJavaScriptの実行を有効にしてくれるとまた状況は変化するのでしょうが、こればかりは環境が整うのを待つしかありませんね...^^;

**Comment by Salvadors-cabin** [comment]
そうですね。ノベルゲーム的なシナリオなら、というところでしょうか

**Comment by snext1220** [comment]
あ、いえ。EPUB/HTML形式は、汎用的なゲームブック用途でもPgFlowを使って戴こうという目的でして^^; 分岐などはSTextの機能は使わず、普通のゲームブックと同様、［～を持っていたら14へ］のような表現になるのかと思います。

ニーズなどあれば、アイテム情報／フラグ情報などから動的に

**［扉を開く（「アイテム1」を持っている場合）］**

のようなリンクに展開することもできますが、条件式が複雑になった時には限界もありますし、SText向けの構成とKindle向けの構成はやはり違うだろうということで、現在はシンプルな実装に。

**Comment by toki-sor1** [comment]
iPhone 7／iOS版Digital Editionsで表示確認。

1. Pg Flowでscenario.txt変換
2. でんでんコンバーターでEPUB変換
3. Dropboxにepubファイルを入れる
4. DropboxからDigital Editionsにエクスポート

上記の流れでepubファイルが読み込めることと、縦書きになっていることを確認しました。

初めから電子書籍化を目的としてシナリオを作成するケースで力を発揮する機能ですね。
特殊なソフトがなくても、手軽に電子書籍用のファイルが作成できるというのは、多くの人の電子書籍化を後押しする素晴らしい機能だと思います。
Pgの万能化が止まりませんねｗ

**Comment by snext1220** [comment]
@toki-sor1 さん：
ご評価ありがとうございます！

> Pgの万能化が止まりませんねｗ

はい～基本機能はおおよそ揃ってきたので、あとは間口を広げ、使ってくれる方を増やしていければと…！
現時点では、逆にPgFlowのほとんどの機能がEPUBでは無効化されてしまうのが問題ではあるのですが…皆さんのご要望次第で、以下のようなオプション機能を設けても、などと考えています～（ニーズありますかね...？）

+ モンスター／アイテム一覧などの自動生成
+ モンスター／アイテム情報のシーンへの埋め込み機能

> シナリオ（現段階では読み物？）

https://github.com/snext1220/stext/issues/224#issuecomment-722388412 とも重なりますが、STextの機能は使えませんが、現状でもGBAT相当の機能は持っているので、一般的な紙／Kndleゲームブックを対象としております～ て、 @Salvadors-cabin さんからも同様のコメントがありましたが、「～～な機能がないと、紙／Kindleゲームブックの作成にも足りない！」などありますかね；；

**Comment by toki-sor1** [comment]
> モンスター／アイテム一覧などの自動生成

「モンスター／アイテム一覧」は、載っているとゲームブックのゲームシートみたいで良いですよね。
更に、アイテムを入手したかどうかをチェックができると良さそうです。

> モンスター／アイテム情報のシーンへの埋め込み機能

モンスターが出現した時やアイテムを入手した時など、予め設定しておいた情報が表示されて確認出来るといいですよね。

> #224 (comment) とも重なりますが、STextの機能は使えませんが、現状でもGBAT相当の機能は持っているので、一般的な紙／Kndleゲームブックを対象としております～ て、 @Salvadors-cabin さんからも同様のコメントがありましたが、「～～な機能がないと、紙／Kindleゲームブックの作成にも足りない！」などありますかね；；

あわわ、言葉足らずで申し訳ありません；
Digital Editionsでファイルを表示させている時のことなのですが、特殊な条件式を設定していないリンクをタップしたところ、エラーで次のページに飛べなかったもので…；
それで「リンク移動はできないのかな？」と思ってからの「現段階では読み物？」という発言でした；

そのため、特殊な条件式が設定されていないリンク移動が可能であれば、紙／Kindleゲームブックの作成ができると考えております～。

**Comment by snext1220** [comment]
スミマセン。
おそらくシャッフルされていない（＝1からの連番になっていない）のではないかと思われます。一旦シャッフルしてから.txt出力戴けますでしょうか。

以下、マニュアル「シーンidをシャッフル」で辛うじて書いてはいたのですが、目立たないですね...事前にダイアログ表示しても良いのですが、毎回出ると一寸五月蠅いかもしれず、一寸悩み中です...
https://sorcerian.hateblo.jp/entry/2019/05/03/211951
＃シャッフル後、番号調整したいというニーズがあったため、現在は自動シャッフルは避けています。

**Comment by toki-sor1** [comment]
> おそらくシャッフルされていない（＝1からの連番になっていない）のではないかと思われます。一旦シャッフルしてから.txt出力戴けますでしょうか。

おわーーーー！？　す、すみません…めちゃめちゃ見落としてました；；
シャッフル後にtxtファイルを出力し、前回と同じ手順でepubファイルを確認し、正常にリンク移動できることを確認しました！
ひえぇ…勘違い大変失礼いたしました；；

> 以下、マニュアル「シーンidをシャッフル」で辛うじて書いてはいたのですが、目立たないですね...事前にダイアログ表示しても良いのですが、毎回出ると一寸五月蠅いかもしれず、一寸悩み中です...

こちらのIssueを参考に作業をしていたため、マニュアル未確認でした…；；（申し訳ありません…）
今後もPg Flowでファイル保存する際に「お、でんでんコンバーター用のtxtファイルに変換できる！」とマニュアル確認前に変換してリンク移動トラブル発生のケースもあるかもですね～…。

そのため、**マニュアルだけでなくPg Flowの方でも、でんでんコンバーター用のtxtファイルを保存する際にダイアログ追加orシャッフルボタンのダイアログに追記が良いかも**と思いました；

**Comment by snext1220** [comment]
> おわーーーー！？　す、すみません…めちゃめちゃ見落としてました；；

いえいえ、ホントに「書いてました」というだけの言い訳的な対応だったので；；
ご意見もありがとうございました。
こちら若干五月蠅いかもですが、保存前に大きめなダイアログを追加しました。
＃何度も繰り返すものでもないので、ギリありかなと^^;

GitHub Onlyで反映済みです～

**Comment by toki-sor1** [comment]
お、お早い…！！
連続のご対応、本当にお疲れ様です＆ありがとうございます…！！
ダイアログを確認しましたが、大き目なダイアログに説明がとても丁寧に書かれていているので、どのような用途のファイルなのか＆シャッフルを実行したかどうかなど、重要な情報を見落とす心配もなくなってとても良いですね！

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！まずは問題なさそうでよかったです～

＃ ホントは［次からは表示しない］チェック的なものも入れようかと思ったのですが、とりあえずはサボっています^^; 今後、チュートリアル機能などを実装するようになったら、必要になるかもしれませんね～

**Comment by cocotori** [comment]
chromeで試してみました。
細かくは見れていませんが、変換できていることを確認できました。

どの機能が利用できて利用できないのか、
マニュアル等できちんとわかるようにしないといけませんね。
なかなか大変ですが・・・

こちらの機能ですが、
まだ目的や経緯を把握できておらず、申し訳ありません。
今まであった、html(For Brower)とは違うのでしょうか？
同じ縦書きフォーマットなので、どちらかだけでいいと思っていました。
（kindle向けの出力ができるのであれば、html形式はいらないかも？）

**Comment by snext1220** [comment]
マニュアル＞ そうですね。標準的なマークダウンはほぼそのまま使えるので、#234 などのIssueでEPUB統合が進むと、大雑把には「既存のSGML拡張／式が利用できなくなる」ということにはなるかと思います。マニュアルもこの辺の改定が落ち着いたところで、まとめていければと思っています～

> 今まであった、html(For Brower)とは違うのでしょうか？

個人的にはEPUB推しなのですが、意外とEPUBよりもHTML＋一太郎のようなツールを好む?方もいらっしゃるです。また、HTML形式はWeb上で公開したいという人も想定しています（その場合、横書きにする必要はありますが、縦書きを解除するのはさほど難しいことではないはず）。

ということで、当面はhtml、txt（epub）並存になっていくのかなと。
EPUB連携が進むと、html形式はかつてのGBAT2STextになっていくのかもしれませんが…^^;

＃ 本Issueは、一応ご意見をお待ちしてJan Updateに持ち越します～

**Comment by toki-sor1** [comment]
> マニュアルもこの辺の改定が落ち着いたところで、まとめていければと思っています～

使い方の幅が拡がるほど「AではできることがBではできない」など、その辺りの認識が困難になってくるので、マニュアルに書かれていると安心ですもんね。
後日、落ち着いた頃によろしくお願いいたします～。

> ということで、当面はhtml、txt（epub）並存になっていくのかなと。

一から手探りで新たな執筆方法を習得するのは大変なので、なるべくなら色んな手段があった方が「この方法だったら今までのやり方が活かせそうだな」って利用の決め手にもなりそうなので良いかなと思います。

**Comment by snext1220** [comment]
コメントありがとうございます！

使い方の幅が拡がるほど＞本当にそう思います。経緯を把握している人しか使えない、とならないよう、マニュアル整備してまいりたいと思います^^; 一寸先にはなるかと思いますが、お待ちくださいませm(_ _)m

なるべくなら色んな手段があった方が＞ご賛同ありがとうございます！メンテとの関係で、どこかでhtmlはそろそろ破棄？みたいなことを言い始めるかもしれませんが^^;、まずは二本並存で行きたいと思います。
