### ISSUE TITLE
【PgFlow】特殊リンクの複数配置

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#225]
https://github.com/snext1220/snext-management/issues/18#issuecomment-706559454 由来のIssueです。

従来、特殊リンクは1シーンひとつずつしか配置できないようになっていましたが（PgFlow上での制約）、複数リンクを配置可能に改めます。既に反映済みなので、ご確認くださいませ。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで特殊リンクが複数登録できることを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 86.0.4240.183(64bit)にて動作確認。
1つのシーンに特殊リンクを複数配置することができました。
