### ISSUE TITLE
【PgFlow】ダイナミックヘルプの改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#226]
従来からの機能ですが、これまでは属性名が重複している場合など、一部の項目が正しいページ位置にジャンプしない問題がありました。

今回、［基本］［シーン］タブについて、この問題を解消しています。
その他、グリッド系のタブからは従来通り、各要素の先頭位置に移動します。

#### ご相談

当初、ラベル位置からツールヒント的にヘルプ表示させることも考えたのですが、オートコンプリートとの絡みで却って見難いのかなと自己廃案にしました。その他、サイドバー、トーストなどで表示させることも可能ですし（トーストは見難いかも）、ご要望あればお寄せください。
＃ 実はヘルプページから動的にテキストを取得するコードは、廃案作業時に準備済みなので、表示方法さえ決まれば、それなりに応用できます。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 86.0.4240.183(64bit)にて動作確認。
基本、シーンタブで各ページ位置にジャンプすることを確認しました。
（基本タブのサマリー、リンク、シャッフル除外、背景色のジャンプ位置は、現在のものが正しい位置なのでしょうか？）

私は、現在のマニュアルからのジャンプで良いと思っています（別窓表示の方が情報を確認し易いので）。
ただ、現在の仕様でちょっと気になるところがありました。

- マニュアルにリンクしていることが分かりにくい
  - リンクのアンダーバー表示or「？」マーク挿入？

- ワンクリックだと入力候補のサイドバーが表示されたり、入力欄を選択してしまう
  - 各タブ内の説明文にヘルプとダブルクリックについての説明を追記？

**Comment by snext1220** [comment]
@toki-sor1 さん：
ご確認ありがとうございます！

> 基本タブのサマリー、リンク、シャッフル除外、背景色のジャンプ位置は、現在のものが正しい位置なのでしょうか？

これらPgFlow固有の機能については、マニュアルに対応する項目を設けていないもので、このような挙動になっています（統一は全然問題ないのですが、却って冗長かなと放置していました^^;）。どうしましょうかね...？

> リンクのアンダーバー表示or「？」マーク挿入？

ですよね...一応、起動時のTIPSには入れているのですが、ご指摘覚悟していました^^;
ただ、現時点では以下の理由から悩んでおります。

+ ［?］アイコン：横幅がギリギリ＆各項目につくと五月蠅いか
+ 説明文：同じく縦幅がギリギリなので、迷い中（［基本］タブは問題なし）
+ リンクのアンダーバー：上記同様、各項目につくと五月蠅いか

亜案として、

+ ラベルホバー時にマウスポインタ―をヘルプスタイルに変更する
+ （中途半端ですが）［シーン］タブの［エディター領域を広げる］の横に説明テキストを入れるか
+ 現在はラベル or 入力ボックスのダブルクリックでヘルプ表示しますが、入力ボックスを対象から外す

なども考えておりますが、如何なものでしょうか。

**Comment by toki-sor1** [comment]
> これらPgFlow固有の機能については、マニュアルに対応する項目を設けていないもので、このような挙動になっています（統一は全然問題ないのですが、却って冗長かなと放置していました^^;）。どうしましょうかね...？

なるほど、そういうことだったのですね。承知しました。
もし対応する項目を設ける必要があると判断した場合は、その時に改めてリンクする感じで、現時点ではこのままで良いと思います～。

> リンクのアンダーバー表示or「？」マーク挿入？

やはり横幅の問題は出てきますよね～…。
個人的には、亜案の**ラベルホバー時にマウスポインタ―をヘルプスタイルに変更する**が分かりやすくて良いかなと思いました。

**Comment by snext1220** [comment]
> もし対応する項目を設ける必要があると判断した場合は、その時に改めてリンクする感じで、現時点ではこのままで良いと思います～。

ありがとうございます！
こちら追加そのものは全く問題ないので、もし気になる場合にはまたお声がけください。

> ラベルホバー時にマウスポインタ―をヘルプスタイルに変更するが分かりやすくて良いかなと思いました。

こちらも了解です！
先ほどGitHub Onlyで反映させて戴きました～

**Comment by toki-sor1** [comment]
> ラベルホバー時にマウスポインタ―をヘルプスタイルに変更する

早速のお返事＆ご対応ありがとうございます！
GitHub版（https://snext1220.github.io/stext/playground/ ）で確認しましたが、ヘルプマークのおかげで「おっ、これは？」と気付き易くなるのが良いと思いました！

**Comment by cocotori** [comment]
>ラベルホバー時にマウスポインタ―をヘルプスタイルに変更する

これはいいですね！感覚的にヘルプがあることがわかりやすくなったと思います。

個人的には更に、
>現在はラベル or 入力ボックスのダブルクリックでヘルプ表示しますが、入力ボックスを対象から外す

があるとありがたいなと思っていますが、無理にとは言いません。

わたしは入力ボックスを選択するときにうっかりダブルクリックをしてしまうことが
結構あるのですが、そのたびにヘルプが出てきてしまい、
煩わしさを感じてしまうことがありました。

**Comment by snext1220** [comment]
> 現在はラベル or 入力ボックスのダブルクリックでヘルプ表示しますが、入力ボックスを対象から外す
> があるとありがたいなと思っていますが、無理にとは言いません。

了解です。こちら先ほどGitHub Onlyにてリリース済みです！
