### ISSUE TITLE
【PgFlow】nexts属性への対応

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#227]
［シーン］タブからnexts属性の入力を可能にしています。

本来、 #191  で管理すべき項目ですが、内部的な修正が大きかったため＆幕末企画にも影響するため、きちんと確認いただいた方が良いかと思い、New IssueとしてUpしています。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeでnexts属性が設定でき、保存時に出力されることを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 86.0.4240.183(64bit)にて動作確認。
Pg Flowでnext属性を設定後、引き継ぎ先のシナリオに情報が引き継がれていることを確認しました。

しかし、挙動で気になるところがありました。
例えば**誤ってend属性のないシーンでnext属性を設定してしまった場合**です。

この時、どのシーンをクリックしても設定したnext属性が表示されてしまうため、**見た目上はend属性のあるシーンでもnext属性を設定したように見えてしまい**ちょっと紛らわしいと感じました。
（実際は、end属性のないシーンにだけnext属性が適用されている）。

**Comment by snext1220** [comment]
> 見た目上はend属性のあるシーンでもnexts属性を設定したように見えてしまいちょっと紛らわしいと感じました。

おぉ、失礼致しました...
いつものあるあるで設定値の同期が取れていませんでした。
先ほど修正しましたので、ご確認くださいませm(_ _)m

＃ いいわけなのですが、この辺、古い技術を利用しているのがネックになっていますね...値の整合を取るのに、そちこちコードを編集しなければならないという（色々同期のための仕掛けを自作しているのですが、十分ではありません；）

**Comment by toki-sor1** [comment]
>> 見た目上はend属性のあるシーンでもnexts属性を設定したように見えてしまいちょっと紛らわしいと感じました。

> 先ほど修正しましたので、ご確認くださいませm(_ _)m

いえいえ、お忙しいところ迅速にご対応いただきありがとうございます…！
シーン毎にnexts属性が表示されるように修正されているのを確認しました！

> 値の整合を取るのに、そちこちコードを編集しなければならないという

おぉ…そうだったのですね…。
一か所を修正すればOKというわけではなく、同時にあちこち修正しなければならないというのはきついですね…；
いつも見えないところでソーサリアンのように激戦を繰り広げられていらっしゃるリオさん…本当にお疲れ様です…；；

**Comment by snext1220** [comment]
早速のご対応ありがとうございます！

激戦＞おつありです！早くトラベラーズインに帰還したいところですが、中々Beautiful dayが流れません^^;

**Comment by cocotori** [comment]
chromeで確認。

無事、引き継がれていました！

引き継ぎの操作に戸惑いそうなので、
きちんと本文中に案内を入れるなどの工夫がいりそうですね・・・
（引き継ぎ先で、間違って最初からを選んでしまうなど）

**Comment by snext1220** [comment]
ご確認ありがとうございます！

> （引き継ぎ先で、間違って最初からを選んでしまうなど）

そうなんですよね...システム的にもガードをかけたいところなのですが、現在ノーアイデアなので^^;、まずは案内でフォローしていければと～

**Comment by cocotori** [comment]
あと、今回の件と直接関係はありませんが、
そろそろシナリオのコード名を一意に持つのが難しくなってきたのではないかと思います。
（シナリオ数が増えて来たということなので
　とても素晴らしいことなのですが。）

例えばですが、シナリオの番号をコード名の先頭につけるなどの工夫はいかがでしょうか？
ソートしたときに順番もわかりやすくなっていいのではないかと思います。
直リンしているところもあると思いますし、
今までのシナリオに関しては今のままでいいと思いますが。

**Comment by snext1220** [comment]
ご意見ありがとうございます！

> 一意に持つのが難しくなってきた

ですね～ そもそも/stextフォルダーの配下もフォルダーが増えてきたので、かねがねサブフォルダーを切りたいという思いもあったり（この辺は影響も大きく手を出しかねているのですが）。

とりあえずフォルダー名については賛成です。ただ全体連番は今後の見せ方次第で変化していくのかな、という懸念もあり（実はUtilもその問題で、王さまbotとの不整合が発生しています）、たとえばシリーズごとに緩く接頭辞を付けるというのは如何でしょうか。
＃ たとえば、幕末であればbak01blackのように。

**Comment by cocotori** [comment]
シリーズごとと全体連番では全体連番のほうが
個人的には賛成度合いが上ですが、
それほどこだわりがあるわけではないのでどういう形でも大丈夫です。

一応、全体連番のほうがいいと思った理由を述べますと、
全体連番であれば命名がシンプルで迷いようがないと思ったからですが、
上で言いましたようにこだわりはそれほどありません。

**Comment by snext1220** [comment]
ご意見ありがとうございます。

シンプルで迷いがない＞ここは魅力的なんですよね...^^;
ただ、スミマセン、とりあえず全体連番での不整合は（現時点では問題ないのですが）将来的に変更のネック or 却って判り難くなる原因ともなりそうなことから、まずはシリーズ接頭辞とさせてくださいm(_ _)m
※そもそも本格的に自動化を進めると、それこそランダム連番にもなっていきそうですが^^;
