### ISSUE TITLE
ステータスシートのレイアウト改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#229]
https://github.com/snext1220/snext-management/issues/13#issuecomment-708848475 由来のIssueです。以下の改善を行っています。

+ スマホ環境でも折り返しを最小限に抑えるため、配置を修正（少々非対称にはなってしまいましたが…）
+ スマホ環境ではボタンサイズを縮小
+ 数値入力ボックスをただのテキストボックスに（上下ボタンが表示されて、桁数が多い場合に肝心の数値が見えなくなっていたため）
+ （幕末対応）STR～KRMの初期値を表示

折り返しはかなり改善しているはずですが、そもそも［+］［-］ボタンの重要度が落ちていることから、レイアウトが更に切迫する場合には、優先順位の低いものから削除も検討してまいります。

以下、既存の意見です（上がときのじさん、下がリオ）。

>［+］［-］は、PC・スマホ環境ともによく利用しています～。ただ、シナリオでは自動加算＆減算が主流となってきましたし、ボタンを減らす方針はありかなと思っています。個人的には、**HP、MPは［-］［+］両方、STRなどはボタン廃止（普段は手動で頻繁に増減させないため）、星の欠片は［-］のみ表示（手動では減らす方が多い気が）**が良いですね。

> HP/MP、STR～KRMは賛成です！
星の欠片は、逆に星を加算する場合の［＋］は時々使うのですが（自動で賄えない場合）、［－］はほぼほぼ魔法実行で使わなかったので、私は逆でした^^;

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで問題無く表示できましたー

**Comment by toki-sor1** [comment]
iPhone 7／Safariで動作確認。
折り返しが最小限になりましたし、STR等の初期値表示も良いと思います！

［-］［+］の有無について、私の意見は下記のように前回と同じですね；

- HP、MPは［-］［+］両方あった方が良い
- STRなどはボタン廃止（普段は手動で頻繁に増減させないため）
- 星の欠片は［-］のみ表示

星の欠片のみリオさんと意見が逆になっていますので、 お忙しいところ恐縮ですが、@Salvadors-cabin さんと @cocotori さんのご意見もお聞きできましたら～。

**Comment by snext1220** [comment]
@toki-sor1 さん：

ご意見ありがとうございます～
意見が割れてしまいましたが、双方利用するということであればママにしてしまうのもありかもしれませんね。
＃折り返しについても、手元のAndroidではStatus、Magicシート共に乱れが気になるものはなくなったので^^;
　もちろん、気になる折り返し箇所がある場合にはなんなりとお知らせください。

**Comment by toki-sor1** [comment]
> 意見が割れてしまいましたが、双方利用するということであればママにしてしまうのもありかもしれませんね。

なるほど、現状ではこちらの環境（iPhone 7）でも星の欠片の辺りで折り返しは発生していないので、そのままでも問題ないかもしれないですね。

**Comment by cocotori** [comment]
PC:
Chrome

タブレット:
HUAWEI MediaPad M3 Lite
Android Chrome

どちらもレイアウトがスッキリした形で表示されていいと思います！

手動で操作することがないとは言えないので、
レイアウト崩れが無いのであれば+-はすべて残しておいていいのではないかと思います。

**Comment by snext1220** [comment]
@cocotori さん：
ご確認ありがとうございます！はい、今回のレイアウト変更で折り返しも発生しなくなったので、無理して機能削除する必要はなさそうですね。

こちらは全員のご意見も出そろったので、これにてCloseとしてまいります。
