### ISSUE TITLE
stars属性、魔法分岐ボタンの仕様変更

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#23]
#18 で［戻る］ボタン廃止の問題が出ていますが、現在、［戻る］を廃止せずに、戻る時に状態をロールバックする方向も、並行して検討しています。

その場合には、以下の点が問題となります。

#### stars属性の減算

対象の星がゼロ未満になった場合にゼロ丸めをしていますが、ロールバックができなくなります。そのため、ゼロ未満になる場合に、そのまま負数にすることを検討しています（エラーにしても良いのですが、多分無敵モードが使いにくくなる）。あるいは減算は不可にするのもありかとは。

#### 魔法分岐ボタン

同じく、魔法分岐ボタンでは移動先で星を減算していますが、［戻る］に際してどのボタンでの移動かが判定できないため、ロールバック不可の対象です。そこで、以下のように移動先でmagic属性を明示する方向にできないかと（元々のサルバさん案です）。

`<scene magic="NOILA-TEM">`

いずれも新機能の仕様変更になりますが、各シナリオに展開する前に、修正するならば修正した方が影響は押さえられるかと。

もちろん、そもそもロールバックせずに［戻る］ボタンを無効化すればいいではないか、と言うご意見もありかとは。

**Comment by Salvadors-cabin** [comment]
>stars属性の減算

負数でいいと思います。そもそも星が負数になる可能性があるのに減算する処理を入れてしまうのはシナリオ側でコントロールすべきことのように思えます。

>魔法分岐ボタン

magic属性の追加も良いと思います。未対応のシナリオは従来の魔法分岐のままなので影響がなくていいのではないかと思います。

**Comment by snext1220** [comment]
実は、Starの所持数による分岐制御はないんですよね…（魔法分岐のみ）
となると、負数の発生を防ぐ手段がないので、負数そのものを許容すべきではない？

＃ そもそも星を減算するニーズってありますか？（GoldなどはFree1,2で表現できるし）＞皆さん

**Comment by Salvadors-cabin** [comment]
>＃ そもそも星を減算するニーズってありますか？

星の減算は魔法を使った時だけなので、単独での減算は必要ないと思います。
将来的に何かのペナルティで使える可能性はあると思いますが、今のところ予定はないです。

**Comment by RYU-DS** [comment]
一応、そのスレ第一部ではクラーケンから逃げると捕まって、脱出判定時に星の総数を使い、脱出後に全てを半数にするのですが、そういうのを強制に出来るのは意義があると思います。

ただ、ほぼ同じ事を第三部でも使う予定ですが「特定の星をいくつ減らす」だけでなく、「全てを半数、1/4、1/3にする、特定の星を無くす」といった事もできないと使いにくいので、そういう公式が設定できるといいのですが…

星所持数による分岐はぜひ欲しいです。これも総数、各種をいくつ持ってるか？が設定できないと使い道が少なくなりますが…

結局それにかかるシステム側の労力と相談でしょうか。
個人的には星総所持数による分岐だけは欲しい所です（プレイ時間や準備の出来具合を計るメーターとして）。

**Comment by snext1220** [comment]
半数、1/4、1/3＞こちらは［戻る］を想定すると、ロールバックができなくなるので難しそうです...（端数が出た場合の処理をフォローしきれない）
＃ ［戻る］を失くすと様々なことが可能になるので、ホントに扱いは悩ましいところです... #18 で指摘戴いているデメリットも判るので、無条件になくすこともできずにいますが；

所持数による分岐は、詳細調査は必要ですが可能だと思います。指定としては以下のものでしょうか（指定方法はあくまでイメージです）。

+ sALL50 … 星の総数が50以上であること
+ s7:6:5:4:3:2:1 … 各種の星がそれぞれ指定の個数であること

**Comment by RYU-DS** [comment]
「戻る」がからんだ場合は「手動で戻してください」でいいのでは？
自動/半自動は正規のプレイルールに従った場合のためのものであり、それから外れる「戻る」を使うならそれに従う必要も無い、というスタンスでも別にプレイヤーを突き放す感じにはならないと思います。
＞sALL50 … 星の総数が50以上であること
以下も欲しいです。
＞s7:6:5:4:3:2:1 … 各種の星がそれぞれ指定の個数であること
これも特定の数ちょうどである事は無いので、指定個数以上と以下が欲しいです。

**Comment by snext1220** [comment]
手動で戻してください＞はい、ある程度まではそれでよいかとは^^; ただ、結構自動化も進んできているので、そもそも何を戻していいかをプレイヤーが判断できるか、ですね（ある程度までは可能だと思いますが、完全には難しくなりつつあると思います）。。

仕様については言葉足らずで失礼しました。

> sALL50 … 星の総数が50以上であること
否定で以下（未満？）も可能になる予定です。

>s7:6:5:4:3:2:1 … 各種の星がそれぞれ指定の個数であること
こちらも以上、以下（未満？）対応の予定です。

**Comment by toki-sor1** [comment]
ロールバック案採用を前提として意見を書きます。

> stars属性の減算

負数処理は、「有り」だと思います。
減算処理は、重大なバグが出る危険性が高い場合は「無し（手動）」、
そうでなければ「有り」でしょうか。

> 魔法分岐ボタン、星所持数による分岐

実装予定の仕様で良いと思います。

**Comment by snext1220** [comment]
> 負数処理有

負数を許容する、という意味でOKでしょうか？（それとも負数のゼロ丸め処理が有り？）
たぶん前者だと思いますが、一応確認でございますm(_ _)m

**Comment by toki-sor1** [comment]
はい、前者の意味で合っています。

**Comment by snext1220** [comment]
皆さま＞ ご意見ありがとうございました。

こちらは戴いたご意見に基づき、以下の改定方針で参ります。

+ stars属性の負数丸めは廃止（減算機能は残すが、注意の旨をマニュアルに追記）
    + 1/4、1/2などはロールバック未定のため、今回は見送る
+ 魔法行使による星減算は（自動ではなく）magic属性明記とする
+ 星所持数による分岐は上記の仕様にて（細部は変更可能性あり）

**Comment by snext1220** [comment]
ロールバックの実装変更により、こちらの改定方針も変更致します。恐縮ですが、ご了承ください。

+ magic属性の追加については中止（ロールバック可能になるため）
+ stars属性の負数丸めも維持（ロールバック可能になるため）
+ 星所持数による分岐は上記の仕様にて（細部は変更可能性あり）
+ 星の1/2を試験的に実装
