### ISSUE TITLE
SGML拡張による実績数／率取得

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#230]
https://github.com/snext1220/snext-management/issues/13#issuecomment-708848475 由来のIssueです。SGML拡張に以下の式を追加します。

+ ${result?id}：シナリオidの実績数を取得
+ ${result_rate?id}：シナリオidの実績率を取得

ただし、現在の実装の制約で、起動時の最初のページでは実績情報を取得できません（Scene 0というわけではありません）。取得失敗時は「?????」を表示します。
ほとんどの場合は問題は発生しないはずではありますが、若干の中途半端さも感じます。。まずはご意見うかがえますと幸いです。
＃ 実装の根幹に絡んでおり、問題修正には最大規模に近い修正が入りますので、採用難しい場合には、実績表記はサイドバーに委ねるなど、他の方法を検討させてください。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 86.0.4240.183(64bit)にて動作確認。
上記の式を設定し、実績数と実積率が正常に表示されることを確認しました。

> ほとんどの場合は問題は発生しないはずではありますが、若干の中途半端さも感じます。。まずはご意見うかがえますと幸いです。

主に幕末ソーで活用する機能ですね。
ステータス強化のタイミングは、初期起動で表示させるScene 0ではなく、次のScene 1からなので、現在の仕様で特に問題はないかなと思っています。

ただ、幕末ソー以外でこの機能を使うとなると、幕末ソーと同じルールにしなければ、起動時の最初のページと式を設定するページが噛み合わないこともありそうですし、確かに中途半端な感じはしますね…。

**Comment by snext1220** [comment]
了解です！
とりあえずマニュアルにはまだ載せずに機能としては残しておきますが、実績表記をどうするかは幕末Issueの方でご意見うかがえれば幸いです。

**Comment by toki-sor1** [comment]
> 幕末ソーサリアン

> とりあえずマニュアルにはまだ載せずに機能としては残しておきますが、実績表記をどうするかは幕末Issueの方でご意見うかがえれば幸いです。

https://github.com/snext1220/snext-management/issues/13#issuecomment-723582625 こちらのIssueにて返信いたしました～。

**Comment by cocotori** [comment]
実績表記に仕様ですが、使うときにやや気をつけなくてはなりませんが、
機能としては十分だと思います。
わたしの方は特に反対はありません！

**Comment by snext1220** [comment]
ご確認ありがとうございました！
では、残課題は #191 に委ね、こちらはCloseとしてまいります～
