### ISSUE TITLE
【PgFlow】アイテム～実績idの重複チェック

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#231]
https://github.com/snext1220/snext-management/issues/18#issuecomment-710006227 由来のIssueです。

［アイテム］～［実績］タブでid重複があった場合にエラーを発生するように改めました。
本番環境反映済みです。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeでエラー時のメッセージ表示を確認しました

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 86.0.4240.183(64bit)にて動作確認。
［アイテム］～［実績］タブでid重複時にエラーメッセージが表示されることを確認しました。

**Comment by cocotori** [comment]
Chromeで確認。

最初からidを重複させた場合はエラーが出るのですが、
例えば、
f01がある状態で次の行にf02を作成　→　f02をf01に修正

とするとエラーが出ませんでした。その状態でxmlに出力すると、
xml上でもidの重複が起きてしまいました。

**Comment by snext1220** [comment]
ご指摘ありがとうございます！
こちら修正し、GitHub OnlyにてUpしております。
＃ 実は完全なチェックではないのですが、それを言っていくと、そちこち修正しなければならないので、まずはママとしております^^;
