### ISSUE TITLE
不正な条件式への通知

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#232]
https://github.com/snext1220/snext-management/issues/18#issuecomment-710729180 由来のIssueです。SGMLで、リンクに不正な条件式が渡された場合に、コンソールに該当箇所のHTMLが表示されるように改めました。

コンソールを開いていただく必要はありますし、内部的な表記ではありますが、少なくともどこで問題が発生しているのかを特定しやすくなったのではないかと。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 86.0.4240.183(64bit)にて動作確認。
リンクの条件式に「f99!」と誤った表記を入力し、コンソールを確認したところ、こちらの画像のようにエラー箇所を確認できました。
![image](https://user-images.githubusercontent.com/42646342/98464359-c29a3900-2205-11eb-8700-6df1a883e8be.png)

エラー箇所の特定がし易くなって良いですね。
ただ、表記ミスではなく「存在しないフラグid」を入力した場合は、上の画像のようにはっきりとエラーを起こしている箇所が確認できないようでした。
![image](https://user-images.githubusercontent.com/42646342/98464500-afd43400-2206-11eb-9a5b-397ab815cddf.png)

**Comment by snext1220** [comment]
こちらスミマセン、存在しないフラグidで確認してみたのですが、特に問題なく動作しているようでして。。お手数ですが、問題となる.json or .xmlをお送り戴いてもよろしいでしょうか（汗

＃ ちなみに、idの不整合はPgFlowのサイドシートを使っていれば、比較的問題起こりにくいということでチェックは割愛させていただいておりました^^;（勿論起こりやすい問題の場合にはチェック追加していければと思います～）

**Comment by toki-sor1** [comment]
お返事が大変遅くなってしまい申し訳ありません…！
ChromeをアプデしてWin 8.1／Chrome 87.0.4280.88にて動作確認を行いましたが、やはり存在しないフラグを指定すると、どこでエラーが起きているのかはっきりと分からないようでした。

https://onedrive.live.com/?id=4837C202555BE782%217411&cid=4837C202555BE782
（stext_flag.jsonというファイルです）

ただ、ゲーム画面自体は動作しているので、チェックの優先度は低そうですね。
問題がなければ、そのままとしていただけましたら。

![image](https://user-images.githubusercontent.com/42646342/101272220-825eb400-37cd-11eb-95c5-c68493d5c786.png)

**Comment by snext1220** [comment]
お忙しい中ありがとうございます！
コンソールを拝見する限り、SText側ではなさそうですね～
恐らくTISProToolbarDefine.jsはTrendツールバー（セキュリティソフト）で、何か問題が発生しているように見えます。
＃ その理屈からすると、フラグの有無に関わらず、出ている可能性は高い、、、かも？

とりあえず戴いた.jsonファイルを実行したところ、特にエラーは出ないようだったので＆ときのじさん環境でも動作そのものは問題ないとのことで、今回はママにできればと…！（最後のエラーはmain.mp3が存在しないためなので、今回は問題ないです～）

**Comment by toki-sor1** [comment]
ご確認いただきありがとうございます！
なるほど、セキュリティソフト側のエラーでしたか；
確かに条件式に問題のないシナリオを実行した時も同じようなエラーが出ておりました。

お騒がせしてしまい申し訳ありません…；
今回はママでこちらも問題ありませんです！（main.mp3についてもなるほど納得です！）

**Comment by snext1220** [comment]
ご確認ありがとうございます～
お騒がせ＞いえいえ、システム内部的な問題は本当に判り難いので、お気づきの点はなんなりとお聞かせ下さい^^
では、今回はママでCloseとしてまいりますね。
