### ISSUE TITLE
【PgFlow】EPUB出力時のモンスター／アイテム一覧生成

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#233]
https://github.com/snext1220/stext/issues/224#issuecomment-723543240 由来のIssueです。

現在は、enemy、itemなどの要素で作成した情報はEPUBでは無視されますが、これらの情報をもとに巻末に一覧を作成することで、連携を強めていければと思っています。

+ 敵一覧
+ アイテム一覧
+ フラグ／実績チェック表

ジャストアイデアなので、まずは皆さまのご意見待ちです（他にもEPUB連携で、こんなこともできれば、というご意見があれば歓迎です）。

**Comment by cocotori** [comment]
一覧表が作れるのは面白いかもしれませんね。

一覧表にしても、隠しボス等の意図的に表に出したくないものもあるかもしれませんので、
個別にON/OFFができるといいかもしれません。
凝りだすとキリがありませんが。

**Comment by toki-sor1** [comment]
一覧表の生成は、まさに書籍型のゲームブック的で良いと思います。
敵一覧、アイテム一覧は必須でしょうか。
フラグの管理もゲームブックではありますよね。
実績はちょっと迷うところですが、一つのシステム（Pg Flow製の特徴）として入れても面白いかなと思いました。

> 一覧表にしても、隠しボス等の意図的に表に出したくないものもあるかもしれませんので、
個別にON/OFFができるといいかもしれません。

確かに隠しておきたい情報ってありますよね。
ON/OFFできると使いやすそうです（OFFにした項目は、空白または？？？表記になるなど）。

**Comment by snext1220** [comment]
ご賛同ありがとうございます！
では、基本は追加の方向で進めてまいりますね。

ON/OFFについてはPgFlowにも影響するので、二段階（後日）リリースになるかもしれませんが、まずは、基本機能からゆるゆる進めていければと。

**Comment by snext1220** [comment]
先ほど以下の対応を行いました。

+ アイテム、敵、実績情報の出力（フラグは一般的に内部情報なので、今回は除外）
+ シーンidシャッフル時のシーンidソートができていなかったので対応
+ EPUB生成時の設定ファイルに誤りがあったので差替

**Comment by Salvadors-cabin** [comment]
Win10+Edgeでアイテム、敵、実績情報がファイルに出力されることを確認しました。

**Comment by cocotori** [comment]
chromeで確認。

一覧が無事出力されているのを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
一覧が表示されていることを確認しました～。
しかし、縦書き変換だと仕様上しかたのないことかなとは思いつつ、半角英数（1、2など）が横（数字が倒れた状態）に表示されてしまうのが気になりますね；

**Comment by snext1220** [comment]
ご確認ありがとうございます！

横に倒れて＞確かに。本文は作者さんの裁量にお任せするとして、実績のLvくらいは漢数字に変換した方が良いでしょうか^^;

**Comment by toki-sor1** [comment]
そうですね～……本文は、縦書きを前提とした作りをすれば大丈夫かなと思うのですが、実績のLv表記はいじれないので、可能であれば全角か漢数字への変換など、システム側でご対応いただいた方が良いかなと思います～；

**Comment by snext1220** [comment]
了解です！
漢数字については早速修正し、本番環境にも反映させて戴きました～

**Comment by toki-sor1** [comment]
早速のご対応ありがとうございます！
漢数字に変換されているのを確認しました！
ただ、そこで気になることがありました。

- 実績の難易度が改行されて「難易」「度」と読み辛い表示になっていた
- ルビを振ると、頭に必ず「＄」が表示されてしまう（ルビは電子書籍用にしても使用するものなので、気になってしまった）

**Comment by snext1220** [comment]
@toki-sor1 さん：
ご確認ありがとうございます！

> 実績の難易度が改行されて「難易」「度」と読み辛い表示になっていた

こちらは文字数やデバイスの縦幅にも依ってくるので悩ましいのですが（完全には解消できない可能性がある）、少しでも短く「Lv」にでもしておきましょうか。横にはなってしまいますが…^^;

> ルビを振ると、頭に必ず「＄」が表示されてしまう（ルビは電子書籍用にしても使用するものなので、気になってしまった）

でんでんとSTextとの仕様差による問題ですね。。。（https://conv.denshochan.com/markdown#ruby）
こちらはEPUB（でんでん）出力する際には、でんでんマークアップに従って本文記述戴く必要があるかと思います。「SText2でんでん」コンバーターを実装することも可能ですが、恐らくEPUB出力する際にはSTextの動的な設定はほぼ利用できないと考えると、あまりメリットはない、かも？ｗ
一応、ルビ構文のみ置き換えることは可能ですが、ご意見うかがえれば幸いです～

**Comment by toki-sor1** [comment]
> こちらは文字数やデバイスの縦幅にも依ってくるので悩ましいのですが（完全には解消できない可能性がある）、少しでも短く「Lv」にでもしておきましょうか。横にはなってしまいますが…^^;

なるほど～……電子書籍などデジタルならではの問題ですね；；
完全に解決するのは難しそうなので、**「Lv」または「難度」** 辺りがギリギリでしょうかね；

> でんでんとSTextとの仕様差による問題ですね。。。

でんでんは、「＄」がなくてもルビが振られる仕様なのですね～；
EPUB出力する前提でシナリオを作るとなると、でんでんの仕様に合わせてシナリオを作成することになりそう（＝SText用シナリオにはしない）なので、**現在の設定のままで大丈夫そうですね。**
ご説明いただきありがとうございました！

**Comment by snext1220** [comment]
ご確認ありがとうございます！

> 完全に解決するのは難しそうなので、「Lv」または「難度」 辺りがギリギリでしょうかね；

では、今回は横になるのを避けて一旦「難度」としておきますね。本番環境にも反映済みです～

> 現在の設定のままで大丈夫そうですね。

ありがとうございます！
今後、SText／でんでんマルチなシナリオを作成するとなった場合には（中々事例もないと辛そうなので、落ち着いたら、そんな企画も試してみたいなと）、この辺も手を入れていきたいですが、まずはこのままと致しますね…！

**Comment by toki-sor1** [comment]
> では、今回は横になるのを避けて一旦「難度」としておきますね。本番環境にも反映済みです～

早速ありがとうございます～！
ただ、ちょっと確認してみたところ、難度は一行であるためか、今度は「度」「難」のように表示されていました；；
![image](https://user-images.githubusercontent.com/42646342/128625194-73624ddb-6768-4b74-917f-84436fa6e2d1.png)

> 今後、SText／でんでんマルチなシナリオを作成するとなった場合には（中々事例もないと辛そうなので、落ち着いたら、そんな企画も試してみたいなと）、この辺も手を入れていきたいですが、まずはこのままと致しますね…！

承知しました！

**Comment by snext1220** [comment]
> ただ、ちょっと確認してみたところ、難度は一行であるためか、今度は「度」「難」のように表示されていました；；

ムム、縦幅狭いとやはりだめですか...Lvで再修正いたしました^^;

**Comment by toki-sor1** [comment]
何度もご対応いただいてお手数をお掛けします；；
縦書きで「Lv」（横に倒れた状態）と出力されているのを確認しました！
