### ISSUE TITLE
敵／アイテム情報の埋め込み（SGML式）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#234]
https://github.com/snext1220/stext/issues/224#issuecomment-723543240 由来のIssueです。

現在は、enemy、item、resultなどの要素で作成した情報はサイドシートでしか表示できませんが、SGML式から引用できるようにできればと考えています。以下イメージ。

+ ${enemy?m01:name} （モンスター名）
+ ${enemy?m01:text} （モンスターの概要）

元々EPUB形式での機能強化を想定していましたが、通常のSText向けシナリオ作成にもご利用いただけるのかなと思っています。対象は、以下の情報です。

+ enemy
+ item
+ result （使う、か？）

**Comment by toki-sor1** [comment]
> 元々EPUB形式での機能強化を想定していましたが、通常のSText向けシナリオ作成にもご利用いただけるのかなと思っています。対象は、以下の情報です。

主にEPUB形式での利用になりそうですが、STextの通常シナ＆EPUB形式のシナの両方で利用できた方が、利用者としても分かりやすいかなと思います。

enemy、item辺りはよく使いそうですが、resultはどうでしょうね……？
電子書籍等のゲームブックで実績の設定は主流なのかどうかちょっと不明なところがあるので；
たた、STextシリーズ（？）の特徴として、実績収集を一つのシステムとして取り入れても面白いかもしれませんね。

**Comment by snext1220** [comment]
ご意見ありがとうございます！

> STextの通常シナ＆EPUB形式のシナの両方で利用できた方が、利用者としても分かりやすいかなと思います。

はい～では、基本はそのように…！
STextでは実行時に判定、EPUBでは出力時の判定なので、どこまで二重化が影響するかがまだ判らず、様子を見ながら
ご相談させてくださいませ。

電子書籍でのresult＞メジャーとまでは言えなさそうですが、実装している書籍は何度か見かけた気がします。とりあえずenemy、itemをやる場合には、resultを入れる入れないはさほど工数差もないので^^;、進めていきたいと思います～
＃ それなり汎用的な仕組みではあると思うので、仰る通り、SText電子書籍の特長としても意味はあるかと…！

**Comment by toki-sor1** [comment]
> STextでは実行時に判定、EPUBでは出力時の判定なので、どこまで二重化が影響するかがまだ判らず、様子を見ながら
ご相談させてくださいませ。

実際に試してみないと、どこにどのような影響が出るのか分からなかったりしますもんね；
様子を見ながら相談を重ね、内容を詰めてゆくのですね。承知しました！
よろしくお願いいたします！

> 電子書籍でのresult＞メジャーとまでは言えなさそうですが、実装している書籍は何度か見かけた気がします。

おお、そうなのですね！　情報ありがとうございます～！
もし機能を実装する際には、enemy、itemに加えてresultが入っても大丈夫そうなのですね。

創作って発想や工夫次第で色んな表現ができるものなので、まだメジャーというほどではないシステムや、斬新なシステムなど、STextやPg Flowを通じて「こんなこともできるんだ！」をどんどんと拡げていきたいですね！

**Comment by snext1220** [comment]
本件、param要素の対応と合わせて、まずはシステム本体を対応済みです（Epub出力は未対応）。
テストのほどをお願いいたします。

+ ただし、機能共通化のため、${item:～}などは${var:～}と改めています。詳しくはマニュアルを参照ください。

**Comment by cocotori** [comment]
chromeで確認。

問題なく動いています！

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 90.0.4430.93(64bit)にて動作確認。
正常に動作していました。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで動作に問題ないことを確認しましたー
