### ISSUE TITLE
【PgFlow】自動シャッフル

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#235]
https://github.com/snext1220/stext/issues/224#issuecomment-723579749 由来のIssueです。

現在はtxt/html出力時のシャッフルは手動を想定していますが、設定ファイルから自動／手動を設定できるようにできればと思っています。

**Comment by Salvadors-cabin** [comment]
どんなときに自動／手動を使い分けたらよいか、分かりにくいかもしれませんね。
#224 のように必要性を感じた場合は設定するかもしれませんが、そのときには解決済かもしれないです。

**Comment by snext1220** [comment]
> どんなときに自動／手動を使い分けたらよいか

最後に必ずシャッフルするならば、自動の方が便利という感じでしょうか（シャッフル後に特定の番号を調整したいというニーズがあるため、現在は手動としています）。
本機能を入れる場合には、自動が既定、あえて手動にしたい人は**自動解除もできる**という扱いになるかと思います。

**Comment by toki-sor1** [comment]
> 現在はtxt/html出力時のシャッフルは手動を想定していますが、設定ファイルから自動／手動を設定できるようにできればと思っています。

シャッフルするのは手動が良いと思います。
最後に必ずシャッフルするとしても、自分がシャッフルしようと判断した時にシャッフルできた方が仕様として安全かなと。
（現状、ボタンを押すだけなので、手動であっても手間ではないかなーと）

**Comment by snext1220** [comment]
ご意見ありがとうございます！

> 手動であっても手間ではないかな

はい、仰る通り、手間ではないのですが、シャッフルを忘れて、「EPUBが動作しない！」になるのを気にしておりました^^;（ダイアログで説明してはいるのですが、結構うっかりはでそうかなと）

とりあえず現時点では積極的な賛成ありませんでしたのでwontfixとし、追加のご意見なければmarch updateでcloseとしていければと思います～
