### ISSUE TITLE
簡易ステータスにおけるラベル表示の改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#236]
#228 からの継続Issueです。
簡易ステータスを残すことにしましたので、こちらも指定ラベルに応じて表記が変化するよう対応していければと思っています。

現時点では指定されたラベルをそのまま表示することを想定していますが、（たとえば）頭文字、先頭2～3文字を表示、など簡単化するためのご要望などあればお知らせください。

**Comment by cocotori** [comment]
短縮形は何がふさわしいか状況によると思われるので、
なかなか扱いが難しいですね・・・

ラベルそのまま表示がシンプルで間違いがないかと思いますので、
そちらに一票です。

**Comment by Salvadors-cabin** [comment]
私は今のままでも良いと思いますが、短縮形もあれば使えると思います。
その場合、設定は通常と短縮形と２か所別々にできた方がよいと思います。

**Comment by toki-sor1** [comment]
簡易ステータスの場合、ラベルは今のまま（現状維持）が良いと思いました。
表示する文字数を制限すればレイアウトのズレは防げますが、ラベル表示で簡略化されるのを前提にラベル名を考えるのも本末転倒な気がするので；

もし強い要望があれば、その時に改めて検討しても良いのではないでしょうか。

**Comment by snext1220** [comment]
皆さん、ご意見ありがとうございます。
こちら皆さんのご意見総合して、まずは「指定ラベルに応じてそのまま表示」の前提で進めていきたいと思います。

短縮形についても一旦は保留いたしますが、実際にラベルカスタマイズが使われ、必要！という状況になったら勿論検討しますので、お声がけください。

**Comment by toki-sor1** [comment]
> 指定ラベルに応じてそのまま表示

良いと思います！
短縮形についても、必要になった時に検討する方針ですね。承知しました！

**Comment by snext1220** [comment]
本件対応しまして、GitHub Onlyにて対応済みです。
伴い、ステータスシートについても「HP MAX」「MP MAX」の表記がカスタマイズ対応されていなかったので、今回の改定で反映されるように改めています。ご確認いただければ幸いです。

**Comment by cocotori** [comment]
Chromeで確認。
簡易ステータスが、指定ラベルされていることを確認しました。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで表示に問題ないことを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 91.0.4472.77(64bit)にて動作確認。
正常に表示されていることを確認しました。
