### ISSUE TITLE
summary属性をプレイ画面にも表示

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#237]
現在、scene要素のsummary属性はPgFlow用途にすぎませんが、オプションで（＝設定オンにした場合のみ）プレイ画面に表示できるようにできればと考えています。
（id属性を表示せずに）summary属性だけを表示するなどのオプションを設ければ、いわゆる「パラグラフ番号レス」なゲームブックにも対応できるのかなと考えています。

ジャストアイデアですが、

+ 賛否
+ 賛成の場合、表示場所（本文一行目に太字 or フォント大き目など）

などご意見うかがえれば幸いです。

**Comment by cocotori** [comment]
今の所わたしの方では使い道を思いつきませんね・・・

パラグラフ番号レスのゲームブックってどんなものかなと思って検索してみたら、
ちゃなさんの記事が出てきました。

（すでにご存知かもしれませんが）とてもためになったので共有します。
http://chanagame.hateblo.jp/entry/2020/05/08/183549

なるほど、本というすでに書かれたことが確定している世界でありながら、
自分で進むべき道を選び取っていく楽しさがあるのですね・・・

話を戻しますが、summaryの表示機能については
今の所賛成とも反対とも言い難いです。
どっちつかずで申し訳ありませんが。

**Comment by toki-sor1** [comment]
ご提案ありがとうございます！
@cocotori さん、情報共有ありがとうございます！

パラグラフ番号レスなシナリオですが、STextのゲーム画面だと**本文にサマリー表示＋URLにパラグラフ番号ではなくサマリー表示**となるのでしょうか？

もしそうであれば、私は**賛成寄り**です。
ただ、前者のみの採用、後者のみの採用、両方とも採用では、ちょっと意見が異なります。

**前者**は手動で入れることが可能なため、個人的には優先度は低めでしょうか。
（サマリーを長めにすると、Pg FlowでSceneが見辛くなりそうという懸念もあります）

**後者**は紙媒体と同じくネタバレやシーンの繰り返しなどを気付かせにくくするため、ゲーム版・電子書籍版ともにあると便利な機能だと思います。

**両方とも採用**となると、URLでのパラグラフ数隠しは良いとして、Pg Flowでのサマリー表示方法を見直す必要がありそうですね。
Sceneに表示できる文字数を制限できれば、視認性の問題もクリアできそうです。
サマリー表示方法は**本文一行目に太字**が見易くて良さそうですね。
ただ、1つのシーンが短いものだと、電子書籍化した時に視界がチラつきそうなので、1シーンが長いもの（区切りが1ページ単位）と相性が良さそうです。

**Comment by snext1220** [comment]
@cocotori さん、@toki_s1 さん：
ご意見ありがとうございます！
詳細なお返事は別途とさせていただきますが（スミマセン）、とりあえず論点ばらけないよう、想定仕様のみ以下お返事いたしますね。

> STextのゲーム画面だと本文にサマリー表示＋URLにパラグラフ番号ではなくサマリー表示となるのでしょうか？

+ 本文：先頭にサマリー表示
+ ページ上部のシーン番号：非表示化（こちらで一定「シーンの繰り返しなどを気付かせにくくする」の効果はあるものと想定しています）
+ URL：移動ボタンでのマウスオーバー時に表示されるものでしょうか。こちらは残念ながらidをキーとするのは変わらないため、ママとなります。。
+ PgFlow：サマリ●○文字以上は「...」表示（省略）

もちろん、ご要望次第で仕様は変化していければと思うので、まずは叩き台ということで引き続きご意見頂ければ幸いです。

**Comment by toki-sor1** [comment]
@snext1220 さん、仕様のご説明ありがとうございます！

> 本文：先頭にサマリー表示

いいと思います！

> ページ上部のシーン番号：非表示化

なるほど、こちらのことでしたか！（私は普段、STextではあまり気にせずに遊んでいたもので；）
いいと思います！

> URL：移動ボタンでのマウスオーバー時に表示されるものでしょうか。

はい、そうです！
こちらはそのまま表示されるのですね、承知しました～（表示されてもOK）。

> URL2：アドレス欄という意味では、変わらずシーン番号、サマリーともに表示しない
PgFlow：サマリ●○文字以上は「...」表示（省略）

いいと思います！

> 電子書籍の方はシーン単位に改ページとなっておりますので、恐らく短いシーンが連なるようなものでも大丈夫、かなと？^^;

ひー、勘違い失礼しました……！　この仕様であれば大丈夫ですね！

**Comment by snext1220** [comment]
こちらは一応反対意見はなし、緩く賛成戴いたという感じですね（仕様も大雑把には問題なしとのこと、了解です！）。

@olreia さんがこの辺ニーズを持っていそうなので、後日ご意見うかがってみて、仕様をもう少し固めてみたいと思います。

**Comment by snext1220** [comment]
本件、システム対応いたしまして、GitHub Onlyで対応済みです。
サマリテキストのスタイルについては仮なので、こんな表示が良い、などご要望あればお願いいたします。

＃ `<init summary="true">` で有効化できます（マニュアルにも反映済み）。

**Comment by cocotori** [comment]
chromeで確認。
パラグラフレスを選択することで、シーン番号の代わりにサマリーが表示されるようになりました。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で問題ないことを確認しましたー

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 91.0.4472.77(64bit)にて動作確認。
パラグラフレス選択時にシーン番号が非表示になり、サマリーが表示されるのを確認しました。
