### ISSUE TITLE
params属性の追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#238]
従来のフラグに若干似た機能です。
ただし、

```
定義：<switch name="名前" min="0" max="100" initial="0"> 説明 </switch>
利用：<scene switches="s01:10">
```

のように値を変化できるようにします。これによって、値の変化によってシーンを制御したい場合に、複数のフラグを組み合わせなくても済むようになります（内部的に個数無制限で利用できるFreeNだと思っても良いかもしれません）。
＃ 設定値は数値だけでなく、特定の文字列を設定できるようにすれば一寸した変数代わりにも利用できるかなと。

当然、switchの値に応じての分岐も可能にできればと。
結構大きな修正ですが、分岐の実装がかなり簡単化できるようになるはずなので、システムとしては積極的に押していきたいと思います（機能的に不明、不足なものがあれば、ご指摘ください）。

#### 修正案

```
定義：<param id="p99" min="0" max="100" initial="0"> 説明 </param>
利用：<scene params="p01:10,p02:-10,p03:@10">
表示：${var?p01:name}
           ${var?p01:value}
分岐：[ラベル](12 "p01:10")   p01が10以上
　　　[ラベル](12 "!p01:10")   p01が10未満
　　　[ラベル](12 "p01:@10")   p01が10である
　　　[ラベル](12 "!p01:@10")   p01が10でない
```

**Comment by cocotori** [comment]
フラグのようにON/OFFだけでなく、
値の大小で分岐先を変えられる要素ということでしょうか？

ツクールでは変数という、似た要素がありますね。

これがあるとだいぶできることの幅が広がると思うので、賛成です！

**Comment by toki-sor1** [comment]
私自身が内容を把握できているのか不安がありますが（汗）、分岐で複数の条件を組み合わせると、結構ミスが起こり易かったりするので、今よりも簡単に設定できるのは嬉しいですね。

それに、Freeも数が限られているので、そこが解消できるのも良いと思います。
**賛成**です～。

**Comment by Salvadors-cabin** [comment]
制作の幅が広がると思います。
みなさんのご意見に同意です。

**Comment by snext1220** [comment]
ご意見ありがとうございます！
こちらは賛成のご意見も強く、他の用途にも転用できそうなので（将来的には、以前に出ていたサルバさんからのシーンを跨る敵HPもできるようになるのではないかと）、ここから仕様を固めて、実装進めていければと思います。プロトタイプ版を実装しつつ、またご相談させて戴くかもしれませんが、引き続きどうぞよろしくお願いいたします。

> ツクールでは変数という、似た要素がありますね。

はい、まさにそんなイメージです。
別Issueでも出ていますが、シーンを跨って情報を保存しておいて、他のシーンで表示する、というような用途でも利用できるかと思います。

今のところ、以下のような機能までは想定していますが、その他、こんなものにも使いたいかも、などあれば、仰って戴ければ、適宜機能加味していければと思います～

+ 数値、文字列の格納
+ 数値は大小判定、文字列は等価判定
+ 格納された値の本文への表示

**Comment by snext1220** [comment]
本Issueの内容について、先ほど対応し、まずはGitHub OnlyにてUpしております。
ただし、互換性の問題があったため、当初予定していたswitchという名前を改め、paramとしております。
ご了承ください。

Issue先頭でも大まかな仕様をまとめておりますが、詳細はマニュアルの方を確認ください。
https://sorcerian.hateblo.jp/entry/2018/11/01/211745

なお、大規模修正のため、PgFlowへの反映は次回Update以降になります（まずはシステム本体としての機能を安定させたいという趣旨です）。テストに当たってはscenario.xmlを直接編集戴ければ幸いです。

**Comment by snext1220** [comment]
他Bug反映の関係で、本機能も本番リリースしております。
お忙しいところ大変恐縮ですが、まずはご自分のシナなどで影響など出ていないかご確認戴けますと幸いですm(_ _)m

**Comment by cocotori** [comment]
自分のシナリオを中心に、一通り確認しました。
特に問題は出ていなそうです。

**Comment by snext1220** [comment]
ああっと、申し訳ありません。
黒船公開前の投稿がそのままになっていました；
既に機能として完成していますので、新機能のテストとしてお願いできますと幸いです。

＃ 先の投稿は、黒船リリース直前で、テスト前の機能をリリースしてしまった＆システムの根幹に手を入れていたので、まずは最低限既存機能に影響が出ていないかをご確認いただきたいという趣旨でした。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 90.0.4430.93(64bit)にて動作確認。
テストシナリオ＋テストシナリオのscenario.xmlを拝見しながら確認していましたが、正常に動作していました。
ただ、**初期に予めp01が30に設定されていて、それがScene 0で＋10されていることがテストシナリオ内には表記されていなかったため、最初はテストプレイの意図がよく分からなくて混乱していました；**

そのため、例えば「p01の数値が現在のSceneでいくつになっているのか」は、シナリオ制作者側が表記していない場合、テストプレイで正常に動作しているのかが分かりにくいかなと感じました。
**デバッグモード（SceneやItemsが表示されている上部の表示）でp01等の現在値が表示されると、テストプレイもし易いかな**と思いました。

paramがいっぱい設定されている場合は、ちょっと見辛くなりそうですが……。

**Comment by snext1220** [comment]
デバッグモードについては、そもそもItems／Enemies同様に設定できた方が良さそうですね。
こちら別途対応しますので、少々お待ちくださいませ～

テストシナについては、スミマセン、#272 のとおりということでご容赦を...m(_ _)m

**Comment by snext1220** [comment]
param属性について、以下の対応を行いましたので、お手すきの折にもご確認くださいませ～（GitHub Only）

+ デバッグモードにparamsを追加
+ PgFlowに内部パラのグリッド＆入力欄を追加（ただし、サイドバー対応などはまだなので、値は手打ちいただく必要があります）

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 90.0.4430.93(64bit)にて動作確認。
デバッグモードのparamsも正常に表示されていました。
Pg Flowの内部パラに入力した値がデバッグモードでも反映されているのを確認しました。

> なお、本件の対応に合わせて右ペインの縦幅が不足したため、［シーン］タブのボタン類を中央に移動しています。

以前よりも見やすく＆使いやすくなって良いと思います！

**Comment by cocotori** [comment]
chromeで一通り確認しました。
問題なく動作していると思います。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで動作に問題ないことを確認しましたー
