### ISSUE TITLE
【PgFlow】アイテム／フラグ等の自動ソート

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#239]
PgFlowでは、現状シナリオロード時にのみアイテム等の情報をソートしていますが、
これを対応するタブを開いたタイミングで行うように改めようと思っています。
対象は以下。

+ アイテム
+ フラグ
+ 敵
+ 実績

**Comment by cocotori** [comment]
よい機能だと思います！

**Comment by toki-sor1** [comment]
情報が即時に反映されるのは良いと思います～。

**Comment by snext1220** [comment]
ありがとうございます！
では、こちらは改定の方向で進めていきたいと思います～

**Comment by snext1220** [comment]
本件、対応しましてGitHub Onlyでリリース済みです。

仕様が若干変わりました。当初はタブ切り替え時に常に再ソートしていたのですが、無駄なうえに地味にもたついていたので、

+ 行を追加した時
+ idを更新した時

を監視して、その場合のみ再ソートするようにしています。殆どの場合問題ないはずですが、もし再ソートされないパターンなどあればお知らせください（致命的ではないはずですが^^;）。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 90.0.4430.93(64bit)にて動作確認。
アイテム、フラグ、敵、実績の行を追加or各idを変更し、タブを切り替えた時に各項目が正常にソートされていました。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで動作に問題ないことを確認しましたー
