### ISSUE TITLE
「直前のシーンへの戻る」機能

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#24]
RYUさんからのリクエストです。
一元管理のために、勝手ながら、こちらへ移動させていただきました。

> 具体的には「キャッシュから直前のシーン番号を見て、そのシーンへ”進む”ように自動的に設定されるキー」という事です。 巻き戻す的な意味ではないので、素人考えですがあまり問題なくできそうな気がするのですが・・・

**Comment by snext1220** [comment]
現時点では前シーンを記録していないので（いわゆる普通の?［戻る］ではないため、それらの管理はすべてアプリの責務）、内部的な修正は諸々必要となりますが、可能だと思います。

ただ、現在、 #18 などで［戻る］（というか、シーン移動）が問題となっており、それらと絡んでくるため、対応する場合も、そちら解決時（もしくは、その後）とさせていただければm(_ _)m

**Comment by cocotori** [comment]
あくまで今のステータスのまま、
「戻らない」で、直前のシーンに「進む」といった機能でしょうか。

なんとなくバグ等が増えそうですね・・・
どこから来たかはシナリオで管理できるはずなので、
（シーン数は増えてしまうかも）
シナリオ側でやってもらう、というわけにはいかないでしょうか。

例えば代案としてバックログ的なものを実装するとか。
文章だけ、直前のものを参照できるような。

どうしても必要とのことであれば、
実装に反対はないです。

**Comment by toki-sor1** [comment]
私もココさんと同じく、「シナリオ側での制御」が望ましいと考えています。
隠しフラグが削除できるようになったので、例えば、RYUさんのシナリオでマニュアルを
参照したい場合、

　1. マニュアルの参照を必要とするScene1の前にあるScene0で、隠しフラグ「マニュアル1」
　　を取得する設定にする

　2. Scene1に「マニュアル1（隠しフラグ）所持で表示されるマニュアルへのボタン」を設置

　3. マニュアル側に「マニュアル1（隠しフラグ）を所持している場合に表示されるScene1へ
　　戻るボタン」を設置
　　（マニュアルの参照を必要とするSceneが違っていても、『隠しフラグの番号』と
　　　『ボタン表示に必要な隠しフラグの番号』を変更し、ボタンに『マニュアル参照前の
　　　Scene』を設定することで対応可能）

　4. Scene1に戻った後、次に進むScene2に「マニュアル1（隠しフラグ）の削除」を設定する
　（マニュアル側のボタン増殖の防止と正しいSceneに戻れるようにする目的）

上記のような設定なら、内部構造をいじらなくても対応できるのではないでしょうか（要検証）。
マニュアルもメインページのみこういう設定にすれば良さそうですし。

但し、隠しフラグとマニュアル側のボタン設定が大幅に増えてしまう上に、フラグとSceneの
管理がかなり面倒なことになってしまうのですが（汗）。

**Comment by snext1220** [comment]
皆さま、ご意見有難うございます。
本件、基本非実装の方向に傾いておりますが、他Issueで意見がありましたので、一旦、［Expired soon］としてクッション置いた後、（現時点では）［wontfix］としていければと思っています。

**Comment by snext1220** [comment]
［Expired soon］から時間経過しましたが、追加の要望もありませんでしたので、このまま［wontfix］（close）としてまいります。ご意見戴いた皆さま、ありがとうございました。
