### ISSUE TITLE
BattleSheetでの敵へのマイナスダメージ（回復）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#240]
cocoさんより戴いたご指摘に基づくIssueです。

> メインマスト戦で、ダイスの目によってはマイナスダメージとなって相手のHPが回復してしまうのが気になりました。

以前からの問題だったので、ダメージマイナスの時にゼロとなるように修正しました。
ただし、ダメージ式によっては永遠に敵を倒せない場合が出てくるので、実際にはシナリオ側でダメージ値がマイナスにならない（またはなりにくい）ように考慮する必要はありそうです。

**Comment by cocotori** [comment]
確認しました。

計算上マイナスの場合も0になっており、
正しく動作していました！

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 89.0.4389.114(64bit)にて動作確認。
敵のHPがマイナスの場合にも0と表示されるのを確認しました。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeの環境で動作確認し、問題ないことを確認しました。
