### ISSUE TITLE
自由入力欄の入力値を表示

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#242]
現在、自由入力ボックスに入力された値は、正否を判定するのみで次のシーンで確認することはできません。これを次のシーンに引き継いで表示できるようにする機能です。

正しい値はひとつなのでハードコーディングしてもいけると思うのですが、誤った値を表示したい、というケースがあるのかな、と考えています。

**Comment by cocotori** [comment]
今の所わたしの方では使う予定は思いつきませんが、
やるとしたらどんな形になるでしょうね・・・

・次のシーンに引き継ぐとありますが、次の次のシーンにはどうなるか？

個人的にイメージしているのは、シナリオごとに
隠しパラメータとしていくつかの一時変数を持っていて、
シナリオ作者が好きなタイミングで更新、参照できると
今回の用途にも使えるのかなと思いました。

自由入力欄を作る時に、入れられた値をどの一時変数に格納するかを
予め設定しておく、というように。

**Comment by toki-sor1** [comment]
こちらの仕様は、例えばScene 10でクイズを出題して答えを入力。
Scene 11に進むと、引き続き自由入力ボックスが表示されて、その自由入力ボックスの中に入力した答えが表示されている状態、ということでしょうか？

今のところ用途があまり思い浮かびませんが、クイズや謎解き、暗号等が必要なシナリオだと自分の回答が表示されるのは、結構助かる感じがしますね。
（勘違いだったら申し訳ありません；）

**Comment by Salvadors-cabin** [comment]
利用方法で思いつくのは、合言葉を入力した後のシーンでセリフ内にそれが使える、ぐらいでしょうか。
それほど必要性は感じませんので、あれば使えるかも、という感触です。

**Comment by snext1220** [comment]
ご意見ありがとうございます！

> 引き続き自由入力ボックスが表示されて、その自由入力ボックスの中に入力した答えが表示されている状態、ということでしょうか？

いえ、恐らくは${answer}のような形で文中に埋め込むような形になるかと思います。
ということで、

> クイズや謎解き、暗号等が必要なシナリオだと自分の回答が表示される
> 合言葉を入力した後のシーンでセリフ内にそれが使える、

のようなイメージになるのかなと。

> 個人的にイメージしているのは、シナリオごとに
> 隠しパラメータとしていくつかの一時変数を持っていて、
> シナリオ作者が好きなタイミングで更新、参照できると
> 今回の用途にも使えるのかなと思いました。

現時点では次シーンまで引き継ぐだけになりそうです。
ただ、別Issueで出ているswitch属性を利用すれば、ご提案のようなことも可能になりそうです。 似たような機能が併存するのも避けたいですし、汎用性を考えると、switch属性の実装を待った方が良いかもしれませんね。

ということで、こちらは問題なければ一旦wontfixとしていきたいと思います（switch属性安定後にコッソリ実装するかも、という程度で^^;）
