### ISSUE TITLE
ダイスの種類／個数を変更可能に

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#243]
タイトルの通りです。現在は6面ダイス×2で固定でしたが、以下のようなカスタマイズを可能にできないかと考えています。

+ 個数を1～5で可変に
+ 種類のバリエーション（1と6だけダイス、4・5・6ダイスなど。アイデア募集）

これまでは計算式で値の大小を調整するしかできませんでしたが、ダイスの種類を変更できれば、確率の調整を表現できるかと期待しています。

これらの情報はシーン単位にdicetype属性で指定できるようにする予定です。

**Comment by Salvadors-cabin** [comment]
>個数を1～5で可変に

ダイス１個の判定もあるのでこれは賛成です。

>種類のバリエーション（1と6だけダイス、4・5・6ダイスなど。アイデア募集）

TRPGでありましたね、４面や８面のダイス。
今のところ予定はありませんが、TRPG風の演出に使えるかもです。

**Comment by cocotori** [comment]
ダイスの個数を変更できるのは賛成です！

出目についてはそうですね、TRPGはあまり詳しくありませんが
100面ダイスとか用意できると面白いかもです。
（1D100？）

こういうのってシーンごとに変更できるものなのでしょうかね・・・
シーンに応じていろんなダイスを使いたいものだと思いますが、
シナリオ固定じゃないとシステム的には難しいのかな、とも。

あと、個人的には出目の確率をいじれると演出として面白いかなと思いました。
1～6が同確率ではなく、4,5,6が倍とか、4,5,6しか出ないとか。
イカサマアイテムを使った後の演出として使えそうです。

**Comment by toki-sor1** [comment]
> 個数を1～5で可変に

これは色々と用途があって良さそうですね。賛成です！

> 種類のバリエーション（1と6だけダイス、4・5・6ダイスなど。アイデア募集）

賛成です！
皆さんも仰っていますが、TRPGでも特殊なダイスがあるので、ここをカバーできるとゲームブックとTRPGの融合みたいな感じになって面白そうですねｗ

そこで調べてみたのですが、例えばクトゥルフ神話TRPGで100までの値で判定したい場合は、10面ダイス×2個で決めることもあるようです。
画像の用意という観点からだと、10面ダイス×2個の方が画像枚数が少なくて済むのかなと思いました。
【参照】http://amida-trpgblog.hatenablog.com/entry/2016/10/07/215207
【参照】https://cthuwebdice.com/dice/

> あと、個人的には出目の確率をいじれると演出として面白いかなと思いました。

こちらもいいですね！
女神の加護（悪魔の呪い）によりプレイヤーの運が良くなっている（悪くなっている）演出なんかもできそうですｗ

**Comment by snext1220** [comment]
ご意見ありがとうございます！
概ねご賛同戴いたという認識で、ここからは詳細の仕様を詰めていきたいと思います。
＃ 実は、結構影響の大きな機能なので、仕様伺いつつ、できるものから実装していければと。

#### ダイスの種類

こちらは、TRPGに沿うならば、以下のようなものでしょうか。

+ d4
+ d6
+ d8
+ d10
+ d20
+ d100

画像を考えると、d100が確かに悩ましいですね...
後述の理由で2個に分けたくないということもあり、まずはニーズ次第でしょうか。
＃ TRPGでは0～100のパラメーターを生成したり、大小判定するための用途が多いように思えますが…

#### 出目の確率

こちらはあらかじめパターンを用意しておくのが、システム的には対応し易そうです。
たとえば、
d8ダイスに対して1、2、3、4、5、6、6、6のように割り当てておけば
6が出やすいダイスになります。

シナリオファイル内で、以下のようにdice定義させることも可能ですが、どうしましょうか（ある程度パターンを決められるならば、その方が作成者的にも楽そう）

`<dice name="hoge" pattern="4,5,6" />`

#### シナリオごと、シーンごと

こちらは確かにシーンごとにできないと、用途が狭まってしまいそうですね^^;
以下のようにdice設定できるようにしたいと思います。

`<scene dice="d6">`

#### ダイスの個数

現時点でも1～2個での判定は可能ですが、3個以上の判定ニーズありますでしょうか。
こちらは戦闘のダメージ式にも影響が出そうだったので（※）、積極的なニーズがなければ表示上は2（必要であればせめて3）個固定としていければと。 ＃ もちろん、ニーズあれば検討いたします～

（※）ダメージ式でL、Rという表記を使っているので、4個以上にした場合、互換性が保ちにくい。3個まではM（Middle）を追加すれば対応できます。4個以上はA、B、C、D、E（左から順に～）などの新たな表記ルールを設ける必要があります。

#### 余談（クトゥルフ神話）

全くの偶然なのですが、先日、息子が新クトゥルフ神話TRPGルールブックを買い込んできました（決して私がそそのかしたわけではありませんｗ）。まだルールブックも読めてないのですが、ＧＷは家族で1セッションこなす予定です。
というわけで、まさにダイスなど触っていたところでした^^;

**Comment by snext1220** [comment]
現在、以下の仕様で一部の実装を進めています。

#### ダイスの種類

+ d4
+ d6
+ d8
+ d10
+ d20

画像は未対応。d100は保留中

#### 出目の確率

あらかじめ以下のパターンを準備。ご要望あれば引き続きお願いします。

+ 'high' : [4, 5, 6],
+ 'cheat_l': [1, 1, 1, 2, 3, 4, 5, 6],
+ 'cheat_h': [1, 2, 3, 4, 5, 6, 6, 6],

#### シーン単位

`<scene dice="d6">`（未実装）

#### ダイスの個数

2～5の可変を可能にする。
ダメージ式での指定は、以下の通り。

+ 2：L、R
+ 3：L、M、R
+ 4：L、ML、MR、R
+ 5：L、ML、M、MR、R

問題なければBattle Sheetでの実装を進めていければと思います～

**Comment by snext1220** [comment]
@toki-sor1 さん：
ダイス画像を戴き、ありがとうございます！
まさにTRPGなダイスで雰囲気満点ですね！！

ただ、申し訳ございません（汗）、内容面で少々ご相談させてくださいませ。

+ 現在、システム的には理論上、d3、d13なども可能ですが、今回戴いたようにタイプ別にわけるとなると、設定はd4、d6、d8、d10に限定ということになるかと思います。
+ 同様の理由で、特殊確率のダイスはd6前提となるかと思います。
+ （細かい点ですが）d10の10は「0」でなく「10」の方が良い？（手元のダイスがどうなっているかは、息子が戻ってこないと不明なのですが；）
+ d20、d100はなしで大丈夫でしょうか（個人的には不要だと思いますが、念のため）

もしシステム上の自由度を維持するならば、単に1～10（10上限の場合）の画像10枚を用意する方が良いかもしれません。
逆に、現在のように画像が明確に分かれていた方が、ダイスの種類は見た目にも明快なので、、、悩ましい^^;

**Comment by toki-sor1** [comment]
早速ご確認いただき、ご意見もありがとうございます～！

> 現在、システム的には理論上、d3、d13なども可能ですが、今回戴いたようにタイプ別にわけるとなると、設定はd4、d6、d8、d10に限定ということになるかと思います。

d3は、6面ダイスの1～3までで代用可能ですね。
d13は例としてのお話だと思いますが、設定上では可能ということで、切り離して考えても大丈夫かなと思います。

> 同様の理由で、特殊確率のダイスはd6前提となるかと思います。

はい、基本は6dメインだと思いますので、特殊確率は6d限定でも良いかなと思います。

> （細かい点ですが）d10の10は「0」でなく「10」の方が良い？（追記：恐らくリアルのd10はd100の一の位を表す関係で0表記になっているかと思うのですが、ゲーム画面上では10は10と表した方が判りやすいかなと思われました）

確かに、d10の「0」は、d10のみの運用だとややこしいと思います。
ただ、ご指摘の通りd100として運用する際には「0」の方が分かり易いので、どちらかというと「0推し」です。

> d20、d100はなしで？（個人的には不要だと思いますが、念のため）

d20は素で忘れていました……；
d100は、上記のd10x2回で代用可能なので、設定可能だと思います。

しかし、ダイスの種類ごとに数字分の画像を作成すると、それだけでファイルが多くなってしまうのが個人的にも気になっていましたし、d20が作れる気がしないので中途半端な実装にもなってしまいそうな気がします；

そうですね、種類ごとのダイスの形にこだわらず、d6を1～10の数字に置き換えた6d以外で使えるダイス画像（ただしd6と区別するために色を変える）が良いのかもしれません。

**Comment by snext1220** [comment]
お返事ありがとうございます～
了解の箇所を割愛しつつ、以下お返事していきますね。

> d3は、6面ダイスの1～3までで代用可能ですね。

あ、スミマセン、こちらは言葉足らずでした；
仰る通り、上限値以上のダイスを使うということであれば、問題ないと思います～ただ、一見カラーで分けているように見えるのに（たとえば）d3とd6は同じ、d4は別というのも混乱しそうかなと思いまして。であれば、実用上はダイス種類を限定した方が良いと考えた次第でした^^;

> d13は例としてのお話だと思いますが、設定上では可能ということで、切り離して考えても大丈夫かなと思います。

はい～恐らく利用するダイスは限られるのかなと思うので、私もd4、6、8、10があれば十分かなと^^;

> d100は、上記のd10x2回で代用可能なので、設定可能だと思います。

こちらは自動計算の関係で不要であれば避けておきたい、ですかね～^^;（スミマセン）
d100ではダイスは2個に固定して、L、Rをそれぞれ演算して合算したものを反映、という感じになり、（もちろんできなくはないのですが）、制限がある割にぱっと見の見た目が判り難いかなと。
＃ あとは先の理由でTRPGでは0～100範囲のパラメーターに対しての判定で利用することが多いように思えるので、STextではあまり使わない、かも？

> そうですね、種類ごとのダイスの形にこだわらず、d6を1～10の数字に置き換えた6d以外で使えるダイス画像（ただしd6と区別するために色を変える）が良いのかもしれません。
> それとも、「今まで使っていたd6を全て数字に置き換える」というご意見だったのでしょうか？（ご意図を読み間違えていましたら申し訳ありません；；）

言葉足らずですみません；
個人的には1～10までは★ベースの画像、11以上は数値ベースの画像で拡張するが現実的かなと思っておりました（であれば、20くらいまではありかなと考えたもので）。
ただ、ときのじさんの画像を拝見して、ダイスの種類で明確に画像を区別できるのも魅力的だなと。

ということで、個人的には現時点では以下の意見でございます。

+ ダイスの種類はd4、6、8、10に制限
+ カスタムはd6ベースのみ
+ 画像は現在作成戴いたもので進める （d100はやらない前提で10の表記は「10」）

利用するダイスの種類も限定できそうですし、見分けも付きやすく、ときのじさんの手戻りもないかな～と。如何でしょうか？（今後、さらに拡張しようとするとネックになる可能性があるのだけがデメリットかと）

お手数をおかけしますが、引き続きご意見頂ければ幸いです～

**Comment by toki-sor1** [comment]
お忙しいところお返事ありがとうございます！

> 仰る通り、上限値以上のダイスを使うということであれば、問題ないと思います～ただ、一見カラーで分けているように見えるのに（たとえば）d3とd6は同じ、d4は別というのも混乱しそうかなと思いまして。

いえいえ、こちらこそ所々しっかりとご意図を把握できておらず、申し訳ありません；；
こちらの件は、ダイスの出目が1～3までと表記されていればカバーはできそうではあるものの、ぱっと見て「d6なのに1～3までしか出ない？」と混乱してしまうのはありそうですね；

> はい～恐らく利用するダイスは限られるのかなと思うので、私もd4、6、8、10があれば十分かなと^^;

TRPGによってはd20も使われる頻度が高いようですが、STextであれば今のところはd4、6、8、10で十分そうな感じはしますよね。

> d100ではダイスは2個に固定して、L、Rをそれぞれ演算して合算したものを反映、という感じになり、（もちろんできなくはないのですが）、制限がある割にぱっと見の見た目が判り難いかなと。

なるほど、今のところどうしてもd100が使いたいというご要望もないですし、自動計算で問題が生じるようであれば、無理やりに実装しない方が良さそうですね。

> 1～10までは★ベースの画像、11以上は数値ベースの画像で拡張する

こちら、7～10まで★で表現すると非常に見辛いと思います；
個人的には、1～20全てを数字に表記した方が見易い＆バランスが取れていると思うのですが、いかがでしょうか？

> 想定範囲内であれば利用するダイスの種類も限定できそうですし、見ための区別も付きやすく、ときのじさんの手戻りもないかな～と。如何でしょうか？（今後、さらに拡張しようとするとネックになる可能性があるのだけがデメリットかと）

ううっ、ご配慮ありがとうございます；；
しかし、今後のデメリットを考えると**やはり画像はd6ベースで1～20の数字を入れた画像が最も利用し易いと思います～。**
そのため、今回作成したダイス画像については、サイトの顔グラ置場と一緒にフリー素材として置くのも有りだと思いますｗ

**Comment by snext1220** [comment]
@toki-sor1 さん：
こちらこそご配慮ありがとうございます～
了解です！
私としては元々想定していた仕様に近い形になるので、異論ございません～
改めて以下に仕様をまとめてみました。

+ ダイスの出目は20を上限にして自由に設定可
+ d6以下の場合は従来のダイス画像を利用
     + d6を利用するケースがほとんどと思われ、その場合は（数字よりも）★ベースの画像が一般的と思われるため
+ d7～20の場合は新規画像を利用（現在のd6ダイスのデザインをベースに、1～20の数値を入れたものをご用意いただく）
+ カスタムダイスも1～20の範囲内で自由に設定可能

宜しくご検討くださいませ～

**Comment by toki-sor1** [comment]
ご検討いただき、また、おまとめありがとうございました～！
仕様も全て異論ございませんです～！
では、d6ベースで1～20の数字を入れた画像を作成しましたら、O/Dにアップした上でこちらにてお知らせいたしますね。

おっと、1つだけ質問よろしいでしょうか？；；
「★ベースの1～6ダイス（従来のもの）」と「数字ベースの1～20のダイス（新規）」のファイル名は、それぞれいかがいたしましょう？

**Comment by snext1220** [comment]
ご了解有難うございます！
ファイル名は以下の通りでお願いできますでしょうか。

従来：cube1.png～cube6.png
数値ベースのもの：cube_num1.png～cube_num20.png

/stext/common/cubeフォルダーを新設致しましたので、こちらに保存いただければ幸いです。

お手数をおかけしまして申し訳ございませんが、どうぞよろしくお願いいたします～
こちらも今回の仕様に基づいて、コード修正してまいりますね。

**Comment by toki-sor1** [comment]
ご返答ありがとうございました！
フォルダーの新設＆コード修正も助かりました！
先程cube_num1.png～cube_num20.pngをご指定のフォルダにアップいたしましたが、問題等ありましたら申し訳ありませんが、声を掛けていただきましたら助かります～；
（サンプルは12までですが、20までアップ済みです）
![image](https://user-images.githubusercontent.com/42646342/116779606-51e82100-aab2-11eb-806a-712518932c99.png)

**Comment by snext1220** [comment]
@toki-sor1 さん：
早速ありがとうございます～
こちらも戴いた画像をもとにコード反映しております。

動作テストの方、どうぞよろしくお願いいたします～＞皆さま

**Comment by toki-sor1** [comment]
お忙しいところご対応いただきありがとうございました！
動作テストを行おうと思ったのですが、シーン単位での指定方法は「<scene dice="6:4">」、ダメージ式では「5：L」のような表記で良かったでしょうか？

Pg Flowではシーン単位でのダイス個数を指定ができなかったため、手動で指定してみましたが、こちらの勘違いでどうにも上手くいかないようです；；（テストシナリオもダイスの数が元のd6x2個に戻っているようでした）
申し訳ありませんが、お手隙の際にご教示のほどよろしくお願いいたします；；

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！

dice属性はご認識の通りでOKです～
ダメージ式は他の指定と同じく「L+2LM+M+RM+R-STR」のような形でお願いいたします。
詳しくは https://sorcerian.hateblo.jp/entry/2018/11/01/211745 から
enemy要素のfunc属性、scene要素のdice属性を参照くださいませ。

> テストシナリオもダイスの数が元のd6x2個に戻っているようでした

こちらは先ほどd8x5個にしてみましたので、ご参考にしてみてください。
＃ params属性もですが、大きな修正のため、PgFlowへの反映はシステム本体に問題がないこと確認の後になるかと；恐縮ですが、当面はscenario.xmlの直接更新をお願いできますと幸いですm(_ _)m

**Comment by toki-sor1** [comment]
指定例をまじえたとても丁寧なご解説、本当にありがとうございました！
先程は指定ミスと確認不足が原因でお騒がせしてしまい、申し訳ありません；；
今度はシーン単位＆ダメージ式でも無事に指定でき、正常に動作しました……！

> params属性もですが、大きな修正のため、PgFlowへの反映はシステム本体に問題がないこと確認の後になるかと；恐縮ですが、当面はscenario.xmlの直接更新をお願いできますと幸いですm(_ _)m
＃ PgFlowへの反映は #191 にて管理／報告いたしますね。

おぉお……早とちり大変失礼いたしました；；
PgFlowへの反映タイミング＆管理と報告についても承知しました！
大きな修正で作業量もかなりの量だと思うのですが、よ、よろしくお願いいたします～……！

**Comment by snext1220** [comment]
いえいえ、新機能ですと、不具合もあり、ドキュメントも十分でなしでお手数をおかけします^^;
おかげさまでダイスも見た目良い感じになりました。こちらこそありがとうございます～

PgFlow＞システム安定しないと、開発ツールも手戻りが多くなってしまうもので、お待たせしております；params、diceは目玉機能ですし、ここから幕末でゲストの皆さんも使われるので、なるべく早く実装できればと思います～

**Comment by cocotori** [comment]
chromeで確認しました。
一通り問題なく動いていそうです。

一点、LMを間違えてMLと入力してしまうと、
計算式がおかしくなってしまいました。
（MとLを足した値になる？）
間違えやすいので、何かしらの機能で防げたらいいのですが。
けれどMもLも使う文字ですし、
難しいようならこのままでも大丈夫だと思います。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

> 間違えやすいので、何かしらの機能で防げたらいいのですが。

こちらML、MRを強制的にLM、RMに変換する機能を設けようかと思ったのですが、記述が不統一になるのも良くないですし、PgFlow側にML、MRをエラーにする機能を追加しました（GitHub Only）。如何でしょうか？

**Comment by toki-sor1** [comment]
> こちらML、MRを強制的にLM、RMに変換する機能を設けようかと思ったのですが、記述が不統一になるのも良くないですし、PgFlow側にML、MRをエラーにする機能を追加しました（GitHub Only）。如何でしょうか？

Win 8.1／Chrome 90.0.4430.93(64bit)にて動作確認。
MLやMRにするとエラーが表示されました。ちょっとややこしいのでエラー表示助かります！

**Comment by Salvadors-cabin** [comment]
Win10+EdgeのGitHUB環境で動作に問題ないことを確認しましたー
