### ISSUE TITLE
［戻る］ボタンの実装

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#244]
現時点では、複数シーンで共有するヘルプ的なシーンを実装する場合、以下のような方策をとる必要がありました。

+ ブラウザーの［戻る］ボタンに頼る
+ リンク元単位に同内容のシーンを実装する

本Issueでは、STextネイティブに「前のシーン」に戻る機能を実装できればと考えています。
リンク元に限らず、前のシーンに戻る、という意味です。
実装方法は未定ですが、場合によっては経過シーンにはカウント**されない**実装になるかもしれませんが、この辺の仕様含めて、まずは要否をご意見いただければ幸いです。

**Comment by snext1220** [comment]
本機能ですが、新シナリオでも必要になるため、β扱いではありますが、一旦実装してみました（GitHub Only）。

+ 90000のリンクをbackボタンとして認識
+ ブラウザーのbackボタンと同様のため、経過シーンはカウントされない
+ リンク先から更に分岐する場合はすべてをback扱いにしないといけない（どこから飛んできたかという情報をブラウザー履歴以外からは取得できないため）
+ リンク先でフラグ／アイテムなどは取得できない（実績だけは例外的に可能）

かなり限定的な機能にはなりますが、ヘルプ的なコンテンツであれば、まずは十分に要件を満たすであろうと判断しています。如何なものでしょうか。

**Comment by toki-sor1** [comment]
実装お疲れ様です！
サイドバーに説明などを表示させるには限界があったため、良い機能だと思います！
説明をちょこちょこ確認したい時もあるので、シーンがカウントされないのも助かりますね。

Win 8.1／Chrome 88.0.4324.150(64bit)にて動作確認。
申し訳ありません、どのように設定すれば良いのかよく把握できておらず、GitHub版のPgFlowでbackボタンを設定＆表示させることができませんでした；
リンクのみで90000に設定することができないため、まずはScene 90000を作ってリンクを設定してみたのですが、普通にScene 90000に飛んでしまうので、これは設定方法を間違えていそうだなと思い…；

お忙しいところ大変恐縮ですが、設定方法を教えていただけましたら助かります；；

**Comment by snext1220** [comment]
お忙しいところ早速のご確認ありがとうございます！
そして、スミマセン、変更コードがGitHubにきちんと反映されておりませんでした...（先ほどプッシュ致しました；）設定方法自体は問題ありませんので、今一度お試し戴けますと幸いですm(_ _)m

シーンカウントされない、など仕様へのご賛同もありがとうございます！
引き続きPgFlowからの入力UIなど、ご意見頂きながらブラッシュアップしていければと思いますので、お気づきの点あればどうぞよろしくお願いいたします～

**Comment by toki-sor1** [comment]
おおっと、そうでしたか！　ご対応ありがとうございました！（どんまいです～！）

Win 8.1／Chrome 88.0.4324.150(64bit)にて動作確認。
GitHub版Pg Flowにて教えていただいた方法でテストを行い、backボタンの表示＆シーンのカウントがされないことを確認しました！

追記も確認しました！
なるほど～、シナリオのプレイを中断する際には気をつけないとですね～。
（back先のシーンに注意書きがあると親切な感じがしますね）

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！（お手数をおかけしました...）
まずは現在の仕様にて問題ないとのことよかったです～

> なるほど～、シナリオのプレイを中断する際には気をつけないとですね～。
>（back先のシーンに注意書きがあると親切な感じがしますね）

はい～、現在ブラウザーバックの機能を前提にしているシナ（双王やドラスレ？）はなんらかの注意書きを書かれていたと思いますが、その辺は変わらずになるかと思います。
ただ、（開発者ではなく）プレイヤーに対する制約なので、ホントは解消できれば良いなぁなどと（#238 などでリンク元を記録できるようになれば解決できるかも）^^;
あまり複雑なしくみになってしまうのも良くないですが、他Issueとも絡めながらより使いやすい形にしていければと思っています～ゆるゆるご意見頂ければ幸いです！

＃ そんな訳で本機能は当面はβ版（Experimental？）な扱いになっていくかもしれません～

**Comment by toki-sor1** [comment]
大変遅くなってしまい申し訳ありません…！　お返事ありがとうございました…！
そうですね、可能であればシナリオを中断するSceneやタイミングを気にせずプレイできた方が快適ですもんね。

シナリオプレイ中にルールが参照し易くなれば、それだけ様々なシナリオが作りやすくなります。
今後問題が解消できたら良いですね～。

**Comment by snext1220** [comment]
問題、については、別Issueでも出ているswitch属性を併用することで、戻る場所を記憶しておく、などもできるかな～と漠然と^^;思っております。一個一個解決していければと思っていますので、気軽に見守ってやってください～
