### ISSUE TITLE
ドラゴンモードの解放解除

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#246]
全体的なシナリオビューを見ていると、新旧それなりに読まれているのですが、ドラゴンモードだけが微妙に穴になっているように見えます。

ある程度公開から時間も経過していることから＆再度盛り上げの意味も込めて、ドラゴンモードのシナリオを遊ぶための実績条件を除去し、普通に遊べるようにするのもありかな、と考えているのですが、如何でしょうか。

以下のような論点があるかと思いますが、ご意見いただければ幸いです（勿論、それ以外でも）。

+ 一時的か、恒久的にか
+ 最終シナ「双王～」をどうするか（ここだけは残さないと、シナの意味が通りにくい？もちろん、割り切りもありとは）
+ 一時的な場合、シナリオを修正するかシステム的に対応するか

**Comment by toki-sor1** [comment]
ドラゴンモードのスタート前から懸念されていた部分ですね。
当時は原作再現で各シナリオでの実績取得がプレイ条件となっていましたが、仰る通り時期的にも実績条件を解除しても良いかなと思います。
実績による解除が足枷になり、興味はあるけどシナリオがプレイできない状況というのは、やっぱり勿体ないですもんね。
（過去にちゃなさんのSText実績が消えて再取得するというトラブルに見舞われていらっしゃいましたし、私も端末によっては実績が消えて実績再取得orリストアすることが何度かあったので）

> 一時的か、恒久的にか

**恒久的**に一票です。
ただ、**順番通りにシナリオをプレイしたからこそ通じるネタもある**ので、シナリオ解放条件を「当シナリオ開始前にプレイ推奨のシナリオ」等に変更した注意書きは必要だと思います。

> 最終シナ「双王～」をどうするか（ここだけは残さないと、シナの意味が通りにくい？もちろん、割り切りもありとは）

**「双王～」もどのタイミングでも遊べる** のが良いですね。
こちらに関しても、シナリオ解放条件を「このシナリオを開始する前にプレイ推奨のシナリオ」等に変更した注意書きは必要だと思います。

> 一時的な場合、シナリオを修正するかシステム的に対応するか

恒久的な公開が良いなと思っているのと、注意書きの変更も必要だと考えているので、（執筆者様には大変お手数をお掛けしてしまい恐縮なのですが） **シナリオを修正した方が良い**と思います。

記述はこんな感じかなと考えてみましたが、如何でしょうか？（修正大歓迎です！）

【記述例】
　※ドラゴンモードシナリオは、既存シナリオの設定が含まれています。
　　このシナリオをプレイする前に、
　　Scenario 1「新・消えた王様の杖」の実績**「オタクの称号」**
　　Scenario 10「魂の選択」の実績**「ありがと！」**
　　の取得を推奨しております（必須ではありません）。

**Comment by Salvadors-cabin** [comment]
>一時的か、恒久的にか

やるなら恒久的に一票です。

>最終シナ「双王～」をどうするか（ここだけは残さないと、シナの意味が通りにくい？もちろん、割り切りもありとは）

もともとドラゴンモードはときのじさんの力で実現した企画だったのでこの件はお任せします！

**Comment by snext1220** [comment]
こちらは、特に大きな反対もないようなので、以下のように決めたいと思います。

+ ドラモードの実績解除条件を、恒久的に解除する（「双王～」も同様）
+ 恒久的ということで、シナリオ側の修正とする（システム対応は行わない）

> 【記述例】
> 　※ドラゴンモードシナリオは、既存シナリオの設定が含まれています。
> 　　このシナリオをプレイする前に、
> 　　Scenario 1「新・消えた王様の杖」の実績**「オタクの称号」**
> 　　Scenario 10「魂の選択」の実績**「ありがと！」**
> 　　の取得を推奨しております（必須ではありません）。

上記の記述について、ご提案ありがとうございます。
ただ、入れるべきかは少々悩んでおりまして；；
というのも、ほとんどのシナの内容が実績シナのネタについては軽く触れている程度で、あえて明記するほどではないかなと思いまして（勿論、双王だけは別格かと）。もちろん入れたいというシナは入れても良いと思うのですが、その程度の扱いでは如何でしょうか。

上記で問題なければ、お手数ですが、 @Salvadors-cabin さんの方で各執筆者さまに注記を入れるかどうかのみ確認いただいて、シナリオそのものはスタッフ内部で修正という形かなと。

**Comment by cocotori** [comment]
すみません、見落としていました。

実績取得によるシナリオ解放はスタンプラリー的な、
お祭りにも通じる企画だったかと思います。

企画が一段落した今となっては、
恒久的な解除に、わたしも賛成です。

>【記述例】
>　※ドラゴンモードシナリオは、既存シナリオの設定が含まれています。
>　　このシナリオをプレイする前に、
>　　Scenario 1「新・消えた王様の杖」の実績**「オタクの称号」**
>　　Scenario 10「魂の選択」の実績**「ありがと！」**
>　　の取得を推奨しております（必須ではありません）。

こちらの注意書きは、個人的にはあったほうがいいと思います。
多かれ少なかれ引き継ぎ元のシナリオの設定を使って作るという経緯があった以上、
文言までなくなってしまうと繋がりが途絶えてしまう気がしてしまいまして。

けれど、無理に入れなくてもいいというのもわかりますので、
どちらでも構いません。

**Comment by toki-sor1** [comment]
ご意見＆ご提案ありがとうございます。

- ドラモードの実績解除条件を、恒久的に解除する（「双王～」も同様）
- 恒久的ということで、シナリオ側の修正とする（システム対応は行わない）

上記は決定でしょうか。

注意書きについては意見が分かれるところですね。
ただ、私の個人的な意見「順番通りにシナリオをプレイしたからこそ通じるネタもある」と、ココさんが仰っている「引き継ぎ元のシナリオとの繋がり」を考えて、注意書きは入れておきたい派です。

一つ提案なのですが**シナリオ内の注意書きは「双王」含めて全ドラモシナリオで消して、サイドバーのシナリオ紹介にある注意書きを記述例のように修正して残す**というのは如何でしょうか？

**Comment by snext1220** [comment]
ご意見ありがとうございます～

> 上記は決定でしょうか。

はい、こちらは皆さん賛成のようなので、決定ということで。

> 追記：サイドバーに残す場合は、もう少しシンプルな記述が良いでしょうか。

はい、賛成です！
個人的には、物語の雰囲気を損なわないという意味で、極力、本文の説明的記述は外せれば、というスタンスだったので^^;、サイドバーに移るのは歓迎です。また、実績解放外したことで、取得実績を明示する意味はなくなっていたので、サイドバーに移す場合にもご提案程度のコメントがベターかと思います。
＃ あえていえば、「このシナリオには、Scenario 2「ゼロの創造」の設定が含まれています。あらかじめプレイしておくと、本シナリオをより楽しめます」程度で如何でしょうか。

問題なければ、これにて @Salvadors-cabin さんに各ご執筆者さまに御確認頂き、シナリオ修正（ゲストさま担当分）は私が、stext.xmlは @toki-sor1 さん修正する、で如何でしょうか（スタッフ担当分は各人にて）。

**Comment by toki-sor1** [comment]
おまとめありがとうございます！
サイドバー案について、落としどころがついた感じになって良かったです！

> ＃ あえていえば、「このシナリオには、Scenario 2「ゼロの創造」の設定が含まれています。あらかじめプレイしておくと、本シナリオをより楽しめます」程度で如何でしょうか。

補足ありがたいです！　**注意書きは、こちらの方が良いですね！**

> 問題なければ、これにて @Salvadors-cabin さんに各ご執筆者さまに御確認頂き、シナリオ修正（ゲストさま担当分）は私が、stext.xmlは @toki-sor1 さん修正する、で如何でしょうか（スタッフ担当分は各人にて）。

はい、異論ありません！
各関係者様からのお返事を確認し次第、ゲスト様分＋自作シナリオのstext.xmlをこちらで修正しますね。
お手数をお掛けしてしまい恐縮ですが、皆様よろしくお願いいたします……！

**Comment by cocotori** [comment]
わたしの方は、サイドバー案で問題ありません！

**Comment by Salvadors-cabin** [comment]
了解です。
ゲスト執筆者様（山田さん、咲華さん、ちゃなさん）に連絡しますので少々お待ちくださいー。

**Comment by snext1220** [comment]
お忙しい処お手数をおかけします；どうぞよろしくお願いいたします～

**Comment by Salvadors-cabin** [comment]
お疲れ様です！
ゲスト執筆者様（山田さん、咲華さん、ちゃなさん）からお返事があり、みなさまご了承を頂きましたー。

**Comment by snext1220** [comment]
@Salvadors-cabin さん：
お忙しい処、ご連絡ありがとうございます！了解いたしました～

皆さん：
ゲストさん作品（gold、traitor、requiem）について先ほどscenario.xml修正済みです。
お手数ですが、ご担当作品についてガードの解除をお願いいたします。

@toki-sor1 さん：
お手数ですが、stext.xmlの表記修正をお願いできますと幸いですm(_ _)m

**Comment by toki-sor1** [comment]
皆さん、ご確認や修正作業等お疲れ様です＆ありがとうございます！
先ほどGitHub、本番環境ともに更新しました。詳細は、下記の通りです。

- stext.xml
  - ゲスト様作品（gold、traitor、requiem）シナリオ紹介ページの表記修正（流儀、レクイエム、金竜）
  - ときのじ作品（shadow、king）シナリオ紹介ページの表記修正
- ときのじシナリオ（shadow、king）のscenario.xml修正

修正方法等に問題がありましたら、ご面倒をお掛けしてしまい大変恐縮ですがお知らせください；

……と、投稿前に今気付いたのですが、皆様の修正が完了してからのstext.xmlの表記修正でしたね……！
確認不足によるフライング修正申し訳ありません……！　戻してきます……！！

**Comment by snext1220** [comment]
@toki-sor1 さん：
早速ありがとうございます！
フライング＞いえいえ、こちらこそ追記で失礼致しました；
あとからまたご反映も大変ですし、以下版で反映戴いても大丈夫かなと、と、と。
https://github.com/snext1220/stext/commit/aabdbe0c0eabb62f81b1cd9b5342be67de2c11d8

**Comment by toki-sor1** [comment]
ひ～……！　お騒がせして申し訳ありません……！
ご寛大なお言葉ありがとうございます！！
あれから変更を戻していたのですが、先ほどGitHubは変更の取り消しを行い（修正版に戻しました）、本番環境にも修正版を再アップいたしました～；

**Comment by Salvadors-cabin** [comment]
先ほど「ドラゴンネゴシエイター」の修正版をアップし、解放条件を解除しました。
よろしくお願いしますー

**Comment by cocotori** [comment]
時を越えた協力者、シナリオの更新とstext.xmlの更新が完了しました。

**Comment by snext1220** [comment]
皆さま、ご対応ありがとうございます！
拝見しまして、以下の修正を行いました。

+ 修正戴いた文言の表記ゆれを全体的に見直し（細かい表記だけで文意は変えていません）
+ ネゴシエーターについてstexl.xmlの修正
+ 今回の件とは関係ありませんが、新シナリオページの仕様変更に合わせてupdated属性の抜けていたシナについてpublished属性と同じ値を入力（今後は未入力の項目は正しく表示されなくなるのでご注意ください）

これでドラモード全ての対応が完了したと思うので、5/10夜間にもドラモード解放の告知を行おうと思っております。どうぞよろしくお願いいたします！

**Comment by Salvadors-cabin** [comment]
「ドラゴンネゴシエイター」のstexl.xml修正ありがとうございます。
こちらのUpdated日も更新しておきましたー

**Comment by snext1220** [comment]
Updated忘れ、失礼致しました＆修正ありがとうございます～
