### ISSUE TITLE
シナリオ分類の整理

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#247]
Ｄでも話題になった件です。

ミドル100（旧Pg100）、ロング200overを新設（リネーム）し、現在不適当な分類となっているシナを整理できればと思っております。ついては、以下の点についてご意見頂ければ幸いです。

+ ミドル、ロング～の名称
+ 再整理対象のシナ（以下以外にあれば）
    + アベンジャーズ、カードバトル、日の光、ドラスレ（開幕シナなのでママでも？）

### 追記（覚書）

シナリオレベルについても1～5の基準を明示

**Comment by toki-sor1** [comment]
Issue立てありがとうございます！

> ミドル、ロング～の名称

分かり易さ重視であれば、ご提案いただいた**ミドル100（旧Pg100）、ロング200over**が良いかなと思いました。

ただ、パラグラフ数がミドルというよりもミニミニなシナリオもあります。
現在だとPg Flowを使っているのが分類の条件になっているのですが、そこに以前からあるミニミニ30を加えると、説明の修正が難しいでしょうか……？

> 再整理対象のシナ（以下以外にあれば）

【再整理】アベンジャーズ（ロング）、カードバトル（ロング）、日の光（ミニorミドル）
※ドラスレは、仰る通り開幕シナリオなのでそのままかなと思っています。

> シナリオレベルについても1～5の基準を明示

うーん、パラグラフ数が必ずしも難易度に直結している訳ではないので、そこがまた悩ましいですよね；
そこを排除して考えると、難易度の判断は「クリアまでの経過Scene数の多さ」「戦闘回数の多さ（battleSheet対象外の戦闘も含む）」「ボスキャラの強さ」「独自ルールの複雑さ」「謎解きの多さ」辺りが深く関わっていそうな気がします。

そう考えると、例えば「少女英雄」の場合、5段階評価で
- クリアまでの経過Scene数：やや多い(4)
- 戦闘回数：多い(5)
- ボスキャラの強さ：やや強い(4)
- 独自ルールの複雑さ：複雑(5)
- 謎解き：普通(3)

となるので、合計21点÷5項目＝4.2、小数点以下切り捨てで「4」になります。

「魂の選択」の場合、5段階評価で
- クリアまでの経過Scene数：少ない(1)
- 戦闘回数：少ない(1)
- ボスキャラの強さ：やや弱い(2)
- 独自ルールの複雑さ：単純(1)
- 謎解き：単純(1)

となるので、合計6点÷5項目＝1.2、小数点以下切り捨てで「1」になります（再設定しないとですね；）。

項目についてはまだ決まった訳ではないですが、 **各項目を5段階評価して平均値を出す**のが良いかなと思いました。

**Comment by Salvadors-cabin** [comment]
私は単純明快で意味がすぐに分かるカテゴリー分けがよいと思います。

短編・・・100シーン未満
中編・・・100シーン以上300シーン未満
長編・・・300シーン以上
連作・・・ドラゴンモード、幕末
ミニゲーム・・占い、カードバトル

単なる思いつきですが、参考までに。

**Comment by snext1220** [comment]
ご意見ありがとうございます！

#### カテゴリー

名称については、総じてシンプルに、というご意見が強そうですね。
その線でいくと、個人的にはミドル、ロングに一票でしょうか（従来のミニミニを活かすという意味で）。
＃ ミニの反対語だとジャンボなどの方が「大ボリューム」のイメージが出る？

そのうえで、連作、ミニゲームなどは積極的にタグとして入れていくようにして、将来的にはシナリオ検索に利用できればなどと考えております。

シーン数については、ミニミニが30だったので（謙信が入る）50程度をMaxとして、ミドルが50～200程度、ジャンボ?が200以上（開幕シナも合わせると対象は5シナほど）で、バランスがとりやすいかなと思いました。

#### 難易度

難易度については、結構感覚値にはなってしまうのですが、凡その基準として加点のポイントがあると判断しやすいですね。ありがとうございます！
こちらは特に反対意見なければ、wikiなどでまとめ、今後参考の計算式として利用していく感じでしょうか。

ちなみに、拙作でカウントしてみました（計算結果は最後四捨五入で良いかと思います。さもないと、オール5でないと5が付かなくなるので）。

王杖： 経過4＋戦闘3＋ボス2＋独自2＋謎解き3＝2.8（四捨五入3）
トライン：経過2＋戦闘3＋ボス1＋独自3＋謎解き2＝2.2（四捨五入2）
終焉ゼロ：経過2＋戦闘2＋ボス1＋独自3＋謎解き2＝2（四捨五入2）

私のシナはボスがいないので、どうしても低く出てしまいますね^^;（ボスがない場合は外して計算するのが妥当かも）

**Comment by snext1220** [comment]
上記件、実は自分の中でしっくりこずに、その後も悩んでいたのですが、**カテゴリーはそのまま維持**で如何でしょうか。というのも、カテゴリー（シナリオ企画）と長短の区分けは切り離しておいた方が良いと思ったためです（Pg100などの企画をリネームしてしまうのは却って判り難くなりそう）。

代わりに、シナリオを見つけやすくするためのフィルター機能をより充実させようという提案です。現在は企画名だけで絞り込みが可能ですが、以下のキーでのフィルターを可能にできればと（現時点では、AND条件ではなく、単一キーでの絞り込みを想定）。

+ 企画名
+ シーン数（大長編：500以上、長編：200以上、中編：70以上、短編：70未満）
+ 難易度（1～5） ※ピンポイントでなく「以下」などの方が良い？
+ タグ（これのみ複数選択可？）
+ 作者名（いらない？）

以前から出ていた話題ですが、30シナリオを超えたところでそろそろ見つけやすさも考えておければと。
＃ この辺きちんとやっておくならば、以前から出ているstext.xmlのデータベース化も検討したいところですが…

**Comment by cocotori** [comment]
意見だしが遅くなり、申し訳ありません。

わたしも、カテゴリーとしては今までのものがあったほうが
いいように思います。

というのも、STextシナリオの大半が企画にそって作られたものであり、
その企画でまとめておいたほうが、後々にもわかりやすいように思うからです。

その上で、シナリオの長短でフィルタリングしたいなど要求は
ごもっともだと思います。

ウディフェスという、Wolf RPG Editorで作られたゲームを持ち寄るという企画が毎年行われているのですけど、
そこの分け方が今回の話に近いかなと思いました。
（大きくは開催年度ごと。そして、その中でジャンルや長短でフィルタリング）

https://wodifes.net/

**Comment by toki-sor1** [comment]
**難易度**
> ちなみに、拙作でカウントしてみました（計算結果は最後四捨五入で良いかと思います。さもないと、オール5でないと5が付かなくなるので）。

> 私のシナはボスがいないので、どうしても低く出てしまいますね^^;（ボスがない場合は外して計算するのが妥当かも）

ご賛同＆ご意見ありがとうございます！
仕様としては、**各項目を1～5ポイント加点で計算・結果は四捨五入・ボスがいない場合は外して計算**が良さそうな感じですね～。
反対意見がなければ、リオさんのご提案通りwikiなどでまとめ、今後参考の計算式として利用していきましょうか。

**カテゴリー**
> 上記件、実は自分の中でしっくりこずに、その後も悩んでいたのですが、カテゴリーはそのまま維持で如何でしょうか。というのも、カテゴリー（シナリオ企画）と長短の区分けは切り離しておいた方が良いと思ったためです（Pg100などの企画をリネームしてしまうのは却って判り難くなりそう）。

ネーミングもそうですが、なかなかしっくりくるものがないのは同感ですね；
それに、シナリオ企画は現状通りシナリオ企画でまとまっている方が見易いですから、そこに通常シナリオやその他企画シナリオが混ざると逆に見にくくなってしまうかも……。

上記の懸念もあり、フィルター機能の強化が良さそうな感じがしますね。
ココさんが挙げてくださったサイト様も拝見しましたが、各作品の検索が楽であったり、結果が非常に見易いところが良いと感じました！（参照URLの共有ありがとうございました～！）

**Comment by snext1220** [comment]
@cocotori さん、 @toki-sor1 さん：
ご意見ありがとうございます～

> そこの分け方が今回の話に近いかなと思いました。

はい、まさにそんなイメージです。.xmlファイルの検索となると、意外と面倒なので、データベース化するのが先かどうかを悩んでいますが、皆さんのご意見揃ったところで（反対意見なければ）実装進めていきたいと思います。

なお、検索条件は以下で大丈夫でしょうか（先のものとほぼ同様）。

+ 企画名
+ シーン数（大長編：500以上、長編：200以上、中編：70以上、短編：70未満）
+ 難易度（1～5）以下／以上条件
+ タグ（これのみ複数選択可）
+ 作者名（いらない？）

> 反対意見がなければ、リオさんのご提案通りwikiなどでまとめ、今後参考の計算式として利用していきましょうか。

とりあえず現在のものを以下にまとめておきました。
もし問題あれば、こちらを更新していきましょう～
https://github.com/snext1220/stext/wiki/GitHub%EF%BC%8FFTP%E3%81%AE%E9%81%8B%E7%94%A8#level%E5%B1%9E%E6%80%A7%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

ちなみに、黒船は今回の後編追加で難易度3に上げております（4に近いようにも思えたのですが、壱という意味もあって3に^^;）。そういえば、今更気づいたのですが、難易度4てほとんどないんですね～

**Comment by Salvadors-cabin** [comment]
確認遅くなり申し訳ありません。
もともとDで話題になったきっかけは、ゲストさんのシナリオ投稿（このときはちゃなさんのカードバトル）をどのカテゴリーで登録したらよいか、だったと思います。
今後も企画外からの投稿もある可能性はあり、そうしたカテゴリーも必要ではないかと思います。

**Comment by snext1220** [comment]
ご意見ありがとうございます＆ご指摘の通りだと思います。
Pg100、ミニ30などは動かさないにせよ、長編枠は設けておいた方が良さそうですね。
検索／フィルター機能の強化は並行して進めるとして、こちらはこちらで命名検討しましょうかね（もちろん、急ぎではありませんが）。

その場合、長編（300Over？）に加えて、以前ときのじさんから出ていたハクジャのような連作を想定したものなどの受け皿になるかと。フィルター機能があれば、企画そのものは（Scene数だけでなく）間口を広げて、命名も凝ったものにしても大丈夫かなと考えています。
＃ あるいは、そもそもミニ30、Pg100から外れるものは、「一般シナリオ」枠を使っても良いのかもしれません（募集ページにあるにも関わらず、分類としては使われていませんでした^^;）。

**Comment by snext1220** [comment]
制作途中ですが、フィルター機能付きのページ（α版）をUpしています。
https://www.web-deli.com/sorcerian/text/scena_v3.aspx
バグ取りはここからですが、検索キーなど、機能的なご要望があればお声がけください。

**Comment by toki-sor1** [comment]
返信が前後して申し訳ありませんが、フィルター機能実装＆サイドバーの表示修正お疲れ様です！
一通り操作してみましたが、サクサクと検索結果が表示されて良い感じですね！
現Verでちょっと気になったところを挙げます～。

- 「難易度」の「以下／以上」を指定できるものの、場合によって各難易度が入り乱れて表示されてしまうため、やや見辛い印象。**難易度1なら難易度1のみ表示された方が個人的には見易いと思いました。**
- 「検索キーワード」ですが、シナリオにどのようなキーワードが設定されているのか傾向を予測し難そう、と感じました。
- **「探索(10)」や「歴史(2)」のように、タグ一覧が見られると便利かな**と思いました。

> 現在は検索ボックスが表示されっぱなしになっていますが、折り畳みが出来た方が良いかもしれません（上に折り畳み時のバーを追加するなど？ @toki-sor1 さん、恐縮ですがご相談させてください）。

そうですね、ちょっと主張が激しい感じがするので、**検索ボックスは折り畳めるとスッキリしそうですよね。**
となると、折り畳み時のバーの見た目は、どのようなイメージでしょうか？
**もし参考画像やサイズの指定等ありましたら、お手数をお掛けしてしまい恐縮ですが、教えていただけましたら助かります～。**

**Comment by snext1220** [comment]
@toki-sor1 さん：
お忙しいところ早速のご確認ありがとうございます！
以下、ご指摘の点についてお返事いたしますね。

> 難易度1なら難易度1のみ表示された方が個人的には見易いと思いました。

こちらは以上、以下を残しつつ、完全一致を追加＆既定にしてみました。
この辺、やや好み（用途？）にも依りそうに思えたので、既定はご要望伺いつつ、今後変えていければと～

>  ただ、それでもやっぱりタグ一覧の方が、分類を調べて検索しなくても良いので楽かなと；（1つしかないタグもあるので、プルダウン形式でもリスト形式でもすごい縦長になりそうですが……）

そうなんですよね...
私も最初はタグ一覧を表示しようと思ったのですが、あまりにばらけすぎていて、一覧が長くなる割に、あまり意味がなくなっているなぁと^^;（ほとんどが1～2個まで絞られてしまうので、ほとんど特定シナのピンポイント検索になってしまうという；）
こちらはもしタグ一覧にするのであれば、一旦タグ体系を整理してからの方が良いかなと思ったのですが、如何でしょうか。

＃ ちなみに、現在のキーワード検索は、タグだけでなく、タイトル／サブタイトル、作者コメント、紹介文を全検索しています。

> 検索ボックスは折り畳めるとスッキリしそうですよね。となると、折り畳み時のバーの見た目は、どのようなイメージでしょうか？

ご検討ありがとうございます。
こちら、現在ある素材で以て仮レイアウトしてみました（文字も仮置き）。
タイトルバーからオンオフするイメージでおります～（素材としてはタイトルバーの背景画像のイメージです） それなりに落ち着いているとは思うのですが、ボタン式やその他良いレイアウトもあるかなと少々悩んでおり、「こんなレイアウトの方が～」などあれば、ぜひご意見のほどお願いいたしますm(_ _)m

**Comment by cocotori** [comment]
ざっと確認しましたが正常に動いているようです。
これは作るの大変だったでしょう・・・ありがとうございます！

難易度の一致が現在は（-）と表示されていますが、「一致」でもいいかもしれませんね。
ただ、今のままでも大丈夫です。

**Comment by snext1220** [comment]
@cocotori さん：
ご確認＆労いのお言葉有難うございます！
ほとんどコード入れ替えでしたが、その分、これまで乱雑だったコードを一新できたので、拡張もしやすくなったように思えます。特定のシナの括りでも紹介しやすくなったはずなので、是非告知に活用ください～

難易度＞ご指摘ありがとうございます！こちら早速修正しました～

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで問題ないことを確認しました！

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 91.0.4472.77(64bit)にて動作確認。
正常に検索できていること、検索条件を反映したページをURLからでも開けることを確認しました。
コード入れ替え本当にお疲れ様です！
検索機能がパワーアップし、結果も見易くなり、シナリオも更に紹介し易くなったと思います！

> こちらは以上、以下を残しつつ、完全一致を追加＆既定にしてみました。
この辺、やや好み（用途？）にも依りそうに思えたので、既定はご要望伺いつつ、今後変えていければと～

実装ありがとうございます！
完全一致もあると目的のシナリオを探しやすいなと思っていたので、ばっちりです！

> こちらはもしタグ一覧にするのであれば、一旦タグ体系を整理してからの方が良いかなと思ったのですが、如何でしょうか。
＃ ちなみに、現在のキーワード検索は、タグだけでなく、タイトル／サブタイトル、作者名、作者コメント、紹介文を全検索しています～

タグ一覧から検索できると便利かなと思ったのですが、全検索できることと、内容が多岐に亘るシナリオでは分類が難しい＆現状を見るとシナリオの個性が出ている部分でもあるので、無理にタグ体系の整理をしなくてもよさそうですね。
意見を出しておきながら申し訳ありませんが、タグ一覧案はなしとしてくださいませ～；

> タイトルバーからオンオフするイメージでおります～（素材としてはタイトルバーの背景画像のイメージです） それなりに落ち着いているとは思うのですが、ボタン式やその他良いレイアウトもあるかなと少々悩んでおり、「こんなレイアウトの方が～」などあれば、ぜひご意見のほどお願いいたしますm(_ _)m

現在は仮レイアウトとのお話ですが、統一感があって十分良さそうな感じですね。
ただ、他のタイトルとのメリハリをつけた方が見易いと思うので、ちょっと色違い版壁紙（title_wp2.png）とアイコン（search.png）を作ってみました。
https://github.com/snext1220/snext-site/tree/main/text/image
あとは、文字色も他のタイトルと変えてみると良いかもしれません。
![searchサンプル](https://user-images.githubusercontent.com/42646342/120934651-2d7b0680-c73a-11eb-84dd-281d5b9cd8a4.png)

**Comment by snext1220** [comment]
@toki-sor1 さん：
ご確認ありがとうございます＆タグ一覧の件、承知いたしました！
タグの扱いは、現時点ではママとしてまいりますね。ただ、正直どう使っていくかが曖昧な箇所でもありましたので、今後ご意見あればまた検討してまいりましょう～

お忙しい処、検索用のバナー＆アイコンについてもありがとうございました！
まずは実装してみましたが、如何でしょうか？？

+ 文字色はやや目立ちにくくなりそうだったので、現時点ではママにしております（スミマセン；）
+ アイコンを入れたことで検索フォームの表示バーであることも判りやすくなったと思うので、カッコ内の文言を削除してみました（モバイル環境では2行になっていたので）
+ アイコンは縮小していれておりますが、SEARCHの文字列が若干見難い？

お手数ですが、引き続きご意見頂ければ幸いでございます～

**Comment by toki-sor1** [comment]
ご意見＆デザイン反映ありがとうございます！
文字色を変えると、確かに背景壁紙と合わさって目立ちにくくなってしまいますね；
白のままの方がはっきりしているように感じました！（現状ままでOK）

カッコ内の文言が削除されてスッキリしましたね！　良いと思います！
＃モバイル環境のことをすっかり忘れていました、すみません……；；

素材作成時も文字が見難いかなと思いましたが、やっぱり見難くかったですね；
文字を大きくしたものも試しに作ってみたものの、どうもしっくりこなかったので、文字を消して縦幅を縮めてみました。
GitHub、本番環境ともに反映済みです～。
＃もしアイコンを縮小しなくても大丈夫なようでしたら、お手数をお掛けして申し訳ありませんが、原寸のままでお願いします。
![image](https://user-images.githubusercontent.com/42646342/121041070-632cf780-c7ed-11eb-8cec-86f4baa38fc3.png)

**Comment by snext1220** [comment]
お忙しい処早速ありがとうございます！
戴いたアイコンにて縦幅を原寸ママとし、マージンなどの調整を致しました～
おかげさまで検索ということもよりはっきりとし、良い感じになったと思いますm(_ _)m

こちら一旦Closeと致しますが、もし問題などありましたらＤなどでお知らせくださいませ。
