### ISSUE TITLE
エンディングの複数bgm

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#25]
RYUさんからの質問です。
一元管理のために、勝手ながら、こちらへ移動させていただきました。

> endのbgmを複数設定する事はできますか？ 
> 基本的にはbadとhappyの2種しかできないようで、今作ってるミニ３０でhappyを複数種類作りたいのですが、happy用bgmを設定せず、そのendシーンに@bgm:で別bgmを設定して再生されますかね？

**Comment by snext1220** [comment]
残念ながら、現状は不可です。
試してはいませんが、恐らくbgm属性を指定してもbgm_happy/bad.mp3で上書きされてしまうかと

**Comment by RYU-DS** [comment]
endはhappyであれbadであれ、結構イメージの違う結末が複数出来てしまいやすい、というか作れないのは困るので、各endにそれぞれbgmを割り当てられるよう希望します。
というか、そのスレがすでに結末の幅的に1曲では無理なので…
現状でも実質のendシーンを数シーン入れてそこに曲を割り当て、最後にend設定シーンを入れて対応しようとは思っていますが…

**Comment by cocotori** [comment]
通常曲も選べるようになったことで、
エンド曲1つずつ、という必然性も薄れてきているかもしれませんね。

（無理なら構いませんが）
実装難易度と互換性次第ですが、
エンド曲も任意に選べたほうがいいような気がします。

**Comment by snext1220** [comment]
皆さま、ご意見有難うございました。

皆さまのご意見を受けて、**end属性のあるシーンでもbgm属性を優先する**方向で改定を進めたいと思います。ただし、bgm関連はend属性との関連など結構複雑なことをしているため、最終的な実装方法は変更になるかもしれません。

#### 余談

end属性にbad1、bad2を追加する方法について。実は、そちらの方が現在の実装にはマッチしているのですが、要件を見るに追加個数が想定できないため（無制限に増えそうなので）、今回は見送りました。ある程度用途を限定できるならば、現在のhappy、badの他に、true（真エンド）、death（死エンド）のような区分を明確にする、という方法はあったかと思います。
