### ISSUE TITLE
enemy要素のdrop属性からフラグ／アイテムを設定

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#254]
enemy要素のdrop属性からは、現在

+ 欠片
+ FREE

を指定可能ですが、加えて

+ フラグ（flag/f01/表記）
+ アイテム（item/i01/表記）

を指定可能にできないかと考えています。
これまではシーン内で戦闘に勝利、その他判定に成功した場合にのみアイテム／フラグを得るような用途では、一度シーンを移動する必要がありましたが、これをより自然にBattle Sheet内で完結できるようにしたものです。

互換性には影響しないことから、既に対応＆GitHub反映済みです。

### 追記

内部パラメーターについても対応しております（GitHub Only）。

+ 内部パラメーター（param/p01:10/瓶の中身）

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 90.0.4430.85(64bit)にて動作確認。
drop属性で指定したフラグとアイテムが指定の表記で正常に表示され、取得できることを確認しました！

**Comment by cocotori** [comment]
chromeにて確認。
フラグやアイテムがドロップされることを確認しました。
