### ISSUE TITLE
Stextサイト全般へのアクセスエラーが多い？

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#256]
STextサイト（トップページ、ゲーム画面、PgFlowなど）全般にわたって、
内部的にライブラリが読み込めずに、表示が乱れることが多くなっているような気がします（スーパーリロード時に多いように思えます）。

当方だけの問題であれば良いのですが、他の皆さまの環境では如何でしょうか。
もし頻発している場合には、ライブラリの配置などを再検討する必要があるかと思っております。
＃ 構造上、影響も大きいので、他の皆さんの方で発生していないようであれば、様子見にできればと。

#### 追記（04/17）

当方環境であまりにひどいので、取り急ぎGitHub環境のみ通常の利用したライブラリのリンク先を入れ替えました（改善済み）。また、同時にライブラリを最新版に置き換えています。
本番環境については別対応となるので（FTP配置だけでなく、別個の対応要）、上記皆さんの状況を伺ったうえで対応の予定です。

**Comment by toki-sor1** [comment]
お疲れ様です！　こちらはiPadのSafariで確認しましたが、表示の目立った乱れはありませんでした。
ただ、サイトのシナリオページで「詳細を表示」ボタンが、場合によっては枠から下にはみ出ているようでした。

**Comment by snext1220** [comment]
ご確認ありがとうございます！
こちらではライブラリが正しく読み込めていないようで、シナリオ一覧がそもそも表示されない、などの問題が出ております（現在進行形）。何度かリロードすれば表示されるのですが、ここ数週間高確率で発生するもので気になっておりました^^;

＃［詳細～］ボタンについては従来からの問題でした（スミマセン；）。こちらは画像の縦幅やタイトルの文字数によって発生するものなのですが、さて、どうするか...；；

**Comment by cocotori** [comment]
言いそびれてしまっていたのですけど、
確かにわたしの環境でも、サイトの表示がおかしい現象が出ています。

chromeだと、シナリオ一覧が表示されず、
いきなり冒険に出発するのボタンが表示されています。
さらに、そのボタンは押せません。

edgeではそういう現象は出ていないです。
キャッシュが悪さをしているかと思って削除したりしたのですが、
状況変わらずです。

**Comment by snext1220** [comment]
ご報告ありがとうございます。
まさに、そのような状況が、こちらでも出ておりました。

ただ、私の方では何度かのリロードで改善していたのですが、cocoさんの方ではそもそも改善しないのですね...
緊急と思われましたので、先ほどSText、PgFlow、SNextサイトでライブラリのリンク先を入れ替えました。
これで現象改善しましたでしょうか？
＃ 原因は旧リンク先のjquery.comが不安定になっているためと思われます。

また、このタイミングでSText/PgFlowは最新のバージョンにUpdateしています。一応、各ページ動作をご確認戴けますと幸いです（Nextサイトは問題ありだったので、旧バージョン据え置き）。

＃ 外部サイトに依存している状態があまりよくなさそうなので、どこかでライブラリの外部参照をすべて自サイトに移動した方が良いかもしれません。こちらは手間も大きいので、落ち着いたところになるかと思いますが…


@Salvadors-cabin さん：
同じ原因でNext2020サイトにも影響が出ていると思われます。
my.masterの以下行を差し替えをお願いいたします。
```
<script type="text/javascript"
   src="https://code.jquery.com/jquery-1.8.3.min.js"></script>
```
⇒
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
```

**Comment by cocotori** [comment]
早速の対応ありがとうございます！

ですが、こちらの環境では残念ながら変化ないようです・・・
おっしゃるとおり、こちらではリロードを繰り返しても治らないことから、
もしかしたら違う原因なのかもしれません。

いつごろ現象が出だしたか覚えていないのですが、
1,2ヶ月はたっているような気がします。
他のブラウザでは動いていたので、あまり気にせず、放置してしまっていました。

**Comment by snext1220** [comment]
なんと。
確かにリロード改善しない、1～2か月という点から違う理由なのかもしれませんね。
他のブラウザーでは問題ないのが救いですが、Chromeが全PVの9割以上を占めているので、悩ましい...；

お手数おかけして申し訳ありませんが、Chromeのデベロッパーツールのコンソールタブをキャプチャ戴いてもよろしいでしょうか。

＃ 黒船との兼ね合いですぐさま対応できるかが不透明ですが、緊急度合い見て動いていければと思います～

**Comment by cocotori** [comment]
よろしくお願いします！

![クリップボード](https://user-images.githubusercontent.com/42885160/115135949-64e10700-a057-11eb-9e18-f0efb9d7ddcf.png)

**Comment by snext1220** [comment]
ありがとうございます！
原因としてはこちらと同様のようです。
ただ、先ほどの対応に不十分な点があったので、先ほど対応いたしました。
お手数ですが、キャッシュクリアの上で再度ご確認いただいてもよろしいでしょうか？
お手数をおかけします。。

**Comment by cocotori** [comment]
直りました！今度こそ大丈夫です。
ありがとうございました。

**Comment by snext1220** [comment]
こちらこそ、早速のご確認ありがとうございました！

**Comment by Salvadors-cabin** [comment]
連絡ありがとうございます。
さきほどSN2020サイトのmy.masterを更新しましたー。
私はWin10+Edgeの環境でしたので全く気付かなかったです。

**Comment by snext1220** [comment]
更新お疲れ様です＆ありがとうございます！

これで全ページUpdateできたと思うので、改めて軽く各ページ見回ってみて戴けますと幸いです～＞皆さん

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 90.0.4430.93(64bit)にて動作確認。
サイトの各ページが正常に表示されていました！（私の環境では以前でも正常に表示されていたのが謎ですが……）

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で特に問題なかったです。
