### ISSUE TITLE
drop属性の複数指定を可能に

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#257]
enemy要素でのdrop属性をカンマ区切りで複数指定できるようにします
＃ func属性でできていたことと同じで、その場合はランダムにドロップアイテムが選択されます。

既にGitHub Onlyで対応済みです。

**Comment by cocotori** [comment]
chromeで確認。
カンマ区切りで複数指定したところ、そこからランダムに選ばれることを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 90.0.4430.93(64bit)にて動作確認。
プレイグラウンド（テスト用シナリオ）で人面岩のランダムドロップを確認しました。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で動作に問題ないことを確認しましたー。
