### ISSUE TITLE
【PgFlow】scenario.xml出力時のリンク切れチェック

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#267]
https://github.com/snext1220/stext/discussions/259#discussioncomment-640885 のご指摘を受けてのIssueです。

PgFlowで.xml形式の出力時に

+ end属性が空
+ リンク先がないシーン

についてコンソールに警告ログを出力するようにしました。
一次的なリンクのチェック負荷を軽減することが目的です。

＃ インポート、戦闘ルール用のシーンなど、特殊なシーンまでもチェックの対象になってしまいますが、ある程度限定的と考え、現時点ではそのままエラー出力しています。

**Comment by cocotori** [comment]
こちらはF12を押したときに出るconsoleに表示されるものですか？
わたしは普段見ないので是非を判断できないのですが、
情報が多くなるのはいいことかもしれません。

**Comment by snext1220** [comment]
@cocotori さん：
はい、ご認識の通りです！
ホントは本体に表示されるのがベターなのですが、表示場所など諸々問題になるので、まずは手軽なところで。
既に表示されている情報もいくつかありますし、今後も適宜追加していくかと思いますので、たまに開いてみてくださいｗ

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 90.0.4430.93(64bit)にて動作確認。
コンソールにエラーが表示されるのを確認しました。
私も普段は確認しないところなのですが、いざという時に原因特定がし易くなって良いと思います～。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で動作に問題ないことを確認しました。

ひとつ気になったのは、sceneにrule="xxx"で指定するBattleSheet表示用シーンもエラー出力されている事でしょうか。
（「ラミディア」ではシーン60,61,62,63がそれにあたります）
※製作者は分かっていることなので大きな問題ではありません。

**Comment by snext1220** [comment]
ご確認ありがとうございます。
はい、こちらは本Issue冒頭の通りでして、その他にも（共通）インポートなど特殊なシーンについては出力の対象となります^^; （特殊用途かどうかを厳密に判定するのは難しいため）仰る通り、製作者は把握していると思われますので、こちらはママとさせていただければと思います～
