### ISSUE TITLE
【PgFlow】リンクの表示ソート

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#268]
［シーン］タブ中央付近の［表示ソート］をクリックすることで、
移動ボタンの表示順序をドラッグ＆ドロップで修正できるようにしました。

デザインの付与などはまだですが、随分と修正が楽になったと思うので、是非触ってやってください。
現時点では、GitHub Onlyです。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 90.0.4430.85(64bit)にて動作確認。
指定の方法で表示順序を入れ替えられ、入れ替えた状態が反映されていることを確認しました。

これはすごいですね！
今までは入れ替えにやや手間取っていましたが、今回の実装で直感的かつ手軽に順序が入れ替えられるようになって嬉しいです～！

**Comment by cocotori** [comment]
chromeで確認。
直感的に入れ替えられるのはありがたいです。

これはわたしの思い違いかもしれませんが、
ソートという表現がわかりにくいかも、と思いました。
ソートというとアルファベット順とか小さい順とかな気がして、
今回のような意味で使うなら並べ替えとかのほうがいいように思いました。

（おそらく、わたしが言ってるのはソートの狭い意味だと思うので
　みなさんが違和感ないようでしたらそのままで構いません。）

**Comment by toki-sor1** [comment]
確かに「並び替え」または「シーンの並び替え」と表記されている方が、どのような機能なのかがぱっと見で分かり易いですね。

**Comment by snext1220** [comment]
ご意見ありがとうございます～
確かに、一寸イメージしにくいかもしれませんね。。＞ソート
＃ 辞書的な意味では正しいはずではあるのですが、どうしても昇順降順のイメージが先に立つのは納得です！

ということで、ご提案の通り、「並べ替え」とし、同じく「リンク追加」も単に「追加」と揃えました（リンクに属しているボタンなので、リンクの～は明らかであることから＆）

**Comment by cocotori** [comment]
提案を採用いただきありがとうございます。
いいと思います！

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで機能を確認しました。問題ありません。

**Comment by toki-sor1** [comment]
意味が分かり易くなって＆スッキリとして良いと感じました！
