### ISSUE TITLE
${input}での数値の増減が動作しない

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#269]
https://github.com/snext1220/stext/discussions/259#discussioncomment-653015 由来のIssueです。

${input}で生成されるスピナーボックスで

+ ［+］［-］ボタンが動作しない
+ テキストボックスのスタイルが解除されている

等の問題がありました。

テキストボックスの仕様を変更した時にサイドバーは修正していたのですが、SGML式の変更が反映されていなかったようです（結構前からの問題だったようです^^;）。
こちら動作そのものに影響する問題なので、修正のうえ、GitHub＆本番環境に反映済みです。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 90.0.4430.85(64bit)にて動作確認。
［+］［-］ボタンが正常に表示され、動作することも確認しました。

**Comment by toki-sor1** [comment]
すみません、気になる挙動を確認したので報告を。
現在、「黒船」のテストプレイを行っていますが、**サイドバーの「Magic」で欠片の［+］［-］ボタンを押すと星が2個ずつ増減している**ようでした；

**Comment by snext1220** [comment]
早速のご確認ありがとうございます！
そして、スミマセンでした；；
重複して加減算が行われておりましたので、改めて処理を整理し直しました。
GitHub Onlyですが、如何なものでしょうか？（汗

**Comment by toki-sor1** [comment]
早速のご確認＆ご対応ありがとうございます！　お疲れ様です！
正常に1個ずつ減算されているのを確認しました！

**Comment by snext1220** [comment]
夜遅くまでありがとうございます～お手数をおかけしました！！

**Comment by cocotori** [comment]
chromeにて確認。
[+][-]ボタンが正常に動作しました。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で動作に問題ないことを確認しましたー。
