### ISSUE TITLE
SText公式サイト刷新

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#27]
原作31周年を過ぎてからの案件ですが、備忘録代わりに。
時間はありますが、今後活動方針にも依るかと思うので、ゆるゆると議論していければと思います。

### 前提

ウソサイト（0401）と、本物コンテンツ（AllAbout）の混在がそろそろ混乱のもとになりかけているので、Next姉妹サイトとしてのAllAboutサイトを作る時が来たのかなと。
また、世の中的にhttps対応が求められているのもその理由です。

基本は、メニューとヘッダーロゴだけを入れ替えて、ほぼ現状のNextサイトのテンプレートを再利用、程度で考えていますが^^;、これを機会に、こうした要素を入れておきたい、などあれば、このスレでご意見いただければ幸いです。

### 想定しているメニュー（左メニュー）

+ Next0401ページへのリンク（現在のAllAboutロゴのような感じで）
+ About（現在のAllAboutページ）
+ Gamebook（STextページを以下に分割）
    + About（概要）
    + Scenario（シナリオ・将来的には検索機能も）
    + Utility（ユーティリティ）
+ Gallery（0401と同様の感じ。作品ごとに）
+ Staff（新設。作品ごとに）

### 懸案

+ トップページ（現在の0401では15シナリオの起動メニュー）に相当する箇所をどうするか（ノーアイデア）
+ そもそもAll About企画の総合ページにするか（統一感はあるが、現時点ではSTextの比重は大きくアンバランス）、SText独立ページにするか（収まりは良いが、毎回サイト立ち上げはめんどい）

**Comment by snext1220** [comment]
その後いろいろ考えていたのですが、現時点ではNextサイトのコピーで、STextサイトを作成できないかと考えています。NextサイトとSTextサイトを分離し、相互リンクさせるだけのイメージです。

メニュー／ロゴの修正は発生しますが、サイト構造をほとんど変えずに、相互の分離が可能になります。また、将来的に別企画を立ち上げた時には、チームとしてのトップページを立ち上げ、そこから各企画にリンクするような形になるかもしれませんが、それは今後の話ということで。
如何なものでしょうか。

### ヘッダー

現在のNextサイトロゴをベースに、NextをTextに置き換え

### 左メニュー

+ Next0401ページへのリンク（現在のAllAboutロゴのような感じで）
+ About（紹介）
+ Scenario（シナリオ・将来的には検索機能も）
+ Utility（ユーティリティ）
+ Staff（新設。作品ごとに）

**Comment by RYU-DS** [comment]
元々見て（使って）いる人には何が変わったかわからない、的な部分は置いといて、元から気になっている点を…

・トップはシナリオの方が良く無いですかね？
その後「これはなんなの？」と思ったら各説明を見に行く方が、興味を引かせるアイキャッチとしていいような気がします。
各シナリオのタイトルやトップ説明にその責任（興味を引かせる）がのしかかりますがｗ

・ドラゴンモードは分離した方がよいのでは？
他シナ条件がある特殊シナなのでその説明をはさむワンクッションのためにも、いったん「ドラゴンと戦う」をクリックして説明を見てもらう方が、道筋的にも雰囲気的にもよいかと。
ミニも分離した方がいいかもしれませんが、シナ全体数と相談…シナリオ番号がキチンと並ばないのもアレですが…「ドラゴンモード０（トータル14）」みたいなのでなんとか（ウザイか）。

あとは個人的にスクロールがおっくう（PC）なのが影響していて、環境（スマホの契約）によっては別を開く方が重いなどの考慮が抜けている意見なので、そこらへんも踏まえて聞いておいて下さい。

**Comment by snext1220** [comment]
早速、ご覧戴いてありがとうございます！

> 元々見て（使って）いる人には何が変わったかわからない、～～

あは、現時点では、ロゴも全然変わってないので、それはあると思いますｗ

今回のサイト分離の目的は、以下の通りでした。

+ Nextサイト（0401企画）の中に間借りしていたので、左メニューをクリックすると、いわゆるウソサイトのコンテンツになるのが誤解を招きそうだった。
+ STextページが極端に縦長になっていたので、ページを複数に分割したかった

ということで、今回はまずページ分割し、リンク等の整理が中心作業。今後、徐々に個々のページをブラッシュアップ、という流れになるかと思います。特に（仰る通り）シナリオページは中心コンテンツなので見やすく、興味を引く形にしていければと。

＃現時点ではメニューがこんな風に分かれますよ、という超プロトタイプレベルでご覧くださいませ～

> ・トップはシナリオの方が良く無いですかね？

そうですね～
作りは全く違いますが、以下ページのように、先頭にごく簡単なキャッチを入れるだけでも、サイトの趣旨は判ると思いますし。なんのページかをより詳しく知りたいならば、［About］ページを見れば良いですしね。
http://gamebook.xyz/

> ・ドラゴンモードは分離した方がよいのでは？

ここはまだ悩み中ですが――
一応現時点では、シナリオページのトップに、「ドラゴンモード開催中！」「ミニミニ30祭」「今日のおすすめ（ランダム）」のように、カテゴリーごとに紹介カルーセルがあっても良いのかなとも思っています。
＃シナリオ一覧はこれまで通り残しておいて、ページ内リンクで、個々のシナリオに飛ぶようなイメージです。

あとは、@toki1-sor さんとも話していましたが、シリーズ単位にタイトルの背景を変化させることで、一覧側でもシリーズごとの見た目を目立たせられるかなと。

**Comment by snext1220** [comment]
テキストなどボチボチ書き換えて、少しずつリニューアル感が出てきた…かもしれません。

ついては、［Gallery］ページやその他のページで個々の項にも画像を載せていきたく、これまでにツイートなどでのみ利用されていて、シナリオ紹介などで利用していない画像があれば、OneDriveにUp戴けますと幸いですm(_ _)m
内容にマッチすれば該当するページに、さもなくば、Galleryページで展示できればと。
＃暫定ながら、勝手におしりかじり虫を利用させていただいてますがｗ、問題あればお知らせくださいm(_ _)m

### 今後のスケジュール

ロゴなどのご相談次第ではありますが、早ければ次回「黄泉へ～」のリリース時には、もしくは来月の「金竜」タイミングに合わせて、リニューアル版サイトリリースを目指していければと。如何でしょうか。

**Comment by cocotori** [comment]
今まで作ったイラストを　https://onedrive.live.com/?id=4837C202555BE782%219373&cid=4837C202555BE782　に置いておきました。自由にお使いください～（一部、イラストメーカーを利用したものは規約的なものがあるはずなのでご注意ください。非営利活動なら問題なかったはずですが）

ひとまずこのフォルダに置きましたが、他にふさわしい場所があればご指摘いただければ。

**Comment by snext1220** [comment]
ありがとうございます！
とりあえず既にシナリオ紹介等、他ページで利用しているものを省いて
Galleryに反映させていただきました～
＃拡大表示時に表示されるタイトルは仮です。

> 規約的なものがあるはずなのでご注意ください。非営利活動なら問題なかったはずですが

はい、たぶん問題なさそうですが、もしなにかあれば、あとからでも取り下げますのでご指摘ください。

> ひとまずこのフォルダに置きましたが、他にふさわしい場所があればご指摘いただければ。

テンポラリなものなので、現在の場所で問題ございませんです。あと、頻繁に変更が発生するようになったら、また、FTPへのアクセス権限付与させて戴くなど、検討したいと思います。

**Comment by snext1220** [comment]
ロゴ／アイコン等を除いて、凡そのテキストリライト、PPTの配置を完了しました。

相変わらずの突貫工事だったので、コードが汚く、後々のために微修正は諸々続けていく予定ですが、まずは構成／テキスト等についてのご確認をお願いできますと幸いです。

**Comment by snext1220** [comment]
### 開発メモ

+ scena.aspx#scepterで、目的のタブパネルへ移動＆開くように（SEM対策）

**Comment by toki-sor1** [comment]
現時点で作成できた素材をサイトの画面にはめ込んだサンプルを作成しました。
今回作成したのは、「ヘッダー（まずはトップ用のみですが）」「各メニュー画像（英語・日本語）」「Next0401ページへのリンク画像」になります。
試作の段階ではありますが、上記素材はO/Dにアップ済みです。
https://onedrive.live.com/?id=4837C202555BE782%219382&cid=4837C202555BE782

![default](https://user-images.githubusercontent.com/42646342/53650692-73f27880-3c88-11e9-9d17-d6ab5ca42f2c.png)

まだ全ての素材は揃っていないのですが、2点ほど確認したいことがございます～。

- 各素材のファイル名はどうしましょう？（今回は仮のファイル名になっています）

- シナリオページでのバナー画像（ミニ30、第1Seasonシナ）の「第1Seasonシナ」のバナー画像ですが、シナリオNo.1～8までのシナリオが掲載されているページに使用しているバナー画像とは別の物を作成するという感じなのでしょうか？

**Comment by snext1220** [comment]
こちらも★★★以外まで一気にご対応頂きましてありがとうございます。
先程、Newサイトに反映させていただきました～
＃ヘッダー画像、前の雰囲気そのままにさりげなくドラゴンモードの裏地がおしゃれですね！

ご質問の件、回答いたします。

### ファイル名

未確定でしたので、ほぼご提案の名前に致しました。
ただし、Nextサイトへのバナーは、他に合わせてnext_banner_bo.png／next_banner_bo_ja.pngに、一部メニュー画像がja、jp混在していたので、多いjaに統一いたしました。

### バナー

とと、スミマセン、これはママで良いですね；色々配置換えをしてたのですが、消さなければと思いながら失念しておりました。ミニミニ30のみのご対応でお願いできますと幸いですm(_ _)m

**Comment by snext1220** [comment]
@toki-sor1 さん＞
あ、あと、以下の件ですが、もしなにか掲載できそうなものがあれば、お願いします～
https://github.com/snext1220/stext/issues/27#issuecomment-461292154

**Comment by cocotori** [comment]
だいぶスッキリしていい感じだと思います！
シナリオとユーティリティが分けられたので、わかりやすくなったと思います。

**Comment by toki-sor1** [comment]
早速のご対応ありがとうございました！
ほぼNext素材・改という感じですが、ヘッダー画像は水晶玉絵を以前描いていたこともあり、ドラゴンモード絵も丁度丸っぽいからと合体してみましたｗ
明確に、と言っていた筈が、さりげなくという感じになっていたので、ドラゴンモードの裏地に気付いていただけて＆お褒めいただけて嬉しいです！

今回は正式リリース優先でデザインはほぼ据え置きとなっているので、今後デザインも少しずつ改善していきたいところなのですが、まずはサイトのメニュー画像やシナリオタイトル等の壁紙の色を変更するだけでも、大分印象が違って見えるかなと思います。

Nextで使った青／赤の組み合わせがシックリきているので、そこから変更するとなるとやや勇気がいるのですが、もし　**今度はこの色をメインに使ってみるのはどうだろう？**　というご意見ご要望がありましたら、是非よろしくお願い致します～m(_ _)m

> ファイル名

あわわ、確認不足による表記ブレすみません……！
Next版と共通しているバナーは、以前作成したものを入れたので、そこで表記ブレを発生させてしまいました；；
もしNextサイト素材と表記を合わせる場合は、「○○_bo_jp.png」のように「jp」に統一していただいた方が良いかなと思いますが、こちら、リオさんにご判断・最終決定していただけましたら助かります；；（お手数をお掛けしてしまい申し訳ありません……）

> バナー

いえいえ、詳細ありがとうございます。
ミニミニ30のみですね、承知しました！

> ［Gallery］ページ

対応が遅れてしまい申し訳ありません……！
こちら、NextとTextに関連する画像をまとめてO/Dにアップしました。
https://onedrive.live.com/?id=4837C202555BE782%219402&cid=4837C202555BE782

いくつかバージョン違い（着色なしorあり、宣伝用に加工したもの等）のものもあり、メイン画像だけでも大丈夫でしたら、メインのみ採用でお願いします。
また、ファイル名もサイト掲載に合わせてご自由に変更していただいて大丈夫です。

Text用フォルダに入っている **title2.png** については、現在Galleryにアップされている同一の画像が、ややバージョンの古いものの為、差し替えていただけましたら助かります；

**Comment by snext1220** [comment]
> 明確に、と言っていた筈が、さりげなくという感じになっていたので～～～

今回は、NextページとTextページの姉妹関係をアピールできればと思っていましたので、共通性を感じられ、でも、よく見ると違うというバランスが、個人的には絶妙でした！ありがとうございます～

> Nextで使った青／赤の組み合わせがシックリきているので、そこから変更するとなるとやや勇気がいるのですが、もし　今度はこの色をメインに使ってみるのはどうだろう？～～～

勇気＞まさに、そうなのですよね...
ソーサリアン色とも言うべき二色だったというのもありますし、その前提で、細かなサイト内のカラーも決めてきたので、一寸した変更でバランスが崩れてしまうだろうなぁと思うと、中々動かしづらく；
むむ、スミマセン、現時点では今以上の希望カラーが出にくいですね...
＃他の皆さまは如何でしょう？？

> Next版と共通しているバナーは、以前作成したものを入れたので、～～

でしたね～私も途中で気づいたのですが、jaで直してしまったのでいいか、という感じでした^^; 頻繁に動かすものでもないので、とりあえずママとし、どこかで気が向いたら統一する、かもという感じで^^;

> ［Gallery］ページ

ありがとうございます！とりあえず複数バージョンあるものは、着色あり、メインのもので統一＆道場などで利用されているものを除いてみましたが、如何でしょうか？（順番的には、全体ものを先頭に、個別シナを既存のものの後方に追加いたしました）これは優先して載せたい、などありましたら、勿論お申し付けください～
＃ Nextものはbotツイで利用しているものも諸々ありで、未使用ものをGalleryという形かなと（スミマセン、こちらは後日対応にて；；）。

> Text用フォルダに入っている title2.png

おっと、スミマセン、手元に複数バージョンあったものを適当に見繕ってしまいました；差し替えさせていただきました～

**Comment by toki-sor1** [comment]
title2.png差し替えありがとうございます！
又、素材についてもお褒めのお言葉ありがとうございました！
素材デザイン関連の作業は、素材を作りながら毎度不安との戦いなので、ご感想をいただけて嬉しいです！

> ソーサリアン色とも言うべき二色だったというのもありますし、その前提で、細かなサイト内のカラーも決めてきたので、一寸した変更でバランスが崩れてしまうだろうなぁと思うと、中々動かしづらく；

ソーサリアン色……まさにそうなんですよね……；；
それに、リオさんが仰る通り（青／赤前提）で細かなサイト内のカラーも決めていたので、確かに一部の変更でも全体に響きそうな感じもして、うう～、難しいですね……。
かと言って、赤が表で青が裏というのも目に優しくないですし……な、悩ましい……。

> 私も途中で気づいたのですが、jaで直してしまったのでいいか、という感じでした^^; 頻繁に動かすものでもないので、とりあえずママとし、どこかで気が向いたら統一する、かもという感じで^^;

了解です～……！（お手数をお掛けしてしまい申し訳ありません；；）

> とりあえず複数バージョンあるものは、着色あり、メインのもので統一＆道場などで利用されているものを除いてみましたが、如何でしょうか？

はい！　ばっちりです！！　ありがとうございました～！！（イラストコメントにニヤリとしましたｗ）
Nextものについても了解です！　お忙しい中恐縮ですが、後日ご対応時によろしくお願い致します～。

**ミニミニ30バナー**
バナーに丁度良い素材がないなぁと思い、枠と30周年ロゴ以外は新規でミニっぽく作成しました～。
（30周年にスタートした企画なのでロゴ有りにしています）
O/Dにアップ済みです。
https://onedrive.live.com/?id=4837C202555BE782%217367&cid=4837C202555BE782
![stext_mini30_banner](https://user-images.githubusercontent.com/42646342/53747825-78689c80-3ee7-11e9-852e-9269f5de0579.png)

**Comment by snext1220** [comment]
> 素材デザイン関連の作業は、素材を作りながら毎度不安との戦いなので、ご感想をいただけて嬉しいです！

こちらこそ、いつもイメージを汲み取って戴いてありがとうございます！
システム／サイト共に、ときのじさんのデザインなしには成立しないものなので、本当に助かっております！！

それだけに各案件が頼り切りになってしまうのが本当に心苦しいのですが；、見通し共有しながら無理なく進めていければと思っておりますので、引き続きどうぞよろしくお願いいたしますm(_ _)m

> かと言って、赤が表で青が裏というのも目に優しくないですし……な、悩ましい……

そうなんですよね…漠然とは、（置き換えではなく）ヘッダー下部などにバナーなどの

>（イラストコメントにニヤリとしましたｗ）

殆ど隠しテキストのようなものまでご覧戴いて！
有難い限りですｗ

> バナーに丁度良い素材がないなぁと思い、枠と30周年ロゴ以外は新規でミニっぽく作成しました～。

ありがとうございます！従来の枠を踏襲しつつも、既存2枚とは異なるテイストで固めて戴いて、良いアクセントになっているかと！「かいて、かいてちょうだい」は、まさに、ミニ30のアピールポイントですね！早速、本番サイトにも反映させていただきました～

これで、足掛け3年!!のサイトリニューアルもとりあえずは一旦のCloseですね。
重ねてありがとうございました！
