### ISSUE TITLE
【PgFlow】タブの整理

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#271]
param要素の追加によって、PgFlowのタブを整理する必要が出てきました（タブが2行になってしまうため）。
現時点で想定している対処案は以下です（△は想定しているデメリット）。

+ 右の領域幅を増やす（△：僅かながら左のチャート領域が減る）
+ タブの名前を短くする or アイコン化（△：視認性は若干悪化。また、短くする場合は名前要検討）
+ グループ化機能の削除（△：純粋な機能削減になる）
+ タブの2行化を許容する（△：タブによって占有される領域が増える。ただ、今後タブが増えた場合には対応はしやすい）

アイコン化が最も他への（機能的な）影響は少ないですが…ご意見うかがえれば幸いです。

**Comment by cocotori** [comment]
2行化に1票です。
今後、項目数が増えて来ればまた同じ問題が出てくると思われ、
それを一番先延ばしにしやすいかなと思いました。

また、現在もシーンとリンクだけはそのシーンに関わるもので、
他の項目は全体に関わるものなので分けたいという気持ちもあります。
（paramも全体？）

**Comment by toki-sor1** [comment]
ココさんが仰っているように、今後項目数が増えれば、その度に同じ問題が出てきてしまいますよね。
そうであれば**今の内に2行化に対応しておくのが良いかな**と思いました。

アイコンはメニューでも使用しているので、Pg Flowの見た目がごちゃっとしてしまいそうですし、やはり文字で表記されている方が分かり易いので。

**Comment by snext1220** [comment]
本件ご意見ありがとうございます！
こちらご意見うかがいながらなんですが、2行化がかなりごちゃっとして見えたので、一旦タブの文字サイズを落として1行にまとめてみました。い、如何なものでしょうか。

仰る通り、後々に問題を先送りしただけではあるのですが、次のタブが増える前に［シーン］［リンク］などのタブの扱いを別出しにするなど検討できればと思っています（cocoさんから戴いた件です）。 ＃ 現在はノーアイデアですが；

**Comment by cocotori** [comment]
この文字サイズであれば視認性も特に問題ありませんので、
大丈夫です！

**Comment by toki-sor1** [comment]
十分読める文字サイズだと思いますし、収まりもよくなったと思います！
