### ISSUE TITLE
［戻る］機能の改良

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#272]
#244 で実装していた［戻る］機能ですが、params属性と連動して機能を改善しました（GitHub Only）。
具体的には、

+ params属性に「p99:戻り先」を設定しておくことで、戻り先を決められる
+ params属性の指定がない場合には、従来通り、ブラウザーバック

戻り先を指定した場合には履歴に残るので、途中でゲーム終了しても元の場所に戻ることが可能になります。

**Comment by cocotori** [comment]
chromeで確認しました。
id90000に移動したときに、p99で指定されたシーンに移動すること、
そこでゲーム終了し再開したとき、ブラウザバックでその一つ前に戻れることを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 90.0.4430.93(64bit)にて動作確認。
正常に動作していました。

ただ、**Scene 0：戻るテスト→Scene 6：戻る→Scene 0：戻るテスト→Scene 6：戻るテストの順で選択していると、Scene 2に行ってしまいました。**

**Comment by snext1220** [comment]
ご確認ありがとうございます～

こちら［戻る］の方は単に0への戻るなので、今回は無視してやってください^^;
［戻るテスト］の方では、今回p99に1をセットしているので、Scene 1（not 2）に戻るかなと思いますが、如何でしょうか。
＃ 指定Sceneに戻ることが確認できるよう、あえてそのように設定していました^^;

なお、テストシナリオですが、私の手元でなんとなくの確認用に作成しているものなので、意図は判り難い（場合によっては正しく動作しない）ものがあるかと思います～あくまで参考程度の扱いとしてやってくださいませm(_ _)m
＃ 皆、同じ値でテストしてしまうと、問題を発見しにくくなるかな～という意味でも^^;
