### ISSUE TITLE
Pg Flowの表示崩れ

### ISSUE THREAD

**Issue by toki-sor1** [snext1220/stext#274]
Win 8.1／Chrome 90.0.4430.93(64bit)にて症状を確認。

GitHub版Pg Flowにて、「テンプレートを選択」からテンプレートを読み込むと、参照画像のようにエディタ画面の表示が崩れてしまいました。
この状態になると、新たにテンプレートが読み込めませんでした。

![image](https://user-images.githubusercontent.com/42646342/117677817-c37a4a80-b1e9-11eb-91bf-5c17fdb7658d.png)

**Comment by snext1220** [comment]
ご指摘ありがとうございます！
こちらbasic要素のsummary属性を新規に追加した故の問題でした（テンプレが対応できていませんでした）。
先ほどGitHub／本番環境双方に新テンプレを反映させましたので、キャッシュクリアの上でご確認くださいませ～

＃ あとは古い.jsonファイルを使った場合に問題が起こる可能性がありますが、、、別途検討いたします。

**Comment by toki-sor1** [comment]
お忙しいところ、迅速なご対応ありがとうございます！！
キャッシュクリア後にGitHub版、本番環境にて動作を確認。
各テンプレートを選択した後、表示が崩れなくなったのを確認しました！　ばっちりです！！

**Comment by cocotori** [comment]
chromeで確認。

一通りのテンプレートを読み込んで確認しましたが、
表示崩れは発生しませんでした。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeでテンプレート読み込みに問題ないことを確認しましたー
