### ISSUE TITLE
Pg Flowで内部パラのサイドバーが出ない

### ISSUE THREAD

**Issue by toki-sor1** [snext1220/stext#275]
Win 8.1／Chrome 90.0.4430.93(64bit)にて症状を確認（GitHub版と本番環）。
※参照画像は、GitHub版を撮影したものです

編集したいシーンを選び、「シーン」タブを選択した時には、「内部パラの空欄」をクリックするとサイドバーが出ました。
しかし、　他のタブを開く→「シーン」タブを開く　という手順を踏むと、「内部パラの空欄」をクリックしてもサイドバーが表示されませんでした（連投すみません……！）。

ただ、内部パラが登録されているテンプレートでは、上記手順を踏んでもサイドバーが表示されていました。
（内部パラが事前に登録されているかどうかが原因？）

**【追記】他の項目（アイテムやフラグ）は、データが登録されていない状態でもサイドバーが表示されていました。**

![image](https://user-images.githubusercontent.com/42646342/117683888-74cfaf00-b1ef-11eb-9c15-dbedc13cfd4b.png)

**Comment by toki-sor1** [comment]
あわわ、私の方こそ夜遅くまで作業をさせてしまい申し訳ありません……！
迅速にご対応いただき、本当にありがとうございます！！

なるほど、テンプレの影響でしたか～！
GitHub版と本番環境にて動作を確認し、先ほどの手順を踏んでも正常に内部パラのサイドバーが表示されていました！　ばっちりでございます～！

**Comment by snext1220** [comment]
こちらこそ夜遅くまでご確認ありがとうございます！
今回は大きくparams、basic要素が追加されたことで、システム／PgFlow／テンプレと影響箇所が広がってしまい、確認しきれていなかったようです；お手数をお掛けして申し訳ありません。。

建て増しの構造上、なかなかチェックが難しくなっているのですが、事あるごとにチマチマ内部構造の改善も行っておりますので、バグの混入も徐々に防ぎやすくなってくるかな～と^^;（と言いながら、機能追加がより速いので、中々追っつかないのですがｗ） 気長にお付き合いいただければ幸いです～

**Comment by cocotori** [comment]
chromeで確認。

他のタブを開く→「シーン」タブを開く→「内部パラの空欄」
という手順を踏んでも、
正常にサイドバーが表示されることを確認しました。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで特に問題ないことを確認しましたー
