### ISSUE TITLE
【PgFlow】シーンの検索機能

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#276]
PgFlowに検索条件でシーンを絞り込む機能を付与しようかと検討しています。

+ 特定キーワード
+ フラグ／アイテム／敵などの紐づけ

ただし、PgFlow2Editorを利用すれば、全文検索などはむしろ簡単なため、PgFlowにクローズすることに拘らないほうが良いのかという思いもあり。まずはニーズを伺えればと思います（ニーズある場合で、検索条件の要望があれば、こちらもお願いします）。

**Comment by cocotori** [comment]
検索したワードの出現箇所がリストで出てくれば、役に立つかもしれません。
ただ、積極的には使わないと思いますので、
個人的な優先度はそれほど高くないです。

**Comment by Salvadors-cabin** [comment]
これまでエディタの検索やgrepを使ってできていたと思うので、それほど必要ではなさそうです。
PgFlowに実装するのであれば、組み合わせで検索できると便利かもしれませんが。

**Comment by snext1220** [comment]
皆さま、ご意見ありがとうございます。
PgEditor、もしくはローカルなエディターで十分な感じですね^^;
あまりニーズもなさそうなので、次回Updateで特別ご意見なければwontfixでCloseとしていきたいと思います。

**Comment by toki-sor1** [comment]
検索機能ですが、私はそこまで必要性は感じません。
「特定の単語を修正したい」等、検索を使いたい状況を考えると、scenario.xmlに出力したものをエディタで読み込んで置換した方が楽かなと思っているので；

**Comment by snext1220** [comment]
皆さま、ご意見ありがとうございました！
PgFlowにクローズして作業したいというニーズがあるかな、とも思いましたが、現時点であまり必要性なさそうとのことでしたので、こちらはwontfix＆Closeにしていきたいと思います～
