### ISSUE TITLE
【PgFlow】フローチャートのコンテキストメニュー

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#277]
現在は、フローチャート上でシーンを選択した後、［シーン］タブから

+ シーンの追加
+ シーンの削除
+ リンクの追加

などを行う必要がありますが、これらをコンテキスト（右クリック）メニューにまとめられないかと思っています。特にシーンの追加などは頻繁に行う作業なので、作業効率化に役立つのではないかと。

それ以外にもコンテキストメニューで行いたい作業があればご要望お願いします（ある程度まとまったところで実装検討したいと思います）。

#### 追記

実装完了しました。チャート上でノードを選択した上で右クリックすることで、コンテキストメニューが表示されます。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でコンテキストメニューが問題なく動作しました。

**Comment by cocotori** [comment]
chromeで確認。

実装された3機能とも、正常に動作しています。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
正常に3つの機能が使えることを確認しました！
これはカーソルを行ったり来たりさせないでも追加等ができるので、楽で良いですね！
