### ISSUE TITLE
BattleSheet内部の画像埋め込みを可能に

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#278]
BattleSheet上の戦闘ルールに画像埋め込みを可能にします。
SGML式も有効となるので、これによって、ほぼほぼ本文同様にBattleSheet上の文章も修飾できるようになります。以前の @Salvadors-cabin さんのご要望もこれで満たすのではないかと。

GitHub Onlyですので、ご確認戴けますと幸いです。

**Comment by Salvadors-cabin** [comment]
ありがとうございます！
やり方は、ruleで指定したシーンに通常のシーンと同様に画像名を記述すればよいのでしょうか。
時間のある時に試してみたいと思いますー

**Comment by snext1220** [comment]
いえいえ。ご提案戴いてからすっかり時間が経過してしまいましたが、お役立ていただければと。
記述については、はい、本文と同じ要領で表せるようにしております～

**Comment by Salvadors-cabin** [comment]
GitHubで問題なく機能することを確認しました。
活用したいと思いますー

**Comment by snext1220** [comment]
ありがとうございます！
活用＞ぜひぜひ～

**Comment by cocotori** [comment]
chromeで確認。

戦闘ルールに画像を表示することができました。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
画像がBattleSheetに表示されるのを確認しました。
