### ISSUE TITLE
移動ボタン／ifの条件式で利用可能な関数

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#279]
条件式により複雑な判定式を表すことを可能にします。

```
fn:関数名(引数,...)
```

現在想定している機能は、以下のようなものです。

+ fn:rand(40)：40％の確率で表示するリンク（ #3 ）
+ fn:include(2,f1,f2,f3)：f1～3の中で2個以上存在すればtrue（i1、i2...も指定可）
+ fn:range(str,5,10)：STRの値が5以上10未満の場合にtrue（指定可能なキーは以下）
    + ステータス（hp、mp、str～krm、free1～3）
    + 内部パラメーター（p01...）
    + 経過シーン数（e）
+ fn:cycle(15,5,3)：1～5、6～10、11～15...（1周15までを3等分）としたときの1番目のグループ1～5、16～20...の範囲に経過シーン数が含まれる場合にtrue

複雑な条件判定を表す場合には、これらを拡張していければと（ご要望あれば是非ともお願いします）。

**上記4個の関数をGitHub Onlyで実装済みです**

**Comment by cocotori** [comment]
chromeで確認。

includeやrangeが正常に動作しています。

randですが、機能していますでしょうか？
rand(40)と入力して何度挑戦してもボタンが表示されず、
rand(100)でもだめでした。

あと、後出しで申し訳ありませんが
rangeは以上未満より以上以下のほうが自然ではないでしょうか？

**Comment by snext1220** [comment]
@cocotori さん：
ご確認ありがとうございます。

random＞スミマセン、こちらはドキュメントが誤っていました。randはrandomが正しいです；別途ヘルプ等も修正させて戴きますね。

range＞SQLやPythonなど、確かに既定は以上以下なんですよね。。
ただ、STextの場合は連続した範囲分岐を表しやすくするよう、以上未満としておりました。

#### 以上以下の場合

+ 40～50、50～60（重複してしまう）
+ 40～49、50～60（49～50に空白ができてしまう）

#### 以上未満の場合

+ 40～50、50～60（連続している）

加えて、他の条件分岐が基本以上条件で、否定が未満となるため、思想も統一できるかと。
内部パラメーターでも小数点数を使うことはあまりないかなとは思っているのですが^^;、こちらはできればママにできればと思うのですが、如何でしょうか。

（余談）実はoSTR～系の条件式だけがおかしな条件式になってしまっているのですよね...既存シナに影響が出るので、変更しにくいのですが、どこかで統一したい...現在は @toki-sor1 さんシナで使われていたのを覚えているのですが、他でも使われてましたっけ？＞皆さん

**Comment by cocotori** [comment]
他のものとの兼ね合いを考えた上での仕様なのですね。
わたしの方は今のままで問題ありません！

**Comment by cocotori** [comment]
fn:randも動くようになっていました！

**Comment by snext1220** [comment]
> （余談）実はoSTR～系の条件式だけがおかしな条件式になってしまっているのですよね...既存シナに影響が出るので、変更しにくいのですが、どこかで統一したい

上記の件ですが、やはり気になったので修正しました。

oHP50でHP50以上、!oHP50でHP50未満を表すようにします（ヘルプも反映済）。
一応従来のoHP50+のような表記も残していますが、こちらは非推奨扱いということで。
ぎりぎりのぶっこみで恐縮ですが、条件式判定とコアな箇所なため、皆さんの環境でもご確認いただけますと幸いですm(_ _)m ※本番環境反映済みです。

**Comment by Salvadors-cabin** [comment]
Win+Edge環境でrange(),rand()が機能していることを確認しました

>fn:cycle(15,5,3)：1～5、6～10、11～15...（1周15までを3等分）としたときの1番目のグループ1～5、16～20...の範囲に経過シーン数が含まれる場合にtrue

これですが、理解が追いついておらず、期待した結果ではありませんでした。
もう少し詳しく説明していただけるとありがたいです。
上の例の場合cycle(15,5,3)：
15・・・1周のシーン数
 5・・・これはなんでしょうか？
 3・・・「3等分」の3？

>（余談）実はoSTR～系の条件式だけがおかしな条件式になってしまっているのですよね...既存シナに影響が出るので、変更しにくいのですが、どこかで統一したい...現在は @toki-sor1 さんシナで使われていたのを覚えているのですが、他でも使われてましたっけ？＞皆さん

「ラミディア」ではMPの判定にoMP+を使っています。特に問題は見られませんでした。

**Comment by snext1220** [comment]
@Salvadors-cabin さん：
ご確認ありがとうございます！

取り急ぎですが、cycleについてです～
たぶん、この辺が回答になっているかと思います。

https://github.com/snext1220/stext/issues/245#issuecomment-835148112
https://github.com/snext1220/stext/issues/245#issuecomment-855683077

複雑な関数で恐縮ですが、如何なものでしょうか。

> 「ラミディア」ではMPの判定にoMP+を使っています。特に問題は見られませんでした。

ありがとうございます！問題なさそうでよかったです～

**Comment by Salvadors-cabin** [comment]
#245 の例では、以下のようになってますね。

>改めて以下のイメージです（e30:3:1の場合）。
>
>0～10：朝
>11～20：昼
>21～30：夜
>31～40：朝（以降繰り返し）

上記は1周30までを3等分して、「朝」がtrueという意味と思います。

>fn:cycle(15,5,3)：1～5、6～10、11～15...（1周15までを3等分）としたときの1番目のグループ1～5、16～20...の範囲に経過シーン数が含まれる場合にtrue

こちらの例cycle(15,5,3)では３項目目の3で等分という意味で合ってますか？
その場合、1番目のグループをどこで指定するのかがわかりません。

**Comment by snext1220** [comment]
先ほど出がけに慌ててお返事してしまいましたが、スミマセン、以下は例が間違っていますね。。。

> fn:cycle(15,5,3)：1～5、6～10、11～15...（1周15までを3等分）

正しくは、fn:cycle(15, 3, 1) ですね。失礼致しました。
1周15シーンを3分割した時の1グループ目を表します。

改めてこれにてご確認いただけますでしょうか。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
fn:rand、fn:include、fn:range、fn:cycleが正常に動作していたことを確認しました。

> 現在は @toki-sor1 さんシナで使われていたのを覚えているのですが、他でも使われてましたっけ？＞皆さん

自シナリオで確認しましたが、正常に動作していました～。

**Comment by Salvadors-cabin** [comment]
説明ありがとうございます。

>正しくは、fn:cycle(15, 3, 1) ですね。

あらためて試してみました。
どうも1～5のとき、16～20とき、それぞれの範囲で１回だけしかtrueにならない感じです。
他の環境では大丈夫でしょうか。
テストは、繰り返し訪れるシーンにfn:cycle(15, 3, 1)を設定してテストしました。（ブラウザの戻るではありません）

**Comment by snext1220** [comment]
度々すみません。ドキュメントと食い違いがあったため、作った本人が大混乱していました。改めてですが...

fn:cycle(15,5,1)

で1～5、6～10、11～15...（1周15シーンを5シーンごとに分割＝3等分）としたときの1番目のグループ1～5、16～20...の範囲に経過シーン数が含まれる場合にtrueとなります。

＃同じく、fn:cycle(15,5,2)で第2グループ（6～10、21～25...）、fn:cycle(15,5,3)で第3グループ（11～15、26～30...）がマッチします。

何度もお手数をおかけしますが、どうぞよろしくお願いいたします；

**Comment by Salvadors-cabin** [comment]
>fn:cycle(15,5,1)

ようやく理解できました。
これなら期待した結果と一致しています。
ありがとうございました！

マニュアルは以下のようになっていたので直しておいた方がよいかと思います。
>fn:cycle(15,5,3)：1～5、6～10、11～15...（1周15までを3等分）としたときの1番目のグループ1～5、16～20...の範囲に経過シーン数が含まれる場合にtrue

マニュアルは項番何番目が何を示しているか、を説明した方がよいと思いますね。

**Comment by snext1220** [comment]
@Salvadors-cabin さん：
早速のご確認ありがとうございます！何度もお手数をおかけしました；

ヘルプですが、恐らくキャッシュで古くなっているようです。現在のものは...

> fn:cycle(15,5,1)：1～5、6～10、11～15...（1周15シーンを5シーンごとに分割＝3等分）としたときの1番目のグループ1～5、16～20...の範囲に経過シーン数が含まれる場合にtrue

一応、各引数の対応する値を文言にも入れている形にしておりますが、如何でしょうか（体裁的に「引数xxxは～」とまで個々に表していくのは冗長に思えた為、このような形にしています～）

**Comment by Salvadors-cabin** [comment]
ありがとうございます。ヘルプの修正確認しました。

すみません。前の書き込みはWebのシナリオ開発リファレンスの方でした。
https://sorcerian.hateblo.jp/entry/2018/11/01/211745
こちらもよろしくお願いしますー

>一応、各引数の対応する値を文言にも入るような形にしておりますが、如何でしょうか（体裁的に「引数xxxは～」とまで個々に表していくのは冗長に思えた為、このような形にしています～）

そうですね。初見の方が分かるかな、、とは思いますが、プロ仕様な感じなのでこのくらいの表記でよいと思います。

**Comment by snext1220** [comment]
ご確認ありがとうございます！
リファレンスの方は修正させて戴きました～
ただ、こちらはヘルプリリースに伴い、更新とめてしまっておりますため、お手数ですが、今後はヘルプの方を参照くださいませm(_ _)m ＃ 一応赤字でアラームしていますが、実は消してしまった方が良いかも？

> 初見の方が分かるかな、、とは思いますが、プロ仕様な感じなのでこのくらいの表記でよいと思います。

ご了承いただき、恐縮です；
確かに関数あたりから段々と仕様も複雑になってきて、記述も複雑化していますね。。
あまりに初心者お断り的になっていくのも避けたいので、ドキュメントも随時見直していきたいと思います。
