### ISSUE TITLE
変更後のbgm不反映について

### ISSUE THREAD

**Issue by RYU-DS** [snext1220/stext#28]
GBATでの
●シーン1の設定
@@
@main:WinterPub
@happy:@end02
@bad:@town01
@bgm:
w:WinterPub「冬の酒場にて」:bgm:しんさんわーくす:dova-s.jp/bgm/play5472.html
@@
●badendシーンの設定
@@
@end:bad
r1:さあ無に還ろう:1:その意気やヨシ！(　´∀｀)Ь
@result:r1
@@
としているのですが…あ、「@bgm:」は入れ忘れていて今入れましたが、badendbgmも現状鳴っていないようです。

**Comment by snext1220** [comment]
構文に誤りがあるようです。以下のようにお願いします。
```
@@
bgm:WinterPub:@end02:@town01
@@
```

構文、例については、以下でも触れているので、「bgm」で検索＆ご確認戴けますと幸いです。
https://sorcerian.hateblo.jp/entries/2018/01/31

**Comment by snext1220** [comment]
ファイルの再送ありがとうございます。
反映し、bgmは正しく再生されているようです。

＃ それとは別に、ボタンの表示が一部おかしくなっている?ところ、WIZARDのスペル誤りなどがあるようでした。こちらはまた改めてまとめますね。

**Comment by RYU-DS** [comment]
bgm再生確認しました。ミス箇所も指摘お願いします・・・
