### ISSUE TITLE
初めての実績取得でエラーが発生

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#280]
そのシナリオで初めて実績を取得する場合に内部的にエラーが発生していました（記録には問題なし）。
こちらを修正し、正しく実績カウントされるようにしています。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で確認。
自シナで問題なく実績が取得できました。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
実績が正常に取得できました。
