### ISSUE TITLE
【PgFlow】［ライセンス］タブの不具合

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#284]
鏡読みさんからＤで戴いた内容に基づいて、Issueを立ち上げています。

> そういえば、今回もplaygroundを利用したのですが、ライセンスをすべて消した状態で別のタグを開き、ライセンスを開き、もう一度別のタグを開き、ライセンスを開くと自動で空のＢＧＭがライセンスに入ってしまう挙動がありましたので一応報告しておきます

確定前の既定値が見えてしまっている状態が、タブを開いたタイミングでデータとして確定されてしまうという問題と思われるので、修正いたします。

**Comment by snext1220** [comment]
本件、GitHub Onlyで対応済みです。
分類の選択ボックス既定値を空文字列にしました。
残念ながら、これでもライセンスタブを開いたタイミングで内部的には空データが出来てしまうのですが、XML出力時にはサプレスされますし、そもそもライセンス情報ゼロはほぼないので、これで良いかなと。如何なものでしょうか。

＃ 弐についても実はとくしさんのドット絵はライセンス情報追加お願いするか迷って。何度もの指摘になってしまうのもアレなので、結局なかったことにしてました^^;

**Comment by cocotori** [comment]
chromeで確認。

空のBGMが入る現象は発生しませんでした。

これで動作は問題ないと思うのですけど、
なんだかライセンスだけ他のタブとは挙動が違うような気がしますね。

アイテムの効果対象、敵の属性なども
ライセンスの分類と同じリスト選択に見えるのですが、
空の項目が増えるのはライセンスだけでした。

（特に直してほしいというものではないです。）

**Comment by snext1220** [comment]
@cocotori さん：
ご確認ありがとうございます！
挙動が違う＞こちらはライセンスのみ主キーがないための問題ですね～他はidが入っていないと弾かれるのですが、ライセンスではガードが掛っていないという；

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
ライセンス情報を全て削除した後、他のタブを開いてからライセンスタブを開くと、空白の情報が追加されていました。
しかし、Flow→Editorに切り替えたところ、ライセンス情報はなくなっていました。
（Flow→Editor→Flowでもライセンス情報がなくなっているのを確認）

最終的には空の情報がなくなるので、特に問題がなければままでも良いかなと思いました。

> ＃ 弐についても実はとくしさんのドット絵はライセンス情報追加お願いするか迷って。何度もの指摘になってしまうのもアレなので、結局なかったことにしてました^^;

全ての修正点をまとめて気が付けば良いのですが、後々になって気付いた時には修正依頼が重なっていたりと、お願いし難い状況になるのはありますね；
ただ、そうですね、**弐では現在の実積率に京都動乱の分を追加する必要がある**ので、次回のシナリオ更新時にライセンス情報の追加をお願いするのはいかがでしょうか？

**Comment by snext1220** [comment]
@toki-sor1 さん：
ご確認ありがとうございます！

> 最終的には空の情報がなくなるので、特に問題がなければままでも良いかなと思いました。

はい、上記の通り出力時にはサプレスされるので＆ライセンス情報が空ということはほぼないはずなので（最低限intro.pngの情報がある筈）、ここはママとさせてくださいませ。

> 弐では現在の実積率に京都動乱の分を追加する必要があるので、次回のシナリオ更新時にライセンス情報の追加をお願いするのはいかがでしょうか？

はい、賛成です。
こちらは @cocotori さん作業になりますでしょうか？
お手数ですが、どうぞよろしくお願いいたします～
