### ISSUE TITLE
ライブラリをローカルサーバーへ移動

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#285]
現在、システム本体／PgFlowのライブラリ（画像含む）の一部をCDN（外部サーバー）に頼っています。
パフォーマンスの向上などのメリットはありますが、外部サーバーが落ちた時、将来的にCDNが廃止になった場合など、ツール自体が使えなくなる可能性があります。

これを防ぐため、すべてのライブラリをweb-deli.comに移動しました。これに伴い、一部のライブラリをバージョンアップ、また、構成を変化するなど、細かな修正を行っています。基本的な挙動は当然変化しないはずですが、内部的には大きな変更となるため、システム本体／PgFlow共に一度全体を触れてみて戴けますと幸いです。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で確認。
自シナを中心に問題ないことを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
こちらの環境でも問題なく動作していることを確認しました～。
