### ISSUE TITLE
【PgFlow】スニペット機能の追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#286]
現在はツールバーからSGML式を追加していますが、エディター上でも式候補が表示されるようにスニペット機能を追加しています。よりエディター上に完結した入力が可能になったので、ぜひご利用ください。

スニペット機能の利用方法についてはPgFlowのマニュアルから「スニペット」で検索ください。
https://sorcerian.hateblo.jp/entry/2019/05/03/211951

これによって、ツールバーの［カーソル位置にタグを追加］の意味合いが若干弱くなるので、将来的には整理を検討したいと思います。以下候補ですが、ご意見いただければ幸いです。

+ 特に整理しない
+ if、rubyなど、既存テキストに対して適用するSGML式のみ残す（既にあるテキストに対してタグを適用する場合には、［カーソル位置にタグを追加］の方が便利かもしれません）
+ ［カーソル位置にタグを追加］を完全に削除

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで特に問題なく動作しました。

>ツールバーの［カーソル位置にタグを追加］

視覚的に分かりやすいのでツールバーにもあってよいと思います。
特に整理しないに一票です。

**Comment by cocotori** [comment]
便利になったと思います。

スニペットはその単語を一文字二文字でも知らないことには
出せないと思うので、
一覧として見られる「カーソル位置にタグを追加」は、
そのまま残しておいていいのではないかと思います。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
正常に動作することを確認しました。
便利で良いと思います！
私はツールバーの［カーソル位置にタグを追加］をよく利用しているので、残していただけると助かります～。

**Comment by snext1220** [comment]
皆さま、ご意見ありがとうございます！
ツールバーの［カーソル位置にタグを追加］については残した方が良いというご意見多数でしたのでママとしてまいりますね…！
