### ISSUE TITLE
【PgFlow】エディターの制御文字を除去

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#287]
長らく問題になっていた点の改善です。

従来、PgFlow上のエディターで日本語を入力する際、先頭部分にアイコンのような文字（制御文字）が表示されていました。これを今回の修正で改善し、表示しないように改めています（GitHub Only）。
些細な修正ですが、だいぶ日本語入力がしやすくなったと思うので、ご確認ください。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで表示に問題ないことを確認しました。

**Comment by cocotori** [comment]
chromeで確認。

おかしな文字の出ることがなくなりました！

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
制御文字が表示されないことを確認しました！
