### ISSUE TITLE
SGML式で職業、ステータスを表示

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#288]
SGML式で表示できる内容を強化しました。
特別重要度が高かったわけではなかったのですが、基本はセーブデータで持っている内容は最大限取得できた方が良いだろうということから、対応しています。

+ ${job} … キャラの職業
+ ${xxxxx} … キャラのステータス（xxxxxはhp、mp、str、int、dex、krm、free1～3のずれか）

これでセーブデータで持っている情報のかなりの部分を自由に表示できるようになったはずです。

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境で問題なく動作しましたー

**Comment by cocotori** [comment]
chromeで確認。

jobからhp～free3まで確認しましたが、
正しく動作していました。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
全て正常に表示されていました。
