### ISSUE TITLE
「ボタンを等間隔に成立」が反映されていない？

### ISSUE THREAD

**Issue by RYU-DS** [snext1220/stext#29]
＞非表示中のボタンがある場合に生じる空行を除去（ボタンを等間隔に成立）
がどうも反映されていないようです。
占いの診断前の「これじゃ！」が広い空間にポツンと表示されてしまってますが…

**Comment by snext1220** [comment]
溜めを入れているのか、と思っていたのですが、違いましたね^^;

こちら、非表示ボタンの**間**の`<br>`を削除していましたので、現時点ではコードそのものは正しく動作しています（当初、頭に大きく空行が出るケースを想定していなかったため）。
ただ、勿論仕様として問題なので修正してまいります（地味に、しくじると全体に影響が及ぶ修正なので＆結構複雑なことをやってるので、暫しお時間をください）。

**Comment by snext1220** [comment]
先程、問題を修正しましてGitHubに反映しました。ご確認戴けますと幸いです。

**Comment by RYU-DS** [comment]
確認しました。ありがとうございます。
でもこれ、意外に「あれ？空白開いてる…別の選択肢あるな？」という攻略に使える要素でもあったんですよねｗ
今回の占いのみたいなのは、単にみっともないだけなのですっきりしてとてもいいんですが。

**Comment by toki-sor1** [comment]
Chrome、iPhone両環境にてGitHub版の動作確認を行いました。
非表示のボタンがあるSceneの空白分が詰められた正常な状態で表示されているのを確認致しました。

**Comment by snext1220** [comment]
RYUさん、ときのじさん＞ご確認ありがとうございます！

攻略に～＞はい、これはSTextチーム内部でも話題になりましたｗ
まあそこは、必要に応じて文章で補っていくということで^^;
