### ISSUE TITLE
ゲーム画面でのシナリオデータ全文出力

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#291]
https://twitter.com/yy7512/status/1412332803136516096 由来のIssueです。
あまりニーズはないかもしれませんが、内部的に出力していたテキストにパラグラフ番号も付け、改行でより見やすくしてみました。完全に裏技ですが、内部をハックしたい人にご利用いただければと思います。

＃ ちなみに、STextでは極力ゲームブックの「ずる」を最大限サポートできればと思っています。本件はその一環です。 参考：https://chanagame.hateblo.jp/entry/2018/06/16/091718

**Comment by cocotori** [comment]
chromeで確認。

upしたxml相当の内容で、シナリオデータを見ることができました。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
パラグラフ番号もつき、かなり読み易い状態でテキストが表示されるのを確認しました。
シナリオの内容（ストーリー）をさっと確認したい時、便利で良いと思います。
