### ISSUE TITLE
【PgFlow】ダイナミックヘルプの改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#293]
現在、PgFlowからリファレンスページ（ブログ）にリンクするようになっていますが、個々の項目をダイアログ表示できればと思っています。

データの一元化から始まるので、大規模な改定になりますが、目的の項目がより理解しやすくなることを期待しています。

伴い、現在のようなリファレンスページは本家サイトで集約するようになるかもしれません（この辺、データ管理の側面から検討していきます）

#### 追記

本件、まずはGitHub Onlyで対応済みです。
まだテキストはブログからのコピーなので不完全ですが、機能としてはほぼ動作しているはず。
今後、本家サイトへの集約をしながら、テキストもブラッシュアップしていく予定です。

**Comment by cocotori** [comment]
これはものすごく便利になったと思います！
対応ありがとうございます。

flowから離れる必要がなくなったので、
執筆が中断されることがなくなったのは、とても効果が大きいと思います。

文章内容の全ては確認できていませんが、
使いながら、何かおかしいところがあればご報告させてもらえればと思います。

**Comment by snext1220** [comment]
御確認ありがとうございます。
実装以上に、既存ドキュメントのデータ化に時間がかかったので、ご評価嬉しいです^^;

何かおかしいところ＞はい、是非お願いいたします。
ブログ文章の組み換え＆PgEditorとの共有なので、細部は諸々ありそうですが；、こちらでもボチボチと再点検していければと。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeでヘルプが表示されることを確認しました。
「基本」「シーン」タブだけダブルクリック時の説明がないのは何か理由があるでしょうか。

**Comment by Salvadors-cabin** [comment]
なるほど。了解です！

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
ヘルプが表示されるのを確認しました！
DM内容と重複してしまうのですが、ヘルプが必要な箇所だけ表示されるので、見やすくてとても良いですね！
ページの往復がないのも、確認が楽で良いと思います！
