### ISSUE TITLE
item要素のtarget属性を拡張

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#294]
内部パラメーターに対応します。

+ target="param"
+ effect属性にはscene要素のparams属性相当

の指定を可能にします（GitHub Onlyにて公開済）。

**Comment by cocotori** [comment]
chromeで確認。

paramを指定したアイテムを使用すると、内部パラメータが変更されることを確認しました。

flowではitemタブの効果対象からparamを選択することが
まだできないようですが、それはこれからでしょうか？
（テストではeditorに移動して設定しました。）

こちらの機能の使いみちについて考えていたのですが、
具体的な状況が思い浮かびませんでした。
itemの個数の概念 #295
と合わせて考えると、#295の方で
アイテムと専用の内部パラメータが紐付いているので、
わざわざこちらの機能で他の内部パラメータを変更できる必要がないように思いました。

**Comment by cocotori** [comment]
追記：

と、思いましたが、
アイテムは消費してなくなってしまうが、
内部パラメータは0ではない
（アイテムの効果が回復等）
場合はアイテムのtargetにparamを指定できたほうがいいですね。

すみません、先の投稿の後半部分は無視してください。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

> flowではitemタブの効果対象からparamを選択することがまだできないようですが、それはこれからでしょうか？

とと、失礼しました。純粋に抜けでしたので、先ほど反映いたしました～

> アイテムは消費してなくなってしまうが、～～

はい、自動での紐づけはあくまで個数なので、アイテムそのものの効果を内部パラメーターで管理されたシナ固有情報（たとえば恐怖度など）に反映させたい場合に必要になるかと思います。もちろん、そのような情報は殆どの場合、freeXを使うはずですが、明示的に見せたくない or freeNを使い切ってしまった、などの場合は、内部パラメーターを使うことがあるかなと。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeでitem使用時にパラメータが変更することを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
該当Sceneにparam設定して、使用できるアイテムの対象をparamにして効果値を設定すると、USEボタンを押してもアイテムが消費されませんでした。

**Comment by snext1220** [comment]
@toki-sor1 さん：
ご確認ありがとうございます！
こちらですが、当方テストデータでは確認できず、申し訳ありませんが、発生したシナリオデータをお送り戴いても宜しいでしょうか。お手数をおかけします。。

**Comment by toki-sor1** [comment]
その時のデータは破棄してしまったので、新規データにparamを設定してみました；
ただ、私がイマイチparamを理解できていないため、単に設定ミスかもしれません；；
https://1drv.ms/u/s!AoLnW1UCwjdI018K9ZQLHbZHRBkq?e=Kk9mb4

**Comment by snext1220** [comment]
@toki-sor1 さん：
データを戴き、ありがとうございます！
こちらにて戴いたデータを修正して動かしてみましたので、ご確認ください～
[param.zip](https://github.com/snext1220/stext/files/6950379/param.zip)

＃ ヘルプなどこう書けばわかるのに、などあれば、何なりとお願いいたします～

**Comment by toki-sor1** [comment]
データのご確認＆修正ありがとうございます！
ああ～～効果値の書き方がいけなかったのですね……！
今度はアイテムがUSEボタンを押すと減り、次のSceneにparam値が変動していることを確認しました～！

> ＃ ヘルプなどこう書けばわかるのに、などあれば、何なりとお願いいたします～

回復アイテムの表記の仕方など、すっかり失念しておりましたので（大汗）、効果値の表記一覧があると良いなと思います。

- 10　10増える
- -10　10減る
-  1..10　1～10増える
- full　全回復（最大値以上は増えない）
- p01:10　p01（param）が10増える（効果対象paramの場合）

**Comment by snext1220** [comment]
@toki-sor1 さん；
早速のご確認ありがとうございます！

effect属性のヘルプについてですが、targetによって変化しますので、現在は以下のようにヘルプ表記しておりました。

```
アイテムの効果を表します。target属性に応じた影響値（5、1..5、fullなど）を指定してください。
利用可能な設定値は、**scene要素の対応する属性を参照してください**（たとえばhpであれば、scene要素のhp属性で指定できる値だけが指定できます）。
```

恐らく今後対応する属性をUpdateした時に更新漏れの原因ともなるので、こちらはそれぞれの属性に委ねる、としておいた方が良いかなと思ったのですが、如何なものでしょうか（ご要望に反するお返事でスミマセン；）。

**Comment by toki-sor1** [comment]
お返事ありがとうございます！
いえいえ、こちらこそ見落とし申し訳ありません……！
各種scene要素の属性をクリックした時に、指定方法が参照できましたね……！

ただ、すみません、「scene要素の対応する属性を参照」＝シーンタブの各属性をクリックしてヘルプを表示させる、というのが現在の説明文からだと少し分かりにくいような印象です；

例えばですが、「利用可能な設定値は、シーンタブのアイテム、内部パラといった各項目名をダブルクリックすると詳細が参照できます」のように、**scene要素という書き方ではなく、シーンタブから参照できるよ**と具体的に書かれている方が分かり易いように思います。

**Comment by snext1220** [comment]
ご指摘ありがとうございます！
参照系は、確かに課題ですね。。

> シーンタブのアイテム、内部パラといった各項目名をダブルクリックすると詳細が参照できます

そうなんですよね。。本来はここまで細かく記述できるのが望ましい、、、のですが、ドキュメント自体がFlow/Editorで共有しているもので、説明がどうしてもふわっとしてしまうという。。保守性の観点からEditor／Flow向け専用のドキュメントを別個にしてしまうのもあまり嬉しくないので、かといって、双方向けの記述を入れてしまうと、却って判り難く思え（どうしようもない箇所はNote入れてるのですが；）。たとえば参照などを入れてリンクできるようにする、なども検討しています。

いずれも一長一短あり＆見せ方をどうするかなどちょっと悩ましいので、一旦、 #191 に移動して継続検討とさせて戴いても宜しいでしょうか。
