### ISSUE TITLE
item要素の個数の概念を追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#295]
内部パラメーターを利用して、アイテムに個数の概念を追加します。

+ アイテム情報はこれまでと同じくitem要素で定義
    + i99に対してpi01（p+アイテムid）のような内部パラを自動生成
+ scene要素のitems属性で「i01:@5,...」のような指定を可能にする
    + 指定方法はparams属性のそれに準ずる
    + 内部パラ0でアイテムを削除（-i～は使用しない）
+ 個数指定可能なアイテムは利用可能である（target属性を持つ）こと

GitHubにて機能を実装済みなので、お試しいただければ幸いです。

**Comment by cocotori** [comment]
chromeで確認。

flowの@5や5が反映されること、
実行中のメニューのuseで個数が減ることを確認しました。

現状target属性をもつアイテムに限定しているようですが、
target属性がないアイテムでも個数の概念があってもよいのではないでしょうか。
使用不可な重要アイテムをいくつ入手する、といったシナリオに利用できると思います。

システム的に実現しにくい、というのがあればそのままでも大丈夫です。

**Comment by snext1220** [comment]
ご確認ありがとうございました！

使用不可な重要アイテム＞こちらは漠然と既存機能と切り離す目的で「使用可能なアイテム」に限定しておりました（target付きのアイテムはまだほとんど利用されていない筈なので）^^;
先ほどコードを確認したところ、一応、target属性がないアイテムに適用しても、それなりに行けそうかなとは思っていますが、シナの作りに矛盾ができないかが少々気にはなりますね。。

引き続き検討してまいりますが、もし「こういう時は大丈夫か？」などあればお知らせください＞皆さん

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でitemが複数化でき、0になるまで使用できることを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
最初、指定方法（Itemの個数を設定する場所）に戸惑ったのですが、param属性のところにpi01で各値を設定するのですね。
アイテムが複数所持できて、背ってした個数を使い切るとなくなるのを確認しました。

**Comment by snext1220** [comment]
@toki-sor1 さん：
ご確認ありがとうございます。
いえ、個数についてはitems属性で指定が可能です（内部的にparams属性でもいけてしまうのですが、あくまでハック的な書き方なので、将来的な保証は（ry）。詳しく（というほどではありませんが^^;）はヘルプをご確認ください～

**Comment by toki-sor1** [comment]
ご説明いただきありがとうございます！
items属性で指定できました！
