### ISSUE TITLE
【PgEditor】ヘルプツリーの追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#296]
#293 の対応に伴い、PgEditorにタグリファレンスを組み込みました。
ヘルプデータがまだ完備できていないので、細部な問題はありますが、ほぼほぼ旧来のブログレベルの情報はPgEditor上で得られるかと思います。
https://www.web-deli.com/sorcerian/text/playground/editor.html
＃ 再編の副作用として、Flow2Editorの機能がGitHub Pagesでも利用できるようになる予定です（現在は未対応）

本件対応に伴い、

+ ブログ側のマニュアルからタグドキュメントは取り除いていくことになるかと思います（情報の分散は避けたいので）。
+ また、SGML式や条件式の記述なども、今後Playgroundに組み込むなり、既存ドキュメントを再編するなりしていく予定です。★済★
+ テストが完了し、安定したことを確認次第、現在公開中のPgEditorは削除していく予定です。

**Comment by cocotori** [comment]
ページの移動なく詳細情報がわかるのは手軽なので
非常にありがたい機能だと思います！

その一方で、従来のヘルプページはページ一枚になっていて
見通しはよかったのでなくしてしまうのは少しさみしいかな・・・と思います。
（検索もしやすいので）

ただ情報の分散を避けるというのもよくわかりますので、
管理のしやすいやり方を採ってもらえればと思います。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

ページ1枚＞こちらは必要性に応じて、現在のヘルプデータから動的に1枚形式のヘルプを生成するようにすれば、似たものを残すことはできるかと思います（ブログ側でなく、本家サイトの方への掲載になる＆データの再編は必要になりますが^^;）。

あとは、どのような使い方をされていたか、ですかね～

+ 要素／属性名で検索されていたならば → ヘルプツリーそのものに検索機能を付けるのがむしろ手軽かも
+ 全文での検索をされていたならば → 1枚形式のヘルプページを設ける
+ 特定の要素配下の属性を一望したいならば → 現在のツリーの要素ヘルプで、要素概要だけでなく属性ヘルプもまとめて表示する

などなど。ある程度慣れを待ってからの方が良い面もありそうですが、その他も具体的な用途伺えれば改善もできるかと思うので、引き続きご意見頂ければ幸いです～

**Comment by cocotori** [comment]
基本的には要素名・属性名で検索していたので、
ヘルプツリーに検索機能があるとありがたいです。

**Comment by snext1220** [comment]
こちら早速検索機能を追加してみました。
ツリー上部のテキストボックスにキーワードを入力すると、部分一致した要素／属性だけに絞り込み表示される感じです。ご利用ください～

**Comment by snext1220** [comment]
とりあえずFlow／Editor共にヘルプ機能そのものは問題なさそうなので、Pg上のメニューバーから辿れるヘルプリンクも改めて整理しました。これで対応するドキュメント、discussionも辿りやすくなったのではないかと…！

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でPgEditorのヘルプツリーが機能していることを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
ヘルプツリーが正常に表示されているのを確認しました。
目当てのヘルプを見付けやすいところも良いですね。
