### ISSUE TITLE
【PgEditor】スニペット挿入の改善

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#297]
PgEditorでのタグ追加、SGML式の機能をPgFlow相当に更新しました。
完全網羅ではありませんが、ほとんどのタグ／式を組み込めるようになったはずです。

#### 補足

もともとPgEditorのヘルプツリーからコンテキストメニュー（Snippet）を選択することで、現在のカーソル位置に要素／属性のスニペットを追加できるようにする予定でしたが、ヘルプとスニペット追加と、機能が混在することで却って判り難くなったので、既存機能の正統進化にしました。

折角ヘルプツリーがあるので、こんな感じで組み込めれば良い、などあればご提案ください。

**Comment by cocotori** [comment]
スニペットというのは例えばaと入力したときにattack, ageと表示されるような、
候補表示のことでしょうか？

細かい構文を忘れてしまっても
補助をしてくれるので、大変便利な機能だと思います。

少しだけ危惧しているのは、
aと入力し改行しようとしてエンターキーを押すと
attackになってしまうので、候補にない単語は逆に入力しづらいと感じました。
（aと入力したければ、a+スペースキーと入力し、わざわざバックスペースで消す必要がある）

プログラマー向けエディタもそんなような動作になっていたと思うので
機能として間違いがあるわけではないと思うのですが。

playgroundは日本語を含めいろんな入力がなされる可能性があるので、
候補入力の方を一手間入れる
（例えば、候補が出たときに、下キーを押してからエンターキーを押すと
　候補が入力される、とか）
ほうが使いやすいかなと思います。

とはいえ、半角英数を文章の中で使う機会が
どれほどあるかという話でもありますし、
現状の機能でも特に不満はないです。

**Comment by snext1220** [comment]
言葉の定義がはっきりしておらず、申し訳ありません。

**スニペット＝ツールバーからのタグ、SGML式の埋め込み** になります。大した修正ではないのですが、最近追加された式／属性を選べるように追加しております。

ご指摘のオートコンプリート機能についてなのですが、現時点でそのようになっておりませんでしょうか。

![無題](https://user-images.githubusercontent.com/27911337/127794803-325cb91c-915c-4a98-b84b-66e9908ec1bd.png)

ただ、スニペット機能で十分ですし、細かな属性の追加はそもそもFlowを利用した方が便利と考えると、オートコンプリート機能自体をオフにしてしまうのもありなのかもしれません。

この辺はご意見頂ければ検討してまいりますので、引き続きよろしくお願いいたします。

**Comment by cocotori** [comment]
勘違いをしておりました！
ツールバーのボタンから一通り入力を試してみて、問題なさそうです。

オートコンプリート機能はそうですね、
あればあったで便利な気もしますし、逆に
煩わしさもあるような気もします。
いずれにしてもわたしはflowの方をメインで使おうと思っているので、
editorをよく使われる方の意見を聞いてみたいところです。

**Comment by snext1220** [comment]
私も基本はPgFlowがメインですね^^;
＃ 実はMarkdownの編集作業であれば、現在でもFlowのエディターの方が高機能であるという；

今回ヘルプツリーの実装でやや再開発していますが、開発の比重もPgFlowに行きがちなので、PgEditorを主に活用されている方のご意見には大変興味があります！

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
ツールバーから各種タグを追加できました。
Flowでもよく使っているので、こういう機能はありがたいです。

Editorは、同じリンクの追加（コピペ）がFlowよりも楽なので、主にリンクのコピペ時にFlowから切り替えて使っています。
しかし、FlowとEditorではタブが別々なので、FlowとEditorを切り替えた後、調べもので別のタブを開いてPlaygroundに戻る時に誤って切り替え前のEditorまたはFlowの古いデータを再編集してしまうかも、と思うことがあります。

**Comment by snext1220** [comment]
@toki-sor1 さん：
ご確認ありがとうございます！

確かに大量リンクの複製は圧倒的にEditorの出番ですね～
ちなみに、Flowでもリンクのコピーを検討したりしていまして。「既存シーンのリンクを指定シーンにすべてコピー」のようなことを考えているのですが、ニーズありますでしょうか（Flowに作業をクローズできれば、という趣旨ですが、Editorの方が却って手軽？）。

> 調べもので別のタブを開いてPlaygroundに戻る時に誤って切り替え前のEditorまたはFlowの古いデータを再編集してしまうかも、と思うことがあります。

この辺、PgFlow／Editorもいずれは統一していきたいと思ってはいるのですが…まったく構造が違うツールなので、これは改めて落ち着いてから、ですね^^;

もう少し小規模な対応としては、そもそも互いに移動したときには、元のタブは閉じてしまうということは可能かと思います（現在は閉じるガードもかかっているので、詳細は要検討）。地味に使い勝手にも影響すると思うので、こちらはもう少しご意見うかがえれば幸いです～

**Comment by toki-sor1** [comment]
> ちなみに、Flowでもリンクのコピーを検討したりしていまして。「既存シーンのリンクを指定シーンにすべてコピー」のようなことを考えているのですが、ニーズありますでしょうか（Flowに作業をクローズできれば、という趣旨ですが、Editorの方が却って手軽？）。

Flowを主に使っている場合、ご提案いただいた機能があると便利そうですね。
ただ、Editorでの「コピペしたいSceneの内容を確認しながらコピペできる」というところが、安心感があって良いなと思っているので、私は今後もEditorでコピペする方法を多用しそうです；

> もう少し小規模な対応としては、そもそも互いに移動したときには、元のタブは閉じてしまうということは可能かと思います（現在は閉じるガードもかかっているので、詳細は要検討）。

個人的には、ご提案いただいた仕様も事故防止に繋がるかなと思います～。
調べものをしていると、タブがもりもり増えてしまうので、戻るべきタブが1つである方が「あれ？　FlowとEditor、どっちで編集してたっけ？」ということがなくなるかなぁと。

**Comment by snext1220** [comment]
> Flowを主に使っている場合、ご提案いただいた機能があると便利そうですね。
> ただ、Editorでの「コピペしたいSceneの内容を確認しながらコピペできる」というところが、安心感があって良いなと思っているので、私は今後もEditorでコピペする方法を多用しそうです；

ですよね^^; 若干優先度も低そうなので、こちらは手元でももう少し検討してみて、意味ありそうであれば改めてIssue上げさせていただきますね。

>>もう少し小規模な対応としては、そもそも互いに移動したときには、元のタブは閉じてしまうということは可能かと思います（現在は閉じるガードもかかっているので、詳細は要検討）。
> 個人的には、ご提案いただいた仕様も事故防止に繋がるかなと思います～。

了解です！
こちらは #305 で別Issueを上げさせていただきましたので、皆さんの反応も見ながら進めてまいりますね。

**Comment by snext1220** [comment]
追記：#305 で一旦グレーアウト機能を設けてみました。お手すきの折にご覧ください～
