### ISSUE TITLE
【PgFlow】サイドバーの自動クローズ

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#298]
これまで開かれたサイドバーは自分で閉じるまで開きっぱなしになっていましたが、タブの移動時、ヘルプダイアログを閉じたタイミングなどで自動クローズするようにしました。

**Comment by cocotori** [comment]
chromeで確認。

一通りのタブに移動して、サイドバーがクローズされるのを確認しました。

自分で閉じる煩わしさがなくなって、
便利になったと思います！

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でタブクリック時にサイドバーが自動クローズすることを確認しました。

**Comment by toki-sor1** [comment]
Win 8.1/Chrome 92.0.4515.131(64bit)にて動作確認。
タブ移動時にサイドバーが閉じることを確認しました。

ただ、リンクタブで条件式を入力欄に直接入力した後、サイドバーを閉じようとして「閉じる」ボタンを押してしまうと、サイドバーの空欄が反映されて条件式が消えてしまうことがあります。

サイドバー側にも条件式欄に入力した設定が反映されると、空白で上書きする事故が減りそうです。

**Comment by snext1220** [comment]
@toki-sor1 さん：
ご確認ありがとうございます。

> ただ、リンクタブで条件式を入力欄に直接入力した後、サイドバーを閉じようとして「閉じる」ボタンを押してしまうと、サイドバーの空欄が反映されて条件式が消えてしまうことがあります。

こちらは［閉じる］では消えないようになっているかと思いますが、如何でしょうか；（［確定］では消えます～）

入力した設定の反映については出来ると思うのですが、他のサイドバーも基本現在値の反映はしていないので、不統一になってしまうのが少々気になりました。
ちなみに、他のサイドバーは値を反映させようとすると結構大変ですが、唯一条件式のサイドバーだけは比較的簡単にはできるかなと（なので、そこだけと割り切っては出来ると思うのですが^^;）。

**Comment by toki-sor1** [comment]
ひぃん、勘違いでご迷惑をお掛けしてしまい、申し訳ありません；；
ご指摘のとおり、［閉じる］ボタンでは条件式は消えず、［確定］ボタンを押した時に上書きで消えていました；

> 入力した設定の反映については出来ると思うのですが、他のサイドバーも基本現在値の反映はしていないので、不統一になってしまうのが少々気になりました。

［確定］ボタンを押さなければ大丈夫＆他のサイドバーと異なった仕様になってしまうのは気になるので、どうか現在の仕様のままでお願いいたします～；

**Comment by snext1220** [comment]
いえいえ、諸々猛ラッシュで確認戴いたので、勘違いドンマイですｗ
では、とりあえず現時点ではママということにさせて戴きますね。
もちろん、この辺はいつでも修正は可能なので、またお気になったところで声がけください～
