### ISSUE TITLE
${input}式のparam対応

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#301]
従来の${input}式はシーン上の計算などを一時的に記録するだけのものでしたが、これを内部パラメーターの参照／更新に対応させるものです（内部パラメーターはこれまでユーザーによる任意に更新を認めていなかったため）。

+ ${input?p01}

これでp01の値を表示し、変更した場合に自動的にセーブデータに反映させるようにします（上限加減を越えて丸めが発生した場合にもガード）。本番環境にも反映済みです。

**Comment by cocotori** [comment]
chromeで確認。

内部パラメータの値が表示されること、
次シーン以降で更新した値が利用できることを確認しました。

**Comment by toki-sor1** [comment]
Win8.1/Chrome 92.0.4515.107(64bit)にて動作確認。
Scene 0で指定した値を増減させた後、次のSceneにも値の変更が反映されていました。

**Comment by Salvadors-cabin** [comment]
Win10+Edgeで問題ないことを確認しました。
