### ISSUE TITLE
王さまbotの複数人管理について

### ISSUE THREAD

**Issue by cocotori** [snext1220/stext#32]
王さまbotの複数人管理について、質問です。

例えばモーメントなどを作る時、「通知」の欄を
見ることがあるかと思います。
そうすると、他の人がログインしたときに
通知の数字が消えてしまいますよね・・・多分。

最新情報に気づきにくくなってしまうかなと思いますが、
なにか運用ルールはありますか？

モーメント制作に関して言えば、
ハッシュタグの検索だけでもなんとかなると思うので、
わたしの方では通知を見ない、という運用もできるかと思います。

メインで利用される方（今はときのじさん？）が
一番やりやすい運用にするのがいいと思いますので、
こうしてくれ、というのがありましたら
教えてください。

**Comment by toki-sor1** [comment]
この度は「モーメントのまとめ」と「登録ツイートの管理・編集」をご担当いただき、
ありがとうございます。
ご質問についてお答えしますね。

Twitterの「通知」について、ご心配いただきありがとうございます！
こちらに関して、以前からきっちりとしたルールは決められていなかったのですが、
私が二代目を運用している現在、通知欄はスマホとPCのダブル体制で随時確認して
おりますので、通知欄もどうか気兼ねなくご確認くださいませ～。

モーメントにまとめるツイートは、主に「ソーサリアン Text・Next関連」、
「NextスタッフのSText・Next関連」のツイートになります。

普段の日常会話につきましては、該当の内容が含まれていない限りモーメントに
まとめていただかなくても大丈夫ですが、この辺りの基準は私も結構アバウトですｗ
ココさんのご判断で「これはまとめた方がいいかな」というツイートをジャンジャンと
追加していただけましたら幸いでございます～。
（過去のモーメントもツイートをまとめる際の参考になると思います）

王さまbotへのリプライの中に上記の話題が含まれていた場合は、目印としてこちらでも
Favを行っておりますので、モーメントをまとめていただく際にチラッとご確認を
お願い致します～。
（ただ、Favの中にはソーサリアン関連の話題で良いなと思ったツイートや、リプライ拝見
しましたよの意味でFavしたツイートも含まれていますので、やや見辛いかもしれませんが…
す、すみません…；）

あと、モーメントのシステムがちょっと不親切で、ツイート溢れ事故が起きる可能性も
ありますので（汗）、まとめツイートが100近くになってきましたら、お互いに声をかける
必要があるかな、とも思います。

モーメントのまとめは、今後ココさんとの共同管理になりますので、お互いに気付いた時に
ツイートを追加したりと、声をかけあっていけたらいいなぁと思っています～。
こちらもまだまだ不慣れでご迷惑をお掛けしてしまうかもしれませんが、
どうかよろしくお願い致します～！

**Comment by cocotori** [comment]
ときさん回答ありがとうございます！

了解しました。
それではそんな感じで運用させてもらいますね。
至らないところあるかと思いますが、よろしくおねがいします。
