### ISSUE TITLE
欠片が2回目から正常に加算されない

### ISSUE THREAD

**Issue by toki-sor1** [snext1220/stext#33]
Windows8.1／Chrome 69.0.3497.100（64 bit）にて確認。
「少女は英雄を語りて」で＜七惑星の欠片＞を加算するシーンが幾つもあり、
該当のシーンでは新たに「stars="2,2,2,2,2,2,2"」のような設定を加えました。

しかし、1回目の加算では「月2個」と正常に加算されるものの、
2回目の加算から「月22個」という風に加算され、
3回目の加算では「月222個」という風になってしまいます。

![default](https://user-images.githubusercontent.com/42646342/46573664-8e733f00-c9d3-11e8-81e1-af4dc7e822b0.PNG)

O/Dに[シナリオ最新版（修正中）とセーブデータ](https://onedrive.live.com/?id=4837C202555BE782%217588&cid=4837C202555BE782)をアップ致しました。
（欠片入手前にフラグを取得するシーンがあるため、データには余裕を持たせています）

以下のシーンにて動作のご確認をお願い致します。

- Scene 09113 → 09100（正常加算）→ 中略 → 13000（異常加算）

※デバッグの方でページを指定して各シーンに飛んだ時には、2回目も正常に
　加算されていたりと、症状が出る条件がいまいちよく分かりません…。
（02:22追記：欠片を入手したシーンで「SAVE STATUS」を押すと再現できました。
　右上の×アイコンで閉じた時は、この症状が出ませんでした）

**Comment by snext1220** [comment]
ご指摘ありがとうございます。
内部的に、ステータス画面からの星の入力値が文字列扱いになっていたのが原因でした。

先ほど修正しましたので、ご確認ください。
また、December Updateですが、（軽微でしたので）負数丸めも合わせて無効化しています。

**Comment by toki-sor1** [comment]
修正ありがとうございます。
GitHubから最新データをDLし、Windows8.1／Chrome 69.0.3497.100（64 bit）にて確認。
今度は＜七惑星の欠片＞が正常に加算されていました。
負数丸めの件も了解です。
