### ISSUE TITLE
種族／性別などをシナリオごとに限定

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#4]
シナリオ単位に生成される種族／性別／年齢を限定（＝初期化）できるようにする。
「美しき花嫁」のように特定性別が前提となる、または「ロマンシア」のように特定の職業が前提となるシナへの対応が目的です。

```
<init>
  <constraint race="FIGHTER,WIZARD" sex="MALE" age="YOUNG"  />
</init>
```

上で挙げている他に、制限を付与したいものがあれば、リクエスト願います。

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 69.0.3497.81（64 bit）、iPhone 7／Safariにて確認。
正常に動作しました。

**Comment by RYU-DS** [comment]
今さらですが、そのスレ、中年男ファイターに制限してもいいものでしょうか・・・

**Comment by snext1220** [comment]
問題ないです！ただし、既存のセーブデータまでは書き変わらないので、あくまで新規開始分からの反映になります（HTTPS対応で一旦クリアされているので、それなり大丈夫そうですが^^;）
