### ISSUE TITLE
scenario.xml（サンプル＆テンプレート）更新

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#40]
Playgroundで利用している機能テスト以外の.xmlが古くなっているので、修正をかけます。

ただ、マニュアル、機能テストデータ、テンプレートと並行してのメンテナンスが困難になってきているため、以下のように再編の予定です。

+ 機能テストデータ（現状維持）
+ テンプレートにコメントとして要素／属性の説明を挿入
    + マニュアルからはGitHubの該当ページにリンク
+ Playgroundの［空テンプレート］は上記のものをもとに提供
    + ［説明付きテンプレート］（コメントあり）
    + ［説明なしテンプレート］（コメントなし）

以下制作中のテンプレート
https://github.com/snext1220/stext/blob/master/stext/playground/scenario_ref.xml

なお、最近のUpdateで @toki-sor1 さんのUtil「道場」も陳腐化しつつあり、どのように更新していくべきかは悩ましいところです。

**現在、Playgroundに試験的に反映させていますが、イマイチ見難く、こちらで一本化するのは難しいかもしれません。皆様のご意見伺いながらではありますが、一旦、［Confirmed］を外して継続検討にさせていただくかもしれません。**

**Comment by snext1220** [comment]
こちら悩ましいですが、現時点では、初心者にも馴染みやすいリファレンスをコードとまとめて管理するのは難しいと判断しております。よって、scenario_ref.xmlは破棄、従来のPlaygroundのテンプレートを（時差はあると思いますが）更新する方向で進めていきたいと思います。

引き続きご意見などあればぜひお願いします。

**Comment by toki-sor1** [comment]
テンプレートを最新仕様に更新していただき、ありがとうございました！
「道場」をVer1.0仕様に更新する際に使用しましたが、内容に問題ないと思います。
また、「道場」も更新し、最新テンプレートを改変する形で編集できるよう解説を改めましたので、現状ままで大丈夫かなと。
