### ISSUE TITLE
トースト表示に関する疑問や問題

### ISSUE THREAD

**Issue by RYU-DS** [snext1220/stext#41]
以前からあったトースト表示に関する疑問と、戦闘計算結果がトースト表示される事に対する問題が発生すると考えたので別でIssue立てました。

以前から疑問だったのですが、トースト表示される時間ってランダムですか？
長文が一瞬しか表示されなかったり、数文字なのにずっと表示されたりするんですが…
しかも一度決まった時間は変更されないようで、一瞬しか表示されない長文をイライラしながらカチカチクリックする事も結構あります。

で、今回このままで行くと「戦闘計算結果がトースト表示される」という事で、今までのリザルトや敵説明のようにトースト内容を別で見たりもう一度見たり、ができないとなるとこれはもう…

「トースト表示はクリックするまで消えない」

を提案します。
今までは避けてこられたトースト表示の重複も戦闘計算結果では起こるので、次の表示分は表示待ちとして先の表示分がクリックされて消えたら次が表示、で。
もちろんずっと表示されてるのも困るので、シーンを移動したら強制的に待ち分も全て消える、で。
これは表示を見ずに進んでしまう可能性がありますが、さすがに自己責任でよいかと。

で、これであれば戦闘計算結果を見ながらステダイアを開いて色々な反映が出来るので、そのスレを自動計算に少しでも対応させるためには、これが最低限必要と考えていますが…

どうでしょうか？

**Comment by RYU-DS** [comment]
自分もトースト表示の元の利用法であるトロフィー表示に関しては、個人的にはイヤでもまあこんなもんだろうと思ってきたのですが、今回用途が広がるという事で提案しました。
用途を拡大しつつも元の用法を遵守する、というのは別にいいと思うのですが、拡大によって無理が出るのは確実ではないかと。
※現実に敵説明への利用には若干無理が出てきていると思います、私の敵説明が長文というのを考慮しても。

**Comment by toki-sor1** [comment]
**戦闘計算結果のトースト表示について**
これまでの流れから、「トーストでは無理が生じる部分がある」ということと、
「トーストの表示時間」が問題になっているとお見受けします。

そうなると、実装可能かどうかはちょっと分からないのですが（汗）、
トーストを使用せず、戦闘計算結果の表示を維持するという意味で、「各モンスターの
表示位置下に戦闘計算結果を表示するスペースを設ける」のも一つの手かな、と思いました。
（自動化対応不可な戦闘では、戦闘計算結果スペースを消す設定にもできると良さそうです）

<img src="https://user-images.githubusercontent.com/42646342/46946914-35329c00-d0b4-11e8-90ef-23ad9977c343.png" width="320">

各モンスターのところにスペースを設けるため、画面が縦に長くなってしまうのと、
レイアウト的な面でやや難ありですが、もしこれが実装可能であれば、
トーストの設定を変えず、また、RYUさんのご要望にも近付けられるように思います。

ただ、先にも申しました通り、実装することが可能なのかどうかがまったく分からないので、
バグが出やすくなる、そもそも実装が難しい（または不可能）等、問題があるようでしたら
廃案にしてください。

**トロフィー＋αのトースト表示について**
トーストが再実装され、私は以前よりも見易くなったと感じています。
トロフィー取得時（とモンスターの情報表示）の時間も問題はないように思いました。
（戦闘結果のトースト表示については、まだ評価はできず）

トロフィーのトーストが自動的に消える仕様についてですが、私もリオさんと同意見です。
「数秒間表示されて自動的に消える」という仕様が馴染み深いという理由もあるのですが、
STextのトロフィー取得時の表示が、元がプレイステーション系ハードのトロフィー取得時の
表示を参考にしたからです。

「トロフィーを取得したシーンが何処なのか分からないという状況を改善するには」と
考えた時、私はRESULTSの各トロフィー（実績）の何処かにシーンの番号を含めたり、
「○○をしたからトロフィーを取得できた」ということが明確である説明文にすることで
一応は改善されるかな、と思いました。

あとは、可能であればトロフィーに「New!」を付与する、でしょうか。
（トロフィー取得時のトーストは、シーン移動後にすぐ表示されるため、
トロフィー名を見逃してしまう可能性はあるものの、トーストが表示されたこと自体を
見逃すことはあまりなさそうかな、と）

**Comment by snext1220** [comment]
> トーストが再実装され、私は以前よりも見易くなったと感じています。

ありがとうございます！
今回の再実装でトーストとしての制御はしやすくなったので、今後様子を見ながら、細かくは調整していければと。

> 各モンスターの表示位置下に戦闘計算結果を表示するスペースを設ける

こちらは――スミマセン、#39 のとおり、議論と実装の発散を防ぐため、まずは基本的な半自動化を優先させたく、一次実装のあとの議論とさせてくださいm(_ _)m
＃ SText本体としても大きな修正となるため、いきなりできることを拡げるのではなく、まずは最小限の機能でどこまで賄えるかを見つつ、徐々に機能を拡充するという形になるかと。

> RESULTSの各トロフィー（実績）の何処かにシーンの番号を含めたり～

はい、現時点ではこうした対応をお願いできますと助かります！
［New!］については実装方法は複数考えられますが、取得タイミング、経過シーンなどまで管理しなければならず、地味にセーブデータ管理が煩雑になることから、ご容赦戴けますとm(_ _)m

> 敵説明への利用には若干無理が出てきている

こちらは情報ごとに表示時間を変更することもできるので、今後、皆さんのご意見を伺いながら調整していければと思います（あまりに長いと、逆に、いつまでも消えずに邪魔、という意見もあるのかな、とも思いますので、他の皆さまのご意見待ちとさせてください）。
＃ ときのじさんは現在のもので丁度良いとのこと、ありがとうございます！

**Comment by RYU-DS** [comment]
なるほど「近年のゲームでの気軽な収集欲刺激を利用してのユーザー確保の一環なので、それに倣うのは曲げられない」ということですか…理解が足りていませんでした。

であればそこは守りつつ、他の用途にも耐えうるようにするには提案されている？通り
「その情報ごとに表示時間を設定できる」
がベストですかね。
簡易な方法として「文字量に比例」がありますが、やはり「シナ側で設定可能」がいいと思います。
しかし「無限（ずっと表示）を設定可能にするかどうか？」、また「トロフィー時は短めに」というのを遵守にするか強制にするか？
などなど問題が多いですね。

今獲得したトロフィーがどれか？は自分で実際感じた事なので改善したいです。
頭や最後に「獲得シーンNo.1234」みたいなのを入れればいいのですが、そのスレだと第四部隊との遭遇トロフィーがあって、同じトロフィーが最大5箇所ほどで得られるのでちょっと微妙ですね…他シナはそもそもトロフィー少なめだから必要ないかな？

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 70.0.3538.77（64 bit）、iPhone 7／Safariにて確認。
正常に表示されています。
現在のトーストの表示時間も丁度良いと思います。
