### ISSUE TITLE
モンスター／罠リストのアイコン画像化

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#42]
#39 からの派生です。
手軽にできるものから対応していければと思います。

+ モンスター一覧のアイコン追加
+ attack属性の修正
+ element属性の修正（非互換）

本件、GitHub Pagesのみで対応済みで、Playgroundだけ本件に対応したデータに移行しています（10/15 17:00現在）。他のシナリオでは敵表示が乱れるので注意してください。
少し待って問題なさそうであれば、各シナリオの修正をお願いしていければと思います。

#### 対応表（コードより抜粋）

```javascript
// 状態異常＆攻撃の表示名
state_names: { '': '正常', 'poison': '毒', 'frozen': '凍結', 'stone': '石化', 'curse': '呪い', 'forget': '忘却', 'physics': '物理', 'magic': '魔法' },
// 属性の表示名
element_names: { 'earth': '地', 'fire': '火', 'water': '水', 'wind': '風', 'spirit': '霊' }
```

**Comment by snext1220** [comment]
#44 （Tweetボタン）のリリースは「占い」のアクセスがおおいうちの方が良いとおもうので、やや早めではありますが、こちらの非互換修正をお願いできればと思っておりますが、如何でしょうか。皆様の修正終わり次第、本番環境に反映できればと。

＃ 他Issueのdecember updateは互換性は維持されているので、機能テストはその後いつもの予定で進められればと。

修正終了＆GitHubへの反映終わった方は、此方の投稿にReaction（+1）など付与戴ければ幸いですm(_ _)m

**Comment by RYU-DS** [comment]
占い、そんなにですか・・・
シナリオの頭数増やし用に「こんなんでほんとにいいんか？」と作ったものがそんなに好評だと、自分の世間とのズレを再認識せざるを得ないですな・・・いや自分としてはそれは良い所なんですが。
一応、そのスレ属性修正対応しました。
Githubへの反映も自分でやった方がいいかなとも思うのですが、自分に出来そうなものでしょうか？

**Comment by snext1220** [comment]
おかげさまでdisk2 以降では、最大の伸びなのではないかと（あくまで感覚値ですが^^;）。
STextそのもののゲームブック層への認知はまだ弱いため、現時点では、純粋なソーサリアン層に訴求するテーマが強いのかなと見ています。その層はいわゆるゲームブック層とは別なはずなので、占いの手軽さが強くマッチしたのではないかと。

> 属性修正

ありがとうございます。
こちら、たぶん、今回はelement属性だけ修正されたかと思うのですが。
attack属性についても「magic,stone」のような複数指定が可能であれば、ドラスレは賄えますかね。というのも、当初はattack属性で互換性の切り替えをしようと思っていたのですが、シナによってアイコンの有無がわかれるのはあまり美しくないので、attackはアイコン表示で統一しようかなと。
＃ その場合は、互換性維持のためのスイッチは別に用意します。

> GitHubの反映

こちらはすみません、権限をスタッフのみに空けているため、現在はサルバさんへのお知らせにてお願いできますでしょうかm(_ _)m

**Comment by cocotori** [comment]
修正してみましたが、アイコンになった分、視覚的に華やかにはなったのですが、
いささか寂しい気がしますね。
（今まで文字だった分の反動かもしれませんが）

ときさんがDMであげてくださった、アイコン+文字ありが可能なら、
そちらの方がいいかなと個人的に感じます。

**Comment by snext1220** [comment]
恐縮です；
暫くは敵リスト周りは細かく弄っていると思うので、徐々に整えていければと。
＃ 仰る通り、UI周りは時間がたつと（見）慣れていくというのもあるので、その辺も含めて、気長に見てやってください^^;

**Comment by RYU-DS** [comment]
＞今回はelement属性だけ修正されたかと思うのですが。
はい、とりあえず急ぎでelement属性だけを。

＞attack属性についても「magic,stone」のような複数指定が可能であれば、ドラスレは賄えますかね。
いくつまで指定、重複指定可能か？によりますね。
現状最大で「物理＋魔法＋状態異常（2種or強を2重で表現）」で4つのアイコンが要ります。
※状態異常をこれ以上重ねる予定はありませんが、もしやるとしてもイベント攻撃になると思います（全部など）。
ある程度は名前側に入れる事で対応可能ですが、そちらには防御不能や魔法無効が入るので場合によっては無理になるかもしれません。
なので上記の「４つ（できれば５つ）を制限無く自由に入れられる」か、もしくは「任意の文字を１～２文字入れられる空アイコン（例えば石化アイコンの横に「強」と入れたアイコンを置く）」が必要になると思います。
物理魔法（剣＆杖）のアイコンを作って１つ減らすのも手ですが…
このようにかなりそのスレのためだけのお願いが多くなってしまいます。
また、現時点であまり固めてしまうと自分としても新しいアイデアが盛り込みにくくなってしまうので、「柔軟性に富んだ幅を許容する仕様＝複雑かつ危険」になってしまうのも難点ですか。

**Comment by snext1220** [comment]
> attack属性

成程…物理/魔法でひとつ、状態異常でひとつの2個を想定していたのですが、そうなるとやはり横幅の意味でも難しそうですね...スミマセン、言い出しておいて恐縮ですが、一旦はママとさせてください^^;

**Comment by RYU-DS** [comment]
本当についでなんですが、ちょっと気になっている事を。
武器などによる直接攻撃を「物理」と呼ぶ事なんですが、おおよそのファンタジーにおける「魔法」というものは、古い魔法少女などが使う「○○にな～れ」でそうなるようなドラえもん的なものではなく…

魔法によって、目前の空間にある物質の分子を強制的に高振動させて高温化・発火させる事により、火炎魔法として効果を発揮する

といったような「現実に即した物理現象」として設定・認知されていると思います。
なので、物理と魔法という分け方はこれらを認知している人間には、とてもひっかかります。
それが今回アイコン化する事で外れる、というのが個人的に大きいと実は思っているのですが…
正規のattack属性として物理の英語訳physicsを使われていますが、これもできればstrikes＝打撃などに変えた方がよいと思います（制作側の認識の問題として）。
またこれもできればですが既存分も以降分も「物理」は「打撃」などに差し替えた方がよいかと。

くだらないうんちくに聞こえると思いますが、そういうものにこだわる事がフィクションを楽しむ上で重要と考えますので、あまり軽視せず考慮してもらえればと思います。

**Comment by snext1220** [comment]
ご提案有難うございます。
ただ、いくつかの理由から本件はママといたしたく。

+ 分子振動等は世界設定によって変動があるように思われる（ソーサリアン世界がそうなのかそうでないのかは、スミマセン、よくわかりません）
+ 個人的には、strikeが打撃（斬でも突でもなく）に限定されることから、これはこれで悩ましいのかな、とも（変更にも議論が必要）。
+ 「物理」「打撃」も同様（こちらは相応に「物理」攻撃で定着もしていると思われる）
+ 現実的なとして、既にスタッフの皆さま＋ちゃなさんにも対応進めて戴いている（半分以上が作業完了している）ステータスなので、今から変更するのは避けたい。

以上から基本ママ、ただし、スタッフの他の皆さまからも、重ねて変更要望が出てきた場合には検討とさせていただければ。

**Comment by snext1220** [comment]
いくつか修正を。

#### 列の表示順序

以下のご指摘を @toki-sor1 さんから戴いていました。

> アイコン同士圧迫感

こちら属性と攻撃手段が隣接していて区切りも判別しにくいおそれがあったので、列の順序も入れ替えてみました。

#### 旧仕様の削除

GitHub Pagesでエラーが出ないよう、element属性の旧仕様を暫定的に許容していましたが、地／火などの旧値のサポートを外しました。移行していないシナリオは正しく動作しなくなるので、ご注意ください。

**Comment by toki-sor1** [comment]
**攻撃の表記について**

ソーサリアン関連の書籍を読んでいたのですが、「魔法」という単語は頻繁に
使われている一方、武器による攻撃については固有の呼び方はなかった感じですね。

「物理攻撃」という表記にはすっかり慣れてしまっているので、違和感はありませんが、
元々の「物理」のことを考えると、確かにちょっと奇妙な感じはしますね。
これも日本の文化が生んだゲーム独自の専門用語ということなのかもしれません。

そうなると、魔法攻撃がmagicであるのに対し、武器による攻撃を表す用語が各作品で
ブレがあるため、日本語では「物理攻撃／魔法攻撃」とし、シナリオでの指定では、
それに準じて「物理（physics）」とした方が直訳している分、わかり易いのではと思いました。

（attackは通常攻撃や物理攻撃という意味で広く使われている印象なので、英語表記では
個人的にはこちらの方が馴染みがあります。しかし、システム関連の修正には、
修正する以外にもご連絡やチェックなど対応に時間が掛かるものも多いため、
ソー31周年までに残された時間を考慮し、今回はそのまま進めていただくの方が良いかと）

**列の順序入れ替え**
現バージョンの順序の方が見易いと感じました。良いと思います。

**Comment by snext1220** [comment]
> （attackは通常攻撃や物理攻撃という意味で～～

そうなんですよね。
私も、後追いで、属性の名前はmethod、actionのような汎用的な名前にして、物理攻撃をattack、魔法をmagicとするのが一番スッキリだったなと；
＃ 初期リリースで結構適当に決めてたのですが、RYUさん仰るように、名前付けとても重要だなと改めて（重要なのに、一度決めると、中々変更が難しいという意味でも）^^;

> 現バージョンの順序の方が見易いと感じました。良いと思います。

ご確認ありがとうございます～
では、まだ細かくは修正していくかと思いますが、まずはこの方向で！

**Comment by toki-sor1** [comment]
無属性アイコンの反映ありがとうございました。
Windows8.1／Chrome 70.0.3538.77（64 bit）、iPhone 7／Safariにて確認。
正常に表示されていました。

**Comment by RYU-DS** [comment]
無属性アイコンとは何でしょうか？
ひょっとしてelement属性を指定しない「無属性」が設定できる？

**Comment by snext1220** [comment]
はい、一応リリース時からelement属性の省略そのものは許容しており、テンペストで使われていました。これまではただ表示されないだけだったのですが、アイコン化で不揃いが発生していたので、「無属性」アイコンとして対応しています。
