### ISSUE TITLE
［ドロップアイテム］ボタンで星、freeXに反映

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#43]
#39 からの派生です。

互換性には影響しない＆ #39 でも殊更に反対意見がないようだったので、実装してみました。現在、GitHub Pagesのみ反映していますので、ご確認戴けますと幸いです。

@toki-sor1 さん＞ボタンは暫定的にデザインしていますが、枠線色、背景色、文字色など良いものがあればご指定願いますm(_ _)m

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 70.0.3538.67（64 bit）、iPhone 7／Safariにて確認。
正常に動作しました。

**ボタンの背景色、枠線色、文字色など**
ドロップしたものを「得る」ので、STATUSダイアログの「＋」と同じ色（組み合わせ）
というのは如何でしょう？

**Comment by RYU-DS** [comment]
確かにいいかもしれませんねー
ついでに「＋」も付けた方がいいかも？
星以外を指定した時の場合とかどうなのかわかりませんが…

**Comment by toki-sor1** [comment]
ご賛同、ご意見ありがとうございます！
色変えがやっつけで申し訳ありませんが（汗）、試しにサンプルを作成しました。
![2](https://user-images.githubusercontent.com/42646342/47090921-d2c9cf00-d25e-11e8-8f19-43f75734164a.png)
「＋」有りと無し、黒枠有りと無しの4パターンです。
白背景だとSTATUSダイアログのままの色設定では、枠がぼんやりしてしまっている印象なので、
更に黒枠を重ねたものも並べています。

**Comment by RYU-DS** [comment]
あ、やっぱり「＋」あると「押すとどうなるか」が明確になっていいですねー
黄色枠が埋もれるのはダイアログとは背景が違うので仕方ないですが、個人的には黒枠はクドイ気がするので別にそのままでもいいかなと思います。
枠の色そのものを変えてしまうのもアリかもしれません。

**Comment by snext1220** [comment]
ご提案ありがとうございます！

とりあえず［+］の背景色に合わせてGitHubは更新してみました。
ただ、スミマセン、二重枠線の色をわけるのは現状ではスタイル変更だけでは済まなくなるので、避けさせてください。仰るように、クリーム色の枠線はボケるので、まずは黒枠線のみとさせていただきましたm(_ _)m

［+］文字の追加は、今後、敵リストの横幅がひっ迫するのが予想されるため、現時点では見送らせてください（アイコン化もそのための施策でして、現在は余裕ができていますが、この後、半自動化で諸々詰めていく予定のためm(_ _)m）

**Comment by toki-sor1** [comment]
反応が遅くなり、申し訳ありません。更新ありがとうございました。
Windows8.1／Chrome 70.0.3538.77（64 bit）、iPhone 7／Safariにて確認。
正常に動作しました。

**ボタン内部の色**
今更になってしまい申し訳ないのですが（汗）、黒背景だと丁度良く見えた赤色も、白背景ではやや暗すぎる感じもしますね。
現在の色よりもやや明るめの赤（#cc0000）又は「Shoot」くらいの明るい赤の方が、色がきつすぎなくて見易いかもしれません。

**ボタンの枠色**
現在は暫定で黒となっているのですが、現在の赤色が暗めの色なので、枠色の黒と合わせると、やや重い印象を受けますね。
STR等のオレンジ色っぽい色を枠色にして、先の赤色と組み合わせると、黄色の時よりも枠線のぼやけた感じがなくなるかなと思います。
（ただ、ボタン内部の色と枠色との境目がややはっきりしなくなるかもですが）

**Comment by snext1220** [comment]
ご指摘ありがとうございます！
こちら、とりあえずボタン内部色をShootに合わせ、GitHub PagesにUpしてみました。
いくつも並んだ時に一寸軽い感じになった気もしますが、如何致しましょうか。
＃ 枠線はオレンジにしてみたのですが、やはりぼやけて見えたため＆中を明るめにしたので、重さが軽減されたかなと一旦そのままにしています。

#### 補足

ダメージ式もボタンになっていますが、こちらはJanuary Updateの作業中のためです。まだ動作しませんので、ご了承くださいm(_ _)m

**Comment by toki-sor1** [comment]
早速のご対応ありがとうございました！

> こちら、とりあえずボタン内部色をShootに合わせ、GitHub PagesにUpしてみました。
いくつも並んだ時に一寸軽い感じになった気もしますが、如何致しましょうか。

内部色がShootと同じになり、見た目的に軽くなった感じがしますね。
ただ、白背景の明るさと相まって、ピンク系の赤がやや目に痛い感じもしますね（汗）。

又、スマホ画面だとボタンになるのですが、今の内部色だと薄ピンク＋白文字という感じになってしまうので、ちょっと見辛い印象でした；
（スマホ上ではこの添付画像よりもっと濃い目でしたが、それでも色は薄い感じでした）
![img_0586](https://user-images.githubusercontent.com/42646342/47619183-5ddc7c00-db1f-11e8-884e-4d7ce955fcfb.png)

ダメージ式の青色は、スマホ画面だと丁度良いのですが、PC画面だとやっぱり暗めに見えたので、#000CCCくらいの青色の方がほどほどに濃くて軽めに見えるかもしれません。

> ＃ 枠線はオレンジにしてみたのですが、やはりぼやけて見えたため＆中を明るめにしたので、重さが軽減されたかなと一旦そのままにしています。

お試しくださりありがとうございます～。こちらはぼやけ気味でしたか；
しかし、ボタンの内部色がやや明るめな色になってきたので、枠が黒でも重たすぎる感じがしなくなりましたね。
内部色は調整が必要かもですが、現状ままで良さそうな気がします。

**Comment by snext1220** [comment]
ご確認有難うございます！

とりあえず枠線はFixですね。
内部色は仰る通り、スマホ環境での見え方が気になるので、一旦はドロップボタンの方は元に戻し、ダメージボタンの方を#000cccに修正しております～

**Comment by RYU-DS** [comment]
今すぐどうこうではなく将来的にですが、ドロップアイテムは複数指定出来た方がよいと思います。
単純にヒールを使えるように木土や、ボーナス的に全部を１つ、あと例などにある固有アイテムを指定すると星の入手手段を別に用意しなければならない問題もあります。
表示の問題はそもそも「敵を倒すまで何を持っているかわからない」通常のゲームを踏襲する、戦利品表示を隠す「マスク表示（内容はクリック時にトーストで確認）」を設定すれば解決するかと（表示したい場合も一定量を超えると自動でマスクになる）。
そのスレではEXPも得られるようにするとやはり星が得られなくなります。これができれば敵EXPを固定にして、LVUPに必要なEXPを上げていく通常の方式にして、LVUPは手動ですがEXPの蓄積は自動にしたいと思うのですが…

**Comment by snext1220** [comment]
はい、こちらは将来的な課題とさせてください。
現在、他シナでもdrop属性は一切利用されていないため、まずは現状機能で利用戴き、ある程度利用感触を見ていきたいと思っています。

**Comment by RYU-DS** [comment]
無属性時にドロップが未指定だと何も置いていかない事を受けてなのですが、置いていく（決定して表示される）物は１つとしても、それを複数候補指定してそれらからランダムで、という戦闘計算式のような仕様にはできないでしょうか？
これは無属性を「魔法が効かない特殊な強い敵」でなく、「どんな魔法でも効く弱い敵」に適用しようとすると、指定した星１種しか置いていかず、星を満遍なく入手させようとするのに問題が出るからなのですが…
またこれなら、RPGのドロップの華である「たまに置いていく物」が設定できるようになるので、通常のアイテムも指定できるようになるといいなと思います。

＞現在、他シナでもdrop属性は一切利用されていないため
これはタイミングと内容の問題だと思います。
この仕様変更がそのスレの第二部制作中であれば自分は間違いなく利用しましたし、ラミディアもそうではないかと。しかし既に元の仕様で組んでしまったので組み直す訳にもいかず利用していない、と。
そしてお話しているように、新たに組み込もうとすると現在の仕様ではちょっと使いにくい、というのが自分の方の現状です。

**Comment by snext1220** [comment]
> タイミングと内容

はい、仰る通り、まだリリースして間もない機能なので、そういうことなのだろうなと。この後、徐々に適用するシナリオが出てくると、要件も諸々出てくるかと思うので、皆さまのご意見をまとめつつ、方向性を決めていければと。

＃ 「ドロップアイテムを選択的に～」含めて、ご要望あればお願いします＞皆さま
