### ISSUE TITLE
Tweetボタンへの対応

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#44]
以下のご要望を受けてのIssueです。
https://twitter.com/ishikawanonoich/status/1051839680314888192

**実装中にエラーが発覚したため、仕様を変更しています。ご了承ください**

シーン内の任意の文字列を［Tweet］ボタンに反映可能にします。

+ ${tweet}～${/tweet}で該当箇所を括ることで、これをTweetボタン側で引用可能に
    + その配下ではMarkdownによる太字などは不可
    + ${tweet}の利用は1個/scene
+ シーン個別の設定の他に、シナリオ既定のテキストを指定可能に

#### SGML

```
<init>
  <intro description="王様の杖を探し出す駆け出しの物語" />
</init>
```

#### GBAT

intro:王様の杖を探し出す駆け出しの物語

**10/16現在、対応し、GitHub Pagesにのみ反映しています。Playgroundのscene0～2へ移動することで変化を確認できるはずです（本番リリースにはdecember updateの非互換更新（element属性）への各シナリオの対応が必要です）**

**Comment by toki-sor1** [comment]
ご検討、そして仕様のご提案ありがとうございました。
この機能が実装されれば、今回の「占い」の結果ツイートの他に、
シナリオ紹介時にも活用できますね。
機能の実装と仕様ともに賛成です。

**Comment by RYU-DS** [comment]
早い…
いや自分も完全に失念していました、ワンクリックでSNSへ投稿できる機能がいかに重要かを。
自分でもツイッター連携してないサイトはほぼ拡散しないのに…
これでプレイした人がちょくちょく投稿拡散してくれると違ってきますかねー。
こういう当たり前のアイデアが出てくるのも一般の人にうけた？利点ですかね。
いやーでも17しかない結果をツイートされるのマジでちょっとキツイなぁーｗ

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 70.0.3538.67（64 bit）、iPhone 7／Safariにて確認。
正常に動作しました。

> こういう当たり前のアイデアが出てくるのも一般の人にうけた？利点ですかね。

開発側だと、当たり前のことほどついつい見落としがちなのかもしれませんｗ

そうですね、今回のTweetボタン実装は、プレイヤーさんの「皆に見てもらいたい欲求」を
ガッツリと刺激するGoodアイデアが詰まったRYUさんのシナリオあってこそ、でした！
ありがとうございます！！（これは『真』作成のフラグ……ゴクリ……）

**Comment by RYU-DS** [comment]
あ、GBATではどうですかね？
${tweet}～${/tweet}
はたぶん大丈夫として
<init>
  <meta description="王様の杖を探し出す駆け出しの物語" />
</init>
はSGML？
これでトロフィーを入れようと思うのですが。

**Comment by RYU-DS** [comment]
<init>
  <meta description="王様の杖を探し出す駆け出しの物語" />
</init>

**Comment by RYU-DS** [comment]
あ、GBATではどうですかね？
${tweet}～${/tweet}
はGBATでも大丈夫そうですが
<init>
  <meta description="王様の杖を探し出す駆け出しの物語" />
</init>
はSGML用に見えるんですが…
これでトロフィーを入れようと思ってます。

**Comment by RYU-DS** [comment]
あれどうしても出ない・・・
隙間は
＞シーン個別の設定の他に、シナリオ既定のテキストを指定可能に
のコマンドの方です。

**Comment by snext1220** [comment]
現時点ではGBATは未対応です。別途、
`meta:王様の杖を探し出す駆け出しの物語`
のようにかけるようにしておりますが、実は、問題が出ておりまして…
metaというタグ名そのものを変更するかもしれません。少々お待ちを。

> あれどうしても出ない・・・

タグ表示についてはMarkdownの記述をご覧ください。
https://guides.github.com/features/mastering-markdown/

**Comment by snext1220** [comment]
先程対応し、GitHubにGBAT対応版をUpしました。
伴い、仕様を変更していますので、Issue冒頭も修正しています。

**Comment by RYU-DS** [comment]
今、対応させた占いで色々チェックしましたが…

1.MarkdownだけでなくSGMLの装飾コマンドも出てしまいます。
![tuiiro](https://user-images.githubusercontent.com/43634197/47153463-ac696980-d31a-11e8-8f10-98535daf0879.PNG)

2.intro:で設定したテンプレツイートは、各シーンでの指定ツイートと併用はできないんですね？
※つまり未指定時用

3.文字数制限がキツイので指定範囲を絞るのは当然として、サイトアドレスなども文字数に入っているので削減をお願いしたいです。
試した所、「https://www.」は外してもリンクしました。ハッシュタグは#falcomは確かに欲しいので削減は無理ですね…ただ、#snextはリンク先がstextのトップなので#stextでよいと思うのですが・・・
![tuikatto](https://user-images.githubusercontent.com/43634197/47154227-ad02ff80-d31c-11e8-9b7b-9bfc41fa1742.PNG)

まあ、リンク時であってもツイート時の文字数オーバーはツイート者が削ってなんとかするのがツイッター文化ではありますが、そこらへんが雑なのもどうかと思うので一応。
アドレスがアホみたいな文字数で出て、言及どころか普通にツイートも出来ないとかなると「バカじゃねーのか？」とは思いますしね。

ちなみに現状でちょうど110文字入るようです…参考までに。
![tui110](https://user-images.githubusercontent.com/43634197/47154677-eee07580-d31d-11e8-9244-40ef4374ee23.PNG)
![tui111](https://user-images.githubusercontent.com/43634197/47154709-00c21880-d31e-11e8-8bfa-a4be645241c1.PNG)

**Comment by snext1220** [comment]
> MarkdownだけでなくSGMLの装飾コマンド

スミマセン、言葉足らずでしたが、こちらは仕様です。いわゆる修飾系の機能はすべて利用できません。

> テンプレツイートは、各シーンでの指定ツイートと併用はできないんですね？

はい、ご認識のとおりです。
＃ 誤解がありそうだったので、マニュアルにも追記しました。

> サイトアドレス

こちらはTwitterの文字数カウント上「https://www.」は関係ないかと。#snext は検討します。お待ちを。
