### ISSUE TITLE
敵リストへの撃破チェック追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#45]
#39 からの派生です。
RYUさんの要請を受けて、1シーンに複数敵が発生する場合にのみ、
行先頭にチェックボックスを表示します。

あくまでその敵を撃破したかどうかを自己管理するためのもので、機能は持ちません。
マニュアルでフォローできればと思いますが、一寸わかりにくい場合には、オンオフのアイコンにした方が良い、かも？

**Comment by RYU-DS** [comment]
素早い対応ありがとうございます。
自分の用途としてはこれでまったくOKですが、他の用途やそのための改良案などあったら提案お願いします。

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 70.0.3538.77（64 bit）、iPhone 7／Safariにて確認。
正常に動作しました。
