### ISSUE TITLE
scene要素のhp／mp属性

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#49]
#39 からの派生です（以前戴いたリクエストの復活案でもあります）。

scene要素にHP/MP自動更新するためのhp、mp属性を追加したいと思います。
いずれもゼロ未満になっても特にガードはしない予定です。

```
<scene hp="-5" mp="-5">  … HP/MPをそれぞれ-5で更新
<scene hp="-5..-1"> … HPを-5～-1の範囲で更新
<scene hp="full"> … HPを全快
```

テキストでなんらかの説明があることを前提にしていますので、特にトーストなどの表示もしない予定です。

**Comment by Salvadors-cabin** [comment]
ありがとうございます。
私としてはこの仕様で問題ないと思います。

**Comment by snext1220** [comment]
こちら現在上限オーバーした時にそのまま加算してしまう問題がありましたので、修正致します。

ただ、実は上限オーバーしても良い、という要件があったりするのかなとも。
＃ こちらは追加になるので、ご要望あれば検討いたしますので、お声がけください＞皆さま

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 70.0.3538.102（64 bit）、iPhone 7／Safariにて確認。
正常に動作しました。

HPまたはMPがマイナスになってからの「数値を指定した回復処理（全回復ではなく50回復など数値を指定した場合）」ですが、こちらは回復処理のあるシーンに進む前にテキストにて「マイナスになった場合は手動でゼロにする」という感じの説明を入れて対処しております。

**Comment by snext1220** [comment]
こちら、スミマセン、ご指摘を図りかねているかもなので、確認させてくださいませ^^;

+ たとえば「-5」になった状態でも「hp="50"」で「45」が得られるかと思いますが、そうならないというご指摘でしょうか？（or ゼロ丸めして、50にしたい？）
+ そもそもHP／MPが0以下でゲームオーバーなので、あまり負数は気にしていなかったのですが、そのような用途を想定されている？
