### ISSUE TITLE
本文のルビ指定

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#5]
文中にルビを振れるための文法を追加する。

`${電子出版|でんししゅっぱん}`

> ■ときのじさんご意見
> 個人的には必須とまではいかない印象なのですが、魔法やアイテム等の格好良い読み方、難しい読みの漢字など、ルビが振れると演出や読み易さも強化されると思います。
> ※以前、同人誌の台詞で漢字にルビが振られていて海外の読者様がとても助かった、というお話をお見掛けしたことがありますね。

仰る通りだと思います。純粋な追加案件で、互換性の問題もないので、記法などに追加のご意見がなければ、対応を進めたいと思います。

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 69.0.3497.81（64 bit）、iPhone 7／Safariにて確認。
正常にルビが振られているのを確認しました。
