### ISSUE TITLE
リンクボタンの条件に「or」が使いたい

### ISSUE THREAD

**Issue by toki-sor1** [snext1220/stext#51]
ドラゴンモードの解放条件の件で、サルバさん経由でRYUさんからリンクボタンの仕様についてご相談がありましたので、情報を共有致します。

> r1001:キングスライムと戦った:1:合体イベントは割愛で。
r1021:ゴブリンマスターと戦った:2:うぬの無力さ、その身で知れい！(オマエガナー)
r1028:オークキングと戦った:3:自称の王様って…キツない？
r1071:ブラッドフラッターと戦った:3:夕日♪輝～くフラッシュ逆光～に♪奴の影！！
r1072:レーベン繁殖期と戦った:4:俺の恋路をジャマする奴ぁ～俺に蹴られて死んじまえ！！
r1075:ホームラントロルと戦った:4:やったね、パパ！明日はホームランだ！(古い上によく知らない)

> 自分としては第一部を遊んでもらった事を条件にしたいのですが、ボスがらみの実績が裏ルートにしか無いのでこうなってしまいます。

> ちょうどよい実績を新たに作る事も考えてますが、それだとすでにキッチリ遊んでる方がやり直さなければならない事になるので…

> 条件にorが使えると、上記or新規の例えば「クラーケンを倒した」にできていいんですが。

こちらの機能について「実装できそう」「代わりになりそうな機能がある」等、ご意見をいただけましたら幸いです。
よろしくお願い致します。

**Comment by snext1220** [comment]
本件、スミマセン、#8 の方で同内容のご意見を募っている状況ですので、こちらはduplicate扱いでCloseさせてください。#8 側で引き続きご意見頂戴できれば幸いです＞皆さま
