### ISSUE TITLE
属性値からの空白除去

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#53]
SGMLからの属性値読み取りの際に、現在はそのままの値を取得しています。

そのため、属性値には「空白を許容しない」という制限が課せられていましたが、本Issueでこれを撤廃し、システム側で一律に属性値に含まれる空白を除去するようにします（前後の空白だけでなく、途中の空白もすべて）。これによって、シナリオ開発の際に考えるべきことを少しだけ減らせるはずです。

挙動としては変化しないはずですが、性質上、シナリオ全体に影響が出るので、テスト時には全体にわたってのご確認をお願いいたします。

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 70.0.3538.102（64 bit）にて確認。
正常に動作しました。

以前DMでは報告していたのですが、モンスターの情報で名前に空白を入れると、その空白が除去されているのを確認し、こちらは仕様ということもあり、名前の空白を「******」と修正して自己解決しておりました。

**Comment by snext1220** [comment]
すみません、空白のＤは見落としてたかもしれません...
仰る通り、まずは「？？？」や「□□□」などで逃がしていただく形になるのかなとm(_ _)m

＃ただ、どうしても困るというケースについては、今後も検討してまいりますので、お声がけくださいませ。
