### ISSUE TITLE
BGMが切り替わらない

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#54]
@Salvadors-cabin さんより戴いた報告に基づき、Issueを立ち上げています。

> 現在のGitHUBテスト環境ですが、BadとHappyのBGMが切り替わらない現象があります。
> なお、本番環境では問題ありません。iOS+Safari、Win10+Edgeの環境で確認済です。

失礼しました。
上記につきまして、 #53 の修正による問題でした。
空のbgm属性を正しく認識できなかったことから問題になっていました（January Updateの範囲だったので、本番には影響が出ていませんでした）。

先ほど修正し、GitHub Pagesに反映しておりますので、ご確認戴けますと幸いです。

**Comment by toki-sor1** [comment]
ご対応ありがとうございました。
Windows8.1／Chrome 70.0.3538.77（64 bit）にて確認。
正常に動作しました。
