### ISSUE TITLE
楽曲のシステム共通化

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#6]
SText標準で提供している楽曲をシステム共通化する。現在、シナリオ個々に共通した音源を同梱しているため、STextのサイズが肥大化している。これを共通化することで、サイズを軽量化するのが目的。

```
<init>
　<bgm main="@field01" happy="@clear01" bad="sigh" />
</init>
```

@～が標準楽曲、それ以外はシナリオフォルダーから読み出すようにする。
また、bgm属性についても同様

> ■ときのじさんご意見
> 私もGitHubからSText本体をダウンロードする際に、かなり時間が掛かるようになってきて、容量のことを気にし始めていました。もし別々のシナリオでも同曲を1つのデータとして共有できるのであれば、今後の事を考えるとその方が良いと思います。

### 懸案

+ 既存シナ全てに影響するため、最低限、スタッフ全員の同意のもとで行いたい
+ 標準楽曲は番号で良いか（識別が意外と面倒なので、一単語で命名しておいた方が良さそう）

**Comment by cocotori** [comment]
これ、ありがたい機能だと思います。
もちろん個人で自由に選曲できるけど、
STextで共通で持つことでAzさんの曲が公式曲の意味合いも強まるのではと思います。

楽曲名は番号でもいいですが、
あとに何か名前があったらいいなと思います。
30_happy01
41_dungeon01　とか。

**Comment by snext1220** [comment]
【募】本件、実行する際には、命名＆Azさんとのご調整については、どなたかご担当いただけると助かります！（Azさんは基本命名などはご自由にとのことでしたが、声がけは必要ですし、現在、Util1で提供しているものも揃える必要があるかと）

＃ 命名ルールとしては、アンダースコアが利用できないので、「happy01」のような名前になるかと。

**Comment by snext1220** [comment]
本件、諸々のやりとりから同意を得られたと判断し、システム改定作業を開始しています。
ただし、非互換箇所が多く出ていますので、仕様を明確にするために、先にマニュアルを修正しています（bgm、フォルダー構造関連を主に更新）。

https://sorcerian.hateblo.jp/entries/2018/01/28

こちらを先にご確認戴けますと幸いです。問題等ある場合には改定に反映してまいります。

なお、ある程度ご確認戴けたところで＆Azさんのリネーム作業完了したところで、まずはGitHubのみを更新し、既存シナへの反映作業をお願いできればと思っております。

**Comment by snext1220** [comment]
GitHubに新機能を反映しました。
マニュアル参照いただいた上で、各シナリオへの反映をお願いします。
＃ 現時点でScepter、Tempestのみ対応済みです。

**Comment by snext1220** [comment]
以下をご覧ください（Utility 1よりリンク）
https://soundcloud.com/venus-az/sets/sorcerian-text-original-sounds/s-2tzI5

＃ 現在ページ埋め込みになっているものはまだ古いままですが、近日中に修正の予定です。

**Comment by RYU-DS** [comment]
あとField02がなぜかDLできなくなってます。
名前変更時のミスでしょうか？
把握されているならいいのですが…

**Comment by RYU-DS** [comment]
曲名ですが、AZさんのサイト上では頭文字が大文字（End01）ですが、DLしたデータでは小文字となっています（end01）、どちらを使うのでしょうか？

**Comment by snext1220** [comment]
> main/happy/badは１つしか指定できませんか…

はい、今回はあくまでSText軽量化の対応なので、ご容赦をm(_ _)m
新たにIssueを立てて戴ければ、スタッフの皆さんの意見も伺いながら要求の有無（強弱）を確認できるかと思いますので、宜しければ。

＃ Issueの立て方については以下も参照ください。https://github.com/snext1220/stext/wiki/Issue%E3%81%AE%E9%81%8B%E7%94%A8%E6%96%B9%E6%B3%95

> あとField02がなぜかDLできなくなってます。

スミマセン、こちらは現在Azさんにご調査お願いしておりますので、お待ちを...

> どちらを使うのでしょうか？

曲名は小文字でお願いします（こちらも統一をAzさんにお願いしています）

＃ ミニ30シナのご送付もありがとうございました。テストページは以下（https://snext1220.github.io/stext/index.html?id=fortune）
恐らく本番サイトからGBAT2STextを起動された故かと思いますが、（まだリリース前なので）現在はbgm未反映になっているようです。リリース前のGBAT2STextはテストページ下部の［ファイル選択］からご利用ください。

**Comment by snext1220** [comment]
Field02の件、大文字小文字の統一について、Azさんに対応頂きました！
Util1の埋め込みページについても反映済みです。
