### ISSUE TITLE
［戻る］時にBGMが戻らない

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#60]
#18 の影響で［戻る］のタイミングで前シーンのbgm属性が認識されていませんでした。

この対応として、［戻る］時にbgm属性を処理するための処理を追加しています。

#### お知らせ

bgmについては複数BGM、［戻る］、マルチエンディング曲の影響で、後付けでかなり複雑な分岐をしており、ここからの修正が難しい状況になりつつあります（バグも頻発するようになっています）。
BGMについては、この後、機能追加は他機能よりも慎重になっていくと思われますので、ご了承ください。
＃今後癌になりそうなので、BGM管理は一から書き直したほうが良いかもしれないです…

**Comment by snext1220** [comment]
現在はシーン遷移で前後のBGMから変化を検知しているのですが、様々なパターンがあり、その辺に無理が出ているのかもしれません。場合によってはbgm要素配下に、以下のようなsource要素を設け、曲単位に（メイン、エンディング以外）適用する曲範囲を指定するという形の方が現実的かもしれません。

```
<source bgm="@field05" range="10-14,20-30" />
<source bgm="@field06" range="15,18,40" />
```

range属性で指定されたシーンに、それぞれBGMを適用。

元々が複雑な制御なので、すぐさまに動かす予定はありませんが、曲切り替えを多用しているシナリオ作者さんは、引き続きご相談させてください。

**Comment by snext1220** [comment]
本件、たびたび申し訳ありません。

今後のバグの可能性が強く懸念されたので、取り急ぎ互換性を維持できる範囲で、bgm確定のロジックを整理しました。機能テストデータのレベルでは問題なく動作していますが、bgm回りのコードを完全に置き換えていますので、機能テスト時には、初回起動、再開、切り替え前後、戻るなど、気にしてご確認戴けますと幸いですm(_ _)m

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 70.0.3538.77（64 bit）にて確認。

「少女英雄」「魂」でテストプレイしたところ、
- 通常のシーンでは、問題なくBGMが再生されたり、シーンが戻った時も指定したBGMが流れるようになっていました。
- しかし、エンディングまで「ブラウザの戻る」が有効になってしまったため、1回のシナリオプレイで何度も繰り返して同じエンディングを見ることができてしまう（＝ボーナスアイテム取り放題）。

という感じで、エンディングに関する不具合が出てきてしまったようです。

**Comment by snext1220** [comment]
ご指摘ありがとうございます！
本件、#61 に移動しております～
