### ISSUE TITLE
${if}、シーン移動ボタンの条件分岐式

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#65]
February Update以降、条件分岐系の機能に諸々手が入ることを想定し、以下の改善を施しています。

+ これまでシーン移動ボタン専用であった条件解析のコードを整理し、拡張性を改善
    + 新構文の追加を比較的少ない工数で可能にしました
+ 伴い、シーン移動ボタンと${if}式（#12）の条件分岐構文を共通化
    + シーン移動ボタンで利用できる構文は${if}でも利用できます。

ただし、従来のシーン移動ボタンを制御していたコードを完全に置き換えていますので、シーン移動ボタンの挙動に問題が出る可能性があります。

お手数をおかけしまして恐縮ですが、コアな機能なので早めに整理しておいた方が、結果的に、バグの発生を抑えられると判断しました。恐縮ですが、機能テストに際しては、お手元のシナリオ（分岐系）の挙動を注意してご確認戴けますと幸いです。

**Comment by toki-sor1** [comment]
Windows8.1／Chrome 70.0.3538.102（64 bit）、iPhone 7／Safariにて確認。
「少女英雄」「魂」「道場」でテストプレイを行いましたが、特に問題なく動作していました。
