### ISSUE TITLE
デバッグモードでの実績設定

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#66]
@toki-sor1 さんからご質問戴いたので、こちらで共有します。

> ドラモードでは特に「他シナリオの実績の有無」が絡んでくるのですが、デバッグモードで一時的に実績の有無を設定することはできるのでしょうか？もし可能であれば、ドラモードではテスト時に便利かなと思うのですが（現在はシナリオの設定を書き換えてテストしています）

現時点では、残念ながら未対応です。
一寸面倒ですが、基本情報のセーブデータをバックアップいただいて、該当するシナリオの実績を追加＆リストアいただく形ですかね...（以下、見やすいように改行しています）
＃ブラウザー操作に練達されている方は、ブラウザー（デバロッパーツール）から直接編集しても構いません。

```javascript
{
"items":["gi14","bgi03","gi04","bgi05"],
★"results":{
"scepter":["r01","r03","r02","r04","r06","r07","r05","r10","r13"],
"playground":[],
"fortune":["r30","r1"],
"tempest":["r13"],
"trial":["r06","r07","r08","r09","r04"],
"inn":["r01","r31","r61","r32","r33","r22","r51","r12","r11","r13","r21","r52","r41","r42","r72"]
},★
"bgm":false,"panel":true}
```

★～★の箇所が実績なので、既存の記述に倣って実績idを追加／削除戴けます。

**Comment by toki-sor1** [comment]
デバッグモードでは未対応なのですね、承知しました。
しかし、セーブデータを編集することで、実績の有無を変更することは可能なのですね。
こちらの方が各シナリオの実績を一度に編集することが可能なので、とても便利だと思います。ありがとうございました！
