### ISSUE TITLE
attack属性の選択肢追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#67]
#57 の内容を実現できそうなもの＆優先順位の高いものから、分離＆実装していきます。

表記テーマについて、無数のパターンを包括するのは難しいので、ある程度汎用性を期待できるパターンから追加していきます。

+ both：物理／魔法の両面攻撃。atk_both.png
+ free1～3：Free欄への反映（アイコンは［F1］［F2］［F3］。数字は下付き文字？）。atk_free1～3.png

上記については早速対応し、GitHub／本番環境にも反映済みです。
また、適用第一号としてトラ☆のダブルデビルスでFREE1ダメージを利用可能にしました。

@toki-sor1 さん＞早速、アイコンのご対応を戴き、ありがとうございました！

**Comment by toki-sor1** [comment]
反映ありがとうございます！
「トラ☆」のFREE1確認致しました！（Playgroundのbothも同時に確認済み）
現状は大丈夫そうかなと思いつつ、ご要望がありましたら都度対応致しますね。

**Comment by snext1220** [comment]
早速のご確認ありがとうございます。
アイコン画像の方はまさにイメージ通りでバッチリでした！
随時、設定値のパターンを増やしていく可能性はありますが、その際はまたご相談させてくださいませm(_ _)m
