### ISSUE TITLE
シナリオ情報（stext.xml）の追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#68]
シナリオ情報をより詳細に表示できるよう、stext.xmlの`<work>`要素に対して、以下の属性を追加します。他に表示しておきたい情報があればお願いします。

+ series：シリーズ名（ドラゴンモード Vol.1など。ある場合だけ）
+ tags：分類（戦国、ダークファンタジー、ギャグ、日常、リメイクなど。複数可）
+ published：公開日（「2018-01-05」の形式。未公開時は頭に「!」）
+ level：難易度（5段階） ※当面は未使用？
+ scenes：シーン数
+ comment：著者からのコメント（50～80文字程度）

また、紹介文と合わせて表示する画像も、シナリオデータと合わせて指定できるように改めます。

+ ファイル名：intro.png
+ 画像サイズ：120×180px（暫定）

**Comment by toki-sor1** [comment]
新属性は、シナリオ選択時に皆さんが知りたいことをフォローしていると思いますので、私の方では今のところ新しく思い付くものはないですね。

「level」も当面は未使用としつつ、皆さんのご意見次第では早めに入れても良いかもしれないですね。
ただ、作者自身が判断するのは基準にバラつきが出る恐れがありますので、以前リオさんが仰っていたように、一人が判断するのが良いと思います（その後、決められた難易度に作者が納得いくか否かを確認すると安心？）

画像の追加もし易くなって良いと思います。

**Comment by snext1220** [comment]
ご意見ありがとうございます！

今後ですが、12/20以降にstext.xmlをコピーして、新仕様で皆さまに各シナの情報更新をお願いさせて戴くかと思いますので、またどうぞよろしくお願いいたします！
＃levelについては、とりあえず私がざくっと入れて、あとは「問題あればご指摘を～」という程度にできればと（運用はまたおいおい考えますｗ）。

**Comment by snext1220** [comment]
こちら追加項目のご要望もなかったようなので、これで作業を進めてまいりたいと思います。
お手数ですが、まずは新規フォーマットでstext.xmlの更新をお願いできますでしょうか。

既に拙作「終焉のゼロ」などを新規フォーマットで更新済みなので、更新に際しては、こちらをご参考にして戴けますと。紹介イラストもintro.pngで/captureフォルダーの中に配置し、`<img>`要素のパスを置き換えて戴ければそのまま表示されるはずです。

皆さまの更新が完了したところで、サイトの見た目も更新予定です。

@Salvadors-cabin さん、お手数ですが、ゲスト投稿者さまへのご連絡もお願いいたしますm(_ _)m

**Comment by snext1220** [comment]
stext.xml 情報追加後の表示イメージを作成していますので、ご参考までに（見た目などで、もしご意見ありましたら、お願いします）。levelは現時点では未使用です。
本番サイトでコメントアウトした状態なので、6～7割揃ったところでリリース掛けたいと思います。

![default](https://user-images.githubusercontent.com/27911337/50380082-a89dee80-069f-11e9-99f8-484d15788b08.png)

**Comment by cocotori** [comment]
わたしの3シナリオ分、stext.htmlの更新終了しました。
公開日についてですが、
実際の日付をメモしていなかったので、シナリオ自体の更新履歴から拾ってきました。
ズレがあったらすみません。

**Comment by snext1220** [comment]
早速ありがとうございます！
公開日については更新履歴にまとめておりますので、こちらご参考にしてください。
https://sorcerian.hateblo.jp/entry/20180507

＃ ネコは恐らく最終更新日を拾われているように見えましたが、実は「初期公開日」と「最終更新日」の2種類があった方が良いでしょうか？？

**Comment by Salvadors-cabin** [comment]
これまで外部投稿者さまにはDMで開発者マニュアルのカテゴリを指定して誘導していたのですが、今回の追加ってマニュアルにありましたっけ？

**Comment by snext1220** [comment]
皆さま＞
先に挙がっていました最終更新日ですが、システム更新への対応も指定ただ抱いておりますし、そのドラのような分割公開のケースもあることから、「最終更新日」もあった方が良いと判断し、@updatedを追加しています。単発でのお願いとなってしまい恐縮ではありますが、合わせての追加を戴けますと幸いです。

@Salvadors-cabin さん＞stext.xmlの仕様はWiki側でまとめていますので、此方をご利用ください。https://github.com/snext1220/stext/wiki/GitHub%EF%BC%8FFTP%E3%81%AE%E9%81%8B%E7%94%A8

@toki-sor1 さん> ありがとうございます！

**Comment by snext1220** [comment]
Ｄより移動しております。

> soulとshadowのscenario.xmlのみ、誤字や改行の修正があり、本番環境の方も更新しています。

こちらについて。

皆さま（現時点では @cocotori さんと @toki-sor1 さん？）：
intro.pngを入れたシナリオを本番環境にも反映頂けますと幸いです。

現在、本番環境とGitHub環境のstext.xmlが食い違ってしまっているようなので、同期しておきたいと思います（現時点では、新属性情報の表示ロジックはコメントアウトしているので、それによる表示の影響はありません）。

**Comment by cocotori** [comment]
updatedの追加、intro.pngの本番環境への追加、終了しました～

**Comment by toki-sor1** [comment]
> 現時点では、新属性情報の表示ロジックはコメントアウトしているので、それによる表示の影響はありません

新属性情報はコメントアウトしているのですね。安心しました！
updatedの追加に伴い、GitHubと本番環境のstext.xml更新、intro.pngの本番環境への追加しました～。

**Comment by snext1220** [comment]
ありがとうございます！こちら、これで9/15が対応済みとなりましたので、暫定ではありますが、本番環境にもリリースいたしました。

お手数ですが、未対応のシナリオについては、引き続きご対応のほどをお願いいたします。

**Comment by Salvadors-cabin** [comment]
確認してみましたが、これまで外部投稿者様にはstext.xmlの変更はお願いしておらず、仕様も連絡していなかったように思います。ちゃなさん、RYUさんにはWeb紹介文の追加情報として連絡しておきました。新規の外部投稿者の方には今後シナリオを公開するときの紹介文の要請の中に含めたいと思います。

**Comment by snext1220** [comment]
> 今後シナリオを公開するときの紹介文の要請の中に含めたい

ありがとうございます！お願いいたします。

なお、新規登録フォームにもstext.xmlに対応した項目（分類、作者コメント）を追加しておきました。
https://ws.formzu.net/fgen/S13986743/
＃ 他の項目はスタッフ側で入れられる（or/and 入れるべき）内容なので、追加しておりません。

**Comment by snext1220** [comment]
ゲストさん情報含めて、stext.xml がほぼ出そろったところで、当方でいくつかの調整を行いました。

+ levelの変更
+ 不正な値については修正（levelは数値に、単作でのseriesは空に、など）
+ ゲストさん作品のresults、clearsの追加

お手数ですが、results／clearsの内容、最終的な表示内容含めて、ゲストさんに内容ご確認戴けますと幸いです＞ @Salvadors-cabin さん

お手数ですが、ご担当シナリオへのresults／clearsの記入をお願いします＞ @toki-sor1 さん、@cocotori さん

**Comment by cocotori** [comment]
results／clearsの追記終わりました。

あと、今回は構わないのですが、
クリア実績に複数の実績を指定することは出来ないでしょうか？
A,B,どちらかの実績を持ってたらクリアとしてみなす、というような。
マルチエンドで、どちらかがバッドというわけではないようなシナリオが
今後出てきた時、あるといいかなと思いました。

今のままでも、ルートAでは実績A,Cを
ルートBでは実績B,Cを取得させ、
クリア実績をCにすれば可能かと思いますので、
必須ではありませんが。

**Comment by snext1220** [comment]
クリア実績、現状もカンマ区切りで複数指定可能です～
王杖や占いなどはそのようにしておりますので、ご参考にしてやってください。

**Comment by toki-sor1** [comment]
お待たせしてしまい申し訳ありません。
results／clearsの記入が完了し、GitHub・本番環境共に反映済みです。
