### ISSUE TITLE
ダメージ式への乗除演算

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#69]
#57 からの派生です。

ダメージ演算に対して、×2、×1/2、×1/4するための機能を実装します。
主に、魔法での補正、シナリオ特定の条件でのダメージ補正にご利用ください。
＃ 現時点では、敵リストのフッター（またはヘッダー）部分に、［×1］［×1/2］...の選択ボックスを配置することを検討しています。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 71.0.3578.98（64 ビット）、iPhone 7／Safariにて確認。
×2、×1/2、×1/4も正常に動作していました。

しかし、両環境で「name」が長いことが影響しているのか、「ダメージ式」が途切れて表示されているケースを確認しました（参照画像は、『常闇』のscene 55です）。

「name」が長いダメージ式が含まれるscene 41では、ダメージ式が折り返されているので、原因は複合的なものかもしれません。

**Comment by snext1220** [comment]
お待たせしました。
上記件、対応完了し、GitHub／本番環境に反映していますので、ご確認戴けますと幸いです。

これまでは単語の区切りで折り返すようにしていましたが、行末で無条件に折り返すように改めています。若干見難くはあるのですが、あまり可読性を問う箇所でもないので、ご容赦くださいませ。
＃ なお、今回の修正に伴い、以前の「>」限定対応は解除しています。
