### ISSUE TITLE
自由アイテムの新設

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#7]
任意の場所で使用できる自由アイテム。数の概念を持っており、複数持つことも可能。利用時はステータス画面から個数を修正

```
<free-items>
  <free-item id="fi01" name="Gold">売買のためのお金</free-item>
  <free-item id="fi02" name="回復役"></free-item>
</free-items>

<scene free-items="fi01:10, -f02:2"> → fi01を10個入手、fi02を2個削除（削除は手動と割り切った方が良いかも）
```

緩募： free-itemという用語がイマイチなので、何か良い単語があれば

> ■ときのじさんご意見
「ラミディア」のようにGP（金貨）を管理したり、使用回数の制限があるアイテムを登場させたりする時に便利そうですね！削除も指定できれば、よりアイテム管理が楽になると思うのですが、他のシステム等に不具合が出たり、実装のハードルが高い場合は、手動として割り切るのが良いと思いました。
> free-item＞魔法発動ボタンでもあった問題なのですが、耳慣れない（見慣れない）言葉を使用すると意味が伝わりにくくなってしまうので、個人的には現状ままも良いかなと思いました。もしくは、今までのitemと今回のfree-itemを合体させて「item」とするのはどうでしょう？（既存シナリオに相当影響が出てきてしまいますが、アイテム欄を1つにまとめられたら良いかなぁと；；）

既存のアイテム（`<items>`）の中で表すことも可能ではありますが、いわゆるイベントアイテム（従来）と自由アイテムとは区別しなければならないため、なにかしらis-freeのような属性で管理することになるかと思います。と考えると、大本で分けておいた方がシナリオ開発者の皆さんにとってもすっきりかもしれません。

### 懸案

free1、free2、stars属性を追加した結果、実は、自由アイテムの必要性が薄れたかもしれません。暫くはご意見待ちますが、「こんな使い方をしたい！」等の要望が出ない場合は廃案にするかも。

**Comment by RYU-DS** [comment]
ウチでもエリクサーの使用（消費）で苦労したので、プレイヤーが使用できるアイテムはぜひ、というかRPGならあるべきと思います。
名称は、一般的には使用できるのが「通常アイテム」でイベント物が「イベント（固定）アイテム」と呼称するので、既存の方を「固定/イベント/フラグアイテム」と変えた方がいいかもしれません。

**Comment by snext1220** [comment]
エリクサーについてはFree1、2で賄えませんでしょうか。
Free枠が少ないようであれば、3～4枠程度までであれば拡張もありかなと。
＃ あまり多くすると、利用しないシナにとっては邪魔になるので、その位が良いところかと。

**Comment by RYU-DS** [comment]
無いなら無いで今回のようにとかfreeで対応は出来るのですが、普通に消費アイテムがあるとRPGゲームらしさが俄然違ってくるので、現状必要かどうかではなく「あるとすごくよい（あるべき）」というスタンスです。
free枠は確かにもう少しあった方がいいと思います。そのスレでも2つでは足りていないので…
※1つはEXPで必須、2つめをLvにしたいが、現戦闘のDM軽減値に使わないと計算が大変。

**Comment by snext1220** [comment]
［Expired soon］からひと月経過しましたが、意見もあまり出なかったことから要望少と判断し、今回は #38 のfree3追加のみの対応とし、［wontfix］（Close）とさせてください。

RYUさん：
「らしさ」という点はご指摘の通りだと思うのですが、現状のfree枠と機能が重複する点から、まずは、他の機能を優先すべきと判断いたしました。将来的にReopenするかもしれませんが、その場合も重複する機能の整理をしてからになりそうです。恐縮ですが、ご了承ください。

**Comment by snext1220** [comment]
■開発メモ■

`<item free="1" name="Gold">ものの売買に利用する</item>`

+ free属性でfree1～3にアイテムを割り当てる
+ 【懸案】ステータス画面上の表示。アイテムではなくinit要素で割り当てを決めるべきか

**Comment by RYU-DS** [comment]
現在、そのスレのエリクサーはゾマ説明から使うと、「戻る」が完全ロールバック化したため使っても無くならない状態になってしまっています（モス戦では無くなる）。
FREEはすでにいっぱい、と言うかかなり特定の場合にしか発生しないアイテムにFREEを1つ使うわけにもいかず…
クリックするとシーン移動せずに指定した条件だけを実行（アイテム01をマイナスなど）するボタンって作れますかね？（シーン移動せずともその場で実行される）

**Comment by snext1220** [comment]
現時点では「アイテムを使った」というシーンを設けて、また戻っていくことをお勧めいたしたく。

一応、アイテムのその場更新そのものは、 #57 の延長でできそうな気はするのですが（詳細は検討要）、もともとイベントアイテムがプレイヤーの任意で∓できる想定ではないので、諸々矛盾が出てくるかと（シナリオ側の責任といえばそうなのですが、これまでも結局はそうはいかず、矛盾を塞ぐために更なるシステム対応という歴史だったので、消極的です^^;）

こちらは恐縮ですが、以降は #57 に移動戴くか、別Issueを立てて戴いた方が良いかもしれません。

＃あと恐縮ですが、想定箇所などscene idで示していただくと、想定されている内容がより明確となり、助かります。ご協力頂けますと幸いですm(_ _)m

**Comment by RYU-DS** [comment]
現在、シーン2101～2631までの森の戦闘シーンは各種NPCの説明（425/442/443/444）へ飛べるようになっており、その中のリッチー説明（444）からさらにエリクサー使用（447）へ行くようになっているのですが、ロールバックせずにとなると全てのシーンへ個別に戻る＝全てのシーンにこれらを埋め込むとなるので、これから先の事を考えればなおさらですが実質不可能でしょう。

結局「どこででもプレイヤーが任意に使える消費アイテム」というのは現状では無理で、それがたまたま以前の「戻る」の穴を利用すると可能だったのでやりましたが、ロールバックの改善（もちろんこの方がいいのですが）でできなくなってしまったので、現状の減らずに使い放題か、もしくは削除するしかないと思っています。
「文中へのボタン追加」で対応できるとよいのですが…
あとは消費型アイテムのシステムの導入待ちでしょうか。

**Comment by snext1220** [comment]
> 「文中へのボタン追加」で対応できるとよいのですが…
> あとは消費型アイテムのシステムの導入待ちでしょうか。

こちらは残念ながら、いずれが導入されたとしても、結局はセーブデータのロールバックで打ち消されるので、解決にはならないかと思います。。
申し訳ありませんが、ご了承くださいませ。

**Comment by RYU-DS** [comment]
＞「文中へのボタン追加」で対応
${button items:ｰi2535}
という形で「アイテムを減らすボタン」が作れれば、アイテム消費シーンは不要となるのでロールバックする必要は無く、戦闘シーンにボタンを埋め込めば可能となり…それでもかなり手間ですがまだ現実的です。

＞あとは消費型アイテムのシステムの導入
これはどういう形かによりますね。シーン側でどうこうするなら上記と同じですが、ステータスウィンドゥでクリックして～であれば…
あ、単純に「メモ欄に現われるアイテム」でも面白いかもしれませんね。プレイヤーの手で消せるだけという（全て自己責任）。

ついでにそういう消費型アイテムの提案を。
「ポーション(3)…HPを30回復」といった感じで使用回数が指定できるといいかと思います。
これをクリックするごとに(2)＞(1)と減り、(1)の時にクリックすると無くなる、効果は手動で。

**Comment by snext1220** [comment]
> アイテム消費シーンは不要となるのでロールバックする必要は無く、

その場で利用できても、マニュアルの中なので、結局は戻らなければならないように見えるのですが、如何でしょうか（その場合はやはりロールバックされます）。

**Comment by RYU-DS** [comment]
いやその「ゾマ説明中からエリクサー」ってのから一旦離れましょうｗ
上記のアイテム消費ボタンが実装されたら、私は全ての戦闘にエリクサー消費ボタンを付けます、という事です。

**Comment by snext1220** [comment]
FREE1～3ラベル用にintro－label要素を追加しました。
詳しくはマニュアルも参照ください。

GitHub／本番環境双方に追加済みです。
また、終焉のゼロには既に適用しているので、ご参考にどうぞ。
