### ISSUE TITLE
stext.xmlのscenario.xmlへの統合

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#71]
stext.xmlの更新競合の問題が出てきていたため、
シナリオ情報をscenario.xmlに統合することを検討します。

**予定している仕様： https://sorcerian.hateblo.jp/entry/2018/11/01/211745
intro要素を参照下さい**

ただ、STextページを表示する度にすべてのscenario.xmlをチェックするのは現実的でないため（速度的に）、scenario.xmlの更新後、動的にstext.xmlを生成するような形になるかと。

運用含めて検討するため、少々お時間ください。

**Comment by snext1220** [comment]
ん～手元でシミュレートしていますが、スタッフが管理すべき項目と、シナリオ作者さんが管理すべき項目が完全に分離できず、あまり効果が見込めない感じですかね...
＃ scenario.xmlをざくっと見た感じ、結局、tags、comment、#textを除いては、stext.xmlに戻ってくる感じ（title、authorすら表記揺れの問題でscenario.xmlのものを使いにくい）。

ご意見見つつではありますが、現状維持でも、という気がしてきています...

**Comment by toki-sor1** [comment]
シナリオ情報など、競合を気にせず自由なタイミングで編集できたり、更新日などを入力しなくても良いというのは魅力的です。
ただ、以前リオさんも仰っていたように、普段は今ほどstext.xmlを頻繁に編集することはないので、今すぐ改良が必要かどうかと考えると、個人的には「現状維持」も良いのではと思っています。

**Comment by snext1220** [comment]
ご意見ありがとうございました！
こちら追加要求は弱そうなので、現時点ではwontfixとしてまいりますね。

ただ、#79 でも出ていますが、プレイヤーの達成度強化のために引き続き実績関連（results、clear）の属性をscenario.xmlに追加検討していければと思います。引き続きご意見のほどをお願いいたします。
