### ISSUE TITLE
Playgroundの初期表示

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#75]
#72 を受けてのIssueです。

> 目立たない ⇒ Playground実行時に初期表示は、現在ガンガン利用されている方にとっては少々気になるかもしれませんが、「チュートリアルが用意されている」ということに気付いていただくには、最も適しているかなと思います。

Playgroundでチュートリアルを初期表示します。
ただし、繰り返し利用する人には余計なので、以下の対策を採ります。

+ 編集時に最後の編集内容をストレージ保存
+ 再立ち上げに際して、過去データがない場合にだけチュートリアルを表示

**Comment by snext1220** [comment]
諸々試してみたのですが、最後の編集内容を表示するのは意外と邪魔っぽかったので^^;、
初期表示時にだけチュートリアルを表示するように改めてみました。
2回目以降では自動表示されませんが、チュートの中でどこで起動できるかを明記すれば十分かなと。
ご意見戴ければ幸いです。

**Comment by toki-sor1** [comment]
> 初期表示時にだけチュートリアルを表示するように改めてみました。

そうですね、シナリオの動作確認をしたいという御方が、ページを開く度にチュートリアルが表示されると煩わしさを感じてしまうかもしれないので、現在の仕様が良いと思います。

> 2回目以降では自動表示されませんが、チュートの中でどこで起動できるかを明記すれば十分かなと。

この対策でバッチリだと思います！

**Comment by cocotori** [comment]
確認しました。大丈夫だと思います！
