### ISSUE TITLE
道場（Trial）の強化

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#76]
#72 を受けて、Issueを立ち上げております。

> 道場でも現在公開中の内容は「GBAT編」と位置付けていますので、今後SGMLの解説も含めていければと考えています。

是非、宜しくお願いします！

ただ、今回チュートリアルも加えていますので、そちらとあまりに重複しても勿体ないですし、テーマ選択は悩ましそうですね；

若干記憶が曖昧ではあるのですが、以前、道場で個別のTIPS集（「自由入力欄を利用するには？」のような小粒モノ？）を、のようなお話があったかと。チュートリアルとマニュアルを埋めるという意味では、こうした一問一答でやりたいことに応えてくれるコンテンツがあっても、とは思いました。

> ただ、用語解説に特化させたマニュアル系か、それともストーリー仕立てでシナリオを一から作成する系か、構成に悩みますね。

個人的には、道場の拡張であれば、統一性と親しみやすさを優先して、ストーリー（会話）仕立てかなと…！（それでもUtil としては分離した方が良い？？）
＃ただ、シンプルさを重視するのであれば、道場から切り離した方が良いかも？

用語解説については、マニュアルの方が向いてそうなので、この辺を充実させよなどあれば、こちらで対応いたします～

**Comment by cocotori** [comment]
もともとの道場が物語チックにコミカルな感じになっているので、
それが継続できたらいいですね！

**Comment by toki-sor1** [comment]
返信が遅くなってしまい申し訳ありません；；
道場強化のご意見や現道場についてもありがたいお言葉、本当にありがとうございます！

### 作風
現道場も親しみ易さと分かり易さを重視していたので、道場を強化する場合は **「物語チックにコミカルな作風」** を継続したいと思います。

### 内容
これがとても悩みます……。
というのも、現在STextのシステムやPlaygroundも目まぐるしく進化しているのですが、物語仕立ての場合、 **システムに変更が出たときに内容の修正が難しく、対応が追い付かない** ことも考えられるからです；

ただ、現道場では「シナリオをいちから完成させる」という連続した物語にしていたことで、内容の修正に手間取っていたところもあるので、 **「個別のTIPS集」というそれぞれが完結しているタイプの物語（対談？）** であれば、物語の繋がりを意識する必要がないので、内容の修正もし易いかなと思います。

> ＃ただ、シンプルさを重視するのであれば、道場から切り離した方が良いかも？

そうですね、「個別のTIPS集」という方向性であれば、 **道場ではなく別の形として展開した方が良いかな** と思います。
イメージ的には、原作ユーティリティ「おたよりをよみたい」で、 **架空のおたよりコーナーとしてソーサリアンがお悩みに答える** 感じが面白そうだなぁと思っていますｗ（実際に質問があったら、その質問にもお答えします、なスタンス）

＃今思い出しましたが、 **ミニミニソーサリアンNextマニュアル「【Ｑ＆Ａ】真面目に回答！でも時々ちょっとヘン？」** （https://sorcerian.hateblo.jp/entry/20130331/1364732722 ）が、そんなノリだったなぁとｗ
![image](https://user-images.githubusercontent.com/42646342/54050046-9acd2380-4221-11e9-9090-6a7667160fdf.png)

**Comment by snext1220** [comment]
こちらもご検討ありがとうございます！

> 内容の修正が難しく、対応が追い付かない ことも考えられるからです；

強く同感です！
我田引水ですが、システム／サイト／マニュアルも、工数の半分以上はメンテ性の向上（維持）に充てている感じです^^; それでも日々の新機能追随には結構手間がかかってるので、そこは外して考えられないですね～（やはりメンテよりも新規の創作に力を入れたいですし！）

ということで、以下に強く賛成です！

>原作ユーティリティ「おたよりをよみたい」で、 架空のおたよりコーナーとしてソーサリアンがお悩みに答える 感じが面白そう

良いですね！
SText Utilityは原作由来の名前付けがメインなので、それにもマッチしますし。
なにより、 https://github.com/snext1220/snext-management/issues/7#issuecomment-468570841 
でも話題に出たまとめ課題の解消という意味でも、今後、執筆者さんからの質問に答える、という意味でも良いと思います！

＃確かに、旧ミニソーNextのマニュアルはそんな感じでしたね～

プラットフォームとしては、道場と同じく、STextでしょうか。「新時代～」の方でもどちらでもいけそうではありますが…

### 余談

とりあえずNew Playgroundもβリリースしましたので、こちらはマニュアルとして「新時代～」に追加の予定です！

**Comment by toki-sor1** [comment]
ご意見＆ご賛同ありがとうございます～。
仕様としてほぼ決定かなと思われる項目は割愛しながら返信しますね～。

> プラットフォームとしては、道場と同じく、STextでしょうか。「新時代～」の方でもどちらでもいけそうではありますが…

私も道場と同じSTextか「新時代～」等にまとめるか悩んだのですが、 **「おたよりをよみたい」らしい演出（BGMが流れる）ができるのは、やはりSTextかな～** と思っていますｗ

> とりあえずNew Playgroundもβリリースしましたので、こちらはマニュアルとして「新時代～」に追加の予定です！

#102 とマニュアル例（https://www.crumblyheadgames.co.uk/gamebook-authoring-tool-help/how-to-use-the-gamebook-authoring-tool/ ）を拝見しましたが、 **まとめ方もシンプルかつ見易くて良いと思います！**

**Comment by snext1220** [comment]
> 「おたよりをよみたい」らしい演出（BGMが流れる）ができるのは、やはりSTextかな

了解です～では、Util 7として追加する感じですね！
まずはドラモードでよく出た質問の再まとめなのかな～と想像しておりますが、どうぞよろしくお願いいたします！

> まとめ方もシンプルかつ見易くて良いと思います！

こちらもご了解有難うございます～ミドル100?が本格稼働する前にこちらも整備できればと！
＃と言いながら、プレイヤーマニュアルが古くなっているのに気づいて、慌てて更新してました^^;

**Comment by snext1220** [comment]
現在、Issueの整理を行っておりますが、本件如何いたしましょうか。
発案から時間も経過しておりますため、感触のお伺いまでに～

**Comment by toki-sor1** [comment]
長らくお時間をいただいたまま結論が出ず、そのままとなってしまい申し訳ありません；
道場の強化ですが、前回の道場シナの経験を踏まえて、下記の理由から**現状では強化は厳しい（＝断念）** と考えています；

- Pg自体が日々進化している最中であること（＝システムの入れ替わりが激しい）
- それによる修正・追記に手が追い付かない可能性が高いこと

散々お待たせしての返答が大変不甲斐ないもので、本当に申し訳ありません…；
**こちらのIssueは整理の際にCloseしていただけましたら助かります**…よろしくお願いいたします；；

**Comment by snext1220** [comment]
ご検討ありがとうございます！

道場の強化＞はい、PgFlowの変化も激しいですし、旧道場のようなストーリー仕立ては難しいですよね^^; まずはFlowマニュアルのメンテを検討してまいります！（こちらもシーン組み立て周りが流動的なので、現時点での修正は様子見しています）

「おたよりをよみたい」＞こちらについては如何でしょうか。以前、ドラモードの時に、執筆参加者さんの質問＆回答が結構お手間だったかと思うので＆揮発性ですと毎回の負担になってしまうので、幕末前になんらかの対策を打った方が良いのかなと思ったもので^^;

**Comment by toki-sor1** [comment]
> 道場の強化＞はい、PgFlowの変化も激しいですし、旧道場のようなストーリー仕立ては難しいですよね^^; まずはFlowマニュアルのメンテを検討してまいります！（こちらもシーン組み立て周りが流動的なので、現時点での修正は様子見しています）

道場の断念、申し訳ありません；；
マニュアルのメンテ、よろしくお願いいたします！！

> 「おたよりをよみたい」＞こちらについては如何でしょうか。以前、ドラモードの時に、執筆参加者さんの質問＆回答が結構お手間だったかと思うので＆揮発性ですと毎回の負担になってしまうので、幕末前になんらかの対策を打った方が良いのかなと思ったもので^^;

確かに、ドラモードの時の反省点として、質問＆回答が重複してしまっていたことが第一に挙げられますし、それらが埋もれてしまうことも同じことの繰り返しになってしまいそうですもんね；

道場を断念した代わりにSText版「おたよりをよみたい」を作ってみました！（GitHubのみアップ）
https://snext1220.github.io/stext/index.html?id=letter

イラストが仮状態なのですが、なるべくメンテが楽になるような構造にしてみました。
こちら、質疑応答コーナーとして使えそうでしょうか？

「ソーサリアン Textの概要」辺りの認識が自信なしなので（汗）、「ここはこうして欲しいな！」という箇所がありましたら、どうぞ遠慮なく仰ってくださいませ～。

**Comment by snext1220** [comment]
> マニュアルのメンテ、よろしくお願いいたします！！

了解です！こちらはたぶん今月～来月のUpdateで現在流動的な改定が一段落つく?と思うので、このタイミングで大幅リニュしていければと～（3周年前には余裕をもって完了させたいところ；）

おたよりをよみたい＞おぉお、早速ありがとうございます（早い！！！）
早速拝見しまして、全く問題ないと思います。
気軽に読めるテイストも良いですし、夫々の回答キャラの色も出ているのがGoodですね～
構造もメンテしやすい感じでよいかと思いました！（構造化されているので、コンテンツが増えてきたときにも改築が簡単そうですね）
＃複数人で気づいたものから追加＆メンテしていく感じでしょうか？（それとも、おひとりの方がやりやすい？）

>「ここはこうして欲しいな！」という箇所がありましたら、～～

些細なことですが、ブラウザバックが微妙に面倒に思えましたので、場合によっては共通インポートを利用して各ページから［トップへ戻る］のリンクボタンがあっても良いのかなと思いました～

**Comment by toki-sor1** [comment]
> 了解です！こちらはたぶん今月～来月のUpdateで現在流動的な改定が一段落つく?と思うので、このタイミングで大幅リニュしていければと～（3周年前には余裕をもって完了させたいところ；）

ここのところ一気にアップデートしていましたもんね～。いつもお疲れ様です…！！
余裕をもって完了させたい、同感です…；；

> おたよりをよみたい＞おぉお、早速ありがとうございます（早い！！！）

早速のご確認＆ご感想ありがとうございます～！
内容的にも問題ないようで安心しました！
どういう風にまとめようかと悩みましたが、お馴染みのキャラに喋ってもらうなど道場での経験が活きましたｗ
実は音楽も原作の曲に近いものを、と意識していたので、そう言っていただけてガッツポーズですｗ

> シナリオの構造もメンテしやすい感じでよいかと思いました！（構造化されているので、コンテンツが増えてきたときにも改築が簡単そうですね～）
＃複数人で気づいたものから追加＆メンテしていく感じでしょうか？（それとも、おひとりの方がやりやすいでしょうか？）

はい～、メンテや改築のことを考えて極力シンプルな構造にしました！
複数人での管理は考えていなかったのですが（というか、その発想自体がなかったｗ）、仰る通り構造化しているため、改築するのも、複数人で追加＆メンテするのも楽かなと思います～。

更新したいのに人を介さなければならないのは時間のロスにも繋がりますから、**「おたよりをよみたい」は、複数人で気づいたものから追加＆メンテ**ということにしましょうか～。
＃イラストがまだ仮なので、完成したら差し替えます～

> 些細なことですが、ブラウザバックが微妙に面倒に思えましたので、場合によっては共通インポートを利用して各ページから［トップへ戻る］のリンクボタンがあっても良いのかなと思いました～

ご助言ありがとうございます！
私もちょっと面倒かなと思いつつも、シンプル構造優先でブラウザバックのままとしていましたが、やっぱりリンクがあった方が便利ですよね～。
トップページ（Scene 0）へのリンクのみ共通インポートを利用し、あとは項目毎にリンクボタンを追加しました！（GitHub版更新済みです）
https://snext1220.github.io/stext/index.html?id=letter

そこでちょっと感じたことなのですが、**Playground Flowからでも「exclude属性」が追加できたら便利かな、と思いました！**
（実は追加できるようでしたらすみません；；　今回はPg Flowからの追加方法が分からず、一旦scenario.xmlに変換してから手動でScene 0のみexclude属性を追加しました）

**Comment by snext1220** [comment]
> ここのところ一気にアップデートしていましたもんね～。いつもお疲れ様です…！！

ありがとうございます～
ご指摘も段々と細部に踏み込んで戴いており、完成度の高まりを実感しています。議論が必要なものも多く恐縮ですが、引き続きよろしくお願いいたします！

> 複数人で気づいたものから追加＆メンテということにしましょうか～

了解です！では、ときのじさんが画像修正、ドラモードのFAQ反映（ありますでしょうか？）など、一通り終えられたところで、こちらでも気づいたものを追加していきますね。
＃ TLでの告知はときのじさん作業が完了したところで？

@cocotori さん＞幕末でも発生してきそうですが、FAQ的なものがあれば適宜追加お願いいたします～

> そこでちょっと感じたことなのですが、Playground Flowからでも「exclude属性」が追加できたら便利かな、と思いました！

共通インポートのご対応もありがとうございます！
こちらは恐縮ですが、現時点で未対応でございます；
#191 でもまとめておりますが、システムとPgFlowのリアルタイム同期が難しくなっているため（新機能は特に、リリース直後に仕様変更が発生しやすいため）、時間差更新に移行しておりました；お手間をおかけして恐縮ですが、暫しお待ちくださいませm(_ _)m

> 「アンダーバー」付きのURLは、GitHub、XAMPP環境だと下記のような警告が出てしまいました；

ご指摘ありがとうございます！
こちらは以前からの問題ですね...ドラモードでも画像ファイル名で問題が出ていましたが（[wiki](https://github.com/snext1220/stext/wiki/%E9%80%A3%E4%BD%9C%E3%80%8C%E3%83%89%E3%83%A9%E3%82%B4%E3%83%B3%E3%83%A2%E3%83%BC%E3%83%89%E3%80%8D%E8%A9%B3%E7%B4%B0%E6%83%85%E5%A0%B1#8%E3%82%B7%E3%83%8A%E3%83%AA%E3%82%AA%E3%81%AE%E4%BF%AE%E6%AD%A3%E3%81%A8%E8%AA%BF%E6%95%B4%E5%85%AC%E9%96%8B%E5%89%8D%E6%BA%96%E5%82%99%E3%81%AE%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E9%A0%85%E7%9B%AE)）、アンダースコアはmarkdownの予約文字のため、内部的に<em>のようなタグに変換された結果、生じております。。
ただ、画像ファイルと違って、リンクは回避できないため、なにかしら対応しないとですね…少々特殊な処理が必要になりそうなので、暫しお待ちくださいませ；（場合によっては恐縮ですが、問題改善まで一旦コメントアウト戴いた方が良いかもしれません。。スミマセン）

**Comment by toki-sor1** [comment]
> 共通インポートのご対応もありがとうございます！
こちらは恐縮ですが、現時点で未対応でございます；
#191 でもまとめておりますが、システムとPgFlowのリアルタイム同期が難しくなっているため（新機能は特に、リリース直後に仕様変更が発生しやすいため）、時間差更新に移行しておりました；お手間をおかけして恐縮ですが、暫しお待ちくださいませm(_ _)m

早速の実装ありがとうございます！！
お返事が一部のみとなってしまい恐縮ですが、Win 8.1／Chrome 84.0.4147.125(64bit)にて動作確認を行いました。
「共通インポートの無効化」にチェックを入れたシーンでは、正常に共通インポートが無効化されていました！
これは設定も楽ですし、便利ですね！

ただ、一点だけ気になったことがあります。
例えば、Scene 0の「共通インポートの無効化」にチェックをした後、Scene 1のシーンタブを開くと、そのままチェックが入っている状態になっていました。

その場合、Scene 1のシーンタブのチェックを外すと無効化を解除できます。
しかし、その状態のままScene 0のシーンタブを開くと「Scene 0のシーンタブのチェックが外れた状態になりつつも、テストプレイでは無効化されている状態」 になっているのです；

これだと、シーンタブを開いた時にどのSceneにチェックを入れて、どのSceneでチェックを入れてないのか編集中に混乱してしまうのではと思いました。

**Comment by snext1220** [comment]
早速のご確認ありがとうございます～
ご指摘の件も大変失礼いたしました。
シーンタブの初期化が正しくされていないための問題でした。
改めて修正しておりますので、ご確認くださいませm(_ _)m

**Comment by toki-sor1** [comment]
迅速なご対応ありがとうございます～！
**上記と同じ環境で動作確認を行い、正常にシーンタブが初期化されていることを確認しました！**
修正お疲れ様でした！

**Comment by Salvadors-cabin** [comment]
Win10+Edge環境でシーンタブが切り替え時に初期化さていることを確認しました。

**Comment by snext1220** [comment]
ご確認ありがとうございました。

>了解です！では、ときのじさんが画像修正、ドラモードのFAQ反映（ありますでしょうか？）など、一通り終えられたところで、こちらでも気づいたものを追加していきますね。 ＃ TLでの告知はときのじさん作業が完了したところで？

こちら如何いたしましょうか。
顔画像共々、近いうちに告知も進めていければと思っております～
勿論急ぎではありませんが^^;、引き続きよろしくお願いいたしますm(_ _)m

**Comment by toki-sor1** [comment]
### おたよりをよみたい
https://snext1220.github.io/stext/index.html?id=letter
完成したイラストと差替え＋intro.png追加＋scenario.xml更新しました（GitHubのみアップ済み）。

> 了解です！では、ときのじさんが画像修正、ドラモードのFAQ反映（ありますでしょうか？）など、一通り終えられたところで、こちらでも気づいたものを追加していきますね。 ＃ TLでの告知はときのじさん作業が完了したところで？

ドラモードのFAQですが、実績によるシナ解除は少々特殊なケースのため、今回は追加を見送っております；
その代わりに、以前問題が出ていたファイル名の注意点をについて追加しております。
（その他にドラモード関連のFAQで必要そうなものってありましたっけ？）

> 顔画像共々、近いうちに告知も進めていければと思っております～
勿論急ぎではありませんが^^;、引き続きよろしくお願いいたしますm(_ _)m

内容等に問題がなさそうでしたら、顔画像と同時期に告知も可能です。
以下は、シナリオ紹介文です。
***
Util 7 STextのFAQコーナー「おたよりをよみたい」（作・ときのじ）

この「おたよりをよみたい」というコーナーは、ソーサリアン達が皆様のお便りを紹介するという体で「ソーサリアンText」の疑問やトラブル解決方法を随時紹介してゆくというものです。
もし「ソーサリアンText」のことで分からないことがあったら、このコーナーも参考にしてみるのも良いでしょう。

それでは、ソーサリアン達と一緒に疑問やトラブルをぱぱっと解決しちゃいましょう！

**Comment by snext1220** [comment]
仕上げの作業お疲れ様です！

> その他にドラモード関連のFAQで必要そうなものってありましたっけ？

主に、実績によるシナ解除を想定しておりました。
特殊ではありますが、次回の幕末でも発生する機能なので、入れておいた方が良いかなぁと^^;
あとは、＜![CDATA[」と「]]＞」でしょうか（非PgFlowの場合ですが、前回も結構話題に上ったところだったので；）。

ただ、細かくは今後修正していければ良いと思いますので、他の皆さまの方でも問題ありませんでしたら、リリース＆告知進めてまいりますね。
＃ PgFlow系もマニュアルを現在更新中なので、もしこちらに入れるのがふさわしい話題があれば加えさせていただきます～

**Comment by snext1220** [comment]
便乗のようで恐縮ですが、PgFlowマニュアルも現況に合わせて修正済みです。
https://sorcerian.hateblo.jp/entry/2019/05/03/211951
最小限ながら一応必要なものは載せたつもりですが、如何でしょうか。

また、「おたより～」に加えた方が良いような内容があれば（現在マニュアルにあるものないもの問わず）、ご指摘いただければ幸いです。

**Comment by toki-sor1** [comment]
### おたよりをよみたい
https://snext1220.github.io/stext/index.html?id=letter
scenario.xml更新しました（GitHubのみアップ済み）。

- 最新の「おたより」jsonファイル
[letter-stext 20200908.zip](https://github.com/snext1220/stext/files/5183869/letter-stext.20200908.zip)

ドラモード関連のFAQについてご助言ありがとうございました！
そうですね、今後のことも考えてシナ解除関連もまとめておいた方がいいですよね。
本日の更新でシナ解除について説明しているシーンを追加しました。

ただ、Playgroundの仕様上、「＜![CDATA[」と「]]＞」はどうにも上手く表示できなくて、wiki参照になってしまいましたが…；（上下をそれぞれ『`』×3で囲ってみたのですが、ゲーム画面では原文のまま表示されなくて；）

> ただ、細かくは今後修正していければ良いと思いますので、他の皆さまの方でも問題ありませんでしたら、リリース＆告知進めてまいりますね。
＃ PgFlow系もマニュアルを現在更新中なので、もしこちらに入れるのがふさわしい話題があれば加えさせていただきます～

こちら、承知しました！
今回の更新内容に問題がなければ、よろしくお願いいたします！（加える話題についても承知しました～）

> 便乗のようで恐縮ですが、PgFlowマニュアルも現況に合わせて修正済みです。

マニュアル更新お疲れ様です！
画像を交えて非常に細やか且つ丁寧に説明されているので、内容がとても分かりやすかったです！

拝読していて、新たに加えた方が良さそうと感じた内容は、今のところ特になかったですね。
もし皆さんの方で「これはあった方がいいかな！」というものについては、追加をお願いいたします～。

**Comment by snext1220** [comment]
シナ解除について、早速ありがとうございます！
ただ、スミマセン、`<![CDATA[～]]>`については、シナ解除限定のお話というよりも新条件式に関わるお話なので、別建てで扱って戴いた方が良いかもしれません（宜しければ、私の方で別途修正いたしましょうか？）

> ただ、Playgroundの仕様上、「＜![CDATA[」と「]]＞」はどうにも上手く表示できなくて、

`<![CDATA～]]>`については半角にするとうまく表示されない、という意味でしょうか？いくつか回避方法はありますが、現状全角にしていただいているので、これはこれでありかなぁと思いましたもので^^;

> マニュアル更新お疲れ様です！

こちらもご確認ありがとうございます！
若干長くなっておりますため、小技βについては将来別ページに移動させるかも、ですが、他の皆さまのご意見も待って確定してまいりますね。

ということで、皆さま＞おたより、マニュアル含めて、ご確認のほどをお願いいたしますm(_ _)m

**Comment by toki-sor1** [comment]
早速ご確認いただきありがとうございます！

> シナ解除について、早速ありがとうございます！
ただ、スミマセン、<![CDATA[～]]>については、シナ解除限定のお話というよりも新条件式に関わるお話なので、別建てで扱って戴いた方が良いかもしれません（宜しければ、私の方で別途修正いたしましょうか？）

承知しました、こちらは切り離して別のシーンとしてまとめたいと思います～。
しかし、まとめるには少々問題がございます；

> <![CDATA～]]>については半角にするとうまく表示されない、という意味でしょうか？いくつか回避方法はありますが、現状全角にしていただいているので、これはこれでありかなぁと思いましたもので^^;

＜![CDATA[」と「]]＞については、全角にするなどして表示させることが可能なのですが、設定例をコピペできると便利なので、**ゲーム画面上でも原文のまま表示させたい**と思っています。

しかし、原文の上下をそれぞれ『`』×3で囲っていても、**テストプレイでゲーム画面に表示させると、設定が適用された状態で表示されてしまうため、ゲーム画面上でコピーして、テキストエディタにペーストということができません；
（if構文を使用している設定例も同様で、実績未所持の場合に表示されない文章が上記の処理をしていても見えなくなってしまいます；）**
＃そのため、wikiを参照してくださいと書いておりました；

何とか原文のままゲーム画面に表示させて、コピペできるようにすることはできますでしょうか？
もし可能でしたら、お手数をおかけしますがお手隙の際にご教示くださいませ；

**Comment by snext1220** [comment]
ご検討ありがとうございます～

> ゲーム画面上でも原文のまま表示させたいと思っています。

以下のように表すことで可能かと思います。

```
&lt;![CDATA[
]]&gt;

$&#123;if condition}$&#123;/if}
```

一寸特殊な書き方にはなってしまうのですが、本件に限るならば、そのままコピペしてご利用いただけますとm(_ _)m
＃ CDATAの方は一行では書けませんので、ご容赦ください。

**Comment by toki-sor1** [comment]
### おたよりをよみたい
https://snext1220.github.io/stext/index.html?id=letter
scenario.xml更新しました（新構文についてシ－ン分離＆修正、GitHubのみアップ済み）。

- 最新の「おたより」jsonファイル
[letter-stext 20200910.zip](https://github.com/snext1220/stext/files/5196439/letter-stext.20200910.zip)

> 特殊な文字は、以下の数値参照10進数で置き換えるイメージです。

表記例と参照サイトのご紹介ありがとうございました！
こういう表記の仕方があるのですね～！　とても勉強になりました！！
めちゃくちゃ悩んでいた箇所だったのですが、リオさんの表記例をありがたくコピペさせていただき、他の箇所もサイト等を参考にして書いて無事に表示させることができました～！

ただ、新構文の説明など、もしかしたら解釈が間違っているかもしれません；
その場合は、お手数をおかけしますが訂正していただけますと助かりますです；；

**Comment by snext1220** [comment]
夜遅くまでお疲れ様です～

> こういう表記の仕方があるのですね～！

はい～この辺、ホントはSGMLの側で意識しなくても良いように、専用構文を用意するのが望ましいのですが^^;、恐らく利用の機会は少ないと思われることから、今回はこんな感じで。無事に表示できたようで良かったです～

> ただ、新構文の説明など、もしかしたら解釈が間違っているかもしれません；

内容問題ないと思います！
ただ、複合条件式という表現が、途中から新構文という表現で置き換わっているように見えましたので、前者で統一した方が良いかもしれません（細かくてスミマセン；）

**Comment by toki-sor1** [comment]
### おたよりをよみたい
https://snext1220.github.io/stext/index.html?id=letter
scenario.xml更新しました（新構文を複合条件式に統一、誤字脱字等の修正、GitHubのみアップ済み）。

- 最新の「おたより」jsonファイル
[letter-stext 20200910.zip](https://github.com/snext1220/stext/files/5201989/letter-stext.20200910.zip)

> はい～この辺、ホントはSGMLの側で意識しなくても良いように、専用構文を用意するのが望ましいのですが^^;、恐らく利用の機会は少ないと思われることから、今回はこんな感じで。無事に表示できたようで良かったです～

労いのお言葉＆ご確認ありがとうございます！
リオさんからご助言いただく前は、苦肉の策で画像化も…いやいや、コピペできないのは面倒だよな…と悩んでいたので、解決策を教えていただき本当に助かりました！
専用構文について、確かに通常のシナリオならば利用の機会は少ないと思いますので、このままでも良いと思います～。

> ただ、複合条件式という表現が、途中から新構文という表現で置き換わっているように見えましたので、前者で統一した方が良いかもしれません（細かくてスミマセン；）

いえいえ、私も途中でこんがらがっていたので、ご助言ありがたいです…！
表記（内容）を複合条件式に統一したことで分かりやすくなったと思います！

内容も問題ないようで安心しました～。
ただ、今回の修正でletterの**実績取得によるシナリオ解放の設定って？**と**マニュアルに出てくる複合条件式って何ですか？**の文章をいじっていますが、修正分の内容は大丈夫そうでしょうか？

**Comment by toki-sor1** [comment]
### おたよりをよみたい
https://snext1220.github.io/stext/index.html?id=letter
scenario.xml更新しました（!r01:zeroに修正、GitHubのみアップ済み）。

- 最新の「おたより」jsonファイル
[letter-stext 20200911.zip](https://github.com/snext1220/stext/files/5202816/letter-stext.20200911.zip)

あわー！　こちらこそ何度もすみません…！
こちら新構文に修正しました！
旧構文のところは、ご指摘いただくまで気付きませんでした…！　ありがとうございます…！！（wikiからコピペしたのが丸分かり感…wikiも修正します；）

顔グラについてもご意見ありがとうございました！
現在はあのページだけ顔グラ2つなのですが、まさにリオさんが仰っていた部分も気になっていたので、顔グラがアクセントになって良かったです！

![道場クリスティ](https://user-images.githubusercontent.com/42646342/92754497-dd972b00-f3c5-11ea-93da-d6c446b883b7.png)
＃実はこちらのアイコンも参照の辺り（ページ右下）に入れようかなと思ったのですが、そんなに画像を増やしてもアレかなぁとか、右寄せって難しいかなぁとボツにしていました～

**Comment by snext1220** [comment]
修正お疲れ様です＆ありがとうございます～
問題ないと思います！！

> そんなに画像を増やしてもアレかなぁ

確かに現時点では右寄せは難しいかもですね^^;
＃ 左に空白付きの画像を作れば無理やりできますが、画面幅が変わった時に問題になりそうですし...

とりあえず本件、他の皆さまの了承がとれましたら、正式公開＆告知してまいりますね。

#### 別件

旧道場、GBAT2STextなどはいよいよ古さ満載になってきましたが、扱いどうしましょうかね...

+ アーカイブ（非推奨）ページを設けて移動
+ ページはそのままに非推奨を明示
+ （一応使えないわけではないので）なにもしない

などの選択肢があるかと思いますが…お手すきの折にもご意見頂ければ幸いです～

**Comment by cocotori** [comment]
おたよりを読みたい、一通り確認させてもらいました。
概要説明、遊び方、作り方、投稿までの
一連の流れが網羅されていて素晴らしいと思います！

構文や投稿方法も最新のものになっていますので、
混乱を招かないように旧道場等は
アーカイブページに移せるといいなと思いました。

**Comment by snext1220** [comment]
ご確認ありがとうございます！

アーカイブページ＞こちらは開発者向けページのコンテンツも増えてきたので、暫定的ながらアーカイブページを設けて、道場、GBATを移動いたしました～

**Comment by toki-sor1** [comment]
反応が遅くなり申し訳ありません…！
「おたより」のご確認＆お褒めのお言葉ありがとうございました！
なるべく硬くなりすぎず、気を楽にして読めるものを目指したので、ご感想とても嬉しいです！

道場＆GBATについては既にアーカイブページへの移動が完了していますが、私もこちらに関しては異論ありませんです～。
移動していただき、ありがとうございました！

**Comment by snext1220** [comment]
アーカイブへの移動もご賛同ありがとうございました！
おかげさまで「おたより」も問題なさそうなので、週明け10/5 夜間にも王さま垢から告知してまいりますね（本当にお疲れさまでした！）。
もし告知文のご要望などありましたら、Twitter グループＤなどからなんなりとお寄せくださいませm(_ _)m
