### ISSUE TITLE
Playgroundへのチュートリアル追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#77]
#72 で @toki-sor1 さんのご意見を受けてのIssueです。

> 内容が弱い ⇒ 先日リオさんが実装してくださったチュートリアルによりクリアできていると思います（これ以上の内容を入れると、かえって分かり辛くなってしまう）。

こちら、Ｄでもご意見戴いていますが、現在の「基本のキ」の他、以下のようなものを追加し、全4～5回程度のチュートリアル集にまとめようと思っています（統合、分離の可能性はあり）。

+ Markdown（第1回に統合？）
+ 戦闘
+ フラグ
+ アイテム
+ bgm設定
+ 付録：サンプルテンプレート（既存のものあり）

> これ以上の内容を入れると～～

こちらはサンプルテンプレートへのご意見になりますでしょうか？
@cocotori さんから「構文を知らなくてもちょこっといじるだけでシナリオができる形になっているので、このあたりを拡充できるといい感じ」のようなご意見も戴いていましたので、最終的にどの程度の規模にしようか、一寸修正悩んでおります。
＃山田さんからは20scene規模の、というご要望もあり、微妙に皆さんのイメージに差があるのかも；

私個人的には、あまり大きくせずに現状＋せいぜい数シーン程度でまとめていければとは。
拡張については、「この辺のテーマくらいは入れてもいいのでは？」があれば、是非お願いします＞ @cocotori さん＆皆さま

チュートリアルについてのご意見の場合で、もし「基本のキ」以上を扱うのはオーバースペックというご意見なのかとも、これまた一寸悩んでしまったので^^;、恐縮ですが、今一度お教え戴ければと＞ @toki-sor1 さん

**Comment by cocotori** [comment]
わたしの感覚での話になりますが。

イメージは、中身はスカスカだけど
エンドまで一通り書いてある、
（チュートリアルと言うよりは）サンプルシナリオ
というような感じでいます。

シナリオ作者は、それをいじってアレンジするだけ。
シーン数も追加しない。
（実際にはそんな単純には行かないでしょうが）
あるものの中から、ちょこちょことアレンジしてもらって、
オリジナルのシナリオを作ってもらう。
そして、慣れてきてそれじゃ物足りなくなってきたら、
改めて構文を勉強してもらう。

というような感覚でいますので、
シーン数は、山田さんのいうように20scene規模というのも
だいたいイメージ通りです。

使用する構文については、
構文の勉強というよりはとにかく最後まで
シナリオを終えられる、ということを意識するのであれば、
選択肢と分岐、戦闘程度でいいのかもしれません。


実際に作るとなるとかなり大変かと思うので、
ひとまず、現状のもので試してもらってもいいのでは、とも思います。

**Comment by snext1220** [comment]
> （チュートリアルと言うよりは）サンプルシナリオ

はい、私も同じイメージです！
＃ というか、私の最初の書き方が悪くて、チュートとサンプルが混在した伺いになってしまって、すみません；

改めて話題を分けますね。

### サンプルシナについて

上記の通り、スタンスとしては @cocotori さんと同意見です。
ただ、こちらはどこまでの機能を盛り込むかで悩んでいました。
フラグやアイテムなどを入れて＆Scene数を増やすと、見通しも悪化するという意味で。

そうした意味では、以下の割り切りはスッキリしますね！
まずは、以下のスタンスで枠だけのシナリオを作成してみたいと思います。

> 選択肢と分岐、戦闘程度でいいのかもしれません。

＃となると、従来のサンプルはサンプルで、フラグやアイテムを使った例として残しても良いのかもしれませんね。

### チュートについて

こちらは構文学習目的なので、「基本のキ」から前投稿のように、
フラグ、アイテム、戦闘...と、ほとんどのシナで利用している基本機能
までは解説する、というつもりでおります。

如何なものでしょうか？？

**Comment by snext1220** [comment]
とりあえずPlaygroundに「N.試作用サンプル」としてUpしております。
まずは機械的に作成しているだけなので、「もっとこんな感じに」など、ご意見戴ければ幸いです。

**Comment by cocotori** [comment]
いい感じだと思います！ありがとうございます。

**Comment by snext1220** [comment]
本件、PgFlowの進化によって必要度合いが低くなっていると思われ、問題なければ現在のもので一旦凍結＆PgFlowに注力していこうと考えていますが、如何でしょうか。問題なければwontfix＆Closeとしてまいります。

**Comment by cocotori** [comment]
そうですね、いいと思います。

例えば外部の方に使って頂いたときに、
わかりにくい、どうしたらいいかわかりにくいなどの声が上がったら
改めて検討する・・・といった形がいいのかなと思います。
