### ISSUE TITLE
マニュアルの導線強化

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#78]
#72 で @toki-sor1 さんのご意見を受けてIssueを分離しています。

> しかし、分量が嵩んでいるのも事実で、シナリオ執筆初挑戦という執筆者様にとっては、「どこを見ればよいのか分からない」「分量に圧倒される」という状態になってしまっているのでは、と考えます。
> 初学者への最初に見るべきものを強化するという意味では、STextページでももっと目立つようにリンクのフォントを大きくする、「ソーサリアンTextとは！？」から分離させて「初めてシナリオ執筆に挑戦する勇者必見！（仮）」のタイトルで一項目設けるなど、チュートリアル・道場などへ誘導する工夫が必要かもしれません。

上記件、STextページが既に縦長になり、シナリオに行きつくまでにスクロールが嵩んでしまっているので（そもそもサイトを何とかしたいｗ）、マニュアル側で見せ方を対応できればと。
具体的には、開発マニュアルのトップページ（https://sorcerian.hateblo.jp/entries/2017/12/21 ）の見出し組を修正して、いわゆる「初めてシナリオ執筆に～」を追加できればと。
如何でしょうか。

**Comment by snext1220** [comment]
ご意見頂きありがとうございます！

> マニュアルの内容量はもう十分～

同感です。
というか、既に多すぎるという感じでｗ、不要なドキュメントはどんどん削除（or 見た目を小さく）していかねば、と思います。

恐らく、シナリオ開発リファレンスあたりは仕様変更で増え続けると思いますし、今後はページを増やすとしても、こうした大きくなりすぎたドキュメントの分離が中心になっていくのかなと。

以下、開発者向けマニュアル（ https://sorcerian.hateblo.jp/entries/2017/12/21 ）の再構成案です。この叩き台で皆さんにご意見戴いた後、再編を進めていければと思います。
＃Playgroundチュートリアルはまだ不完全なので、そちらが優先になるとは思いますが^^;

---

# 初めての開発者へ

## テキストエディターで執筆したい人

+ Playground（チュートリアル）

## GBATで始めたい人

+ ソーサリアン Text開発道場
@cocotori さん仰るように、チュートと道場はマニュアルとは別ものなので＆初心者向けの二本柱なので、トップに移動しました。GBATとPlayground（生）いずれをよりアピールするかは悩ましいところなのですが…
＃ 入り口が大きくふたつあるのも紹介しにくくなっている原因なのですよね…GBATのエディター機能がもっとリッチであれば（ry

# より詳しい仕様を知りたくなったら

+ マニュアル（シナリオ開発リファレンス）
+ マニュアル（GBAT to SText編）
+ マニュアル（環境準備編）

@cocotori さん＞環境準備編も当初から随分変化して、Playgroundメインの解説になっており。一旦、後ろに下げてしまいましたが、実は、Playgroundだけを切り離して「初めての開発者へ」に移動した方が良いでしょうか（チュートだけでもそれなりいけるかな、と悩み中です^^;）

# 開発を極めたい人のために

+ マニュアル（テクニック集）

# 更新履歴

# 過去ドキュメント

---

**Comment by Salvadors-cabin** [comment]
私もマニュアルは十分と思います。活用させてもらってます！

**Comment by snext1220** [comment]
ご活用いただき、ありがとうございます～
はい、マニュアルについては分量は足りてそうなので、あとは見せ方ですね。
以下で新しいメニュー構造もまとめておりますので、ご意見いただければ幸いです。
https://github.com/snext1220/stext/issues/78#issuecomment-451617493

**Comment by cocotori** [comment]
新メニュー構成、ありがとうございます！
いい感じだと思います。

開発環境の準備については、どんなものでしょうね。
個人的には、このまま後ろに下げてもいいのかなと思っています。
環境の準備、非常に丁寧ではあるのですけど、
わたしのようにまずツールに触れて覚えたい、みたいな人からすると
あまり説明が最初にあるととっつきにくいと思ったので。

このあたりは感覚の違いあるかと思いますので、一意見と思ってもらえれば。

**Comment by snext1220** [comment]
構成ご確認ありがとうございます！

このまま後ろ＞了解です～一部ちょっと使いどころがわかりにくい機能があるかなと心配したのですが、新たにTIPS機能を設けたので、これで緩くはフォローできるかもしれませんね(?)

他の方のご意見もお待ちしながらになるかと思いますが、まずは現在の新メニュー構成を前提に考えたいと思います！（なんにせよ、再編はチュートが一通り完成してからになるかと思うので^^;）

**Comment by snext1220** [comment]
前回の議論からかなり時間が経過してしまい、New Playgroundも本格的にリリースされましたので、その前提で開発者マニュアルを再構成してみました。
https://sorcerian.hateblo.jp/entries/2017/12/21

伴い、NewPgはPlayground Flow、旧PgはPlayground Textと命名しておりますが、如何なものでしょうか。これからプレグラ100、幕末で本格的に作者募集していくにあたって、「これを見て」と言えるような環境を用意しておければと思いますので、なんなりとご意見頂戴できますと幸いです。

**Comment by cocotori** [comment]
新しい機能にも対応して、だいぶスッキリしていて
よいのではないかと思います。

一番押してほしいであろうマニュアルへのリンクテキストが、
他の文章と同じサイズでやや目立たない印象がありますね・・・
リンクで色が違うので一応わかりはするのですが。
もう少し、大げさに目立つ形にしてもいいのかもしれません。
（Playground Flowマニュアルとか）

それか、STextサイトのPostのページのように、リンクは予め列挙してから、
後で説明するとか。
（https://www.web-deli.com/sorcerian/text/post.aspx）

あと、シナリオ執筆の流れは
図があってわかりやすいのですが、
GBAT、GitHub等の情報は要りますかね・・・？

個人的にはGBATはもう封印でいいのではないかと思っています。
もちろん使うのを禁止するつもりはありませんが、
使うのは自己判断でやってね、という意味でも
画像からは消してしまってのもいいのではと思っています。

GitHubについても、
わたしたちは存分に活用しながら運営していますが、
シナリオ投稿者さんが利用するかというと
かなりハードルが高いのではないかと思います。

なぜこんな意見をいうかというと、
使う頻度の低い固有名詞を可能な限り
マニュアルなどから省きたい、という思いがあるからです。
SText企画は結構に耳慣れない単語が多く、
初心者の方はまずその情報量に圧倒されてしまうのではないか
という恐れを抱いています。

これは用語の統合/整理のところでも
議論させてもらおうと思っています。

**Comment by snext1220** [comment]
ご意見ありがとうございます！

> もう少し、大げさに目立つ形にしてもいいのかもしれません。

こちらブログ標準の記法（markdown）だけだと表現に限界があったので、HTMLを入れ込み、STextサイトと似た雰囲気のボタンにしてみました。如何でしょうか。
とりあえずFlowマニュアルの箇所だけ書き換えてみましたが、これで問題なければ、本ページの主要なリンクは同様に置き換えたいと思います。

> SText企画は結構に耳慣れない単語が多く、～～

まさにこれですよね；
当初機能を急速に乱造したのも原因ですし、仰る通り、用語の整理（削減）が急務だと思います！

> GBAT、GitHub等の情報は要りますかね・・・？

これについては、私も悩んでいました。
Flowリリース時にPPTを最低限しか修正しなかった、という手抜きな理由もあるのですがｗ、それ以外に以下の理由から消してしまってよいのかと；

+ Flow投稿の機能は8MB制限なので、より大きなシナの受け口を確保する必要がある（実際、その制限を超えているシナは結構あり）。
+ Flow投稿がリリースしたてで問題の有無が不明なので、正常動作しない場合の安全弁が必要
+ GBATがゲームブック界でそれなりに有名なので、そこからの流入を見込めないか、という若干の期待

まずは初見の人のハードルを下げるという意味では、いずれも割り切りか、とは思っているのですが（たとえば容量ひとつとっても近頃が全体として膨らみ過ぎているので、8MBで普通は十分）、この辺もう少しだけ皆さまのご意見を伺って方針を決めていければ良いなと思っています～

おそらくこの辺は、［Post］ページの修正とも絡んでくると思うので、引き続きどうぞよろしくお願いいたします！

**Comment by toki-sor1** [comment]
> とりあえずFlowマニュアルの箇所だけ書き換えてみましたが、これで問題なければ、本ページの主要なリンクは同様に置き換えたいと思います。

図も入り、分かり易くなって良いと思います～。
ただ、一点気になるところを挙げるとすると、 **全体的に文字がぎっちりと詰まっていて、項目の区切りが分かり辛いところでしょうか。**
項目の区切りにもう少し行間を空ける or 区切り線を入れる、などすると読み易くなるのでは、と思いました。

> GBATの表示

現在では、GBATによるシナリオ執筆はほぼサポート対象外となっているので、目次の図からはGBATを削除した方が見易くなるかなとは思います。
ただ、GBATを使用してSTextにご参加いただいた執筆者様もいらっしゃること、また、今後のGBATからの流入を考えた場合、どこかにGBATの表示があった方が良さそうな感じがします。

中間の意見ですが、図からはGBATを削除して、「2.Playground Editor（Playground）」の下辺りに「GBATで作成したファイルをインポートする機能も搭載」と表記するのはどうでしょう？

> GitHubの表示

図の中に、投稿方法が何故2つ用意されてるのかの説明を入れると良いような感じがします。
例えば、「作品の容量が8MB以下なら（8MB以上なら）」とか表記されていると、「あ、なるほどね」とご納得いただけると思いますので。

＃初回投稿から8MB超えはあまりなさそうなので、GitHubの表示は大体が「こういう投稿方法もあるよ」と伝えるためのものになりそうですが、postページに飛んでから投稿方法が2つ表示されているよりも、図で予め表示されている方が親切かなと。

**Comment by snext1220** [comment]
ご確認有難うございます！

> 全体的に文字がぎっちりと詰まっていて、項目の区切りが分かり辛いところでしょうか。

そうなんですよね...この辺、実はゲームブック風に「初心者の人は...」「慣れてきたら...」などとゲームブック風にリンク＆ページ分割しようと思ったのですが、却ってウザイかなと一ページにしていました^^;

とりあえずタイトルレベルを一部上げて、途中に区切り線をいれるなどしてみましたが、如何でしょうか？
＃その際、リンクボタンもまとめて反映しました。

> 目次の図からはGBATを削除した方が見易くなるかなとは思います。
> 図の中に、投稿方法が何故2つ用意されてるのかの説明を入れると良いような～～～

こちらもまずは取り急ぎ図を反映してみましたが、如何でしょうか。
とりあえず現在の最新（あるべき）にはなったかと。
初見はスッキリさせるべきというcocoさんのご意見もまさになので、今後のFlowの安定性を見ながら、GitHubを削除するかどうかはご相談にて。

＃実は、Flowからも複数回に分ければ8Mbを越えての投稿も許容できるのですが、専らセキュリティ上の問題で（認証もしていないので）現在はガードしています。この辺も様子見ながら。

> どこかにGBATの表示があった方が良さそうな感じがします。

こちらは悩んだのですが、現状NoteにGBATの表記があるので、そこのみ残すで割り切ってみました（ホント、できればいろいろ拾いたいという欲が出てしまうので、悩ましいです...）

**Comment by toki-sor1** [comment]
早速のご対応ありがとうございます～。

> 全体的に文字がぎっちりと詰まっていて、項目の区切りが分かり辛いところでしょうか。

> そうなんですよね...ただ、これ以上文字数を少なくするのも辛そうなので～

ああっ、言葉足らずで申し訳ありません…！（汗）
文字数の多さ＝文字数を少なくしてほしい、という意図の発言ではなく、項目ごとにもう少し隙間があった方が、メリハリがついて目が滑りにくいかなと思っての発言でした；（ゲームブック風などもご検討いただき、ありがとうございました！）

> とりあえずタイトルレベルを一部上げて、途中に区切り線をいれるなどしてみましたが、如何でしょうか？

はい！　とても見易くなって良いと思います！
ただ、「これらのツールで開発に慣れてきたら…」の「▼」が、画面の横幅が狭いスマホなどの環境では、折り返されて表示が崩れていたので気になりました。

> こちらもまずは取り急ぎ図を反映してみましたが、如何でしょうか。

こちらも最新版の作成ありがとうございました！
しかし、私の方は初期の図の「GBAT」の部分を削除し、8MB制限の文字を追加というイメージだったので、とてもとても申し訳ないのですが、（主に視線誘導の関係で）最新版はちょっと見辛い感じがしてしまいました；

凄く雑な編集になってしまい大変恐縮ですが（大汗）、個人的には以下のような感じが見易いかなと思いました（しかし、私自身、こういう図の作成に関して、本来はどのようなルールがあるのか知らず、逆に見にくくなっていましたらすみません；）。

**【旧版を活かす場合】**
![postのコピー](https://user-images.githubusercontent.com/42646342/66264628-f2794f00-e843-11e9-96f2-5e328dd34c90.png)

**【最新版を活かす場合】**
![post (1)のコピー](https://user-images.githubusercontent.com/42646342/66264629-f2794f00-e843-11e9-9c64-d3c1cc5aac21.png)

> ＃実は、Flowからも複数回に分ければ8Mbを越えての投稿も許容できるのですが、専らセキュリティ上の問題で（認証もしていないので）現在はガードしています。この辺も様子見ながら。

なるほど、セキュリティ問題については、以前も投稿機能の件でも出ていましたもんね。
こちらは仰る通り、様子見で良いと思います～。

> こちらは悩んだのですが、現状NoteにGBATの表記があるので、そこのみ残すで割り切ってみました（ホント、できればいろいろ拾いたいという欲が出てしまうので、悩ましいです...）

こちら、丁度良いところに収まった感じで良いと思います！
本当に、色々と拾いたいものの、それを拾うと情報が多くなるなど、本当に悩ましいところですね；

**Comment by snext1220** [comment]
早速の、そして細部までのご確認戴き有難うございます！
凡そは問題ないようで良かった！一部はこちらが変に回り込みしすぎての曲解で申し訳ありませんでした！＆▼は修正済です～
あとは、図ですね...^^;

> しかし、私自身、こういう図の作成に関して、本来はどのようなルールがあるのか知らず

いえいえ、私も正直あまり得意な方ではないので^^;
とりあえず新版は

+ 他の環境からデータインポートできる点
+ Flowが作成～投稿にネイティブ対応している点

を表そうとしておりました。結果としてFlowの図を大きくしたことで、

+ FlowがSTextメインのツールである点もアピール

しようと考えておりました。Flowについては、上から下への流れがなくなったことで違和感を感じられているとは思うのですが、さて...；

あと、【最新版を活かす場合】ですが、こちらなにか変化していますでしょうか。
＃ 【旧版を活かす場合】との比較のために挙げて戴いたというだけの感じでしょうか（汗
判りが悪くて申し訳ありません...

なお、戴いたお返事に、で恐縮ですが、トップページの見直しが収束してきたところで、各細部のマニュアルも徐々に見直しております。が、Editorまわりが早速悩ましいですね...

+ SGMLの理解が前提
+ 道場はGBAT前提

となると、

+ 道場はGBATのNoteに移動。
+ 伴い、EditorではPlaygroundチュートリアル（テンプレート）を案内

とした方が良いのか。そもそも

+ エディターチュートリアルを先に持ってくるべき

なのか、などなど。
結構悩み始めています...

今更で申し訳ありませんが、引き続きご意見戴ければ幸いです；
＃ この辺、Dec Updateに持ち越しつつ、腰を据えた方が良いかもしれません^^;

**Comment by toki-sor1** [comment]
お返事＆▼の修正ありがとうございました！（修正箇所、確認済みです）

> 最新版の図

なるほど、そういう意図があったのですね！（汲み取れず申し訳ありません…！）
仰る通り、上から下への流れがなくなったことで違和感があったのですが、様々な意図を合わせると、最新版の方がより適しているように感じますね。

> あと、【最新版を活かす場合】ですが、こちらなにか変化していますでしょうか。

分かり辛い変更ですみません…！（大汗）
前レスにあった視線誘導の関係で、Playground Flowの表示位置が他のツール名よりも下にあることで見辛く感じたので、ツール名の位置を揃えていました；

そこだけ修正していただければ、ツール名が見易くなると思いますし、採用する図も最新版が良いかなと思います！（上のサンプルは切り貼りしてあるので、お手数ですが再編集をお願いしてしまうことになりますが；）

> トップページの見直しが収束してきたところで、各細部のマニュアルも徐々に見直しております。が、Editorまわりが早速悩ましいですね...

> 道場はGBATのNoteに移動。

こちらは良いと思います！

問題の「SGMLの理解が前提」の箇所についてですが、Editorとサクサク開発のところに、「シナリオ開発リファレンス」へのページ内移動リンク（？）を記載するのはどうでしょう？
同内容のリンクボタンをいくつも設置する必要がないので、見た目は割とスッキリしているかなとは思います～。

**Comment by snext1220** [comment]
お忙しいところ、早速のご確認ありがとうございます！

> なるほど、そういう意図があったのですね！（汲み取れず申し訳ありません…！）

いえいえ、意図が明確に伝わらないのは作り手の問題ですので（汗
こちらこそ、【最新版を活かす場合】を理解できておらず、失礼しました；
ご意見受けて、最新版維持を前提に、ご指摘の点修正しまして、再Up致しました～
今後諸々修正していく中で、また修正出てくるかもしれませんが、一旦はこれで確定とさせていただきますね（勿論、お気づきの点は引き続きご指摘お願いします！）

> 同内容のリンクボタンをいくつも設置する必要がないので、見た目は割とスッキリしているかなとは思います～。

ありがとうございます＆その方向で行ければと！
Editor対応については、他にも見直すべき点が多々あるため、 #140 として別Issueを立て、改めて修正等進めてまいりますね。

重ねてですが、ご意見ありがとうございました～
