### ISSUE TITLE
キャラの連続性（連作＆レベル）

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#79]
#72 を受けて、Issueを立ち上げています。
キャラを複数シナに跨って利用したいという要望を戴いています。

> 以前何処かで意見を出していたかもですが、各シナリオ（の実績初取得時）に経験値を設定し、引き継げ1る要素として「レベル」が導入できると面白いかなと思いました。
> レベルアップによる能力値補正は、正直バランスブレイカーかなと思うので、あくまでもプレイヤー自身のレベル（＝数々のシナリオをクリアした証）という感じなのですが。

上記、たぶん実績導入 or/and 初期機能のクリアボーナスに関連して出たお話でしたかね～
その際は、能力値補正はクリアボーナスと、証的な意味では実績と重複するということで、一旦見送りになった気がします。

改めてご提案戴いての亜案として、以下のようなものを考えてみました。

+ stext.xmlへの実績数の追加（取得集/実績数 で表示）
+ result要素へのclear属性追加（クリア実績のカウント） ※ただし、既存のセーブデータに対応できないので、その辺どうするかはノーアイデア^^;
+ 実績数によってプレイヤー称号を付与？

ご意見、またはほかのご意見あればお願いします～

> ただ、シナリオによっては種族等が限定されているものもあるため、全てのシナリオに反映するのは難しく、やはり連作等の限られたシナリオのみの適用になりそうですよね。
> 連作であれば、種族等は限定しないルールで引き継ぎし易くし、キャラの能力値が初シナリオクリアに強化されるというのも良さそうですよね（上記問題から、全シナリオ対応なら能力値のみ強化される、とか）。

はい、キャラ引継ぎについては、やるとしたら、以下のような感じになるかと思います。

### 前提

+ 種族制限のない（or統一された）連作でのみ可（システムとしてチェックはしない）
    + scenario要素にseries属性（シリーズid）を追加
+ その他、パラメーターのルールは統一（システムとしてチェックはしない）

### ルール

+ 新規のキャラ生成で＜シリーズキャラ＞が存在する場合は、そちらを引き継ぐ（存在しない場合のみ自動生成）
+ ＜シリーズキャラ＞はシリーズ1キャラのみ
    + 既存キャラを削除するための機能は、どこかで設ける必要あり（スタート画面？）
    + 実績と別管理なので、キャラを作り直した場合も実績は消えない（途中のシナから遊ぶことは可能→レベルアップ前提の構造になっていると、辛いかも）
+ キャラ強化のために同じシナリオを何度か遊んで、「レベルアップ」するのは許容する（原作と同じ）
+ パラメーター強化は連作機能というよりも、パラメーターの操作機能として、scene要素にstr、intなどの属性を追加しても良いかも

### 懸案

+ 修正規模は大きいので、具体的な連作企画を立ち上げてからの対応にした方が無難かもしれません。
+ 連作対応のために、他に機能は不要？（結局、連作としてどんな効果を狙いたいのかによって、機能が変化しそう）
+ シナの繋がりが強まるので、後のシナはアクセスが頭打ちになる惧れがあります

**Comment by cocotori** [comment]
キャラの連続性と言うと、Card Wirthのシステムがお手本になりますかね。

・キャラの新規作成時に、メイキング要素がある。
　→ 現状のランダム作成だと育てるモチベーションに繋がりにくいかも？
・パーティーを複数持って、切り替えられる。
　→ 限定シナリオに対応できそう

とかですかね・・・
相当な追加要素になるかと思うので、
実際にやる前にかなり検討が必要かと思います。
当初出たやりたい目的のプレイヤーのシナリオクリアの証、
という意味では
今の実績数がそれに代用できると思っています。

ただ、高難易度シナリオを用意して、
いくつものシナリオをクリアしてレベルを上げたもののみが
クリアできる、というのも面白そうではありますよね。
リオさん言われるように、
やるとしたら、まずレベルアップのモデルとする連作を用意して、
それを土台に考えるのがいいと思います。

**Comment by snext1220** [comment]
以下を受けての実装案です。
https://github.com/snext1220/snext-management/issues/13
> ただ、以前出ていたプレイヤーキャラを継続してシナリオで使用したい（snext1220/stext#79 ）等のストーリーに関係するシステム改定のことを考えると、連作テーマが決まりましたら、この辺りのことは早めに議論していきたいですね。

現時点では既存システムに影響の少ないキャラ引き継ぎは、前シナでのエンディング処理で次シナのセーブデータをコピー／生成するという実装になるかと思っています。
＃ 最終シーンで`next="scepter"`（杖へ続く）のような属性を追加するイメージ（次シナでのガードは実績分岐を利用するだけ）

もちろん、この場合、引継ぎは常に一方向で、（たとえば）連作の中で特定のシナを繰り返しクリアするようなことはできなくなります。

あとは、（当然ですが）このような実装の場合は、途中からのプレイはできなくなるので、後方のシナになるほど、アクセスは先細ります。ドラモードレベルでも相応に影響は出ている気がするので、その辺の検討は必要になりそうです。

**Comment by snext1220** [comment]
> ナビゲーターウィンドウ（仮）

こちらこそモロ反対意見になってしまい、すみませんでした；
以前にもちらっと話題に上ったのですが、現時点では、システム改定の判定基準として、緩く以下のような点を設けております（絶対ではありませんｗ）。

+ 既存機能で代替できるものは、そちらの活用、もしくは既存機能の強化で対応する（類似機能を極力避ける）
+ 既存機能でできるもの（ or 代替できるもの）のビジュアル化は慎重に行う

特にビジュアル化は、結局、ノベルゲー／コマンド式RPGへの進化になってしまうため、ゲームブックアプリとしては慎重に行っていきたいなと（見た目の強化は、しくみだけであれば、いくらでもできてしまうので猶更^^;）
勿論、そもそもノベルゲーに舵を取るという方針を決めた場合は、その限りではありませんし、この辺は必要に応じて、SText全体方針として議論させてください～

> ナビゲーター役

はい、こちらはメインストーリーがもう少し固まってきたところで、今一度ご相談させてください～

> システム改定
> そうですね～、可能であれば皆さんにご意見を伺うのも良いと思います～。

はい、特に本件は山田さん発案だったので、ご意見ありそうかもと。
当初話題に上った「成長」「連作」が、現在の議論とは別ものに見えたもので^^;、気になった次第でした。

> システム別案（ゲージ）

こちら、キャラの引継ぎ（コピー）で賄えそうに思えます。
https://github.com/snext1220/stext/issues/79#issuecomment-485803884

コピーについては、もしかしたら十分にお伝えしきれてないかもなので、補足なのですが、 **エンディング時にその時点でのステータス情報を次シナにコピー** という形になります。よって、シナリオ内でステータスを向上させた場合にはこれを引き継ぐこともできますし（勿論Freeも）、アイテムなども同様です。
＃どこまでをコピーの対象にするかは、既存Issueの通り、要相談ですが；

特定のシナで50ptまで、という制御は、（新機能になってしまいますが）Free欄に上限下限設定を設けるかですね...（自動化をどこまで強化するかだと思います）

あとは、コピー案では基本決められた順序でのクリアになるので（逃げはありそうですが、なんかしらの制限は出るかと；）、そこは要相談ですね～連作モデルをきちんと作成するという意味では、順序ありで割り切るのはなしではないとも思っています^^;
＃朝令暮改で恐縮ですが、アクセス数優先とするか、今後のモデルケースとして連作全体を一本のシナと割り切るかは決めの問題ではあるかと^^;

**Comment by snext1220** [comment]
以下のIssueコメントを受けて、成長システムの具体的な仕様について検討していければと思っています。引き続きのご意見をお願いいたします。
https://github.com/snext1220/snext-management/issues/13#issuecomment-509816814

## 基本仕様

+ `<scene>`要素にnext属性（次のシナリオコード）を追加
+ 指定されたシナリオコードで現在のセーブデータをコピー
+ 以下は、セーブデータの一覧（コピーしない項目が★）

```
├──chara …………………… キャラ情報
│　　├──title …………… 称号
│　　├──name  …………… 名前
│　　├──race  …………… 種族
│　　├──sex ……………… 性別
│　　├──age ……………… 年齢帯（YOUNG／ADULT／OLD）
│　　├──job ……………… 職業
│　　├──state …………… 状態異常★
│　　├──stone_scene …… 石化の経過シーン数★
│　　├──forget_scene  … 忘却の経過シーン数★
│　　├──hp_m  …………… HP上限
│　　├──hp  ……………… HP現在値 
│　　├──mp_m  …………… MP上限
│　　├──mp  ……………… MP現在値
│　　├──str_i …………… 強さ初期値（0～10）
│　　├──str ……………… 強さ現在値（0～10）
│　　├──int_i …………… 賢さ初期値（0～10）
│　　├──int ……………… 賢さ現在値（0～10）
│　　├──dex_i …………… 器用さ初期値（0～10）
│　　├──dex ……………… 器用さ現在値（0～10）
│　　├──krm_i …………… 魅力初期値（0～10）
│　　├──krm ……………… 魅力現在値（0～10）
│　　├──free1 …………… 自由ステータス1★
│　　├──free2 …………… 自由ステータス2★
│　　└──free3 …………… 自由ステータス3★
├──stars …………………… 所持している七惑星の欠片（月～太陽の個数を配列で）
├──items …………………… 所持しているアイテム（配列）★
├──flags …………………… 所持しているフラグ（配列）★
├──memos …………………… 冒険メモ（自由入力欄）
├──scene …………………… 現在のシーン★
├──ellapsed_scene  ……… 経過したシーン数★
├──bgm ……………………… 現在再生中のBGM（空文字列はメインテーマ）★
├──bonus …………………… 現在のシナリオで適用されるボーナス
└──isEnded ………………… エンディングに到達しているか★
```

## 課題

+ next属性で複数シナリオの指定も可能とするか
    + 任意順序のクリアに対応する場合は必須
+ freeN欄のコピーは不要でよいか
    + 武器ステータスをここで管理する場合は必要
    + コピーしておいて、各シナリオで明示的に初期化する方法はあり
+ items欄は、`<item>`要素でshared属性を付与したものだけをコピーの対象とする
+ state（状態異常）はコピーしないで良い？

その他、これはコピーしてほしい、というものがあればお願いします。

**Comment by cocotori** [comment]
具体的な仕様の案、ありがとうございます！
助かります。

それぞれの課題についてですが、

・next属性で複数シナリオの指定も可能とするか
複数シナリオ指定は可能にしたいと思っています。
やはり強制シナリオ順固定となると、
各シナリオの門戸を狭めてしまうように思うので・・・


・freeN欄のコピーは不要でよいか
ないほうが、各シナリオでfreeを自由に使えて、
自由度があがると思います。

武器にfreeを使用する場合は悩ましいですが、
引き継ぎ武器にはfree使用禁止にするくらいが
管理しやすいのではないでしょうか。


・items欄は、<item>要素でshared属性を付与したものだけをコピーの対象とする
いいと思います！


・state（状態異常）はコピーしないで良い？
なしでいいのでは、と思います。
石化の経過シーン数をコピーしておいて、
タイムアタック的な挑戦をするというのも面白そうではありますが。

それよりも、前のクリア時の毒なり忘却なりが残っていることによる、
煩わしさを与えるデメリットの方が大きいように思います。

**Comment by snext1220** [comment]
@cocotori さん：

反応有難うございます！
こちら、まずはご意見のままにnexts／shared属性をシステムに組み込んでみました。
GitHubのみ有効＆マニュアル反映済みです～

＃細かな仕様はまだ変更可能なので、ご意見引き続きお願いします！

**Comment by toki-sor1** [comment]
> こちら、まずはご意見のままにnexts／shared属性をシステムに組み込んでみました。
GitHubのみ有効＆マニュアル反映済みです～

- 動作確認環境：Win 8.1／Chrome 76.0.3809.87(64bit)

Testingが付与されていたのでGitHub(XAMPP）でテストしようと思い、Playgroundのscenario.xmlを改変して試していたのですが、対象のシナリオ2つに同idのshared属性指定アイテムをコピーしようと、コピー先の指定を「nexts="king"」としたところ、「終末」にはコピーされていませんでした。

私の指定の仕方が間違っている可能性が大いにありますが、もし「まだコピーできる段階じゃないよ！」という場合は、早とちりすみません；；

**Comment by snext1220** [comment]
テスト有難うございます！
とりあえずGitHub Pagesでは利用できる状態にはなっているはずですが（汗
お手数ですが、うまく動作しないscenario.xmlをUp戴いても宜しいでしょうか？

**Comment by toki-sor1** [comment]
ううっ、お手数をお掛けしてしまい申し訳ありません；；
O/Dにtest（Playground内のものを改変）とkingのscenario.xmlをアップしました～。
https://onedrive.live.com/?id=4837C202555BE782%219612&cid=4837C202555BE782

先ほど、肝心のshared属性のこいしがi01とi05で被っていたり、そもそもi05を入手する設定を忘れていたのに気付いて修正していました；

**Comment by snext1220** [comment]
scenario.xmlのUpをありがとうございました。
こちらtestをPlaygroundに反映し、kingをtestにそれぞれUpし、それに伴いnexts属性も「nexts="test"」にはしておりますが（テストの便宜上でそれ以外は戴いたデータをそのまま利用）、それで確認したところ、問題なくアイテムi05の移行はできているようでした。

現時点で現象が再現せず、という状況ですが、test/scenario.xmlクリア時のストレージをご確認戴いて、そのタイミングでのkingのセーブデータをキャプチャ戴いても宜しいでしょうか。
参照：https://sorcerian.hateblo.jp/entries/2018/06/18

＃あるいは、king起動時に「最初から～」になっているかなども気になりました。

お手数をおかけしまして恐縮ですが、どうぞよろしくお願いいたします～

**Comment by toki-sor1** [comment]
お忙しい中、シナリオのご確認＆ご助言ありがとうございます！
リオさんのご助言を参考に、セーブデータを確認しながら前回アップしたscenario.xmlで改めてテストを行ったところ、**今度は「king」に「こいし（i05）」が引き継がれていました！**
（kingのアイテム欄でも『こいし』を持っていました）
![kingセーブデータ](https://user-images.githubusercontent.com/42646342/62703675-a9b04000-ba24-11e9-9cfa-3c08265cee34.PNG)

前回はテストの方法が間違っていましたorz　お騒がせして申し訳ありません；；
その原因を備忘録として書きますね；（どうも別のエラーが起きていたので、下の方までスクショを撮っています）

- testクリア時に「最初から冒険に挑戦する」を選んでいました
- ご指摘の通り、king起動時に「最初から」を選んでいました

**上記2点の間違いを同時に、または交互に行っていたため**原因がどうにも判らず混乱していた状態でした；
正解の手順は、 **「testクリア時に『最初から冒険に挑戦する』を押さずにkingを『続きから』始める」** だったのですね……盛大な勘違いでご迷惑をお掛けしてしまい、本当に申し訳ありませんでした；；

ただ、今回のことで**シナリオクリア時に「最初から冒険に挑戦する」ボタンをウッカリ押してしまう引き継ぎトラブルも起きるのでは**と感じました。
引き継ぎシステムを利用する際には、注意書き等の対策も必要かもしれませんね。

**Comment by snext1220** [comment]
お忙しいところ、ご確認有難うございました！
そして、とりあえず現時点での正常動作をご確認できたとのことよかったです^^;

> 「最初から冒険に挑戦する」ボタンをウッカリ押してしまう

こちら私の方でも悩んでいたのですが、きちんと申し送りできておらず、申し訳ありませんでした；現時点での対策というか懸案事項ですが、以下のように考えています。

+ nexts属性が付与されている場合、エンディングページには［最初から～］の代わりに、［次のシナリオに進む］ボタンを表示する
+ 【懸案】nexts属性に複数のidを指定した場合、最初の一つを表示、で良い？（複数表示もできるが、却ってわかりにくくなりそうだが、単一の場合は他にも引き継がれていることが判りにくいかも）
+ では、いっそのこと、nexts属性の有無に関わらず、「end="happy"」では［最初から～］のボタンを表示しない or ［ペンタウァに戻る］が明快？（そもそもhappyでは最初から冒険、はあまり使わないのでは？）
+ 後続のシナリオ（今回はking）では［続きから］という形になりそう（［最初から］への変更は、に既存機能のそちこちに影響が出るので若干悩ましい）

という感じです。
皆さんのご意見を伺ってからの対応の方が良さそうなので、こちらはOct Update?に持ち越しですかね^^; お手数ですが、引き続きご意見のほどをお願いいたします。

**Comment by snext1220** [comment]
こちらときのじさんからＤにてご意見戴いておりましたが、長くもなってきましたので、勝手ながらこちらへ移動させて戴きました。

>個人的には、今後のキャラ引継でトラブル防止の為にも「nexts属性の有無に関わらず、「end="happy"」では［最初から～］のボタンを表示しない or ［ペンタウァに戻る］」が良いかなと思いました。

賛成です！確かにhappyで［最初から～］はあまり意味がないんですよね（当初はマルチエンディングに挑戦するため、という趣旨はありましたが）^^;
では、happyで［ペンタウァに戻る］を表示、badは現状維持で、nextsは特に対処しない、で、まうは進めていきたいと思います。

nextsについては、リンクではなく、たとえば「※クリアデータは、そのまま次のシナリオに引き継がれます。」のような文言をリンクの下に表示させるのもありかもしれませんね（次のシナリオ情報は、scenarioページで扱うのみでシナリオ側では記載しない）。
