### ISSUE TITLE
制御ボタンにおける条件のグループ化

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#8]
ボタン制御でのグループ化（フラグが何個以上揃ったら表示）

```
g(f01,i01,r01:scepter,...)3     … 条件が3個以上揃っていたら
```

g(...)1とすることで、これまでは表現できなかったor条件を表すことも可能。

互換性は維持されますが、一度、新構文を追加してしまうと、以降の構文追加は難しくなると思われるため、将来的な要件も合わせて、他に必要な条件がないかなど、ご意見戴けますと幸いです。

> ■ときのじさんご意見 （バグ報告移動済みのため、省略しています）

**Comment by cocotori** [comment]
条件分岐まわりなどの制御の機能要求はおそらく際限がなく、
ずっと作り続けないといけないかも、というのを心配しています。

これ以上の機能UPとなると
ツクールやティラノスクリプトを使ったほうが
すでに用意されている・完成度も高いことが多く、
今のSTextのプラットフォームで頑張って作る
労力や時間がもったいないようにも思います。

今まで作ってきたものは最低限必要なレベルのものだったと思うので、
作ってきたものまで無駄だったというつもりは全然ありませんが。

ただこれ以上となると、作り込みも確認時間も馬鹿になりませんし、
慎重になったほうがいいかなと感じます。

ずっとSTextを精力的に作ってくださってるのに
水を差したいわけではないし、
動作確認等の協力はこれからも積極的にしたいと思いますが、
一意見として参考にしてもらえればと思います。

**Comment by toki-sor1** [comment]
作り込みや様々な確認作業に関する懸念ですが、確かに現状では、システムの拡張からの動作確認以外にも、シナリオ作成に始まり、各人のシナリオのテストプレイや意見交換、更にはサイトやbotの管理運営など、企画の参加者全員にそれぞれ負担が掛かっていると思います。

負担削減については以前から掲げている目標でしたが、現状を顧み、それが上手く実現できていないと実感しております（汗）。

Next自体が息の長い企画ですから、この機会にシステムの拡張の件だけに止まらず、SText全体の運営方法・方針を見直し、もう少し緩やかで、のびのびと創作できるような環境へと改善していきたいところですね。

**Comment by snext1220** [comment]
こちらは時間も経過してきたので、ニーズがなければ一旦クローズにしていきますが、そこまで要件ない感じですかね^^;

**Comment by cocotori** [comment]
すみません！反応が遅くなりました。

何個以上揃ったら、という機能は
そこまで必要ないかなと思っているのですが、

・一度たったフラグのOFF
・複数フラグ指定の場合は、andだけでなくor指定
・そのさい、ON or ON or ONだけでなく、
　OFF or OFF or ON
　といった、ON/OFFの混在

あたりの制御ができると、フラグ周り制御としては
完璧かなと思っています。

どれも、アイテムなどを駆使して
無理やり実現することはできるので、
難しいようならなくても大丈夫です。

**Comment by snext1220** [comment]
> ・複数フラグ指定の場合は、andだけでなくor指定
> ・そのさい、ON or ON or ONだけでなく、
> 　OFF or OFF or ON
> 　といった、ON/OFFの混在

まさに同感です。
ただ、問題になっているのが従来シナとの互換性でして。

「a,b,c」「-a,b,c」のような記法を現在認めていますが、
これに「a,-b,-c」（a & -b & -c）のような表記を認めた場合、
「-a,b,c」の意味が曖昧になってしまうという問題が；
＃ さすがに分岐周りは既存シナへの影響が大きいので悩ましい…

とりあえず、これまでの表記の延長線であれば、

+ 「a|b|c」で、a、b、cのいずれかを満たしている場合
+ 「-a|b|c」で、a、b、cのいずれも満たしていない場合

を実装することは可能だと思います。

あるいは、完全に追加構文にして、

+ 「&(a,-b,c)」で「aがON、かつ、bがoff、かつ、cがon」
+ 「|(a,-b,c)」で「aがON、または、bがoff、または、cがon」
+ 「^&(a,-b,c)」で「aがON、かつ、bがoff、かつ、cがon」の否定
+ 「^|(a,-b,c)」で「aがON、または、bがoff、または、cがon」の否定

とするのが一番重い対応ですかね...（この辺になると、否定とか使いこなせる気がｗ）
＃ 実は、上の構文にすると、元々の案「g3(a,b,c)」にも親和性は良い^^;

とりあえず優先順位（あるとすごく助かる、あれば良いかも、なくても、ない方がいい）などのご意見を引き続き皆さまから募っていければと思います～

＃ もちろん、上記以外の表記案もなんなりと。

**Comment by RYU-DS** [comment]
私も散々andとorを希望してきた身ですが、従来との互換問題は難しいですねー、GBATとかでも検索&置換が出来ると簡単に書き換えできるんですが…
思い切って全く新しい構文にして、従来の構文もそのまま認識して使えるようにするとか？
新しい構文もズバリandとorとかｗ
フラグaとbとc全て必要＞(a,and,b,and,c)
フラグaと、bかcのいずれかが必要＞(a,and,b,or,c)
フラグが無い事が条件の場合はそれぞれ頭にｰを
といった具合にフラグ1つ1つに条件を設定できるとわかりやすく汎用性も高いと思います、素人考えですが。

**Comment by snext1220** [comment]
> 全く新しい構文にして、従来の構文もそのまま認識して使える

こちらについては可能なのですが、似た機能があると、ご新規さんへのハードルが高まるのと、二重化によってテスト工数が跳ね上がるのが気にはなっています...（特にキモの部分なので）

and／orの混在については優先順位の問題が出てくるので、さらに厄介ですね...（「aとb」または「c」、なのか、「a」と「bまたはc」なのか）勿論、この辺もカッコ構文を設ければ対処はできるのですが（影響は大です）、そこまで使いこなせる開発者（あるいは必要とするシナリオ）が限定されるのではないか＆シーンを分けた方が却ってすっきりするのではないか、とも。

条件分岐はSTextのコアでもあるので、機能性を高めつつも、テストの容易性／保守性も維持できるよう、優先順位を付けていければと。引き続き皆さまのご意見を伺う、とさせてくださいm(_ _)m

＃ このようなシーンで、このような記述を使いたい、という例があると、可否、代替案なども出しやすく、助かります～

**Comment by RYU-DS** [comment]
従来構文の使用は、ただ単に既存シナ製作者の改訂負担だけの話なので、そこは「がんばってください(ﾆｯｺﾘ)」でもいいっちゃいいんですよねｗ
条件同士の関連まで考えるとほんとーに面倒ですよねー、コレはさすがに「必要になったものから順に」でいいと思うんですが、執筆側がそれを認識するタイミングやらその実装まで待てるか？っていう問題が…
そのスレでもラストでどれか必要になるかもしれないんですが、たぶん現状でなんとかしちゃうだろうと…

**Comment by RYU-DS** [comment]
自分の希望は
●andとorの混在は難しいのでそれぞれで囲ってなどしての条件付け
・and(1,2,3)で1&2&3全てが必要
・or(1,2,3)で1or2or3のいずれかが必要
●上記と平行して有り無しの混在
・and(1,ｰ2,3)で1が有り、かつ2が無く、かつ3が有る、というの全ての条件を満たすと出る
・or(1,-2,３)で1が有る、または2が無い、または3が有る、というのいずれかの条件を満たすと出る
この2つ（一部現在でも出来ますが）が欲しいです。

具体的な使用例は
・andの場合は、and(ボス１倒しf,ｰボス２倒しf)で
「ボス１を倒した後、ボス２を倒すまでの間だけ出したい選択肢」を簡単に出せる、というものです。
・orの場合は、or(NPC1,NPC2,NPC3)で
「仲間が（1人）いる事を条件にした選択肢」が出せます。
いずれも裏のfを設定したり、既に実装された隠しfの設定やその削除のおかげで可能にはなっていますので、どうしてもと言うわけではありませんが、やはり今後必ず必要になると思うのとその際に戻って別のfを設定する事になると危険かな、という長編をやっている者としての危惧からなので、少数意見ではあると思いますが。

**Comment by snext1220** [comment]
試験的に、新しい条件構文をGitHub Pagesに導入してみました。
異例ですが、あくまでα版の扱いで、今後削除するかもしれませんので、お試しでのみご利用ください（簡単なテストしかしていないので、不具合あったらすみません）。

+ 基本構文は、!(A&(-B|C))
+ 「!」は全体の否定（先頭のみ）、「&」は「かつ」、「|」は「または」
+ 個々の条件の否定は「-」で
+ カッコの利用は自由
+ ただし、利用する場合には以下のようにscene要素配下をCDATAセクションで括ること

```
<scene id="2">>
<![CDATA[
...本文...
]]>
</scene>
```

是非お試し戴いて、使い勝手などの面でご意見あればお願いします。
繰り返しですが、まだ確定の機能ではないので、今後構文は変更の可能性あります。

**Comment by toki-sor1** [comment]
お試し条件構文の導入お疲れ様です！
早速Playgroundの機能テストファイルを変更したりしながら試していましたが、この機能でリンクボタンそのものの表示も制御できました。
ただ、こういう使い方をして不具合が出ないか心配ではあります。

（あと、戦闘があるシーンの場合、1番上に設定した条件構文の文章とリンクボタンが戦闘欄を挟む形で上下に分離してしまったので、戦闘があるシーンでは、リンクボタンの表示を制御する目的では使えないかも……？）
![image](https://user-images.githubusercontent.com/42646342/48315275-723c7080-e617-11e8-92de-02f0d3c20fb2.png)

**Comment by snext1220** [comment]
> ただ、こういう使い方をして不具合が出ないか心配ではあります。

ご指摘の用途はあまり想定していなかったので、確認はしていなかったのですが^^;、理屈上は可能ではあります。ただ、リンクボタンそのものに分岐機能があるので、基本はそちらをご利用ください、というところでしょうか。
＃ 文章を伴う場合も、${if}分岐とボタン分岐を分けて記述戴くということになるかと（条件式は重複しますが；）。

> 文章とリンクボタンが戦闘欄を～

はい、現在は戦闘欄（敵リスト）は、**移動ボタンの直前に埋め込む**という仕様になっているので、そのような状態になります。
＃ こちらも、勿論、どのようなルール（位置）で表示する、を決められれば（＆汎用性があれば）変更することはできます～

ということで、まとめますと、STextでは、

+ 本文
+ 敵リスト
+ 移動ボタン

という順序での表示を想定しての仕様になっていますので、これに沿ったscene構成にしていただくと、表示のまとまりはよくなるかと。
＃ 繰り返しですが、あくまでルールなので、仕様としての一貫性さえ保てれば、変更そのものは可能です！

**Comment by snext1220** [comment]
こちらマニュアル更新済みです。
https://sorcerian.hateblo.jp/entry/2018/11/01/211745
今後は極力、新規構文をご利用いただきますようお願いいたします。

**Comment by toki-sor1** [comment]
山田さんがこちら（https://sorcerian.progoo.com/bbs/sorcerian_tree_r_1775.html） にアップされているテキストの動作確認を行っておりましたが、scene 29のresultを修正した上でscene 0をscene id直下から下のsceneの上の行までをCDATAで囲ったところ（https://github.com/snext1220/stext/issues/8#issuecomment-437653689） 、実績不要の確認用のボタンごと非表示になってしまいました。
（私自身まだ新構文に慣れていないので、こちらの指定ミスの可能性大ですが；；）

動作環境は、Win8.1 Chrome 71.0.3578.98（64 ビット）です。

**Comment by snext1220** [comment]
こちらご迷惑をおかけしています。
新規構文とMarkdownとの競合?で問題が出ているようです。

とりあえずバグ修正したものを、GitHubにのみ反映しております。
実は、かなり泥臭い処理をしており、他の分岐への影響を否定できませんので（すみません）、引き続き検証を進めます。
皆さまの方でもFebruary Update動作テストの一環として、既存シナの確認、及び、新構文での試しをお願いできますと幸いです。
