### ISSUE TITLE
pre要素（```～```）、code要素(`～`）へのスタイル指定

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#80]
主にチュートリアル対応です。

pre、code要素へのスタイルを追加します。
＃現在は小さなフォントに見えるだけで、あまり用途がないので、独自のスタイルを設定します。

**Comment by toki-sor1** [comment]
チュートリアルで拝見して、これは便利だなぁと思っていました。
「道場」制作時には、全角にして対応したり、スクショを使って対応していたのですが、 **pre、code要素を使った方が見易かったのでは、と感じる場面も多々あった** ように思います。

また、チュートリアル以外でも、 **シナリオ本文と謎掛け（または手紙）など、見た目を明確に分けたい時** に、これらの要素が役立ちそうと感じました。

**Comment by snext1220** [comment]
ご評価ありがとうございます～

手紙＞はい、まさに、そのような引用系を表すことを想定しておりました！（これまで罫線で区切る程度しかできなかったので^^;）まだ利用されているシナも少ないかと思うので、見た目面で「こんな感じの方が～」というご意見は先着順ですｗ
＃というのは冗談ですが、でも、早いうちの方が修正はしやすいかと^^;

あとはMarkdownであまり利用されていないのは＃、＃＃（見出し）あたりですが（＃＃＃以降はそれなりに使われてる？）、なにかしら目立つように修飾を入れようかなとも。
