### ISSUE TITLE
シナリオ紹介への背景透かし追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#81]
#68 で追加したresults、clears属性ですが、正直あまり目立たないため、以下の方策を取れないかと考えています。

+ クリア済みのシナリオ：背景に斜めに［Cleared！］のような透かし文字画像を入れる
+ すべての実績を取得している場合：同様に［Complete!!］のような透かし文字画像を入れる
+ 明確に区別するように、透かしの色は変化させたい

如何なものでしょうか。
これに伴い、「クリア？」項目は削除（取得実績数はママ。ただし、パーセンテージは追加するかも）できればと思っております。

画像追加にあたっては、何時も恐縮ながら、@toki-sor1 さんへのご相談になってしまうのですが、如何なものでしょうか。お手すきの時にでもご意見頂戴できますと幸いです。

**Comment by toki-sor1** [comment]
> クリア済みのシナリオ：背景に斜めに［Cleared！］のような透かし文字画像を入れる
すべての実績を取得している場合：同様に［Complete!!］のような透かし文字画像を入れる
明確に区別するように、透かしの色は変化させたい

背景に［Cleared！］［Complete!!］が表示されるので、パッと見て判断できるのが良いですね。
何となくモンハンのクエストクリア時のスタンプ風表示をイメージしましたｗ（http://www.capcom.co.jp/monsterhunter/goods_other109.html ）
もし参考になりそうな画像等がありましたら、教えていただけますと助かります。

しかし、上記ご要望について気になる点があります。

- シナリオ紹介文には画像が左or右に配置されていますが、壁紙サイズや文字の表示位置は如何しましょう？（①中央配置・文字が隠れない程度　②中央配置・文字が多少見切れても良い等）
- 「クリア済み＆すべての実績を取得している場合」の表示（文字）はどうしましょう？（1枚の壁紙になると思いますが）

> これに伴い、「クリア？」項目は削除（取得実績数はママ。ただし、パーセンテージは追加するかも）できればと思っております。

壁紙が実装された時には、「クリア？」は削除しても良さそうですね。
実績パーセンテージは、追加されると実績取得率が分かり易くて良いと思います。

**Comment by toki-sor1** [comment]
参考資料とご回答ありがとうございました！（いえいえ、こちらこそ仕様の勘違い失礼しました…！）
こちらの手違いでサンプルの画像表示位置が中央ではないのですが（すみません；；）、試作品を作ってみました（O/Dアップ済みです）。
https://onedrive.live.com/?id=4837C202555BE782%217572&cid=4837C202555BE782

壁紙としての使用を想定していますが、画像はザックリとトリミングしただけなので、もしご希望のサイズがありましたら教えていただけましたら幸いです。
![default](https://user-images.githubusercontent.com/42646342/51035029-0a40e100-15ec-11e9-95e2-1a97ab1f520e.png)

**Comment by snext1220** [comment]
早速ありがとうございます！
先ほどGitHubにも/stext/common配下にmark_～.pngとして登録致しました（これまで/commonはこちらでUpしてきたのですが、宜しければ以降は @toki-sor1 さんの方でもこちらにUpしてやってくださいませ）。

https://github.com/snext1220/stext/commit/0c88b5fa82b93a835c0a67c14c53edf0f7d6d794
また、本番ページにはClearedのみ有効にしています。

![default](https://user-images.githubusercontent.com/27911337/51036974-247dbd80-15f2-11e9-95ff-44d4392ea7e1.png)

現在は縦横中央に配置しているのですが、丁度ボタンに隠される感じになってしまっているようでして。斜度を60°くらいに付けて戴いても宜しいでしょうか。また、サイズも（あまり制約はないため曖昧で恐縮なのですが）一回り程度大きくても良いように思えました。
如何なものでしょうか。

**Comment by toki-sor1** [comment]
先程GitHubと本番環境に改良版の壁紙をアップ致しました。
合成画像で申し訳ありませんが（汗）、改良版表示イメージはこんな感じです。
![clear](https://user-images.githubusercontent.com/42646342/51074452-d1277000-16c2-11e9-9a8a-afb2111ef2db.png)

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 71.0.3578.98（64 ビット）、iPhone 7／Safariにて確認。

透かし画像、パーセンテージ共に正常に表示されています。

ただ、iPhone 7（Safari）では、シナリオにて指定されたクリア実績を得た際、何故か［Cleared！］が表示されず、その後に全ての実績を得て［Complete!!］が表示されるという謎の挙動を確認しましたが、その後はそういったバグ（？）はなかったです。
（バグが出た時は、実績数の表示確認の為に途中でブラウザの「戻る」を使用し、STextページまで戻ったりしていたので、もしかしたらその影響かもしれません）

透かし画像の反映ありがとうございました！
色は薄目にしていますが、もし「見辛い・他の色の方が良い」という場合には、改めてご相談ください。

**Comment by snext1220** [comment]
clear、複数環境で起こっているということで、気になりますね...
私の環境（Chrome、Edge）で再現できずにおりますが、とりあえず以下の点をお願いしても宜しいでしょうか（お手数をおかけします；；）

+ 発生環境？
+ 現象発生した場合のセーブデータ（フル） ※Up戴けますとm(_ _)m
+ もしエラーが出ているようであればログも戴いて宜しいでしょうか？ ※参考
：https://sorcerian.hateblo.jp/entries/2018/06/18

**Comment by snext1220** [comment]
早速ありがとうございます！
戴いたセーブデータで確認したところ、確かに再現しましたので、確認してまいりますね。

＃セーブデータはUtil6のユーザーディスクツールをぜひ使ってやってくださいｗ（戴いたもので問題なかったので、確認はこちらで進めますね）

**Comment by toki-sor1** [comment]
お返事が遅くなり、申し訳ありません……！
バグの修正やご報告、背景透かしについてのご意見ありがとうございました！
判読を優先させなくても大丈夫＆色は薄めの方が良さそう、ということで、色を薄くし（透明度40%→70%）、ノイズを削除してスッキリさせてみました。
GitHub、本番環境ともに反映済みです。
![image](https://user-images.githubusercontent.com/42646342/51832649-9ebf7900-2338-11e9-9a27-d137efb3f18a.png)

**Comment by snext1220** [comment]
お忙しいところ、早速ありがとうございます！
巻物部分のノイズが消えたことで、画像としてもよりすっきりした気がしますね～

PC、Android、iPadで確認しまして、Android／iPadについてはほぼ問題ありませんでした。
PCについてはCleardだけが若干薄すぎにも感じましたが（Completeは問題なし）、モバイル系ではさほど問題感じないことから、ディスプレイ環境の問題かもしれませんね；他の皆さまは如何でしょうか。

**Comment by toki-sor1** [comment]
ご確認＆ご意見ありがとうございました！
ノイズ除去により見易くなったようで安心しました！

画像の色味や濃さは、仰る通りディスプレイ環境にも左右されますが、前回の修正では、不透明度を結構大胆に調整していたので、同じ調整でも水色系は薄過ぎましたね；

Cleard、Completeともに、O/Dに不透明度70%版（前回）と不透明度60%版（今回）の画像をアップ致しましたので、お手数をお掛けしてしまい恐縮ですが、より適した方を反映いただけましたら助かります。
https://onedrive.live.com/?id=4837C202555BE782%217572&cid=4837C202555BE782

（こちらのモニター上では、前回と今回の画像で濃度の差がはっきりとしているので、どちらか片方だけの差し替えよりも、両方同じ濃度のものと差し替えていただいた方が違和感がなくて良いかなと）

**Comment by snext1220** [comment]
お忙しいところ、何度もありがとうございました！
拝見しまして、60％パターンで本番環境を差し替えさせていただきました～
Clearedもみやすく、Completeも濃すぎるということはないように思えます！

＃GitHubについては、New Playgroｕnd関係で他作業がペンディング中なので、未更新なのですが、次の反映時にまとめてUpできればと思います～
