### ISSUE TITLE
プレイヤー称号（レベル）の追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#82]
#79 を受けてのIssueです。

クリア／実績／ボーナスアイテムの取得数によってSTextトップページに、＜プレイヤー称号＞（レベル）を付与してはどうか、という提案です。

### 称号の計算式

+ シナリオレベルでクリア得点を決定（L1：100＜150＜170＜180＜200：L5）
+ 実績（個数×2） ※シナリオによって個数の差があるので悩ましい
+ ボーナスアイテム（個数×10）
+ 以上を合計したものがプレイヤースコア

本格的には、本当にやることになった場合に考えますが、基本的には得点制とし、シナリオを増やすごとに称号も少しずつ拡張していければと（割合とし、シナリオが増えた場合にはランクおちという方法もありますが、上方向だけの方が気持ちは良いかと）。

### 表示場所／内容

STextページのシナリオ紹介の前？で、表示内容は以下

+ 称号（バナー表示？）
     + @toki-sor1 さん、ご相談させてください。あまりご負担にならぬよう、何ランクかごとに色だけを変化させていければと。
+ 実績情報（総クリア数、総ボーナスアイテム数、総実績数）

### 懸案

本来ならば、実績はレベルごとに重みづけしたいが、個々のscenario.xmlをすべて読み込むのは辛いため、現状は単なる取得数を想定

### 称号名募集

皆さま、部分的にでもぜひお願いします。

+ 50未満：Youngな16歳（例）
+ 50～100
+ 100～200
+ 200～300
+ 300～500
+ 500～700
+ 700～1000
+ 1000～1300
+ 1300～1600
+ 1600～2000
+ 2000～2500
+ 2500～3000 
+ 3000～3500 ※現在のMax
+ 3500～4000
+ 4000～5000
+ 5000～：ドラゴンスレイヤー（例）

**Comment by snext1220** [comment]
# メモ

現状の各シナリオ点数＋合計

No. | Level | 実績数 | レベル点 | 実績点 | 小計
-- | -- | -- | -- | -- | --
1 | 3 | 45 | 170 | 90 | 260
2 | 3 | 3 | 170 | 6 | 176
3 | 1 | 4 | 100 | 8 | 108
4 | 2 | 16 | 150 | 32 | 182
5 | 4 | 11 | 180 | 22 | 202
6 | 1 | 2 | 100 | 4 | 104
7 | 5 | 56 | 200 | 112 | 312
8 | 3 | 3 | 170 | 6 | 176
9 | 1 | 5 | 100 | 10 | 110
10 | 2 | 8 | 150 | 16 | 166
11 | 2 | 3 | 150 | 6 | 156
12 | 1 | 18 | 100 | 36 | 136
13 | 2 | 17 | 150 | 34 | 184
14 | 2 | 10 | 150 | 20 | 170
15 | 3 | 8 | 170 | 16 | 186
16 | 2 | 4 | 150 | 8 | 158
  |   |   |   |   | 2786

**Comment by toki-sor1** [comment]
返信が大幅に遅れてしまい申し訳ありません；
仕様について様々なご提案ありがとうございます！

### 称号の計算式
ご提案の仕様、良いと思います！
実績の個数ですが、原作シナリオでも「天の神々たち」のように難易度が易しくても経験値が稼ぎやすいものもあったりするので、 **シナリオのクリア得点（経験値）の多い少ないも個性であり、 ある意味では原作再現** のような気もしますｗ

### 表示場所／内容
表示場所、内容ともに良いと思います！
バナーについては、 **ドットアイコンのようなイメージ** を想定しています（サイズは、表示場所の関係もあり、あまり大きくない方が良いかなと思っています）。
**「何ランクかごとに」** を前提に、 **「トロフィーのように基本的には色替えで対応し、上位の物は独自のものにする」** くらいが丁度良いのかもしれません。

###  懸案
「取得数」が良いと思います。
肝心のシナリオが快適に遊べなくなってしまってはいけませんし、内部的に処理が重くなる・メンテが厳しい・他の問題を誘発する等の問題を抱えてまで実績のレベルごとに重みづけをするのは、 **リスクの方が際立っている** ように感じました。

### 称号名
各シナリオ点数＋合計まとめありがとうございます！　お疲れ様です！

> 称号候補（キャラtitleと被る？Xanaduネタでいくか）

確かにキャラtitleと被ってる感じはしますが、 **ネタ募集の際には「杖の探索者」等の方が考えやすい気もします。**
ただ、 **Xanaduネタもドラゴンスレイヤー繋がりという意味でも、シンプルでスッキリとしているところも良い感じ** なのですよね～！（あと、独自に考える必要がないところもメリットかと）

Xanaduネタ採用の場合は、称号ごとにバナー（アイコン？）を変えたい感じもしますが、そうなると **見た目をどうするのかネタを募集することになるかも** ですｗ

**Comment by snext1220** [comment]
詳細なお返事ありがとうございます！

### 称号の計算式

> 同じシナリオでクリア得点が稼げる仕様ではない

はい、なるべく様々なシナリオに挑戦してもらおう、が狙いなので、点数加算はあくまで初回クリア時のみです！（というか、点数はセーブデータから都度計算の予定なので、それしかできないｗ）

### 表示場所／内容

> ドットアイコン、あまり大きくない方が～～
> 「何ランクかごとに」 を前提に、 「トロフィーのように基本的には色替え～～

すべて賛成です！
New サイトに移行してしまったので、表示位置は若干悩み中ですが、［シナリオ］ページのシリーズバナーの下部、個別シナの紹介の上、かなぁと今のところは^^;

どんなレイアウトで見せるかによって、バナーの幅が決まりそうですね。
＃ 今のところ、称号名（バナー）、クリアシナリオ数、取得実績総数を見せる感じかなと思っていますが、全体的な見せ方（レイアウト）ゆる募でございますm(_ _)m

### 懸案

> 「取得数」が良いと思います。

賛成です！
実績レベルはシナリオによって、かなり差がありそうですし、シナリオレベルと違って、管理者が調整するのは難しそうですものね～^^;

### 称号候補

ここが一番悩ましいです；；
考えやすさは、やはり「杖の探索者」なんですよね。。
ただ、キャラtitleと少しでも差別化を、と考えると、はたと思考が止まってしまうという；（言い回しは多少工夫できると思うんですが、結局同じものだよね、になってしまいそうｗ）

ということで、（あくまで現時点では、ですが）Xanadu押しでしかね～
シンプルでドラスレ繋がり＆独自に考えなくとも、はまさにでして。

Xanaduでは戦士称号と魔法使い称号が二系統ありますが、今回は、双方を入りくり（混ぜ合わせる）かな～と。たぶん、FIGHTER、Wizard-Lv.15のような、意味的に他と重複したり、呼称的にイマイチなものを間引いていく感じかなと。

あとは、和名を併記すると、それなり独自性も出せるかも？
＃たとえば、Aspirant（大志を抱く者）、Battler（戦人）とか？？

> Xanaduネタ採用の場合は、称号ごとにバナー（アイコン？）を変えたい～～

視覚的に楽しいので歓迎！ですが、ときのじさんのご負担だけが心配ですね...^^;
ある程度、ご負担を抑えつつという意味では、背景に、称号イメージに合った原作シナ＋Nextキャプチャを重ねる、とかはありでしょうか？（たとえばAspirantであれば、はじまりゼロの朝日のキャプチャとか）

**Comment by toki-sor1** [comment]
こちらこそお返事＆各種項目についてご賛同ありがとうございます～！
仕様としてほぼ決定かなと思われる項目は割愛しながら返信しますね。

### 表示場所／内容
> New サイトに移行してしまったので、表示位置は若干悩み中ですが、［シナリオ］ページのシリーズバナーの下部、個別シナの紹介の上、かなぁと今のところは^^;

特にソシャゲでよく見掛けますが、プレイヤーのステータスは常に見えるところに配置されていますので、 **［シナリオ］ページのシリーズバナーの下部、個別シナの紹介の上** がベストな感じはしますね～。

> どんなレイアウトで見せるかによって、バナーの幅が決まりそうですね。
＃ 今のところ、称号名（バナー）、クリアシナリオ数、取得ボーナスアイテム数、取得実績総数を見せる感じかなと思っていますが、全体的な見せ方（レイアウト）ゆる募でございますm(_ _)m

表示する情報については、 **リオさんが挙げてくださったものが良さそう** ですね。

見せ方ですが、個人的には、やはり **ソーサリアン風を推したい** ので、 **ゲーム画面のSTATUSのような枠に各種情報を入れる** のをイメージしています～。

**バナーの幅について** は、「称号候補」の話題と併せて後述しますね。

### 称号候補

> Xanaduでは戦士称号と魔法使い称号が二系統ありますが、今回は、双方を入りくり（混ぜ合わせる）かな～と。たぶん、FIGHTER、Wizard-Lv.15のような、意味的に他と重複したり、呼称的にイマイチなものを間引いていく感じかなと（～Lv.15は独特の味があるといえば、そうなんですがｗ）。

（現時点では個人的にですが） **賛成です！**
私も戦士称号と魔法使い称号は、きっと混ぜ合わせるものだと考えていましたのでｗ
間引き基準についても、良いと思います！

> あとは、和名を併記すると、それなり独自性も出せるかも？
＃たとえば、Aspirant（大志を抱く者）、Battler（戦人）とか？？

（こちらも現時点では個人的にですが） **賛成です！**
魔法名や技名にルビが振られているのとか大好物なのでｗ
それに、独自性を出せるという意味でも良い案だと思います！

> ある程度、ご負担を抑えつつという意味では、背景に、称号イメージに合った原作シナ＋Nextキャプチャを重ねる、とかはありでしょうか？（たとえばAspirantであれば、はじまりゼロの朝日のキャプチャとか）

お気遣いいただき、ありがとうございます……！

称号イメージに合った原作シナ＋Nextキャプチャを使用するのも **良いですね！**
こちら、バナーのお話とも絡んでくるのですが、  **「キャラクターの顔グラのように称号イメージに合った原作シナ＋Nextキャプチャを表示する」**　ようにすると、称号名の視認性も良く、尚且つ、枠内にも納め易そうと思いました（サンプル参照　※空白が寂しくて仮にPOINTを入れています）。
![称号サンプルのコピー](https://user-images.githubusercontent.com/42646342/54490980-0be59880-48fe-11e9-86e7-dafd0e2f40c5.png)

**Comment by toki-sor1** [comment]
連投すみません……！
今回のサンプルで仮に「POINT」と入れたのですが、 **「EXP.」** の方がよりソーサリアンらしいかもしれません（ただ、文字数が少ないので、配置バランスが難しそうではありますが；）。

**Comment by snext1220** [comment]
お返事前後しますが、取り急ぎ称号候補を挙げてみました。
正直、和名はかなり適当でもちっと見栄えのするものもできそうなので、代案絶賛募集中です^^;

画像候補については埋まりきってません；
まずはNext系を中心に入れていますが、原作で良いものがあればぜひ。

称号 | 和名 | 画像（候補）
-- | -- | --
Novice Adventurer | 駆け出し | 消えた王様の杖（しぬでないぞ）
Initiate | 新参者 | 暗き沼の魔法使い（かえって～）
Aspirant | 大志を抱く者 | ゼロ
Battler | 戦人（いくさびと） |  
Adept | 熟練者 |  
Chevalier | 義侠の者 |  
Conjurer | 奇術師 |  
Theurgist | 神々に祈る者 | 天の神々
Warrior | 古つわもの |  
Enchanter | 魅了する者 | Ys
Warlock | 七つの塔の魔術師 |  
Sorcerer | ソーサリアン | クロノス
Necromancer | 死者と語る者 | 剣と魔法の都
Illusionist | 幻惑を魅せる者 | 少女は英雄を
Paladin | 聖騎士 |  
Dragon Slayer | ドラゴンスレイヤー | 時の封土

**Comment by snext1220** [comment]
とりあえずダミーですが、作成戴いたバナーをページ右隅の固定表示されるようにしてみました（ページも隠しページです）。現在は未実装ですが、クリックで非表示になるようにする予定です。
https://web-deli.com/sorcerian/text/scena_new.aspx

如何でしょうか？？

**Comment by toki-sor1** [comment]
### 称号候補

称号候補アップありがとうございます！
称号と和名を拝見しましたが、ソーサリアンでは意外と騎士キャラがいないので、「Paladin（聖騎士）」が特に画像を決めるのが大変そうだと感じましたｗ

なかなか候補を挙げるのが難しいものもありますが、私も使用画像を一部ですが考えてみました！

称号 | 和名 | 画像（候補）
-- | -- | --
Battler | 戦人（いくさびと） | **ボスと戦うソーサリアン達**
Adept | 熟練者 |  **ドトーのトライアスロン（ギャルのパ…アルモス）**
-- | -- | または **白夜に消えた村人（真面目にマーヴァル）**
Chevalier | 義侠の者 | **魔の下僕ガッシュの陰謀（ミラル爺）**
Conjurer | 奇術師 | **MD版／マリオネットの館（ダール伯爵）**
Warrior | 古つわもの | **呪われたオアシス（ルワン）**
Warlock | 七つの塔の魔術師 | **囚われた魔法使い（ログレック）**
Paladin | 聖騎士 | **パンドラの箱（デュカリオンがそれっぽい？）**

### バナー

仮実装ありがとうございます～！
やはり実際にサイト内に表示されると、イメージも掴み易くなりますね！

> とりあえずダミーですが、作成戴いたバナーをページ右隅の固定表示されるようにしてみました（ページも隠しページです）。現在は未実装ですが、クリックで非表示になるようにする予定です。

おお、こういう仕様も可能なのですね！
クリックで非表示にできる（予定）というのも良いと思います！
PCとiPhoneから確認しましたが、バナーサイズを調節すると画面もスッキリしそうです。

> ちょっと大きいので、スペースに余裕もあるのを考えると、最終的にはもう少しコンパクトに抑えた方が良いかもしれませんね^^;

そうですね、横幅はもっと狭めても良いと思いますし、「（0%）」も削って横幅を削っても良さそうです。
ただ、縦幅を広くすると、バナーの非表示を実装しても、バナーが表示された時に見辛そうなので、極力縦幅は広くしない方が良いかもしれません。
＃iPhoneから見ると色が暗めだったので、グラデ＋少し明るめに調整しています。

![称号サンプル２のコピー](https://user-images.githubusercontent.com/42646342/54540020-93a0d500-49da-11e9-8a30-b90e7629ef4a.png)

**Comment by snext1220** [comment]
諸々ありがとうございます！
お返事前後してしまい恐縮ですが（汗）、とりあえず現在のものでプロトタイプを作成してみようかと。ついてはお手数ですが、文字／画像の入っていない枠だけのバナーをUp戴いても宜しいでしょうかm(_ _)m

**Comment by snext1220** [comment]
とりあえず現在のもので、文字を反映させるようにしてみました（よって文字は重なっていますが、お許しください）。あとは、諸々の実績を演算して、ランクを決定するロジックを実装して完成です！
＃てか、それがメインロジックなんですがｗ

@toki-sor1 さん＞
お手数ですが、埋め込み画像のご用意をお願いできますでしょうか（高さ50px、幅80px／rank0.png～rank15.png）。
＃縮小すると、画像の乱れが出るものがあり、、お手数をおかけします。。

画像は取り直しもきつそうなので、ソーサリアン時計（ https://1drv.ms/f/s!AoLnW1UCwjdIgyPrKc3UpVVIgJeW
 ）で賄える範囲で、と思っておりますが、如何なものでしょうか（基本は、 https://github.com/snext1220/stext/issues/82#issuecomment-473949517 のご提案で異存はないのですが、一部時計で賄えないものがある、かも…？）。

**Comment by toki-sor1** [comment]
お待たせしました～！
先程O/Dに文字無しバナー（2種類）をアップしました！
https://onedrive.live.com/?id=4837C202555BE782%216763&cid=4837C202555BE782
![stext_title1](https://user-images.githubusercontent.com/42646342/54598973-fba7f780-4a7c-11e9-818a-7ab3d619a3bd.png)
![stext_title2](https://user-images.githubusercontent.com/42646342/54598975-fba7f780-4a7c-11e9-9406-712917df3c3c.png)

どちらか良さそうなものを反映していただけましたら幸いです～。

**Comment by toki-sor1** [comment]
> とりあえず現在のもので、文字を反映させるようにしてみました（よって文字は重なっていますが、お許しください）。

お疲れ様です！！　早速の改良ありがとうございます～！！
文字が太字＋大き目になって、縮小表示されるスマホ環境でも見易くなりましたね～。
ただ、項目の文字数の関係で、実績取得数が増えてきた時（EXP.  2786／2786など）に、何だかはみ出してしまいそうな気配がありますね……；
こちら、 **「項目を他の表現に変更する（短縮）」「項目は3行に変更する」** などの調整が必要かもしれませんね；；

> また、ご指摘の通り、初期表示時には若干邪魔にも思えたので、少しスクロールしたところで表示されるようにし、また、クリックでの非表示にも対応しました。

おお、視界の外でバナーがチラつかなくて良いですね！　素晴らしいお気遣い！！

> お手数ですが、埋め込み画像のご用意をお願いできますでしょうか（高さ50px、幅80px／rank0.png～rank15.png）。
＃縮小すると、画像の乱れが出るものがあり、、お手数をおかけします。。

いえいえ、こちらも了解です！
私もソーサリアン時計の時に使用したスクショを利用することを考えていましたので、主にはO/D内にあるスクショを使用させていただこうと思います～。

> （基本は、 #82 (comment) のご提案で異存はないのですが、一部時計で賄えないものがある、かも…？）。

O/D内のスクショを改めて確認し、対応できるものは優先して対応し、現在の提案で対応が難しいものについては、代案で対応またはご相談させてくださいませ～。

**Comment by snext1220** [comment]
早速の背景画像ありがとうございました！
こちら判断で少し明るめ＆ゲーム画面の透かしとも共通する方を選択させていただきました～（実績演算含めて、既に実装済みなので、ご確認くださいませm(_ _)m）
＃細部調整してまいりますので、暫くは変更あるかもです^^;

> 「項目を他の表現に変更する（短縮）」

仰るように既にはみ出てましたのでｗ、ラベルを短縮させていただきました！
チラつきもなくなったようで、良かったです～

> O/D内にあるスクショを使用させていただこうと思います～。

お手数をおかけします（汗
代案の可能性についても承知いたしました～

Paladinは確かに悩ましいですね^^;
代案でMaster Load（偉大なる領主）で、呪われた国～のディンギルとか？

もし和名の代案もありましたら、引き続きよろしくお願いします～（こちらも気まぐれに差し替えるかもしれませんｗ）

**Comment by toki-sor1** [comment]
> こちら判断で少し明るめ＆ゲーム画面の透かしとも共通する方を選択させていただきました～（実績演算含めて、既に実装済みなので、ご確認くださいませm(_ _)m）
＃細部調整してまいりますので、暫くは変更あるかもです^^;

実装＆調整お疲れ様です～！
サンプルが無地でややシンプル過ぎた感じがしたので、背景もプラスしたのですが、確かにリオさんが仰っていた画像透かしという点で共通していますね！
作成して良かったです！　反映ありがとうございました～！（細部調整も了解です！）

> 仰るように既にはみ出てましたのでｗ、ラベルを短縮させていただきました！
チラつきもなくなったようで、良かったです～

おお～！　かなりスッキリしましたし、はみ出しも解消できて最高ですね！
ありがとうございます～！

> ＃熟練者はパ●ティしかないと思います！

スクショを眺めていて、パ●ティな師匠はある意味熟練者だと思ったので提案させていただいたのですが、まさかの採用ｗｗ

> Paladinは確かに悩ましいですね^^;
代案でMaster Load（偉大なる領主）で、呪われた国～のディンギルとか？

スクショについてご意見やご提案ありがとうございます！
縮小画像の見栄えの関係で、「古つわもの（幕末ソーに変更）」「PaladinからMaster Loadに変更（ディンギルに変更）」と一部変更させていただき、埋め込み画像を作成しました～（ソーサリアン時計のスクショでは対応が難しいものは、スクショを撮って対応済み）。
https://onedrive.live.com/?id=4837C202555BE782%219468&cid=4837C202555BE782
![image](https://user-images.githubusercontent.com/42646342/54610717-e6d95d00-4a98-11e9-8d47-2f924ba4206f.png)

**Comment by snext1220** [comment]
早速ありがとうございます！
そして、キャプチャ反映しまして、ページも本番環境に反映しております～

ただ、スミマセン、rank14.png（ディンギル）が恐らく古いものになっているようでしたので、差し替え戴けますと＆ノリでrank4.png＝パン●ィだったのですが縮小してしまうと元ネタが判らないかもですね。。（そうした意味ではrank5.pngも？）一寸元ネタが判りやすいものに差し替えた方が良いかもしれません。。4、5は私の方でも見繕ってみますね～

**Comment by toki-sor1** [comment]
本番環境への反映お疲れ様でした！　そして、ありがとうございます～！！

PCとiPhoneから確認してみましたが、**PCからは問題ない感じ** ですね～。
ですが、 **iPhone（スマホ環境）だと、称号名（というか色が）がちょっと見辛い印象** でしたね。
iPhoneでも拡大すれば称号名もきちんと見えるようになるのですが、縮小された状態だと、背景色との境がやや曖昧な感じかもです；

> ただ、スミマセン、rank14.png（ディンギル）が恐らく古いものになっているようでしたので、差し替え戴けますと

うわー！？　す、すみません！　rank14.pngが差し替えられていませんでしたね……！（大汗）
先程、ディンギルに差し替えました！！
https://onedrive.live.com/?id=4837C202555BE782%219468&cid=4837C202555BE782

> ノリでrank4.png＝パン●ィだったのですが縮小してしまうと元ネタが判らないかもですね。。（そうした意味ではrank5.pngも？）一寸元ネタが判りやすいものに差し替えた方が良いかもしれません。。

私も縮小時に元ネタが分かりにくいものもあるなぁとは思っていたのですが、やっぱり、そうですよね～……；；
＃そんな中で、とくしさんがお作りになった画像は、縮小してもしっかりと元ネタが分かり易く、ぱっと目を引くインパクトが損なわれておらず、本当に凄いなぁと感動していました！　プロの皆様のお仕事しゅごい……！！

> 4、5は私の方でも見繕ってみますね～

おぉお、ありがとうございます～！　それでは、よろしくお願い致しますっ！

**Comment by snext1220** [comment]
> iPhone（スマホ環境）だと、称号名（というか色が）がちょっと見辛い印象 でしたね。

こちら赤系でかなり明るくしてみました（現在、f6f）。
Android環境ではかなり見やすくなったと思いますが、如何でしょうか？

なお、称号だけだとレベル感がわかりにくかったので、プレイヤーレベルも追加しています。
若干、カラーも緑めでいれてますが、合わせてご確認いただけますとm(_ _)m
＃ページ本体にもPlayer Levelについて軽く文章を追加していますが、マニュアルにも別途追加予定です。

> 先程、ディンギルに差し替えました！！

ありがとうございます～差し替えました！
改めて取り直しなどもしていただいたものもあり、ありがとうございました！

> ＃そんな中で、とくしさんがお作りになった画像は、縮小してもしっかりと元ネタが～～

ですね～流石ワンカットで見栄えがが意識されているのかと！

> 4、5は私の方でも見繕ってみますね～

こちらは時計のキャプチャを一通りサムネで見てみたのですが、イマイチこれといったものがないですね...引き続きAll About～など眺めながら見てみたいと思いますが、もしよさげなものがありましたら是非に！

**Comment by snext1220** [comment]
プレイヤーマニュアルも更新済みです。
https://sorcerian.hateblo.jp/entry/20171220

**Comment by toki-sor1** [comment]
昨日はドトーの更新お疲れ様でした～！
また、実装＆告知ありがとうございました～！

> こちら赤系でかなり明るくしてみました（現在、f6f）。
Android環境ではかなり見やすくなったと思いますが、如何でしょうか？

PC、iPhone環境で確認しましたが、背景との境もくっきりして **とてもGOODでした！！**

> なお、称号だけだとレベル感がわかりにくかったので、プレイヤーレベルも追加しています。
若干、カラーも緑めでいれてますが、合わせてご確認いただけますとm(_ _)m

プレイヤーレベルの追加！　**とても良いと思います！**
確かに、称号だけだといまいちレベル感もわかりにくく、目標がぼやけてしまうとやり込み意欲が削がれてしまったりもしますもんね。
プレイヤーレベルのカラー設定も、和名との違いもわかり、且つ、画面全体のバランスとしても崩れていない選択だと感じました！　**こちらもとても良いですね！**

> ですね～流石ワンカットで見栄えがが意識されているのかと！

ですね！　未加工のゲームのスクショは「ゲーム画面そのまま」なので、ワンカットの見栄えを意識した一工夫の大切さを実感しますね！

> ありがとうございます～差し替えました！
改めて取り直しなどもしていただいたものもあり、ありがとうございました！

お手数をお掛けしました……！　ディンギル差し替えありがとうございました！

> こちらは時計のキャプチャを一通りサムネで見てみたのですが、イマイチこれといったものがないですね...引き続きAll About～など眺めながら見てみたいと思いますが、もしよさげなものがありましたら是非に！

ご検討ありがとうございます～。
そうなんですよね、シーンやキャラとしては称号とばっちり合うのに、スクショを縮小した時の見栄えがいまいち……というケースが結構ありますよね……；；
私の方でもコンプリートを進めつつ、 **引き続き丁度良さそうなシーン等がないか探してみます！**

> プレイヤーマニュアルも更新済みです。

更新お疲れ様です＆ありがとうございます！
内容も確認しましたが、 **分かり易い説明で、ばっちりでした！！**

**Comment by cocotori** [comment]
こちらの話題にほとんど触れられずにすみません。
出来上がったものを拝見しましたが、とてもいいと思います・・・！

一つ一つの別々のシナリオが、こういう仕組みがあることで
一つの大きなプロジェクト感がでていいと思います。

このレベルでないと挑戦できないよ、という感じではないので
（それはそれで面白いかもですが）
シナリオ挑戦の邪魔にならず、お、なんだか少しずつレベルがあがってるな
という感じでちょうどいい感じだと思います。

軽く動作確認しましたが、
取得した実績がきちんと反映されていました。

**Comment by snext1220** [comment]
> 一つの大きなプロジェクト感がでていいと思います。

ありがとうございます～実績／ボーナスではなんとなく物足りない、でも重複したものを実装しても…と悩みながらの実装でしたが、ご評価いただいて有難い限りです！折角の機能なので、今後、よりプロジェクトとしての一体感を高める形に発展させられればと…！（ノーアイデアですが^^;）
