### ISSUE TITLE
Playgroundのボタンをアイコン化

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#83]
立て続けに @toki-sor1 さん絡みの案件になってしまい、申し訳ありません。

Playgroundも機能（ボタン）が増えてきて、場所を圧迫しているため、今後の機能拡張を考慮して、ボタンをアイコン化できればと考えております。以下はその案です（あくまで案なので、良いデザインがあればアドバイス願います）。
日本語テキストは、ツールヒントとしてマウスポイント時に表示できればと考えています。

+ シナリオを実行：再生のようなボタン
+ カーソル位置にタグを追加：「<+>」のようなボタン
+ ストレージに保存：https://pixabay.com/p-152091/?no_redirect みたいな感じ？
+ ダウンロード：PCに下矢印を重ねるようなイメージ？
+ クリア：消しゴム？
+ ヘルプ（マニュアルへのリンク。新設）：ハテナマーク
※いずれもサイズは縦30×幅50px程度？

急ぎではないので、実行是非や詳細、ゆるゆるとご相談させて戴けますと幸いです。

**Comment by snext1220** [comment]
早速ありがとうございます！！
おぉ、プレイ画面ともマッチしたデザインで良い感じですね^^（スリットちゃんもｗ）
ファイル名ですが、以下のようにお願いできますでしょうかm(_ _)m

+ pg_clear.png
+ pg_run.png
+ pg_save.png
+ pg_dl.png
+ pg_tag.png
+ pg_help.png

**Comment by snext1220** [comment]
画像作成有難うございました！
本番環境にも反映しておりますので、ご確認ください。
＃テスト時には並び順などについてもご意見頂戴できれば幸いです。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 71.0.3578.98（64 ビット）、iPhone 7／Safariにて確認。
正常に動作しました（参照画像はクリックで原寸表示可）。

<img src="https://user-images.githubusercontent.com/42646342/51084676-523d4080-1771-11e9-92d3-7fbf8c10939c.png" alt="" width="320">

こちらこそ反映ありがとうございました！
ゲーム画面と並んだ時のことを考えて途中でデザインを変更したり、道場のイメージからスリットちゃんにしようと決めたりと、夢中でドット打ってましたｗ
イメージと実際に配置した時の雰囲気はやっぱり違うのと、ゲーム画面と背景色が違うので不安でしたが、個人的には違和感がなさそうで安心しましたｗ

> ＃テスト時には並び順などについてもご意見頂戴できれば幸いです。

並び順は特に問題ないと思います。
事故防止の要素としてアイコン毎に使用する色をできるだけ分けたり、pg_clear.pngのみ色を変えたりしています（pg_clear.pngについてはダイアログによる警告も表示されるので、枠色は他と同じでも良い？）。

「pg_clear.pngの枠色だけ色が違って違和感がある」という場合は、「他のアイコンと同じ色にする」「配置を端っこにする」で解決できるかなと思います。

pg_clear.pngの枠色変更や、その他ご要望等、改めてご相談いただけましたら幸いです。

**Comment by snext1220** [comment]
改めてドット打ちとご確認ありがとうございました！
メイン画面のFIGHTERと開発画面のスリットちゃんと対称的でもあり、愛を感じますねｗ

色をできるだけ分けたり＞はい～お蔭様で視認性も優れていて良いかと！
並びについては、clearを境に、左が編集系、右が保存系＋αとしていました（clearは折角ひとつだけ枠線が違うので、区切り線代わりに利用させていただきましたｗ なので、個人的にはママで良いかと思います！）

＃ フロチャが正式実装されると、こちらのアイコンをお願いさせていただくかもしれませんが（お手数をおかけします；；）、これはまだ若干先のお話ということで^^;、現在は問題ないかと思います！

**Comment by cocotori** [comment]
アイコン化、とてもいいです。
ちっちゃいアイコンでちゃんとスリットちゃんがわかるのかわいいです。

あと、今回の変更ではありませんが、
「ストレージに保存」は「ブラウザに保存」とかのほうが
わかりやすくないでしょうか？
そのままでももちろん構いません。

**Comment by snext1220** [comment]
ご指摘ありがとうございます～
修正済みです！＞ストレージ
