### ISSUE TITLE
ダメージ式のFreeN表記

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#84]
Scenario 16 Traitorで問題になった件です。

ダメージ式での表記と条件分岐の表記が不統一で若干わかりにくくなっています。
https://sorcerian.progoo.com/bbs/sorcerian_tree_p_1817.html

ただ、ダメージ式の方はFree1（数字）表記を残した方が表記もコンパクトになるため維持しつつ、FreeI（ローマ数字）の表記を許容することを検討します。

＃現時点では他に問題出ないかを検討中です。

**Comment by toki-sor1** [comment]
こちらは今後「表記の違いついて注意を促す」ことで、個人的には現状のまま（Free1とFreeI）でも良さそうかなと思っています。

**Comment by snext1220** [comment]
了解です～
システムとしてはその方が楽なのでｗ、引き続きご意見待ちつつ、リクエストなければwontfixとしてまいります！

**Comment by cocotori** [comment]
問題ありません！
