### ISSUE TITLE
Playgroundでの終了処理

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#85]
Playgroundでのシナリオ終了時に編集中の内容がクリアされてしまう問題を、以下でご指摘戴きました。
https://sorcerian.progoo.com/bbs/sorcerian_tree_r_1835.html

伴い、ボタンクリック時に確認ダイアログを表示するよう改めています。

> 現在の注意書きがややヒッソリとしている印象なので、もう少し目立つようにしても良いかなと思います。

上記のご指摘も戴いていますが、確認ダイアログを追加したことから、現状はママとしています。「やはり事前にもう少し注意してほしい」とのご意見あれば、お手数ですがご指摘願います。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 71.0.3578.98（64 ビット）、iPhone 7／Safariにて確認。
正常に動作しました。
ダイアログの内容、ダイアログが表示されるタイミング、OKとキャンセルが選べるところも良いと思います。
内容の保存を促すには十分なご対応という印象でしたので、ゲーム画面上の注意書きは現状のままで良さそうです。
ご対応ありがとうございました！

**Comment by cocotori** [comment]
Win 10/Edge で確認しました。
問題なさそうです。
ワンクッション置くことで、より親切になったかと思います！
