### ISSUE TITLE
Playgroundのフロチャ表示

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#86]
Playgroundで編集したシナリオデータを、GBATのようなフローチャート形式で表示する機能を追加できないか、検討中です。試験的なものではありますが、まずは皆さまのニーズがあるかを確認できれば助かります。

※現時点では、単にフロチャを表示することだけを考えていますが、将来的にはブラウザー上でフロチャを編集し、リンク関係を生成するようにしていければとも（こちらは大規模改訂なので、実現未定ではありますが^^;）
参考：http://visjs.org/examples/network/events/interactionEvents.html

**Comment by snext1220** [comment]
試作版を以下にUpしてみました。
https://snext1220.github.io/stext/flow.html

![default](https://user-images.githubusercontent.com/27911337/51086246-c1be2a80-1787-11e9-8571-ae537cf641c8.png)

とりあえず、シナリオによってはそれなりに表示はしてくれるのですが、特定のシーンに集中的にリンクされると、結構微妙なグラフが出来上がりますね...性質上、致し方はないのですが、集中的なリンクは割愛するなどの工夫が必要かもしれません。。

**Comment by toki-sor1** [comment]
うおおおお試作版アップありがとうございます！！　しゅごい！！！
早速こちらも比較的シンプルなsoulでフロチャ生成してみました！（※画像のフロチャは手動で並びを整形してます）
![image](https://user-images.githubusercontent.com/42646342/51087412-54fe5c80-1796-11e9-8f30-b4546446cfbf.png)

**良かったところ**
- シナリオをコピペするだけでフロチャが自動生成される
- フロチャを縮小・拡大表示できる（全体表示、一部分だけの表示が可能）
- 生成されたフロチャを手動で整形できる

**意見・要望**
- フロチャが生成するごとに形が変わるので、毎回同じ形に生成されると確認し易そうです
- 手動でフロチャを整形すると並びがガタガタになってしまうので、PowerPointのようにピタッと位置が合わせられるのも良さそう
- シーンに含まれる要素（endやenemiesなど）によってシーンの色が変わると見易い？（将来的に編集が可能になると、不要な機能かもしれませんが）
- シーンの表示で冒頭に「${if ○○～」など指定されている場合は、「${if ○○～」が除外されるとシーンが把握し易い？

こんなに簡単にフロチャが生成されるだけでもう感動ものなのですが、これから更に改良されてゆくのだと思うとワクワクが止まりませんね！（意見・要望は、実装可能かどうか分からず書いていますので、難しいものはスルーで；）

> とりあえず、シナリオによってはそれなりに表示はしてくれるのですが、特定のシーンに集中的にリンクされると、結構微妙なグラフが出来上がりますね...性質上、致し方はないのですが、集中的なリンクは割愛するなどの工夫が必要かもしれません。。^^;
＃図はShadowのものですが、Scepter、beginなどは結構香ばしくなりましたｗ

shadowのフロチャサンプルありがとうございます！
動作確認の時間を短縮しようとエディタに直打ちしていたシナリオなので、フロチャは今回初めて見ましたが、動作確認時にも感じていた進行のシンプルさが視覚からも感じられて、なるほど納得という結果でしたｗ

確かに特定のシーンに集中的にリンクされているケースが多いシナリオだと、フロチャが凄いことになっていますね……ｗ（heroも香ばしく仕上がっていて見た瞬間に吹き出しましたｗｗ）
GBATでもそうでしたが、上記ケースでは性質上どうしても表示が複雑化してしまうので、フロチャの見易さを重視する場合は、簡略化も必要かもしれないですね；

開発・改良は、私が考えている以上に大変だと思うのですが（大汗）、引き続きよろしくお願い致します……！

**Comment by snext1220** [comment]
早速のご確認有難うございます～
ちょうど若干手直ししていたので、断片的で恐縮ですが、お返事でございます！

+ プロローグとエンドのみ色で識別できるようにしております。
+ 複雑なフロチャを回避するために、シーン番号の範囲を指定できるようにしました（無指定では全部がフロチャ生成されます） 

その他については、またお返事改めますね…！

**Comment by snext1220** [comment]
改めて早速のご確認有難うございました！
Playgoundリリース以来の大きなアプデ（のはじまり）になるのかな、と自分でもワクワクしていますｗ

> 将来的にはフロチャ編集も視野に……！

はい～問題も山積なので、まずはフロチャ生成機能が安定した後、徐にプロトタイプ版を重ねて、という形にはなるかと思いますが、将来的には^^;
本機能が実現した場合には、GBAT2STextは撤収になって、いよいよ念願の**メイクリアン**と銘打ってのリリースになっていくのかなと。

> フローチャートと言えば、ちゃなさんがシナリオ編集時に色々と～

諸々一家言ありそうですし、是非とも伺いたいですね～ＴＬでもちらっと呟いていますが、ドラモード完結の折には、集まれる方々だけでもオフで、ザックリご意見収集会などできれば、などと。その折にはときのじさんも宜しければオン参加ご検討ください～ｗ

さて、以下ご要望へのお返事です。

> PowerPointのようにピタッと位置が合わせられる

はい～まさに書かれているように、都度生成なので＆位置情報まで保持となると、シナリオデータが大きくなるため、現時点では…スミマセン^^;
編集可能にした時にどうするかですが…たぶん、表示位置の維持よりも部分的なチャート表示（後述）で賄っていくのかなと漠然と。

> シーンに含まれる要素（endやenemiesなど）によってシーンの色が変わると見易い？

現時点では、プロローグ／エンディングのみ色分けしていますが、その他条件がはっきりすれば対応そのものは可能なので、引き続きご意見お願いします～
＃ただ、色を増やすと、それだけ識別がしにくくなるので、皆さまのご意見を伺いながら、最大公約数を採っていく形になるかとは^^;

> 「${if ○○～」が除外されるとシーンが把握し易い？

こちらは対応としては可能なのですが、スミマセン、構文が増える都度、除去のルールも追加しなければならないため（＝保守工数が嵩む）、現時点では見送らせてくださいm(_ _)m
代案としましては、以下を検討しています。

+ scene要素にフロチャ用のtitle属性（フロチャに表示させるためのテキスト）を追加
    + もちろん任意で、存在しない場合は本文の頭数文字ママ。
    + フロチャ向けの情報をシナリオに持たせる？と反論もありそうですが、これまでコメントなどでシーンのメモ書きを付けていた方にとっては用途はありそう
+ ノード（シーン）クリック時に、テキスト情報をポップ表示する
    + UI的に見難くならないかは要検討

> heroも香ばしく仕上がっていて

まさに。これはコスモ世界か…！のような出力になりますよねｗ
これはこれで美しいんですが^^;

> フロチャの見易さを重視する場合は、簡略化も必要かもしれないですね；

はい～試験的に生成範囲を設けてみましたが、（範囲の試行錯誤は若干必要なものの）それなりに見られる感じになった気がします。如何でしょうか？？

**Comment by snext1220** [comment]
本件、試験的にPlaygroundにフロチャ機能を追加してみました（まだ別ページです）
https://www.web-deli.com/sorcerian/next/playground_new.aspx
