### ISSUE TITLE
Playgroundの修飾ショートカット追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#88]
#73 でSGML要素の追加機能を対応しましたが、その拡張版です。
`[Link](...)`、${if}、%red%など、よく利用する拡張マークの追加機能を検討しています。

ただし、構文拡張のたびにメンテも発生するため、ご要望があれば、というレベルで、まずはご意見をお待ちしたいと思います。

**※暫定的に、リンク、条件分岐のみ、本番仮（playground_new.aspx）に反映しています。**

**Comment by snext1220** [comment]
リンク、条件分岐、カラーリングのみ暫定的に反映し、本番環境に反映しています。
該当テキストを反転させた状態でメニュー選択すると適用されます～

**Comment by cocotori** [comment]
確認しました。
自動的にテキストが囲われるの、いいですね。

**Comment by toki-sor1** [comment]
ご報告が遅くなってしまい、申し訳ありません。

Win 8.1 Chrome72.0.3626.121（64bit）／iPhone 7 Safariにて確認。
両環境ともに、選択されたテキストが自動的に囲われるのは、楽で良いと思います。

しかし、iPhone 7 Safariでは、テキストを部分的に選択しようとする度に、画面が左側（メニューボタン付近）に寄ってしまい、部分的にテキストを選択できませんでした。
（変更できたのはデフォルトで入っている一文のみで、そちらも全文選択でしか機能を試せませんでした）

**Comment by snext1220** [comment]
ご確認有難うございます。
こちら手元にiPhoneがないため、iPadで試してみたのですが、以前からの問題かもしれませんね...
＃エディター機能は見た目だけで内部的には入力ボックスではないので；

こちらは恐縮ですが、開発機能ということで、モバイル版は「可能な範囲の対応」ということでお許しいただけますとm(_ _)m
＃以前、TL上でモバイル環境で開発されている方がいらっしゃいましたが、基本機能としては動いているのでギリ許容範囲かなと...^^;
