### ISSUE TITLE
Playgroundのヘルプ追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#89]
追加したヘルプボタンをコンテキストメニュー化し、

+ Playground
+ SGMLリファ
+ GBATリファ

への直接アクセスを可能にします。現時点では本番仮（playground_new.aspx）のみ反映しています。

**Comment by toki-sor1** [comment]
Win 8.1／Chrome 71.0.3578.98（64 ビット）、iPhone 7／Safariにて確認。
正常に動作しました。
