### ISSUE TITLE
Playgroundのエディター自動補完

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#90]
Playgroundのエディターに、タグ／属性／設定値の自動補完機能を追加します。
文脈までは見ませんが、直入力するよりは役に立つのではないかと。

![default](https://user-images.githubusercontent.com/27911337/51437007-d98f3480-1cda-11e9-8cd5-6fc20564724b.png)

現在も本番仮で動作しますが、データがほとんど入っていないので、雰囲気のみ味わってください^^;

**Comment by snext1220** [comment]
主な予約語を入力し、本番反映いたしました！

**Comment by toki-sor1** [comment]
タグ追加ボタンを押した後、属性などはマニュアルを参照する必要があるので、何かいいアイデアはないかなぁと思っていましたが、これで解決ですね！　便利！！

Win 8.1／Chrome 71.0.3578.98（64 ビット）、iPhone 7／Safariにて確認。
PC環境では正常に動作しました。
スマホ環境は元々がシナリオ編集向けではないので問題はないかなと思うのですが、一応、こちらは自動補完できませんでした、とご報告。

**Comment by snext1220** [comment]
早速ご確認戴き、ありがとうございます～
自動補完機能はどこまで役立つかなと心配だったのですが、お役に立ったようでなによりです！
今後、もう少し手を入れてく予定ですが、お気づきの点あれば何なりとお願いしますm(_ _)m

スマホ＞はい～こちらは仰る通りモバイル環境での編集は考えにくいため＆キーボード処理上対応難しいため、ママでm(_ _)m
