### ISSUE TITLE
シナリオ情報のデータベース管理

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#94]
現在のサーバーでデータベース連携する見込みが立ったので、これまでできなかったことを徐々に対応していければと思っております。

具体的には、以下のものです。

### シナリオ単位のアクセス数

現在、汎用的なアクセスツールで賄ってはいますが、最大3か月しかデータがとれないので、永続的にカウントアップできる環境を、というのが目的です。

###  読者コメント入力機能

現在もSNSで賄えていますが、サイトとして受け口があるのは一定の意味があるかと。
ただ、優先順位は若干落ちるので、皆さんのリクエストを伺えればと。

### stext.xmlのデータベース化

前から出ていた話です。ただし、以前に一度wontfixになっている件で、運用面での課題もあるため、今回はとりあえず挙げているだけで、優先順位は一番低いと思います。

**Comment by snext1220** [comment]
あまり要望も出なかったので、このままなにもなければ、一旦はwontfix＆closeでいければと～

**Comment by toki-sor1** [comment]
### シナリオ単位のアクセス数
以前はアクセス数がプレイヤーさんの好みの把握やシナリオ作成の指針として活躍していましたが、テストプレイで頻繁にアクセスすることもあり、どこまでが本来のアクセス数なのか判断が難しいところもありましたね。
個人的には、アクセス数カウントは、評価や知名度が気になるSText初期を支え、現在ではSTextもじわじわと広まってきたことからも、役目を全うしたように感じていますので、廃案かなと思っています。

### 読者コメント入力機能
Twitterで各種コメント送信サービスのお話をお見掛けしますが、一部の悪意ある投稿の存在も無視できないといった印象を受けます。
勿論、メリットの方が遥かに多く、励まされている方々もよくお見掛けしていますので、読者コメント入力機能の実装を全面的に否定している訳ではありません。
しかし、健全な創作活動において、それを阻害するリスクが生じる可能性があることもまた事実です。

近年のゲームも緩いネット連携が主流のようで、意思疎通は定型文であったりとトラブル回避の傾向を強く感じていますので、もしSTextで読者が反応できる機能を設けるとすれば、「定型文もしくはTwitterのファボのようなものが気軽に反応できて丁度良い」のではと思いました。

### stext.xmlのデータベース化
より手軽に管理できるのは良いなぁと思う一方で、でも現在のように直接stext.xmlを編集する方法で事足りているという印象も。
個人的には、直接編集であまり不便は感じていないので、こちら廃案かな～と思っています。

**Comment by snext1220** [comment]
こちらもご意見ありがとうございます！
ほぼほぼ了解なので、以下はほぼ余談でございます～

### シナリオ単位のアクセス数

> どこまでが本来のアクセス数なのか判断が難しいところもありましたね。

まさに。一応、私のアクセスだけは除外する設定になっていたのですが、他の方のそれは識別できませんでしたので；（有償では可）とりあえず直近であれば、おおよそテストプレイのそれは視認できるので、今後も、その範囲でなんとなく反応の程度を把握していく感じですね^^;

### 読者コメント入力機能

> 一部の悪意ある投稿の存在も無視できない

まさに仰る通りかと！
アクセス数共々、gamebook.xyzさんの機能相当を想定していましたが、あまり無理することはありませんね（ちなみに、あちらは既製のソフトを利用されているようです）

> 定型文もしくはTwitterのファボのようなものが気軽に反応できて丁度良い

［いいね］程度ですかね～？単体での実装は若干割りに合わないので、他にデータベース機能を実装する際に合わせて検討できればなどと！

### stext.xmlのデータベース化

こちらも同意です！
尤も、こちらは、いずれは投稿から掲載までを完全自動化することも企んでおり、その際にまとめて対応できればとは（というか、その場合は対応せざるを得ない）。

＃現在、投稿フォーム／GitHubでメールよりは若干ハードルが下がった?とは思うのですが、やはり人手を介するのは結構精神的ハードルが高いかなと。ただ、現在の投稿数であれば、自動化開発まではというのもあったり、でも、自動化すれば投稿も増えるのか、という思いもあったりで…悩ましく；

**Comment by RYU-DS** [comment]
・シナリオ単位のアクセス数
プレイヤーも見れて選択の参考基準になるのが割りと一般的かと思いますが、より一層人気のあるものに偏ってしまうのが弱点で、絶対数を増やすのかバランスよく触れてほしいのかの目的で導入すべきかどうかが決まると思います。
自分は（プレイヤーも見れる）導入で。

・読者コメント入力機能
ちょくちょく言ってますが、どんな意見でもあった方がいいです。
それを取捨選択するのが受け取り側のやるべき事。
荒れるとまともな意見の人が寄り付かなくなる問題はありますが…
導入を強く希望します。

**Comment by snext1220** [comment]
こちらRYUさんのご意見を戴きましたので、ひと月wontfixを延ばして、他の方のご意見を待ちたいと思います。ご要望が多い場合には、検討してまいりたいと思います。

私の方は、現時点では、 @toki-sor1 さんのご意見にほぼ賛同というスタンス変わらずですかね^^;
https://github.com/snext1220/stext/issues/94#issuecomment-471252464
ご賛同得られれば、質問箱については公式サイトからもリンクしていきたいと思いますが、開発工数を鑑みても、まずはその程度から様子を見ても良いかな、というレベルです。
https://github.com/snext1220/stext/issues/106#issuecomment-478246222

**Comment by toki-sor1** [comment]
### シナリオ単位のアクセス数

確かにアクセス数が多いものは、読者側（利用者側）としては好奇心が刺激されることも多く、作品を見る動機の一つとなり得る要素ですよね。
それに、どのような作品（傾向）が読者に好まれているのか、というデータを得やすいところも魅力です。

ただ、RYUさんも懸念されているとおり、アクセス数が見えることで、更にアクセス数が偏りやすくなるという問題も出てきてしまうのですよね。

あと、アクセス数は **良くも悪くも「比較」対象となるデータ** でもあります。
個人的には、みんなが色々と気にせずにのびのびと創作できる環境作りという意味では、 **「アクセス数の一般公開はなし」が良いかなぁ** と思いました。

### 読者コメント入力欄

Twitterなどに慣れていると、気負わず＆気軽に反応できるものがあるといいなぁと思いますよね。
TLでも匿名でコメントを送れる質問箱やマシュマロなどは人気のようで、ご利用なさっている御方をよくお見掛けします。

既にリオさんが試験的に導入されていますが（ありがとうございます！）、私も **まずは質問箱で様子を見てみるのが良さそうかな** と思いました。
＃ある程度の利用者が見込めないと、システム開発が徒労に終わってしまう可能性もあるので；

暫く様子を見て、 **質問箱を続けるか・廃止するか・他のサービスを検討するか・定型文やファボのようなタイプに移行** などなど、決めていけたらいいですよね。

**Comment by cocotori** [comment]
・シナリオ単位のアクセス数

あれば個人的には嬉しいかなと思います。
ただ、たまに見るくらいで
日常的に運用することはないと思うので、
あってもなくても、どちらでも大丈夫です。


・読者コメント入力欄

なかなか悩みどころだと思います・・・
感想や意見を出してくれる人にもタイプがあって、
SNSでソフトに触れる方、
公式サイトに意見を投稿してくれる方、
ブログ等でガッツリまとめてくれる方などいるかと思います。
そういう方の意見をもれなく回収するためにも、
コメント入力欄はあったほうがいいような気はします。

ただ、あまり運用されなかった場合、管理するのも大変だと思うので、
投稿数との兼ね合いを見て、臨機応変に対応していく
必要はあるかなと思いました。


・stext.xmlのデータベース化

こちらあまりイメージが湧きませんでしたが、
自動投稿・掲載のための礎と言った感じですかね？
こちらはもうちょっと先の話でもいいのかなと思いました。

**Comment by snext1220** [comment]
ご意見有難うございます！
戴いたご意見への軽レスでございます～

#### シナリオ単位のアクセス数

一長一短という感じですね。
TLでは、時々気まぐれに4半期アクセス傾向を出していますが、その位の緩さで7割方の要件は満たしそうな気はします^^;（もしこんな情報も欲しいなどあれば、仰って戴ければ、その時に可能な範囲で合わせて流します～）。

なお、スタッフさんについては、内部ログへの共有idもお渡しできますので、もし細かなアクセス情報を把握したい場合はお知らせくださいm(_ _)m

#### 読者コメント入力欄

質問箱＞とりあえずサイトフッターからひっそりとリンクを貼ってたりします。Aboutページあたりでもう少しアピールしても良いかなとも思いますが、ご意見伺いつつ^^;

> システム開発が徒労～
> あまり運用されなかった場合、管理するのも大変だと思うので、～

ここですよね。。。
とりあえず一からのコーディングはそれなり大きいので、（少なくとも最初は）出来合いの掲示板を使うとしても、TwitterのTLにD、Issue×2と合わせて、日常的に見きれるかという話もあり；最初は誘い水的にも、スタッフ間でも意図して利用、なども考えると（使われてる形跡がないところに投稿もないと思うので）、一寸二の足ではあります^^;

#### stext.xmlのデータベース化

> 自動投稿・掲載のための礎と言った感じですかね？

はい、合わせてその後の管理もブラウザー上からできるための準備（＆編集競合を防ぐ）ですかね。そして、上のログ／コメント欄をシナ単位に管理するとなると、その前提にもなります。
＃現在、環境の関係でJavaScript、PHP、VBと複数環境を併用しているのですが、地味に、これ以上シナリオidが分散するのは辛いので、これをまとめる必要があります。

**Comment by snext1220** [comment]
本件、ひと月wontfixを見送っておりましたが、現時点で積極的に～というほどの意見が出ていませんので、June Updateのcloseタイミングでwontfixの予定です（基本は質問箱の設置のみ、ということになります）。これまで触れられていない理由など、追加でのご意見などある場合は、お早めにお願いいたします。
