### ISSUE TITLE
enemy要素へのhp属性の追加

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#95]
#57 にて @Salvadors-cabin さんのご要望を受けて、Issueを分離します。

---
複数回攻撃を与えるモンスター対応。

+ enemy要素にhp属性を追加（敵体力を設定）
+ hp属性が設定されている場合にはプレイ画面の敵リストに体力（テキストボックス）を表示
+ 敵体力は手動管理
+ 敵ダメ式を設ける（ボタンクリックで敵体力に反映）

ただし、横幅を結構とるので、正直辛くは。
使わないシナでは非表示にするにせよ、見た目があまりに異なるので混乱しそう。
今後のご要望を伺いながら、その度合いで決めていくことになるかと思います。

---

まずは上記箇条書きの前提で入れてみたいと思うので、ご意見あればお願いします。

**Comment by Salvadors-cabin** [comment]
「敵体力は手動管理」というのは、具体的にはどんな事をさしているのでしょうか。

**Comment by snext1220** [comment]
単に、テキストボックス上にhp属性の値を表示するのみで、自動計算はしない（＝hp更新はテキストボックスの書き換え）ことを想定しています。

こちらに自動計算を含めようとすると、更にenemy_func、enemy_attackなどの属性と、対応する表示枠を設けなければならないため、一寸厳しそうに思えた＆ラミディアを拝見する限り、敵hpの減算は比較的シンプルなので自動計算外でも問題なさそうに見えた、などが理由です。
＃仰るように、func式を非表示にすることも考えましたが、今度はhp対応しないシナでは表示がスカスカになるなぁと。

非互換更新が発生するのも何なので^^;、実装には、他の皆さん含めてご意見戴きながら、もう少し考えていきたいと思いますが、現状の想定は以上のとおりです。

**Comment by RYU-DS** [comment]
自分も現在ボスにHPを設定して、手動で減らしていく方法を検討中ですが…
自動計算で減らしてくれないなら、あまり意味が無いように思います。
実験的に互換性を維持する折半案として、現状の計算式からどこかの部分を敵に与えるDM数値として使用できるようにするのはどうでしょうか？
現状は「ダイス/敵攻撃力/自分攻撃力/フリー」から自分へのDMを算出していますが…
例えばこの中から「ダイス/自分攻撃力」のみを計算した数値を敵DMとして算出（自分へのDM計算と同時に）して＞敵HPから引く
といった感じです（もちろんどの数値を使用するかは設定できる）。

**Comment by snext1220** [comment]
現状の計算式から～は、コード側が複雑になる割に、制約は強い＆裏ルール的なものが増えそうなので、やや消極的です。

ボスに限られるならば、一般的な推奨としては「常闇」のようにFree欄をご利用いただければ、という話になってくるかとは思います（ドラスレに限定すると、難しいことは承知しているのですが；）。

こちらもフルセットとなると、敵リストを二行ワンセットとし、二行目に以下のような情報を詰め込む形になるのかなと（行単位の方が不要なシナで非表示にはしやすそう）。

+ hp（敵生命力）
+ enemy_func（敵へのダメージ式）
+ その他なにか？

ただ、あとから非互換更新が発生するのも良くないので（最小限にしたいので）、どの程度の機能が必要なのかは、もう少し皆さんのご意見を伺いたいところです。
＃最初からフルセットにするのは危険なので、できればスモールスタートはしていきたい。

**Comment by RYU-DS** [comment]
FREE欄をステ窓以外に設置できたらいいですねー
自分はそのスレですでにFREE3を使い切っているので、FREEの追加を希望しているのですが、希望（案）としては…

・①FREE4を敵に
・②FREE5をシーンに

①は表示スペースの問題はあるのですが、シナリオ作成側が従来の「自分DM用enemy」に加えて「敵DM用enemy（名前等簡素にしてスペースを確保する）」を設定する事で、ある程度解決が図れるかと思います。
②は表示スペースの問題は無いのですが、敵HP用途としてはボス戦などに限られます。
しかし、シーンカウントなど別用途にも使えるのが利点になるかと。
ただ、シーンに固定するのか？別シーンに移動しても表示し続けるのか？などの設定で大きく用途が変わってくるので、そこら辺の設定（の可不可も含めて）が複雑な部分もありますが。
例えばシーンに固定すると、何度も戻ってくる場所で特定の行動で変動させるなど、ギミックとして面白い使い方が出来ると思います。

自分は現在ボスのHP制にしか使う予定が無いので、別にどれでも問題無いですが。

**Comment by snext1220** [comment]
> FREE欄をステ窓以外に設置できたらいいですねー

実は、以下でこっそり?話題に挙がっていたのですが、不可視のFreeN（更新と条件に利用できるが、ステータスには表示されない）を考えていました。
https://github.com/snext1220/snext-management/issues/8#issuecomment-457509740

これらの不可視FreeNを #57 の

+ 文中へのボタン追加
+ 文中へのテキストボックス追加（一部は実装済み）

に対応させれば、ほぼできるようには思えます。

ただ、仰る通り、ボス用途に限定されてしまうので、他シナで雑魚敵相手にも利用したいとなると、悩ましいですね。

似たような機能が乱立するのを避けるためにも、他の皆さま含めて、用途の有無、雑魚／ボス用途など伺いながら、整理していければと思います。

**Comment by snext1220** [comment]
#160 でより包括的なリクエストがありましたので、そちらに議論を統合したいと思います。
