### ISSUE TITLE
デバッグモードでのエラーチェック

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#97]
+ デバッグモード時のエラーチェックを強化（主に、init要素など新機能）
+ New Playgroundのデバッグモード対応

ご執筆時に間違えやすい、またはチェックが難しいなどのポイントがあれば、自動チェックの項目を増やしていければと。ご要望あればお願いします（現在も一部はチェックしていますが、すべては困難なので、ご要望のあるものから対応していきます）。

**Comment by toki-sor1** [comment]
私が把握していないだけで、既に実装されていましたらすみません；
シーンの「アイテム」などで登録していないアイテムを設定すると、テストプレイ時に警告が出るのですが、リンクの「条件式」に登録していないアイテムなどを設定した時は警告が出ませんでした。

**条件式の方でも、登録情報と食い違いがあった時に警告が出ると良いかな** と思いました。
＃ただ、そうするとドラモードのように違うシナリオの実績を指定した時に警告が出てしまったりするのでしょうか？（その場合は現状ままでお願いします～）

**Comment by snext1220** [comment]
ご要望ありがとうございます！

はい、現在はご認識の通り、条件式に含まれるアイテムの不整合はノーチェックです。
属性と本文（条件式）は全く別物のしくみで、しかも本文の解析は手作業なので現時点では対象外としていました^^;

まだどういう形で実装していくかは未確認なのですが、まずは調査してみますので、暫しお待ちくださいませ。

＃ということで、本件はwontfixを外し、June以降の対応としていきますね。

**Comment by snext1220** [comment]
本件ですが、PgFlowの入力支援機能によって条件式の入力誤りを防ぎやすくなった点から、必要性が低下したように思えます。一旦、［Confirmed］にしたIssueではありますが、問題なければ［wontfix］にできればと思いますが、如何でしょうか。

＃ シナリオ作成時に間違いを引き起こしやすいなどの問題については、PgFlowにて対応していければと思いますので、お気軽にリクエスト願います（勿論、「いやいややはりデバッグモードで～」というご意見もありうると思っています^^;）。

**Comment by toki-sor1** [comment]
大変遅くなってしまい申し訳ありません；
仕様についてご説明いただき、また、実装についてもご検討いただき、ありがとうございました！

属性と本文のしくみは別物であることや、入力支援機能の実装で誤入力を防ぎやすくなったことから、本件は［wontfix］にしていただいて問題ありません！

> ＃ シナリオ作成時に間違いを引き起こしやすいなどの問題については、～

ありがとうございます！
これは間違いを起こし易そうかなと感じるような箇所がありましたら、その時はまたご報告やリクエストさせていただきますね～。

**Comment by snext1220** [comment]
ご了解戴き、ありがとうございます～
PgFlowにリソースを集中させるために、近頃結構wontfixしてますが、勿論他のツール、システム本体も引き続き強化していきますので、リクエストなんなりとです！

**Comment by cocotori** [comment]
すみません。そもそものところがわかっておらず申し訳ないです・・・
デバッグモードというのがよくわからないのですが、
どういった機能なのですか？

playgroundの画面から、なにか操作をするとデバッグモードに
移行するのでしょうか。

**Comment by snext1220** [comment]
Playgroundでのデバッグ支援機能になります。
詳しくは以下を参照戴けますと幸いですm(_ _)m

https://sorcerian.hateblo.jp/entry/20180125
［5］デバッグモードを利用する

**Comment by cocotori** [comment]
動作確認したときに上に表示されている枠のことだったのですね。
よく役立たせてもらっています。

エラーチェックについてはそうですね、
入力支援機能がありますので
この話題についてはwontfixで問題ありません！
