### ISSUE TITLE
バックアップ／リストア機能の統合

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#98]
メインゲーム画面に既存のバックアップ／リストア機能を統合します。
既にユーティリティで提供していますが、イマイチ利用されていないように思われるので、ゲーム画面に統合し、使い勝手を改善するのが目的です。

現在のコントロールパネルに［Backup＆Restore］ボタンを追加できればと思っております（現時点では以前の［Reload］ボタンで代替）。
お手数ではありますが、アイコンボタンの追加をご相談させて戴けますと幸いです★★★＞ @toki-sor1 さん
＃イマイチかもしれませんが、以下イメージです -> https://www.silhouette-illust.com/illust/26427

### 追記

従来のバックアップ／リストア機能とは別コードになりそうです（再利用できる部分はありますが、そのための修正も必要になりそう）。動作テストに当たっては、Utilityのバックアップ／リストア、ゲーム画面のバックアップ／リストア双方について、確認をお願いできますと幸いです。

**Comment by toki-sor1** [comment]
お待たせしました、［Backup＆Restore］ボタンの試作品を作成しました。
ボタン名を略してしまうと意味が分かりにくいので、2行＆色変えで対応しています。
![ctrl_backup_restore](https://user-images.githubusercontent.com/42646342/53636938-1f89d180-3c65-11e9-93c7-4c4af6f83365.png)
ファイル名は仮に「ctrl_backup_restore」としていますが、正式なファイル名が決まっているようでしたら、そちらに変更しますね。

**Comment by snext1220** [comment]
早速ありがとうございます！
イメージバッチリで、上下方向に矢印も補って戴いてありがとうございます。
とりあえず名前はctrl_backup.pngとさせていただき、GitHubには反映済みです（以降、こちらから上書き戴けますと幸いですm(_ _)m）。

以下気付いた点でございます。

+ 並んだ時に青文字が横に並んでいた方が良いので、上（Backup）が青の方が良いでしょうか？
+ 他のアイコンが62x62のため、統一をお願いしても宜しいでしょうか（今回は64x64）；
    + こちらでもサイズ変更したのですが、滲んだ感じになってしまい微妙だったので、ときのじさんの方でご覧戴いても宜しいでしょうか（お手数をおかけします...）

Newサイト共々、お手数をおかけしますが、引き続きよろしくお願いいたします。

**Comment by toki-sor1** [comment]
ご確認＆ご意見ありがとうございます！
イメージもバッチリと仰っていただけて安心しましたｗ
……が、しかし、あわわ、勘違いとサイズ変更ミス申し訳ありません……！

ctrl_backup.pngは、ご指摘いただきました箇所を修正し、GitHubにアップしました。
お手隙の際にご確認お願い致します～。

![ctrl_backup](https://user-images.githubusercontent.com/42646342/53652604-a8683380-3c8c-11e9-9a93-a425d222b6b8.png)

こちらこそ引き続きよろしくお願いします！

**Comment by snext1220** [comment]
ありがとうございます！
GitHub Pagesの方から確認しまして、問題ないと思います！！
こちら、これで確定してまいりますねm(_ _)m

**Comment by snext1220** [comment]
プレイヤーマニュアルも更新済みです。
https://sorcerian.hateblo.jp/entry/20171220

**Comment by cocotori** [comment]
確認しました。新しいアイコン、いいと思います！

動作も問題なさそうです。

一点、別のシナリオのバックファイルを選択してしまった場合も
通常と同様にリロードされますね。
多分、その場合は何も変化がない？感じかと思うので大丈夫なのですが、
ファイル名で判断して、別のは読み込めないようにしてしまうとかが
できると親切かと思いました。

**Comment by snext1220** [comment]
> 選択してしまった場合も通常と同様にリロードされますね。

ご確認有難うございます！
こちらマニュアルで言い訳していたのですが^^;、仰る通りの挙動の方が自然ですね。。先ほど修正し、本番／GitHub環境双方をUpdateしました。
＃マニュアルは別途修正予定です～

**Comment by toki-sor1** [comment]
Win8.1 Chrome 73.0.3683.86(64bit)から確認。正常に動作しました。

皆さんお疲れ様です。
ゲーム画面でのバックアップ／リストアは、 **プレイ中のシナリオのみというところが分かり易く、親切で良いですね。**
結果もきちんと表示されるので、プレイヤーさんの「もしかして別のシナリオにも影響が出てる？」という **不安も取り除けたのではないかと思いました。**

プレイヤーズマニュアルも確認しました。 
**内容も簡潔で分かり易くまとめられていて、良いと思います。**

**Comment by snext1220** [comment]
ご評価ありがとうございます！

判りやすく＞やはりデータ消えたら、的な怖さはありますよね^^;
あとは、そもそもUtilityに戻ってまでバックアップするか、といった問題もあり、正直、あまり使われていない感があったもので、今回対応してみました。

これでバックアップも前提に、どんどん思い切って死にゲーも出てくれば良いなとｗ
