### ISSUE TITLE
タイトル／メタ情報／Twitterカードの反映

### ISSUE THREAD

**Issue by snext1220** [snext1220/stext#99]
SEO/SEM対策で、以下の方策を追加します。

+ シナリオのタイトルをタブに反映
+ キーワード／紹介文をメタ情報としてページに反映
+ 伴い、intro要素にkeywords属性を追加（紹介文はdescriptionを転用）
+ Twitterカードにシナリオ情報を反映

### Twitterカード（メモ）

```
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@snext1220" /> 
<meta property="og:url" content="記事のURL" />
<meta property="og:title" content="記事のタイトル" />
<meta property="og:description" content="記事の要約" />
<meta property="og:image" content="画像のURL（intro.png）" />
```

**Comment by snext1220** [comment]
現状、タイトル／メタ情報のみ対応完了です。
Twitterカードについては、プログラムの都合上、サーバーサイドでの対応が必要になるため、若干後回しにさせて戴くかもしれません。

**Comment by toki-sor1** [comment]
Win8.1 Chrome 73.0.3683.86(64bit)／iPhone7 Safariから確認。
**タイトルもシナリオ毎に表示されるようになり、タブからぱっと把握し易いのも良いですね。**

お恥ずかしい話ながら、まずはメタ情報、keywords属性について調べていました。
データについて説明するデータであったり、検索ページに表示する情報のことだったのですね。
検索すると長文が中略されていて、内容が分かり辛いものもあるので、 **こちらは簡潔にまとめられた情報が表示されるところが良いと思います。**

現在メタ情報が含まれている「新・王さま～（Stextゲーム画面）」が検索結果に出てこないのですが、 **こちらは検索エンジンに反映されるまで時間が掛かる、ということなのでしょうか？** （勘違いしていたらすみません；）

Twitterカードもお恥ずかしい話ながら（中略）。
Twitter上でも既に表示されるようになっていますね。遅ればせながら、ご対応お疲れ様でした！
画像の表示方法は2種類ほどあるようですが、 **現在採用されている表示の仕方の方が、スッキリとしていて見易いですね。良いと思います。**

**Comment by snext1220** [comment]
ご確認と仕様前提の調査お疲れ様です＆ありがとうございます！

メタ情報ですが、スミマセン、現時点で検索エンジンに反映されていないようですね...（アクセス分析の方では見えているのですが）どうもプログラムで動的に生成しているテキストが検索エンジンから認識できないようです（Twitterカードも同じく）

こちらを改善するには、サーバー側で別のコードを組んでやる必要がありそうです。
若干時間もかかりそうなので、大変申し訳ないのですが、June Update以降に持ち越していければと。
お待ち戴けますと幸いですm(_ _)m

**Comment by snext1220** [comment]
とりあえず暫定ではありますが、Twitterカードについてはシナリオごとに表示されるようになったかと思います。ただ、問題が結構残っているので、引き続き対応してまいります^^;
https://twitter.com/yy7512/status/1112246104936964096

**Comment by snext1220** [comment]
#107 とも関連しますが、Google sitemap.xmlにも対応し、サーバーサイドでぺージを組み立てるように修正したので、数日内で検索エンジンにも反映されるのではないかと。気長にお待ちいただけますとm(_ _)m

**Comment by toki-sor1** [comment]
ご対応お疲れ様です＆ご返信ありがとうございます！
先程「少女英雄」でテストを行い、 **Twitterカードが正常に表示されているのを確認しました。**
https://twitter.com/toki_s1/status/1112374900340092933

＃リオさんが貼ってくださったツイート（https://github.com/snext1220/stext/issues/99#issuecomment-478317094 ）ですが、「このページは存在しません。」と表示されてしまいました；

keyword属性の追加に伴い、ツイート用の紹介文にも追記しています **（GitHub、本番環境ともにscenario.xml更新済み）**。
Twitter上だと呟くまで内容が反映されているか分かりませんが、 **Card validator** （https://cards-dev.twitter.com/validator ）なら呟く前に内容が分かるのですね。
今回呟いた直後には、まだ追記前の紹介文だったので、今後はCard validatorを利用して内容に不備がないか確認しようかなと思っています。

**参照記事** ： https://saruwakakun.com/html-css/reference/twitter-card ）
＃前に同じページを見ていたのですが、このチェックについては見落としてました；

> #107 とも関連しますが、Google sitemap.xmlにも対応し、サーバーサイドでぺージを組み立てるように修正したので、数日内で検索エンジンにも反映されるのではないかと。気長にお待ちいただけますとm(_ _)m

Google sitemap.xml対応前は、メタ情報について上手く表示されない問題が起こっていたのですね；
こちらもご対応お疲れ様でした！　**数日後に改めて検索してみようと思います！**

**Comment by snext1220** [comment]
おぉ、失礼しました！
テストツイートだったもので、その後、本ツイートを出した時に反射的に消してしまっておりました；該当コメントも新たなツイで置き換えました^^;

> Card validator （https://cards-dev.twitter.com/validator ）なら～～

はい、こちらで一旦表示させてから呟くと、ＴＬではリアルタイムにカードが最新で認識されるので（特に画像は若干タイムラグがあるようです）、そうした意味でも有効です！（て、私からもご案内しておけばと、あとから；ご案内有難うございます～）

> Google sitemap.xml対応前は、メタ情報について上手く表示されない問題～～

こちらは複数の問題が錯綜しており、そもそもsitemap.xml前はまともにGoogleがページを認識できていなかったようです（一部、ブログなどでリンクしていたものだけを認識）；メタ情報はそれとは別にサーバー対応で認識されるように…て、ゴチャゴチャしてますね；；

ただ、（当たり前なのですが）アプリで動的にテキストを生成しているので、SEO的に弱いのは依然として間違いなく。根本的にどうすべきかは悩ましいところです。。
＃検索エンジン的には、紹介文だけが裏にある空ページにしか見えていないので；

**Comment by snext1220** [comment]
ボチボチと検索エンジンにも反映されている感じですね（一部）。
ただ、やはり直接のリンクがないと、かなり弱い、という印象なので、ぜひご自分のブログなどでもリンク付きでシナリオ紹介してくださると、助かりますm(_ _)m

新時代～では、目次ページを兼ねて、以下のような投稿を立ち上げました。
https://sorcerian.hateblo.jp/entry/2019/04/02/101343
まだ暫定なので、スタッフさんシナ、ゲストさんシナでページをわけて、紹介文も軽く追加の予定です。

**Comment by cocotori** [comment]
twitterカード、投稿テストしてみました。
タイトルや絵が載るのがいいですね！

ブログの方はまだ試してませんが、リンクだけでなくて
絵や紹介文が出るの、結構ありがたいので
今度試してみたいと思います。

**Comment by snext1220** [comment]
早速お試しいただき、ありがとうございます～
はい、当初思ってた以上に良い感じになってるのでｗ、是非活用してやってください！

ブログ＞はい、現在、SEO対策をしきりと施してますが、他のサイトからのリンクが一番大きいので、是非宣伝方々、引用してやっていただけますと…！
